### ISSUE TITLE
form触发onFinish的时候，假如校验失败会有一瞬间高度塌陷

### ISSUE THREAD

**Issue by laii7** [ant-design/ant-design#36613] opened 2022-07-20 08:48 UTC
### Reproduction link

[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce

直接点击submit

### What is expected?

高度不塌陷

### What is actually happening?

高度会塌陷

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | react18 |
| System | macos big sur 11.6.5 |
| Browser | 103.0.5060.114 |

---
任意一个有校验规则的form如果校验不通过都会出现这个高度塌陷的问题
开发环境没问题，发布生产就会有这个问题

**Comment by afc163** [comment] 2022-07-20 08:58
Duplicate of #36470

**Closed by afc163** 2022-07-20 08:58 UTC
