### ISSUE TITLE
TreeSelect 自定义数据结构无法回显

### ISSUE THREAD

**Issue by kaysonwu** [ant-design/ant-design#30247] opened 2021-04-21 08:10 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-w7528?file=/index.js:523-540)

### Steps to reproduce
1. 运行重新链接
2. 查看 `treeData` 变量的数据结构

### What is expected?
可以正常运行

### What is actually happening?
选中后无法正常把选中的项回显到 input 里面

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | latest |
| System | windows 10 |
| Browser | latest |

---
经常跟后端对接 `id` 是最长打交道的，但目前 TreeSelect 仅支持 `value` 字段名，请增加个属性让其不再限制 `value` 的字段名

**Comment by afc163** [comment] 2021-04-21 08:23
Duplicate of #24282

**Closed by afc163** 2021-04-21 08:23 UTC

**Comment by kaysonwu** [comment] 2021-04-21 11:21
临时解决方案：

```typescript
import React, { ReactElement } from 'react';
import { TreeSelect as Select } from 'antd';
import { TreeSelectProps as Props } from 'antd/lib/tree-select';
/* eslint-disable-next-line import/no-extraneous-dependencies */
import { DataNode } from 'rc-tree-select/lib/interface';

interface TreeSelectProps<T> extends Props<T> {
  treeNodeValueProp?: string;
}

const TreeSelect = <T extends object = {}>(
  {
    treeNodeLabelProp = 'title',
    treeNodeValueProp = 'value',
    treeData,
    ...props
  }: TreeSelectProps<T>,
): ReactElement => {
  const renderTree = (data: DataNode[] | undefined) => data?.map(item => (
    <Select.TreeNode value={item[treeNodeValueProp]} title={item[treeNodeLabelProp]}>
      {renderTree(item.children)}
    </Select.TreeNode>
  ));

  return (
    <Select {...props}>
      {renderTree(treeData)}
    </Select>
  );
};

export default TreeSelect;
```
