### ISSUE TITLE
Switch pin position not correct

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#24237] opened 2020-05-18 02:23 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wenzihetubiao-ant-design-demo-jh0vz?file=/index.js)

### Steps to reproduce
See reproduce

### What is expected?
Work as brefore

### What is actually happening?
Pin not correct

| Environment | Info |
|---|---|
| antd | 4.2.3 |
| React | latest |
| System | IOS |
| Browser | chrome |

**Comment by zombieJ** [comment] 2020-05-18 02:53
ref https://github.com/ant-design/ant-design/pull/24122

**Comment by yoyo837** [comment] 2020-05-18 03:19
相关的 #24226

**Comment by afc163** [comment] 2020-05-18 04:13
Duplicate of #24226

**Closed by afc163** 2020-05-18 04:13 UTC
Labels: 🐛 Bug, 👷🏻‍♂️ Someone working on it
