### ISSUE TITLE
table添加scroll属性后，折叠sider卡顿

### ISSUE THREAD

**Issue by ssvh** [ant-design/ant-design#31878] opened 2021-08-23 09:17 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-chu-fa-qi-antd-4-16-12-forked-ldily)

### Steps to reproduce
table添加scroll属性后，折叠sider很卡，即使只设置的scroll-y

### What is expected?
和没有添加scroll属性一样流畅

### What is actually happening?
卡顿

| Environment | Info |
|---|---|
| antd | 4.16.12 |
| React | 17.0.0 |
| System | win10 |
| Browser | 火狐developer 92.0b4 |

**Comment by afc163** [comment] 2021-08-23 09:21
Duplicate of #27775

**Closed by afc163** 2021-08-23 09:21 UTC
