### ISSUE TITLE
antd form has error displayed and then disappeared when use Chinese input in Safari browser

### ISSUE THREAD

**Issue by franklingu** [ant-design/ant-design#25223] opened 2020-06-25 11:57 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hhvq4)

### Steps to reproduce
select chinese input
type "miaoshu" and then space
now observe the input

### What is expected?
there should be not error message about required showing up at all

### What is actually happening?
after 描述 is inputed, it first shows the error msg that this field is required then the error msg disappears

| Environment | Info |
|---|---|
| antd | 3.26.16 |
| React | 16.8.6 (or latest one) |
| System | mac 10.14.6 |
| Browser | Safari Version 13.1.1 (14609.2.9.1.3) |

**Comment by franklingu** [comment] 2020-06-25 11:59
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4099698/85715824-6afba500-b71e-11ea-8109-7347018ef568.gif)

**Comment by afc163** [comment] 2020-06-28 13:13
Duplicate of #19944

**Closed by afc163** 2020-06-28 13:13 UTC
Labels: 3.x
