### ISSUE TITLE
Tabs do not dynamically handle container width

### ISSUE THREAD

**Issue by Ehesp** [ant-design/ant-design#7231] opened 2017-08-16 12:02 UTC
### Version
2.12.6

### Environment
Chrome 60

### Reproduction link
[https://codepen.io/anon/pen/YxEBZM?editors=001](https://codepen.io/anon/pen/YxEBZM?editors=001)

### Steps to reproduce
1) Ensure the window width is wider than the tabs (so no arrows appear).
2) Scale the window size until they overlap the tabs
3) Click a tab, they jerk and now show arrows

Window bigger than tabs:
![image](https://user-images.githubusercontent.com/842078/29362236-106bc4bc-8283-11e7-84d7-fecb580871eb.png)

Window resized to be smaller than tabs:
![image](https://user-images.githubusercontent.com/842078/29362252-1b3db18e-8283-11e7-9611-46e8098e9e58.png)

When clicking a tab, the arrows now appear:
![image](https://user-images.githubusercontent.com/842078/29362263-26ff081a-8283-11e7-8996-f172727a053b.png)

### What is expected?
I'd expect the arrows to appear dynamically if the window width comes inside of the tabs with, without the need to click a tab or refresh the page.

### What is actually happening?
They're not dynamically handling the window width.

**Comment by afc163** [comment] 2017-08-16 12:14
Duplicate of #7210

**Closed by afc163** 2017-08-16 12:14 UTC
