### ISSUE TITLE
When ant design has own rich text editor? 

### ISSUE THREAD

**Issue by julin69** [ant-design/ant-design#10255] opened 2018-04-26 02:19 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We need a rich text editor to solve html edit problem,but other plugins is not suit for ant-design,and has a lot of problems

### What does the proposed API look like?
I need a rich text editor with less config,and can edit freely

**Comment by yesmeck** [comment] 2018-04-26 02:37
Duplicate of #1083

**Closed by yesmeck** 2018-04-26 02:37 UTC

**Comment by TRamainoane** [comment] 2023-02-16 17:51
nn

**Comment by MyIvory** [comment] 2023-04-09 12:22
### 

> [`_****_`](url)
