### ISSUE TITLE
Input value for search filter shouldn't disappear in Select Component (multiple mode)

### ISSUE THREAD

**Issue by alsikora** [ant-design/ant-design#9369] opened 2018-02-16 10:49 UTC
### What problem does this feature solve?
Typing phrase in the Selector with multiple mode allow me to filter the results. After selecting the one of the options, search criteria disappears and when I want to select other option with the same phrase I have to type it again. 

I'd like my search criteria to remain in the selector, so that I could easily select all related things without having to re-type it.

This would be great user experience feature for Select component with ```mode="multiple"```

### What does the proposed API look like?
```javascript
<Select
    showSearch
    optionFilterProp="children"
    filterOption={this.filterList}
    mode="multiple"
    permanentFilter
```

permanentFilter - type: boolean

**Comment by yesmeck** [comment] 2018-03-14 12:51
Duplicate of #9573

**Closed by yesmeck** 2018-03-14 12:51 UTC
Labels: Component: Select
