### ISSUE TITLE
TimePicker doesn't showing up with locale aware formats that contains time ( Ex: LLL )

### ISSUE THREAD

**Issue by mhmt** [ant-design/ant-design#31142] opened 2021-06-25 21:20 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/choose-time-antd4165-forked-yq72d?file=/index.js)

### Steps to reproduce
Add two date pickers. Add showTime prop true for both. 1 datepicker with format="LLL" and other's format="D MMMM YYYY HH:mm". You cannot select time with LLL formatted datepicker but you can see the time.

### What is expected?
User should be able to select time with locale aware formats like LLL that contains time section. 

### What is actually happening?
LLL format actually contains time section. But DatePicker is not controling this type of formats.
https://github.com/ant-design/ant-design/blob/399f073001cbaad06a8dcc8d66e487295c724458/components/date-picker/generatePicker/index.tsx#L31

| Environment | Info |
|---|---|
| antd | 4.16.5 |
| React | 16.14 |
| System | Windows |
| Browser | Chrome 91 |

**Comment by afc163** [comment] 2021-06-27 05:36
Duplicate of #27777

**Closed by afc163** 2021-06-27 05:36 UTC
