### ISSUE TITLE
Popconfirm包裹的button被禁用时还是出现Popconfirm

### ISSUE THREAD

**Issue by gc654321** [ant-design/ant-design#13932] opened 2018-12-26 07:58 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
win7，谷歌最新版本

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/92o7490yj4)

### Steps to reproduce
点击删除

### What is expected?
不会弹出Popconfirm

### What is actually happening?
弹出Popconfirm

**Comment by afc163** [comment] 2018-12-26 08:41
Duplicate of #13351

**Closed by afc163** 2018-12-26 08:41 UTC
