### ISSUE TITLE
新建项目@types/react 16.8.13 Button的ts类型错误 16.8.12正常

### ISSUE THREAD

**Issue by jieny** [ant-design/ant-design#16042] opened 2019-04-12 02:42 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/facebook/react/](https://github.com/facebook/react/)

### Steps to reproduce
create-react-app xxx --typescript
yarn add antd
使用Button

### What is expected?
无类型错误

### What is actually happening?
TypeScript error: Type '{ children: string; type: "primary"; htmlType: "button"; }' is missing the following properties from type 'Pick<Pick<(Readonly<AnchorButtonProps> & Readonly<{ children?: ReactNode; }>) | (Readonly<NativeButtonProps> & Readonly<{ children?: ReactNode; }>), "defaultChecked" | "defaultValue" | ... 257 more ... | "block"> & Pick<...> & Pick<...>, "defaultChecked" | ... 256 more ... | "prefixCls">': defaultChecked, defaultValue, suppressContentEditableWarning, suppressHydrationWarning, and 252 more.  TS2740

    22 |             Learn React
    23 |           </a>
  > 24 |           <Button type="primary" htmlType="button" >Primary</Button>
       |            ^
    25 |         </header>
    26 |       </div>
    27 |     );

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | chrome |

**Comment by afc163** [comment] 2019-04-12 02:46
<img width="639" alt="image" src="https://user-images.githubusercontent.com/507615/56008860-48938c80-5d10-11e9-8628-76dedd7acdf3.png">

**Comment by afc163** [comment] 2019-04-12 02:47
Duplicate of #15930

**Closed by afc163** 2019-04-12 02:47 UTC
