### ISSUE TITLE
Icon组件在TypeScrpt中使用报缺少“translate”属性

### ISSUE THREAD

**Issue by mxt142114** [ant-design/ant-design#23479] opened 2020-04-22 07:19 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost:4000/无连接](http://localhost:4000/无连接)

### Steps to reproduce
通过import { PlusOutlined} from '@ant-design/icons';引入组件，使用方式为：<PlusOutlined />，在js中没问题，但是在ts文件中会报缺少“translate”属性，请问这种引入方式是按需加载的还是全量引入的

### What is expected?
在ts文件中使用无问题

### What is actually happening?
在ts文件中会报缺少“translate”属性

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.12.0 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment] 2020-04-22 07:20
Duplicate of #23266

**Closed by afc163** 2020-04-22 07:20 UTC
