### ISSUE TITLE
Select.Option: property "value" should not support type "string" only 

### ISSUE THREAD

**Issue by lvlw** [ant-design/ant-design#6883] opened 2017-07-18 08:12 UTC
### What problem does this feature solve?
In actual development, "number" and even "object" are all types that may be used.

### What does the proposed API look like?
https://ant.design/components/select/#Option-props  
the type of property "value" should be "string | number | object".

**Comment by afc163** [comment] 2017-07-18 08:26
Duplicate of #2857

**Closed by afc163** 2017-07-18 08:26 UTC
