### ISSUE TITLE
TreeSelect 为了去除Bug移除了键盘导航功能也是醉了，应该恢复。

### ISSUE THREAD

**Issue by meseme** [ant-design/ant-design#33737] opened 2022-01-17 00:39 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
TreeSelect 为了去除Bug移除了键盘导航功能，这种解决Bug的方式着实另人费解。希望能恢复这个功能。[Bug描述详见](https://github.com/ant-design/ant-design/issues/33161#issue-1071036139) 

### What does the proposed API look like?
恢复键盘导航功能

**Comment by afc163** [comment] 2022-01-17 02:36
Duplicate of #33161

**Closed by afc163** 2022-01-17 02:36 UTC
