### ISSUE TITLE
[react18] Menu 组件子项存在children时可能会出现鼠标移入另一项时前一项不消失

### ISSUE THREAD

**Issue by chenyueban** [ant-design/ant-design#35527] opened 2022-05-13 01:02 UTC
### Reproduction link

[https://stackblitz.com/edit/react-ts-44qq5y?file=App.tsx](https://stackblitz.com/edit/react-ts-44qq5y?file=App.tsx)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/27852165/168191584-5d2db0a0-dea9-441b-8d12-cfb1f6ef07cd.png)

如图 从 user item bill这个子item的children出来时，鼠标移入Team item 这时候前一项 user item 不会消失

### What is actually happening?

 

| Environment | Info |
| --- | --- |
| antd | 4.20.4 |
| React | 18.1.0 |
| System | windows11 |
| Browser | Chrome 101.0.4951.54 |

**Comment by afc163** [comment] 2022-05-13 02:12
Duplicate of #35212

**Closed by afc163** 2022-05-13 02:12 UTC

**Comment by Renderz** [comment] 2022-08-30 09:13
> Duplicate of #35212

这个问题有什么进展么？
