### ISSUE TITLE
5.2.3版本内  #40933 这个pr新增的suffixCls 属性  在react被认定为是一个 无效的props 导致警告

### ISSUE THREAD

**Issue by Ruler1020730** [ant-design/ant-design#40988] opened 2023-03-01 07:35 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-qy91ps?file=/index.js)

### Steps to reproduce

使用Layout组件就会显示警告

### What is expected?

警告消失

### What is actually happening?

react-dom.development.js:86 Warning: React does not recognize the `suffixCls` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `suffixcls` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

| Environment | Info |
| --- | --- |
| antd | 5.2.3 |
| React | 18.2.0 |
| System | MacOS 13.0.1 (22A400) |
| Browser | 109.0.5414.119 |

**Comment by zombieJ** [comment] 2023-03-01 07:37
Duplicate of #40968

**Closed by zombieJ** 2023-03-01 07:37 UTC
Labels: unconfirmed

**Comment by LeoHuang520** [comment] 2023-03-02 03:33
This problem IS NOT FIXED !!! @zombieJ

**Comment by yoyo837** [comment] 2023-03-02 03:39
> This problem IS NOT FIXED !!! @zombieJ

Duplicate of #40968
