### ISSUE TITLE
Table component - child table and fixed the parent table right column when expand child column, the right column icon position changed (If the column on the right side of the fixed subtable is invalid )

### ISSUE THREAD

**Issue by zjmzy1001** [ant-design/ant-design#12721] opened 2018-10-19 01:24 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Use table component child table and fixed column function at the same time

### What does the proposed API look like?
Can use both the parent and child tables and the fixed right column function
![default](https://user-images.githubusercontent.com/38421105/47192616-cf2e6900-d380-11e8-9558-8f8530b8be57.png)
![default](https://user-images.githubusercontent.com/38421105/47192617-cf2e6900-d380-11e8-9bf8-448c177be0b8.png)
![default](https://user-images.githubusercontent.com/38421105/47192618-cfc6ff80-d380-11e8-8430-727a8f93387c.png)

**Comment by afc163** [comment] 2018-10-19 02:50
Duplicate of #9900

**Closed by afc163** 2018-10-19 02:50 UTC
