### ISSUE TITLE
[4.0] Using Select's autoFocus on Table filter scrolls user to top of page

### ISSUE THREAD

**Issue by mikeyshing88** [ant-design/ant-design#22864] opened 2020-04-02 10:39 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/customized-filter-panel-ant-design-demo-clwjy)

### Steps to reproduce
1) Create a `Table` with a custom filter dropdown using `Select` component - and apply `autoFocus`
2) Ensure the table is not rendered at the top of the page so that you can scroll down to view it
3) Open the column filter dropdown

Refer to reproduction link

### What is expected?
The page should not scroll to the top when opening the filter

### What is actually happening?
Page is scrolling back to the top when opening the filter

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | Latest |
| System | MacOS |
| Browser | Chrome |

---
Seems like we would need to be able to target the `input` ref and apply something like `inputRef.current.select()`.

We could potentially add a prop like `getInputRef` on `Select` to target the inner `input` in `rc-select`.

I've made some changes here to my `rc-select` fork which may or may not be a solution: https://github.com/mikeyshing88/select/commit/2c9cb348e763cf0a9d9a9908f91546dfc394278c

**Comment by zombieJ** [comment] 2020-04-02 10:45
Duplicate of #20575

**Closed by zombieJ** 2020-04-02 10:45 UTC

**Comment by mikeyshing88** [comment] 2020-04-02 10:52
@zombieJ Thanks for that!

Just another question, if I use `3.0` in the reproduction code I gave above, the scrolling does not happen (ie: https://codesandbox.io/s/customized-filter-panel-ant-design-demo-clwjy ). Any idea why it works fine in `3.0`?

**Comment by mikeyshing88** [comment] 2020-04-02 11:31
So the same thing happens with using an `Input` as the filter instead of `Select`.

Reproduction: https://codesandbox.io/s/customized-filter-panel-ant-design-demo-7hywz

Notice that if we use `autoFocus` prop (or `.focus()` method), the page will scroll back to to the top.

However, if we use `.select()` method, it works as expected (remove `autoFocus` prop and uncomment the commented out code to see it working).

**Comment by jayeshchoudhary** [comment] 2021-03-10 07:52
thanks 

> @zombieJ Thanks for that!
> 
> Just another question, if I use `3.0` in the reproduction code I gave above, the scrolling does not happen (ie: https://codesandbox.io/s/customized-filter-panel-ant-design-demo-8hep2 ). Any idea why it works fine in `3.0`?
> 
> Update:
> 
> Actually, it looks like in `4.0`, the filter element does not append until the user opens it - so I do not think `position: fixed` would solve this issue?

thanks man solved my problem

**Comment by wesleymostien** [comment] 2021-12-02 17:47
For a select I check if it is in view before trying to focus it:


`  

import { useInView } from 'react-intersection-observer';


    const { ref: refDropdown, inView } = useInView();

useEffect(() => {
        if (!inView) return;
        refSelectCondition.current?.focus();
    }, [inView]);`
