### ISSUE TITLE
RangePicker Initial month for right panel

### ISSUE THREAD

**Issue by wwan5803** [ant-design/ant-design#18135] opened 2019-08-07 05:27 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
As we disable the date after current date, which will make show next month on the right panel meaningless. So instead of showing current month on the left panel in RangePicker, we want to show the previous month on left panel and this month on the right side. 
![Screen Shot 2019-08-07 at 3 21 35 pm](https://user-images.githubusercontent.com/6858452/62597019-f104d680-b927-11e9-8f2a-7c64d1f86bb7.png)
![Screen Shot 2019-08-07 at 3 21 45 pm](https://user-images.githubusercontent.com/6858452/62597022-f3ffc700-b927-11e9-9852-571fcf7d15e5.png)

### What does the proposed API look like?
`<RangePicker value={[null, null]} initialMonthForLeftPanel={}/>`

**Comment by afc163** [comment] 2019-08-08 15:24
Duplicate of #15360

**Closed by afc163** 2019-08-08 15:24 UTC

**Comment by Balderrama** [comment] 2019-11-14 03:50
i'm having the same problem i can't control the months that are showed on the calendar

step 1:
I select the range of dates
let's say i selected 11/10/2019 - 11/13/2019 // MM-DD-YYYY

step 2:
if i open the calendar and navigate through it and change the month, let's say i moved to september and without select any date i close the calendar.

step 3:
If i open again the calendar it shows the month of september instead of show november which is the date i have selected.

To sum up based on the range of dates selected i need to show those months when i open the calendar

thanks in advance.
