### ISSUE TITLE
Button.fixTwoCNChar shouldn't check text from DOM

### ISSUE THREAD

**Issue by rinick** [ant-design/ant-design#21160] opened 2020-01-31 09:09 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://github.com/ant-design/ant-design/blob/3ee0e4a58e0f93aaf3cec89dad1488c7a060ef02/components/button/button.tsx#L184

Inside Button.hasTwoCNChar, it reads buttonNode.textContent and buttonNode.innerText.
reading value from dom would force browser to re-layout and recalculate-style.

my testing page renders 10% faster just by removing fixTwoCNChar function from antd.  not because I use a lot of Buttons,  but because fixTwoCNChar breaks things that can originally be done in one browser layout into 2 or 3 re-layout

### What does the proposed API look like?
since the component already has these information during render(), it should be more efficient to parse the ReactNode to search for CNChar during render() rather than read the text from dom afterwards

**Comment by zombieJ** [comment] 2020-02-02 09:18
We can remove this check when ConfigProvide close this ability.

**Closed** 2020-02-02 10:03 UTC
Labels: improvement

**Comment by rinick** [comment] 2020-02-04 05:51
@zombieJ disable it with config is nice, but I think this is still an issue that needs to be truly fixed.

please check my benchmark pages

original, super slow: https://rinick.github.io/antd-performance/button-performance.html
remove fixTwoCNChar: https://rinick.github.io/antd-performance/no-fixTwoCNChar.html

You wont see this issue if everything is done in initial render, it only happens when children component are updated asynchronously, this usecase is common when page is driven by server data.

Actually you don't need hundreds of buttons to reproduce this bug, when Button calls fixTwoCNChar at certain time it force the browser to layout for an extra time. if other part of the page is heavy, one single button can make the page render 50% slower.

**Comment by zombieJ** [comment] 2020-02-04 06:17
Since this is by design to make one space in 2 Chinese char, we may not adjust this logic currently. That's why to improve the logic to skip when ConfigProvider disable insert space.

**Comment by rinick** [comment] 2020-02-04 06:29
> Since this is by design to make one space in 2 Chinese char, we may not adjust this logic currently. That's why to improve the logic to skip when ConfigProvider disable insert space.

Why not check reactNode directly? this doesn't have to be read from DOM. I actually tried to make a PR, but I have some issue setting up my  enviroument to compile the latest version of antdesign :(

**Comment by zombieJ** [comment] 2020-02-04 06:49
User may wrap node with HOC:

```jsx
const Wrapper1 = props => <span>确定</span>;

<Button><Wrapper1 /></Button>
```

**Comment by rinick** [comment] 2020-02-04 08:10
@zombieJ
OK, after some further research,  I find textContent actually won't cause a re-layout, only innerText will

Now it makes sense since my application mostly use icon buttons.

So I strongly suggest to remove innerText from there
if textContent  is null or blank, innerText is always null, except for IE <= 8

**Comment by paranoidjk** [comment] 2020-02-24 04:00
![image](https://user-images.githubusercontent.com/7971415/75128030-2541b800-56fd-11ea-95e2-e45541b01fab.png)

@zombieJ  can we cherry pick this performance fix to branch v3?

**Comment by afc163** [comment] 2020-02-24 04:10
@paranoidjk done

https://github.com/ant-design/ant-design/commit/e85ec40c9afc335c5b3aef8195b16140aa9b771f
