### ISSUE TITLE
 getPopupcontainer component is only executed the first time the select is clicked

### ISSUE THREAD

**Issue by Toril92** [ant-design/ant-design#30577] opened 2021-05-18 14:43 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/long-fog-1l6wr?file=/src/index.js)

### Steps to reproduce
To pass the getPopupContainer property to the select. Expand the options several times, it will be seen that the getPopupContainer function is only called the first time

### What is expected?
It is expected that every time the select is clicked to display the options, getPopupContainer is called.

### What is actually happening?
getPopupContainer is only called the first time

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 16.13.1 |
| System | Windows 10 Pro 20H2 |
| Browser | Opera GX LVL 2 (core: 75.0.3969.259) |

---
This bug does not allow changing the attach node of the options after opening it once and if a scroll appears on the screen we cannot adjust the options to the new scenario

![GIF2](https://user-images.githubusercontent.com/36948842/118671880-1fe7f600-b7f8-11eb-9e88-774a1e14d835.gif)

**Comment by afc163** [comment] 2021-05-19 02:41
Duplicate of #26071

**Closed by afc163** 2021-05-19 02:41 UTC
