### ISSUE TITLE
Fixed columns inline style height does not fit the unfixed columns height

### ISSUE THREAD

**Issue by thanhtunguet** [ant-design/ant-design#19684] opened 2019-11-12 04:50 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-hbfgy?fontsize=14)

### Steps to reproduce
- Make one or more very first columns on the left side of table, the others are unfixed
- Set `scroll.x` to a big enough number

### What is expected?
The table is displayed perfectly like the example `[Fixed columns and header](https://antd.thanhtunguet.info/components/table/#components-table-demo-fixed-columns-header)` in the documentation

### What is actually happening?
The fixed columns height is bigger than the others height, maybe smaller (not sure)

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16.8.6 |
| System | Ubuntu 18.04 |
| Browser | Chrome/78.0.3904.97 |

A screenshot to prove the issue exists
![image](https://user-images.githubusercontent.com/22119727/68643022-8248a200-0542-11ea-9175-1bb2f87135a1.png)

**Comment by afc163** [comment] 2019-11-12 13:46
Duplicate of #14859

**Closed by afc163** 2019-11-12 13:46 UTC
