### ISSUE TITLE
Layout.Sidebar Collapse along with Table horizontal scroll - Lagging animation. 

### ISSUE THREAD

**Issue by shaaandi** [ant-design/ant-design#32907] opened 2021-11-17 06:13 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sider-antd-4-17-0-forked-69kxf?file=/index.js)

### Steps to reproduce
1. Open the sandbox.
2. Open the sandbox preview in the new browser window.
3. Now one dev tools and adjust your browser screen in a such a way that the table don't have horizontal overflow when the sidebar is collapse but it will have when you open the side bar. So, for me it's 1536 px. You can change the columns too in code to achieve such case.
4. Now toggle the side bar collapse button at the bottom left.

### What is expected?
Smooth sidebar toggle animation as always.

### What is actually happening?
The sidebar animation is lagging.
Specifically:
1. The sidebar animation lags only when the table changes to have a horizontal scroll due to the change in width.

| Environment | Info |
|---|---|
| antd | 4.17.0 |
| React | ^16.14.0 |
| System | https://codesandbox.io/ |
| Browser | Version 95.0.4638.69 (Official Build) (64-bit) |

**Comment by afc163** [comment] 2021-11-17 06:16
Duplicate of #27775

**Closed by afc163** 2021-11-17 06:16 UTC
