### ISSUE TITLE
When Table with no data and fixed columns, the scrollbar will show under header which IMO is unreasonable

### ISSUE THREAD

**Issue by jasonxia23** [ant-design/ant-design#10984] opened 2018-06-21 10:51 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.3

### Environment
Chrome 66

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns](https://ant.design/components/table-cn/#components-table-demo-fixed-columns)

### Steps to reproduce
Create a Table with empty dataSource, and some fixed columns, try scroll the component horizontally.

### What is expected?
Scrollbar should show under no data

### What is actually happening?
Scrollbar shows under header

**Comment by yesmeck** [comment] 2018-06-21 12:02
Duplicate of #10490

**Closed by yesmeck** 2018-06-21 12:02 UTC
