### ISSUE TITLE
Image 图片预览组件，在关闭的时候会闪烁

### ISSUE THREAD

**Issue by deng-yc** [ant-design/ant-design#39087] opened 2022-11-29 09:53 UTC
### Reproduction link

[https://ant.design/components/image-cn](https://ant.design/components/image-cn)

### Steps to reproduce

点击预览，然后关闭，非常容易出现闪烁

### What is expected?

正常关闭后不闪烁

### What is actually happening?

非常容易在关闭后闪烁

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | react |
| System | win11 |
| Browser | chrome 107 |

**Comment by afc163** [comment] 2022-12-01 16:08
Duplicate of #39054

**Closed by afc163** 2022-12-01 16:08 UTC
