### ISSUE TITLE
导入theme会报错Can't resolve 'antd/es/theme/style'，其他组件无报错

### ISSUE THREAD

**Issue by hejun311** [ant-design/ant-design#39896] opened 2022-12-29 09:12 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eyldjy?file=/demo.tsx:371-437)

### Steps to reproduce

使用文档例子即报错

### What is expected?

不报错

### What is actually happening?

提示：Module not found: Error: Can't resolve 'antd/es/theme/style'

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.2.0 |
| System | Windows 10  |
| Browser | Google Chrome108.0.5359.124 |

**Comment by MadCcc** [comment] 2022-12-29 09:19
移除 `babel-plugin-import`

**Comment by zombieJ** [comment] 2022-12-29 09:20
Duplicate of #39344

**Closed by MadCcc** 2022-12-29 09:19 UTC

**Comment by liuxi0811** [comment] 2023-01-03 11:51
> 移除`babel-plugin-impo
按照文档设置了  继续报错

**Comment by shpilu** [comment] 2023-01-05 01:19
> 移除 `babel-plugin-import`
能说下怎么移除 babel-plugin-import吗？我package.json没有这个`babel-plugin-import`，照样报错

**Comment by changguilei** [comment] 2023-06-17 13:11
能说下怎么解决的吗

**Comment by yuanguandong** [comment] 2023-08-01 13:40
我补充一下，大家如果用了umi, 需要把umirc里的antd配置disableBabelPluginImport设为true, 或者直接把antd配置关闭
