### ISSUE TITLE
Table 无数据情况下无滚动条可拖动查看全部字段信息

### ISSUE THREAD

**Issue by yichenw7** [ant-design/ant-design#16698] opened 2019-05-21 06:02 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/charming-khayyam-4931w)

### Steps to reproduce
链接示例，操作表格，可发现无法展示隐藏部分字段内容

### What is expected?
无行数据也能够拉动滚动条查看收起字段内容

### What is actually happening?
无滚动条可拉动查看

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | v16.8.6 |
| System | windows7 |
| Browser | chorome |

---
在没有行数据的场景下，需求知晓表格字段内容

**Comment by afc163** [comment] 2019-05-21 06:26
Duplicate of #10490

**Closed by afc163** 2019-05-21 06:26 UTC
