### ISSUE TITLE
Table 虚拟表格实现列固定

### ISSUE THREAD

**Issue by Kumahime-Echo** [ant-design/ant-design#35317] opened 2022-04-29 01:20 UTC
### What problem does this feature solve?

虚拟表格左侧勾选列，右侧设置列固定不随滚动条左右滚动

### What does the proposed API look like?

fixed

**Comment by afc163** [comment] 2022-04-29 01:47
Duplicate of #20339

**Closed by afc163** 2022-04-29 01:47 UTC
