### ISSUE TITLE
Bad type for Table onChange (third parameter)

### ISSUE THREAD

**Issue by Jack-Works** [ant-design/ant-design#9859] opened 2018-03-29 07:11 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### What is actually happening?
Type of the second param is `Object`, then if I try to access any other property on "Object", typescript will throw an error. It might be `any`, `Record<keyof T, SortOptions>` or something.

Type `Object` in Typescript refer to the global `Object` object.

**Comment by yesmeck** [comment] 2018-03-29 12:38
Duplicate of #9858

**Closed by yesmeck** 2018-03-29 12:38 UTC
Labels: Component: Table
