### ISSUE TITLE
table 是否可以增加一个 列宽度可以拖动 改变

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#10515] opened 2018-05-15 12:55 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
table 是否可以增加一个 列宽度可以拖动 改变 ，比如我按住 姓名和 年龄之间的 边框线，可以多动 性别的占用大小

### What does the proposed API look like?
dragBoard = true 
maxDragBoard={200}
minDragBoard={200}

**Comment by yesmeck** [comment] 2018-05-15 14:46
Duplicate of https://github.com/ant-design/ant-design/issues/8390

**Closed by yesmeck** 2018-05-15 14:46 UTC
