### ISSUE TITLE
Table sticky 且 scroll.x 情况下，初次渲染列会闪动

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#50496] opened 2024-08-20 07:13 UTC
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-mpsdjq?file=demo.tsx)

### Steps to reproduce

1、点击刷新

### What is expected?

不闪动

### What is actually happening?

闪动

| Environment | Info |
| --- | --- |
| antd | latest |
| React | latest |
| System | mac |
| Browser | chrome |

https://github.com/user-attachments/assets/80013b20-03da-47f2-a187-f617c3dd8397

可以从视频第 13 秒看出，会先闪成下图这样再恢复

![image](https://github.com/user-attachments/assets/bc159dbc-90f3-4d75-98d0-d78528c227ae)

**Comment by afc163** [comment] 2024-08-20 10:24
Duplicate of https://github.com/ant-design/ant-design/issues/49099

**Closed by afc163** 2024-08-20 10:24 UTC
Labels: unconfirmed
