### ISSUE TITLE
nextjs menu hover style error

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#39815] opened 2022-12-26 07:34 UTC
### Reproduction link

[https://github.com/hengkx/test-antd5-next](https://github.com/hengkx/test-antd5-next)

### Steps to reproduce

hover menu
![Kapture 2022-12-26 at 15 33 19](https://user-images.githubusercontent.com/8358236/209518798-f7ab7d47-d7f6-47c7-8ee3-caa1731f95a3.gif)

### What is expected?

normal

### What is actually happening?

style error

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | react 18 |
| System | mac |
| Browser | chrome |

**Comment by MadCcc** [comment] 2022-12-26 08:03
Some problem not related to this issue: StyleProvider in `_document.tsx` will only work in server side.

**Comment by MadCcc** [comment] 2022-12-26 08:05
And the issue is that style is mixed with tailwindcss.
![image](https://user-images.githubusercontent.com/27722486/209522422-85c7f3f8-ec2b-48fe-a53b-82537c71570a.png)
Could be fixed in antd. Working on it now.

**Closed** 2022-12-27 02:29 UTC
Labels: 🐛 Bug
