### ISSUE TITLE
New ant design version 5.0.0 is confilicting with tailwindcss

### ISSUE THREAD

**Issue by rizwan92** [ant-design/ant-design#38794] opened 2022-11-21 08:52 UTC
### Reproduction link

[code sandbox reproduction](https://codesandbox.io/s/ant5-tailwind-test-vt13jb)

### Steps to reproduce

<Button type="primary> Button</Button> button primary is not working 

### What is expected?

Button primary should work

### What is actually happening?

Button Primary is not right output

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18 |
| System | mac os |
| Browser | chrome |

---
please fix it

**Comment by rizwan92** [comment] 2022-11-21 09:22
reproduction link added

**Comment by li-jia-nan** [comment] 2022-11-21 10:07
You can close `preflight` in `tailwind.config.cjs`:

```js
// tailwind.config.cjs
module.exports = {
  corePlugins: {
    preflight: false,
  },
};
```

**Comment by sherali-1** [comment] 2022-11-21 10:19
yes @li-jia-nan solution is working for me previous version and after migrating to new 5.0 version still working

**Comment by MadCcc** [comment] 2022-11-22 02:59
It's not issue with antd since tailwindcss's preflight override the style of Button. The priority of css selector are the same.

**Comment by Damienbelingheri** [comment] 2022-11-24 15:38
> @li-jia-nan preflight: false tailwind border not working and may more feature not working in tailwind
> 
> and one more thing as you can see my primary colour is different in the antd config provider in the reproduction link but form input element has blue border color when we focus on it

Same problem here ! Can you please reopen the issue @MadCcc  ?

**Comment by li-jia-nan** [comment] 2022-11-24 15:41
reopen

**Comment by phatify** [comment] 2022-11-27 14:39
facing the same issue

**Comment by phatify** [comment] 2022-11-27 14:40
> reopen

we need a patched update

**Comment by phatify** [comment] 2022-11-27 14:49
Ohhh! I fixed this issue by using StyleProvider, it work like a charm:   

```
<StyleProvider hashPriority="high">
    <RootApp />
</StyleProvider>
```

**Comment by MadCcc** [comment] 2022-11-27 14:58
> Ohhh! I fixed this issue by using StyleProvider, it work like a charm:
> 
> ```
> <StyleProvider hashPriority="high">
>     <RootApp />
> </StyleProvider>
> ```

Yes, this could help solve the problem by raise the priority of antd's selector. Since we do not have better solution for mixed style with tailwindcss, this may be the most suitable way to fix it. But you should be aware of the high priority brought by hash class, it may cause some other effect in style. Ref: https://ant.design/docs/react/customize-theme#compatible-adjustment

Going to close this issue with possible solution.

**Comment by zombieJ** [comment] 2022-11-27 14:59
Though the `StyleProvider` with `hashPriority="high"` is design for legacy browser. But it seems also resolve this problem:
https://ant.design/docs/react/customize-theme#compatible-adjustment

**Closed by MadCcc** 2022-11-27 14:58 UTC

**Comment by HimanshuW7** [comment] 2022-12-06 11:51
Antd v5 might have some improvements but now antd v5 + tailwind CSS has conflicts, for instance: className gets overridden via :where(.css-dev-only-do-not-override-1ij74fp)  now what to do. The only solution I can think of is to stay on v4 and forget about v5. They introduced CSS in js, and now with this new thing, we've to consequences that have no permanent solution, until and unless we start from scratch.

**Comment by Vincz** [comment] 2022-12-09 08:44
The `StyleProvider` solution was working a couple of days ago, but it doesn't seems to work anymore.

**Comment by dzcpy** [comment] 2022-12-11 06:38
Any updates?

**Comment by HimanshuW7** [comment] 2022-12-11 06:40
> Any updates?

I don't think so, it will get fixed sooner and for later I am still unsure about it. Although, they're using emotion js in v5 and I thinking chances are less to work along.

**Comment by chunsch** [comment] 2022-12-11 07:05
One way is to configuration[Important of Tailwind CSS](https://tailwindcss.com/docs/configuration#important), let Tailwind CSS a higher priority.


```js
// tailwind.config.js

module.exports = {
// ...other

  corePlugins: {
// Remove Tailwind CSS's preflight style so it can use the antd's preflight instead (reset.css).
    preflight: false
  },
  important: '#app',

// ...other
}
```

```tsx
// pages/_document.tsx or app/layout.tsx

<body id="app">
...
</body>
```

```css
/* globals.css */

@import 'antd/dist/reset.css';
@import 'styles/preflight.css';

// fix Tailwind CSS border styles,form Tailwind CSS's preflight
*,
::before,
::after {
  box-sizing: border-box; /* 1 */
  border-width: 0; /* 2 */
  border-style: solid; /* 2 */
  border-color: theme('borderColor.DEFAULT', currentColor); /* 2 */
}

::before,
::after {
  --tw-content: '';
}

@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Comment by HimanshuW7** [comment] 2022-12-11 07:31
> One way is to configuration [Important of Tailwind CSS](https://tailwindcss.com/docs/configuration#important), let Tailwind CSS a higher priority.
> 
> 
> ```js
> // tailwind.config.js
> 
> module.exports = {
> // ...other
> 
>   corePlugins: {
> // Remove Tailwind CSS's preflight style so it can use the antd's preflight instead (reset.css).
>     preflight: false
>   },
>   important: '#app',
> 
> // ...other
> }
> ```
> 
> ```tsx
> // pages/_document.tsx or app/layout.tsx
> 
> <body id="app">
> ...
> </body>
> ```
> 
> ```css
> /* globals.css */
> 
> @import 'antd/dist/reset.css';
> 
> // fix Tailwind CSS border styles,form Tailwind CSS's preflight
> *,
> ::before,
> ::after {
>   box-sizing: border-box; /* 1 */
>   border-width: 0; /* 2 */
>   border-style: solid; /* 2 */
>   border-color: theme('borderColor.DEFAULT', currentColor); /* 2 */
> }
> 
> ::before,
> ::after {
>   --tw-content: '';
> }
> 
> @tailwind base;
> @tailwind components;
> @tailwind utilities;
> ```
> 

I don't think it will work the same way with @apply because this tailwind class has been added.
For instance, .btn { @apply text-base bg-black p-5 } and so on. Applying on direct antd styles will affect and it won't let override and also if theme has been set via tailwind css than it's also issue because with tailwindcss we apply classes and so in v5 it will override.
Not everytime direct css can be used and so, with @apply yes it make chaos because of :where(.css-dev-only-do-not-override-1ij74fp)

And I know about reset.css but it's much of help in terms of fixing tailwind classes.

**Comment by KhokharJunaid** [comment] 2022-12-12 06:38
> You can close `preflight` in `tailwind.config.cjs`:
> 
> ```js
> // tailwind.config.cjs
> module.exports = {
>   corePlugins: {
>     preflight: false,
>   },
> };
> ```

Thanks, bro it is really working for me.

**Comment by gavinliu6** [comment] 2022-12-22 05:42
`<StyleProvider hashPriority="high">...</StyleProvider>` doesn't work now.

**Comment by chemicalkosek** [comment] 2022-12-23 13:28
Something broke in recent update to 5.1
Previously I have disabled the `preflight` in tailwind config and imported the antd reset. It worked ok.
After updating antd to 5.1 the fontSize became bigger and fontFamily is not applied
The colorPrimary does still seem to get applied tho. Even specifying the fontSize in configprovider doesn't work.

```javascript
const antdTheme = {
  token: {
    colorPrimary: '#dd6b20',
    colorLink: '#dd6b20',
    fontFamily:
      'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
    fontSize: 14,
  },
};

<ConfigProvider theme={antdTheme} locale={plPL}>
  ...
  ```

**Comment by nicoknoll** [comment] 2022-12-24 09:58
Hey so the main issue isn't preflieght but the order of style tags in the <head>. Tailwind usually is placed atthe bottom using style loader/sass loader while ant design is placed at the top. Thats why overwrites hae a higher priority. 

I tested it in the codesandbox in the first sample:

<img width="1209" alt="Bildschirmfoto 2022-12-24 um 10 55 00" src="https://user-images.githubusercontent.com/1143670/209430838-59397fad-30ae-42fe-be58-e6c6b8ebc12f.png">

here you can see the button not working while tailwind is at the bottom ant ant design at the top.

I moved the style node up manually in the dom and that fixes it:

<img width="1691" alt="Bildschirmfoto 2022-12-24 um 10 55 08" src="https://user-images.githubusercontent.com/1143670/209430857-5fdf11ed-7179-44b0-87de-f95770abe124.png">

Working on figuring out how to do that automatically and will update this message then :)

**Comment by chemicalkosek** [comment] 2022-12-24 12:01
@nicoknoll In mantine you solve this by passing a custom emotion cache to its provider
There's no need to disable preflight there
https://github.com/mantinedev/mantine/discussions/1672#discussioncomment-3951866
```javascript
export const myCache = createEmotionCache({ key: 'mantine', prepend: false });

 <MantineProvider
        withGlobalStyles
        withNormalizeCSS
        emotionCache={myCache}
      >
```
Then you for SSR styles to work, you'll need to pass the same cache in _document.js too (Next.js)
https://mantine.dev/theming/emotion-cache/#server-side-rendering-with-custom-cache

As AntD uses also emotion, perhaps this should be done the same way?

**Comment by zombieJ** [comment] 2022-12-25 07:40
Check `@ant-design/cssinjs` version is match what antd using. And pls fire new issue with reproduce instead since origin issue is for history trace which means origin reproduce is not align with latest version:

https://codesandbox.io/s/ant5-tailwind-test-forked-jk2stm?file=/package.json

**Comment by cowienduckie** [comment] 2022-12-28 08:00
> Ohhh! I fixed this issue by using StyleProvider, it work like a charm:
> 
> ```
> <ConfigProvider
>     theme={{
>         token: {
>             colorPrimary: '#000000',
>         },
>     }}
> >
>     <StyleProvider hashPriority="high">
>         <RootApp />
>     </StyleProvider>
> </ConfigProvider>
> ```
> 
> My Reproduction link demo: https://stackblitz.com/edit/nextjs-6j8zb7?file=pages/_app.js

This really works with my situation, thank you a lot!
I'm using Vite + Tailwind CSS + Ant Design. Just follow the basic setup on their docs, add `important: true` to Tailwind config and the above comment.

```javascript
// tailwind.config.cjs
module.exports = {
  important: true,  // <= This is needed to some cases that Tailwind need to override Antd
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {}
  },
  plugins: []
};
```

**Comment by Lunatix01** [comment] 2022-12-31 12:21
> Something broke in recent update to 5.1 Previously I have disabled the `preflight` in tailwind config and imported the antd reset. It worked ok. After updating antd to 5.1 the fontSize became bigger and fontFamily is not applied The colorPrimary does still seem to get applied tho. Even specifying the fontSize in configprovider doesn't work.
> 
> ```js
> const antdTheme = {
>   token: {
>     colorPrimary: '#dd6b20',
>     colorLink: '#dd6b20',
>     fontFamily:
>       'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
>     fontSize: 14,
>   },
> };
> 
> <ConfigProvider theme={antdTheme} locale={plPL}>
>   ...
> ```
> 
> Reverting to 5.0.7 fixes.

even this doesn't work for me

**Comment by cowienduckie** [comment] 2023-01-03 06:55
> 



> > Something broke in recent update to 5.1 Previously I have disabled the `preflight` in tailwind config and imported the antd reset. It worked ok. After updating antd to 5.1 the fontSize became bigger and fontFamily is not applied The colorPrimary does still seem to get applied tho. Even specifying the fontSize in configprovider doesn't work.
> > ```js
> > const antdTheme = {
> >   token: {
> >     colorPrimary: '#dd6b20',
> >     colorLink: '#dd6b20',
> >     fontFamily:
> >       'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
> >     fontSize: 14,
> >   },
> > };
> > 
> > <ConfigProvider theme={antdTheme} locale={plPL}>
> >   ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Reverting to 5.0.7 fixes.
> 
> even this doesn't work for me

@Lunatix01 I have a project using Antd(5.0.1) and Tailwind(3.2.4) works pretty fine without any bugs. Hope it would help if you tried that combo.

**Comment by GGuinea** [comment] 2023-01-05 19:15
> Ohhh! I fixed this issue by using StyleProvider, it work like a charm:
> 
> ```
> <ConfigProvider
>     theme={{
>         token: {
>             colorPrimary: '#000000',
>         },
>     }}
> >
>     <StyleProvider hashPriority="high">
>         <RootApp />
>     </StyleProvider>
> </ConfigProvider>
> ```
> 
> My Reproduction link demo: https://stackblitz.com/edit/nextjs-6j8zb7?file=pages/_app.js

That's fix my issue too. But instead setting colorPrimary  to '#000000', a set to "#1C64F2" (default tailwind blue color?)

**Comment by Webbrother** [comment] 2023-02-07 17:14
Changing of `hashPriority` or `preflight` disabling are dirty workarounds, because they doesn't fix the origin of the problem.

But as [@nicoknoll](https://github.com/nicoknoll) said here https://github.com/ant-design/ant-design/issues/38794#issuecomment-1364501286 and [@chemicalkosek](https://github.com/chemicalkosek)
said here https://github.com/ant-design/ant-design/issues/38794#issuecomment-1364518311 the real problem is about `<style>` tags ordering! So the only correct solution is to change the order.

**Comment by faner11** [comment] 2023-02-27 09:21
antd 5.2.2 又不正常了，button 透明的老问题

**Comment by EmberCCC** [comment] 2023-02-28 08:22
> antd 5.2.2 又不正常了，button 透明的老问题

https://unpkg.com/browse/tailwindcss@3.0.23/src/css/preflight.css  把css里面的@tailwind base删掉然后新建一个css，再把链接里面的css复制到新建的css文件中，然后删除有关button的样式就可以了

**Comment by faner11** [comment] 2023-03-01 04:17
> > antd 5.2.2 又不正常了，button 透明的老问题
> 
> https://unpkg.com/browse/tailwindcss@3.0.23/src/css/preflight.css 把css里面的@tailwind base删掉然后新建一个css，再把链接里面的css复制到新建的css文件中，然后删除有关button的样式就可以了
试了不行呀tailwindcss版本3.2.7 @EmberCCC

**Comment by EmberCCC** [comment] 2023-03-01 05:13
> 

应该没问题的呀，我的tailwindcss是3.2.4，antd是5.2.2，我把index.css里面的@tailwind base删掉之后，在引入链接里面的css删除button的样式就行了，只引入@tailwind components @tailwind utilities 这两个，@tailwind base这个样式相当于自己填写

**Comment by EmberCCC** [comment] 2023-03-01 05:13
> > > antd 5.2.2 又不正常了，button 透明的老问题
> > 
> > 
> > https://unpkg.com/browse/tailwindcss@3.0.23/src/css/preflight.css 把css里面的@tailwind base删掉然后新建一个css，再把链接里面的css复制到新建的css文件中，然后删除有关button的样式就可以了
> > 试了不行呀tailwindcss版本3.2.7 @EmberCCC

应该没问题的呀，我的tailwindcss是3.2.4，antd是5.2.2，我把index.css里面的https://github.com/tailwind base删掉之后，在引入链接里面的css删除button的样式就行了，只引入https://github.com/tailwind components https://github.com/tailwind utilities 这两个，https://github.com/tailwind base这个样式相当于自己填写

**Comment by EmberCCC** [comment] 2023-03-01 05:14
> > > antd 5.2.2 又不正常了，button 透明的老问题
> > 
> > 
> > https://unpkg.com/browse/tailwindcss@3.0.23/src/css/preflight.css 把css里面的@tailwind base删掉然后新建一个css，再把链接里面的css复制到新建的css文件中，然后删除有关button的样式就可以了
> > 试了不行呀tailwindcss版本3.2.7 @EmberCCC

应该没问题的呀，我的tailwindcss是3.2.4，antd是5.2.2，我把index.css里面的@tailwind base删掉之后，在引入链接里面的css删除button的样式就行了，只引入@tailwind components @tailwind utilities 这两个，@tailwind base这个样式相当于自己填写

**Comment by faner11** [comment] 2023-03-01 05:42
> > > > antd 5.2.2 又不正常了，button 透明的老问题
> > > 
> > > 
> > > https://unpkg.com/browse/tailwindcss@3.0.23/src/css/preflight.css 把css里面的@tailwind base删掉然后新建一个css，再把链接里面的css复制到新建的css文件中，然后删除有关button的样式就可以了
> > > 试了不行呀tailwindcss版本3.2.7 @EmberCCC
> 
> 应该没问题的呀，我的tailwindcss是3.2.4，antd是5.2.2，我把index.css里面的@tailwind base删掉之后，在引入链接里面的css删除button的样式就行了，只引入@tailwind components @tailwind utilities 这两个，@tailwind base这个样式相当于自己填写

我找到原因了，是因我用了pro-components 的ProLayout导致StyleProvider hashPriority='high'没有生效

**Comment by pappijx** [comment] 2023-03-10 10:11
Using ant design with styled-component, and it works like a chorm

import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'
import { BrowserRouter } from 'react-router-dom'
import { ConfigProvider } from 'antd'
import { dashboardThemeConfig } from './Core/Theme'

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <BrowserRouter>
      <ConfigProvider theme={dashboardThemeConfig}>
        <ConfigProvider theme={dashboardThemeConfig}>
          <ConfigProvider theme={dashboardThemeConfig}>
            <ConfigProvider theme={dashboardThemeConfig}>
              <ConfigProvider theme={dashboardThemeConfig}>
                <App />
              </ConfigProvider>
            </ConfigProvider>
          </ConfigProvider>
        </ConfigProvider>
      </ConfigProvider>
    </BrowserRouter>
  </React.StrictMode>,
)

**Comment by tobiasriemenschneider** [comment] 2023-03-27 03:07
My understanding:
Tailwinds Preflight Reset (coming first) is partially messing up Antds styles (coming second).
Is there a PROPER solution for this?

**Comment by KSubedi** [comment] 2023-03-30 02:54
I am still looking for a solution for this as well. Disabling preflight causes other issues with tailwind styles not working properly.

**Comment by zombieJ** [comment] 2023-03-30 15:40
@KSubedi Pls feel free to open new issue with reproduce : )
Closed issue can not be well traced.

**Comment by gidgudgod** [comment] 2023-04-08 09:38
fixed issue in antd 5.0.5 by adding this
https://github.com/ant-design/ant-design/issues/38794#issuecomment-1364501286

and set important to true in tailwind config
```
module.exports = {
 ....,
 important:true,
};
```

But some antd styles not applied example in <Button/> component when icon prop supplied in it, I need to add tailwind flex align-center to make the button icon and text centered. 
However about this prob, its fine for me bcoz just need add some centering classnames

**Comment by cdx111** [comment] 2023-04-11 03:00
I solved it by using StyleProvider. now it worked

**Comment by cdx111** [comment] 2023-04-11 03:04
5.4.0 of antd  and 3.0.0 of tailwind version

**Comment by alissonmarqui** [comment] 2023-04-25 15:16
Tailwind Preflight set Button background-color to transparent:
https://unpkg.com/tailwindcss@3.3.1/src/css/preflight.css

```
/*
1. Correct the inability to style clickable types in iOS and Safari.
2. Remove default button styles.
*/

button,
[type='button'],
[type='reset'],
[type='submit'] {
  -webkit-appearance: button; /* 1 */
  background-color: transparent; /* 2 */
  background-image: none; /* 2 */
}

```

For this specific problem, I fixed with !important in button color in 
antd theme

```
{
  "token": {
    "colorPrimary": "#f9c871"
  },
  "components": {
    "Button": {
      "colorPrimaryActive": "#E1A51F",
      "colorPrimaryHover": "#F7C778",
      "colorPrimary": "#FFB718 !important"
    }
  }
}
```

**Comment by rgnldws** [comment] 2023-05-01 21:31
> ```js
> ome cases that Tailwind need to override Antd
> ```

So far do you think it's only the Button component that is affected?

**Comment by eveforest** [comment] 2023-05-28 13:15
antd5.5.1, in windcss, this work for me:
```
export default defineConfig({
    preflight: false,
})
```

**Comment by kasvith** [comment] 2023-06-07 10:01
<StyleProvider> worked

**Comment by liwei478** [comment] 2023-06-12 02:10
> > You can close `preflight` in `tailwind.config.cjs`:
> > ```js
> > // tailwind.config.cjs
> > module.exports = {
> >   corePlugins: {
> >     preflight: false,
> >   },
> > };
> > ```
> 
> Thanks, bro it is really working for me.

Thank you, dude, this also works for me.

**Comment by wqcstrong** [comment] 2023-06-29 12:50
> Hey so the main issue isn't preflieght but the order of style tags in the `<head>`. Tailwind usually is placed at the bottom using style loader/sass loader while ant design is placed at the top. Thats why overwrites have a higher priority.
> 
> I tested it in the codesandbox in the first sample:
> 
> ```
> <head>
> ...
> <style data-rc-order="prependQueue" data-css-hash="pqrs3r" data-token-hash="mcxaqb" data-dev-cache-path="mcxaqb|Shared|ant"></style>
> ...
> <style>...tailwind...</style>
> ...
> ```
> 
> here you can see the button not working while tailwind is at the bottom ant ant design at the top.
> 
> I moved the style node up manually in the dom and that fixes it:
> 
> ```
> <head>
> ...
> <style>...tailwind...</style>
> <style data-rc-order="prependQueue" data-css-hash="pqrs3r" data-token-hash="mcxaqb" data-dev-cache-path="mcxaqb|Shared|ant"></style>
> ...
> ```
> 
> ~Working on figuring out how to do that automatically and will update this message then~
> 
> **Edit:**
> 
> As it seems this is controlled via `node_modules/@ant-design/cssinjs/lib/hooks/useStyleRegister.js` and is executed during run time so we can't fix it by adjusting webpack style-loader options.
> 
> So what works for me for now as a workaround (not a finished solution) is to manually resort style tags after initial load. E.g. I added this to my `<App>` component:
> 
> ```js
> useEffect(() => {
>     const head = document.querySelector('head');
>     const tailWindStyleTag = [...head.querySelectorAll('style')].find((style) =>
>         style.innerHTML.includes('tailwind')
>     );
>     head.insertAdjacentElement('afterbegin', tailWindStyleTag);
> }, []);
> ```
> 
> @rizwan92 I updated the original codesandbox to show this workaround works: https://codesandbox.io/s/ant5-tailwind-test-forked-55yhhn

This way doesn't work after building in create-react-app, since there is no included `tailwind` identifier `<style>` tag, and it's included in a css chunk file.

**Comment by coderlcb** [comment] 2023-07-27 06:22
So is there an optimal solution?  i use antd@5.7.2 and tailwindcss@3.3.2👀

**Comment by yunsii** [comment] 2023-08-19 03:38
I have made a postcss plugin [postcss-antd-fixes](https://github.com/yunsii/postcss-antd-fixes) tries to process conflicts of antd with any others global CSS reset, support TailwindCSS for now. Online example: https://stackblitz.com/edit/postcss-antd-fixes?file=postcss.config.js

**Comment by FeiPengDev** [comment] 2023-09-20 21:23
any updates on this issue?

**Comment by yunsii** [comment] 2023-09-24 11:00
> I have made a postcss plugin [postcss-antd-fixes](https://github.com/yunsii/postcss-antd-fixes) tries to process conflicts of antd with any others global CSS reset, support TailwindCSS for now. Online example: [stackblitz.com/edit/postcss-antd-fixes?file=postcss.config.js](https://stackblitz.com/edit/postcss-antd-fixes?file=postcss.config.js)
> 
> ### 20230924 Update
> I just found that there is also a anchor style confilict, antd will [generate link style](https://github.com/ant-design/ant-design/blob/f556a54dd53202fb500c083efa4b53c3725b6e0a/components/style/index.ts#L65) like this ![image](https://user-images.githubusercontent.com/18096089/270159127-c890b946-9c75-4ce9-a24d-9356ea736b11.png)
> 
> And tailwind has related anchor reset css: [tailwindlabs/tailwindcss@`b33c302`/src/css/preflight.css#L88](https://github.com/tailwindlabs/tailwindcss/blob/b33c30284f8a857a94c5dece88d489a7589dfaf6/src/css/preflight.css#L88)
> 
> ```css
> a {
>   color: inherit;
>   text-decoration: inherit;
> }
> ```
> 
> So I add new fix function to resolve it, make anchors style under any antd components normal as expected, online example updated.

FYI, There is a anchor style conflict to be fixed.

**Comment by EdwardMoMo** [comment] 2023-10-05 12:22
> > I have made a postcss plugin [postcss-antd-fixes](https://github.com/yunsii/postcss-antd-fixes) tries to process conflicts of antd with any others global CSS reset, support TailwindCSS for now. Online example: [stackblitz.com/edit/postcss-antd-fixes?file=postcss.config.js](https://stackblitz.com/edit/postcss-antd-fixes?file=postcss.config.js)
> > ### 20230924 Update
> > I just found that there is also a anchor style confilict, antd will [generate link style](https://github.com/ant-design/ant-design/blob/f556a54dd53202fb500c083efa4b53c3725b6e0a/components/style/index.ts#L65) like this ![image](https://user-images.githubusercontent.com/18096089/270159127-c890b946-9c75-4ce9-a24d-9356ea736b11.png)
> > And tailwind has related anchor reset css: [tailwindlabs/tailwindcss@`b33c302`/src/css/preflight.css#L88](https://github.com/tailwindlabs/tailwindcss/blob/b33c30284f8a857a94c5dece88d489a7589dfaf6/src/css/preflight.css#L88)
> > ```css
> > a {
> >   color: inherit;
> >   text-decoration: inherit;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So I add new fix function to resolve it, make anchors style under any antd components normal as expected, online example updated.
> 
> FYI, There is a anchor style conflict to be fixed.
Hi, @yunsii May I know if you fixed this anchor style conflict?

**Comment by EdwardMoMo** [comment] 2023-10-05 12:25
> > I have made a postcss plugin [postcss-antd-fixes](https://github.com/yunsii/postcss-antd-fixes) tries to process conflicts of antd with any others global CSS reset, support TailwindCSS for now. Online example: [stackblitz.com/edit/postcss-antd-fixes?file=postcss.config.js](https://stackblitz.com/edit/postcss-antd-fixes?file=postcss.config.js)
> > ### 20230924 Update
> > I just found that there is also a anchor style confilict, antd will [generate link style](https://github.com/ant-design/ant-design/blob/f556a54dd53202fb500c083efa4b53c3725b6e0a/components/style/index.ts#L65) like this ![image](https://user-images.githubusercontent.com/18096089/270159127-c890b946-9c75-4ce9-a24d-9356ea736b11.png)
> > And tailwind has related anchor reset css: [tailwindlabs/tailwindcss@`b33c302`/src/css/preflight.css#L88](https://github.com/tailwindlabs/tailwindcss/blob/b33c30284f8a857a94c5dece88d489a7589dfaf6/src/css/preflight.css#L88)
> > ```css
> > a {
> >   color: inherit;
> >   text-decoration: inherit;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So I add new fix function to resolve it, make anchors style under any antd components normal as expected, online example updated.
> 
> FYI, There is a anchor style conflict to be fixed.

Hi, @yunsii May I know if you fixed this anchor style conflict?

**Comment by yunsii** [comment] 2023-10-05 13:51
@EdwardMoMo As a non-native English speaker, maybe my expression is not clear? I had fixed and released with [postcss-antd-fixes@0.2.0](https://github.com/yunsii/postcss-antd-fixes/compare/v0.1.0...v0.2.0)

**Comment by EdwardMoMo** [comment] 2023-10-05 15:42
Great, thanks, I noticed the new commit of your plugin.

**Comment by dananjaya6005** [comment] 2023-12-12 10:45
guys 

> Ohhh! I fixed this issue by using StyleProvider, it work like a charm:
> 
> ```
> <ConfigProvider
>     theme={{
>         token: {
>             colorPrimary: '#000000',
>         },
>     }}
> >
>     <StyleProvider hashPriority="high">
>         <RootApp />
>     </StyleProvider>
> </ConfigProvider>
> ```
> 
> My Reproduction link demo: https://stackblitz.com/edit/nextjs-6j8zb7?file=pages/_app.js

this one is working perfectly. no need to disable tailwindcss's preflight. Also, disabling preflight is not recommended.It can be affect to native tailwind style

**Comment by BarrySong97** [comment] 2023-12-19 00:55
> ```js
>  corePlugins: {
> // Remove Tailwind CSS's preflight style so it can use the antd's preflight instead (reset.css).
>     preflight: false
>   },
>   important: '#app',
> ```

This work for me.

**Comment by BarrySong97** [comment] 2023-12-19 01:07
> Ohhh! I fixed this issue by using StyleProvider, it work like a charm:
> 
> ```
> <ConfigProvider
>     theme={{
>         token: {
>             colorPrimary: '#000000',
>         },
>     }}
> >
>     <StyleProvider hashPriority="high">
>         <RootApp />
>     </StyleProvider>
> </ConfigProvider>
> ```
> 
> My Reproduction link demo: https://stackblitz.com/edit/nextjs-6j8zb7?file=pages/_app.js

This worked for me well.

**Comment by kaustubhxd** [comment] 2024-01-21 17:17
I gave up after trying everything for fixing my button color. I went with this in global.css

`.ant-btn-primary {
  background-color: #1677ff !important;
}`

**Comment by jagaa999** [comment] 2024-01-26 06:38
> I gave up after trying everything for fixing my button color. I went with this in global.css
> 
> `.ant-btn-primary { background-color: #1677ff !important; }`

maybe me too

**Comment by jagaa999** [comment] 2024-01-26 06:53
> I have made a postcss plugin [postcss-antd-fixes](https://github.com/yunsii/postcss-antd-fixes) tries to process conflicts of antd with any others global CSS reset, support TailwindCSS for now. Online example: https://stackblitz.com/edit/postcss-antd-fixes?file=postcss.config.js
> 
> ### 20230924 Update
> I just found that there is also a anchor style conflict, antd will [generate link style](https://github.com/ant-design/ant-design/blob/f556a54dd53202fb500c083efa4b53c3725b6e0a/components/style/index.ts#L65) like this ![image](https://private-user-images.githubusercontent.com/18096089/270159127-c890b946-9c75-4ce9-a24d-9356ea736b11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTIyNjgsIm5iZiI6MTcwNjI1MTk2OCwicGF0aCI6Ii8xODA5NjA4OS8yNzAxNTkxMjctYzg5MGI5NDYtOWM3NS00Y2U5LWEyNGQtOTM1NmVhNzM2YjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA2NTI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiOTE1ZDAxNmY4ZjFiMzBlOGM3MmE0YzcxYzk5YjJiMDRhNjRkNWE3NWQzODMxZmVkN2MxZDhiMTIyYzJlNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xkF0xw4Sj9k6mCsgsfarwLP3FoAiQCaDWMJBcj7PGCM)
> 
> And tailwind has related anchor reset css: https://github.com/tailwindlabs/tailwindcss/blob/b33c30284f8a857a94c5dece88d489a7589dfaf6/src/css/preflight.css#L88
> 
> ```css
> a {
>   color: inherit;
>   text-decoration: inherit;
> }
> ```
> 
> So I add new fix function to resolve it, make anchors style under any antd components normal as expected, online example updated.

Thank you, it is working for me. Saving my life.

**Comment by abduhere** [comment] 2024-07-04 13:32
While going through this thread and exploring different options to configure Tailwind CSS with AntD V5, I finally found the official solution on the AntD website.
Link to solution: https://ant.design/docs/react/compatible-style#tailwindcss-arrange-layer

This solution of AntD website worked best for me. Hope this helps other people too!

**Comment by yunsii** [comment] 2024-07-04 13:44
Also I have updated my postcss plugin docs: https://github.com/yunsii/postcss-antd-fixes#features

**Comment by muyoou** [comment] 2024-07-30 03:00
> While going through this thread and exploring different options to configure Tailwind CSS with AntD V5, I finally found the official solution on the AntD website. Link to solution: https://ant.design/docs/react/compatible-style#tailwindcss-arrange-layer
> 
> This solution of AntD website worked best for me. Hope this helps other people too!

It is working perfectly for me,  thank you!

**Comment by anotheri** [comment] 2025-02-05 15:55
Does anybody have a luck to make it work with Tailwind CSS 4 (+ lightning css, ideally)?

**Comment by liaoyinglong** [comment] 2025-02-23 13:12
@anotheri try replace ` @import "tailwindcss";` with following
```global.css
@layer theme, base, components, utilities;

@import 'tailwindcss/theme.css' layer(theme);
@import 'tailwindcss/preflight.css' layer(base);

// put @tailwind utilities in #app or other selectors
#app {
  @tailwind utilities;
}
```

then u can see it works
```tsx
<Button className='hidden'>start</Button>
```

**Comment by diqye** [comment] 2025-02-23 17:48
`  root.render(<ConfigProvider theme={theme}><StyleProvider hashPriority="high"><UI /></StyleProvider></ConfigProvider>);
`
works for me.

**Comment by anotheri** [comment] 2025-02-25 15:00
@liaoyinglong yeah, i've also noticed last week that it seems to be working as expected (after a couple updates of Vite, postcss so most probably it was not directly related to antd), thanks for heads up anyways.

**Comment by revskill10** [comment] 2025-03-18 16:39
Can you put a working stackblitz example @diqye @anotheri ?
