### ISSUE TITLE
Add Additional Color Support for Buttons

### ISSUE THREAD

**Issue by Joon7891** [ant-design/ant-design#30563] opened 2021-05-18 03:11 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently API Buttons can only be "primary" (light blue) and "danger" (light red) with the offered props. It would be nice to see the implementation of a "color" property which can select from Ant Design's Global Styles Colors.

### What does the proposed API look like?
"color" prop is added to Buttons. The "color" prop must be in the form "<color>-<n>" which corresponds to the base color palettes on [https://ant.design/docs/spec/colors](https://ant.design/docs/spec/colors).

**Comment by afc163** [comment] 2021-05-18 04:03
Duplicate of #1984

**Closed by afc163** 2021-05-18 04:03 UTC
