### ISSUE TITLE
Select组件数组为8时，报错`NaN` is an invalid value for the `top` css style property.

### ISSUE THREAD

**Issue by XiaoColl** [ant-design/ant-design#27493] opened 2020-11-02 03:43 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?editors=0011](https://codepen.io/pen/?editors=0011)

### Steps to reproduce
只需将数组数量置为 8 ,然后进行选择

### What is expected?
不报错

### What is actually happening?
报错`NaN` is an invalid value for the `top` css style property.

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by xrkffgg** [comment] 2020-11-02 03:48
Duplicate of https://github.com/ant-design/ant-design/issues/27282

**Closed by xrkffgg** 2020-11-02 03:48 UTC
