### ISSUE TITLE
Custom styles in Inputs with suffix/prefix don't work

### ISSUE THREAD

**Issue by yallie** [ant-design/ant-design#11956] opened 2018-08-29 13:12 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.4

### Environment
Google Chrome 68.0.3440.106

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1ol0q0q2vl)

### Steps to reproduce
* Create an Input with style={{ backgroundColor: "gray" }}. Works fine.
* Add a suffix or a prefix to the Input. The custom style is gone.

### What is expected?
The style should be applied to the Input component.

### What is actually happening?
The style is applied to the wrapper span, but not applied to the Input itself.

![image](https://user-images.githubusercontent.com/672878/44789772-28122a00-aba6-11e8-9101-66ab22f18cc6.png)

**Comment by afc163** [comment] 2018-08-30 02:41
Duplicate of #9941

**Closed by afc163** 2018-08-30 02:41 UTC
