### ISSUE TITLE
Checkbox is not checked when parent container prevents clickEvent

### ISSUE THREAD

**Issue by konossow** [ant-design/ant-design#33927] opened 2022-02-03 14:53 UTC
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-tjhd82?file=index.js](https://stackblitz.com/edit/react-tjhd82?file=index.js)

### Steps to reproduce
Click on checkbox label

### What is expected?
Checkbox should become checked

### What is actually happening?
Checkbox is not checked

| Environment | Info |
|---|---|
| antd | 4.18.5 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome 97.0.4692.99 |

---
Checkbox can be checked by direct click on input, however it cannot be than unchecked in any way. OnChange callback on checkbox element is also not called. Checking and unchecking checkbox should not depend on parent custom event handler.

**Comment by cwjTerrace** [comment] 2022-02-08 09:36
https://zhuanlan.zhihu.com/p/431268270

**Comment by MadCcc** [comment] 2022-02-09 06:34
Duplicate of https://github.com/ant-design/ant-design/issues/32790

**Closed by MadCcc** 2022-02-09 06:34 UTC
