### ISSUE TITLE
notification not respecting prefixCls from ConfigProvider

### ISSUE THREAD

**Issue by hugobarragon** [ant-design/ant-design#21119] opened 2020-01-27 17:28 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

similar: #15260

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/solitary-voice-6znzj?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
import antd styles (css)
Create aplication with antd
Apply ConfigProvider component to change prefixCls prop to change all antd classname prefix for "lib-ant"
apply button component and on click open a notification

### What is expected?
notification to show without styles because we are importing css styles (just for example) and the css style antd prefix is "ant", since we changed the prefix to "lib-ant" the css will not match, button lost the styles because prefixCls changed correctly but notification still keeps "ant" prefix

### What is actually happening?
notification shows with prefixCls set to "ant" and displays with all styles and button is correct m showing without styles because class name has changed

| Environment | Info |
|---|---|
| antd | 3.26.5 |
| React | 16.12 |
| System | Windows 10 |
| Browser | Chrome Version 79.0.3945.130 (Official Build) (64-bit) |

---
this is just and example, I have tried with lessjs change the prefix variable and notification always keeps "ant" prefix, this for my company is a major because we have multiple npm modules that use antd components and we have to change the prefixCls so they don't affect other styles, I only spotted this on the notification api, we use antd components for a long time, I am available to help if needed, its affecting all versions the 4.0 to

**Comment by hugobarragon** [comment] 2020-01-27 17:59
btw with message api is the same, but placing prefixCls on message api config works, on notification it does not work, and message api config is missing prefixCls on DOCS:
https://ant.design/components/message/#message.config

`  
messageAPI.config({
  prefixCls: "ex-ant-message",
});
`

**Comment by zombieJ** [comment] 2020-01-28 03:18
Duplicate of #15260

**Closed by zombieJ** 2020-01-28 03:18 UTC

**Comment by hugobarragon** [comment] 2020-01-28 10:05
> Duplicate of #15260

its not duplicated, that issue refers to modal not notification api thats why i open this issue..... and a fix was made to modal this one:
https://github.com/ant-design/ant-design/issues/15260#issuecomment-554714836
so you are saying me if i apply this fix notification prefix starts working??????

**Comment by zombieJ** [comment] 2020-02-03 02:39
notification & Modal.xxx both create additional div to create the popup element which missing the context for origin one. They are meeting the same issue.

In v4, we have a PR to use hooks for creating context support call: https://github.com/ant-design/ant-design/pull/20949

**Comment by hugobarragon** [comment] 2020-02-03 11:05
> notification & Modal.xxx both create additional div to create the popup element which missing the context for origin one. They are meeting the same issue.
> 
> In v4, we have a PR to use hooks for creating context support call: #20949

i understand that, the only solucion is to upgrade to version 4? the modal api has prefix works on the config, but on the notification it does not....

**Comment by zombieJ** [comment] 2020-02-04 02:13
Yes. v3 need to be compatible with React 15. And missing context with additional dom render is a long time issue that we can't resolve perfectly. Internally we have much hard code to save the config into global but it meets issue that multiple config-provide failed.
We strongly recommend to upgrade into v4 if no legacy React or browser needed.

**Comment by hugobarragon** [comment] 2020-02-05 14:32
Updated to v4 and same bug still cant do it on notification....

**Comment by hugobarragon** [comment] 2020-02-05 14:54
@zombieJ  I updated to v4 and same bug still cant do it on notification.... its not applying the prefixcls

**Comment by zombieJ** [comment] 2020-02-06 02:13
#20949 has merged recently. notification PR will follow up : )

**Comment by hugobarragon** [comment] 2020-02-06 18:56
> #20949 has merged recently. notification PR will follow up : )

thanks, but why you closed the issue when the solution was not implemented? and the referenced one was from a modal component that had the same problem "can't access to configprovider" and the new approach was to use context.... but its completely different components there was no solution for notification on that related PR, only suffered from the same problem, but  solving the modal problem was not going to fix notification

**Comment by afc163** [comment] 2020-02-07 02:48
Duplicate of #15260 means that you should trace this quesion in #15260.

**Comment by hugobarragon** [comment] 2020-02-10 17:09
@afc163 ok,thanks
@zombieJ should rc4 already have this fix for notification?

**Comment by yoyo837** [comment] 2020-02-10 18:27
@hugobarragon Yes, #21275, Pls try rc4.

**Comment by hugobarragon** [comment] 2020-02-10 18:39
> @hugobarragon Yes, #21275, Pls try rc4.

i have tried on rc4 and its not working, thats why i was asking..... i checkd docs for notification and the implementation looks the same

**Comment by yoyo837** [comment] 2020-02-10 18:43
Maybe that should probably be used in a hook way, only hook. I'll reopen #15260.

**Comment by hugobarragon** [comment] 2020-02-10 18:51
> Maybe that should be used in a hook way, only hook. I'll reopen #15260.

maybe, if someone can update the docs or check if something is wrong, i am using antd rc4 with what is written on the docs and the prefix is not changed so the style is never applied to the notification

**Comment by yoyo837** [comment] 2020-02-10 18:55
Try [this](https://next.ant.design/components/notification/#components-notification-demo-hooks) with `ConfigContext.Consumer`.

**Comment by hugobarragon** [comment] 2020-02-11 10:07
> Try [this](https://next.ant.design/components/notification/#components-notification-demo-hooks) with `ConfigContext.Consumer`.
  

yes its fixed, but not with that ConfigContext.Consumer just have to migrate from  
this :  
[![Edit antd-notification-bug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-notification-bug-6znzj?fontsize=14&hidenavigation=1&theme=dark)

to this:  
Working example (prefixCls changed so new class name and style losted):  
[![Edit antd-notification-bug-fixed](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-notification-bug-fixed2-m7cvs?fontsize=14&hidenavigation=1&theme=dark)  

we will need to so some serius update on the docs, thanks for the help @yoyo837

**Comment by hugobarragon** [comment] 2023-08-01 11:02
> @hugobarragon Have you fixed it? I am using notification from antd. When i trigger openNotification function on onClick it works fine. but when i trigger the openNotification function through another function (not by onClick), application throws error Unhandled Rejection (TypeError): getPrefixCls is not a function

Hi the sandboxlink was failing, i updated it now it doesnt crash, from my last coment here:    
https://github.com/ant-design/ant-design/issues/21119#issuecomment-584559579

**Comment by awaistintash** [comment] 2023-08-01 12:02
> 

@hugobarragon Hi, Thanks but as i mentioned like in sandboxlink if I implement trigger openNotification() function on onClick it will work fine. I am having problem when I call openNotification() function from other function like in the screenshot
<img width="314" alt="Screenshot 2023-08-01 at 5 02 04 PM" src="https://github.com/ant-design/ant-design/assets/128799916/542fa959-bcb0-4e85-a96b-be6e9c3ffa3d">

**Comment by hugobarragon** [comment] 2023-08-01 12:05
> > 
> 
> @hugobarragon Hi, Thanks but as i mentioned like in sandboxlink if I trigger openNotification() function on onClick it will work fine. I am having problem when I call openNotification() function from other function like in the screenshot <img alt="Screenshot 2023-08-01 at 5 02 04 PM" width="314" src="https://user-images.githubusercontent.com/128799916/257507706-542fa959-bcb0-4e85-a96b-be6e9c3ffa3d.png">

the issue that you are talking about has nothing to do with this that we are on then, but anyways send me the reproducible link , or grab mine and just apply the code that produces your bug so i can check it out

**Comment by hugobarragon** [comment] 2023-08-01 12:08
@awaistintash i just tested without onClick and works fine,  

![image](https://github.com/ant-design/ant-design/assets/35630927/60a3be81-2903-43bb-b5f4-31a9ef19e3f7)

**Comment by awaistintash** [comment] 2023-08-01 12:56
@hugobarragon can you share your email?

**Comment by hugobarragon** [comment] 2023-08-01 13:31
> 

no, just place here the example ou a codebox reproducible link so i cant check the problem

**Comment by awaistintash** [comment] 2023-08-02 00:01
@hugobarragon it worked. Thanks

**Comment by hugobarragon** [comment] 2023-08-02 09:35
> 

what has worked?
