### ISSUE TITLE
Menu not showing items correctly even if props are passed

### ISSUE THREAD

**Issue by sklinov** [ant-design/ant-design#30388] opened 2021-05-04 07:28 UTC
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-menu-wrapper-czj6k?file=/src/App.tsx)

### Steps to reproduce
Hover on the left menu `This menu NOT showing items correctly` and see those menu items are not displayed correctly.
Item have a wrapper that passes `...props`  to its children with `React.cloneElement` (check out `Wrapper.tsx`)

### What is expected?
Menu items are shown and working correctly because `...props` are passed to them

### What is actually happening?
We can see that item are there (there are 3 of them according to `show` attribute), but they are not displayed

| Environment | Info |
|---|---|
| antd | 4.15.4 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by afc163** [comment] 2021-05-05 14:47
Duplicate of #4853

**Closed by afc163** 2021-05-05 14:47 UTC
