### ISSUE TITLE
Tooltip 组件 children 为函数组件时不工作

### ISSUE THREAD

**Issue by gauseen** [ant-design/ant-design#28322] opened 2020-12-11 07:34 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-antd492-forked-tosgt?file=/index.js)

### Steps to reproduce
hover 按钮，Tooltip 无提示

### What is expected?
正常提示

### What is actually happening?
无提示

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | "^16.14.0" |
| System | Mac |
| Browser | Chrome |

---
将 `<UploadSendImage></UploadSendImage>` 改成 `{UploadSendImage()}` 调用就 OK，为什么？

**Comment by huntdream** [comment] 2020-12-11 07:49
需要把`props`传递到`UploadSendImage`里面的dom上面去。函数调用的方式，`Tooltip`的子组件实际上是`Button`

**Comment by afc163** [comment] 2020-12-11 07:50
Duplicate of #15909

**Closed by afc163** 2020-12-11 07:50 UTC
