### ISSUE TITLE
Tab页签超过页面宽度（后方出现省略号下拉menu时），关闭下拉menu中的所有标签后，会出现多余的白框

### ISSUE THREAD

**Issue by CiciIvory** [ant-design/ant-design#35854] opened 2022-06-01 07:48 UTC
### Reproduction link

[https://ant.design/components/tabs-cn/](https://ant.design/components/tabs-cn/)

### Steps to reproduce

Tab页签超过页面宽度（后方出现省略号下拉menu时），关闭下拉menu中的所有标签后，会出现多余的白框

### What is expected?

没有多余的白框

### What is actually happening?

会出现多余的白框

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.2 |
| System | windows |
| Browser | chrome  101.0.4951.54 |

---
官方的组件demo就直接可复现这个问题
![dElh3HrK96](https://user-images.githubusercontent.com/40973214/171354364-666c2bf8-c6d5-4139-b10a-8e5c392bb452.jpg)

**Comment by afc163** [comment] 2022-06-01 07:51
Duplicate of #33311

**Closed by afc163** 2022-06-01 07:51 UTC
