### ISSUE TITLE
Checkbox render is slow in Dynamic form when it appends row

### ISSUE THREAD

**Issue by miyunim** [ant-design/ant-design#22401] opened 2020-03-19 08:36 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/checkbox-list-tzcnh)

### Steps to reproduce
Just click the add field button and can change the count user this variable `CHECK_COUNT`

### What is expected?
Append the dynamic forms smoothly

### What is actually happening?
It will be slow when clicked the add button

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | lastest |
| System | Mac ios |
| Browser | Chrome |

---
I always develop base on your "AntD" very well, it's really helpful and many thanks.

I have a problem during change my code to Antd v4.
I make a dynamic form now, but if a dynamic form has Checkbox components (above 3 items), add a row feature will be slow.

Please give me some tips.
And I shared a URL for the test.

**Comment by zombieJ** [comment] 2020-03-19 12:49
Duplicate of #22288

**Closed by zombieJ** 2020-03-19 12:49 UTC
