### ISSUE TITLE
Image的图片预览功能没有api可以配置是否展示旋转按钮或者放大按钮

### ISSUE THREAD

**Issue by leyuan1234** [ant-design/ant-design#39156] opened 2022-12-01 09:39 UTC
### Reproduction link

[https://4x.ant.design/components/image-cn/#previewtype](https://4x.ant.design/components/image-cn/#previewtype)

### Steps to reproduce

点击图片预览

### What is expected?

期望可以配置旋转按钮是否展示

### What is actually happening?

没有可配置旋转按钮的选项

| Environment | Info |
| --- | --- |
| antd | 4.24.4 |
| React | react |
| System | mac |
| Browser | 107.0.5304.110 |

**Comment by yoyo837** [comment] 2022-12-01 09:43
Maybe duplicate of https://github.com/ant-design/ant-design/issues/38418

**Closed** 2022-12-01 11:12 UTC
