### ISSUE TITLE
表格开启虚拟滚动，横向滚动时会导致表头列和表格内容显示错位

### ISSUE THREAD

**Issue by linlinjiang** [ant-design/ant-design#51785] opened 2024-11-26 09:18 UTC
### Reproduction link

[https://ant-design.antgroup.com/components/table-cn](https://ant-design.antgroup.com/components/table-cn)

### Steps to reproduce

虚拟表格横向滚动，快速拖动过去再拖动回来，表头错位了

### What is expected?

期望在虚拟滚动下 列头和内容不会出现内容错位问题

### What is actually happening?

横向滚动了就会有BUG

| Environment | Info |
| --- | --- |
| antd | 5.22.2 |
| React | 18.2.0 |
| System | windows |
| Browser | chrome版本131.0.6778.70 |

**Comment by linlinjiang** [comment] 2024-11-26 09:18
Uploading 20241126-171737.mp4…

**Comment by linlinjiang** [comment] 2024-11-26 09:20
![screenshot-20241126-171958](https://github.com/user-attachments/assets/22ed0672-5a11-480e-aaf5-7f98d9b941b8)

**Comment by Wxh16144** [comment] 2024-11-26 09:21
看看是不是和 https://github.com/ant-design/ant-design/issues/45524类似

**Comment by linlinjiang** [comment] 2024-11-26 09:24
> 看看是不是和 #45524 类似

的确

**Comment by afc163** [comment] 2024-11-26 14:33
Duplicate of #45524

**Closed by afc163** 2024-11-26 14:33 UTC
Labels: unconfirmed
