### ISSUE TITLE
Form.Item 没有子元素时，Grid 布局显示异常

### ISSUE THREAD

**Issue by fayhy** [ant-design/ant-design#16937] opened 2019-06-03 10:04 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rowcolformitem-eywix)

### Steps to reproduce
- 第二个 Form.Item 子元素为空，后续的 Col 布局不正确  
- Firxfox 显示正常，Chrome、IE、Edge 都有问题

![image](https://user-images.githubusercontent.com/35906690/58793905-ac0fab80-8629-11e9-8caa-e86561eb8dcd.png)

应该是这个 `ant-form-item-control` line-height 变更导致的
[commit e94ce11 diff](https://github.com/ant-design/ant-design/commit/e94ce11bd9636aaf43fc17c15cc491e592cf0ece?diff=unified#diff-51de536edf29809d26f0ccfab96f81fcL79)    
```diff
-    line-height: @form-component-max-height - 0.0001px; // https://github.com/ant-design/ant-design/issues/8220
+    line-height: @form-component-max-height;
```

### What is expected?
Grid 按顺序布局

### What is actually happening?
Grid 布局不正确，跳过了红框的位置

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | 16.6.0 |
| System | windows |
| Browser | Chrome |

**Comment by zombieJ** [comment] 2019-06-04 14:09
Duplicate of #16809

**Closed by zombieJ** 2019-06-04 14:09 UTC
