### ISSUE TITLE
Typography.Text (Title) component renders with error (Function components cannot be given refs)

### ISSUE THREAD

**Issue by ordenilluminaten** [ant-design/ant-design#19083] opened 2019-10-02 08:25 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-typography-reproduction-lwebn)

### Steps to reproduce
Render Typography.Title (or Text) component anywhere

### What is expected?
Rendering without errors

### What is actually happening?
I get an error:
index.js:1375 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `ResizeObserver`.
    in Typography (created by ResizeObserver)
    in ResizeObserver (created by LocaleReceiver)
    in LocaleReceiver (created by Base)
    in Base (created by Context.Consumer)
    in withConfigConsumer(Base) (created by Title)
    in Title (at src/index.tsx:5)

| Environment | Info |
|---|---|
| antd | 3.23.5 |
| React | 16.10.1 |
| System | Windows 10 Pro x64, Build 1809 |
| Browser | Google Chrome 77.0.3865.90 |

---
In 3.23.5 version you declared Typography component as 'const Typography: React.RefForwardingComponent<{}, InternalTypographyProps>'. So I think it's related with my problem. In 3.23.4 version I have no problems.

https://github.com/ant-design/ant-design/compare/3.23.5...master

**Comment by zombieJ** [comment] 2019-10-02 08:59
Duplicate of #19064

**Closed by zombieJ** 2019-10-02 08:59 UTC
