### ISSUE TITLE
Inline form's style conflict on mobile

### ISSUE THREAD

**Issue by LiHwsqh** [ant-design/ant-design#22009] opened 2020-03-09 05:39 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-f6z7f?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. create a Form with inline layout
2. specify the labelCol and wrapperCol
3. resize the window to 500px width

### What is expected?
The label and wrapper work as expect

### What is actually happening?
Label and Wrapper both has a 100% width, crowded in the same row and overflow their parent box,  because the "flex-basic" is set to 100% in media query when the screen width is less than 575px.
The default layout for form items overwrite my own config.

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.8.6 |
| System | mac 10.14.6 |
| Browser | chrome 80.0.3987.132 |

**Comment by LiHwsqh** [comment] 2020-03-09 08:52
@shaodahong Hey, thanks for your attention. I just take a look at your commit, and i think you might misunderstand my point. In my opinion, the 'form-item-label' and 'form-item-controll' element should display in the right size just like we specified in the `LableCol` and `WrapperCol` above, because it's "inline" mode.

Or, maybe we can just use the same style as the other case, each of them occupy a single row, at least it can show the data correctly.

**Comment by shaodahong** [comment] 2020-03-09 09:09
@LiHwsqh It's by design,  inline mode(or horizontal mode) `label` and `input` should  a single row when Media Screen less than 575px, if you used in 3.0 version, the layout should be the same now(after fixes)

**Comment by LiHwsqh** [comment] 2020-03-09 09:39
@shaodahong Thanks. And maybe you should put the 'flex-wrap: wrap' to the upper level. It's not work for now, just try it in the sandbox.

**Comment by shaodahong** [comment] 2020-03-09 09:49
https://codesandbox.io/s/antd-reproduction-template-y1phn You can try this demo, and if still have, please reproduce, thanks

**Comment by LiHwsqh** [comment] 2020-03-09 09:56
It works 😄

**Comment by zombieJ** [comment] 2020-03-09 11:45
@shaodahong, is that going on?

**Comment by shaodahong** [comment] 2020-03-09 12:15
> is that going on?

@zombieJ Fixed by #21907

**Closed** 2020-03-10 14:15 UTC
Labels: 🐛 Bug, 👷🏻‍♂️ Someone working on it
