### ISSUE TITLE
`Input`组件包含一个`Form.Item`的`addonBefore`的时候，如果路由跳转，会报错

### ISSUE THREAD

**Issue by aiyuchen** [ant-design/ant-design#22669] opened 2020-03-27 09:16 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zhucexinyonghu-ant-design-demo-tvbc3?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
点击上方演示链接，在打开的页面中点击链接【home】，能够在调试信息中看到错误；
说明：
① 表单组件是直接copy官方文档`Form`组件【注册用户】https://ant.design/components/form-cn/#components-form-demo-register
② 我在此去掉不需要的表单组件，添加路由

### What is expected?
点击路由跳转后应该不会报错

### What is actually happening?
点击路由链接跳转后会报错
<img width="945" alt="792C10F3-65D8-4B9F-AEEF-636EE8FFE6D7" src="https://user-images.githubusercontent.com/578141/77740842-e762e700-704e-11ea-99e1-3029a9d5583a.png">

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13.1 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment] 2020-03-27 09:19
Duplicate of #22544

**Closed by zombieJ** 2020-03-27 09:19 UTC
