### ISSUE TITLE
Menu 出现 onItemHover is not a function错误

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/ant-design#19463] opened 2019-10-28 10:46 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-fh1ul?fontsize=14)

### Steps to reproduce
打开控制台，鼠标移动到`删除`上

### What is expected?
![image](https://user-images.githubusercontent.com/23520283/67672572-311da780-f9b3-11e9-813b-c0906907cb63.png)

### What is actually happening?
onItemHover is not a function

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser |  77.0.3865.120 |

**Comment by Liu-Ya** [comment] 2019-10-28 10:54
```jsx
true && [
  <Menu.Divider key="divider" />,
  <Menu.Item key="delete">删除</Menu.Item>,
 ]
```

🤔这种写法就没问题了

**Comment by afc163** [comment] 2019-10-28 11:47
Duplicate of #18022

**Closed by afc163** 2019-10-28 11:47 UTC
