### ISSUE TITLE
Sider menu bug

### ISSUE THREAD

**Issue by datnguyen89** [ant-design/ant-design#35708] opened 2022-05-24 09:38 UTC
### Reproduction link

[https://github.com/datnguyen89/sider-menu-bug.git](https://github.com/datnguyen89/sider-menu-bug.git)

### Steps to reproduce

Open child menu
Click collapse button

### What is expected?

Sider and Menu collapse with out blink child menu

### What is actually happening?

Child menu appear and disappear before the Sider collapse

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 18.1.0 |
| System | window 10 |
| Browser | Chrome Version 101.0.4951.67 |

**Comment by datnguyen89** [comment] 2022-05-24 10:51
https://user-images.githubusercontent.com/55984933/170018301-b1b1a7d1-2362-43da-92b9-fcbc80a1bdf5.mp4

**Comment by afc163** [comment] 2022-05-24 14:44
Duplicate of https://github.com/ant-design/ant-design/issues/35343

**Closed by afc163** 2022-05-24 14:44 UTC
