### ISSUE TITLE
Found 2 elements with non-unique id 

### ISSUE THREAD

**Issue by ddzy** [ant-design/ant-design#13317] opened 2018-11-28 02:56 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
win10, Chrome70

### Reproduction link
[https://github.com/ant-design/ant-design/issues/10218](https://github.com/ant-design/ant-design/issues/10218)

### Steps to reproduce
Found 2 elements with non-unique id
Found 2 elements with non-unique id

### What is expected?
I hope you can fix this bug.

### What is actually happening?
I hope you can fix this bug.

**Comment by afc163** [comment] 2018-11-28 02:57
Duplicate of ##10218

**Comment by afc163** [comment] 2018-11-28 02:57
Don't create duplicate issue.

**Closed by afc163** 2018-11-28 02:57 UTC
