### ISSUE TITLE
Tooltip对于有zoom样式的元素定位错位

### ISSUE THREAD

**Issue by mushan0x0** [ant-design/ant-design#36537] opened 2022-07-15 06:41 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/wei-zhi-antd-4-21-6-forked-l11nqb?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

打开重现链接后把鼠标移动到按钮上

### What is expected?

箭头不错位

### What is actually happening?

<img width="625" alt="image" src="https://user-images.githubusercontent.com/29084441/179166674-748d68ba-a13a-4f88-8a74-5a53982687ff.png">

箭头错位

| Environment | Info |
| --- | --- |
| antd | 4.21.6 |
| React | 17 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment] 2022-07-15 07:13
Duplicate of #26681

**Closed by afc163** 2022-07-15 07:13 UTC
