### ISSUE TITLE
InputNumber数字输入框增加suffix

### ISSUE THREAD

**Issue by k983551019** [ant-design/ant-design#30523] opened 2021-05-14 08:51 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决不需要输入单位
想好Input   suffix一样
不使用formatter 格式化 
![HZX 66F}WGR(}3`) RW2Q{L](https://user-images.githubusercontent.com/48147837/118246503-9c1aca80-b4d4-11eb-8091-8da2f2337274.png)
### What does the proposed API look like?
suffix :ReactNode

**Comment by afc163** [comment] 2021-05-16 07:56
Duplicate of #14284

**Closed by afc163** 2021-05-16 07:56 UTC

**Comment by afc163** [comment] 2024-07-10 06:45
`suffix` prop has been added in https://github.com/ant-design/ant-design/pull/49674
