### ISSUE TITLE
Table中排序按钮问题

### ISSUE THREAD

**Issue by Colinlyj210** [ant-design/ant-design#11543] opened 2018-07-31 09:49 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Table中排序按钮点击的范围太小，希望可以点击单元格进行排序（包括点击单元格中的文字），第一次是正序第二次就倒序第三次正序...

### What does the proposed API look like?
不需要API，希望功能默认支持

**Comment by afc163** [comment] 2018-07-31 10:02
Duplicate of #9911

**Closed by afc163** 2018-07-31 10:02 UTC

**Comment by AnnieLeo** [comment] 2020-04-27 10:05
Table中排序按钮点击的范围太大,我里面放置了input的框,只要点击input框就会触发排序按钮,体验不好,希望排序按钮不要点击整个所在的table-cell就出发
