### ISSUE TITLE
Select component in IE browser Bug!!!

### ISSUE THREAD

**Issue by onlinelemon** [ant-design/ant-design#7934] opened 2017-10-19 02:29 UTC
### Version
2.13.6

### Environment
Win, IE11

### Reproduction link
[http://new-issue.ant.design/](http://new-issue.ant.design/)

### Steps to reproduce
Select component in IE browser, when the content is long, can not drag the drop-down box scroll bar

### What is expected?
Drag and drop scroll bar does not disappear

### What is actually happening?
Dragging the drop-down scroll bar, the drop-down box disappears

---
Select component when content is more

**Comment by ddcat1115** [comment] 2017-10-19 02:43
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by afc163** [comment] 2017-10-19 02:52
https://github.com/ant-design/ant-design/issues/1428

It should have been fixed before.

**Comment by afc163** [comment] 2017-10-19 03:00
![](https://gw.alipayobjects.com/zos/rmsportal/ahNKthpuYhcEhuIoJPde.gif)

**Comment by onlinelemon** [comment] 2017-10-19 06:14
Try Edge

**Comment by bert-huang** [comment] 2017-11-05 10:51
I can confirm this is happening.
Happens in IE11 only, the Windows Edge app doesn't trigger this bug.

The codepen is here: https://codepen.io/CookiePaw/pen/zPqQLp?editors=0011
It's just a simple select with enough entries to show the scrollbar. However I can't get the pen to work in IE11, got a bunch of errors like:
- SCRIPT5009: 'antd' is undefined
- SCRIPT438: Object doesn't support property or method 'startsWith'
- SCRIPT5007: Unable to get property 'set' of undefined or null reference

**Comment by shangxinliu** [comment] 2017-11-20 03:48
i have encounter the same question, try:
OS:win7
Broswer:IE11
the official demo have  the same bug.

**Comment by afc163** [comment] 2017-11-21 02:58
<img width="395" alt="image" src="https://user-images.githubusercontent.com/507615/33052577-80fcb84e-ceaa-11e7-9ce8-97211f0fdb3b.png">

![1](https://user-images.githubusercontent.com/507615/33052668-e938d776-ceaa-11e7-952a-a6f9451473c0.gif)

Tried IE11, still can't reproduce it.

**Comment by bert-huang** [comment] 2017-11-21 19:27
Seems like it's introduced in a newer version of IE11

![screenshot_1](https://user-images.githubusercontent.com/8079497/33092416-f6dbd5fe-cf5e-11e7-96b5-ad397b9ebc32.png)

**Comment by tianlang89757** [comment] 2018-01-17 03:51
There is still a problem with Internet explorer's Edge document mode.

**Comment by yesmeck** [comment] 2018-01-22 05:16
Same issue https://github.com/selectize/selectize.js/issues/1004

**Comment by tianlang89757** [comment] 2018-01-23 03:18
@afc163 @onlinelemon @bert-huang This problem I have solved, the solution is to delete antd.css stylesheet inside .ant-select-dropdown-menu under the overflow: auto style, you can solve the IE11 browser Edge document mode drag the scroll bar selection box Disappear problem

**Comment by afc163** [comment] 2018-01-23 03:32
@tianlang89757 Good job! Fixed in 1502d3604

**Comment by afc163** [comment] 2018-02-07 03:39
1502d36 cause the problem of #9276

**Comment by yesmeck** [comment] 2018-02-07 04:12
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15558714/

**Closed** 2018-02-07 12:14 UTC
