### ISSUE TITLE
Form.Item package RangePicker, it can't input by manual

### ISSUE THREAD

**Issue by K-Stella** [ant-design/ant-design#23604] opened 2020-04-26 03:31 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6n57x?file=/index.js)

### Steps to reproduce
Input the time by manual.

### What is expected?
Input the time by manual and click Tab to another picker,  the first picker value is saving.

### What is actually happening?
Input the time by manual and click Tab to another picker,  the first picker value is gone.

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 16.10.2 |
| System | macOS Catalina 10.15.3 |
| Browser | Chrome 81.0.4044.122 |

**Comment by afc163** [comment] 2020-04-26 03:53
Duplicate of #22118

**Closed by afc163** 2020-04-26 03:53 UTC
