### ISSUE TITLE
nextjs脚手架下antd组件样式闪动

### ISSUE THREAD

**Issue by Fled8617** [ant-design/ant-design#17725] opened 2019-07-19 02:13 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.lsz8617.com/login](https://www.lsz8617.com/login)

### Steps to reproduce
重复刷新页面即可

### What is expected?
不闪动

### What is actually happening?
组件先加载，样式后加载

| Environment | Info |
|---|---|
| antd | 3.20.3 |
| React | 16.8  |
| System | win |
| Browser | chrome |

---
css的确是先加载了，next里又带了mincss,页面上的input框尤其明显

**Comment by afc163** [comment] 2019-07-19 02:19
Duplicate of #16037

**Closed by afc163** 2019-07-19 02:19 UTC

**Comment by NAMANANAS** [comment] 2020-07-01 08:05
请问解决了吗，怎么解决

**Comment by zhangwei900808** [comment] 2023-02-09 06:50
```
 const [mounted, setMounted] = useState(false) useEffect(() => setMounted(true), [])
<div style={{ visibility: !mounted ? 'hidden' : '' }}><Component {...pageProps} /></div
```
[参考](https://github.com/vercel/next.js/issues/18769)
