### ISSUE TITLE
TimePicker参数placement失效

### ISSUE THREAD

**Issue by CNFeffery** [ant-design/ant-design#49275] opened 2024-06-06 03:31 UTC
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-pk7hrr-pgwtfu?file=demo.tsx)
![image](https://github.com/ant-design/ant-design/assets/49147660/25210396-bded-449a-8d3b-ef338a338280)

### Steps to reproduce

设置了不同placement参数的TimePicker组件，呈现出相同的悬浮层展开方位

### What is expected?

placement正常生效

### What is actually happening?

placement未正常生效

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | ^18.0.0 |
| System | win11 |
| Browser | Chrome |

**Comment by afc163** [comment] 2024-06-06 10:21
Duplicate of #48026

**Closed by afc163** 2024-06-06 10:21 UTC
Labels: unconfirmed
