### ISSUE TITLE
Complex Calendar

### ISSUE THREAD

**Issue by mitsol** [ant-design/ant-design#27400] opened 2020-10-27 09:17 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
There is the calendar component (https://ant.design/components/calendar/). However I was looking for finding a more complex example and also a week view with drag and drop functionality (similar to google calendar). Is there any plan to realize such a calendar in future?

### What does the proposed API look like?
I tried to find any complex solution, which is this one: https://github.com/jquense/react-big-calendar. Of course it works together with antd, but I'd love to see antd integrated such a component as well!

**Comment by afc163** [comment] 2020-10-27 09:23
Duplicate of #12591

**Closed by afc163** 2020-10-27 09:23 UTC
