### ISSUE TITLE
Support striped rows in tables

### ISSUE THREAD

**Issue by iainhallam** [ant-design/ant-design#8393] opened 2017-11-30 16:11 UTC
### What problem does this feature solve?
When you have a lot of data in a table, it's easy to skip between rows while reading across the line, so lots of places colour every other row (or every nth row) to make it clearer. Here are [some examples](https://www.google.com/search?tbm=isch&q=striped table rows).

### What does the proposed API look like?
Perhaps a new string property on the Table API to allow every nth row to be striped using the same selectors as the [CSS nth-child selectors](https://www.w3.org/TR/css3-selectors/#nth-child-pseudo):

* `stripes=even` - use the stripe colour for rows 2, 4, 6, ...
* `stripes=odd` - use the stripe colour for rows 1, 3, 5, ...
* `stripes=4` - use the stripe colour on row 4
* `stripes=4n` - use the stripe colour on every fourth row: 4, 8, 12, ...
* `stripes=4n 2` - use the stripe colour on  every fourth row, starting with the second row: 2, 6, 10, ...
* `stripes=-n 2` - use the stripe colour on the first two rows: 1, 2

**Comment by afc163** [comment] 2017-12-01 01:49
Duplicate of #7684

**Closed by afc163** 2017-12-01 01:49 UTC

**Comment by Evanlai8** [comment] 2018-03-07 05:06
I think the proposed is useful

**Comment by roshanshetty91** [comment] 2019-11-09 14:37
You could achieve it via css : 

table tr:nth-child(2n) td {
  background-color: #eee;
}

**Comment by shaahiiin** [comment] 2019-12-09 12:28
I found two ways to do this as of now:

One way is to use `rowClassName` prop of Table:
```css
.table-row-light {
    background-color: #ffffff;
}
.table-row-dark {
    background-color: #fbfbfb;
}
```
```jsx
<Table
  rowClassName={(record, index) => index % 2 === 0 ? 'table-row-light' :  'table-row-dark'}
  columns={columns}
  dataSource={dataSource}
  loading={loading}
/>

```

Second way is to use plain CSS
```css
.table-striped-rows tr:nth-child(2n) td {
    background-color: #fbfbfb;
}
.table-striped-rows thead {
    background-color: #f1f1f1;
}
```
```jsx
<Table
  className="table-striped-rows"
  columns={columns}
  dataSource={dataSource}
  loading={loading}
/>
```

Note that rowClassName works only for rows, so for CSS on table headers we can only use plain CSS like above.

**Comment by hekmatnajafi** [comment] 2021-04-26 14:28
an easy way:
`tableClass tr:nth-child(even) {
  background-color: #f2f2f2;
}`
`<Table className="tableClass" />`

**Comment by mellis481** [comment] 2021-12-13 19:38
The even-odd CSS suggestions made in this thread don't work with nested tables.

**Comment by KrishnaPG** [comment] 2022-07-12 06:17
The problem is, all these explicit css styles expect you to explicitly set the `even` and `odd` background colors, which you may not know correctly when using a custom theme.

It is better if the antd natively supports a `stripes` attribute and takes care of picking up the correct dark and light colors based on the current active theme.

**Comment by besabellacyrus** [comment] 2024-02-19 09:58
even and odd also not working properly for expanded row.

**Comment by DrainGangScholar** [comment] 2024-12-06 15:30
use rowClassName={(record)=>record.myCondition?'one':'two'}
.one > td{
    background: #eeeeff  !important;
}
.two > td{
    background: #ffffff  !important;
}

**Comment by Xmppsocalled** [comment] 2025-02-04 03:01
https://csser.space/questions/switch-between-every-other-pair-of-table-rows-then-repeat-with-the-following-two-pairs i have the solution

**Comment by Longshoez** [comment] 2025-03-03 23:26
why is it so hard to just add this feature? it seems like a no brainer to add this on a table component.
