### ISSUE TITLE
add a property to table "rowCanExpand(record)"

### ISSUE THREAD

**Issue by arthurgallo** [ant-design/ant-design#10270] opened 2018-04-26 19:09 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
this would allow someone to hide the expander if there is no data to show. 

### What does the proposed API look like?
<Table rowCanExpand={rec => if (rec.otherChildren && rec.otherChildren.length) return true else return false} ..../>

**Comment by yutingzhao1991** [comment] 2018-04-27 06:30
You mean this https://github.com/ant-design/ant-design/issues/6077 ?

**Comment by arthurgallo** [comment] 2018-04-27 11:41
No this is different. I am not using the children property, I'm using Table.expandedRowRender() to render another table. I want to suppress the icon if there is no data to show. Looking at the source of rc-table, if expandedRowRender is present, the icon is always rendered as well.

**Comment by yesmeck** [comment] 2018-04-27 12:30
Duplicate of #7817

**Closed by yesmeck** 2018-04-27 12:30 UTC
