### ISSUE TITLE
Horizontal Collapse

### ISSUE THREAD

**Issue by OmriBenShoham** [ant-design/ant-design#46553] opened 2023-12-20 16:21 UTC
### What problem does this feature solve?

I am looking for kind of menu that I can open from the side (it will open from right to left for example) - I do familiar with Collapse, Menu componenets - but couldn't find anything there that will help me build it.
So I imagine it as a menu that you have a button on it to close and open it, and when you decide to close it - it will minimize at the side.

### What does the proposed API look like?

I imagine it as the regular Collapse API with an attribute of a button that will be on the collapse border for close and open.
Also, it is important that the Collapse will get the attributes which should appear when the collapse is open and the attributes for when it closed.

I can also add an example from confluence application which have similar element:
When the menu open:
<img width="317" alt="Screenshot 2023-12-20 at 18 15 41" src="https://github.com/ant-design/ant-design/assets/26386874/19709d54-f500-4856-8781-66b8e72d8b41">

When the menu close:
<img width="53" alt="Screenshot 2023-12-20 at 18 15 54" src="https://github.com/ant-design/ant-design/assets/26386874/8cbd7c05-3525-49a7-bd4d-7d38026d9202">

**Comment by MadCcc** [comment] 2023-12-21 05:40
Duplicate of https://github.com/ant-design/ant-design/issues/44525

**Closed by MadCcc** 2023-12-21 05:40 UTC
Labels: unconfirmed

**Comment by OmriBenShoham** [comment] 2023-12-21 06:50
@MadCcc Just trying to understand - is the solution is to use : [https://pro-editor.antdigital.dev/components/draggable-panel](https://pro-editor.antdigital.dev/components/draggable-panel )?
Does antd working on something similar?
