### ISSUE TITLE
table的column设置fixed后dropdown组件改为受控组件下拉内容会出现double

### ISSUE THREAD

**Issue by hms181231** [ant-design/ant-design#20424] opened 2019-12-24 13:36 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigorous-golick-yqd63)

### Steps to reproduce
```js
{
      title: "Long Column",
      dataIndex: "address",
      key: "address 4",
      fixed: "right",
      width: 100,
     render: (_, record, index) => {
        const moreOperation = (
          <Menu>
            <Menu.Item key="menu-a">
              <a>test</a>
            </Menu.Item>
          </Menu>
        );

        return (
          <Dropdown
            visible={record.visible}
            overlay={moreOperation}
            onVisibleChange={visible => {
              this.setState(({ data }) => {
                const newData = [...data];
                newData[index].visible = visible;
                return { data: newData };
              });
            }}
            trigger={["click"]}
          >
            <Button>操作</Button>
          </Dropdown>
        );
      }
   }
```

### What is expected?
显示正常

### What is actually happening?
dropdown 下拉内容 双份

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.7 |
| System | os mojave |
| Browser | chrome v79 |

**Comment by afc163** [comment] 2019-12-24 14:34
Duplicate of #9262

**Closed by afc163** 2019-12-24 14:34 UTC
