### ISSUE TITLE
White background with white text in SubMenu when 'theme' props of Menu set to "dark"

### ISSUE THREAD

**Issue by wuweiran** [ant-design/ant-design#23062] opened 2020-04-08 21:10 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dingbudaohang-ant-design-demo-xh8vg)

### Steps to reproduce
Please hover on the SubMenu of the demo

### What is expected?
Dark background with white text.

### What is actually happening?
White background with white text.

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 0.62.2 |
| System | Windows 10 |
| Browser | 80.0.361.111 |

**Comment by afc163** [comment] 2020-04-09 02:59
Duplicate of #23031

**Closed by afc163** 2020-04-09 02:59 UTC
