### ISSUE TITLE
Using the virtual list of Table, when modifying dataSource, the header is not aligned with the body column.

### ISSUE THREAD

**Issue by wellssu0** [ant-design/ant-design#36127] opened 2022-06-20 04:33 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xu-ni-lie-biao-antd-4-21-3-forked-sdbljc)

### Steps to reproduce

1. 横向滚动表格
2. 点击reset dataSource按钮

### What is expected?

header和body竖向对齐

### What is actually happening?

header的ScrollX重置了，body的ScrollX还保原来的值

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | 16.14 |
| System | macos |
| Browser | Version 102.0.5005.115 (Official Build) (arm64) |

**Comment by afc163** [comment] 2022-06-20 05:09
Duplicate of #35665

**Closed by afc163** 2022-06-20 05:09 UTC

**Comment by wellssu0** [comment] 2022-06-20 05:55
> Duplicate of #35665

这应该是两个问题吧🤔

**Comment by wellssu0** [comment] 2022-06-21 03:02
问题解决了，获取scrollBodyRef.scrollLeft没有写get方法

```diff

const [connectObject] = useState(() => {
    const obj = {};
    Object.defineProperty(obj, "scrollLeft", {
-     get: () => null,
+     get: () => {
+       if (gridRef.current) {
+          return gridRef.current?.state?.scrollLeft || null;
+       }
+       return null;
+      },
      set: (scrollLeft) => {
        if (gridRef.current) {
          gridRef.current.scrollTo({
            scrollLeft
          });
        }
      }
    });
    return obj;
  });



```
