### ISSUE TITLE
希望给InputNumber组件添加addonAfter属性（Input组件里有这个属性）

### ISSUE THREAD

**Issue by q5222777** [ant-design/ant-design#22532] opened 2020-03-23 15:27 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
InputNumber这个数字组件，有很大的需求后面会带单位，像Input组件里有addonAfter这个参数，很好的解决里样式问题，但最需要这个属性的InputNumber组件却没有

### What does the proposed API look like?
给InputNumber组件添加像Input组件里的属性addonAfter

**Comment by afc163** [comment] 2020-03-23 15:37
Duplicate of #14284

**Closed by afc163** 2020-03-23 15:37 UTC

**Comment by q5222777** [comment] 2020-03-23 20:19
@afc163 为什么会被关闭？

**Comment by yoyo837** [comment] 2020-03-23 23:15
> @afc163 为什么会被关闭？

因为 Duplicate of #14284

**Comment by afc163** [comment] 2020-03-24 02:37
https://github.com/ant-design/ant-design/issues/10846#issuecomment-395663125
https://github.com/ant-design/ant-design/issues/1228#issuecomment-199338244
