### ISSUE TITLE
Add option to disable confirmation for TimePicker

### ISSUE THREAD

**Issue by KevinHurts** [ant-design/ant-design#22261] opened 2020-03-16 10:05 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In ant design v3 you could select a time and click outside the dropdown and your changes would be saved. In v4 you have to press ok to confirm. This is good behaviour but our users are used to clicking outside the dropdown instead of clicking on ok. A lot of our users are confused and don't know they have to press ok. I propose to add a prop to disable the confirmation button in the TimePicker.

### What does the proposed API look like?
I would propose the prop needsConfirmation (or something like that) which is set to true by default.
When needsConfirmation is false onChange is triggered each time the input is changed instead of only when pressing ok.
```
<TimePicker
    needsConfirmation={false}
    ...
/>
```

**Comment by zombieJ** [comment] 2020-03-16 10:27
Duplicate of #21189

**Closed by zombieJ** 2020-03-16 10:27 UTC
