### ISSUE TITLE
Menu Component click event will be triggered twice

### ISSUE THREAD

**Issue by changhui3067** [ant-design/ant-design#10418] opened 2018-05-08 09:59 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.0

### Environment
windows10, chrome&IE

### Reproduction link
[https://codepen.io/freyjachang/pen/BxJLXK?editors=0010](https://codepen.io/freyjachang/pen/BxJLXK?editors=0010)

### Steps to reproduce
1. hover on the menu button
2. click on the menu item

### What is expected?
there should be only one message info

### What is actually happening?
there are two message info after click the menuItem, one is "click one item 1", and the other is "click on item undefined"

---
add code "e.domEvent.preventDefault();" at the begining of click handle function can fix the issue temporarily but it should not the right way to fix.

**Comment by yesmeck** [comment] 2018-05-08 10:06
Duplicate of #10368

**Closed by yesmeck** 2018-05-08 10:06 UTC
