### ISSUE TITLE
Select组件 mode=‘tags’，作为Table组件中的Cell，即使结合scroll.y使用依然造成布局被破坏

### ISSUE THREAD

**Issue by liuhuagui** [ant-design/ant-design#20888] opened 2020-01-14 06:29 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://xgt80.csb.app/](https://xgt80.csb.app/)

### Steps to reproduce
在左侧输入框输入内容

### What is expected?
布局正常

### What is actually happening?
布局被破坏

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | 16.9.17 |
| System | windows7 |
| Browser | 版本 79.0.3945.117（正式版本） （32 位） |

**Comment by liuhuagui** [comment] 2020-01-14 06:30
![image](https://user-images.githubusercontent.com/21290865/72319567-757b3280-36da-11ea-93c7-ae91689192d0.png)

**Comment by zombieJ** [comment] 2020-01-14 06:47
Duplicate of #14859

**Closed by zombieJ** 2020-01-14 06:47 UTC
