### ISSUE TITLE
Context created by the App component has items with duplicate keys

### ISSUE THREAD

**Issue by tebafu** [ant-design/ant-design#39789] opened 2022-12-24 20:50 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-uecql6?file=/index.js)

### Steps to reproduce

1. Use the App component from antd anywhere in a react app.

### What is expected?

No warnings for duplicate keys in the console.

### What is actually happening?

The following warning is displayed in the console:

Warning: Encountered two children with the same key, `holder`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

React dev tools show the following items in the context created by the App component:

1. Anonymous Memo
2. Anonymous key="holder" ForwardRef
3. Anonymous key="holder" ForwardRef

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 18.2.0 |
| System | Microsoft Windows 10 Education Version 10.0.19044 Build 19044 |
| Browser | Chrome Version 108.0.5359.125 (Official Build) (64-bit) |

**Comment by li-jia-nan** [comment] 2022-12-25 03:49
- #39695

fixed

**Comment by zombieJ** [comment] 2022-12-25 07:51
Duplicate of #39694

**Closed by zombieJ** 2022-12-25 07:51 UTC
