### ISSUE TITLE
the bug about the combination of Popover,Popconfirm,Button

### ISSUE THREAD

**Issue by shihangbo** [ant-design/ant-design#8932] opened 2018-01-11 08:34 UTC
### Version
3.1.0

### Environment
os: 10.12.5, browser: chrome 63.0.3239.108 (Official Build) (64-bit), react: 16.2.0

### Steps to reproduce
1. my code:
<img width="919" alt="1ca020aa-37fb-4bfd-921c-d04480a9a2e8" src="https://user-images.githubusercontent.com/19473390/34815769-a18b0294-f6ed-11e7-91b7-d35779f372c0.png">

2. Scenario
i user variable "hasSelected" to control the Button is available. when the variable "hasSelected" is true, the Popover works ok!
but when the variable "hasSelected" is false, the Button don't be used. and when i move my mouse on the Popover, the content is displayed, but when i moveout my mouse from the Button, the content don't disappear.

### What is expected?
the issue is resolved

### What is actually happening?
as described above

**Comment by yesmeck** [comment] 2018-01-11 10:32
Duplicate of https://github.com/react-component/tooltip/issues/18

**Closed** 2018-01-11 10:32 UTC
