### ISSUE TITLE
Deleting an item from a dynamic form does not reflect correctly on the onFinish function when using React.StrictMode

### ISSUE THREAD

**Issue by Jdash99** [ant-design/ant-design#27869] opened 2020-11-19 03:05 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dynamic-form-nest-items-antd480-forked-xf6bh)

### Steps to reproduce
1. Add 2 rows to the dynamic form and enter values for them.
2. Delete the last one.
3. Click the submit button
3. Check values in the onFinish function.

### What is expected?
The values should now be an array with only one element, the first one.

### What is actually happening?
The values are actually an array with 2 elements with the properties of the last one having been changed to undefined.

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 17.0.1 |
| System | Windows 10 Pro |
| Browser | Chrome |

---
The code seems to work fine if I remove React Strict Mode

**Comment by afc163** [comment] 2020-11-19 03:36
Duplicate of #27770

**Closed by afc163** 2020-11-19 03:36 UTC
