### ISSUE TITLE
react严格模式使用Menu组件控制台警告"findDOMNode is deprecated in StrictMode"

### ISSUE THREAD

**Issue by boiboif** [ant-design/ant-design#41079] opened 2023-03-06 01:54 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/proud-sun-qrfhs5?welcome=true)

### Steps to reproduce

npm create vite@latet
pnpm add antd
使用官方文档Menu组件第一个例子
控制台报警告Warning: findDOMNode is deprecated in StrictMode. 

### What is expected?

解决控制台报警告

### What is actually happening?

控制台报警告

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18.2.0 |
| System | win10 |
| Browser | chrome 103.0.5060.134 |

**Comment by Yuiai01** [comment] 2023-03-06 01:57
Duplicate of https://github.com/ant-design/ant-design/issues/35361

**Comment by afc163** [comment] 2023-03-06 02:01
Duplicate of https://github.com/ant-design/ant-design/issues/35361

**Closed by afc163** 2023-03-06 02:01 UTC
Labels: unconfirmed
