### ISSUE TITLE
Input

### ISSUE THREAD

**Issue by suhaizeng** [ant-design/ant-design#28417] opened 2020-12-18 08:38 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/priceless-montalcini-qzif1?file=/index.js)

### Steps to reproduce
限制长度 汉字连续输入如超过长度 ，则输入全部为英文字母

### What is expected?
输入长度过长，截取符合长度即可， antd v3.X.X版本正常

### What is actually happening?
输入汉字长度超过，自动赋值字母

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | v16.8.6 |
| System | macOS |
| Browser | chrome v87.0.4280.88 |

**Comment by afc163** [comment] 2020-12-19 05:29
请修改为有语义的标题。

**Comment by afc163** [comment] 2020-12-21 07:25
Duplicate of #27116

**Closed by afc163** 2020-12-21 07:25 UTC
