### ISSUE TITLE
ant.design/components/modal

### ISSUE THREAD

**Issue by stanislav-zavistnov** [ant-design/ant-design#50234] opened 2024-08-04 17:54 UTC
### Reproduction link

[https://ant.design/components/modal](https://ant.design/components/modal)

### Steps to reproduce

just open ant.design/components/modal

### What is expected?

normal work

### What is actually happening?

fatal error after 5 seconds on page ant.design/components/modal

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | react |
| System | windows |
| Browser | chrome |

---
I can not use it

**Comment by AdamFipke** [comment] 2024-08-04 21:49
Can confirm, going onto the official modal documentation will cause the whole page to go white after a few seconds.

**Comment by AsuraKev** [comment] 2024-08-04 21:51
Cant seem to replicate it :/

**Comment by afc163** [comment] 2024-08-05 04:52
Duplicate of https://github.com/ant-design/ant-design/issues/50232

**Comment by afc163** [comment] 2024-08-05 04:52
Fixed in https://github.com/ant-design/ant-design/commit/7b7525ad09b49aa562875ddac039cca3e4f7c70d

**Closed by afc163** 2024-08-05 04:52 UTC
Labels: unconfirmed
