### ISSUE TITLE
Antd table without pagination is slow with big amounts of data

### ISSUE THREAD

**Issue by Sven65** [ant-design/ant-design#19085] opened 2019-10-02 13:30 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/sven65/pen/jONgZyx](https://codepen.io/sven65/pen/jONgZyx)

### Steps to reproduce
1. Change the `rows` variable from `10` to `1000`
2. Try to select a row

### What is expected?
I'm expecting it to not take 3 seconds to have a row be selected.

### What is actually happening?
It takes 3 seconds to select a row.

| Environment | Info |
|---|---|
| antd | 3.23.5 |
| React | 16.9.0 |
| System | Windows 10 |
| Browser | Chrome  76.0.3809.132 |

**Comment by afc163** [comment] 2019-10-03 09:31
Duplicate of #10431

**Closed by afc163** 2019-10-03 09:31 UTC
