### ISSUE TITLE
Form.item extra collapsed with Input.TextArea count

### ISSUE THREAD

**Issue by Cygra** [ant-design/ant-design#29805] opened 2021-03-18 07:50 UTC
- [√] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-f31sw?file=/index.js)

### Steps to reproduce
as in the codesandbox link

### What is expected?
Form.Item extra rendered below Input.TextArea count

### What is actually happening?
Form.item extra collapsed with Input.TextArea count

| Environment | Info |
|---|---|
| antd | 4.14.0 |
| React | 17.0.1 |
| System | macOS Catalina 10.15.6 |
| Browser | Google Chrome 89.0.4389.90 |

**Comment by Cygra** [comment] 2021-03-18 07:56
It seems that the Input.TextArea is wrapped in a div which has a `:after`，and the `:after` has a negative `margin-bottom`.
![image](https://user-images.githubusercontent.com/34186314/111591350-48f10800-8802-11eb-9bda-1c479bd51f7a.png)

**Comment by Cygra** [comment] 2021-03-18 08:01
https://github.com/ant-design/ant-design/pull/29245

重复了。

**Comment by Cygra** [comment] 2021-03-18 08:04
Oops, it's still collapsed.

![image](https://user-images.githubusercontent.com/34186314/111592297-95891300-8803-11eb-8df8-d0d2e50df8fc.png)

**Comment by afc163** [comment] 2021-03-19 01:35
Duplicate of #29709

**Closed by afc163** 2021-03-19 01:35 UTC
