### ISSUE TITLE
Tree树形控件设置了draggable后，如何让叶子节点不能拖拽？

### ISSUE THREAD

**Issue by ZhangMingZhao1** [ant-design/ant-design#19350] opened 2019-10-22 09:53 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
因为draggable属性是在Tree组件上的，不能细控制到每个TreeNode，需求是叶子节点的TreeNode不允许拖拽怎么办呢？（在onDragStart可以拿到拖拽的Node节点，但是不过return什么也不能阻止可拖拽的行为。）

### What does the proposed API look like?
能在每个TreeNode上做到拖拽的开关属性

**Comment by afc163** [comment] 2019-11-01 02:58
Duplicate of #15926 and #18226

**Closed by afc163** 2019-11-01 02:58 UTC
