### ISSUE TITLE
日期选择框支持多选

### ISSUE THREAD

**Issue by wsxe9988** [ant-design/ant-design#42844] opened 2023-06-05 15:05 UTC
### What problem does this feature solve?

日期选择框支持多选

### What does the proposed API look like?

日期选择框支持多选

**Comment by afc163** [comment] 2023-06-06 07:48
Duplicate of #4447

**Closed by afc163** 2023-06-06 07:48 UTC
Labels: unconfirmed

**Comment by daydayupon** [comment] 2023-09-08 09:29
什么时候能实现啊
