### ISSUE TITLE
被popconfirm包裹的button被禁用后，点击button还是会弹出popconfirm

### ISSUE THREAD

**Issue by CTheMyth** [ant-design/ant-design#14433] opened 2019-01-19 02:03 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/CTheMyth/Ant.design-bug](https://github.com/CTheMyth/Ant.design-bug)

### Steps to reproduce
点击禁用的button，依然弹出popconfirm

### What is expected?
ant-design 3.10.4版本被popconfirm包裹的button被禁用后，点击button是不会弹出popconfirm的，但3.12.3却会

### What is actually happening?
被popconfirm包裹的button被禁用后，点击button还是会弹出popconfirm

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16.6.0 |
| System | win10 |
| Browser | Chrome 70.0.3538.102（正式版本） |

**Comment by zombieJ** [comment] 2019-01-19 09:42
duplicate of #13351

**Closed by zombieJ** 2019-01-19 09:42 UTC
