### ISSUE TITLE
DropdownRender doesn't trigger the click event everytime

### ISSUE THREAD

**Issue by shahlav** [ant-design/ant-design#18508] opened 2019-08-27 17:52 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/hungry-brown-jv9pm)

### Steps to reproduce
Click on dropdown and Click on the `  Add Item`.
Do this multiple times and check the console to see the log
Click event doesn't trigger everytime

### What is expected?
Click event should be triggered everytime

### What is actually happening?
Click event doesn't trigger everytime. Sometimes it doesn't trigger the event

| Environment | Info |
|---|---|
| antd | 3.22.1 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Chrome |

---
I want first option to be   Add item and whenever user clicks it we will update the dropdown list programmatically.

**Comment by afc163** [comment] 2019-08-28 03:06
Duplicate of #13448

**Closed by afc163** 2019-08-28 03:06 UTC
