### ISSUE TITLE
Possibility to drag Select Tags around

### ISSUE THREAD

**Issue by rbrugnollo** [ant-design/ant-design#9847] opened 2018-03-28 14:38 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
 I need to drag and drop tags from one Select to another, and for that I'd like to use http://react-dnd.github.io/.

I tried to make it work but so far I couldn't. And I believe that's because somehow the Select or Tag component doesn't let my component inside the tag to fire the "dragstart" event.

You can replicate the problem here on Codesandbox: https://codesandbox.io/s/m5kz2vw5p

### What does the proposed API look like?
There would be no API for this feature, and just need that the component inside a Tag to fire dragstart event.

**Comment by yesmeck** [comment] 2018-03-29 06:16
Duplicate of #9459

We treat tags as an unordered list, so adding dragging makes no sense for select.

**Closed by yesmeck** 2018-03-29 06:16 UTC
Labels: Component: Select

**Comment by rbrugnollo** [comment] 2018-03-29 10:51
@yesmeck thanks for your answer.

My idea is not to drag the tags around the same Select to order them, I'd like to be able to drag tags from one Select to another. Does that make sense?

If this doesn't make sense to antd and everybody who uses this, would it be possible to just tell me what's preventing the dragstart event? That way I could make this change locally and get the feature my client wants.

**Comment by yesmeck** [comment] 2018-03-29 11:57
The reason is we prevent the mouseDown default behavior here https://github.com/react-component/select/blob/bc6da392a16512bf8100818e55548974be2124e9/src/Select.jsx#L1196 for some reasons.

**Comment by rbrugnollo** [comment] 2018-03-29 12:15
Thanks @yesmeck. That helps me a lot!

**Comment by macc6579** [comment] 2020-08-03 12:53
> Thanks @yesmeck. That helps me a lot!

How did you solve this problem? Can you tell me a reference, thank you very much！

**Comment by aralroca** [comment] 2020-10-19 08:54
I'm also interested in the solution 👏

**Comment by ChenCyl** [comment] 2020-11-04 08:07
> > Thanks @yesmeck. That helps me a lot!
> 
> How did you solve this problem? Can you tell me a reference, thank you very much！

Hi, you should add this event to your Tag label:

```
onMouseDown={e => {e.stopPropagation();}}
```

@rbrugnollo has mentioned it [here](https://stackoverflow.com/questions/49498684/cannot-get-antd-select-tags-to-be-draggable/49559038#49559038?newreg=08b60bdfde344fb9a26d18d17476a7f2).
