### ISSUE TITLE
Multiple Select trigger `submit` event on `enterKey`

### ISSUE THREAD

**Issue by m1n0s** [ant-design/ant-design#10499] opened 2018-05-14 10:43 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
Windows 10, Chrome 66.0.3359.139

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/012mmm39yp)

### Steps to reproduce
Add multiple (tags) select to form
try to add some tag or pick value by enter key
observe that `submit` triggered

### What is expected?
Submit event doesn't triggered by Enter key in multiple select (as it was before)

### What is actually happening?
submit does triggered by Enter key

---
I couldn't find this change is change log (to clarify is it a bug or expected behavior).
We faced with it when upgrading from `3.2.0` to `3.5.1`.

**Comment by m1n0s** [comment] 2018-05-26 16:58
@dan-dr yeah, it could help but only like a temporary workaround.

**Comment by chenshuai2144** [comment] 2018-06-11 05:50
fixed in https://github.com/react-component/select/commit/804ede42762725e8e8e43c83989571fbdef005ca

**Comment by afc163** [comment] 2018-06-11 05:55
Duplicate of #10861

**Closed by afc163** 2018-06-11 05:55 UTC
Labels: Component: Select
