### ISSUE TITLE
是否有可能为Table组件增加属性作用于额外展开行

### ISSUE THREAD

**Issue by chaiguanpeng** [ant-design/ant-design#17254] opened 2019-06-23 14:12 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues/6895) of this repository 

### What problem does this feature solve?
Table组件的expandedRowRender属性用来显示额外的展开行来描诉额外信息，是否可以添加多个属性来控制额外信息的位置(在行的上面或者下面)

### What does the proposed API look like?
可以加expandedPosition="top" 属性

![28353724-9db96202-6c8f-11e7-8234-1f4ef4937f25](https://user-images.githubusercontent.com/22465693/59977456-c2df6780-9603-11e9-8c06-90d0fff8fffb.png)

**Comment by afc163** [comment] 2019-06-24 02:23
Duplicate of #15630

**Closed by afc163** 2019-06-24 02:23 UTC
