### ISSUE TITLE
级联选择是否考虑支持虚拟滚动  

### ISSUE THREAD

**Issue by CoCoManYY** [ant-design/ant-design#50482] opened 2024-08-19 07:37 UTC
### What problem does this feature solve?

1w+ 条数据下，减少dom数量，避免页面卡顿

### What does the proposed API look like?

virtual

**Comment by afc163** [comment] 2024-08-19 07:38
Duplicate of https://github.com/ant-design/ant-design/issues/26645

**Closed by afc163** 2024-08-19 07:38 UTC
Labels: 💡 Feature Request
