### ISSUE TITLE
[DatePicker] Hope to support microseconds for time

### ISSUE THREAD

**Issue by dengfuping** [ant-design/ant-design#29955] opened 2021-03-30 07:02 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/riqishijianxuanze-antd494-forked-c8dm7)

### Steps to reproduce
Select a date and view the format result.

### What is expected?
Microseconds value should be real.

### What is actually happening?
Microseconds value is always `000`.
![image](https://user-images.githubusercontent.com/14918822/112946766-7de94d00-9168-11eb-8fef-a115a531de61.png)

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 16.14.0 |
| System | MacOS 10.15.5 |
| Browser | Chrome 81.0.4044.138 |

**Comment by afc163** [comment] 2021-03-30 08:47
Duplicate of #16466

**Closed by afc163** 2021-03-30 08:47 UTC
