### ISSUE TITLE
Typescript Error for Auto-complete

### ISSUE THREAD

**Issue by jon-r** [ant-design/ant-design#12793] opened 2018-10-23 08:53 UTC
- [ x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.2

### Environment

- mac OS 10.13  
- Intellij IDE 2018.2  
- react 16.4.2  
- typescript 3.0.1

### Reproduction link
[https://gist.github.com/jon-r/3078a56733440dcdf8d87c98219450b2](https://gist.github.com/jon-r/3078a56733440dcdf8d87c98219450b2)

### Steps to reproduce
The `onFocus` type does not exist in the AutoComplete prop interface.
Pasting the demo gist into an existing react tsx project will raise a type error

### What is expected?
that onFocus is a valid prop

### What is actually happening?
TS2339 'on focus does not exist on ... AutoCompleteProps'

**Comment by afc163** [comment] 2018-10-23 09:19
PR is welcome~

**Comment by jon-r** [comment] 2018-10-23 09:34
testing this, it is just the interface that needs changing, functionally works the same

```
        const AutoCompleteAllowProps = AutoComplete as any;
        const field =  (
            <AutoCompleteAllowProps
                onFocus={this.setFocused}
                {...fieldProps}
            />
        );
```

will correctly trigger the focus event

**Comment by alireza-mh** [comment] 2018-10-27 13:39
i tried and everything was fine and i couldn't replicate the error. 
also i tried it on stackblitz and everything was fine there as well.
https://stackblitz.com/edit/react-ts-cn2dqa

**Comment by zombieJ** [comment] 2018-10-29 12:54
hi @jon-r, could you provide an online reproduce about this? Since `onFocus` is defined: https://unpkg.com/antd@3.10.3/lib/auto-complete/index.d.ts

**Comment by muzea** [comment] 2018-10-29 13:55
@zombieJ https://unpkg.com/antd@3.10.1/lib/auto-complete/index.d.ts  3.10.1 also defines `onBlur`

see https://github.com/ant-design/ant-design/issues/12498

**Comment by zombieJ** [comment] 2018-10-29 14:41
Maybe its on [3.10.0](https://unpkg.com/antd@3.10.0/lib/auto-complete/index.d.ts).

@muzea, let's close this issue first but still continue work with your PR : )

**Closed by zombieJ** 2018-10-29 14:41 UTC
Labels: help wanted
