### ISSUE TITLE
Horizontal Menu breaks into a second line when the first line overflows the container

### ISSUE THREAD

**Issue by pobch** [ant-design/ant-design#30725] opened 2021-05-27 07:05 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu/](https://ant.design/components/menu/)

### Steps to reproduce
1. Go to the official document https://ant.design/components/menu/
2. Narrow down the viewport to 656 width
3. Go to the first example (i.e. Top Navigation)
4. The menu is broken into 2 lines

### What is expected?
The menu should be 1 line with `...` icon at the end of the line.

### What is actually happening?
The menu is broken into 2 lines

![image](https://user-images.githubusercontent.com/19894957/119780961-a2f20600-bef4-11eb-97b1-4bc27a217a6f.png)

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | 17.0.2 |
| System | 11 |
| Browser | Firefox 88, Chrome 90 |

**Comment by afc163** [comment] 2021-05-27 07:09
Duplicate of #30662

**Closed by afc163** 2021-05-27 07:09 UTC

**Comment by Abakanmeister** [comment] 2021-06-15 15:26
> Duplicate of #30662

omg. those is CHINESE!!!

**Comment by afc163** [comment] 2021-06-15 15:29
@Abakanmeister Fixed in https://github.com/ant-design/ant-design/pull/30672
