### ISSUE TITLE
时间轴mode设置为left后自动居中了，有什么办法可以默认居左显示 antd

### ISSUE THREAD

**Issue by Mathround** [ant-design/ant-design#29722] opened 2021-03-11 08:06 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
建议可以默认居左显示

### What does the proposed API look like?
建议可以默认居左显示

**Comment by afc163** [comment] 2021-03-11 08:23
Duplicate of #26485

**Closed by afc163** 2021-03-11 08:23 UTC
