### ISSUE TITLE
dist/antd-with-locales.min.js 不可用

### ISSUE THREAD

**Issue by yulrosy** [ant-design/ant-design#24182] opened 2020-05-15 08:26 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
  <script src="https://cdn.jsdelivr.net/npm/antd@4.2.2/dist/antd-with-locales.min.js"></script>

### What is expected?
正常

### What is actually happening?
antd-with-locales.min.js:28 Uncaught ReferenceError: E1g is not defined

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.13.1 |
| System | MacOS 10.15.4 |
| Browser | chrome  81.0.4044.138 |

**Comment by zombieJ** [comment] 2020-05-15 08:45
Duplicate of #24116

**Closed by zombieJ** 2020-05-15 08:45 UTC

**Comment by yoyo837** [comment] 2020-05-15 08:58
@yulrosy 周末了，快发版了。
