### ISSUE TITLE
Form scrollToFirstError 对 Upload 失效

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#48171] opened 2024-03-29 09:52 UTC
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-14xjhu?file=demo.tsx)

### Steps to reproduce

1. 点击 submit，能自动滚动到 Username
2. Username 输入内容，再次点击 submit

### What is expected?

滚动到 upload

### What is actually happening?

没有滚动

| Environment | Info |
| --- | --- |
| antd | 5.15.4 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment] 2024-03-29 10:01
Duplicate of https://github.com/ant-design/ant-design/issues/28869

**Closed by afc163** 2024-03-29 10:01 UTC
Labels: unconfirmed
