### ISSUE TITLE
Form 组件配置项scrollToFirstError，在包含Form.List且有添加rule时不生效

### ISSUE THREAD

**Issue by pipu11qiao** [ant-design/ant-design#42316] opened 2023-05-12 09:04 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dong-tai-zeng-jian-biao-dan-xiang-antd-5-4-7-forked-vc89u4?file=/demo.tsx)

### Steps to reproduce

点击提交按钮

### What is expected?

点击提交按钮滚动到错误的表单项

### What is actually happening?

未发生滚动

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | 18.2.0 |
| System | mac |
| Browser | Chrome/112.0.0 |

**Comment by afc163** [comment] 2023-05-12 09:48
Duplicate of https://github.com/ant-design/ant-design/issues/33030

**Closed by afc163** 2023-05-12 09:48 UTC
Labels: unconfirmed
