### ISSUE TITLE
table如何进行拖拽表头进行列宽的调整？

### ISSUE THREAD

**Issue by yyyyffqqqq** [ant-design/ant-design#49604] opened 2024-06-26 04:52 UTC
### What problem does this feature solve?

用户可以根据列数据的长短或者喜好，便捷的调整列宽

### What does the proposed API look like?

提供配置参数，并且能够获取到列宽的变化

**Comment by afc163** [comment] 2024-06-26 06:06
Duplicate of https://github.com/ant-design/ant-design/issues/32811

**Closed by afc163** 2024-06-26 06:06 UTC
Labels: unconfirmed
