### ISSUE TITLE
Multiple columns filterdropdown can be opened at the same time

### ISSUE THREAD

**Issue by NaveenKumarVUK** [ant-design/ant-design#43248] opened 2023-06-28 07:44 UTC
### Reproduction link

[https://ant.design/components/table#components-table-demo-head](https://ant.design/components/table#components-table-demo-head)

### Steps to reproduce

In the latesh version(5.6.3) can't we keep only one column filter dropdown active like we had in version 4?

### What is expected?

In the table we should be able to see only one column active filterdropdown. 

### What is actually happening?

We can able to select all the columns filter and each column filterdropdown will be visible in the screen at same time. in older versin if we click on next column filter, the previus column filter will be auto closed.

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | 16.14.0 |
| System | Windows 10 |
| Browser | Google Chrom |

![image](https://github.com/ant-design/ant-design/assets/104412999/925173dd-852f-4d9c-a554-1ea0daa802d2)

**Comment by MadCcc** [comment] 2023-06-28 07:53
Duplicate of https://github.com/ant-design/ant-design/issues/43093

**Closed by MadCcc** 2023-06-28 07:53 UTC
Labels: unconfirmed
