### ISSUE TITLE
updating to 4.1.1, The menu has some style error with the mode 'vertical' and the theme 'dark' 

### ISSUE THREAD

**Issue by jeessy2** [ant-design/ant-design#22977] opened 2020-04-07 03:36 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qiehuancaidanleixing-ant-design-demo-y73tb?file=/index.js)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/6205259/78627365-d8d4c500-78c3-11ea-9fb2-55a882187142.png)
It's https://github.com/ant-design/ant-design/pull/22908  problem, maybe

### What is expected?
should be dark

### What is actually happening?

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16 |
| System | all |
| Browser | chrome |

**Comment by zombieJ** [comment] 2020-04-07 03:54
@AshoneA , pls help to check this.

**Comment by afc163** [comment] 2020-04-07 04:02
Duplicate of #22949

**Closed by afc163** 2020-04-07 04:02 UTC
