### ISSUE TITLE
Customize Table sort Asc/Desc Icon

### ISSUE THREAD

**Issue by phuhd-0935** [ant-design/ant-design#34693] opened 2022-03-24 10:51 UTC
### What problem does this feature solve?

In version 4.18.8, I can't override the icon of sort Asc/Desc Icon in Table component.

### What does the proposed API look like?

Apply new props to customise this, likely AscIcon, DescIcon

**Comment by afc163** [comment] 2022-03-24 12:31
Duplicate of #19561

**Closed by afc163** 2022-03-24 12:31 UTC

**Comment by afc163** [comment] 2023-05-22 04:04
Supported in https://github.com/ant-design/ant-design/pull/42498
