### ISSUE TITLE
Modal is closing when onMouseUp event fires outside the modal frame

### ISSUE THREAD

**Issue by liadbe** [ant-design/ant-design#16009] opened 2019-04-10 16:25 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When I hold mouse down inside modal frame (border) and release it outside the modal, the modal is closing (with <Modal maskClosable={true} />).
I would think that I would want to close modal only when clicking (mouse down & up) would happen outside the modal. But in this case, the mouseDown event fires inside the modal but the MouseUp fires outside. 

### What does the proposed API look like?
The modal will not be closed if only the mouse click is held down inside the modal and released outside the modal, but only if clicked outside.

**Comment by zombieJ** [comment] 2019-04-10 16:34
Duplicate of #15891

**Closed by zombieJ** 2019-04-10 16:34 UTC
