### ISSUE TITLE
form.item 的 shouldUpdate 为函数时，form.getFieldError获取不到最新的值

### ISSUE THREAD

**Issue by DY-ZYQ** [ant-design/ant-design#33286] opened 2021-12-14 07:26 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-j6euu)

### Steps to reproduce
直接打开控制台看console.log，发现form.getFieldError('zyq')一直打印空数组

### What is expected?
错误对象的数组

### What is actually happening?
空数组

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 16.9.0 |
| System | 12.0.1 |
| Browser | 96.0.4664.93 |

**Comment by afc163** [comment] 2021-12-15 03:47
Duplicate of #26888

**Closed by afc163** 2021-12-15 03:47 UTC
