### ISSUE TITLE
select组件使用自定义value字段，回车无法选中值(已定位到原因)

### ISSUE THREAD

**Issue by zhongweiming** [ant-design/ant-design#34047] opened 2022-02-14 13:11 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/zhongweiming/antd-problem](https://github.com/zhongweiming/antd-problem)

### Steps to reproduce
Select组件使用fieldNames自定义value字段，然后使用回车选择选项，无法选中。点击则可以

### What is expected?
能选中

### What is actually happening?
未选中

| Environment | Info |
|---|---|
| antd | 4.18.3 |
| React | 17.0.0 |
| System | macOS Mojave |
| Browser | chrome 98 |

---
具体详情见重现那个链接

**Comment by MadCcc** [comment] 2022-02-15 03:56
Duplicate of https://github.com/ant-design/ant-design/issues/33815
rc-select 已经更新了，删掉 node_modules 重新装一下

**Closed by MadCcc** 2022-02-15 03:57 UTC

**Comment by xufromxu** [comment] 2022-11-02 09:01
请教一下，这种组件的bug是怎么定位的呢

**Comment by zhongweiming** [comment] 2023-01-30 11:07
> 

要看一下源码的
