### ISSUE TITLE
Table Drag sorting with handler overlaps rows on drag

### ISSUE THREAD

**Issue by nicolabosco87** [ant-design/ant-design#25481] opened 2020-07-07 12:28 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gju0w)

### Steps to reproduce
- Drag the first row (John Brown) on the second row (Jim Green) and drop
- Now the "Jim Green" is in the first position and "John Brown" is in the second position
- Drag the current first row (Jim Green) on the second row (John Brown) and drop

(basically every drag after the first one until the original order will be restored)

### What is expected?
The currently not dragged items should be in the correct starting position.

### What is actually happening?
Trasform has been applied right after the dragging (without moving over other elements) putting the elements in a wrong position.
If the elements are setted in the original order the dnd visualization is correct.

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome 83.0.4103.116 |

---
The issue is visible directly from the documentation (https://ant.design/components/table/#components-table-demo-drag-sorting-handler) and in fact the link to minimal reprodution is the documentation's codesandbox example.

**Comment by afc163** [comment] 2020-07-10 09:10
Duplicate of #25481

**Closed by afc163** 2020-07-10 09:10 UTC
Labels: help wanted

**Comment by yoyo837** [comment] 2020-07-10 09:14
写过issue编号了吗？

**Comment by yoyo837** [comment] 2020-07-10 09:15
写错issue编号了吗？与当前编号相同了！
