### ISSUE TITLE
Table 组件设置 scroll，在宽高未超出的情况下依旧显示滚动条

### ISSUE THREAD

**Issue by Overcase** [ant-design/ant-design#32065] opened 2021-09-07 08:11 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gu-ding-tou-he-lie-antd-4-17-0-alpha-0-forked-vzbyv?file=/index.js)

### Steps to reproduce
无

### What is expected?
未超出宽高时不显示滚动条

### What is actually happening?
未超出宽高时仍旧显示滚动条

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.9.0 |
| System | windows |
| Browser | chrome-87.0.4280.88 |

**Comment by Overcase** [comment] 2021-09-07 08:12
简单看了下，将 overflow 设置为 auto 就可以解决这个问题，我能否修复这个问题

**Comment by yoyo837** [comment] 2021-09-07 08:14
这好像是刻意为之的, 不太记得了. 为了对齐表头.

**Comment by Overcase** [comment] 2021-09-07 08:22
> 这好像是刻意为之的, 不太记得了. 为了对齐表头.

这样子的吗。。

**Comment by afc163** [comment] 2021-09-07 10:21
Duplicate of #29082

**Closed by afc163** 2021-09-07 10:21 UTC
