### ISSUE TITLE
InputNumber缺少清除属性allowClear（Input组件里有这个属性）

### ISSUE THREAD

**Issue by q5222777** [ant-design/ant-design#22533] opened 2020-03-23 15:33 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
InputNumber缺少清除属性allowClear

### What does the proposed API look like?
像Input组件一样给InputNumber添加allowClear属性

**Comment by afc163** [comment] 2020-03-23 15:37
Duplicate of #18566

**Closed by afc163** 2020-03-23 15:37 UTC
