### ISSUE TITLE
Support Table Summaries

### ISSUE THREAD

**Issue by ChuckJonas** [ant-design/ant-design#8790] opened 2017-12-30 15:52 UTC
### What problem does this feature solve?
It's very common for tables to have summaries of certain columns (sum, average, etc).  However, with the table component, there doesn't seem to be any way to do this.  A footer can be added (which is typically where these summed values would go), but there doesn't seem to be any way to get the values to line up with the desired column.  

### What does the proposed API look like?
One possible way of solving this would be to add a "Summary" function to the `Table Column`: `(text, record) => string`

**Comment by afc163** [comment] 2018-01-01 07:05
Duplicate of #5710

**Closed by afc163** 2018-01-01 07:05 UTC
