### ISSUE TITLE
table组件在数据量比较大时实现虚拟滚动和滚动加载

### ISSUE THREAD

**Issue by hejinhua** [ant-design/ant-design#18651] opened 2019-09-04 06:04 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前table只支持分页加载，公司业务需求不用分页，需要滚动加载，数据量超过百条时页面渲染变慢
react-virtualized不能很好的和antd的table结合使用，antd-table-infinity滚动时很容易出现空白，所以希望官方能实现这个功能,实现虚拟滚动和滚动加载

### What does the proposed API look like?
<Table
   loadMore={this.loadMore}
/>
loadMore方法会在表格滚动条滚动到底部时触发，表格自带虚拟滚动

**Comment by afc163** [comment] 2019-09-04 06:05
Duplicate of #3789

**Closed by afc163** 2019-09-04 06:05 UTC
