### ISSUE TITLE
DatePicker的周选择器 选中的value会在不同年份的相同日期会再次选中

### ISSUE THREAD

**Issue by luoluo5945** [ant-design/ant-design#32348] opened 2021-09-29 07:53 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gy9cq)

### Steps to reproduce
周选择器选中任意一周的数据，然后切换年份

### What is expected?
期望周选择器选中的value只会在正确的年月日时候才选中

### What is actually happening?
周选择器在选中某一星期值后，不同年份相同日期时，周选择器的选中会再次生效

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | react |
| System | mac |
| Browser | 93.0.4577.63 |

**Comment by afc163** [comment] 2021-09-30 09:52
Duplicate of #31782

**Closed by afc163** 2021-09-30 09:52 UTC
