### ISSUE TITLE
Footer with columns for Table Component

### ISSUE THREAD

**Issue by masonwongcs** [ant-design/ant-design#9979] opened 2018-04-10 06:40 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It will eventually resolve the issue for purposely injecting another table into the table component just for the footer.

### What does the proposed API look like?
By using tfoot element

**Comment by afc163** [comment] 2018-04-11 04:49
Duplicate of #5710

**Closed by afc163** 2018-04-11 04:49 UTC
Labels: Component: Table
