### ISSUE TITLE
样式兼容px2vw/vh

### ISSUE THREAD

**Issue by whiteroseisred** [ant-design/ant-design#47750] opened 2024-03-07 02:50 UTC
### What problem does this feature solve?

将项目中的px转vw/vh 做界面适配

### What does the proposed API look like?

类似现有px2rem用法

**Comment by afc163** [comment] 2024-03-07 03:11
Duplicate of #47748

**Closed by afc163** 2024-03-07 03:11 UTC
Labels: unconfirmed

**Comment by asd116725** [comment] 2025-08-06 06:28
```typescript
/**
 * respect https://github.com/evrone/postcss-px-to-viewport
 */
import type { CSSObject, Transformer } from "@ant-design/cssinjs";
import unitless from "@emotion/unitless";

interface Options {
	/**
	 * The viewport width for conversion.
	 * @default 1920
	 */
	viewportWidth?: number;
	/**
	 * The decimal numbers to allow the VW units to grow to.
	 * @default 5
	 */
	precision?: number;
	/**
	 * Whether to allow px to be converted in media queries.
	 * @default false
	 */
	mediaQuery?: boolean;
	/**
	 * Set the minimum pixel value to replace.
	 * @default 1
	 */
	minPixelValue?: number;
}

const pxRegex = /url\([^)]+\)|var\([^)]+\)|(\d*\.?\d+)px/g;

function toFixed(number: number, precision: number) {
	const multiplier = Math.pow(10, precision + 1),
		wholeNumber = Math.floor(number * multiplier);
	return (Math.round(wholeNumber / 10) * 10) / multiplier;
}

const transform = (options: Options = {}): Transformer => {
	const {
		viewportWidth = 1920,
		precision = 5,
		mediaQuery = false,
		minPixelValue = 1,
	} = options;

	const pxReplace = (m: string, $1: string) => {
		if (!$1) return m;
		const pixels = parseFloat($1);
		// 如果像素值小于最小转换值，则不转换
		if (pixels < minPixelValue) return m;
		const fixedVal = toFixed((pixels / viewportWidth) * 100, precision);
		return `${fixedVal}vw`;
	};

	const visit = (cssObj: CSSObject): CSSObject => {
		const clone: CSSObject = { ...cssObj };

		Object.entries(cssObj).forEach(([key, value]) => {
			if (typeof value === "string" && value.includes("px")) {
				const newValue = value.replace(pxRegex, pxReplace);
				clone[key] = newValue;
			}

			// no unit - 处理纯数字值
			if (!unitless[key] && typeof value === "number" && value !== 0) {
				clone[key] = `${value}px`.replace(pxRegex, pxReplace);
			}

			// Media queries
			const mergedKey = key.trim();
			if (mergedKey.startsWith("@") && mergedKey.includes("px") && mediaQuery) {
				const newKey = key.replace(pxRegex, pxReplace);

				clone[newKey] = clone[key];
				delete clone[key];
			}
		});

		return clone;
	};

	return { visit };
};

export default transform;

```

**Comment by k-w-wang** [comment] 2025-08-06 09:10
```
> /**
>  * respect https://github.com/evrone/postcss-px-to-viewport
>  */
> import type { CSSObject, Transformer } from "@ant-design/cssinjs";
> import unitless from "@emotion/unitless";
> 
> interface Options {
> 	/**
> 	 * The viewport width for conversion.
> 	 * @default 1920
> 	 */
> 	viewportWidth?: number;
> 	/**
> 	 * The decimal numbers to allow the VW units to grow to.
> 	 * @default 5
> 	 */
> 	precision?: number;
> 	/**
> 	 * Whether to allow px to be converted in media queries.
> 	 * @default false
> 	 */
> 	mediaQuery?: boolean;
> 	/**
> 	 * Set the minimum pixel value to replace.
> 	 * @default 1
> 	 */
> 	minPixelValue?: number;
> }
> 
> const pxRegex = /url\([^)]+\)|var\([^)]+\)|(\d*\.?\d+)px/g;
> 
> function toFixed(number: number, precision: number) {
> 	const multiplier = Math.pow(10, precision + 1),
> 		wholeNumber = Math.floor(number * multiplier);
> 	return (Math.round(wholeNumber / 10) * 10) / multiplier;
> }
> 
> const transform = (options: Options = {}): Transformer => {
> 	const {
> 		viewportWidth = 1920,
> 		precision = 5,
> 		mediaQuery = false,
> 		minPixelValue = 1,
> 	} = options;
> 
> 	const pxReplace = (m: string, $1: string) => {
> 		if (!$1) return m;
> 		const pixels = parseFloat($1);
> 		// 如果像素值小于最小转换值，则不转换
> 		if (pixels < minPixelValue) return m;
> 		const fixedVal = toFixed((pixels / viewportWidth) * 100, precision);
> 		return `${fixedVal}vw`;
> 	};
> 
> 	const visit = (cssObj: CSSObject): CSSObject => {
> 		const clone: CSSObject = { ...cssObj };
> 
> 		Object.entries(cssObj).forEach(([key, value]) => {
> 			if (typeof value === "string" && value.includes("px")) {
> 				const newValue = value.replace(pxRegex, pxReplace);
> 				clone[key] = newValue;
> 			}
> 
> 			// no unit - 处理纯数字值
> 			if (!unitless[key] && typeof value === "number" && value !== 0) {
> 				clone[key] = `${value}px`.replace(pxRegex, pxReplace);
> 			}
> 
> 			// Media queries
> 			const mergedKey = key.trim();
> 			if (mergedKey.startsWith("@") && mergedKey.includes("px") && mediaQuery) {
> 				const newKey = key.replace(pxRegex, pxReplace);
> 
> 				clone[newKey] = clone[key];
> 				delete clone[key];
> 			}
> 		});
> 
> 		return clone;
> 	};
> 
> 	return { visit };
> };
> 
> export default transform;

```
How to use transform
