### ISSUE TITLE
Drawer component “touchmove” event throws an error

### ISSUE THREAD

**Issue by jaceyi** [ant-design/ant-design#30896] opened 2021-06-07 08:33 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jichuchouti-antd4162-forked-g0729?file=/index.js)

### Steps to reproduce
![avatar](https://firebasestorage.googleapis.com/v0/b/chat-cc664.appspot.com/o/editor-file%2F1623054316855a1z1my4p8g8.png?alt=media&token=ebda2fd5-a51f-48f6-b600-50325889b9ae)

### What is expected?
Don't catch preventDefault

### What is actually happening?
throws error

| Environment | Info |
|---|---|
| antd | 4.16.2 |
| React | 17.0.1 |
| System | Mac |
| Browser | Chrome91 |

**Comment by afc163** [comment] 2021-06-07 08:39
Duplicate of #28787

**Closed by afc163** 2021-06-07 08:39 UTC
