### ISSUE TITLE
Range Picker: Blinks on open and close in Safari

### ISSUE THREAD

**Issue by potty** [ant-design/ant-design#19433] opened 2019-10-25 11:58 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-vnl8k?fontsize=14)

### Steps to reproduce
Open or close Range Picker

### What is expected?
Range Picker should smoothly open or close

### What is actually happening?
Range Picker blinks when opening or closing: https://recordit.co/OU5Vcdd2OI

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16.8.5 |
| System | MacOs 10.14.6 |
| Browser | Safari 13.0.2 |

**Comment by afc163** [comment] 2019-10-27 06:31
Duplicate of #11957

**Closed by afc163** 2019-10-27 06:31 UTC
