### ISSUE TITLE
微前端场景，ant-tabs-dropdown，产生的菜单样式失效了，看如下图

### ISSUE THREAD

**Issue by Topthinking** [ant-design/ant-design#32232] opened 2021-09-18 10:37 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What is actually happening?

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.14 |
| System | mac |
| Browser | chrome 最新 |

---
![image](https://user-images.githubusercontent.com/13382821/133885877-71f85ec0-fc2d-4229-9116-3f5122ee223f.png)

![image](https://user-images.githubusercontent.com/13382821/133885979-d27b0f51-e818-4c83-82a8-3127c30bd60f.png)

**Comment by afc163** [comment] 2021-09-18 13:38
Duplicate of #25844

**Closed by afc163** 2021-09-18 13:38 UTC
