### ISSUE TITLE
Select mode="tags"，输入比如’22‘后，再次点击输入框，’22‘会被清空。另一种场景是复制粘贴后再次点击输入框，粘贴的内容也会被清空

### ISSUE THREAD

**Issue by WenquanWuNCS** [ant-design/ant-design#51036] opened 2024-09-26 09:21 UTC
### Reproduction link

[https://ant-design.antgroup.com/components/select-cn](https://ant-design.antgroup.com/components/select-cn)

### Steps to reproduce

Select mode="tags"，输入比如’22‘后，再次点击输入框，’22‘会被清空。另一种场景是复制粘贴后再次点击输入框，粘贴的内容也会被清空，官方示例即可复现

### What is expected?

重现场景中的内容在再次点击输入框的时候不被清空

### What is actually happening?

输入或者复制的内容被清空了

| Environment | Info |
| --- | --- |
| antd | 5.19.4 |
| React | ^18.2.12 |
| System | window |
| Browser | google |

**Comment by Jarryxin** [comment] 2024-09-26 09:31
怎么复现

**Comment by coding-ice** [comment] 2024-09-26 09:41
Duplicate of https://github.com/ant-design/ant-design/issues/51036

**Closed by coding-ice** 2024-09-26 09:41 UTC
Labels: unconfirmed
