### ISSUE TITLE
Collapse not working properly

### ISSUE THREAD

**Issue by singh-sumit** [ant-design/ant-design#36327] opened 2022-06-30 18:47 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/panel-separated-collapse-pbeoj6)

### Steps to reproduce

- Put the Panel within separate component, say PanelElement,
- Wrap this new component within Collapse component,

### What is expected?

# Problem
- I want every Panel within a separate component to manage(i.e. refresh) each panel with its state,

### What is actually happening?

# Observation:
- ">" icon doesn't appear, and panel is not collapsible even
- While the other panels wrapped just within the Collapse Component are collapsible

| Environment | Info |
| --- | --- |
| antd | 4.21.4 |
| React | 16.14.0 |
| System | Windows 10 |
| Browser | Chrome Version 103.0.5060.66 (Official Build) (64-bit) |

![collapse-error](https://user-images.githubusercontent.com/52070590/176757887-50816b5e-f902-42de-9f18-a41f573f04db.PNG)

**Comment by afc163** [comment] 2022-07-01 01:52
Duplicate of https://github.com/ant-design/ant-design/issues/4853

**Closed by afc163** 2022-07-01 01:52 UTC

**Comment by afc163** [comment] 2022-07-01 01:55
https://codesandbox.io/s/panel-separated-collapse-forked-67495r?file=/PanelElement.js
