### ISSUE TITLE
npm run build error:Cannot find module: 'css-animation/es/Event'

### ISSUE THREAD

**Issue by cjfpersonal** [ant-design/ant-design#17937] opened 2019-07-29 01:49 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/17935](https://github.com/ant-design/ant-design/issues/17935)

### Steps to reproduce
npm install & 
npm run build

### What is expected?
编译成功

### What is actually happening?
![image](https://user-images.githubusercontent.com/17400972/62016699-30277f00-b1e6-11e9-86b7-6a1720cfcb7d.png)
./node_modules/antd/es/_util/wave.js
Cannot find module: 'css-animation/es/Event'.

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | react |
| System | linux |
| Browser | chrome |

---
8月26号到新服务器打包，编译正常；
8月28开始报错：
./node_modules/antd/es/_util/wave.js
Cannot find module: 'css-animation/es/Event'.
跑到8月26号的服务器上，重装依赖，build时也开始报错了

是第三方引用更新了？还是有做什么修改吗？

**Comment by zombieJ** [comment] 2019-07-29 06:28
Duplicate of #17930
Please reinstall node_modules this has been fixed.

**Closed by zombieJ** 2019-07-29 06:28 UTC

**Comment by meodemsao** [comment] 2019-07-30 07:20
i have same issue with antd-mobile

```sh
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/bangvu/Desktop/Projects/wtt/wttcms-frontend/node_modules/rc-animate/lib/AnimateChild.js:35:21)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19) 
```

**Comment by Luckyre** [comment] 2019-08-08 11:31
已解决👀👀 https://github.com/ant-design/ant-design/issues/17928
