### ISSUE TITLE
Body scroll on visible modal component (Safari browser)

### ISSUE THREAD

**Issue by PavelRazumov** [ant-design/ant-design#30114] opened 2021-04-12 15:24 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal/#API](https://ant.design/components/modal/#API)

### Steps to reproduce
- Open Ant design in Safari and find modal componet
- After open popup try scroll body 
- Body and content under popup scroll

### What is expected?
Body and content not scrolled under popup

### What is actually happening?
Body and content scrolled

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React |  "react": "^17.0.1", |
| System | IOS v.14.1 |
| Browser | Safari |

---
It is known issue in safari browsers "overflow: hidden" not enough, 
for disabled scroll we used next props

let scrollPosition = 0;
export const disableBodyScroll = () => {
  scrollPosition = window.pageYOffset;
  document.body.style.overflow = "hidden";
  document.body.style.position = "fixed";
  document.body.style.top = `-${scrollPosition}px`;
  document.body.style.width = "100%";
  document.body.style.height = "100%";
  document.body.style.overflow = "hidden";
  document.body.style.pointerEvents = "none";
  document.body.style.touchAction = "none";
};

export const enableBodyScroll = () => {
  document.body.style.removeProperty("position");
  document.body.style.removeProperty("top");

  document.body.style.removeProperty("pointer-events");
  document.body.style.removeProperty("touch-action");
  document.body.style.removeProperty("height");
  document.body.style.removeProperty("overflow");

  window.scrollTo(0, scrollPosition);
};

**Comment by afc163** [comment] 2021-04-13 14:12
Duplicate of #23202

**Closed by afc163** 2021-04-13 14:12 UTC
