### ISSUE TITLE
页面上有Sider组件会导致Layout其他组件渲染两次

### ISSUE THREAD

**Issue by winter-ice** [ant-design/ant-design#12372] opened 2018-09-22 20:22 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
win10,chrome 69

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q8ryr9z59)

### Steps to reproduce
见重现链接

### What is expected?
渲染一次

### What is actually happening?
渲染两次

**Comment by zombieJ** [comment] 2018-09-23 02:50
Duplicate of #8347

**Closed by zombieJ** 2018-09-23 02:50 UTC

**Comment by ycjcl868** [comment] 2018-09-23 02:58
[Layout](https://github.com/ant-design/ant-design/blob/master/components/layout/layout.tsx#L45-L49)
