### ISSUE TITLE
Popconfirm套在Menu.Item下，无法点击

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design#22285] opened 2020-03-17 03:13 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/intelligent-varahamihira-q6b5z)

### Steps to reproduce
1.点击1st menu item测试
2. Popconfirm无法选中点击

### What is expected?
Popconfirm气泡可选中点击

### What is actually happening?
 Popconfirm无法选中点击

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.12 |
| System | window |
| Browser | chrome |

**Comment by afc163** [comment] 2020-03-17 03:18
Duplicate of #22007

**Closed by afc163** 2020-03-17 03:18 UTC

**Comment by ISBN9527** [comment] 2020-03-17 03:24
好的，谢谢大哥
