### ISSUE TITLE
[4.0] datepicker切换起止后无法取消focus状态

### ISSUE THREAD

**Issue by zkwolf** [ant-design/ant-design#20438] opened 2019-12-25 08:11 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
![GIF](https://user-images.githubusercontent.com/8555127/71438513-05a80680-2731-11ea-82f4-ae091fec2e0e.gif)

### What is expected?
在切换起止后点击其他区域可以取消focus状态

### What is actually happening?
在切换起止后点击其他区域没有取消focus状态

| Environment | Info |
|---|---|
| antd | 4.0.0-beta.0 |
| React | x |
| System | win10 |
| Browser | chrome 79 |

**Comment by afc163** [comment] 2019-12-25 08:21
Duplicate of #20385

**Closed by afc163** 2019-12-25 08:21 UTC
