### ISSUE TITLE
Close open drawer component using keyboard escape key

### ISSUE THREAD

**Issue by sagar7993** [ant-design/ant-design#16629] opened 2019-05-16 10:52 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Drawer component cannot be closed by pressing escape on the keyboard, which breaks accessibility. It would be great if Drawer could be closed with the escape key, exactly like the implementation in Modal component.

### What does the proposed API look like?
We can pass the keyboard config into the drawer props such as 

export interface DrawerProps {
    ...drawerProps
    keyboard?: boolean;
}

**Comment by afc163** [comment] 2019-05-17 02:46
Duplicate of #11628

**Closed by afc163** 2019-05-17 02:46 UTC
