### ISSUE TITLE
Transfer组件提供自定义的搜索组件，或者提供方法在外部可以传入搜索的value

### ISSUE THREAD

**Issue by andyyxw** [ant-design/ant-design#17717] opened 2019-07-18 08:43 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可根据业务场景使用自定义的搜索组件，比如 Input.Search

### What does the proposed API look like?
类似antd-form的自定义表单组件，提供 value 和 onChange

**Comment by afc163** [comment] 2019-07-18 14:03
Duplicate of #17240

**Closed by afc163** 2019-07-18 14:03 UTC
