### ISSUE TITLE
Cascader数据量过大显示隐藏Cascader时很卡

### ISSUE THREAD

**Issue by Wtianliang** [ant-design/ant-design#33390] opened 2021-12-23 02:49 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-17-4-forked-t5c0b?file=/index.js:403-421)

### Steps to reproduce
按照我给的demo连接 点击按钮操作

### What is expected?
点击按钮显示隐藏Cascader不卡顿

### What is actually happening?
点击按钮显示隐藏Cascader很卡

| Environment | Info |
|---|---|
| antd | 4.17.4 |
| React | 16.14.0 |
| System | macHd |
| Browser | chrome90 |

**Comment by Wtianliang** [comment] 2021-12-23 02:58
之前别的项目用3.x并不卡

**Comment by Wtianliang** [comment] 2021-12-23 03:08
测试了下，好像时 rc-cascader 的问题

**Comment by afc163** [comment] 2021-12-23 05:33
Duplicate of #33016

**Closed by afc163** 2021-12-23 05:33 UTC

**Comment by afc163** [comment] 2022-03-03 10:10
测试了一下 antd@4.18.9 速度已经很快了：https://codesandbox.io/s/runtime-violet-d8iw4w?file=/index.js

**Comment by LOU-4599** [comment] 2023-01-05 01:42
> 测试了一下 antd@4.18.9 速度已经很快了：https://codesandbox.io/s/runtime-violet-d8iw4w?file=/index.js

这才几条数据啊，2000多条数据得卡5秒左右，打开和隐藏都时这样
