### ISSUE TITLE
Table的scroll样式错误

### ISSUE THREAD

**Issue by YoungHearts** [ant-design/ant-design#16154] opened 2019-04-18 03:42 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/rbdNPy?&editable=true&editors=001](https://codepen.io/anon/pen/rbdNPy?&editable=true&editors=001)

### Steps to reproduce
当内容过多，需要为table设置scroll后，样式错误

### What is expected?
样式正确

### What is actually happening?
样式错误

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.8.4 |
| System | mac10.13.5 |
| Browser | chrome73.0.3683.103 |

**Comment by YoungHearts** [comment] 2019-04-18 03:44
![图片](https://user-images.githubusercontent.com/19346339/56335499-57c28080-61cf-11e9-8f25-24d0ebe5ed55.png)

**Comment by afc163** [comment] 2019-04-19 08:37
Duplicate of #14211

**Closed by afc163** 2019-04-19 08:37 UTC
