### ISSUE TITLE
Treeshaking of Icons

### ISSUE THREAD

**Issue by Opty1712** [ant-design/ant-design#12674] opened 2018-10-16 09:27 UTC
- [ +] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Size of final bundle increased on 500kb after changing icons from font to svg

### What does the proposed API look like?
It is good idea to move icons to antd-icons and import only needed icons from that library or any of your idea.

**Comment by afc163** [comment] 2018-10-16 10:28
Duplicate of #12011

**Closed by afc163** 2018-10-16 10:28 UTC
