### ISSUE TITLE
expose onInputKeyDown from Select inside TreeSelect

### ISSUE THREAD

**Issue by raptoria** [ant-design/ant-design#13338] opened 2018-11-28 20:46 UTC
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

 

### What problem does this feature solve?

I want to be able to handle the Enter key pressed event inside the TreeSelect Input

 

### What does the proposed API look like?

<TreeSelect

 onInputKeyDown={this.onKeyDown}

  />

 

function onKeyDown(event){
  if (event.key === 'Enter'){
    console.log('got enter key');
  }
}

**Comment by afc163** [comment] 2018-11-29 08:03
Try `onSearch`

**Comment by afc163** [comment] 2018-11-29 08:04
Duplicate of #12955

**Closed by afc163** 2018-11-29 08:04 UTC
