### ISSUE TITLE
antd doc——Press ctrl k shortcut keey and wake up the search pop-up modal, press up key, console report an error

### ISSUE THREAD

**Issue by DZ-study** [ant-design/ant-design#31144] opened 2021-06-26 02:32 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/overview-cn/](https://ant.design/components/overview-cn/)

### Steps to reproduce
1. press ctrl   k shortcut key
2. press pgUp key

### What is expected?
Normal page browsing

### What is actually happening?
Page blank

| Environment | Info |
|---|---|
| antd | 4.16.5 |
| React | ^17.0.1 |
| System | win10 |
| Browser | chrome（版本 91.0.4472.114（正式版本） （64 位）） |

**Comment by afc163** [comment] 2021-06-27 05:32
Duplicate of #31040

**Closed by afc163** 2021-06-27 05:32 UTC
