### ISSUE TITLE
phone number auto format

### ISSUE THREAD

**Issue by swimhiking** [ant-design/ant-design#33759] opened 2022-01-18 21:57 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input/](https://ant.design/components/input/)

### Steps to reproduce
1), create a normal input box with ant design Form.Item;
2), User enter a valid phone number such as 0211386654356 or 4040440044; I wish it can automatically format as 021-1386654356 and 404-044-0044
3), the value user input is number, however, I prefer treated as string and formatted as above 2 examples

### What is expected?
format normal input box phone number properly, such as 0211386654356 to 021-1386654356  and 4040440044 to 404-044-0044

### What is actually happening?
doesn't have any format when user input a phone number, input box display the value as is after user move away the focused mouse.

| Environment | Info |
|---|---|
| antd | 4.18.4 |
| React | 17.0.2 |
| System | windows 10 |
| Browser | Chrome |

**Comment by afc163** [comment] 2022-01-19 02:58
Duplicate of #23201

**Closed by afc163** 2022-01-19 02:58 UTC
