### ISSUE TITLE
【在 TypeScript 中使用】页面按教程来，修改package.json文件react-app-rewired start --scripts-version react-scripts-ts   启动不了

### ISSUE THREAD

**Issue by q921232954** [ant-design/ant-design#14151] opened 2019-01-07 08:53 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
"scripts": {
-   "start": "react-scripts-ts start",
    "start": "react-app-rewired start --scripts-version react-scripts-ts",
-   "build": "react-scripts-ts build",
    "build": "react-app-rewired build --scripts-version react-scripts-ts",
-   "test": "react-scripts-ts test --env=jsdom",
    "test": "react-app-rewired test --env=jsdom --scripts-version react-scripts-ts",
}
修改后yarn  start报错Cannot find module '/Users/XXX/react_demo/antd-demo-ts/node_modules/react-scripts-ts/config/webpack.config'

### What is expected?
解决，并修改教程

### What is actually happening?
报错

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | xx |
| System | mac  10.12.6 |
| Browser | xx |

**Comment by afc163** [comment] 2019-01-07 09:00
Duplicate of https://github.com/ant-design/ant-design/issues/14085#issuecomment-451459385

**Closed by afc163** 2019-01-07 09:00 UTC

**Comment by woow-wu** [comment] 2019-01-12 10:34
why
