### ISSUE TITLE
 Tabs and CustomTabPane

### ISSUE THREAD

**Issue by Poyoman39** [ant-design/ant-design#30567] opened 2021-05-18 09:14 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-z70rr)

### Steps to reproduce
<Tabs>
  <MyHoc />
</Tabs>

// ===

const MyHoc = () => (<TabPane tab="hello" key="hello" />)

### What is expected?
We should be able to have local useState inside TabPane, in order to set the "tab" property for instance

### What is actually happening?
We can't

| Environment | Info |
|---|---|
| antd | 4.15.6 |
| React | react 16.13.1 |
| System | all |
| Browser | all |

---
I'm would like to re-open the bug https://github.com/ant-design/ant-design/issues/5165 which is still a valid request. The current tabPane implementation make it impossible to encapsulate logique of tabs inside them. (Like local useState)

**Comment by afc163** [comment] 2021-05-18 13:24
Duplicate of https://github.com/ant-design/ant-design/issues/4853

**Closed by afc163** 2021-05-18 13:24 UTC
