### ISSUE TITLE
Emotion styles not visible on tests (react-testing-lib, jest)

### ISSUE THREAD

**Issue by val1991** [ant-design/ant-design#46686] opened 2023-12-28 13:28 UTC
### Reproduction link

[https://github.com/val1991/antd-emotion](https://github.com/val1991/antd-emotion)

### Steps to reproduce

I added emotion for styles and when run project locally styles are applied, also I created simple Text element and test works but on antd elements I can't test styles

### What is expected?

possibility to test styles with emotion

### What is actually happening?

it doesn't see any styles

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | ^18.2.0 |
| System | mac |
| Browser | Crome |

---
Please check Text component and Button component on github example
Text works but Button not

**Comment by afc163** [comment] 2023-12-28 13:38
Could https://emotion.sh/docs/@emotion/jest resolve your problem?

**Comment by MadCcc** [comment] 2023-12-29 02:33
Not related to Ant Design, closing.

**Comment by val1991** [comment] 2023-12-29 07:00
@MadCcc why it is not relative to antd? I created two components Text(simple div) and Button(antd button) and on Text I can check styles but on antd no 

@afc163 I user @emotion/jest in my exmaple

**Comment by chri911** [comment] 2023-12-29 08:47
I can totally relate to this issue! I encountered a similar problem while working on my tests. Adding emotions for styles worked seamlessly when running the project locally. However, I hit a roadblock when trying to test styles for antd elements. It seems like the styles aren't recognized during testing.

**Comment by annisokay97** [comment] 2023-12-29 09:17
I have the same issue with testing styles with emotion.

**Comment by Olia25** [comment] 2023-12-29 13:59
Ш have the same issue. While I was working with ant version 4.24.8 I had no problem writing tests, but since version 5.7.0 I can't test styles with emotions in ant elements. 
And I still haven't found how to fix it

**Comment by Stacyy** [comment] 2023-12-29 14:30
I'm experiencing a similar problem. 
Previously, when using ant version 4.*, I could write tests without any issues.
However, after updating to version 5.* (5.11.0), I've been unable to test styles involving emotions within ant elements.

**Comment by franciscowinocur** [comment] 2023-12-29 14:42
Same issue here, it worked on v4 but now with v5 it's broken

**Comment by qmorozov** [comment] 2023-12-29 14:48
I'm encountering the same issue when attempting to test styles using Emotion...

**Comment by mardarolya** [comment] 2023-12-29 14:48
Hi! I faced with described the issue. Steps to reproduce: create react app via yarn create react-app. My dependencies: 
 ```
 "dependencies": {
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^13.0.0",
    "@testing-library/user-event": "^13.2.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.0",
    "@emotion/jest": "^11.11.0",
    "@emotion/react": "^11.11.3",
    "@types/jest": "^27.0.1",
    "@types/node": "^16.7.13",
    "@types/react": "^18.2.45",
    "@types/react-dom": "^18.2.18",
    "antd": "^5.12.5"
  }
```

App.js:

```
import './App.css';
import {Button} from 'antd';

export function App() {
  return (
    <div className="App">
      <header className="App-header">
        <Button css={{
      '&.ant-btn': {
        background: 'red'
      }
    }}>test</Button>
      </header>
    </div>
  );
}
```

App.spec.js:

```
import { render, screen } from '@testing-library/react';
import { App } from './App';
import { createSerializer } from '@emotion/jest';

expect.addSnapshotSerializer(createSerializer())

test('Button styles', () => {
  const { asFragment } = render(<App />);
  expect(asFragment()).toMatchSnapshot()
  
  const button = screen.getByText(/test/i);
  expect(button).toBeInTheDocument();

   expect(button).toHaveStyle({
      background: 'red'
    })
});
```
The jest report:

```
    expect(element).toHaveStyle()

    - Expected

    - background: red;

      13 |   expect(button).toBeInTheDocument();
      14 |
    > 15 |    expect(button).toHaveStyle({
         |                   ^
      16 |       background: 'red'
      17 |     })
      18 | });
```

**Comment by danielbc09** [comment] 2023-12-29 14:49
I'm encountering the same issue when attempting to test styles using Emotion...

**Comment by crisderzweiter** [comment] 2023-12-29 14:51
I'm having the same issue it worked on v4 but now with v5

**Comment by tolochenkovad** [comment] 2023-12-29 14:53
After updating antd(to 5.12.5) I have the same issue.
Previously I had version 4.24.8 and all worked as expected.

**Comment by clos747** [comment] 2023-12-29 14:54
Same issue, not working on v5

**Comment by antrem21** [comment] 2023-12-29 14:59
Issue is also reproducing for me too, 
I am using the same stack, 
For 4 version all works, but when update to 5 version get this issue.

**Comment by andrzejTrinetix** [comment] 2023-12-29 15:00
I'm having the same issue it worked on v4 but now with v5

**Comment by sebaseser** [comment] 2023-12-29 15:26
Same issue here!

**Comment by zombieJ** [comment] 2023-12-29 15:53
1. Jest do not support `:where` selector correctly, which means it will get wrong priority with real world. You can prevent injection with `@ant-design/cssinjs` StyleProvider.
2. (In your test case) `screen.getByText(/test/i);` get the span element, not the button element. antd Button is wrap children with a span element. Use `querySelector` instead.

```diff
    import { render, screen } from '@testing-library/react';
    import { Button } from './Button';
    import { createSerializer } from '@emotion/jest';
++  import { StyleProvider } from '@ant-design/cssinjs';

    expect.addSnapshotSerializer(createSerializer())

    test('Button styles', () => {
      const styleHolder = document.createElement('div'); // Remove antd style in the element not in the doc
      const { asFragment, container } = render(<StyleProvider container={styleHolder}>
        <Button>test</Button>
        </StyleProvider>);
      expect(asFragment()).toMatchSnapshot()
  
--    const button = screen.getByText(/test/i); // Wrong selection
++    const button = container.querySelector('.ant-btn');

      expect(button).toBeInTheDocument();

      expect(button).toHaveStyle({
        background: 'red'
      })
  });
```

That's it:
<img width="602" alt="snapshot" src="https://github.com/ant-design/ant-design/assets/5378891/86fc7d1d-6647-4b53-a693-d692cbf3479a">

**Closed by zombieJ** 2023-12-29 15:53 UTC
Labels: unconfirmed

**Comment by val1991** [comment] 2024-01-04 12:30
@zombieJ Thanks a lot, it works, but I have issue with `:active` and `:hover` pseudo-classes.
If I added same style it overwrite it 
```
<AntButton
      css={{
        '&.ant-btn': {
          background: 'red',

          '&:active': {
            background: 'green'
          },

          '&:hover': {
            background: 'aqua'. // this background will be in tests
          },

          '&:disabled': {
            background: 'grey'
          },
        }
      }}
      {...rest}
    >
      {children}
    </AntButton>
```
<img width="1051" alt="Screenshot 2024-01-04 at 14 26 37" src="https://github.com/ant-design/ant-design/assets/32544149/ac60a1e9-ab75-469e-8698-1f237df14555">


But on Col (antd) element it will work fine

I pushed new changes here [https://github.com/val1991/antd-emotion](url)
