### ISSUE TITLE
Modal没有打开的回调

### ISSUE THREAD

**Issue by mengWenTao-Kobe** [ant-design/ant-design#32343] opened 2021-09-29 02:01 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
这样我能在每次打开Modal的时候触发回调来获取表单数据进行回填

### What does the proposed API look like?
就onOpen就行了啊！element的dialog对话框都有打开的回调，为什么antd这么全面的UI却没有？

**Comment by afc163** [comment] 2021-09-29 02:04
Duplicate of https://github.com/ant-design/ant-design/issues/8491#issuecomment-349882926

**Closed by afc163** 2021-09-29 02:04 UTC
