### ISSUE TITLE
TreeSelect 在层级过多时部分节点被遮挡无法完全显示

### ISSUE THREAD

**Issue by Dolov** [ant-design/ant-design#34477] opened 2022-03-14 07:05 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/dolov/pen/GRygobz?editors=001](https://codepen.io/dolov/pen/GRygobz?editors=001)

### Steps to reproduce
https://codepen.io/dolov/pen/GRygobz?editors=001

### What is expected?
能够滚动显示全部节点

### What is actually happening?
层级深的节点无法展示

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17 |
| System | MAC |
| Browser | CHROME |

---
是否可以增加一个功能拖拽右下角能够放大下拉框宽高，或者可以滚动内容区域

**Comment by afc163** [comment] 2022-03-14 08:59
Duplicate of https://github.com/ant-design/ant-design/issues/33495#issuecomment-1064954154

**Closed by afc163** 2022-03-14 08:59 UTC
