### ISSUE TITLE
Drawer: Received `true` for a non-boolean attribute `visible`

### ISSUE THREAD

**Issue by Fiorello** [ant-design/ant-design#17446] opened 2019-07-03 15:09 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-np6qf)

### Steps to reproduce
Just open the drawer

### What is expected?
No React error

### What is actually happening?
Three react error:
- Warning: Received `true` for a non-boolean attribute `visible`...
- React does not recognize the `renderEmpty` prop on a DOM element...
-  React does not recognize the `getPrefixCls` prop on a DOM element...

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8.6 |
| System | MacOs |
| Browser | Chrome 75.0.3770.100 |

**Comment by afc163** [comment] 2019-07-03 15:17
Duplicate of #17387

**Closed by afc163** 2019-07-03 15:17 UTC
