### ISSUE TITLE
Divider分割线组件，之前的线颜色是浅灰色，现在变成了深黑色

### ISSUE THREAD

**Issue by dmdoit** [ant-design/ant-design#27146] opened 2020-10-14 07:31 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/divider-cn/](https://ant-design.gitee.io/components/divider-cn/)

### Steps to reproduce
Divider分割线之前的线颜色是浅灰色，现在变成了深黑色。导致业务界面变得很丑

### What is expected?
期望还是和之前一样。分割线的文字是深色，线是浅色

### What is actually happening?
分割线变成了深黑色
![image](https://user-images.githubusercontent.com/19385704/95957889-e64ea700-0e32-11eb-9a35-7437d4bc99b0.png)

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | react@16.13.1 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment] 2020-10-14 07:36
Duplicate of #27132

**Closed by afc163** 2020-10-14 07:36 UTC
