### ISSUE TITLE
Tree's checkbox cant be selected when click text

### ISSUE THREAD

**Issue by Zero0331** [ant-design/ant-design#9406] opened 2018-02-24 06:08 UTC
### What problem does this feature solve?
Click the text selected node。 we can click checkbox to select node by onCheck(), 

### What does the proposed API look like?
selectedKeys the same as checkedKeys

**Comment by yesmeck** [comment] 2018-02-24 06:17
Duplicate of #8581

**Closed by yesmeck** 2018-02-24 06:17 UTC
Labels: Component: Checkbox

**Comment by AidinD** [comment] 2020-05-18 07:45
This is not a duplicate. [https://github.com/ant-design/ant-design/issues/8581](#8581) refers to the TreeSelect component while this issue I think is about the Tree component where clicking on the text does not check the checkbox!
