### ISSUE TITLE
Using <Modal> results in "findDOMNode is deprecated in StrictMode" warning

### ISSUE THREAD

**Issue by hyjoong** [ant-design/ant-design#31709] opened 2021-08-07 11:33 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/hyjoong/Schedule-management/commit/c5a17fa18286100020abc74a6673f8816b4f906d](https://github.com/hyjoong/Schedule-management/commit/c5a17fa18286100020abc74a6673f8816b4f906d)
 

### What is expected?
No warnings should be displayed.

### What is actually happening?
A warning message will appear in console.log stating "Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Wave which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here:"

 
| Environment | Info |
|---|---|
| antd | 4.16.10 |
| React | 17.0.2|
| System | window |
| Browser | chrome 92.0 |

---
The source of the problem is coming from <Modal/> component. 

See the file in question:
https://github.com/hyjoong/Schedule-management/commit/c5a17fa18286100020abc74a6673f8816b4f906d

**Comment by afc163** [comment] 2021-08-08 05:16
Duplicate of #26136

**Closed by afc163** 2021-08-08 05:16 UTC
