### ISSUE TITLE
InternalMenu firing setState after component unmounts

### ISSUE THREAD

**Issue by dfee** [ant-design/ant-design#16321] opened 2019-04-25 20:44 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/623mow7j0k)

### Steps to reproduce
Re-render a `Menu`.

### What is expected?
There is not a state update on unmounted component error.

### What is actually happening?
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in InternalMenu (created by Context.Consumer)
    in Menu (created by AppMenu)
    in AppMenu (created by App)
```

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | 16.8.6 |
| System | Mac OS 13 |
| Browser | FF |

**Comment by afc163** [comment] 2019-04-26 02:52
Duplicate of #16290

**Closed by afc163** 2019-04-26 02:52 UTC
