### ISSUE TITLE
How about prop labelInValue in Component Cascader , just like labelInValue in Select

### ISSUE THREAD

**Issue by agoni1212** [ant-design/ant-design#15757] opened 2019-03-30 13:58 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
labelInValue in Component Cascader

### What does the proposed API look like?
labelInValue in Select

**Comment by afc163** [comment] 2019-03-30 14:03
Duplicate of #15681

**Closed by afc163** 2019-03-30 14:03 UTC
