### ISSUE TITLE
主动setValue("")无效

### ISSUE THREAD

**Issue by muzifangtong** [ant-design/ant-design#48396] opened 2024-04-11 05:33 UTC
### Reproduction link

[https://ant-design.gitee.io/components/input-cn#components-input-demo-otp](https://ant-design.gitee.io/components/input-cn#components-input-demo-otp)

### Steps to reproduce

// 点击 Rest. setValue(“”); 后 期望框内显示内容变成空

import React from 'react';
import { Input, Space, Typography, type GetProp, Button } from 'antd';

const { Title } = Typography;

const App: React.FC = () => {
  const [value, setValue] = React.useState('9');
  const onChange: GetProp<typeof Input.OTP, 'onChange'> = (text) => {
    console.log('onChange:', text);
setValue(text)
  };

  const sharedProps = {
    onChange,value
  };

  return (
    <Space direction="vertical">
<Button onClick={() => {
setValue('');
console.log("******")
}}>Rest</Button>
      <Title  level={5}>With formatter (Upcase)</Title>
      <Input.OTP formatter={(str) => str.toUpperCase()} {...sharedProps} />
      <Title level={5}>With Disabled</Title>
      <Input.OTP disabled {...sharedProps} />
      <Title level={5}>With Length (8)</Title>
      <Input.OTP length={8} {...sharedProps} />
      <Title level={5}>With variant</Title>
      <Input.OTP variant="filled" {...sharedProps} />
    </Space>
  );
};

export default App;

### What is expected?

otp框内值有变为空

### What is actually happening?

otp框内显示内容并无变动

| Environment | Info |
| --- | --- |
| antd | 5.16.0 |
| React | 18  |
| System | window |
| Browser | chrome  |

**Comment by afc163** [comment] 2024-04-11 05:36
Duplicate of #48395

**Closed by afc163** 2024-04-11 05:36 UTC
Labels: unconfirmed
