### ISSUE TITLE
UI freeze when try to disable select animation 

### ISSUE THREAD

**Issue by Grandiada** [ant-design/ant-design#21114] opened 2020-01-27 11:46 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-f86su)

### Steps to reproduce
In antd select component
https://ant.design/components/select/
1. set transitionName to 'none'
2. set choiceTransitionName to 'none'

### What is expected?
Dont freeze unselect action

### What is actually happening?
After unselect there is at least 1sec delay before unselected item disapear

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | react |
| System | Windows 10 |
| Browser | Chrome |

---
Please help me to disable this UI freeze)
Best regards 
Thanks for attention

**Comment by zombieJ** [comment] 2020-01-28 13:21
Duplicate of #951

**Closed by zombieJ** 2020-01-28 13:21 UTC

**Comment by zombieJ** [comment] 2020-01-28 13:27
PS: `transitionName` & `choiceTransitionName` is internal usage and animation is little coupling with process logic, pls use css solution instead.
