### ISSUE TITLE
React18.2.0导致menu收缩的时候会有hover浮窗

### ISSUE THREAD

**Issue by Erdrian** [ant-design/ant-design#37083] opened 2022-08-16 11:28 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-b1h7to?file=/index.js)

### Steps to reproduce

点开二级菜单，选中具体的item，
点击侧边栏的收缩按钮
再点击展开按钮

### What is expected?

侧边栏收缩
不会出现hover的浮窗

### What is actually happening?

收缩时闪现出item  hover时的浮窗

| Environment | Info |
| --- | --- |
| antd | 4.22.5 |
| React | 18.2.0 |
| System | win11 |
| Browser | Chrome 104.0.5112.81 |

---
相同代码，在react 17.0.2版本下不会出现item的hover浮窗

**Comment by afc163** [comment] 2022-08-17 05:22
Duplicate of #36152

**Closed by afc163** 2022-08-17 05:22 UTC
