### ISSUE TITLE
Menu don't work in nextjs 12.3.1

### ISSUE THREAD

**Issue by ccdarvin** [ant-design/ant-design#38106] opened 2022-10-19 07:12 UTC
### Reproduction link

[https://github.com/ccdarvin/authcloud.git](https://github.com/ccdarvin/authcloud.git)

### Steps to reproduce

We have a menu in side left of page, when click in link display this:
```
Application error: a client-side exception has occurred (see the browser console for more information).
```
I had probed remove the Menu component, and problem is fixed

### What is expected?

when you click on the link you should go to the other page

### What is actually happening?

Display dis error 
```
Application error: a client-side exception has occurred (see the browser console for more information).
```
in console show:
```
framework-7751730b10fa0f74.js:9 TypeError: number 0 is not iterable (cannot read property Symbol(Symbol.iterator))
    at new Map (<anonymous>)
    at 252-e9d1cab486ec2437.js:1:15175
    at 252-e9d1cab486ec2437.js:1:13936
    at eA (252-e9d1cab486ec2437.js:1:15154)
    at w (252-e9d1cab486ec2437.js:1:12192)
    at 252-e9d1cab486ec2437.js:1:12240
    at uJ (framework-7751730b10fa0f74.js:9:91731)
    at u1 (framework-7751730b10fa0f74.js:9:91927)
    at o5 (framework-7751730b10fa0f74.js:9:112680)
    at oQ (framework-7751730b10fa0f74.js:9:104018)

Error rendering page:  Error: Cancel rendering route
    at s (main-3bfbace5a300f221.js:1:20025)
    at main-3bfbace5a300f221.js:1:19965
    at new Promise (<anonymous>)
    at ei (main-3bfbace5a300f221.js:1:19936)
    at main-3bfbace5a300f221.js:1:17692
```

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | chrome 106.0.5249.119  |

---
This problem only occurs then run: 
```
yarn build
yarn start
```

**Comment by ccdarvin** [comment] 2022-10-19 15:30
already I have the solution.
```
# next.config.js
 //swcMinify: true,
```
it comment swrMinify or set in false

**Comment by icflorescu** [comment] 2022-10-19 16:16
@ccdarvin Your workaround just saved my arse, thank you!

**Disabling SWC minification significantly increases the build time in Next.js**, so everyone should consider it just as a **temporary** workaround till the underlying bug gets fixed.

I have a feeling that this has something to do with the Menu/Menu.Item refactoring since 4.20.x: https://ant.design/components/menu/#Usage-upgrade-after-4.20.0

**Comment by mitrosunay** [comment] 2022-10-19 18:48
after spending lots of hours, rewriting entire web site from the beginning...  i wouldnt belive the one comment could had solved my problemm... however the hardest part was to find out MENU item that resulting the bug.

**Comment by tohsaka888** [comment] 2022-10-20 06:32
> already I have the solution.
> 
> ```
> # next.config.js
>  //swcMinify: true,
> ```
> 
> it comment swrMinify or set in false

It is fixed on the latest nextjs canary release.

[see more infomation](https://github.com/vercel/next.js/issues/40889)

**Comment by mitrosunay** [comment] 2022-10-20 18:52
> already I have the solution.
> 
> ```
> # next.config.js
>  //swcMinify: true,
> ```
> 
> it comment swrMinify or set in false

THANKS!!!! :)

**Closed** 2022-10-27 13:34 UTC

**Comment by kdy1** [comment] 2022-11-14 02:11
Can someone provide a reproduction? I tried reproducing this but failed

**Comment by kdy1** [comment] 2022-11-14 02:12
Oh there was one, sorry

**Comment by thinnakrit** [comment] 2023-01-20 04:42
If i want to use  "swcMinify: true", How to fix it ?

**Comment by tohsaka888** [comment] 2023-01-20 05:02
> If i want to use  "swcMinify: true", How to fix it ?
> 

try to upgrade your next.js to 12.3.2 or later.
