### ISSUE TITLE
Allow date pickers to be rendered in a modal

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#44158] opened 2023-08-10 10:08 UTC
### What problem does this feature solve?

Ability to display datepickers in a modal allows us to handle mobile usage case

### What does the proposed API look like?

extend the current panelRender props or have something like the Calendar component but allows not just a singular datepicker but all types of datepicker

**Comment by MadCcc** [comment] 2023-08-10 11:32
Duplicate of https://github.com/ant-design/ant-design/issues/43929

**Comment by MadCcc** [comment] 2023-08-10 11:35
We are trying to design a more flexible DatePicker, which may meet your demand.

**Comment by afc163** [comment] 2023-08-11 16:20
Duplicate of https://github.com/ant-design/ant-design/issues/26758

**Closed by afc163** 2023-08-11 16:20 UTC
Labels: 💡 Feature Request
