### ISSUE TITLE
`autoFocus` prop of `AutoComplete` rendered inside a `Modal` doesn't work

### ISSUE THREAD

**Issue by sleepyArpan** [ant-design/ant-design#41866] opened 2023-04-18 09:05 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-5-4-2-forked-m4k3qx?file=/demo.tsx)

### Steps to reproduce

Render the `AutoComplete` component inside a `Modal` with `autoFocus` as true

### What is expected?

AutoComplete to have focus when the modal is opened.

### What is actually happening?

AutoComplete does not have focus when the modal is opened.

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 18 |
| System | Apple M1 Macos Ventura 13.3 |
| Browser | Firefox - 111.0.1 (64-bit) |

**Comment by afc163** [comment] 2023-04-18 10:36
Duplicate of https://github.com/ant-design/ant-design/issues/41239

**Closed by afc163** 2023-04-18 10:36 UTC
Labels: unconfirmed
