### ISSUE TITLE
`getFieldsValue` method in a `render props` cannot get the initialValues when the form component first render

### ISSUE THREAD

**Issue by USTCLX** [ant-design/ant-design#34290] opened 2022-03-03 13:36 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-4-18-9-forked-rw1q2t?file=/index.js)

### Steps to reproduce
As shown in the code below. The `values` will be a empty object when first render
```
import React from "react";
import ReactDOM from "react-dom";
import "antd/dist/antd.css";
import "./index.css";
import { Form, Input } from "antd";

const Demo = () => {
  return (
    <Form
      initialValues={{
        username: "Admin"
      }}
    >
      <Form.Item label="Username" name="username">
        <Input />
      </Form.Item>

      <Form.Item label="Password" dependencies={["username"]}>
        {({ getFieldsValue }) => {
          const values = getFieldsValue();
          console.log("values", values);
          return (
            <Form.Item name="password">
              <Input.Password placeholder={`${values.username}'s password`} />
            </Form.Item>
          );
        }}
      </Form.Item>
    </Form>
  );
};

ReactDOM.render(<Demo />, document.getElementById("container"));

```

### What is expected?
The `values` get from the `getFieldsValue` in a render props should equal to `initialValues` when first render

### What is actually happening?
The `values` is a empty object when first render

| Environment | Info |
|---|---|
| antd | 4.18.9 |
| React | 16.14.0 |
| System | macOS Big Sur version 11.6.1 |
| Browser | Chrome Version 98.0.4758.109 (Official Build) (x86_64) |

**Comment by afc163** [comment] 2022-03-07 03:35
Duplicate of #25280

**Closed by afc163** 2022-03-07 03:35 UTC
