### ISSUE TITLE
checkbox、radio 组件在 Firefox 浏览器样式不正确

### ISSUE THREAD

**Issue by jsm1003** [ant-design/ant-design#11882] opened 2018-08-25 10:08 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.2

### Environment
win10：17738、Firefox：61.0.2 (64 位)、react：16.4

### Reproduction link
[https://ant.design/components/checkbox-cn/](https://ant.design/components/checkbox-cn/)

### Steps to reproduce
用 firefox 打开 ant.design 官网，查看 checkbox 和 radio 组件即可

### What is expected?
checkbox 和 radio 组件的样式和 chrome 表现一致

### What is actually happening?
在 Firefox 浏览器中，checkbox 中间的对勾没有居中、radio 中的圆点没有居中

**Comment by afc163** [comment] 2018-08-25 10:44
Duplicate of #11640

**Closed by afc163** 2018-08-25 10:44 UTC
