### ISSUE TITLE
treeSelect 选中的选项出现描边

### ISSUE THREAD

**Issue by kkkisme** [ant-design/ant-design#45776] opened 2023-11-10 03:41 UTC
### Reproduction link

[https://ant.design/components/tree-select-cn#%E4%BB%A3%E7%A0%81%E6%BC%94%E7%A4%BA](https://ant.design/components/tree-select-cn#%E4%BB%A3%E7%A0%81%E6%BC%94%E7%A4%BA)

### Steps to reproduce

1、选中某个选项后，下拉框关闭。再次唤起下拉框

### What is expected?

选中的选项无描边

### What is actually happening?

有描边，并且描边还显示不全

| Environment | Info |
| --- | --- |
| antd | 5.11.1 |
| React | 18.2.0 |
| System | window 11 |
| Browser | chrome 119 |

![image](https://github.com/ant-design/ant-design/assets/18638401/ba3286ff-f578-4fd8-9dc6-54e6f5f926ec)
![image](https://github.com/ant-design/ant-design/assets/18638401/bfae58a0-f79c-4262-a27c-a773c41fcaa5)

**Comment by afc163** [comment] 2023-11-15 10:59
Duplicate of https://github.com/ant-design/ant-design/issues/44492

**Closed by afc163** 2023-11-15 10:59 UTC
Labels: unconfirmed
