### ISSUE TITLE
Table column custom render JSX component no longer allowing hooks

### ISSUE THREAD

**Issue by jtheberge** [ant-design/ant-design#35292] opened 2022-04-28 04:12 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-bug-report-cant-use-hooks-in-table-column-custom-cell-lk3emx?file=/index.js)

### Steps to reproduce

In Table's "column" prop, using the "render" key and passing in a custom column cell with its own hooks.

### What is expected?

The cell should be able to use hooks inside it without crashing.

### What is actually happening?

The app crashes with error:
"Rendered fewer hooks than expected. This may be caused by an accidental early return statement."

| Environment | Info |
| --- | --- |
| antd | 4.20.1 |
| React | 17.0.2 |
| System | Mac Version 12.3.1 (21E258) |
| Browser | Chrome Version 100.0.4896.127 (Official Build) (x86_64) |

---
antd@14.8.8 introduced bug.

Refs:
https://github.com/ant-design/ant-design/pull/34075
https://github.com/react-component/table/pull/752

Reverting to antd@14.8.7 fixes issue.

**Comment by zombieJ** [comment] 2022-04-28 04:21
Duplicate of #756

**Closed by zombieJ** 2022-04-28 04:21 UTC

**Comment by jtheberge** [comment] 2022-04-28 04:24
How is this a duplicate of your link? This issue is about not finding DatePicker component.

**Comment by jtheberge** [comment] 2022-04-28 04:33
I see a related issue here - https://github.com/ant-design/ant-design/issues/35079. It may be the same cause, but the issue is a little different. I'm setting state inside the custom rendered cell component which crashes the app. In the above, it looks like it's just not causing re-render cycle properly.

**Comment by afc163** [comment] 2022-04-28 04:54
It is https://github.com/react-component/table/issues/756

**Comment by jtheberge** [comment] 2022-04-28 05:12
Ah thanks! I was able to fix like stated:
`render: () => <CustomCell />`

**Comment by aayush216** [comment] 2022-05-23 09:27
I was not able to understand why one of these cases worked but the other did not but I think I understand why now :-

`render: () => <CustomCell />` this will work. (because this is JSX, React.createElement is called here when render is called)
`render: CustomCell` this will not work. (this is not JSX, we are just calling this React component as a function, i.e. React.createElement is not called here when render is called which causes the issue.) [https://github.com/react-component/table/issues/756#issuecomment-1047613144](url)

anyone looking for a more in depth explanation should check this out :- [https://kentcdodds.com/blog/dont-call-a-react-function-component](url)

**Comment by yelvert** [comment] 2024-01-04 19:32
This is still broken for me on 5.10.0 using either of methods mentioned by @aayush216. Any state inside of CustomCell will be incorrect once the tables data changes.
