### ISSUE TITLE
Tree in Transfer can't disable if relating children and parents

### ISSUE THREAD

**Issue by xyj404** [ant-design/ant-design#19184] opened 2019-10-12 02:14 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pensive-fast-5vsfd)

### Steps to reproduce
Let data to right and the left data don't disable.

### What is expected?
can disable

### What is actually happening?
not disable

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 16.8.6 |
| System | macOS Mojave 10.14.3 |
| Browser | chrome 76.0.3809.100 |

---
It's can be seen that the console log is true, but disable fail.

**Comment by zombieJ** [comment] 2019-10-14 06:01
Duplicate of #18863

**Closed** 2019-10-14 06:02 UTC
Labels: Usage
