### ISSUE TITLE
As for the long English words to be displayed in the Tooltip component, the phenomenon of "disconnection" will occur in the middle of the word.

### ISSUE THREAD

**Issue by XanderXueMingJi** [ant-design/ant-design#11740] opened 2018-08-14 07:42 UTC
Hello, Tooltip component if the English word to display too long, the word will occur in the middle of the "disconnection" phenomenon, I looked inside the code, should be due to word-break: break-all; caused, do not know how to remove this code, how to solve
![weititop](https://user-images.githubusercontent.com/20898793/44078122-594a72dc-9fd8-11e8-8f46-c3b3a49056bc.png)

**Comment by afc163** [comment] 2018-08-14 07:46
Duplicate of #11739

**Closed by afc163** 2018-08-14 07:46 UTC
