### ISSUE TITLE
Maybe a css bug of Table SelectInvert Dropdown

### ISSUE THREAD

**Issue by Syzmex** [ant-design/ant-design#5423] opened 2017-03-21 08:01 UTC
When I use **RowSelection**, the fourth column is partially covered.
My table has left fixed columns.
Here is the screenshot.
![20d1f05d-efbc-4344-8311-c7bc3908949f](https://cloud.githubusercontent.com/assets/2884665/24137181/9e58b118-0e4d-11e7-9a86-75553c3ab8fb.png)

**Comment by xutou12** [comment] 2017-03-22 08:45
👌  demo here  [codepen demo](http://codepen.io/xutou12/pen/GWxwKP?editors=0010)

**Comment by yesmeck** [comment] 2017-03-22 09:51
@xutou12 

You give columns wrong width, six columns have 100% width total which  causes table can't compute width correctly.

**Comment by yesmeck** [comment] 2017-03-22 09:51
So, I thinks it's not a bug of antd, close this.

**Comment by xutou12** [comment] 2017-03-23 08:25
I don't think so...
If there are some fixed columns, and my table is designed responsively, and my column width setting is like this.

| column1     | column2    | column3     | column4      | column5     | column6    | column7     |
|----------|----------|----------|----------|----------|----------|----------|
|(min)width: 100px|(min)width: 100px|width: 30%|width: 30%|width: 40%|(min)width: 100px|(min)width: 100px|
| | |minWidth: 100px|minWidth: 100px|minWidth: 150px| | |
|fixed|fixed| | | |fixed|fixed|

When the table's width less than 750px, there is no column be covered, and it works fine with horizontal scrollbar. 
When the table's width more than 750px, it works fine too.
The percent-width columns's width total must be >= 100%.

Now the `<Table>` component is not support one column with px-minWidth and percent-width both, so I put a `<div>` tag  with px-minWidth into the `<td>` tags of the columns with percent-width. 

[Here is a new demo.](http://codepen.io/xutou12/pen/vxjRBj?editors=0110)

**Comment by yesmeck** [comment] 2017-03-26 09:09
Thanks for such a clear demo, if you already know how to fix this issue, could you open a PR?

**Comment by xutou12** [comment] 2017-03-27 03:05
ok, I'll do it in few days.

**Comment by afc163** [comment] 2017-04-09 06:44
Just give us PR, close this now.

**Closed by afc163** 2017-04-09 06:44 UTC
Labels: Bug, Need Demo
