### ISSUE TITLE
Button 组件中文垂直居中稍微偏下

### ISSUE THREAD

**Issue by shield2018** [ant-design/ant-design#20058] opened 2019-12-03 07:28 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-pocpt)

### Steps to reproduce
放一个button控件

### What is expected?
按钮内中文垂直居中

### What is actually happening?
按钮内中文垂直会偏下

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.12.0 |
| System | mac 10.14.6 |
| Browser | chrome 78 |

---
发现
https://github.com/ant-design/ant-design/pull/18139/commits/05181d552e452dc5de34e4293abf009be1e89fd3
提交将之前1.4999改成了1.5.我本地覆盖line-height为1.4999后，居中正常
![53626D2C-222D-45C7-8981-05FC34DCC2C3](https://user-images.githubusercontent.com/5371329/70029108-4c4a8b00-15e1-11ea-8fa9-caddc3d2e40d.jpg)
深色为antd:3.26.0
半透明为 antd:3.10.10
文字大概偏下了半像素

**Comment by afc163** [comment] 2019-12-03 07:51
@zombieJ ...sad

**Comment by afc163** [comment] 2019-12-03 07:51
Duplicate of #19972

**Closed by afc163** 2019-12-03 07:51 UTC
