### ISSUE TITLE
Jest testing, Warning: you should not use `ref` on enhanced form, please use `wrappedComponentRef

### ISSUE THREAD

**Issue by webdevsyd** [ant-design/ant-design#8903] opened 2018-01-10 05:49 UTC
### Version
3.1.0

### Environment
react v15.4.2, react-dom v15.4.2, enzyme v3.3.0, jest v22.0.4

### Reproduction link
[https://ant.design/components/form/](https://ant.design/components/form/)

### Steps to reproduce
```
<Form.Item
  className={(!business.edittingBusinessName ? styles.hidden : '')}
  label="Name" {...formItemLayout}
>
  {
    getFieldDecorator('name', {
      initialValue: business.data.partner ? business.data.name : 'Test Business',
      rules: [{ required: true }],
    })(<Input
      id="name"
      suffix={getSuffix('name')}
      onBlur={handleBusinessNameBlur}
    />)
  }
</Form.Item>
```

```
it('should set value for business name', () => {
    const wrapper = mount(<BusinessForm {...props} />);
    wrapper.instance().setFieldsValue({
      name: 'Test Business',
    });
    expect(wrapper.instance().getFieldValue('name')).toBe('Test Business');
  });
```

then do the npm run test

### What is expected?
It should not display a console.error

### What is actually happening?
This is displaying in the terminal

console.error node_modules/warning/warning.js:51
    Warning: you should not use `ref` on enhanced form, please use `wrappedComponentRef`. See: https://github.com/react-component/form#note-use-wrappedcomponentref-instead-of-withref-after-rc-form140

**Comment by benjycui** [comment] 2018-01-12 09:03
Please provide a re-producible repo.

**Comment by yesmeck** [comment] 2018-01-31 06:23
Closing since no reproduce.

**Closed by yesmeck** 2018-01-31 06:23 UTC
Labels: Component: Form, Need Reproduce

**Comment by windyrain** [comment] 2018-05-29 03:40
`wrapper.instance()` cause a warning.

* add wrappedComponentRef prop on wrappedComponentForm

    `<AddComponent wrappedComponentRef={(inst) => {formRef = inst}} />`

*  get form from formRef.props

     `const { form } = formRef.props; `

*  use antd form api

     `console.log(form.getFieldsValue());`

### a demo below

    import React from 'react';
    import { Form } from 'antd';
    import Add from '../pages/Add';

    const AddComponent = Form.create()(Add);

    describe('Add', () => {
      let wrapper, formRef;

      it('render without crashing', () => {
        wrapper = mount(<AddComponent wrappedComponentRef={(inst) => {formRef = inst}} />);
      });

      it('add item', () => {
        const { form } = formRef.props; 

        console.log(form.getFieldsValue());
        wrapper.find('button').simulate('click');
        console.log(form.getFieldsValue());
      });

    });

sorry for reply on a close issue, I think it will help someone like me.
