### ISSUE TITLE
Radio component is unclickable in IE 11

### ISSUE THREAD

**Issue by Mongkii** [ant-design/ant-design#19010] opened 2019-09-26 02:29 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/radio-cn/](https://ant.design/components/radio-cn/)

### Steps to reproduce
Click on a Radio component.

### What is expected?
The selected Radio should switch to the one you clicked on.

### What is actually happening?
The selected one doesn't change.

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.8.6 |
| System | Windows 10 1809 (Ver. 17763.107) |
| Browser | IE 11 (Ver. 11.55.17763.0) |

---
* This problem exists in both Radio and Radio.Button.
* It happens not only in my own project, but also the showcase on official site.

**Comment by keithort** [comment] 2019-09-26 11:58
Duplicate of https://github.com/ant-design/ant-design/issues/19005

**Closed** 2019-09-26 13:45 UTC
Labels: help wanted
