### ISSUE TITLE
create-react-app with babel-import plugin does not make antd treeshakeable

### ISSUE THREAD

**Issue by sharikovvladislav** [ant-design/ant-design#19471] opened 2019-10-28 20:45 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/sharikovvladislav/is-antd-treeshakeable](https://github.com/sharikovvladislav/is-antd-treeshakeable)

### Steps to reproduce
1. clone the repo
2. yarn
3. yarn run build && yarn run size

### What is expected?
I expect that bundle is not as big as 210 KB with treeshaking enabled in antd package.

### What is actually happening?
You will get overal size of 210 KB. Initial size (new cra application) is 41.18 KB. I don't expect that 150 KB was added for one notification.

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | 16.11.0 |
| System | macOS 10.14.6 (18G87) |
| Browser | Chrome  78.0.3904.70 (Official Build) (64-bit) |

---
The app is very simple. It is basic cra application + notification from antd.

I made all steps from https://ant.design/docs/react/use-with-create-react-app docs page (react-app-rewired   customize-cra   babel-plugin-import). I copy pasted `config-overrides.js` from the docs page. But bundle is very big anyway.

Even importing as:

```
import notification from 'antd/es/notification';
import 'antd/es/notification/style/css';
```

does not help.

**Comment by sharikovvladislav** [comment] 2019-10-28 20:46
Looks like https://github.com/ant-design/ant-design/issues/13274 is similar to this issue, but @kaushalyap did not use `customize-cra` there. I used it, but still get same result.

**Comment by zombieJ** [comment] 2019-10-29 02:49
Duplicate of #12011

Touch:
<img width="1426" alt="截屏2019-10-29上午10 48 48" src="https://user-images.githubusercontent.com/5378891/67733572-bc418080-fa39-11e9-906d-3abe017292a0.png">

**Closed by zombieJ** 2019-10-29 02:49 UTC
