### ISSUE TITLE
Table加上rowSelection，expandedRowKeys，onExpandedRowsChange这三个属性，页面非常的卡

### ISSUE THREAD

**Issue by Mathround** [ant-design/ant-design#14888] opened 2019-02-18 07:19 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#rowSelection](https://ant.design/components/table-cn/#rowSelection)

### Steps to reproduce
数据不是很多，也就一百条，不管是勾选还是展开或合并，都会延迟一两秒后才能操作

### What is expected?
不会很严重卡顿现象

### What is actually happening?
严重卡顿现象

| Environment | Info |
|---|---|
| antd | 3.13.3 |
| React | react |
| System | windows |
| Browser | 谷歌等其它浏览器 |

**Comment by afc163** [comment] 2019-02-18 07:59
Duplicate of #12408

trace #3789

**Closed by afc163** 2019-02-18 07:59 UTC

**Comment by Mathround** [comment] 2019-02-18 08:27
> Duplicate of #12408
> 
> trace #3789

表示没找到实际问题答案，分页并不能解决真正问题，依旧还是会出现卡的现象
