### ISSUE TITLE
Cascader 能否像select一样支持多选

### ISSUE THREAD

**Issue by qnlz** [ant-design/ant-design#27850] opened 2020-11-18 07:02 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以选择多个级联选项

### What does the proposed API look like?
无

**Comment by afc163** [comment] 2020-11-18 07:18
Duplicate of #23410

**Closed by afc163** 2020-11-18 07:18 UTC
