### ISSUE TITLE
Descriptions组件bordered=true时labelStyle与contentStyle的样式控制位置不对

### ISSUE THREAD

**Issue by su1924** [ant-design/ant-design#50545] opened 2024-08-22 15:51 UTC
### What problem does this feature solve?

Descriptions组件bordered=true时labelStyle与contentStyle的样式控制位置不对，样式被写到了.ant-descriptions-item-label下的span，这样很难控制宽度

### What does the proposed API look like?

期望样式写在.ant-descriptions-item-label上

**Comment by afc163** [comment] 2024-08-23 01:37
Duplicate of #50364

**Closed by afc163** 2024-08-23 01:37 UTC
Labels: unconfirmed
