### ISSUE TITLE
Differences Development / Production

### ISSUE THREAD

**Issue by beeef** [ant-design/ant-design#23788] opened 2020-04-30 11:51 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-3d97z)

### Steps to reproduce
This issue is about the `Switch` component. When using in development, the `Switch` works perfectly. The icons are displayed at the correct position when the `Switch` is checked and also when it's unchecked.

But when compiling the Production build, some things change. The `Switch` doesn't work as it should. If you go to the reproduction codesandbox, you can see that the icon of the `Switch` is not shown if it's not checked.

### What is expected?
The icons of the `checked={true}` and `checked={false}` states (using `uncheckedChildren` and `checkedChildren`) should be displayed inside the `Switch` component.

### What is actually happening?
The icon is not visible when the `Switch` is not `checked`.

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.12.0 |
| System | Pop!_OS 19.10 |
| Browser | Brave 1.7.98 |

---
I'm also using the `antd.compact.css` and it's awesome, but it seems that the font size and padding is a little bit bigger in the development version. In the production version everything gets even smaller, it's too small. This seems to be a bug I guess.

**Comment by afc163** [comment] 2020-04-30 11:53
Duplicate of #23784

**Closed by afc163** 2020-04-30 11:53 UTC
