### ISSUE TITLE
Sum of column values in footer.

### ISSUE THREAD

**Issue by remyvanderwereld** [ant-design/ant-design#8006] opened 2017-10-24 12:52 UTC
### What problem does this feature solve?
At this moment there's no solution for adding the table totals in the footer. I tried to add a new table with one row in the footer but this table is not inline with the column width. 

### What does the proposed API look like?
It would be nice to add a footer attribute to the column properties.

**Comment by afc163** [comment] 2017-10-24 12:53
Duplicate of #5710

**Closed by afc163** 2017-10-24 12:53 UTC

**Comment by ehsansk** [comment] 2023-03-20 06:04
we have same issue i want to sum of column data in that comun footer
