### ISSUE TITLE
InputNumber does not support addons

### ISSUE THREAD

**Issue by ruchidh** [ant-design/ant-design#15214] opened 2019-03-05 15:18 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2pk2lz8y7j)

### Steps to reproduce
import inputNumber  from antd library, then <InputNumber addonBefore="mrp" /> and run 

### What is expected?
expected the addon before the inputNumber with written text mrp

### What is actually happening?
No addon is working for inputnumber

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | react  16.7 |
| System | mac air  |
| Browser | google chrome |

---
Is there way to fix it ?

**Comment by zombieJ** [comment] 2019-03-05 15:52
duplicate of #14284

**Closed by zombieJ** 2019-03-05 15:52 UTC

**Comment by afc163** [comment] 2019-03-05 16:09
https://github.com/ant-design/ant-design/issues/10846#issuecomment-395663125
https://github.com/ant-design/ant-design/issues/1228#issuecomment-199338244
