### ISSUE TITLE
Select all option

### ISSUE THREAD

**Issue by karenmkrtumyan7** [ant-design/ant-design#40511] opened 2023-02-02 09:59 UTC
### What problem does this feature solve?

Logic wroten with onFilter and keeping state will move into your codes and we will not repeat the code.

### What does the proposed API look like?

for example selectAll={bool}

**Comment by afc163** [comment] 2023-02-02 10:45
Duplicate of https://github.com/ant-design/ant-design/issues/30041

**Closed by afc163** 2023-02-02 10:45 UTC
Labels: unconfirmed
