### ISSUE TITLE
<StyleProvider layer /> messageApi.success() 等提示的图标颜色被覆盖

### ISSUE THREAD

**Issue by liuzhaowei55** [ant-design/ant-design#49534] opened 2024-06-21 01:53 UTC
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-ehrfvz?file=index.tsx)

### Steps to reproduce

```javascript
createRoot(document.getElementById('container')).render(
  <StyleProvider layer>
    <Demo />
  </StyleProvider>
);
```

```javascript
<Button
          type="primary"
          onClick={() => {
            messageApi.success('success');
          }}
        >
          Success
        </Button>
```
<img width="342" alt="image" src="https://github.com/ant-design/ant-design/assets/1835787/7903fb33-b600-4d9c-9630-e35dd144ae36">
<img width="326" alt="image" src="https://github.com/ant-design/ant-design/assets/1835787/b2db74bb-aa56-4e8d-9ea3-90d928d812e6">

### What is expected?

success, error, info, warn 等消息使用不同颜色图标

### What is actually happening?

颜色设置未生效

| Environment | Info |
| --- | --- |
| antd | 5.18.2 |
| React | 18.3.1 |
| System | macOS |
| Browser | Arc 1.21.3 |

**Comment by MadCcc** [comment] 2024-06-21 01:54
Duplicate of https://github.com/ant-design/ant-design/issues/49377

**Closed by MadCcc** 2024-06-21 01:54 UTC
Labels: unconfirmed
