### ISSUE TITLE
Modal中进行Select选择，Modal自动隐藏

### ISSUE THREAD

**Issue by sb9527** [ant-design/ant-design#27123] opened 2020-10-13 05:00 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/focused-wildflower-lcs1j?file=/index.js)

### Steps to reproduce
分别将antd版本切换成4.7.0和4.6.6，查看Modal中点击Select某一项后的效果

### What is expected?
Select选择某一项后，Modal不要自动隐藏

### What is actually happening?
Select选择某一项后，Modal自动隐藏

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | ～ |
| System | ～ |
| Browser | Chrome |

---
如果将`maskClosable={false}`加入到Modal，则不会出现异常

看起来在4.7.0版本中，Modal中点击Select选项会判定为点击了蒙层

**Comment by yoyo837** [comment] 2020-10-13 05:03
Duplicate of #27084

删除node_modules 和lock文件 重新安装试试

**Comment by afc163** [comment] 2020-10-13 05:13
Fixed in https://github.com/react-component/dialog/pull/204

**Closed** 2020-10-13 05:13 UTC
