### ISSUE TITLE
Upload上传文件限制文件格式.xlsx，但是.xls格式的文件也可以上传

### ISSUE THREAD

**Issue by 481418011** [ant-design/ant-design#10343] opened 2018-05-03 07:23 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.5

### Environment
ie10浏览器和360浏览器

### Reproduction link
[http://income-tax.zgcszkw.com/](http://income-tax.zgcszkw.com/)

### Steps to reproduce
请先注册一个账号，点击左侧menu数据中心，点击参数配置，上传文件

### What is expected?
Upload上传文件限制文件格式.xlsx，但是.xls格式的文件不可以上传

### What is actually happening?
Upload上传文件限制文件格式.xlsx，但是.xls格式的文件也可以上传

**Comment by zheeeng** [comment] 2018-05-04 02:35
Please provide a demo reproduction. And I have a personal suggestion that checking the implementation of the file types validation. With your use-case, you cloud to validate the file's MIME or the file's extension.

**Comment by yesmeck** [comment] 2018-05-04 07:33
Duplicate of #9071

**Closed by yesmeck** 2018-05-04 07:33 UTC

**Comment by iiiok** [comment] 2018-05-07 04:41
1.
accept: "application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/msword,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel,application/pdf",

2.
      accept: '.pdf,.doc,.xls,.xlsx,.docx',
