### ISSUE TITLE
Tables more Responsive / Ellipsis Implementation

### ISSUE THREAD

**Issue by dbrrt** [ant-design/ant-design#14522] opened 2019-01-24 00:52 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Displaying automatically the content for Table component, especially long text which could be ellipsed

### What does the proposed API look like?
<Table ellipsed={true}/>
Before 
|Long Content|Short Content| Actions
Long Content 
Long Content

After
|Long Content...|Short Content| Actions

**Comment by afc163** [comment] 2019-01-24 02:30
Duplicate of #5753

**Closed by afc163** 2019-01-24 02:30 UTC
