### ISSUE TITLE
升级ant design到最新版本，Modal confirm组件国际化出现问题

### ISSUE THREAD

**Issue by beibeibear** [ant-design/ant-design#27787] opened 2020-11-16 06:54 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce
Modal confirm组件如果不传okText 与 cancelText，点击confirm打开弹窗，再点击取消, 然后再点击打开弹窗，默认的取消，确定中文按钮名称变为英文

### What is expected?
国际化不会有问题

### What is actually happening?
国际化有问题

| Environment | Info |
|---|---|
| antd | 4.8.3 |
| React | 16.12.0 |
| System | windows |
| Browser | chrome 86.0.4240.193 |

**Comment by xrkffgg** [comment] 2020-11-16 06:57
Duplicate of https://github.com/ant-design/ant-design/issues/27597

**Closed** 2020-11-16 12:21 UTC
Labels: 🐛 Bug
