### ISSUE TITLE
Select is not working properly in Web Component

### ISSUE THREAD

**Issue by 4in** [ant-design/ant-design#28012] opened 2020-11-26 04:05 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/summer-monad-82xdh?file=/src/SelectComp.tsx)
https://codesandbox.io/s/summer-monad-82xdh?file=/src/SelectComp.tsx

### Steps to reproduce
Web Component中的Select组件点击后会立即消失，但是focus后按键盘上下键可以正常工作

Select's dropdown will disappear immediately after click, but up/down key work.

### What is expected?
点击后下拉框正常显示

Show dropdown after click.

### What is actually happening?
点击后下拉框立即消失

Dropdown disappear after click.

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | 17.0.0 |
| System | macOS |
| Browser | Chrome 87 |

**Comment by afc163** [comment] 2020-11-27 06:25
Duplicate of #27250

**Closed by afc163** 2020-11-27 06:25 UTC
Labels: help wanted
