### ISSUE TITLE
菜单错误

### ISSUE THREAD

**Issue by scanking** [ant-design/ant-design#30748] opened 2021-05-28 02:26 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/menu-cn/](https://ant-design.gitee.io/components/menu-cn/)

### Steps to reproduce
调整浏览器宽度

### What is expected?
最后一个“…”代表更多的菜单能够跟随显示的菜单后面

### What is actually happening?
又空白菜单占位，order属性不生效

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | 17.0.1 |
| System | win10 |
| Browser | chorme 89.0.4389.114 |

**Comment by afc163** [comment] 2021-05-28 05:28
Duplicate of #30662

**Closed by afc163** 2021-05-28 05:28 UTC
