### ISSUE TITLE
@ant-design can provide tree-shaking

### ISSUE THREAD

**Issue by yuanclan** [ant-design/ant-design#12163] opened 2018-09-10 08:37 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
@ant-design can provide tree-shaking,In version 3.9.0, two categories were added, with more than 90 new ICONS,But I can't use all the ICONS.

### What does the proposed API look like?
@ant-design can provide tree-shaking,In version 3.9.0, two categories were added, with more than 90 new ICONS,But I can't use all the ICONS.

**Comment by afc163** [comment] 2018-09-10 08:46
Duplicate of #12011

**Closed by afc163** 2018-09-10 08:46 UTC
