### ISSUE TITLE
Table 同时设置 scroll-x 为 max-content 与 scroll-y 会造成Table横向滚动失效

### ISSUE THREAD

**Issue by fubd** [ant-design/ant-design#29283] opened 2021-02-08 08:23 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-t5sbx?file=/index.js)

### Steps to reproduce
STEP-1. 
``` <Table
          columns={columns}
          dataSource={data}
          size="middle"
          pagination={false}
          scroll={{
            x: "max-content",
            y: document.body.offsetHeight - 220          }}
          bordered
        />
 ```

STEP-2. 
```
    <Table
          columns={columns}
          dataSource={data}
          size="middle"
          pagination={false}
          scroll={{x: "max-content"}}
          bordered
        /> 
```

### What is expected?
max-content 起到效果；没有造成Table中的内容换行显示。

### What is actually happening?
max-content失效；Table中的内容被挤压变形，除非改成固定的像素值。

| Environment | Info |
|---|---|
| antd | 4.12.2 |
| React | 17.0.1 |
| System | mac os v11.1 |
| Browser | Chrome 88.0.4324.150 |

**Comment by fubd** [comment] 2021-02-22 14:08
有人吗 Is there anyone?

**Comment by afc163** [comment] 2021-03-11 15:14
Duplicate of #29734

**Closed by afc163** 2021-03-11 15:14 UTC

**Comment by childrentime** [comment] 2021-11-23 07:38
这个问题解决了吗

**Comment by fcppliang** [comment] 2025-05-07 07:02
When using  4.16.13 version, there are also similar issues
