### ISSUE TITLE
 antd Uncaught (in promise) TypeError: Cannot read Property 'call' of undefined

### ISSUE THREAD

**Issue by beevivo6** [ant-design/ant-design#16703] opened 2019-05-21 07:00 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://admin.test.shanlaan.com](http://admin.test.shanlaan.com)

### Steps to reproduce
1；页面加载出错，错误如下，
2； antd Uncaught (in promise) TypeError: Cannot read Property 'call' of undefined
      at c(umi.js:1)
      at Object.STA  （40.async.js:1）
      at c(umi.js:1)
      at asnyc Promise.all(/index.js:0)

### What is expected?
1；网站加载成功。。

### What is actually happening?
 antd Uncaught (in promise) TypeError: Cannot read Property 'call' of undefined

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.8 |
| System | mac,window |
| Browser | 谷歌 |

**Comment by afc163** [comment] 2019-05-21 07:17
Duplicate of #16702

**Closed by afc163** 2019-05-21 07:17 UTC
