### ISSUE TITLE
Inconsistent default behavior on Grid

### ISSUE THREAD

**Issue by kossel** [ant-design/ant-design#5030] opened 2017-02-23 16:59 UTC
Antd: 2.7.2

with grid (Col and Row) if I use offset on a specific screen size, then I have to add default value for other screen size, otherwise it applies to all.

Please look at the example: http://codepen.io/kossel/pen/JWjWOP

Row 1 has offset: 2 in all screen size even I just have set `offset:2` in xs size.
Row 2 with offset removed then everything work as default behaviour.
Row 3 is the expected behavior, but I need to add `offset:0` to all the screen size.

inspecting the elments, there is no media query on the **ant-col-xs-offset-2**
![image](https://cloud.githubusercontent.com/assets/1760498/23269933/c278d2e4-f9b7-11e6-9da4-1f7455c7ae8c.png)

This also happens with grid order

**Comment by NE-SmallTown** [comment] 2017-02-24 01:34
Ye,I think it's not a bug,it's intentional.

But you can see the [bootstrap v3](http://v3.bootcss.com/css/#grid-offsetting) is the same with you write.
But [boostrap v4](http://v4-alpha.getbootstrap.com/layout/grid/#offsetting-columns) add media query on offset.

[relevant issue](https://github.com/twbs/bootstrap/issues/19798)

**Comment by afc163** [comment] 2017-02-24 03:42
`lg={20}` is alias for `lg={{ span: 20 }}` now.

Maybe we should change `lg={20}` equal to `lg={{ span: 20, offset: 0, push: 0, pull: 0 }}`?

**Comment by NE-SmallTown** [comment] 2017-02-24 03:55
@afc163 Maybe we can provide a option,because if we change the default behavior like bootstap V4,I guess there will be someone to ask us to go back.

**Comment by kossel** [comment] 2017-02-24 05:28
I see, so antd works like bootstrap v3 than bootstrap v4, where `sm={3}` actually means "sm and greater than sm" and `xs` actually means "xs and greater than xs"?

if that is true then I can understand why we have to explicitly put `offset:0` for other screen size

**Comment by afc163** [comment] 2017-02-24 08:25
@kossel Yes, I just update the documentation about it.

I am closing this now.

**Closed by afc163** 2017-02-24 08:25 UTC

**Comment by NE-SmallTown** [comment] 2017-02-24 08:33
@afc163 maybe we can discuss the option as I mentioned above?

**Comment by afc163** [comment] 2017-02-24 08:50
Actually we didn't change any of bootstrap default behavior. We added media query on offset except for xs, just like bootstrap v3  and v4.

**Comment by NE-SmallTown** [comment] 2017-02-24 09:07
@afc163 Oh,sorry,I go back to see again, bootstrap v3 and v4 are the same.But we can provide some config to help users if they just set `xs-offset` and the config is `true`,we auto set the `sm-offset-0`.

**Comment by afc163** [comment] 2017-02-24 09:10
I think that will confuse people who look bootstrap's documentation.

**Comment by NE-SmallTown** [comment] 2017-02-24 10:07
@afc163 Why?The config default is false,and we will also add doc description, as a new to antd,he won't set the config when he doesn't know what it means.But your concern is also reasonable,so I have to clear that this is just my thought,if there will be anybody else post relevant issue,happy to discuss again.
