### ISSUE TITLE
垂直模式下导航栏显示错误

### ISSUE THREAD

**Issue by junhui75165** [ant-design/ant-design#7588] opened 2017-09-14 01:52 UTC
### Version
2.13.1

### Environment
chrome 版本 60.0.3112.101（正式版本） （32 位）

### Reproduction link
[https://codepen.io/junhui/pen/MEYoaX?&editors=001](https://codepen.io/junhui/pen/MEYoaX?&editors=001)

### Steps to reproduce
当导航栏位置在底部时

### What is expected?
能否自动向上或向右展开

### What is actually happening?
导航展开的内容向下拉出时会被底部覆盖

**Comment by afc163** [comment] 2017-09-14 01:54
Duplicate of #2830

**Closed by afc163** 2017-09-14 01:54 UTC

**Comment by junhui75165** [comment] 2017-09-14 02:19
@afc163 So this question is not yet resolved right?

**Comment by afc163** [comment] 2017-09-14 02:25
yep~
