### ISSUE TITLE
Select组件定义suffixIcon后点击自定义icon后 没法触发下拉框弹出

### ISSUE THREAD

**Issue by xiyangjun** [ant-design/ant-design#28312] opened 2020-12-11 02:44 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wubiankuang-antd492-forked-u6h4d?file=/index.js)

### Steps to reproduce
Select组件 加入suffixIcon属性 点击自定义icon

### What is expected?
点击自定义icon和点击自带小剪头icon行为保持一致

### What is actually happening?
点击自定义icon行为和点击自带icon行为不一致

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 16.13.1 |
| System | macos 10.15.7 |
| Browser | chrome  86.0.4240.198 |

**Comment by afc163** [comment] 2020-12-11 02:48
Duplicate of #27479

**Closed by afc163** 2020-12-11 02:48 UTC

**Comment by qq1147050160** [comment] 2021-08-05 08:29
需要添加className="ant-select-suffix"才有效果

来自：https://github.com/ant-design/ant-design/pull/23274
