### ISSUE TITLE
formitem  出现错误提示后在输入内容还是会抖动一下

### ISSUE THREAD

**Issue by mwj610** [ant-design/ant-design#36618] opened 2022-07-20 10:23 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-21-7-forked-mtcpms?file=/demo.js)

### Steps to reproduce

出现错误提示后在输入内容

### What is expected?

不会上下抖动

### What is actually happening?

上下抖动

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 18.0.1 |
| System | windows 11 |
| Browser | edge |

**Comment by MadCcc** [comment] 2022-07-20 10:25
Duplicate of https://github.com/ant-design/ant-design/issues/36470

**Closed by MadCcc** 2022-07-20 10:25 UTC
