### ISSUE TITLE
Improve usability of date range picker on smaller screens

### ISSUE THREAD

**Issue by gabschne** [ant-design/ant-design#41908] opened 2023-04-20 11:04 UTC
### What problem does this feature solve?

This is a follow up of https://github.com/ant-design/ant-design/issues/12831.

In both modes, with or without time selection, the date range picker tends to be too wide on mobile devices in a vertical views or on small screens, causing an overflow. This makes using it on such devices difficult or even impossible.

### What does the proposed API look like?

I've given some thoughts on how to improve the date range picker in terms of responsiveness. First of all: I'm not completely satisfied with some of them myself, but I can't think of anything better right now.

- From a certain screen width or if the width of the rangepicker is >= screenwidth the picker view could switch from the two (column) calendar mode to a one calendar one, as it is when the time picker is enabled. This should be the easiest to implement of all the ideas here.
- When time selection is enabled, it could be hidden first and the day can be selected by the user. Once a day is selected, the time selection appears as an extra view (inside the selection window), e.g. from the right like a drawer or as a modal (also inside the picker view, of course). This increases the steps needed to select a date range, but in return also significantly increases usability on smaller displays. **Note:** I intentionally didn't write that the day selection should be replaced by the time one, because I think that too much active changing of already displayed items and views is bad design/UI.
- Preset selection: The presets view could be hidden first as well and accessible via a button in the header or footer of the picker view. It could appear as a drawer from the left inside the view or as a modal. The latter would be ok in my opinion, as EITHER a preset OR manually a date range is selectable.
- Another quick thought I just had while writing: Maybe it increases usability if the picker view switches from a "floating mode" to a centered "modal mode" at a certain screen size, at it is with some native picker controls.  **Note:** The disadvantage here would be that other picker views (date picker, time picker, ...) should behave the same for consistency reasons, so this would be quite a bigger change.

I may create some more mockups later today and attach them.

As I mentioned before, this is a complex issue and I am not happy with all of my ideas. So I would really like to read other suggestions.

**Comment by MadCcc** [comment] 2023-04-26 07:51
Since antd is mostly for pc, we didn't work a lot on responsive layout for most components, but it's good to make it.
In mobile device, `ant-design-mobile` would be more suitable for you. And users may not expect a popover when they have to choose a time.

We may improve UX of RangePicker if we have a better design.

**Comment by afc163** [comment] 2023-05-10 05:38
Duplicate of https://github.com/ant-design/ant-design/issues/26758

**Closed by afc163** 2023-05-10 05:39 UTC
Labels: 📱Mobile Device
