### ISSUE TITLE
Allow  `layout` property in `Form.Item`. 

### ISSUE THREAD

**Issue by MostFrumiousBandersnatch** [ant-design/ant-design#36956] opened 2022-08-08 11:23 UTC
### What problem does this feature solve?

By now, we have `layout` property in `Form`, though it makes sense to combine items with both vertical and horizontal layout in one form, sometimes. 

### What does the proposed API look like?

Form.Item -> layout : 'vertical' | 'horizontal'

**Comment by zombieJ** [comment] 2022-08-08 11:25
Could you provide a layout sample about your reqirement?

**Comment by afc163** [comment] 2022-08-08 12:05
Duplicate of #31044

**Closed by afc163** 2022-08-08 12:05 UTC
Labels: needs-more-info
