### ISSUE TITLE
Popover组件在自定义组件上不生效

### ISSUE THREAD

**Issue by xwzpp** [ant-design/ant-design#12812] opened 2018-10-24 10:58 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.2

### Environment
chrome70 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pjwkpvmlym)

### Steps to reproduce
自键一个组件，然后使用Popover进行包装，即可复现

### What is expected?
Popover生效

### What is actually happening?
Popover不生效

---
在以前的antd3.x版本上，这个功能Ok，没有问题。应该是最近几个版本引入的bug.

**Comment by afc163** [comment] 2018-10-24 10:59
Duplicate of #4270

**Closed by afc163** 2018-10-24 10:59 UTC

**Comment by afc163** [comment] 2019-05-08 17:03
#15909

**Comment by lyndon-learn** [comment] 2023-06-15 08:48
how to resolve this problem?
