### ISSUE TITLE
Upload组件坏掉了，快来修一修，十万火急，mac电脑点组件没反应

### ISSUE THREAD

**Issue by zengganglan** [ant-design/ant-design#33999] opened 2022-02-10 06:51 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
https://ant.design/components/upload-cn/

### What is expected?
https://ant.design/components/upload-cn/

### What is actually happening?
https://ant.design/components/upload-cn/

| Environment | Info |
|---|---|
| antd | 4.18.6 |
| React | ·· |
| System | q q |
| Browser | · |

---
https://ant.design/components/upload-cn/

**Comment by afc163** [comment] 2022-02-10 06:55
Duplicate of https://github.com/ant-design/ant-design/issues/33966

**Closed** 2022-02-10 07:05 UTC
