### ISSUE TITLE
TextArea加上allowclear属性后，resize只能向下拉，回不去

### ISSUE THREAD

**Issue by fred8617** [ant-design/ant-design#20688] opened 2020-01-06 06:16 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-1nzto)

### Steps to reproduce
向下拉

### What is expected?
自由上下拉动

### What is actually happening?
只能向下

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | 16.8  |
| System | win |
| Browser | chrome |

**Comment by afc163** [comment] 2020-01-06 06:17
Duplicate of #19652

**Closed by afc163** 2020-01-06 06:17 UTC
