### ISSUE TITLE
ReferenceError: self is not defined.

### ISSUE THREAD

**Issue by masonyeh** [ant-design/ant-design#7169] opened 2017-08-10 12:39 UTC
### Version
3.0.0-alpha0

### Environment
react ssr node

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
When i use React SSR ,webpack has been pass.but node start it ,it was report 'ReferenceError: self is not defined.'

if i don't import package of ant design it is ok no error report for me...

help help help!!!!!!

### What is expected?
not error please

### What is actually happening?
got ReferenceError: self is not defined.

**Comment by afc163** [comment] 2017-08-10 12:52
Could you problem a reproducible repo?

**Comment by afc163** [comment] 2017-08-11 01:59
@masonyeh ping

**Comment by masonyeh** [comment] 2017-08-11 02:24
Hey @afc163 thank you @ me.

my  repository has been upload to github already below
https://github.com/masonyeh/react-ssr-ant-design.git  
this is a react ssr demo

going to ./ dir

type run command: ' npm run dev'  it was work that for develop environment,
and run 'npm run build' for product it was work as well
but npm run start  

it is mean for node run  about the server.js can not work....

server.js ->  /dist/server/server.js

so i don't know what's happening on it...

it is error on css???for webpack some where config is waring?

**Comment by keller35** [comment] 2017-08-11 02:26
@afc163 
I met this issue when i am using vue ssr also.
I guess this issue may caused by [babel-plugin-import](https://github.com/ant-design/babel-plugin-import).
If i remove  the importplugin and import antd component and its style manually, this issue solved.

**Comment by masonyeh** [comment] 2017-08-11 02:39
@keller35 have you support babel-plugin-import on your project now?
because if you not suport it ant-design will be so huge on your project unless you import about detail js and css of ant design!

**Comment by keller35** [comment] 2017-08-11 02:50
@masonyeh 
Yes, i import detail js and css manually, but it is a little bit complicated.
So i change to using babel-plugin-import, sadly it cause this issue.

**Comment by masonyeh** [comment] 2017-08-11 02:52
@keller35 it was a troublesome coding way!

**Comment by afc163** [comment] 2017-08-11 07:42
https://github.com/masonyeh/react-ssr-ant-design/pull/1

There are two problems in you repo:

1. babel-plugin-import will import css files when you set the `style: 'css'`, which introduced the `self is not defined` bug. It can be fixed by https://github.com/masonyeh/react-ssr-ant-design/pull/1/commits/73a8c61116786f6644390d5221444a76b1c23981
2. You imported two polyfills from `babel-polyfill` and `babel-plugin-transform-runtime` which will cause the problem:
   <img width="672" alt="2017-08-11 13 50 32" src="https://user-images.githubusercontent.com/507615/29204789-9644130e-7eab-11e7-8500-f73c28822cd6.png">
   It is been fixed by https://github.com/masonyeh/react-ssr-ant-design/pull/1/commits/4b8519e636ab9813129bee1a69005d7968c8d678 [参考](https://github.com/lmk123/blog/issues/45)

**Comment by afc163** [comment] 2017-08-11 07:44
It turns out it is not `antd-related` bug so I suggest you ask in stackoverflow or segmentfault next time useless you can make sure there is some wrong in antd.

**Closed** 2017-08-11 07:44 UTC
Labels: Usage

**Comment by robertosannazzaro** [comment] 2021-03-27 16:22
I am having the same issue with Next.js version 10. Any idea on how this can be solved?

**Comment by ilkaydnc** [comment] 2021-04-22 13:04
I got the same error. I thought it was a problem with SSR because I was using Next.js. As a result, the problem disappeared when I did the following code blocks.

**./components/Chart/tsx**
```ts
import { useState, useRef } from 'react'
import { Line } from '@ant-design/charts'

const Chart = () => {
  const [data, setData] = useState([
    { year: '1991', value: 3 },
    { year: '1992', value: 4 },
    { year: '1993', value: 3.5 },
    { year: '1994', value: 3 },
    { year: '1995', value: 4.9 },
  ])

  const ref = useRef<any>()

  return (
    <Line
      data={data}
      height={600}
      xField="year"
      yField="value"
      ref={ref}
      smooth
      tooltip={false}
    />
  )
}

export default Chart

```

**./App.tsx**

```ts
import { NextPage } from 'next'

const Chart = dynamic(() => import('@components/Chart'), { ssr: false })
```

**Comment by allanzi** [comment] 2021-06-09 19:49
> I got the same error. I thought it was a problem with SSR because I was using Next.js. As a result, the problem disappeared when I did the following code blocks.
> 
> > This solution is valid for Next.js. I think you can do it by searching the dynamic/lazy import for React.
> 
> ```ts
> // ./components/Chart/tsx
> 
> import { useState, useRef } from 'react'
> import { Line } from '@ant-design/charts'
> 
> const Chart = () => {
>   const [data, setData] = useState([
>     { year: '1991', value: 3 },
>     { year: '1992', value: 4 },
>     { year: '1993', value: 3.5 },
>     { year: '1994', value: 3 },
>     { year: '1995', value: 4.9 },
>   ])
> 
>   const ref = useRef<any>()
> 
>   return (
>     <Line
>       data={data}
>       height={600}
>       xField="year"
>       yField="value"
>       ref={ref}
>       smooth
>       tooltip={false}
>     />
>   )
> }
> 
> export default Chart
> ```
> 
> ```ts
> // ./App.tsx
> 
> import { NextPage } from 'next'
> 
> const Chart = dynamic(() => import('@components/Chart'), { ssr: false })
> ```

Thanks man, saved my day 😄
