### ISSUE TITLE
Calendar Events View

### ISSUE THREAD

**Issue by Fangmingdu** [ant-design/ant-design#26685] opened 2020-09-11 00:50 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We already have a very nice calendar view and have capabilities to custom rendering cell or month. However, it would be nice to be able to render multiple days together as a way to show a event spanning multiple days. Examples are here: http://jquense.github.io/react-big-calendar/examples/index.html

### What does the proposed API look like?
Examples are here:
http://jquense.github.io/react-big-calendar/examples/index.html
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/5725594/92833834-2501c500-f38e-11ea-964e-7bcd2ede272e.png">

**Comment by afc163** [comment] 2020-09-11 00:59
Duplicate of #12591

**Closed by afc163** 2020-09-11 00:59 UTC
