### ISSUE TITLE
table 表格 提供 合计功能

### ISSUE THREAD

**Issue by lljava2007** [ant-design/ant-design#17333] opened 2019-06-27 06:09 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
table 表格 提供 合计功能

### What does the proposed API look like?
table 表格 提供 合计功能

**Comment by afc163** [comment] 2019-06-27 06:10
Duplicate of #5710

**Closed by afc163** 2019-06-27 06:10 UTC
