### ISSUE TITLE
Remove hard dependency on moment.js

### ISSUE THREAD

**Issue by pocesar** [ant-design/ant-design#15390] opened 2019-03-13 22:25 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I'm doing all the imports manually, like antd/es/grid or antd/es/layout, but somehow moment is being added as a dependency, but I'm not using the DatePicker or anything date related.
moment.js alone is 52kb, and all the functions I'm using from Ant Design are 50kb... 

### What does the proposed API look like?
All components seems to be intertwined without a clear away to separate them

**Comment by ycjcl868** [comment] 2019-03-13 23:41
Duplicate of #15311.

**Closed by ycjcl868** 2019-03-13 23:41 UTC
