### ISSUE TITLE
table 设置virtual     components 被覆盖

### ISSUE THREAD

**Issue by learn-js2016** [ant-design/ant-design#44990] opened 2023-09-21 06:07 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-g57cnl?file=/index.js)

### Steps to reproduce

table 设置virtual     components 被覆盖

### What is expected?

components 不被覆盖

### What is actually happening?

components 被覆盖

| Environment | Info |
| --- | --- |
| antd | 5.9.2 |
| React | 18.2.0 |
| System | Window 10 |
| Browser | Chrome 88.0 |

**Comment by zombieJ** [comment] 2023-09-21 06:08
virtual 使用的 `components` 做虚拟定制，文档里漏了，要补一下。

**Comment by yoyo837** [comment] 2023-09-21 06:10
Duplicate of #44787

**Comment by zombieJ** [comment] 2023-09-21 06:11
合到 #44787 里一起跟踪吧

**Closed by zombieJ** 2023-09-21 06:11 UTC
Labels: 📝 Documentation
