### ISSUE TITLE
穿梭框如何自定义左右footer？

### ISSUE THREAD

**Issue by yatingFeng** [ant-design/ant-design#31089] opened 2021-06-22 12:45 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
不太通用哦

### What does the proposed API look like?
穿梭框可以支持同时设置左右footer，而不是一个footer同时作用在

**Comment by afc163** [comment] 2021-06-22 14:17
Duplicate of #28082

**Closed by afc163** 2021-06-22 14:17 UTC
Labels: help wanted
