### ISSUE TITLE
Table component doesn't allow custom sort icons

### ISSUE THREAD

**Issue by evikadar** [ant-design/ant-design#30674] opened 2021-05-25 08:47 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Our team uses Ant table and we would like to add custom sort icons. We were wondering if we could send the sort icon via a prop type, but we could not find any prop type that satisfies this. 

Having this feature can make the design of the tables look smoother in use cases where custom design is implemented, thus creating a nicer look and unified feeling for users. 
There has been a previous issue but it has been closed because it was filed against ant 3: https://github.com/ant-design/ant-design/issues/19561

### What does the proposed API look like?
`<Table sortUpIcon={<MyIconAscend />} sortDownIcon={<MyIconDescend />} sortNoneIcon={<MyIconNoSort />} />`

**Comment by afc163** [comment] 2021-05-26 05:46
Duplicate of #19561

**Closed by afc163** 2021-05-26 05:46 UTC

**Comment by afc163** [comment] 2023-05-22 04:05
Supported in https://github.com/ant-design/ant-design/pull/42498

**Comment by evikadar** [comment] 2023-05-22 05:28
Thank you @afc163!!
