### ISSUE TITLE
Mentions 提及 组件键盘选择option时选项下拉框能否跟随滚动

### ISSUE THREAD

**Issue by LMYAAA** [ant-design/ant-design#45603] opened 2023-10-31 09:00 UTC
### What problem does this feature solve?

解决展示问题，与select组件保持一致

### What does the proposed API look like?

期望是在原有select原有的基础上再去添加提及功能

**Comment by afc163** [comment] 2023-11-01 02:49
Duplicate of #41651

**Closed by afc163** 2023-11-01 02:49 UTC
Labels: unconfirmed
