### ISSUE TITLE
 希望DatePicker提供一个接口yearPicker，

### ISSUE THREAD

**Issue by haoLingLing** [ant-design/ant-design#15133] opened 2019-03-01 08:05 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1 会涉及到一些切换年月日的事情，如年月日选择，单独选择年的时候，这时候通过mode 年的时候，很多Api 使用不方便

### What does the proposed API look like?
 <YearPicker disabledDate={disabledDate} placeholder="Select year" />

**Comment by afc163** [comment] 2019-03-01 08:21
Duplicate of #4524

**Closed by afc163** 2019-03-01 08:21 UTC
