### ISSUE TITLE
RangePicker onOpenChange事件异常

### ISSUE THREAD

**Issue by CNFeffery** [ant-design/ant-design#45902] opened 2023-11-15 14:02 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fan-wei-xuan-ze-qi-antd-5-11-1-forked-cq6zrw?file=/demo.js)

### Steps to reproduce

按照重现链接中做法进行可控open后，发现onOpenChange在用户完成两端日期选择后，并没有像v4版本中那样触发false，导致展开菜单不会在完成两端选择后自动关闭

![image](https://github.com/ant-design/ant-design/assets/49147660/b58b6f87-644a-4bc4-8de8-40b76f45d360)

### What is expected?

像antd v4一样恢复正常的交互行为

### What is actually happening?

onOpenChange异常

| Environment | Info |
| --- | --- |
| antd | 5.11.1 |
| React | ^18.0.0 |
| System | win11 |
| Browser | Chrome |

**Comment by aaarichter** [comment] 2023-11-15 20:18
@CNFeffery I google translated your text and if this 

> After performing a controllable open according to the method in the reproduction link, I found that onOpenChange did not trigger false like in the v4 version after the user completed the date selection at both ends, causing the expanded menu to not automatically close after completing the selection at both ends.

is correct, then reading the `onOpenChange` definition https://ant.design/components/date-picker#common-api, this callback is fired when you open the picker and close it (e.g by clicking outside of the component). if you remove the `open={open}` and `setOpen(e)`  code lines from your example this picker works as you expect it

**Comment by CNFeffery** [comment] 2023-11-16 01:05
@aaarichter But this works well in `antd ` v4 ( https://codesandbox.io/s/fan-wei-xuan-ze-qi-antd-4-24-14-forked-hg587y?file=/demo.js )

![image](https://github.com/ant-design/ant-design/assets/49147660/ca03003d-0ade-4f23-9c0a-2d55d3ad3bd1)

**Comment by afc163** [comment] 2023-11-16 02:00
Duplicate of #39200

**Closed by afc163** 2023-11-16 02:00 UTC
Labels: unconfirmed

**Comment by aaarichter** [comment] 2023-11-16 08:40
@CNFeffery I'm fairly new to antd and don't know how it worked in v4. 

The meaning of the wording of `onOpenChange` tells me this is a handler that gets fired when the open state of the picker changes, so you can run custom code. Using it to set the open state of the component via useState setter, seems wrong. So if v4 required you to set the picker's open state through `onOpenChange`, then the v5 behavior is a big improvement. 

What are you trying to achieve with `onOpenChange`?

**Comment by CNFeffery** [comment] 2023-11-21 10:04
@aaarichter @afc163  The weirdest thing is that `onOpenChange` perform like v4 when `showTime` is set to `true`:

![image](https://github.com/ant-design/ant-design/assets/49147660/ebd31efb-1128-4523-9968-fb98b2da924f)

**Comment by aaarichter** [comment] 2023-11-22 09:00
@CNFeffery When you set `showTime`, the range picker gets this ok button to confirm your date/time selection. It seems the okay button changes the internal open state when an end date has been set. Then the `onOpenChange` fires afterward passing the new state in the handler. When this happens, your code above will set `open` to false, which will render the component again. But the RangePicker component's internal open state is already `false`

**Comment by CNFeffery** [comment] 2023-11-22 09:06
@aaarichter There are definitely some issues with v5 versus v4 in this regard, but v4's interaction style feels natural to my users.
