### ISSUE TITLE
Layout.Sider 与DirectoryTree联合使用时候，设置了width ,x方向字段过长时候 点击只能选中width范围内的数据

### ISSUE THREAD

**Issue by shijuanjuan93** [ant-design/ant-design#22664] opened 2020-03-27 06:52 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/layout-cn/#header](https://ant.design/components/layout-cn/#header)

### Steps to reproduce
import React, { PureComponent, Fragment } from 'react';
import { Layout, Tree,} from 'antd';

const { Sider } = Layout;
const { DirectoryTree } = Tree;

class Test extends PureComponent {
state = {
treeData: [
{ title: 'Expand to loadExpand to loadExpand to load', key: '0' },
{ title: 'Expand to loadExpand to loadExpand to loadExpand to loadExpand to loadExpand to load', key: '1' },
{ title: 'Tree Node', key: '2', isLeaf: true },
],
};

render() {
const {treeData} = this.state;
return (

<Layout style={{ height: '800px', width: '100%' }}>
<Sider theme="light" width="10%" style={{ overflowY: 'auto' }}>
);
}
}

export default Test;

步骤: 选择超出width范围的树节点，移动x轴滚动条，超出范围的title 看不到了

### What is expected?
树节点的title 应该全部选中

### What is actually happening?
click 时候只选择到了 范围内的title

| Environment | Info |
|---|---|
| antd | 3.19.0 |
| React | 16.11.0 |
| System | window 10  |
| Browser | 谷歌 70.0.3538.67 |

---
 使用Tree 是没有问题的 用 DirectoryTree 有这种问题

**Comment by afc163** [comment] 2020-03-27 07:45
Duplicate of #22005

**Closed by afc163** 2020-03-27 07:45 UTC
