### ISSUE TITLE
table中打开勾选功能，数据超过300条就会导致整体页面操作卡顿。

### ISSUE THREAD

**Issue by QzAmoy** [ant-design/ant-design#10548] opened 2018-05-17 06:22 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
macos 10.13.5；2.5 GHz Intel Core i7；16 GB 1600 MHz DDR3；react16.3.2；Chrome66.0.3359.181

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w0w6k76yw5)

### Steps to reproduce
将连接中的模拟数据改为300或以上；分页改为300；然后点击勾选；

### What is expected?
快速响应勾选；整体页面不卡顿；

### What is actually happening?
勾选响应慢；页面其他操作同样卡顿；

**Comment by afc163** [comment] 2018-05-17 06:40
Duplicate of #10431

**Closed by afc163** 2018-05-17 06:40 UTC
