### ISSUE TITLE
form表单校验url会卡死页面

### ISSUE THREAD

**Issue by wangyingjie123** [ant-design/ant-design#34531] opened 2022-03-16 03:56 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/#components-form-demo-warning-only](https://ant.design/components/form-cn/#components-form-demo-warning-only)

### Steps to reproduce
输入一个url地址，比如https://xxx.cos.ap-nanjing.myqcloud.com，然后从后面逐个删除，到o的时候页面卡死

### What is expected?
正常删除，不卡死页面

### What is actually happening?
然后从后面逐个删除，到o的时候页面卡死

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | 17.0.2 |
| System | chrome |
| Browser | 98 |

**Comment by afc163** [comment] 2022-03-16 04:00
Duplicate of #28286

**Closed by afc163** 2022-03-16 04:00 UTC
