### ISSUE TITLE
RangePicker doesn't let me select any values after production build with parcel

### ISSUE THREAD

**Issue by websours** [ant-design/ant-design#28355] opened 2020-12-14 17:15 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/websours/antd-rangePicker](https://github.com/websours/antd-rangePicker)

### Steps to reproduce
1. Clone the repository
2. Run: **npm install**
3. Run: **npm run build**
4. Run: **npm install --global http-server**
5. Run: **http-server dist/index.html**

### What is expected?
The Range TimePicker works ok in development mode. But as soon I build the project using parcel and run production build, it's not working. It should work both in development and production mode.

### What is actually happening?
The Range TimePicker works ok in development mode when I run it using the command: **npm run dev**. But when I build the project using a parcel and run it, then it's not letting me select any time. And if I build the project with **--no-minify** command using parcel, then the picker works fine.

| Environment | Info |
|---|---|
| antd | 4.9.3 |
| React | 16.14.0 |
| System | Windows 10 |
| Browser | Chrome |

---
Please resolve it as soon as possible. I got stuck in my project. Btw, thanks for this amazing library.

**Comment by afc163** [comment] 2020-12-15 02:36
Duplicate of #24045

**Comment by afc163** [comment] 2020-12-15 02:37
https://github.com/parcel-bundler/parcel/issues/3523

**Closed by afc163** 2020-12-15 02:36 UTC
