### ISSUE TITLE
have not prefix props for textarea ?

### ISSUE THREAD

**Issue by uguraktas** [ant-design/ant-design#11606] opened 2018-08-04 09:38 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.3

### Environment
reactjs

### Reproduction link
[https://u.ant.design/codesandbox-repro](https://u.ant.design/codesandbox-repro)

### What is expected?
I want to use textarea with icon, input for work but textarea does not have this

### What is actually happening?
<a href="https://ibb.co/mKCO1K"><img src="https://preview.ibb.co/kncqgK/Ekran_Al_nt_s.jpg" alt="Ekran_Al_nt_s" border="0"></a>

**Comment by afc163** [comment] 2018-08-04 12:53
Duplicate of #10249

**Closed by afc163** 2018-08-04 12:53 UTC
