### ISSUE TITLE
Table 组件中的 footer能否设置列对齐

### ISSUE THREAD

**Issue by junhui75165** [ant-design/ant-design#13577] opened 2018-12-12 04:10 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在表格中进行数据统计时，时常需要对表格内数据进行统计求和，但是作为footer只能设置返回ReactNode，需要查询具体每一行的宽度，然后依次去布局，这样很麻烦

### What does the proposed API look like?
footer = function|Object
Object = {key : String|ReactNode}
直接配置对应列的key，在表格中显示对应的内容

**Comment by afc163** [comment] 2018-12-12 04:12
Duplicate of #5710

**Closed by afc163** 2018-12-12 04:12 UTC
