### ISSUE TITLE
components-table-demo-virtual-list 丢失 选择功能？

### ISSUE THREAD

**Issue by tuxming** [ant-design/ant-design#31064] opened 2021-06-21 03:27 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[ https://ant.design/components/table-cn/#components-table-demo-virtual-list ]( https://ant.design/components/table-cn/#components-table-demo-virtual-list )

### Steps to reproduce
按照实例代码，封装好了以后使用，发现每一行前面的选择框都丢失了，难道这个虚拟table只能用来看么？ 

### What is expected?
能帮我说说具体的原因，那怕我自己手动封装也成！

### What is actually happening?
每一行前面的选择框都丢失了

| Environment | Info |
|---|---|
| antd | 4.16.1 |
| React | ^17.0.2 |
| System | window 10 |
| Browser | chrome  |

**Comment by zombieJ** [comment] 2021-06-22 03:00
Duplicate of #20339

**Closed by zombieJ** 2021-06-22 03:00 UTC
