### ISSUE TITLE
Tabled 的Column的 fixed 属性 与 Badge 组件使用，有问题。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#20750] opened 2020-01-08 03:31 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/table-fix-he-badge-de-wenti-xlxov)

### Steps to reproduce
根据我发的连接，当fixed 的时候，网左边拖动，会发现badge会覆盖到左边固定的区域。

### What is expected?
badge 组件应该在 fixed 列的下面

### What is actually happening?
badge 组件应该在 fixed 列的上面

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | latest |
| System | windows 10  |
| Browser | chrome  78.0.3904.108 |

**Comment by afc163** [comment] 2020-01-08 03:38
Fixed in #13930 but caused by #15782 again.

**Comment by xgj1988** [comment] 2020-01-08 04:10
'zindex-badge':'auto'

**Closed** 2020-01-08 04:09 UTC
Labels: 🐛 Bug
