### ISSUE TITLE
Ant Button conflict with TailwindCSS 

### ISSUE THREAD

**Issue by phatify** [ant-design/ant-design#39036] opened 2022-11-27 13:37 UTC
### Reproduction link

[https://stackblitz.com/edit/nextjs-26lbuu?file=pages/index.js](https://stackblitz.com/edit/nextjs-26lbuu?file=pages/index.js)

### Steps to reproduce

add tailwindcss and ant design works together and then add `<Button type="primary">Click me</Button>` and now you can see the Button broken!

### What is expected?

Button should worked perfectly together with TailwindCSS. Please don't recommend to me disable preflight in Tailwind CSS, because It really necessary for me 

### What is actually happening?

Button component broken when adding TailwindCSS

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | React lastest version |
| System | Windows 10 |
| Browser | Chrome lastest version |

**Comment by afc163** [comment] 2022-11-27 14:30
Duplicate of #38794

**Closed by afc163** 2022-11-27 14:30 UTC
