### ISSUE TITLE
Cascader多选时，value值选中的只有最后一个

### ISSUE THREAD

**Issue by yumengjuan1** [ant-design/ant-design#33778] opened 2022-01-20 03:36 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/meeenenengeng/pen/OJxYwMj?editors=001](https://codepen.io/meeenenengeng/pen/OJxYwMj?editors=001)

### Steps to reproduce
 <Cascader
                            style={{ width: 250 }}
                            placeholder="请选择"
                            options={[
                              { label: '西安001', value: 'OU=西安001', children: null },
                              { label: '杭州测试部', value: 'OU=杭州测试部', children: null },
                              { label: '西安002', value: 'OU=西安002', children: null },
                              { label: '杨戈部门', value: 'OU=杨戈部门', children: null },
                            ]}
                            onChange={values => changeCascaderSelect(values, indexs)}
                            value={['OU=西安001', 'OU=杭州测试部']}
                            multiple
                            maxTagCount="responsive"
                          />

### What is expected?
可以正常回填 选中数据

### What is actually happening?
没有回填数据

| Environment | Info |
|---|---|
| antd | 4.18.4 |
| React | 16.8.6 |
| System | mac |
| Browser |  Chrome 96.0.4664.110 |

**Comment by afc163** [comment] 2022-01-20 06:01
Duplicate of #33683

**Closed by afc163** 2022-01-20 06:01 UTC

**Comment by yumengjuan1** [comment] 2022-01-20 07:07
值给多个后，只会展示以及选中最后一个
![image](https://user-images.githubusercontent.com/98071534/150290078-0a536281-cc9e-4f91-a710-3b2be76e6538.png)
