### ISSUE TITLE
Custom render Upload picture-card(Upload自定义渲染图片)

### ISSUE THREAD

**Issue by zhshch9527** [ant-design/ant-design#23787] opened 2020-04-30 11:37 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
For example, I need to add a description below each picture, or operating tools, etc.
![SKS8QCQP{NMLM{KL(H`2W(K](https://user-images.githubusercontent.com/42881276/80705940-fd663a80-8b19-11ea-8c11-105800ef0665.png)

### What does the proposed API look like?

````jsx
pictureRender:(pictureDom,{index,file,fileList})=>{
  return (
    <div>
      <MyExtraHeader/>
      {pictureDom}
      <MyExtraFooter/>
    </div>
  )   
}
or for all types
itemRender:(dom,{index,file,fileList})=>{
  return (
    <div>
      <MyExtraHeader/>
      {dom}
      <MyExtraFooter/>
    </div>
  )   
}
````

**Comment by zhshch9527** [comment] 2020-04-30 11:38
![~{FT_R@44}IXHZ P HV{9FN](https://user-images.githubusercontent.com/42881276/80706008-2090ea00-8b1a-11ea-91d7-03387a259fd6.png)

**Comment by afc163** [comment] 2020-04-30 11:48
Duplicate of #16047

**Closed by afc163** 2020-04-30 11:48 UTC
