### ISSUE TITLE
Calendar Mode: need to add weekly mode like full calendar

### ISSUE THREAD

**Issue by mmejaz** [ant-design/ant-design#41127] opened 2023-03-08 14:57 UTC
### What problem does this feature solve?

I am using Ant-d calendar and I need to show the weekly schedules with time slots like the "full calendar" but there is no option for showing weekly schedules. please add this feature.

### What does the proposed API look like?

I am using Ant-d calendar and I need to show the weekly schedules with time slots like the "full calendar" but there is no option for showing weekly schedules. please add this feature.

**Comment by Yuiai01** [comment] 2023-03-08 15:29
@mmejaz  Hello, Can you provide a link to a similar function?

**Comment by mmejaz** [comment] 2023-03-09 17:04
https://fullcalendar.io/demos
here is the link after opening the link please click on week then you will able to see the all-day time slot on the left side of the calendar. please guide me on how can I print time column in ant-d calendar

**Comment by Yuiai01** [comment] 2023-03-12 00:51
> https://fullcalendar.io/demos here is the link after opening the link please click on week then you will able to see the all-day time slot on the left side of the calendar. please guide me on how can I print time column in ant-d calendar

AntD `Calendar` mode only supports `month` and `year`, perhaps by adding `week`.

**Comment by mmejaz** [comment] 2023-03-13 11:46
I have checked Ant-d supports only two mod monthly and yearly, there is no option to support week

**Comment by afc163** [comment] 2023-03-19 08:30
Duplicate of #40051

**Closed by afc163** 2023-03-19 08:30 UTC
Labels: unconfirmed

**Comment by dogukankumru** [comment] 2024-08-01 13:15
I dont understand why this issue closed as Duplicate of #40051. Both issues definitely no similarity with each other. I am also having this issue for my project and needed to add week mode to my Calendar component

**Comment by katerina7479** [comment] 2024-12-16 20:29
Agreed, does not look like the same issue to me.
