### ISSUE TITLE
InputNumber 样式 width 有问题

### ISSUE THREAD

**Issue by xiaoshuangLi** [ant-design/ant-design#29030] opened 2021-01-25 10:06 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-number-cn/](https://ant.design/components/input-number-cn/)

### Steps to reproduce
打开  Chrome devtools, .ant-input-number 的样式看看，就可以找到 witdth: 90px

### What is expected?
width: 100%;

### What is actually happening?
width: 90px;

| Environment | Info |
|---|---|
| antd | 4.11.1 |
| React | 17.0.0 |
| System | MacOS |
| Browser | Chrome |

---
问题截图地址： https://cdn-health.zhongan.com/magiccube/resource/rl/WWXmjFVvMn.png

**Comment by xrkffgg** [comment] 2021-01-25 10:16
Duplicate of https://github.com/ant-design/ant-design/issues/27970

**Closed by xrkffgg** 2021-01-25 10:16 UTC
