### ISSUE TITLE
Select component virtual list search option bug——select组件虚拟列表搜索选项bug

### ISSUE THREAD

**Issue by thding** [ant-design/ant-design#21027] opened 2020-01-20 07:55 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/throbbing-hooks-5b3fx?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1.Enter 66 in the select component  2.Select test66 option  3.Select the select component again  4. An error occurs and the screen is blank 
  ——  1、在select组件输入66  2、选择test66选项  3、再次选择select组件  4、出现错误，白屏

### What is expected?
can work —— 正常工作

### What is actually happening?
error && blank screen —— 报错 && 白屏

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 16.12.0 |
| System | macOS Catalina 10.15.2 |
| Browser | Chrome |

---
The error is reported in the getNodeHeight method of the file node_modules/rc-virtual-list/es/utils/itemUtil.js. The parameter received by getNodeHeight is undefined. Currently, I temporarily return a null value after catching errors in the getNodeHeight method. Make components work temporarily —— 报错在文件node_modules/rc-virtual-list/es/utils/itemUtil.js的getNodeHeight方法中，getNodeHeight接收到的参数为undefined，目前我临时在getNodeHeight方法中捕获错误后返回null值。临时让组件可以工作

**Comment by zombieJ** [comment] 2020-01-20 08:21
Duplicate of #20874

**Closed by zombieJ** 2020-01-20 08:21 UTC
