### ISSUE TITLE
Range Picker not working  with es locale

### ISSUE THREAD

**Issue by AntonioNtV** [ant-design/ant-design#30763] opened 2021-05-28 18:31 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/strange-sun-ivbmq?file=/src/App.tsx)

### Steps to reproduce
1 - Click in Fecha Inicial or in Fecha Final
2- See the Error

### What is expected?
It's expected to open the date picker

### What is actually happening?
Type Error: clone is undefined

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | 16.13.1 |
| System | ubuntu 20.04 |
| Browser | firefox, chrome |

**Comment by afc163** [comment] 2021-05-29 15:54
Duplicate of #26699

**Closed by afc163** 2021-05-29 15:54 UTC

**Comment by AntonioNtV** [comment] 2021-06-02 11:57
`
import es from 'antd/es/date-picker/locale/es_ES';

es.lang.locale = 'es';
`
worked for me.
