### ISSUE TITLE
hope support row-group to table components

### ISSUE THREAD

**Issue by imic07** [ant-design/ant-design#21766] opened 2020-03-02 08:11 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
对数据进行简单快速的分组展示。类似easyui的row-group，参考easyui-vue 的 datagrid 中的row group

### What does the proposed API look like?
有如下列表数据：   [{id:1, username:张三, age:18, groupName:成都}, {id:2, username:张三2, age:18, groupName:成都}, {id:3, username:张三3, age:18, groupName:北京}]  
传递给table组件后，设置分组字段为groupName, 列表中自动按groupName分组展示
类似下图：
![image](https://user-images.githubusercontent.com/16321067/75657106-7410c400-5ca0-11ea-92e6-a0c515dd9f86.png)

**Comment by afc163** [comment] 2020-03-02 08:13
Duplicate of #15630

**Closed by afc163** 2020-03-02 08:13 UTC
