### ISSUE TITLE
table sticky 在容器内滚动无效/异常

### ISSUE THREAD

**Issue by lich-yoo** [ant-design/ant-design#26835] opened 2020-09-21 05:57 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hungry-matsumoto-0yjv9?file=/index.js)

### Steps to reproduce
table 设置 sticky，在modal 或 容器内滚动无法生效且 header 异常

正常时：
![image](https://user-images.githubusercontent.com/18572962/93741365-dc17ff00-fc1e-11ea-857b-84e0ea23eab8.png)
非预期：
![image](https://user-images.githubusercontent.com/18572962/93741493-1b465000-fc1f-11ea-921f-6190ac77e7dd.png)

### What is expected?
sticky 是否支持容器内滚动？

### What is actually happening?
容器内滚动不生效，header 异常。

~~ps: 极少见时候 modal 中也会看到 sticky 滚动条。但拖拽滑动后就会消失。~~
update: 只有第一次打开弹窗时，会显示横向滚动条，但是位置不对。后续打开还会消失。

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | lastest |
| System | win10 |
| Browser | chrome |

**Comment by shaodahong** [comment] 2020-09-21 08:33
Duplicate of https://github.com/ant-design/ant-design/issues/26399

**Closed by shaodahong** 2020-09-21 08:33 UTC
