### ISSUE TITLE
Keyboard backspace not working with DatePicker and date-fns

### ISSUE THREAD

**Issue by thomastvedt** [ant-design/ant-design#51255] opened 2024-10-15 10:28 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-4xvghz?file=%2Findex.tsx)

### Steps to reproduce

- Select a date in the DateFnsPicker
- Place cursor behind the year 2024
- Try to erase the digit "4"

### What is expected?

The input should work with keyboard also when using date-fns in stead of dayjs

### What is actually happening?

The year changes to 0202 and the cursor jumps to the end of the input

Here is a video illustrating the issue:

https://github.com/user-attachments/assets/4397bb3a-e0c6-4600-9c75-c38d0f70ff0b

| Environment | Info |
| --- | --- |
| antd | 5.21.4 |
| React | 18.0.0 |
| System | MacOS |
| Browser | Chrome 129.0.6668.91 |

**Comment by afc163** [comment] 2024-10-15 10:46
Duplicate of https://github.com/ant-design/ant-design/issues/47241

**Comment by thomastvedt** [comment] 2024-10-15 11:32
> Duplicate of #47241

You're right. Thanks for linking that issue, I was able to use the workaround. 
I also noticed this commit in rc-picker which might be related?: https://github.com/react-component/picker/commit/72ccd4b23c7f8976311d911ea7547327315de0f4

**Closed** 2024-10-15 11:33 UTC
Labels: unconfirmed
