### ISSUE TITLE
建议新增SegmentedControl组件

### ISSUE THREAD

**Issue by DreamPWJ** [ant-design/ant-design#33172] opened 2021-12-06 01:16 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决单选设计样式  更美观更好用

### What does the proposed API look like?
SegmentedControl组件

**Comment by DreamPWJ** [comment] 2021-12-06 01:17
![image](https://user-images.githubusercontent.com/16730031/144772525-f1808cb5-ae8e-42eb-a6be-d0390003181c.png)
类似y云效中的设计

**Comment by afc163** [comment] 2021-12-06 02:45
Duplicate of #31399

**Closed by afc163** 2021-12-06 02:45 UTC
