### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by jellohouse** [ant-design/ant-design#30199] opened 2021-04-18 17:56 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/latobibor/antd-tryout/commit/e373cb5038d88bf73358a05c8b37e0369dbaf478](https://github.com/latobibor/antd-tryout/commit/e373cb5038d88bf73358a05c8b37e0369dbaf478)

### Steps to reproduce

    install dependencies (npm i)
    run app (npm start)
    check console

### What is expected?
No warnings should be displayed.

### What is actually happening?
`Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DOMWrap which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node`

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17.1 |
| System | mac |
| Browser | electron |

---
A similar issue was closed previously here https://github.com/ant-design/ant-design/issues/22493

I'm getting this on the Slider component, but I see people are getting it with many other components such as Button, Modal, etc. 

This issue should not have been closed - the proposed solution is not nice.

Someone who is working on the repo must fix this.

**Comment by afc163** [comment] 2021-04-19 02:31
Duplicate of #26136

**Closed by afc163** 2021-04-19 02:31 UTC
