### ISSUE TITLE
Antd Affix: Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by mendoncanorma** [ant-design/ant-design#22697] opened 2020-03-28 11:16 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wonderful-shamir-tn0fu)

### Steps to reproduce
1. Scroll a little till the Affix becomes sticky.
2. Click on Toggle button.
3. First Affix is removed and second Affix gets mounted.
4. Warning seen on console - Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
5. Note: This is particularly observed in Chrome - Emulation Mode (Responsive Viewport Mode)

### What is expected?
Warning should not appear

### What is actually happening?
Can't perform a React state update on an unmounted component warning is seen

| Environment | Info |
|---|---|
| antd | 3.26.13 |
| React | 16.13.0 |
| System | Win 10 |
| Browser | Chrome 80 (Responsive Viewport Mode) |

**Comment by afc163** [comment] 2020-03-28 11:18
Duplicate of #22683

**Closed by afc163** 2020-03-28 11:18 UTC
