### ISSUE TITLE
antd表格组件嵌套表格 expandedRowRender 为什么出现多余空白列

### ISSUE THREAD

**Issue by qcxiaoshuai-snake** [ant-design/ant-design#37951] opened 2022-10-11 10:12 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-i0twwc)

### Steps to reproduce

import React from "react";
import { createRoot } from "react-dom/client";
import { DownOutlined } from '@ant-design/icons';
import { Badge, Dropdown, Menu, Space, Table } from 'antd';
import "antd/dist/antd.css";
import "./index.css";

const App = () => {
  const dataSource = [
    {
      key: '1',
      name: 'Screem',
      platform: 'iOS',
      version: '10.3.4.5654',
      upgradeNum: 500,
      creator: 'Jack',
      createdAt: '2014-12-24 23:12:00',
      children: [
        {
          key: '111',
          date: '2014-12-24 23:12:00',
          name: 'This is production name',
          upgradeNum: 'Upgraded: 56',
        },
        {
          key: '222',
          date: '2014-12-24 23:12:00',
          name: 'This is production name',
          upgradeNum: 'Upgraded: 56',
        }
      ],
    },
    {
      key: '2',
      name: 'Screem',
      platform: 'iOS',
      version: '10.3.4.5654',
      upgradeNum: 500,
      creator: 'Jack',
      createdAt: '2014-12-24 23:12:00',
      children: [
        {
          key: '333',
          date: '2014-12-24 23:12:00',
          name: 'This is production name',
          upgradeNum: 'Upgraded: 56',
        },
        {
          key: '444',
          date: '2014-12-24 23:12:00',
          name: 'This is production name',
          upgradeNum: 'Upgraded: 56',
        }
      ],
    }
  ]
  const expandedRowRender = (record) => {
    const columns = [
      { title: 'Date', dataIndex: 'date', key: 'date' },
      { title: 'Name', dataIndex: 'name', key: 'name' },
      {
        title: 'Status',
        key: 'state',
        render: () => (
          <span>
            <Badge status="success" />
            Finished
          </span>
        ),
      },
      { title: 'Upgrade Status', dataIndex: 'upgradeNum', key: 'upgradeNum' },
    ];

    
    return <Table rowKey={'key'} columns={columns} dataSource={record.children} pagination={false} />;
  };

  const columns = [
    { title: 'Name', dataIndex: 'name', key: 'name' },
    { title: 'Platform', dataIndex: 'platform', key: 'platform' },
    { title: 'Version', dataIndex: 'version', key: 'version' },
    { title: 'Upgraded', dataIndex: 'upgradeNum', key: 'upgradeNum' },
    { title: 'Creator', dataIndex: 'creator', key: 'creator' },
    { title: 'Date', dataIndex: 'createdAt', key: 'createdAt' },
    { title: 'Action', key: 'operation', render: () => <a>Publish</a> },
  ];

  return (
    <div className="App">
      <h1>antd version: 4.5.3 | 4.23.4</h1>
      <Table
        rowKey={'key'}
        columns={columns}
        expandable={{ expandedRowRender }}
        dataSource={dataSource}
      />
    </div>
  );
};

const root = createRoot(document.getElementById("root"));
root.render(<App />);

### What is expected?

无空白行

### What is actually happening?

有空白行

| Environment | Info |
| --- | --- |
| antd | 4.23.4 |
| React | 18 |
| System | mac |
| Browser | chrome |

---
解决方案：https://blog.csdn.net/qq_35909965/article/details/127267540?spm=1001.2014.3001.5502

**Comment by afc163** [comment] 2022-10-11 10:25
Duplicate of #37947

**Closed by afc163** 2022-10-11 10:25 UTC
