### ISSUE TITLE
含有内嵌菜单的Sider收缩时，Menu组件会闪动

### ISSUE THREAD

**Issue by lukelew** [ant-design/ant-design#38787] opened 2022-11-21 06:55 UTC
### Reproduction link

[https://ant.design/components/menu-cn#components-menu-demo-inline-collapsed](https://ant.design/components/menu-cn#components-menu-demo-inline-collapsed)

### Steps to reproduce

1. 展开二级菜单； 2.点击收缩Sider按钮；

### What is expected?

没有Menu的多余闪动画面

### What is actually happening?

Menu组件快速闪动后消失

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18.2 |
| System | MacOS 13 Ventura |
| Browser | Chrome v107.0.5304.110 |

**Comment by afc163** [comment] 2022-11-21 06:57
Duplicate of #36152

**Closed by afc163** 2022-11-21 06:57 UTC
