### ISSUE TITLE
Table组件中的columns加上fixed的话，如果columns标题换行了，fixed列会出现错位

### ISSUE THREAD

**Issue by dongkeng001** [ant-design/ant-design#18218] opened 2019-08-12 07:14 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### What is expected?
正常

### What is actually happening?
不正常

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | react |
| System | windows |
| Browser | 谷歌等其它浏览器 |

**Comment by dongkeng001** [comment] 2019-08-12 07:18
![image](https://user-images.githubusercontent.com/20589684/62850042-5421af00-bd14-11e9-88c5-e62ad1f24d7e.png)

**Comment by dongkeng001** [comment] 2019-08-12 07:19
如果标题出现换行了，右边固定的两列就错位了

**Comment by afc163** [comment] 2019-08-13 03:47
Duplicate of #14859

**Closed by afc163** 2019-08-13 03:47 UTC
Labels: 🤔 Need Reproduce
