### ISSUE TITLE
Sider breakpoint 与 Menu demo 存在不兼容

### ISSUE THREAD

**Issue by iugo** [ant-design/ant-design#26753] opened 2020-09-15 10:04 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-nmg5ag?file=index.js](https://stackblitz.com/edit/react-nmg5ag?file=index.js)

### Steps to reproduce
1. 将窗口变窄, 刷新页面.
2. 点击展开菜单.
4. 查看菜单分类是否默认被打开.

or

1. 宽窗口打开.
2. 确保某菜单分类已经打开.
3. 将窗口变窄.
4. 查看刚才的菜单分类是否原来的样子.

### What is expected?
菜单分类不受是否缩回影响.

### What is actually happening?
已打开的菜单分类在布局缩回时也自动缩回.

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.13.1 |
| System | macOS |
| Browser | Chrome |

---
https://ant.design/components/menu-cn/#components-menu-demo-sider-current

**Comment by afc163** [comment] 2020-09-17 06:42
Duplicate of #24967

**Closed by afc163** 2020-09-17 06:42 UTC
