### ISSUE TITLE
antd 3.x版本 Carousel 组件导致内存溢出

### ISSUE THREAD

**Issue by yzz3730781** [ant-design/ant-design#27993] opened 2020-11-25 02:01 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/yzz3730781/antd_issued_carousel/tree/master](https://github.com/yzz3730781/antd_issued_carousel/tree/master)

### Steps to reproduce
在多个router页面引入  Carousel  ，路由页面起个定时器，定时切换 发现浏览器内存一直在上涨  我把这个注释了 内存不增

### What is expected?
多个页面使用carousel 浏览器内存不停地上涨

### What is actually happening?
内存一直在上涨 页面定时45秒切换一次 24小时左右浏览就崩了

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | react16.6.3 |
| System | win10 |
| Browser | chrome |

---
github链接中页面只引入单个carousel组件 6个页面来回定时切换  500ms切一次 明显看到内存上涨 挂着一晚上 早上来内存就涨到2600M

**Comment by afc163** [comment] 2020-11-25 02:49
Duplicate of https://github.com/ant-design/ant-design/issues/15062

**Closed by afc163** 2020-11-25 02:49 UTC
