### ISSUE TITLE
Select dropdown options disappear after drag and drop

### ISSUE THREAD

**Issue by nenadbarjak** [ant-design/ant-design#38269] opened 2022-10-28 11:16 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-2tk521?file=/index.js)

### Steps to reproduce

- Drag an item (A-F) from the left sidebar and drop it in the middle section
- Open Select dropdown above

### What is expected?

To see all dropdown items and be able to select them.

### What is actually happening?

If you open the Select dropdown after droping a dragging item, the options items are not shown.

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18.2.0 |
| System | Ubuntu 20.04.5 LTS |
| Browser | 106.0.5249.119 (Official Build) (64-bit) |

---
This does not happen in Firefox. Happens in Chrome and Edge (I'm not sure about Safari). Also happens in older versions of antd and older versions of React.

**Comment by afc163** [comment] 2022-10-28 11:32
Duplicate of #38152

**Closed by afc163** 2022-10-28 11:32 UTC
