### ISSUE TITLE
ColumnProps dataIndex property would be more accurately typed as (keyof T) in TypeScript

### ISSUE THREAD

**Issue by jakelauer** [ant-design/ant-design#10268] opened 2018-04-26 18:28 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
N/A

### Reproduction link
[http://not-relevant-to-this.report](http://not-relevant-to-this.report)

### Steps to reproduce
- Use TypeScript
- Create columns using ColumnProps
- Specify a string in dataIndex that is not present in the data

### What is expected?
dataIndex should not let you use a key that is not present in the data you are using. If there is a scenario when you want to use a string that is not valid in keyof T, you can just cast it to "any".

### What is actually happening?
You can use any string in dataIndex

**Comment by yesmeck** [comment] 2018-04-28 07:31
Duplicate of #9856

**Closed by yesmeck** 2018-04-28 07:31 UTC
Labels: TypeScript, help wanted
