### ISSUE TITLE
List with Checkbox and Pagination

### ISSUE THREAD

**Issue by joshuagautham** [ant-design/ant-design#10125] opened 2018-04-17 11:23 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
List component to have checkboxes and pagination similar to tables. This will be a highly scalable component.

### What does the proposed API look like?
Didn't Find anything suitable

**Comment by afc163** [comment] 2018-04-17 16:14
Duplicate of #9303

**Closed by afc163** 2018-04-17 16:14 UTC
Labels: Component: List
