### ISSUE TITLE
可以夸天标记吗

### ISSUE THREAD

**Issue by githubcheng2978** [ant-design/ant-design#44260] opened 2023-08-17 05:39 UTC
### What problem does this feature solve?

Calendar 可以夸天标记吗

### What does the proposed API look like?

Calendar 可以夸天标记吗

<img width="370" alt="image" src="https://github.com/ant-design/ant-design/assets/22095448/5674a413-8c04-44b8-95c0-23dd42373398">

**Comment by afc163** [comment] 2023-08-17 05:40
Duplicate of #12591

**Closed by afc163** 2023-08-17 05:40 UTC
Labels: unconfirmed
