### ISSUE TITLE
DatePicker 范围选择器能否适配移动端

### ISSUE THREAD

**Issue by amin168** [ant-design/ant-design#45187] opened 2023-10-06 03:28 UTC
### What problem does this feature solve?

DatePicker 范围选择器能否适配移动端，现在官网在移动端的样式也是错乱

![image](https://github.com/ant-design/ant-design/assets/10808093/37a3be27-ffd3-41e4-89a6-2fd96b2e2650)

### What does the proposed API look like?

DatePicker 范围选择器适配移动端

**Comment by afc163** [comment] 2023-10-07 04:04
Duplicate of #26758

**Closed by afc163** 2023-10-07 04:04 UTC
Labels: 📱Mobile Device, unconfirmed
