### ISSUE TITLE
在from表单中使用filterOption函数来搜索，获取不到label的值，只能获取到value的值

### ISSUE THREAD

**Issue by burning110-lab** [ant-design/ant-design#28379] opened 2020-12-16 05:58 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/select-cn/ （第二个案例）](https://ant-design.gitee.io/components/select-cn/ （第二个案例）)

### Steps to reproduce
直接搜索，然后打印option的值，option对象包含了value、label、key的值，唯独获取不到label的值undefined

### What is expected?
filterOption={(input,option) => option?.value.includes(input)} 期望给的这个option的值能获取到label的值

### What is actually happening?
获取到label的值为undefined

| Environment | Info |
|---|---|
| antd | 4.9.3 |
| React | 16 |
| System | Mac |
| Browser | chorm最新版本 |

---
我的业务就是搜索时候能够根据value和label都能搜索到，由于只能拿到value的值，我没办法获取到label的值.

**Comment by afc163** [comment] 2020-12-16 06:24
Duplicate of #28285

**Closed by afc163** 2020-12-16 06:24 UTC
