### ISSUE TITLE
ant desgin 官网 全局搜索功能在内容为空的情况下按上下方向键的时候会导致报错白屏

### ISSUE THREAD

**Issue by shimengwen** [ant-design/ant-design#31317] opened 2021-07-08 09:15 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce
1. 进入官网，按下command   k 唤起搜索功能
2. 在不输入任何内容的情况下按下上下方向键盘（任意）

### What is expected?
无反应

### What is actually happening?
白屏

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | react |
| System | mac os 11.4 |
| Browser | chrome 91.0.4472.114 |

**Comment by afc163** [comment] 2021-07-08 09:53
Duplicate of #31040

**Closed by afc163** 2021-07-08 09:53 UTC
