### ISSUE TITLE
v4 表单组件中，使用 shouldUpdate 根据值来渲染额外字段时，卸载组件后，编辑的字段仍然存在

### ISSUE THREAD

**Issue by theprimone** [ant-design/ant-design#21369] opened 2020-02-13 10:02 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/form-cn/#components-form-demo-control-hooks](https://next.ant.design/components/form-cn/#components-form-demo-control-hooks)

### Steps to reproduce
1. 先选择 gender 字段为 other 后，编辑表单再提交打印到控制台
2. 选择其他 gender 后， 再提交时， customizeGender 字段值仍为上次输入的值

### What is expected?
卸载组件后，相应的字段同步删除

### What is actually happening?
新增字段值未删除

| Environment | Info |
|---|---|
| antd | ^4.0.0-rc.4 |
| React | ^16.8.6 |
| System | Windows 10 |
| Browser | Chrome 80.0.3987.100 |

**Comment by zombieJ** [comment] 2020-02-17 06:41
Duplicate of #21320

**Closed by zombieJ** 2020-02-17 06:41 UTC
