### ISSUE TITLE
Datepicker is not working in all locales when using date-fns

### ISSUE THREAD

**Issue by semdejong** [ant-design/ant-design#35575] opened 2022-05-16 09:59 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elated-bird-zgfoh9?file=/src/App.js)

### Steps to reproduce

Issues occurs when trying to open the date picker (by clicking it).

### What is expected?

The date picker should open just fine, using the right locale, and show no errors.

### What is actually happening?

The date picker using date-fns tries to call a function. This function has a locale parameter. Right now the locale is in this format (ex. nl_NL, de_DE, fr_FR), this is fine with momentJS, but not accepted by date-fns. Therefor the datepicker crashes and shows an error.

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | all |
| System | all |
| Browser | all |

---
Possible todo:
- the function getShortMonths, getWeekFirstDay and getShortWeekDays in the dateFnsConfig should fall back to the first two characters when the full locale is not found. For example nl_NL becomes nl.
- If no locale is found fall back to the default locale.

**Comment by afc163** [comment] 2022-05-16 11:55
Duplicate of #26699

**Closed by afc163** 2022-05-16 11:55 UTC
