### ISSUE TITLE
Fixed (pin, sticky) tab

### ISSUE THREAD

**Issue by urrri** [ant-design/ant-design#25763] opened 2020-07-22 15:22 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
User can have some tabs always visible and immediately available (UX)
In our app we have 2-3 main static tabs on page that must be always available and some dynamic, closable, that can overflow the bar. 

### What does the proposed API look like?
To the TabPane add boolean prop, named 'fixed' (or 'sticky' or 'pin') like for the table column.

**Comment by afc163** [comment] 2020-07-22 15:43
Duplicate of #18782

**Closed by afc163** 2020-07-22 15:43 UTC
