### ISSUE TITLE
flex - the table of the grid of the scroll bar under ie11 and ege browser does not support the mouse wheel

### ISSUE THREAD

**Issue by shadow-Fiend** [ant-design/ant-design#5194] opened 2017-03-07 03:29 UTC
As long as the mouse wheel rolling will report error.
![1488857678 1](https://cloud.githubusercontent.com/assets/24544648/23640699/431362ae-032a-11e7-8657-0c25f21c60bc.png)
![1488857759 1](https://cloud.githubusercontent.com/assets/24544648/23640698/430f2478-032a-11e7-9e11-78889f978be6.png)
Hope the great god help to solve this problem, thank you!

**Comment by benjycui** [comment] 2017-03-07 05:57
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment] 2017-03-09 13:53
Have you import es6-shim or babel-polyfill?

**Comment by afc163** [comment] 2017-03-15 09:16
closing for cannot reproduce.

**Closed by afc163** 2017-03-15 09:16 UTC
