### ISSUE TITLE
Virtual table and row selection

### ISSUE THREAD

**Issue by keshikashviligio** [ant-design/ant-design#23525] opened 2020-04-23 09:09 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have a long list and I use this example code: https://ant.design/components/table/#components-table-demo-virtual-list, it's ok but I need row selection there and how can I achieve rowSelection functionality with react-window, Is it possible with virtual list?
 

### What does the proposed API look like?
--

**Comment by afc163** [comment] 2020-04-23 09:12
Duplicate of #20339

#23057

**Closed by afc163** 2020-04-23 09:12 UTC

**Comment by leventebg93** [comment] 2022-09-28 06:29
@keshikashviligio 
Did you find the solution to this? Ive cheched the related comment from afc163, its everything but clear
