### ISSUE TITLE
Using @font-face with Chinese Quote and preferring it as primary font causes problem for non-Chinese languages in IE-11

### ISSUE THREAD

**Issue by mkaman** [ant-design/ant-design#13765] opened 2018-12-21 07:07 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
win7 - ie11 react-16.4.0

### Reproduction link
[https://jsfiddle.net/a73ekh6z/9/embedded/result,css,html,js](https://jsfiddle.net/a73ekh6z/9/embedded/result,css,html,js)

### Steps to reproduce
It can be reproduced on jsfiddle which can be opened for read only mode in IE - 11. A very basic use case is provided in reproduction link.

### What is expected?
Right font should be rendered for non-Chinese languages in IE-11

### What is actually happening?
Wrong-unintented font family is being rendered

---
Chrome > 69.0 and Firefox have no this problem.

I'll appreciate if there is a work-around.

**Comment by afc163** [comment] 2018-12-21 07:37
Duplicate of #13095

**Closed by afc163** 2018-12-21 07:37 UTC
