### ISSUE TITLE
Floating labels for Input component (like in Material UI)

### ISSUE THREAD

**Issue by derblitz** [ant-design/ant-design#16487] opened 2019-05-08 17:25 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The problem solved is that you can still read the label of the text field when there is actual text entered - without taking as much space as normal labels currently available in ant design.

This is how it is solved in material ui:
https://material-ui.com/demos/text-fields/

### What does the proposed API look like?
That needs to be discussed but I suggest in the simplest form a property of the Input component that lets you define the input component type for floating labels.

**Comment by afc163** [comment] 2019-05-09 02:50
Duplicate of #16323

**Closed by afc163** 2019-05-09 02:50 UTC
