### ISSUE TITLE
Use context to separate the `Tabs` and the `Tabs.TabPane`

### ISSUE THREAD

**Issue by cangSDARM** [ant-design/ant-design#35574] opened 2022-05-16 09:54 UTC
### What problem does this feature solve?

currently, we cannot use something like this:

```tsx
<Tabs defaultActiveKey="1" onChange={callback}>
   <div>
     <TabPane tab="Tab 1" key="1">
      Content of Tab Pane 1
    </TabPane>
    <TabPane tab="Tab 2" key="2">
      Content of Tab Pane 2
    </TabPane>
    <TabPane tab="Tab 3" key="3">
      Content of Tab Pane 3
    </TabPane>
   </div>
</Tabs>
```

At this point nothing is rendered.

If we use context, we can dynamically look up the nearest Tabs, and then use it, instead of requiring `Tabs` to be the parent component and `Tabs.TabPane` to be the child component.

It is more flexible to use.

### What does the proposed API look like?

```tsx
<Tabs defaultActiveKey="1" onChange={callback}>
   <div>
     <TabPane tab="Tab 1" key="1">
      Content of Tab Pane 1
    </TabPane>
    <TabPane tab="Tab 2" key="2">
      Content of Tab Pane 2
    </TabPane>
    <TabPane tab="Tab 3" key="3">
      Content of Tab Pane 3
    </TabPane>
   </div>
</Tabs>
```

At the very least, this code should render properly. like the style in the document:

![image](https://user-images.githubusercontent.com/20441896/168567119-771e892c-934a-4d86-8c4b-a82698dec910.png)

**Comment by cangSDARM** [comment] 2022-05-16 09:56
context is not the only option. Separating these two components is a requirement of this issue.

or optional: force a tabsList option in tabs

**Comment by zombieJ** [comment] 2022-05-16 10:05
> context is not the only option. Separating these two components is a requirement of this issue.
> 
> or optional: force a tabsList prop in Tabs

Yes. props is what we want. For Menu we've already warning user to move to `items` instead. Syntactic sugar may be less and less.

**Comment by afc163** [comment] 2022-05-16 12:59
Duplicate of https://github.com/ant-design/ant-design/issues/4853

**Closed by afc163** 2022-05-16 12:59 UTC
