### ISSUE TITLE
For component Pagination, when the showQuickJumper is true, the page number of the jump can be custom modified?

### ISSUE THREAD

**Issue by sosout** [ant-design/ant-design#6958] opened 2017-07-26 02:50 UTC
### What problem does this feature solve?
For component Pagination, when the showQuickJumper is true, the page number of the jump can be custom modified。For example, I input decimal numbers, such as 2.4... I expect to display 2 or 3, or enter less than 1, and I expect to display 1

### What does the proposed API look like?
I would like to have the QuickJumper custom function to customize the page number of the display input

**Comment by afc163** [comment] 2017-07-27 04:19
Duplicate of #6970

**Closed by afc163** 2017-07-27 04:19 UTC

**Comment by afc163** [comment] 2017-07-27 04:20
https://github.com/ant-design/ant-design/issues/6970#issuecomment-318039942
