### ISSUE TITLE
Form.Item incompatible typescript signature v4

### ISSUE THREAD

**Issue by sitepodmatt** [ant-design/ant-design#21079] opened 2020-01-22 12:23 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
Signature of Form.Item returns ReactNode, this is incompatible when used in a Functional component.  Current workaround:

const FormItem = Form.Item as unknown as (props : FormItemProps) => ReactElement | null;

### What is expected?
Unification of ReactNode and (ReactElement | null)

### What is actually happening?
Typescript fails to  build form if taking the functional route

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.2 |
| React | 16.12.0 |
| System | Linux |
| Browser | Chrome |

**Comment by zombieJ** [comment] 2020-01-22 12:28
Duplicate of #21075

**Closed by zombieJ** 2020-01-22 12:28 UTC
