### ISSUE TITLE
form组件通过 onFieldsChange 和 fields把表单的数据存储到上层组件时，onFieldsChange 没有返回error信息

### ISSUE THREAD

**Issue by jclegendary** [ant-design/ant-design#22633] opened 2020-03-26 08:13 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-vkmcvc](https://stackblitz.com/edit/react-vkmcvc)

### Steps to reproduce
删除username的内容

### What is expected?
删除username的内容，没有出现必填提示

### What is actually happening?
删除username的内容，应该出现必填提示

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | react16 |
| System | windwo |
| Browser | chrome |

**Comment by zombieJ** [comment] 2020-03-26 12:52
Duplicate of #21922

**Closed by zombieJ** 2020-03-26 12:52 UTC
