### ISSUE TITLE
TreeSelect存在性能问题

### ISSUE THREAD

**Issue by Monsooon** [ant-design/ant-design#13266] opened 2018-11-23 09:20 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.8

### Environment
Mac OS Mojave 10.14/Google Chrome 70/React 16.2

### Reproduction link
[https://github.com/Monsooon/react-demo](https://github.com/Monsooon/react-demo)

### Steps to reproduce
当子节点数过大（超过10000）时，CPU会被占用用来进行虚拟DOM的构建与更新，占用时间很长，block用户的其他操作。

### What is expected?
期望可以实现TreeNode层级逐步构建如渲染，不如指构建和渲染展开的节点。

### What is actually happening?
一次性全部渲染，并且每次组件更新都会产生很严重的CPU占用。

**Comment by ztplz** [comment] 2018-11-23 13:20
#3789  You can get some information from this issue.

**Comment by zombieJ** [comment] 2018-11-27 02:44
duplicate of #13041

**Closed by zombieJ** 2018-11-27 02:44 UTC

**Comment by tqma113** [comment] 2019-09-24 06:42
谢谢
