### ISSUE TITLE
Table component - cells render on mouseOver

### ISSUE THREAD

**Issue by ericpierlot** [ant-design/ant-design#33637] opened 2022-01-09 21:02 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-im4vh?file=/index.js)

### Steps to reproduce
Mouse over a Row of the Table.

### What is expected?
Nothing re-render

### What is actually happening?
The column "Date" make the Date.now() render everytime we hover the row.

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | React 17.0.2 |
| System | Windows |
| Browser | Google Chrome 96 |

---

**Comment by afc163** [comment] 2022-01-10 02:14
Duplicate of #32979

**Closed by afc163** 2022-01-10 02:14 UTC
