### ISSUE TITLE
Export Table as CSV

### ISSUE THREAD

**Issue by sureshhustle** [ant-design/ant-design#6941] opened 2017-07-24 16:02 UTC
### What problem does this feature solve?
Is there any ways to export antd tables as csv files.., Please help me

### What does the proposed API look like?
I am new for this requirement please help me to create Export CSV from Antd Table

**Comment by zachguo** [comment] 2017-07-24 17:44
We easily handle this without using antd. Put CSV generation logics in the component wrapping your `Table`, and put an `Export CSV` in table footer or any other place you want.

**Comment by yesmeck** [comment] 2017-07-24 23:54
Duplicate of #1977

**Closed by yesmeck** 2017-07-24 23:54 UTC

**Comment by LucasBSC** [comment] 2019-04-05 16:40
Does anyone have a working english example for this?

**Comment by ztplz** [comment] 2019-04-05 16:59
@LucasBSC  Sorry, there are no examples at present as we don’t think it’s what `Antd` should do. It is beyond the scope of the `Antd`. Perhaps you can do it by the way that @zachguo said.

**Comment by LucasBSC** [comment] 2019-04-06 00:21
@zachguo Could you point the way more specifically when you say to wrap the `Table` with CSV generation logics? Is there any lib or component usually used for it?

**Comment by zachguo** [comment] 2019-04-06 01:57
In the component that renders a Table, you need to pass data into the
dataSource prop, right? Then you only need to add a method to convert the
data into a CSV then download it.

**Comment by monkeysuffrage** [comment] 2019-05-14 02:23
I feel like there needs to be a way to access the filtered and sorted data.
Otherwise there's really no way to implement csv export properly.

**Comment by LucasBSC** [comment] 2019-05-31 02:53
@monkeysuffrage

There is actually a way to capture the filtered/sorted data through `onChange` prop on `Table />` component

**Comment by NickDubelman** [comment] 2019-12-13 19:44
@LucasBSC But you are still left manually duplicating the filtering/sorting logic, which is ugly. It means you are performing all of the same filtering/sorting logic already implemented within the table and if you want to make changes you need to make sure you make them in 2 places.

**Comment by luisgustavomob** [comment] 2020-03-18 18:54
> ~@LucasBSC But you are still left manually duplicating the filtering/sorting logic, which is ugly. It means you are performing all of the same filtering/sorting logic already implemented within the table and if you want to make changes you need to make sure you make them in 2 places.~
> 
> I ended up writing some boilerplate like this, which may or may not be useful to others:
> 
> ```ts
> // This function can be used with antd's Table component and will perform the
> // necessary sorting and filtering logic on the records, given the value of columns.
> // It is useful when you want to create a CSV with data that mirrors data in an antd
> // table
> export function filterAndSortTableData<R>(records: R[], columns: ColumnProps<R>[]) {
>   return records
>     .filter(record => {
>       for (let col of columns) {
>         const { filteredValue, onFilter } = col
>         if (onFilter && filteredValue && filteredValue.length > 0) {
>           if (filteredValue.filter(val => onFilter(val, record)).length === 0)
>             return false
>         }
>       }
>       return true
>     })
>     .sort((a, b) => {
>       const sort = (col: ColumnProps<R>) => {
>         const { sorter, sortOrder } = col
>         if (sorter && sorter instanceof Function && !isBool(sortOrder)) {
>           return sorter(a, b, sortOrder)
>         }
>         return 0
>       }
> 
>       const sortColumn = columns.find(c => !!c.sortOrder)
>       if (sortColumn) return sort(sortColumn)
> 
>       const defaultSortColumn = columns.find(c => !!c.defaultSortOrder)
>       if (defaultSortColumn) return sort(defaultSortColumn)
> 
>       return 0
>     })
> }
> 
> function isBool(x: any): x is boolean {
>   return typeof x === 'boolean'
> }
> ```

Nice!

I've added a simple thing that adds support to export data exactly like we see in table...

`// This function can be used with antd's Table component and will perform the
// necessary sorting and filtering logic on the records, given the value of columns.
// It is useful when you want to create a CSV with data that mirrors data in an antd
// table
export function filterAndSortTableData<R>(records: R[], columns: ColumnProps<R>[]) {
    return records
        .filter(record => {
            for (let col of columns) {
                const { filteredValue, onFilter } = col
                if (onFilter && filteredValue && filteredValue.length > 0) {
                    if (filteredValue.filter(val => onFilter(val, record)).length === 0)
                        return false
                }
            }
            return true
        })
        .sort((a, b) => {
            const sort = (col: ColumnProps<R>) => {
                const { sorter, sortOrder } = col
                if (sorter && sorter instanceof Function && !isBool(sortOrder)) {
                    return sorter(a, b, sortOrder)
                }
                return 0
            }

            const sortColumn = columns.find(c => !!c.sortOrder)
            if (sortColumn) return sort(sortColumn)

            const defaultSortColumn = columns.find(c => !!c.defaultSortOrder)
            if (defaultSortColumn) return sort(defaultSortColumn)

            return 0
        }).map((record, idx) => {
            const ret: any = {};
            
            for (const col of columns) {
                const index = col.dataIndex || col.key;
                if (index) {
                    const text = (record as any)[index];
                    
                    if (col.render) {
                        ret[index] = col.render(text, record, idx);
                    } else {
                        ret[index] = text;
                    }
                }
            }

            return ret;
        })
}

function isBool(x: any): x is boolean {
    return typeof x === 'boolean'
}`

**Comment by thekennysong** [comment] 2022-01-07 20:03
@luisgustavomob thanks for sharing! Does this function work for you when there's a sort? I can't get it to work for me , only filters work.

**Comment by piraspierpaolo991** [comment] 2023-10-25 09:09
To read the current state of table dataSet, including filters and sorting, of an Ant Design table, you can utilize the `onChange` function of the table, which returns various values, including the `currentDataSet`, where you can find all the rows that match the column filters.

**Comment by yoyo837** [comment] 2023-10-25 09:14
You can do this through any Excel export library, relying on the full configuration props of the Table, etc column, dataSources...
