### ISSUE TITLE
table组件filter功能失效

### ISSUE THREAD

**Issue by webxiaobian** [ant-design/ant-design#13632] opened 2018-12-14 08:04 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
mac  谷歌浏览器 版本70.0.3538.110

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/77cf42a3](https://riddle.alibaba-inc.com/riddles/77cf42a3)

### Steps to reproduce
https://riddle.alibaba-inc.com/riddles/77cf42a3
无法点击过滤  当前的代码是官网的  版本不知道为什么无法选择 这又是一个bug

### What is expected?
修复一下

### What is actually happening?
会影响线上的功能

---
无法快速筛选对应的项目

**Comment by jialuchun** [comment] 2018-12-14 10:51
.ant-table-filter-dropdown lacks position: relative;
.ant-table-filter-dropdown样式 缺少 position: relative;属性

**Comment by jialuchun** [comment] 2018-12-14 11:48
.ant-dropdown:before   should be deleted。
.ant-dropdown:before  样式应该删除

**Comment by afc163** [comment] 2018-12-15 09:14
Duplicate of #13563

**Closed by afc163** 2018-12-15 09:14 UTC
