### ISSUE TITLE
Table设置scroll:{{x:1300}},为多列设置fixed:'right’。无数据情况下Table显示异常

### ISSUE THREAD

**Issue by changyijie** [ant-design/ant-design#6299] opened 2017-05-31 01:47 UTC
### Version
2.10.2

### Environment
win7  chrome版本 59.0.3043.0  

### Reproduction link
[https://codepen.io/anon/pen/MmNYpq?editors=0110](https://codepen.io/anon/pen/MmNYpq?editors=0110)

### Steps to reproduce
设置 Table scroll={{ x: 1500, y: 300 }}并且为多列设置fixed:'right’

### What is expected?
在多列设置fixed，无数据情况下与有数据情况下Table显示相同

### What is actually happening?
在多列设置fixed，无数据情况下与有数据情况下Table显示不相同
![image](https://cloud.githubusercontent.com/assets/22167211/26612248/4176fcfe-45e6-11e7-8b2b-61f354a8abb2.png)

有数据
![image](https://cloud.githubusercontent.com/assets/22167211/26612280/67f83190-45e6-11e7-89a9-5098a0a61658.png)

**Comment by benjycui** [comment] 2017-05-31 03:28
还是滚动条宽度的问题，ref: https://ant.design/components/table-cn/#components-table-demo-fixed-header

**Comment by yesmeck** [comment] 2017-06-13 07:28
Duplicate of #4637.

**Closed by yesmeck** 2017-06-13 07:28 UTC
