### ISSUE TITLE
antd.css should NOT add css styles to the `body` element

### ISSUE THREAD

**Issue by niole** [ant-design/ant-design#9662] opened 2018-03-13 17:33 UTC
### Version
3.3.0

### Environment
mac high sierra, google chrome v. 64

### Reproduction link
[https://codesandbox.io/s/jnw46698m3](https://codesandbox.io/s/jnw46698m3)

### Steps to reproduce
Use antd.css, look at the font-family style on the body element of the entire webpage, note that it is provided by the antd.css.

### What is expected?
As this is a component library it should not add opinionated styling to global DOM elements in the application that it is used in

### What is actually happening?
This component library, which one uses for its components, is adding opinionated styling to the app I'm working on and clobbering styling that we designed.

**Comment by dengfuping** [comment] 2018-03-14 01:54
@niole There is no perfect method to solve the problem. After all, antd is a complete design system where every component needs to comply with whole design style. Maybe https://github.com/ant-design/ant-design/issues/4331#issuecomment-268722790 could help you.

**Comment by niole** [comment] 2018-03-14 02:11
The referenced solution is not a complete solution. Antd as a product should address this for its users.

I think antd should take this componentized stylesheet idea further. Take these less stylesheets, redefine them with a library that puts styles into the DOM only when a component is used and leave the more global styles in a stylesheet. 'styled-components' would work well for this issue: https://github.com/styled-components/styled-components

**Comment by afc163** [comment] 2018-03-14 02:20
Duplicate of #9363

**Closed by afc163** 2018-03-14 02:20 UTC
