### ISSUE TITLE
Dynamic Theme Config 

### ISSUE THREAD

**Issue by daiwa233** [ant-design/ant-design#28544] opened 2020-12-25 08:42 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hope to add a themeContext to make the dynamic switching theme more compatible with React.
Although it is now possible to dynamically switch themes by compiling less in the browser, it is more complicated to use and can only be replaced globally, and components in different regions cannot be used with different themes.

### What does the proposed API look like?
-

**Comment by afc163** [comment] 2020-12-28 03:53
Duplicate of #5656

**Closed by afc163** 2020-12-28 03:53 UTC
