### ISSUE TITLE
input 可以输入多少提示

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design#16429] opened 2019-05-05 09:33 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以很明确告诉用户，还可以输入多少

### What does the proposed API look like?
maxLength、lengthDisplay

![image](https://user-images.githubusercontent.com/18542211/57191779-d4898480-6f5b-11e9-97ac-4332fee2be61.png)
希望可以增加这个功能

**Comment by sabrinaluo** [comment] 2019-05-06 04:39
这个功能的潜在issue是，不同用户对于字符数的计算方法可能不同，比如
- 英文字符占0.5，中文字符占1
- 中英文都占1

似乎有点重口难调

**Comment by kaoding** [comment] 2019-05-06 05:37
中英文都占1

**Comment by MrHeer** [comment] 2019-05-06 07:05
Both are count 1

`maxlength`
> The maximum number of characters (unicode code points) that the user can enter. If this value isn't specified, the user can enter an unlimited number of characters.

[textarea](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea)

**Comment by kaoding** [comment] 2019-05-06 07:35
maxlength 换行也占1

**Comment by afc163** [comment] 2019-05-06 13:06
Duplicate of #8148

**Closed by afc163** 2019-05-06 13:06 UTC
