### ISSUE TITLE
Remove moment and support alternative packages like Luxon, Day.js, date-fns

### ISSUE THREAD

**Issue by albinBitclass** [ant-design/ant-design#28430] opened 2020-12-19 07:21 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Moment.js themself recommend to use these alternatives since it has some performance issues and all. https://momentjs.com/docs/#/-project-status/ Can see the detailed report in this link

### What does the proposed API look like?
The preferred solution is to use Luxon.

**Comment by sridharan21994** [comment] 2020-12-19 12:27
@albinBitclass https://github.com/ant-design/ant-design/issues/26759 Please check this. Looks like a duplicate.

**Comment by afc163** [comment] 2020-12-20 03:44
Duplicate of #26759

**Closed by afc163** 2020-12-20 03:44 UTC
