### ISSUE TITLE
Form in Modal to Create

### ISSUE THREAD

**Issue by JenishDholariya2505** [ant-design/ant-design#39057] opened 2022-11-28 10:35 UTC
### Reproduction link

[https://ant.design/components/form](https://ant.design/components/form)

### Steps to reproduce

click to new collection and click close modal

### What is expected?

modal close after not blink modal

### What is actually happening?

modal close after not blink modal

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | 6.14.15 |
| System | windows 11 |
| Browser | chrome |

**Comment by afc163** [comment] 2022-11-29 04:50
Duplicate of #39013

**Closed by afc163** 2022-11-29 04:50 UTC
