### ISSUE TITLE
Equal representation of our religion, 🐸ism

### ISSUE THREAD

**Issue by neruthes** [ant-design/ant-design#13836] opened 2018-12-25 02:57 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Reports have indicated that there is only a Christmas Easter Egg within this project. However, I would like the maintainers of this project to consider, carefully, keeping the ​equal status of our religion with Christianity, in due respect of our religion, 🐸ism. In our religion, 🐸ism, we celebrate the birth of our idol on August 17th of every year. Just like the way Christians celebrate the birth of their idol.

Otherwise, I suspect that certain people might interpret the maintainers of this project a bunch of Christian Supremacists, which will be harmful for the reputation, reception, and evaluation of this project. Therefore, dear maintainers, please let me and other developers know that you are not racists or Christian Supremacists, by supporting diversity, secularity, and equal representation of religions.

Thank you. 😃

### What does the proposed API look like?
Whenever the date matches August 17th, let the buttons show wave effects upon clicking, and let their `title` be “🐸🐸🐸”, just like “Ho Ho Ho” for the Christian one.

**Comment by sirzxj** [comment] 2018-12-25 03:01
蛤蛤蛤

**Comment by afc163** [comment] 2018-12-25 03:04
Fixed in https://github.com/ant-design/ant-design/commit/d648b822a6b2789a783c7ad685a122466f6c083c

Duplicate of #13837

**Closed by afc163** 2018-12-25 03:04 UTC

**Comment by pangjunpeng** [comment] 2018-12-25 03:30
> Fixed in [d648b82](https://github.com/ant-design/ant-design/commit/d648b822a6b2789a783c7ad685a122466f6c083c)
> 
> Duplicate of #13837

这个回复是最骚的

**Comment by CUI950809** [comment] 2018-12-25 03:34
You guys shall promote your knowledge level.

**Comment by by-chimon** [comment] 2018-12-25 03:41
资瓷

**Comment by nyanpassu** [comment] 2018-12-25 04:42
HA ~ HA HA

**Comment by Gaohaoyang** [comment] 2018-12-25 05:34
资瓷资瓷
