### ISSUE TITLE
Table not render dataSource when using pagination

### ISSUE THREAD

**Issue by zanisis** [ant-design/ant-design#14875] opened 2019-02-17 13:34 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
https://codesandbox.io/s/kyjr4k175
table from dataSource detect array empty when on page 2,3,4 etc, when on page 1 when renden array what i need

### What is expected?
show data from dataSource and not read array empty when has array of object.

### What is actually happening?
fixed

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | react |
| System | mac os sierra |
| Browser | chrome 72.0.3626.109 |

**Comment by zanisis** [comment] 2019-02-17 15:31
> Hello @zanisis. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @zanisis, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。

**Comment by zanisis** [comment] 2019-02-17 15:34
Table work normaly on version 3.12.0

**Comment by imhele** [comment] 2019-02-17 16:36
This reproduction is just the bug fixed by #14608 . When `total` and length of `dataSource` are different, `current` must be set manually.

**Comment by ztplz** [comment] 2019-02-17 17:02
Pagination should show the actual number of pages. Datasource only has 4 pieces of data, but it shows two pages.

**Comment by ztplz** [comment] 2019-02-17 17:08
![image](https://user-images.githubusercontent.com/17755202/52916382-aa8bd300-3319-11e9-8ffe-52f54bd12841.png)

**Comment by zombieJ** [comment] 2019-02-18 01:30
@zanisis , you can ref @imhele 's reply and here is the fix reproduce: https://codesandbox.io/s/73jzz218z6

Additionally, current display logic is little tricky since user can hardly figure out how to trigger ajax sync logic since they use same `dataSource`.

**Comment by afc163** [comment] 2019-02-18 02:12
<img width="321" alt="image" src="https://user-images.githubusercontent.com/507615/52924015-a5ed0c00-3365-11e9-8943-783e0e7669ee.png">

I think it is intend behavior that we should not change it.

**Comment by afc163** [comment] 2019-02-18 02:45
When set `pagination.current` to Table, it works: https://codesandbox.io/s/l93l843j5m, but in 3.13.0 it is not necessary.

**Comment by imhele** [comment] 2019-02-18 03:00
> <img alt="image" width="321" src="https://user-images.githubusercontent.com/507615/52924015-a5ed0c00-3365-11e9-8943-783e0e7669ee.png">
> 
> I think it is intend behavior that we should not change it.

I think the effect #14608 wants to achieve is a special requirement, and it may be more appropriate for developers to judge the actual situation and deal with it by himself. In addition, it would be better to write this logic into the document.

**Comment by zombieJ** [comment] 2019-02-18 03:23
revert #14608 ?

**Closed** 2019-02-18 10:05 UTC
Labels: Bug🐛
