### ISSUE TITLE
Unable to import ant stylesheets while avoiding modifying global styles

### ISSUE THREAD

**Issue by jimmy-e** [ant-design/ant-design#18799] opened 2019-09-13 19:17 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/jimmy-e/ant-styling-debug](https://github.com/jimmy-e/ant-styling-debug)

### Steps to reproduce
1. run `yarn`
2. run `yarn build:dev`
3. run `yarn start`
4. Open your browser to `http://localhost:8080/`

### What is expected?
An ant button component is rendered and properly styled, looking something like one of [these](https://ant.design/components/button/) primary ant buttons.

### What is actually happening?
No ant styling / style-sheets are applied, and instead a basic html button is rendered.

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.4 |
| System | macOS High Sierra Version 10.13.6 |
| Browser | Chrome Version 76.0.3809.132 (Official Build) (64-bit) |

---
I followed the steps [here](https://ant.design/docs/react/customize-theme#How-to-avoid-modifying-global-styles?) to implement ant styling while at the same time avoiding modifying global styles. After reproducing these instructions I was unable to get the expected results. The relevant code:

**[webpack.common.js](https://github.com/jimmy-e/ant-styling-debug/blob/master/webpack.common.js):**
```
const config = {
  ...
  module: {
    rules: [
      {
        test: /\.less$/,
        use: [
          {
            loader: 'style-loader',
          },
          {
            loader: 'css-loader',
          },
          {
            loader: 'less-loader',
            options: {
              javascriptEnabled: true,
            },
          },
        ],
      },
    ],
  },
  plugins: [
    new webpack.NormalModuleReplacementPlugin(
      /node_modules\/antd\/lib\/style\/index\.less/,
      './src/index.less',
    ),
  ],
  ...
};

module.exports = config;
```

**[index.jsx](https://github.com/jimmy-e/ant-styling-debug/blob/master/src/index.jsx):**
```
import 'babel-polyfill';
import React from 'react';
import { render } from 'react-dom';
import { Button } from 'antd';

render(
  <Button type="primary">Hello World</Button>,
  document.getElementById('app'),
);
```

**[index.less](https://github.com/jimmy-e/ant-styling-debug/blob/master/src/index.less):**
```
#antd {
  @import '~antd/es/style/core/index.less';
  @import '~antd/es/style/themes/default.less';
}
```

**Comment by afc163** [comment] 2019-09-14 05:24
Duplicate of #9363

**Closed by afc163** 2019-09-14 05:24 UTC
