### ISSUE TITLE
Image组件相册模式希望下方能提供图片预览

### ISSUE THREAD

**Issue by Sharang-heng** [ant-design/ant-design#48147] opened 2024-03-28 06:06 UTC
### What problem does this feature solve?

点击预览时不只左右键能切换预览的图片，通过点击下方的预览图片也能切换图片，即类似百度地图的图片查看效果
![image](https://github.com/ant-design/ant-design/assets/69613396/18d026dd-32d6-4eb7-b90d-b959820e8267)

### What does the proposed API look like?

通过参数控制下方预览图片是否显隐

**Comment by afc163** [comment] 2024-03-28 08:35
Duplicate of https://github.com/ant-design/ant-design/issues/40194

**Closed by afc163** 2024-03-28 08:35 UTC
Labels: unconfirmed
