### ISSUE TITLE
In IE11 and Firefox 45.9.0 browsers, alignment problems occur in forms using InputNumber and DatePicker components.

### ISSUE THREAD

**Issue by 15531400827** [ant-design/ant-design#11133] opened 2018-07-03 03:39 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
window7, IE11, Firefox 45.9.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8xj6n858nl)

### Steps to reproduce
Copy links, open in IE11 or Firefox browser, enlarge the screen, compare the 3 forms, and find the input box of InputNumber and DatePicker components up.

### What is expected?
InputNumber and DatePicker should be aligned with other components.

### What is actually happening?
The InputNumber and DatePicker controls are aligned to the top of the FormItem.

**Comment by afc163** [comment] 2018-07-03 03:41
Duplicate of #9827

**Closed by afc163** 2018-07-03 03:41 UTC
