### ISSUE TITLE
BackTop回到顶部元素没有隐藏

### ISSUE THREAD

**Issue by bihongbin3027** [ant-design/ant-design#31352] opened 2021-07-12 08:16 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/back-top-cn/](https://ant.design/components/back-top-cn/)

### Steps to reproduce
看官网的例子，我滚回去的时候，明明元素显示效果已经隐藏掉了，但是鼠标还可以点击，触发了返回顶部的效果。

### What is expected?
希望元素没有在显示区域，实际要把它隐藏掉。

### What is actually happening?
元素未隐藏，还可以点击触发返回顶部的效果。

| Environment | Info |
|---|---|
| antd | 4.16.7 |
| React | 16.14.0 |
| System | window 10 |
| Browser | chrome 91.0.4472.77 |

**Comment by afc163** [comment] 2021-07-12 10:10
Duplicate of #31253

**Closed by afc163** 2021-07-12 10:10 UTC
