### ISSUE TITLE
table使用fixed="left"时,如果对应的列字段值为空,行高有问题

### ISSUE THREAD

**Issue by huapeng222** [ant-design/ant-design#22463] opened 2020-03-21 08:08 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/relaxed-brattain-z2o0m)

### Steps to reproduce
见链接

### What is expected?
行高对齐

### What is actually happening?
左边固定的一列未对齐

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.0 |
| System | mac 10.15 |
| Browser | Edge 80.0.361.66 |

---
右侧固定没有发现对应问题

**Comment by zombieJ** [comment] 2020-03-21 12:05
Duplicate of #22358

**Closed by zombieJ** 2020-03-21 12:05 UTC
