### ISSUE TITLE
Not seeing the time in onChange when it's entered wrongly formatted

### ISSUE THREAD

**Issue by lxtadhamnawito** [ant-design/ant-design#31157] opened 2021-06-27 18:02 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-hcydn4?file=index.js](https://stackblitz.com/edit/react-hcydn4?file=index.js)

### Steps to reproduce
I'm using time format as mm:ss:SSS ( minutes, seconds, milliseconds) .. so if the user tried at any time to change the time manually not from the drop down list, by writing it himself as (01:35) and not providing milliseconds, the whole time just get cleared from the timepicker and nothing happens, where it should still send it to the onChange function in-order for me to handle this case if it wasn't set.

### What is expected?
Sending the changed time in onChange function.

### What is actually happening?
Not changing anything in the timepicker, and if there's already time selected before .. it revert the value to the previous selected time.

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | ^16.13.1 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by afc163** [comment] 2021-06-28 02:36
Duplicate of https://github.com/ant-design/ant-design/issues/28591

**Closed by afc163** 2021-06-28 02:36 UTC

**Comment by lxtadhamnawito** [comment] 2021-06-28 08:47
@afc163  this is a different issue than #28591 , Milliseconds works in the format, but what I'm facing is not controlling them whenever they are not provided.
Like if user set mm:ss not mm:ss.SSS, in this case i have no control and nothing is sent to onChange function.
