### ISSUE TITLE
Table组件的column不设置sorter的情况下，点击列头也会触发onPageChange

### ISSUE THREAD

**Issue by 624220042** [ant-design/ant-design#12540] opened 2018-10-08 11:26 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
mac、chrome69，react16

### Reproduction link
[https://ant.design/docs/react/introduce](https://ant.design/docs/react/introduce)

### Steps to reproduce
点击列头

### What is expected?
Table组件的column不设置sorter的情况下，点击列头不触发onPageChange

### What is actually happening?
Table组件的column不设置sorter的情况下，点击列头也会触发onPageChange

**Comment by afc163** [comment] 2018-10-08 11:30
Fixed in https://github.com/ant-design/ant-design/issues/12515

**Comment by zombieJ** [comment] 2018-10-08 11:30
Duplicate of #12532

**Closed by afc163** 2018-10-08 11:30 UTC
