### ISSUE TITLE
[Antd 4.x] [ConfigProvider] Add more feature prevent refresh children component when ConfigProvider change locale

### ISSUE THREAD

**Issue by autuanthinh** [ant-design/ant-design#27418] opened 2020-10-28 04:38 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Children will be refresh when ConfigProvider change locale.
Hope Antd developer will support this problem.
Thanks.

### What does the proposed API look like?
```javascript
import { ConfigProvider } from 'antd';
import en_GB from 'antd/lib/locale/en_GB';
import vi_VN from 'antd/lib/locale/vi_VN';

class Page extend PureComponent {
  constructor(props);
    super(props);
    console.log('Has Refresh');
  } 
}

<ConfigProvider locale={antdLocale}><Page /></ConfigProvider>
```

**Comment by afc163** [comment] 2020-11-06 14:59
Duplicate of #27617

**Closed by afc163** 2020-11-06 14:59 UTC
