### ISSUE TITLE
Button group not showing on antd documentacion website

### ISSUE THREAD

**Issue by hugobarragon** [ant-design/ant-design#23889] opened 2020-05-05 15:24 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/button/](https://ant.design/components/button/)

### Steps to reproduce
acess antd website to check documentacion for Button.Group

### What is expected?
read button.group documentacion

### What is actually happening?
button.group is not showing up

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 0 |
| System | windows 10 |
| Browser | Google Chrome |

---
on previous version docs show just great https://3x.ant.design/components/button/

**Comment by afc163** [comment] 2020-05-06 02:42
Duplicate of #21278

**Closed by afc163** 2020-05-06 02:42 UTC
