### ISSUE TITLE
TreeSelect 异步加载 搜索结果是否能展示出展开箭头

### ISSUE THREAD

**Issue by asiareal** [ant-design/ant-design#31995] opened 2021-09-01 07:46 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在异步加载时候，搜索结果展开箭头会消失

### What does the proposed API look like?
在异步加载时候，搜索结果展开箭头保留

**Comment by asiareal** [comment] 2021-09-01 07:47
![image](https://user-images.githubusercontent.com/26968189/131632956-7ef7d4fe-c3bb-42d6-a830-3c34163c2261.png)

demo: https://codesandbox.io/s/hungry-cache-95qdz

**Comment by afc163** [comment] 2021-09-02 01:59
Duplicate of #31845

**Closed by afc163** 2021-09-02 01:59 UTC
Labels: 🐛 Bug
