### ISSUE TITLE
Menu horizontal 响应式异常

### ISSUE THREAD

**Issue by Seek-knowledge** [ant-design/ant-design#30681] opened 2021-05-25 11:27 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nvbz9)

### Steps to reproduce
横向菜单响应式，没有展示为一行  https://codesandbox.io/s/nvbz9
；但发现这个demo确能展示为一行 https://codesandbox.io/s/nameless-thunder-8fd4w
PS：代码来自网络

### What is expected?
横向Menu响应式下，展示为一行。

### What is actually happening?
横向Menu响应式下，分行展示。

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | react |
| System | win10 |
| Browser | 谷歌浏览器 |

**Comment by zombieJ** [comment] 2021-05-25 12:03
Duplicate of #30662

**Closed by zombieJ** 2021-05-25 12:03 UTC
