### ISSUE TITLE
Drawer抽屉组件使用多层抽屉后，页面不能正常滚动

### ISSUE THREAD

**Issue by qiaodaima** [ant-design/ant-design#28572] opened 2020-12-28 08:51 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/drawer-cn/#components-drawer-demo-multi-level-drawer](https://ant.design/components/drawer-cn/#components-drawer-demo-multi-level-drawer)

### Steps to reproduce
1. 在官方文档中（Drawer抽屉示例），使用【多层抽屉】demo
2. 关闭Drawer组件后，文档页面没办法正常滚动

### What is expected?
希望页面能正常滚动

### What is actually happening?
使用【多层抽屉】demo演示后，页面不能正常滚动

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | react |
| System | macOS Big Sur11.1 |
| Browser | Google Chrome 已是最新版本 版本 87.0.4280.88（正式版本） (x86_64) |

**Comment by yoyo837** [comment] 2020-12-28 09:04
Duplicate of #28528

**Closed by yoyo837** 2020-12-28 09:04 UTC
