### ISSUE TITLE
意外报错

### ISSUE THREAD

**Issue by Zei8Shuai** [ant-design/ant-design#45986] opened 2023-11-21 07:56 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-d4ynhy)

### Steps to reproduce

datePicker的onChange回调方法中设置属性，更新对象报错
“
let [formObj, setFormObj] = useState({});

<DatePicker
format="YYYY.MM.DD"
placeholder="请选择立项时间"
value={formObj.createTime}
onChange={(date, value) => {
setFormObj((prev) => {
return { ...prev, createTime: value };
});
}}
/>
”

### What is expected?

无

### What is actually happening?

报错

| Environment | Info |
| --- | --- |
| antd | 5.11.0 |
| React | 18.2.0 |
| System | windows |
| Browser | Google |

**Comment by yoyo837** [comment] 2023-11-21 07:59
Duplicate of #45983

**Comment by zombieJ** [comment] 2023-11-21 07:59
```diff
    setFormObj((prev) => {
--    return { ...prev, createTime: datestring };
++    return { ...prev, createTime: date };
    });
```

DatePicker `value` 接受的是 DayJS 对象，你传给他的是 string 自然就报错了哈~

**Closed by yoyo837** 2023-11-21 07:59 UTC
Labels: unconfirmed
