### ISSUE TITLE
use ConfigProvider.config() to turn on dark theme.

### ISSUE THREAD

**Issue by MarkLyck** [ant-design/ant-design#33812] opened 2022-01-21 17:13 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
For an application that does not use less already. It is a massive undertaking and pain to set up antd to work with custom themes.

It took several full days to implement it in our application and significantly increases our bundle size and time to load. We don't use or need less for anything other than switching between dark & light antd theme.

With version 4.17.0 I thought we would finally be able to delete many files and tons of code related to less and just have a dynamic theme in the ConfigProvider.

It works great with primaryColor, but after spending 2 hours deleting and cleaning up everything that had to do with less. I found out that the dynamic theme part of the ConfigProvider is limited to only five colors!??? You can only change primary, error, warning, success and info colors?????

And there is not even a dark theme with variable.css yet?

I am extremely disappointed in this. After spending this much time thinking we could finally remove all this less configuration and drastically improve our application, we cannot use the dynamic ConfigProvider CSS variables to actually change our theme? I don't understand why you would finally let us have a proper dynamic theme functionality but limit its features to just 5 colors?

Please please please allow us to at least switch between dark and light mode using the ConfigProvider dynamically. We've been asking for this feature for years. Please listen

### What does the proposed API look like?
```
ConfigProvider.config({
    theme: {
      type: 'dark'
    },
  })
```

**Comment by afc163** [comment] 2022-01-24 03:14
Duplicate of #23371

**Closed by afc163** 2022-01-24 03:14 UTC

**Comment by AlexandreMouyen** [comment] 2022-01-31 11:33
I am so sorry, it is not a duplicated issue. We have the new "ConfigProvider", why it could not be possible to switch between light and dark theme.

**Comment by wellitongervickas** [comment] 2022-10-18 01:30
Hey there, it should help you> [https://www.npmjs.com/package/antd-theme-vars](https://www.npmjs.com/package/antd-theme-vars)
