### ISSUE TITLE
Input suffix positioning

### ISSUE THREAD

**Issue by ops1ops** [ant-design/ant-design#20772] opened 2020-01-08 10:39 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-2w2lt)

### Steps to reproduce
1. Use long suffix
2. Type in input long text
3. See that input text is overlaid on suffix text

### What is expected?
Input text is not overlaid on suffix text

### What is actually happening?
This happens because you are using absolute positioning. You need to make common container and append suffix in it. This solution will be more independent and scalable.

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | 16.8.6 |
| System | Ubuntu 18.04.3 LTS |
| Browser | Chrome 76.0.3809.100 |

**Comment by afc163** [comment] 2020-01-08 10:45
Duplicate of #17811

**Closed by afc163** 2020-01-08 10:45 UTC
