### ISSUE TITLE
RangePicker disabledDate invalid

### ISSUE THREAD

**Issue by lj2312763** [ant-design/ant-design#16450] opened 2019-05-07 07:13 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://xjnk45z5vz.codesandbox.io/)

### Steps to reproduce
<RangePicker
      style={{ marginLeft: "20px" }}
      placeholder={["开始时间", "结束时间"]}
      showTime={{ format: "YYYY-MM" }}
      disabledDate={() => true}
      mode={["month", "month"]}
    />

### What is expected?
disabledDate effective (disabledDate 方法无效)

### What is actually happening?
disabledDate invalid(disabledDate 方法有效)

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | 16.9.0 |
| System | window 10 |
| Browser | chrome |

**Comment by afc163** [comment] 2019-05-07 07:20
Duplicate of #9008

**Closed by afc163** 2019-05-07 07:20 UTC
