### ISSUE TITLE
Expand/collapse icon in table rows shown incorrectly in Firefox

### ISSUE THREAD

**Issue by skymountain2012** [ant-design/ant-design#29848] opened 2021-03-22 00:42 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/#components-table-demo-tree-data](https://ant.design/components/table/#components-table-demo-tree-data)

### Steps to reproduce
Just open the above link in Firefox

### What is expected?
The expand icon should be ‘+’
The collapse icon should be '-'

### What is actually happening?
The expand icon is shown as '|'.
The collapse icon is shown as empty

| Environment | Info |
|---|---|
| antd | 4.14.0 |
| React | 17 |
| System | Windows 10 |
| Browser | Firefox 86.0.1 |

---
When expanding/collapsing a row, I can see that the correct icon got shown briefly, but eventually showing incorrect icon.

**Comment by MrHeer** [comment] 2021-03-22 07:54
It’s really weird, Chrome is perfect, Safari will flash when `+` -> `-`, and Firefox will disappear - `-` when `+` -> '-'. All strange phenomena happen when rotating to the `-`.

**Comment by jspark-gigworks** [comment] 2021-03-22 09:14
In my case, it is ok in Safari and Chrome. But, Firefox does not show "+" and "-".
When it is collapsed, "|" is displayed instead of "+", and when expanded, " " is displayed instead of "-".
I guess the icon cannot display "-" part, so that only "|" is displayed in "+".

My environment is macOS M1.

**Comment by anddrzejb** [comment] 2021-03-23 09:17
This is a duplicate of #293003 raised by @yasikovsky . I have exactly the same issue and I commented it on the that closed issue. 
I did some digging and I found out that when I disable the `transform-origin: bottom` on the css class `ant-table-row-expan-icon` it looks ok. I tested it on Firefox, Chrome and Edge (also checked the mobile mode).

![firefox_expandableRow](https://user-images.githubusercontent.com/6518006/112122247-c03ee700-8bc8-11eb-8b0b-9bf11f0b35dc.gif)

I do not have access to Safari, but maybe you @MrHeer could have a look if this also fixes the issue on Safari? 
I am no css guru, so I have no idea what exactly `transform-origin: bottom` was supposed to do for the expandable icon, but I cannot see any visual change in my case.

**Comment by MrHeer** [comment] 2021-03-24 01:58
@anddrzejb It's not work on Safari. `-` have a small displacement.

**Comment by anddrzejb** [comment] 2021-03-24 07:01
Dang :/. Well, I have no way of testing on Safari, so that it for me. Maybe this is going to be helpful - when I was looking for the problem, I noticed that the `+` is actually built from the `::before` sudo element and `::after` sudo element (each case `1px width` with `background-color` set). I first investigated the `::before` sudo element of the expand button - among other css properties, it has `top: 7px`. In firefox if I changed that to `6px`, the horizontal line was showing up. Obviously change to `6px` was causing the line to move and it wasn't in the center of the vertical line any longer. Max that it was still showing was `6.4999px` so I guess its threshold is `6.5px`. Why, I have no clue...

**Comment by yasikovsky** [comment] 2021-04-13 08:36
https://github.com/ant-design/ant-design/issues/29303#issuecomment-814765368 this now contains a good workaround, but the issue still persists

**Comment by afc163** [comment] 2021-05-06 07:38
<img width="1164" alt="图片" src="https://user-images.githubusercontent.com/507615/117259906-161dd480-ae81-11eb-8571-7b60b7bc6868.png">

<img width="1164" alt="图片" src="https://user-images.githubusercontent.com/507615/117259926-1c13b580-ae81-11eb-808a-bd7ba3029e1b.png">

The expand icon show perfectly in my Firefox.

**Comment by anddrzejb** [comment] 2021-05-06 07:47
@afc163 please check @MrHeer [comment](https://github.com/ant-design/ant-design/issues/29848#issuecomment-805414797) - it says this fix is not working on Safari...

**Comment by afc163** [comment] 2021-05-06 07:52
@anddrzejb I can't find displacement problem in safari either.

<img width="1695" alt="图片" src="https://user-images.githubusercontent.com/507615/117261726-115a2000-ae83-11eb-99fb-587352a027a3.png">

**Closed** 2021-05-06 08:01 UTC
Labels: IE | Firefox | Safari, 🐛 Bug

**Comment by anddrzejb** [comment] 2021-05-06 08:04
Ok 😄 I am perfectly ok with that. I have no access to safari so I was relying on others. I am glad to see that the solution I found is the same as the applied.

**Comment by yasikovsky** [comment] 2021-05-06 10:56
@afc163 are you using Firefox on Windows? I have established that this doesn't happen with some certain Windows scaling settings, but when OS level scaling is set to 100% the issue still persists. I can reproduce it consistently on multiple computers, including fresh OS installations.
