### ISSUE TITLE
能否提供滚动条组件

### ISSUE THREAD

**Issue by kaneaaa** [ant-design/ant-design#40322] opened 2023-01-19 01:54 UTC
### What problem does this feature solve?

统一美化需要滚动条的地方

### What does the proposed API look like?

可以设置滚动位置left\top，滚动到顶部\底部事件，滚动事件，自动隐藏滚动条，自动计算滚动条高度

**Comment by MadCcc** [comment] 2023-01-19 03:03
Duplicate of https://github.com/ant-design/ant-design/issues/39623

**Closed by MadCcc** 2023-01-19 03:03 UTC
Labels: unconfirmed
