### ISSUE TITLE
Input 的 lineHeight 在使用系统推荐缩放 125% 下 ，浏览器缩放 100%，高度变为21.6px

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design#43314] opened 2023-07-01 12:08 UTC
### Reproduction link

[https://ant.design/components/input-cn#components-input-demo-search-input](https://ant.design/components/input-cn#components-input-demo-search-input)

### Steps to reproduce

https://ant.design/components/input-cn#components-input-demo-search-input

Input 的 lineHeight 在使用系统推荐缩放 125% 下 ，浏览器缩放 100%，高度变为21.6px。导致 Input 高度为 31.6，而不是 32

![61468cf658928d6153dc65e528ed4866_215305430-d9f8669f-2f52-4fac-b657-a025ba20f9b4](https://github.com/ant-design/ant-design/assets/3166799/22e7210b-26e1-4a95-9f9e-b8f1ac083d43)

![99d5a4facdf6555095bb9efad3d44fcd_208244393-e141ca4f-608d-4e65-9af7-c1522b1b9f21](https://github.com/ant-design/ant-design/assets/3166799/7db23f0e-a431-4cce-973d-a2943569a728)

![image](https://github.com/ant-design/ant-design/assets/3166799/1fbff8af-be01-4754-97bf-58bf9ce1d18f)

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | Reace 18 |
| System | Windows10 |
| Browser | Chrome 100 |

**Comment by afc163** [comment] 2023-07-01 12:15
Duplicate of #40440

**Closed by afc163** 2023-07-01 12:15 UTC
Labels: unconfirmed

**Comment by hihuangwei** [comment] 2023-07-01 12:32
@afc163  这问题有办法解决吗
