### ISSUE TITLE
In version 4.24.x, <Steps.Step> cannot be used in a wrapped component.

### ISSUE THREAD

**Issue by umcai** [ant-design/ant-design#42937] opened 2023-06-09 08:44 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-x8w8hh)

### Steps to reproduce

Props like `title` in wrapper component didn't work.  
Works fine in 4.23.6 and below.

### What is expected?

The props of Steps.Step works fine.

### What is actually happening?

The values of props such as title are not displayed.

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Chrome 114 |

**Comment by afc163** [comment] 2023-06-09 10:19
Duplicate of https://github.com/ant-design/ant-design/issues/4853

**Closed by afc163** 2023-06-09 10:19 UTC
Labels: unconfirmed
