### ISSUE TITLE
`moment` is outdated; new version has new typings which makes ant design typings miss

### ISSUE THREAD

**Issue by schwigri** [ant-design/ant-design#24411] opened 2020-05-23 01:43 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/moment/moment](https://github.com/moment/moment)

### Steps to reproduce
1. Install the latest moment (2.26.0)
2. Install the latest ant design (4.2.4)
3. Create a TypeScript calendar with dateCellRender function
4. The type of moment.Moment does not match between moment and ant desitn

### What is expected?
The moment used by ant design should be compatible with the latest version of moment

### What is actually happening?
My VS Code errors, saying this: moment Property 'isoWeeksInISOWeekYear' is missing in type 'moment.Moment' 

The latest version of moment has new typings for isoWeeksInISOWeekYear, so the moment used by ant design does not match the lastest version of moment, so my project errors when trying to use dateCellRender

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.13.1 |
| System | TypeScript |
| Browser | any |

**Comment by afc163** [comment] 2020-05-23 05:27
Duplicate of #24377

**Closed by afc163** 2020-05-23 05:27 UTC

**Comment by cpprookie** [comment] 2020-07-01 11:14
Both issues are closed, have you guys fixed this?

**Comment by afc163** [comment] 2020-07-01 11:37
Yeah, wait for next patch.

**Comment by cpprookie** [comment] 2020-07-02 11:37
Thanks for your hard work.
