### ISSUE TITLE
Virtual list with all Table features

### ISSUE THREAD

**Issue by ButuzGOL** [ant-design/ant-design#23057] opened 2020-04-08 15:26 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/#components-table-demo-virtual-list](https://ant.design/components/table/#components-table-demo-virtual-list)

### Steps to reproduce
Tried Virtual List with features
1. Fixed columns
2. Grouped Headers
3. Tree data

### What is expected?
Virtual List will support all Table features

### What is actually happening?
Table broken

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16 |
| System | Mac |
| Browser | Chrome |

**Comment by crawler-django** [comment] 2020-04-09 02:40
u can use 'virtuallist-antd'.😆
try.

**Comment by zombieJ** [comment] 2020-04-09 02:47
Duplicate of #20339

**Closed by zombieJ** 2020-04-09 02:47 UTC
