### ISSUE TITLE
Table scrollbar cannot use

### ISSUE THREAD

**Issue by xiiiAtCn** [ant-design/ant-design#5115] opened 2017-03-01 03:49 UTC
#### Environment(required)

- antd version: 2.7.4
- OS and its version: win10
- Browser and its version: 56.0.2924.87

I set the table's scroll, and set the first column fixed in the left.Then I find I can't move the table by the scrollbar which is under the fixed columns. To make it clearer， I set the first three columns fixed in the left.  Here is the re-produce.http://codepen.io/XiiiAtCn/pen/oZjmrL?editors=0010. It would work properly only if the scrollbar of y-axis  appears,such as adding more data or setting the scroll's property of 'y' smaller

**Comment by yesmeck** [comment] 2017-03-01 03:57
Duplicate of #4893.

**Closed by yesmeck** 2017-03-01 03:57 UTC

**Comment by yesmeck** [comment] 2017-03-01 04:02
Try reinstall node_modules.

**Comment by xiiiAtCn** [comment] 2017-03-01 05:09
It worked. However, the online demo still has problems. I wish you could update the online 'antd' as  the newer verson released.
