### ISSUE TITLE
Check Box Validation not working

### ISSUE THREAD

**Issue by Sathiyamm** [ant-design/ant-design#8262] opened 2017-11-21 08:07 UTC
### Version
2.13.10

### Environment
Windows 7,

### Reproduction link
[https://github.com/ant-design/ant-design/issues/8260](https://github.com/ant-design/ant-design/issues/8260)
[https://ant.design/components/form/](https://ant.design/components/form/)

### Steps to reproduce
The enter all details , but not checked in checkbox and submit click . Not showing check box validation

### What is expected?
Check box not checked validation show

### What is actually happening?
Not validation show in check box.

**Comment by afc163** [comment] 2017-11-21 08:08
Duplicate of #8261

**Closed by afc163** 2017-11-21 08:08 UTC
