### ISSUE TITLE
Table 开启 virtual，覆盖默认的 table组件不生效

### ISSUE THREAD

**Issue by cjtcjt999** [ant-design/ant-design#45312] opened 2023-10-13 01:44 UTC
### Reproduction link

[https://stackblitz.com/edit/react-3bejp9-dpb5m7?file=demo.tsx](https://stackblitz.com/edit/react-3bejp9-dpb5m7?file=demo.tsx)

### Steps to reproduce

Table的components配置
header: {
   cell: header,
},
在开启virtual: true后失效

### What is expected?

virtual开启，表头组件依然生效

### What is actually happening?

virtual开启，表头组件不生效

| Environment | Info |
| --- | --- |
| antd | 5.10.0 |
| React | 18.2.0 |
| System | win11 |
| Browser | 117.0.5938.92 |

**Comment by yoyo837** [comment] 2023-10-13 01:50
Duplicate of #44787

**Closed by yoyo837** 2023-10-13 01:50 UTC
Labels: unconfirmed
