### ISSUE TITLE
rowSelection doesn't support rowSpan?

### ISSUE THREAD

**Issue by liu2080019** [ant-design/ant-design#7908] opened 2017-10-17 04:04 UTC
### What problem does this feature solve?
i used rowSpan in my Table, but each row has a rowSelection, it is not cool...

### What does the proposed API look like?
i expect that rowSelection also can use rowSpan,that is cool. Any solutions for now ?

**Comment by afc163** [comment] 2017-10-17 05:26
Duplicate of #3505

**Closed by afc163** 2017-10-17 05:26 UTC
