### ISSUE TITLE
Table大数据量卡卡卡卡卡卡卡，要进行表头列拖动，已经表格中cell可以编辑，当row数量超过300，整个页面都不能动了，只能换官方的FIXED-data-table-2，卡顿解决了，但是样式没antd洋气。

### ISSUE THREAD

**Issue by z5614036** [ant-design/ant-design#10726] opened 2018-05-31 13:14 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Table大数据量卡卡卡卡卡卡卡卡

### What does the proposed API look like?
API你们定义，我用就行！

**Comment by yesmeck** [comment] 2018-05-31 14:39
Duplicate of #10431

**Closed by yesmeck** 2018-05-31 14:39 UTC
