### ISSUE TITLE
rc-menu has outdated dependencies using findDOMNode, whch cause warning in React 18 ScritMode

### ISSUE THREAD

**Issue by Lantianyou** [ant-design/ant-design#41223] opened 2023-03-14 08:00 UTC
### Reproduction link
The link is wrong
[https://new-issue.ant.](https://codesandbox.io/s/antd-reproduction-template-forked-qwsqrb?file=/index.js)

### Steps to reproduce

Any antd project using `Menu` component

### What is expected?

No warning

### What is actually happening?
To fix this issue, I believe changing the code in rc-resize-observer is necessary. The `findDomNode` method is problematic 

![image](https://user-images.githubusercontent.com/37259750/224934194-597259b1-6207-4778-b1c7-b03b672fcbd3.png)
![image](https://user-images.githubusercontent.com/37259750/224934288-d68f1c98-7234-4347-86e9-54d49b473282.png)

![image](https://user-images.githubusercontent.com/37259750/224934036-e6f530af-1383-433a-9aac-0fcf768b2cb5.png)

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | latest |
| System | Ubuntu |
| Browser | Latest Chrome |

**Comment by Lantianyou** [comment] 2023-03-14 08:10
Hi @MadCcc the reproduction link is here https://codesandbox.io/s/antd-reproduction-template-forked-qwsqrb?file=/index.js

**Comment by Lantianyou** [comment] 2023-03-14 08:10
![image](https://user-images.githubusercontent.com/37259750/224936569-baba0fe3-9dba-44a3-9b20-1bdeb93bd8ed.png)

**Comment by guoyunhe** [comment] 2023-03-16 09:00
Same issue here with React 18.

**Comment by afc163** [comment] 2023-03-19 08:32
Duplicate of #35361

**Closed by afc163** 2023-03-19 08:32 UTC
Labels: improvement
