### ISSUE TITLE
tabs hideadd不生效

### ISSUE THREAD

**Issue by zlab** [ant-design/ant-design#24672] opened 2020-06-02 01:25 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?editors=0010](https://codepen.io/pen/?editors=0010)

### Steps to reproduce
直接打开官网的自定义新增 demo吧

### What is expected?
隐藏➕

### What is actually happening?
依然显示

| Environment | Info |
|---|---|
| antd | 4.3.0 |
| React | 16.13 |
| System | mac13 |
| Browser | chrome 80 |

**Comment by zombieJ** [comment] 2020-06-02 01:44
Duplicate of #24617

**Closed by zombieJ** 2020-06-02 01:44 UTC
