### ISSUE TITLE
DropDown组件trigger为hover，使用弹窗组件会出现在弹窗层hover时，dropdown下拉框也会展示

### ISSUE THREAD

**Issue by linnaMao** [ant-design/ant-design#43600] opened 2023-07-17 04:06 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-7-0-forked-7yd8t7?file=/demo.tsx)

### Steps to reproduce

hover展示下拉框，点击打开弹窗

### What is expected?

打开弹窗后 hover到弹窗不会让dropdown下拉框展示

### What is actually happening?

打开弹窗后 hover到弹窗会导致dropdown下拉框展示

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18.0.0 |
| System | Windows 11 企业版 |
| Browser | chrome |

---
弹窗组件只要放在dropdown组件内部就会复现

**Comment by linnaMao** [comment] 2023-07-17 04:07
![image](https://github.com/ant-design/ant-design/assets/46858441/13cbbd73-5a03-45c4-b74c-1c0ead9ee902)

**Comment by Wxh16144** [comment] 2023-07-17 04:14
Duplicate of #43527

**Closed by Wxh16144** 2023-07-17 04:14 UTC
Labels: unconfirmed
