### ISSUE TITLE
Table组件单页数据500复选框很慢

### ISSUE THREAD

**Issue by ksh033** [ant-design/ant-design#18974] opened 2019-09-24 09:15 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Table组件单页数据量大

### What does the proposed API look like?
Table组件单页数据量大的展示

**Comment by afc163** [comment] 2019-09-24 10:04
Duplicate of #10431

**Closed by afc163** 2019-09-24 10:04 UTC
