### ISSUE TITLE
React版本更新至16.9.0后，使用表格组件，控制台打印Warning信息

### ISSUE THREAD

**Issue by EmiyaGm** [ant-design/ant-design#18283] opened 2019-08-15 02:09 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/EmiyaGm/react-project-formwork](https://github.com/EmiyaGm/react-project-formwork)

### Steps to reproduce
react 更新至16.9.0版本，并且引入 antd 表格组件即可

### What is expected?
控制台无warning

### What is actually happening?
控制台输出warning

例：

```
index.js:1437 Warning: The <HeadTable /> component appears to be a function component that returns a class instance. Change HeadTable to a class that extends React.Component instead. If you can't use a class try assigning the prototype on the function as a workaround. `HeadTable.prototype = React.Component.prototype`. Don't use an arrow function since it cannot be called with `new` by React.
console.<computed> @ index.js:1437
index.js:1437 Warning: The <BodyTable /> component appears to be a function component that returns a class instance. Change BodyTable to a class that extends React.Component instead. If you can't use a class try assigning the prototype on the function as a workaround. `BodyTable.prototype = React.Component.prototype`. Don't use an arrow function since it cannot be called with `new` by React.
console.<computed> @ index.js:1437
index.js:1437 Warning: The <ColGroup /> component appears to be a function component that returns a class instance. Change ColGroup to a class that extends React.Component instead. If you can't use a class try assigning the prototype on the function as a workaround. `ColGroup.prototype = React.Component.prototype`. Don't use an arrow function since it cannot be called with `new` by React.
console.<computed> @ index.js:1437
index.js:1437 Warning: The <TableHeader /> component appears to be a function component that returns a class instance. Change TableHeader to a class that extends React.Component instead. If you can't use a class try assigning the prototype on the function as a workaround. `TableHeader.prototype = React.Component.prototype`. Don't use an arrow function since it cannot be called with `new` by React.
console.<computed> @ index.js:1437
index.js:1437 Warning: A future version of React will block javascript: URLs as a security precaution. Use event handlers instead if you can. If you need to generate unsafe HTML try using dangerouslySetInnerHTML instead. React was passed "javascript:;"
```

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.9.0 |
| System | macOS Mojave 10.14.5 (18F2058) |
| Browser | Google Chrome 75.0.3770.142 |

**Comment by afc163** [comment] 2019-08-15 02:20
Duplicate of #9792

**Closed by afc163** 2019-08-15 02:20 UTC

**Comment by fireswork** [comment] 2019-09-09 05:52
https://github.com/react-component/table/issues/368
rc-table也有个类似的issue，不确定是rc还是react-hot-loader的问题

**Comment by happy760690** [comment] 2019-09-19 07:23
我也有同样的问题
backend.js:1 Warning: React does not recognize the `dataIndex` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `dataindex` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by happy760690** [comment] 2019-09-19 07:24
我也有同样的问题
backend.js:1 Warning: The <HeadTable /> component appears to be a function component that returns a class instance. Change HeadTable to a class that extends React.Component instead. If you can't use a class try assigning the prototype on the function as a workaround. `HeadTable.prototype = React.Component.prototype`. Don't use an arrow function since it cannot be called with `new` by React.

**Comment by fireswork** [comment] 2019-09-20 01:13
@happy760690 哪有什么解决方案，@hot-loader/react-dom是给react hooks提供支持的，问题一直都存在

**Comment by Miiskye** [comment] 2019-09-20 08:42
warning + 1，正在寻找解决方案

**Comment by EmiyaGm** [comment] 2019-09-23 00:45
> warning + 1，正在寻找解决方案

暂时选择了react的版本回退至 16.8.x

**Comment by yanyang1116** [comment] 2019-10-02 10:58
的确是 react-hot-loader 报的错。
移除 react-hot-loader 相关，代码就不报这个错了。

**Comment by nianiaJR** [comment] 2019-11-07 08:34
A way to fix this: https://github.com/react-component/table/issues/368

**Comment by zhengyanwen** [comment] 2021-03-31 08:12
`npm install @hot-loader/react-dom`

and webpack set：

```
resolve: {
    alias: {
      'react-dom': '@hot-loader/react-dom',
    }
  },
```
