### ISSUE TITLE
form.validateFieldsAndScroll滚动到的表单项显示不全

### ISSUE THREAD

**Issue by Thj007** [ant-design/ant-design#21328] opened 2020-02-10 12:49 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gmzhp)

### Steps to reproduce
1.在modal中使用form
2.设置modal的body高度，并设置overflow: auto
3.填充很多表单

### What is expected?
表单滚动时可以显示到label或完全显示错误信息

### What is actually happening?
错误信息不能够完全展示或label展示不全

| Environment | Info |
|---|---|
| antd | 3.26.9 |
| React | 16.8 |
| System | window |
| Browser | chrome |

**Comment by Thj007** [comment] 2020-02-10 12:50
实际结果：
![image](https://user-images.githubusercontent.com/30485600/74151333-eadd1300-4c46-11ea-8eb2-858142d1e684.png)
预期结果：
![image](https://user-images.githubusercontent.com/30485600/74151354-f8929880-4c46-11ea-8b55-f6461988e18e.png)

**Comment by zombieJ** [comment] 2020-02-11 10:01
Reproduce 没有用到 `validateFieldsAndScroll`，是不是忘记保存了？

**Comment by Thj007** [comment] 2020-02-12 03:48
https://codesandbox.io/s/antd-reproduction-template-z1dvq
@zombieJ  @ant-design-bot

**Comment by Thj007** [comment] 2020-02-12 03:53
1.打开页面，滚动条置顶
![image](https://user-images.githubusercontent.com/30485600/74301440-0bfc4b80-4d8e-11ea-820f-07a74f10bbc3.png)
2.点击确定按钮
![image](https://user-images.githubusercontent.com/30485600/74301513-4239cb00-4d8e-11ea-8cb7-b6a3a4e12493.png)

**Comment by afc163** [comment] 2020-02-20 09:00
Duplicate of #21485

**Closed by afc163** 2020-02-20 09:00 UTC
Labels: 🤔 Need Reproduce
