### ISSUE TITLE
Menu.SubMenu popup 打开时 闪烁

### ISSUE THREAD

**Issue by pentyh** [ant-design/ant-design#27395] opened 2020-10-27 07:07 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://preview.pro.ant.design/profile?primaryColor=daybreak&splitMenus=false&navTheme=light&layout=top&contentWidth=Fixed](https://preview.pro.ant.design/profile?primaryColor=daybreak&splitMenus=false&navTheme=light&layout=top&contentWidth=Fixed)

### Steps to reproduce
鼠标 光标移动到 Menu 上 popup 打开时 闪烁非常严重

### What is expected?
不让它闪烁

### What is actually happening?
闪烁

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.14.0 |
| System | Windows 10 |
| Browser | Chrome 86.0.4240.111 |

**Comment by afc163** [comment] 2020-10-27 07:42
Duplicate of #26979 and #26970

**Closed by afc163** 2020-10-27 07:42 UTC
