### ISSUE TITLE
ConfigProvider不支持对Popconfirm进行className样式覆盖，在ConfigProvider的类型定义中没找到Popconfirm（不是theme里的token覆盖）

### ISSUE THREAD

**Issue by projectcss** [ant-design/ant-design#50329] opened 2024-08-09 07:12 UTC
### Reproduction link

[https://github.com/ant-design/ant-design/blob/7085ab39d07c4757779238550a04840be2a71c95/components/config-provider/index.tsx#L183](https://github.com/ant-design/ant-design/blob/7085ab39d07c4757779238550a04840be2a71c95/components/config-provider/index.tsx#L183)

### Steps to reproduce

https://github.com/ant-design/ant-design/blob/7085ab39d07c4757779238550a04840be2a71c95/components/config-provider/index.tsx#L183

### What is expected?

ConfigProvider支持对Popconfirm进行className样式覆盖

### What is actually happening?

ConfigProvider不支持对Popconfirm进行className样式覆盖

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 18.3.1 |
| System | mac |
| Browser | 120 |

**Comment by Wxh16144** [comment] 2024-08-16 10:04
找不到就是没有设计这个 Feature

**Comment by MadCcc** [comment] 2024-08-21 08:11
duplicate of https://github.com/ant-design/ant-design/issues/50303

**Closed by MadCcc** 2024-08-21 08:11 UTC
Labels: unconfirmed
