### ISSUE TITLE
filter not work while another filter using custom filterdropdown with react hooks

### ISSUE THREAD

**Issue by lfpkkk** [ant-design/ant-design#28107] opened 2020-12-01 06:22 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-cs2cq?file=/index.js)

### Steps to reproduce
Make any selection in the filter of Name field and press OK.

### What is expected?
Table content should be filtered by selection of Name filter

### What is actually happening?
Table content doesn't change

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | chrome Version 87.0.4280.66 (Official Build) (64-bit) |

**Comment by marianayap** [comment] 2020-12-03 04:29
I'll like to work in this issue @afc163

**Comment by marianayap** [comment] 2020-12-03 17:46
@afc163  I'm working on it, is it necessary to assign it to me in here? Thank you

**Comment by lfpkkk** [comment] 2020-12-08 02:32
@marianayap really appreciate it for your keen help. I tried your attached link but didn't see any use of react hooks. Would you mind give me more details about how to fix this bug? 
Also I think you can raise a pull request to make your fixes available for other ant design users.

**Comment by marianayap** [comment] 2020-12-16 04:15
@lfpkkk I can create the pull request so it can be more visible, I just haven't found the file where I can do the changes in the repo and make the PR. I'm wondering if you have an idea where could I found it or the file's name?

**Comment by afc163** [comment] 2021-05-20 08:20
@marianayap PR is welcome~

**Comment by wendellhu95** [comment] 2021-06-06 01:45
I can took a loot at it since marianayap seems to have been afk for a while.

**Comment by wendellhu95** [comment] 2021-06-06 04:40
After some investigation I think it is a by-design behavior rather than a bug. The Table component sees filters as 'controlled' if a `filteredKeys` is passed in.

![image](https://user-images.githubusercontent.com/12122021/120912704-26b1ac80-c6c4-11eb-909f-cc18fb65f576.png)

So, shall we close this issue or change the behavior here? @zombieJ @afc163

**Comment by zombieJ** [comment] 2021-06-06 12:55
@wendellhu95 , seems we can add warning about this to avoid confusing?

**Comment by wendellhu95** [comment] 2021-06-06 16:34
> @wendellhu95 , seems we can add warning about this to avoid confusing?

Ok. I will change the warning message (and doc if necessary) to clarify this kind of situation.

**Comment by wendellhu95** [comment] 2021-06-07 01:58
@zombieJ PR is submitted. Though it might be time-expensive to give correct warning message when number of columns is big.

**Closed** 2021-06-09 04:19 UTC
Labels: help wanted, 🐛 Bug

**Comment by Jahn08** [comment] 2021-11-21 12:25
> > @wendellhu95 , seems we can add warning about this to avoid confusing?
> 
> Ok. I will change the warning message (and doc if necessary) to clarify this kind of situation.

Are you sure that this warning is enough to avoid this situation? Because one can set up all `filteredValue: null` [in the example above](https://codesandbox.io/s/antd-reproduction-template-forked-cs2cq?file=/index.js) to avoid the warning, whereas it won't make the filter working. Instead, using `defaultFilteredValue` instead of `filteredValue` could help in that particular case. Moreover, now this warning adds even more confusion since there is no direct explanation in documentation what conditions it tries to prevent and what is actually recommended.
