### ISSUE TITLE
Table summary row need to be fixed at the bottom within the scroll window

### ISSUE THREAD

**Issue by kangkang07** [ant-design/ant-design#25169] opened 2020-06-23 03:23 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When the table is very long, you need to scroll to bottom to see the summary row

### What does the proposed API look like?
```<Summary.Row fixed="bottom" />```

**Comment by afc163** [comment] 2020-06-23 03:40
Duplicate of #25116

**Closed by afc163** 2020-06-23 03:40 UTC
