### ISSUE TITLE
allow choose Select dropdown direction

### ISSUE THREAD

**Issue by xuchaoying** [ant-design/ant-design#9468] opened 2018-03-01 09:30 UTC
### What problem does this feature solve?
when a Select component is placed at the bottom of a page, it is useful to change the dropdown direction to 'top', so it won't be cut off.

### What does the proposed API look like?
add a 'dropdownDirection' prop to Select

**Comment by yesmeck** [comment] 2018-03-01 09:57
Duplicate of #5130

**Closed by yesmeck** 2018-03-01 09:57 UTC
Labels: Component: Dropdown
