### ISSUE TITLE
Typescript examples

### ISSUE THREAD

**Issue by P0oOOOo0YA** [ant-design/ant-design#12774] opened 2018-10-22 19:55 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Where is the love for Typescript? Ant design is written in Typescript, still when you read the docs, all examples are written in JavaScript. Please provide Typescript examples as well.

### What does the proposed API look like?
TS   JS

**Comment by afc163** [comment] 2018-10-23 02:40
Duplicate of #5390

**Closed by afc163** 2018-10-23 02:40 UTC
