### ISSUE TITLE
Dark Mode: Modal Colors (Confirm, Warning, Info, Error) Remain White

### ISSUE THREAD

**Issue by shalinirana1999** [ant-design/ant-design#51818] opened 2024-11-28 10:50 UTC
### Reproduction link

[https://prnt.sc/VJxDat8LTZ2F](https://prnt.sc/VJxDat8LTZ2F)

### Steps to reproduce

- Set the theme to dark mode in the Ant Design application.
- Trigger any modal of type Confirm, Warning, Info, or Error.
- Observe that the modal background remains white, while the rest of the UI follows the dark theme.

### What is expected?

The Confirm, Warning, Info, and Error modals should adapt to dark mode by having appropriate background and text colors, matching the rest of the UI.

### What is actually happening?

The modal background remains white and behaves like light mode even when the dark mode theme is enabled.

| Environment | Info |
| --- | --- |
| antd | 5.22.1 |
| React | 18.3.1 |
| System | m2 air (mackbook air) |
| Browser | crome |

---
N/A

**Comment by Wxh16144** [comment] 2024-11-28 11:03
@petercat-assistant Please communicate in English!

**Comment by shalinirana1999** [comment] 2024-11-28 12:53
Thank you for the suggestions. I have already tried the these steps. Additionally, I have added other types of modals, and they are adapting to dark mode correctly. However, the specific modals of type Confirm, Warning, Info, or Error are not adapting to dark mode and remain in light mode.

**Comment by afc163** [comment] 2024-11-29 02:10
https://ant.design/components/modal#why-i-can-not-access-context-redux-configprovider-localeprefixcls-in-modalxxx

**Comment by afc163** [comment] 2024-11-29 02:11
Duplicate of https://github.com/ant-design/ant-design/issues/40546

**Closed by afc163** 2024-11-29 02:10 UTC
Labels: unconfirmed
