### ISSUE TITLE
onBlur does not work in tree select

### ISSUE THREAD

**Issue by habeebahmed** [ant-design/ant-design#23597] opened 2020-04-25 19:13 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/condescending-night-lfn2v?file=/index.js)

### Steps to reproduce
- Click on the input field
- Click on somewhere else to remove focus

### What is expected?
when focus is removed onBlur should be called

### What is actually happening?
when focus is there both onFocus and onBlur is called

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | latest |
| System | latest |
| Browser | latest |

**Comment by afc163** [comment] 2020-04-26 04:05
Duplicate of #21498

**Closed by afc163** 2020-04-26 04:05 UTC
