### ISSUE TITLE
TextArea 设置maxlength 时候中文输入法，字母输入最大值的时候关闭输入法

### ISSUE THREAD

**Issue by suxin2017** [ant-design/ant-design#29513] opened 2021-02-26 03:48 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/angelname/pen/wvoyGjr?editors=1010](https://codepen.io/angelname/pen/wvoyGjr?editors=1010)

### Steps to reproduce
mac 搜狗中文输入法
输入当字母到达最大长度会关闭输入框

### What is expected?
和Input行为保持一致

### What is actually happening?
不一致

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16 |
| System | mac |
| Browser | chrome |

**Comment by suxin2017** [comment] 2021-02-26 03:54
https://user-images.githubusercontent.com/28481035/109252830-69dcc380-7829-11eb-9260-0d5917260d8b.mov

**Comment by afc163** [comment] 2021-02-26 07:32
Duplicate of #28940

**Closed by afc163** 2021-02-26 07:32 UTC
