### ISSUE TITLE
Filters doesn't pass into Table onChange handler

### ISSUE THREAD

**Issue by oceandrama** [ant-design/ant-design#28603] opened 2020-12-29 11:15 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-sb8w9?file=/index.js)

### Steps to reproduce
1. Click to `name` column filter
2. Type something
3. Click Search
4. Go to the console

### What is expected?
`name` filters includes search string

### What is actually happening?
`name` filters are empty

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Chrome  87.0.4280.88 |

---
This error appeared after https://github.com/ant-design/ant-design/pull/28220 in function `generateFilterInfo`

**Comment by afc163** [comment] 2020-12-29 15:37
@Meowu

**Comment by urrri** [comment] 2020-12-29 15:39
First version I found the problem is 4.9.3

**Comment by Meowu** [comment] 2020-12-29 15:45
I will have a look at this later.

**Comment by empz** [comment] 2020-12-30 10:00
Came here to report the same issue. Subscribing to get updated.

**Comment by SSW-imp** [comment] 2020-12-31 02:52
+1

**Comment by Meowu** [comment] 2020-12-31 08:25
fixed in https://github.com/ant-design/ant-design/pull/28627

**Closed** 2021-01-04 03:17 UTC
Labels: 👷🏻‍♂️ Someone working on it
