### ISSUE TITLE
Range Picker when in [year, year] mode does not update current value when new year clicked

### ISSUE THREAD

**Issue by s-kashif** [ant-design/ant-design#15877] opened 2019-04-05 02:29 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/xlrx646o4o)

### Steps to reproduce
1. Create a range picker with mode=['year','year']
2. Open the picker and try choosing new years
Result: the newly selected year is not updated in the UI

### What is expected?
Expected to see updated year just like in date and month mode

### What is actually happening?
the newly selected year is not updated in the UI

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.8 |
| System | Windows/Mac  |
| Browser | Chrome/Firefox |

**Comment by afc163** [comment] 2019-04-05 07:32
Duplicate of #9809

**Closed by afc163** 2019-04-05 07:32 UTC
