### ISSUE TITLE
Table -> expandedRowRender icon is showing when dataSource.children is array

### ISSUE THREAD

**Issue by cesarve77** [ant-design/ant-design#12684] opened 2018-10-16 22:44 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
OSX 10.14, All browsers

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/42oz43nzvx)

### Steps to reproduce
Create a table component with dataSource having a row with a property children = []

### What is expected?
Don't show expandedRowRender icon if not expandedRowRender property is defined

### What is actually happening?
Table component Show expandedRowRender icon  if expandedRowRender property is undefined when the datasource has a row with a property children as Array

**Comment by afc163** [comment] 2018-10-17 02:41
Duplicate of #11937

**Closed by afc163** 2018-10-17 02:41 UTC

**Comment by afc163** [comment] 2018-10-17 02:43
https://github.com/ant-design/ant-design/issues/9689

**Comment by afc163** [comment] 2019-02-20 02:42
Duplicate of #1365

**Comment by Julycc41** [comment] 2023-04-04 09:36
children = []Can control + display 
Excuse me, my chidren is dynamically requested to render when I add expandable, it seems chidren is no longer valid, all + are displayed
![image](https://user-images.githubusercontent.com/80231740/229751208-0f542d0d-f6ab-409f-bd24-49a137590235.png)
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/80231740/229751350-9343cec6-88f6-4a9f-a897-6c4f1a4dc601.png">

**Comment by Julycc41** [comment] 2023-04-04 09:45
https://codesandbox.io/s/antd-reproduction-template-forked-y51dkm?file=/index.js
