### ISSUE TITLE
TreeSelect在选项很多时默认不显示滚动条，这样会使用户造成误解

### ISSUE THREAD

**Issue by ppmmwozuiai** [ant-design/ant-design#28017] opened 2020-11-26 09:42 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-select-cn/#components-tree-select-demo-async](https://ant.design/components/tree-select-cn/#components-tree-select-demo-async)

### Steps to reproduce
一直异步加载子节点，使tree-select的长度超出其max-height，此时并不显示滚动条，只有在鼠标滚动时才出现滚动条。
如果初始状态就存在足够多的选项，这样用户就会任为选项只有显示出来的一部分，如果恰巧遇到用户使用古早的没有滚轮的鼠标或者滚轮失效的鼠标则下面的选项就无法完整显示

### What is expected?
在选项较多时默认就显示滚动条

### What is actually happening?
没有默认显示滚动条

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | 16.x |
| System | windows10 |
| Browser | chrome，edge |

**Comment by afc163** [comment] 2020-11-30 08:15
Duplicate of #28074

**Closed by afc163** 2020-11-30 08:15 UTC
Labels: improvement
