### ISSUE TITLE
componentWillMount, componentWillReceiveProps, and componentWillUpdate warnings after upgrading to react 16.9.0

### ISSUE THREAD

**Issue by hjiawei** [ant-design/ant-design#18197] opened 2019-08-10 04:43 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-yluyf)

### Steps to reproduce
Just build the latest ant design (3.21.4) with react 16.9.0. You will see warnings in the console like this:

> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
>
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
>
> Please update the following components: Tabs

### What is expected?
No console warnings on deprecated React lifecycle methods.

### What is actually happening?
Various warnings on deprecated React lifecycle methods. According to the note, they won't work anymore after React 17.x.

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.9.0 |
| System | Ubuntu 19.04 |
| Browser | Google Chrome 76.0.3809.100 (latest official build) |

**Comment by afc163** [comment] 2019-08-10 05:52
Duplicate of #9792

**Closed by afc163** 2019-08-10 05:52 UTC

**Comment by pjt57364413** [comment] 2019-08-13 13:14
can you tell me how to fixed?

**Comment by hjiawei** [comment] 2019-08-13 15:24
I guess we have to wait until https://github.com/ant-design/ant-design/issues/9792 is resolved atm.
