### ISSUE TITLE
InputNumber character change issue 

### ISSUE THREAD

**Issue by genc6541** [ant-design/ant-design#20551] opened 2019-12-30 13:47 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/captainblack/pen/abzLbjz?&editable=true&editors=001](https://codepen.io/captainblack/pen/abzLbjz?&editable=true&editors=001)

### Steps to reproduce
We use inputnumber component of antdesign. While we are writing numbers inside of inputnumber component after seventeenth character the number is changing to another number. For example, I m typing only 1 number 20 times and after 17 it changes to diffrent numbers.

### What is expected?
If I type 20 piece of 1 number I wait it must appear as 11111111111111111111

### What is actually happening?
when I type 11111111111111111111 it appears 1111111111111111168

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.8.4 |
| System | windows 10 |
| Browser | chrome  |

**Comment by afc163** [comment] 2019-12-30 14:13
Duplicate of #19653

**Closed by afc163** 2019-12-30 14:13 UTC
