### ISSUE TITLE
希望Table组件可以支持多列排序

### ISSUE THREAD

**Issue by Chastrlove** [ant-design/ant-design#12141] opened 2018-09-08 03:44 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前的Table组件只支持单列排序。对于多列进行服务端排序的业务场景，会导致视图显示的排序样式与实际得到的数据不相符（高亮的排序永远只有一个）。

### What does the proposed API look like?
``` javascript
{
...
sorter:true,
sorted:true // 受控的排序字段，高亮样式
}
```

**Comment by afc163** [comment] 2018-09-08 14:47
Duplicate of #10946

**Closed by afc163** 2018-09-08 14:47 UTC
