### ISSUE TITLE
react18 StrictMode模式下 Layout Sider  收起状态下移动到 Menu 任一节点异常

### ISSUE THREAD

**Issue by wanghui94** [ant-design/ant-design#36141] opened 2022-06-21 01:51 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/affectionate-wu-4nk9pi?file=/src/App.tsx)

### Steps to reproduce

1. 点击 展开/收缩 按钮
2. 鼠标移动到左侧菜单选项一
3. 查看控制台异常信息

### What is expected?

React 18 StrictMode 模式下，无异常信息

### What is actually happening?

React 18 StrictMode 模式下异常

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | react@18.2.0 |
| System | macOS 12.4 |
| Browser | Chrome 102.0.5005.115 |

**Comment by afc163** [comment] 2022-06-21 02:11
Duplicate of #35361

**Closed by afc163** 2022-06-21 02:11 UTC
