### ISSUE TITLE
InputNumber onChange not fired if one digit in input and backspace is hit 

### ISSUE THREAD

**Issue by sandeshbagade** [ant-design/ant-design#30318] opened 2021-04-26 18:13 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-rwjyf)

### Steps to reproduce
1.Just create a component having  <InputNumber value={state} onChange={(e)=>{setState (e); console.log (e}} />
2. Type something and then start doing backspace. Notice the onchange not called for last backspace

### What is expected?
It should call onChnage with empty value 

### What is actually happening?
Onchange not called for last backspace. i.e when input gets empty

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 16.14.0 |
| System | Ubuntu 18.04 |
| Browser | Chrmoe |

**Comment by afc163** [comment] 2021-04-27 06:26
Duplicate of #30096

**Closed by afc163** 2021-04-27 06:26 UTC
