### ISSUE TITLE
Select with React 18

### ISSUE THREAD

**Issue by MalekBouba** [ant-design/ant-design#34815] opened 2022-03-31 11:37 UTC
### Reproduction link

[https://stackblitz.com/edit/react-bwwwus-uzrch6](https://stackblitz.com/edit/react-bwwwus-uzrch6)

### Steps to reproduce

Put a <Select/> component inside a React18 app (CRA)

### What is expected?

Normal behavior.

### What is actually happening?

- Select options do not appear.
- Freezing & crash.

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | 18 |
| System | MacOS |
| Browser | Safari |

**Comment by afc163** [comment] 2022-03-31 14:16
Duplicate of #34805

**Closed by afc163** 2022-03-31 14:16 UTC
