### ISSUE TITLE
当table其中一列指定fixed，且table设置scroll.y后，会出现表头闪动问题

### ISSUE THREAD

**Issue by idujiawei** [ant-design/ant-design#51051] opened 2024-09-27 09:46 UTC
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/vitejs-vite-x6fr7d?file=src%2FApp.tsx)

### Steps to reproduce

点击示例刷新按钮

![image](https://github.com/user-attachments/assets/d112a2cf-8729-46d8-9631-509f888e2d8d)

### What is expected?

列表头不闪动

### What is actually happening?

首次加载会出现闪动

![image](https://github.com/user-attachments/assets/cb387b68-6ee7-4b17-9000-e7165c4df6d1)

| Environment | Info |
| --- | --- |
| antd | 5.21.1 |
| React | 18.3.1 |
| System | mac  |
| Browser | chrome |

**Comment by afc163** [comment] 2024-09-27 10:51
Duplicate of https://github.com/ant-design/ant-design/issues/49099

**Closed by afc163** 2024-09-27 10:51 UTC
Labels: unconfirmed
