### ISSUE TITLE
Tooltip don't disappear when triggered by a disabled Button

### ISSUE THREAD

**Issue by gabriel-naressi** [ant-design/ant-design#20739] opened 2020-01-07 14:02 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nkwv5l9k40)

### Steps to reproduce
Pass mouse over "test" the button, then mouse out

### What is expected?
Tooltip close

### What is actually happening?
Tooltip remains open

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | 16.12.0 |
| System | Ubuntu 19.04 |
| Browser | Google Chrome 79.0.3945.88 |

**Comment by afc163** [comment] 2020-01-07 15:16
Duplicate of #9581

**Closed by afc163** 2020-01-07 15:16 UTC

**Comment by gabriel-naressi** [comment] 2020-01-07 19:53
@afc163 the solution of styled components does not work for me

**Comment by afc163** [comment] 2020-01-08 01:50
https://codesandbox.io/s/l5qpjp2k4z

It works on my chrome.
