### ISSUE TITLE
TimePicker for millisecond

### ISSUE THREAD

**Issue by AlisaBen** [ant-design/ant-design#20335] opened 2019-12-18 12:11 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Refinne the time granularity.
When used as a performance improvement tool, I need to refine the amount of data in time latitudes.

### What does the proposed API look like?
add a column for selection of millisecond

**Comment by yoyo837** [comment] 2019-12-18 12:13
Millisecond values ​​may be fine for developers, but not necessarily for users I think.

**Comment by AlisaBen** [comment] 2019-12-18 12:42
> Millisecond values ​​may be fine for developers, but not necessarily for users I think.
maybe unnecessary for ordinary users, while the users of a performance improvement tool are developers

**Comment by afc163** [comment] 2019-12-19 04:49
Duplicate of #16466

**Closed by afc163** 2019-12-19 04:49 UTC
