### ISSUE TITLE
add support for luxonjs 2.0

### ISSUE THREAD

**Issue by pdeva** [ant-design/ant-design#31439] opened 2021-07-18 02:09 UTC
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently AntD only supports LuxonJS 1.0.
LuxonJS 2.0 has many breaking changes. please add support for it.
https://moment.github.io/luxon/#/upgrading

### What does the proposed API look like?
the antd api shouldn't need to change by supporting luxonjs 2.0

**Comment by afc163** [comment] 2021-08-24 11:43
Duplicate of #29710

**Closed by afc163** 2021-08-24 11:43 UTC
Labels: help wanted
