### ISSUE TITLE
drawer 在 getContainer={false} 两种共存时不清除 overflow: hidden

### ISSUE THREAD

**Issue by jljsj33** [ant-design/ant-design#24821] opened 2020-06-08 06:44 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/drawer-cn/](https://ant.design/components/drawer-cn/)

### Steps to reproduce
打开 《渲染在当前 DOM 》的 drawer 后再打开第一个，再关闭。。

### What is expected?
-

### What is actually happening?
-

| Environment | Info |
|---|---|
| antd | undefined |
| React | last |
| System | osx  |
| Browser | chrome |

**Comment by afc163** [comment] 2020-06-08 07:25
Duplicate of #21539

**Comment by jljsj33** [comment] 2020-06-08 08:47
不是同一个问题

**Comment by jljsj33** [comment] 2020-06-08 14:21
这问题修不修？？？@afc163

**Comment by afc163** [comment] 2020-06-08 14:22
修啊

**Comment by jljsj33** [comment] 2020-06-08 14:33
有点不敢修，，修了怕又出来个坑。。。

**Comment by jljsj33** [comment] 2020-06-08 14:39
rc-drawer v4.1.0

**Closed** 2020-06-08 14:38 UTC

**Comment by jljsj33** [comment] 2020-06-08 14:40
@afc163 https://github.com/ant-design/ant-design/blob/master/package.json#L122, 这里自已改下
