### ISSUE TITLE
Typography copy, edit and expand node should not trigger ellipsis tooltip

### ISSUE THREAD

**Issue by dengfuping** [ant-design/ant-design#51692] opened 2024-11-19 07:34 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/typography-ellipsis-tooltip-hw7dzm?file=%2Fdemo.tsx)

### Steps to reproduce

View the demo.

### What is expected?

should just trigger edit tooltip, not including ellipsis tooltip.
![image](https://github.com/user-attachments/assets/23c9082a-c475-4a2e-a947-5f8123c909f8)

### What is actually happening?

trigger edit tooltip and ellipsis tooltip both.
![image](https://github.com/user-attachments/assets/507f7de7-cff9-4c60-b958-89673c02ab5a)

| Environment | Info |
| --- | --- |
| antd | 5.22.1 |
| React | 18.3.1 |
| System | MacOS |
| Browser | Chrome 120.0.6099.225 |

**Comment by afc163** [comment] 2024-11-19 09:48
Duplicate of #48733

**Closed by afc163** 2024-11-19 09:48 UTC
Labels: unconfirmed
