### ISSUE TITLE
Why not  export every ts type in d.ts file?

### ISSUE THREAD

**Issue by linmodev** [ant-design/ant-design#8328] opened 2017-11-27 07:23 UTC
### What problem does this feature solve?
I use typescript in my project, so I need to use some of the types exported in the declaration file. But at the moment it seems that only some components have been exported and no other types have been exported

### What does the proposed API look like?
I hope to export all the useful type information

**Comment by yesmeck** [comment] 2017-11-27 07:24
Duplicate of #6593

**Closed by yesmeck** 2017-11-27 07:24 UTC
