### ISSUE TITLE
Handle responsive use cases for all types of datepickers

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#47691] opened 2024-03-03 18:34 UTC
### What problem does this feature solve?

It ll make datepickers more useable in a mobile view.

### What does the proposed API look like?

Have a new props called modal={true} which will open the datepicker in a modal

**Comment by afc163** [comment] 2024-03-04 03:18
Duplicate of https://github.com/ant-design/ant-design/issues/26758

**Closed by afc163** 2024-03-04 03:18 UTC
Labels: unconfirmed

**Comment by AsuraKev** [comment] 2024-03-04 03:50
@afc163   It is indeed a duplicate. But there’s no formal fix for this tho. The Datepicker RFC was suppose to address this one from last time what they said
