### ISSUE TITLE
Dropdown and Popconfirm don't work properly in a fixed column of Table

### ISSUE THREAD

**Issue by Ustimov** [ant-design/ant-design#21266] opened 2020-02-06 19:32 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-cyf7b)

### Steps to reproduce
1. Move your mouse over the Open button
2. Click Item2 in the Dropdown
3. Try to click OK in the Popconfirm

### What is expected?
The Popconfirm shouldn't disappear until the OK (or Cancel) button is clicked and the Dropdown shouldn't appear while the Popconfirm is open

### What is actually happening?
The Popconfirm and the Dropdown randomly appear and disappear

| Environment | Info |
|---|---|
| antd | 3.26.8 |
| React | 16.12 |
| System | macOS Catalina Version 10.15.3 |
| Browser | Google Chrome Version 79.0.3945.130 (Official Build) (64-bit) |

**Comment by afc163** [comment] 2020-02-07 02:46
Duplicate of #9262

And you can try antd@4.0.0-rc.3

**Closed by afc163** 2020-02-07 02:46 UTC

**Comment by Ustimov** [comment] 2020-02-11 16:00
> Duplicate of #9262
> 
> And you can try antd@4.0.0-rc.3

In version 4 it's way worst. Ok, I will try to fix it on my own.

**Comment by Even-Lau** [comment] 2020-03-26 06:12
> > Duplicate of #9262
> > And you can try antd@4.0.0-rc.3
> 
> In version 4 it's way worse. Ok, I will try to fix it on my own.

I got the same issue. Have you fixed it yet? @Ustimov 
It's a bug unfixed, please reopen it. @afc163

**Comment by Ustimov** [comment] 2020-03-26 08:21
> > > Duplicate of #9262
> > > And you can try antd@4.0.0-rc.3
> > 
> > 
> > In version 4 it's way worse. Ok, I will try to fix it on my own.
> 
> I got the same issue. Have you fixed it yet? @Ustimov
> It's a bug unfixed, please reopen it. @afc163

As a workaround I wrapped the whole Dropdown in the Popconfirm instead of just Menu.Item contents. It requires a little bit more code, but at least it works. Here is a sample: [https://codesandbox.io/s/antd-bug-n9tft](https://codesandbox.io/s/antd-bug-n9tft).

**Comment by pahaz** [comment] 2020-07-03 13:54
There is a problem with ant v4 too

**Comment by palkim** [comment] 2022-04-28 07:21
> > > > Duplicate of #9262
> > > > And you can try antd@4.0.0-rc.3
> > > 
> > > 
> > > In version 4 it's way worse. Ok, I will try to fix it on my own.
> > 
> > 
> > I got the same issue. Have you fixed it yet? @Ustimov
> > It's a bug unfixed, please reopen it. @afc163
> 
> As a workaround I wrapped the whole Dropdown in the Popconfirm instead of just Menu.Item contents. It requires a little bit more code, but at least it works. Here is a sample: https://codesandbox.io/s/antd-bug-n9tft.

nice workaround thanks
