### ISSUE TITLE
safari 浏览器下 FormItem help 信息展示问题

### ISSUE THREAD

**Issue by yvanwangl** [ant-design/ant-design#20604] opened 2020-01-02 10:13 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/](https://ant.design/components/form/)

### Steps to reproduce
1.切换至中文输入法    2.选择代码演示/Username输入框  3. 输入任意字符，按空格键

### What is expected?
不会出现提示信息的闪现

### What is actually happening?
提示信息 Please input your username 会闪现一下然后消失，该现象在 chrome 浏览器下不会出现
![antd](https://user-images.githubusercontent.com/11405052/71662155-7aabb980-2d8b-11ea-9e59-f3672f490c17.png)

| Environment | Info |
|---|---|
| antd | 3.26.5 |
| React | 16.5.2 |
| System | 10.13.6 |
| Browser | safari 13.0.3 |

---
经过初步debug发现，在safari浏览器下会生成一个 `<div class="ant-form-explain">Please input your username</div>`节点，但是其父节点却包含了 has-success 的 class，但是该节点应该是在字段校验失败的时候出现的，所以会闪现

**Comment by afc163** [comment] 2020-01-02 10:30
Duplicate of #19944

**Closed by afc163** 2020-01-02 10:30 UTC
