### ISSUE TITLE
使用antd的Table、Select等组件在IE浏览器内页面滚动时会闪屏

### ISSUE THREAD

**Issue by xiaozhezhe** [ant-design/ant-design#30792] opened 2021-05-31 08:59 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/select-cn/](https://3x.ant.design/components/select-cn/)

### Steps to reproduce
在IE浏览器运行react antd项目时，滚动页面会出现闪屏情况

### What is expected?
IE浏览器不闪屏

### What is actually happening?
在滚动的时候会闪屏

| Environment | Info |
|---|---|
| antd | 3.26.16 |
| React | 16.8.0 |
| System | windows 10 |
| Browser | Internet Explorer 11 |

---
使用Select作为查询条件的页面同时有Table组件，在滚动的时候会有闪屏的情况

**Comment by xrkffgg** [comment] 2021-05-31 09:27
Duplicate of https://github.com/ant-design/ant-design/issues/21039

**Closed by xrkffgg** 2021-05-31 09:27 UTC
Labels: IE | Firefox | Safari, Internet Explorer
