### ISSUE TITLE
官网点击动不了了，赶紧修改发布新版啊！

### ISSUE THREAD

**Issue by weixiaoyi** [ant-design/ant-design#26355] opened 2020-08-24 02:18 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
官网打开就动不了

### What is expected?
恢复正常

### What is actually happening?
报错，控制台报错

| Environment | Info |
|---|---|
| antd | 4.6.0 |
| React | 16.13 |
| System | windows |
| Browser | chrme |

**Comment by afc163** [comment] 2020-08-24 02:24
Duplicate of #26353

**Closed by afc163** 2020-08-24 02:24 UTC
