### ISSUE TITLE
[DraggableTree] Hover style apply to a wrong node after dropping

### ISSUE THREAD

**Issue by AlanCutFlim** [ant-design/ant-design#27764] opened 2020-11-13 13:12 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-cn/#components-tree-demo-draggable](https://ant.design/components/tree-cn/#components-tree-demo-draggable)

### Steps to reproduce

- Enter the link, and find the draggable tree demo
- Drag a treeNode and drop it in the same level depth
- To prevent extra impact, keep your mouse still when you drop

### What is expected?
Hover style apply to the treeNode we just dropped, because our mouse stay the same position

### What is actually happening?
Hover style apply to the wrong node. If you wait a second, it will also display a wrong title tooltip which is also shown in the GIF
![wrong22](https://user-images.githubusercontent.com/50612752/99075187-05885200-25f4-11eb-85b9-d1b7a510c771.gif)

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | react 16.14.0 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 86.0.4240.111 |

---
NOTICE:
- **This problem may not always happen** (currently i don't know why). But once you run into it, it will very likely happen in the following try
- If you can't reproduce it, please create another tab and try again
- Sometimes the hover style will apply correctly as we expected, and then it will always be correct
![correct222](https://user-images.githubusercontent.com/50612752/99074893-88f57380-25f3-11eb-8c95-8cbd070c8249.gif)

**Comment by afc163** [comment] 2020-11-13 16:15
Duplicate of #27692

**Closed by afc163** 2020-11-13 16:15 UTC
