### ISSUE TITLE
table组件开启虚拟滚动后表头和表体错位

### ISSUE THREAD

**Issue by mk39481024** [ant-design/ant-design#51825] opened 2024-11-29 00:49 UTC
### Reproduction link

[https://ant.design/components/table-cn#table-demo-virtual-list](https://ant.design/components/table-cn#table-demo-virtual-list)

### Steps to reproduce

官网虚拟列表例子就能重现出bug, 在windows11 chrome131 环境下横向来回拉滚动条就会出现, mac电脑没这问题
![088086de0510d1ba9e79](https://github.com/user-attachments/assets/7c5c3c00-5c74-49bb-82f9-8f20a0ad1c98)

### What is expected?

table表头和表体对齐

### What is actually happening?

table表头和表体不对齐

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 18.2.0 |
| System | windows 11 |
| Browser | chrome 131 |

**Comment by afc163** [comment] 2024-11-29 01:58
Duplicate of https://github.com/ant-design/ant-design/issues/45524

**Closed by afc163** 2024-11-29 01:58 UTC
Labels: unconfirmed
