### ISSUE TITLE
v4 AutoComplete cannot use custom Options with Custom Input

### ISSUE THREAD

**Issue by N00nDay** [ant-design/ant-design#26195] opened 2020-08-13 14:31 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/laughing-cherry-p143h?file=/index.js)

### Steps to reproduce
Add `AutoComplete` with custom `Input` (in this case `TextArea`) and custom `Option`s (in this case utilizing `Select.OptGroup`)

### What is expected?
To see custom `Input` and upon typing the custom `Input` remains and the drop down shows the `Option`s

### What is actually happening?
Custom `Input` shows on initial render but once you start typing the `Input` is replaced by generic `Input` and no `Option`s show

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.12.0 |
| System | Mac Catalina 10.15.5 |
| Browser | Chrome 83.0.4103.116 |

---
I can use this structure to do one or the other, custom `Input` or custom `Option`s but not both. I can use `dataSource` to achieve the desired effect but as that is being deprecated we need a more permanent solution for this.

Here is my attempt to use `options`:
https://codesandbox.io/s/youthful-lichterman-pcxq6?file=/index.js

Here is the working version utilizing `dataSource`:
https://codesandbox.io/s/lively-morning-xgigv

Looking at the source code for `AutoComplete` it assumes if there is more than 1 child it could only be Options. Source code shown below: 

```
}); // ============================= Input =============================

  var customizeInput;

  if (childNodes.length === 1 && isValidElement(childNodes[0]) && !isSelectOptionOrSelectOptGroup(childNodes[0])) {
    var _childNodes = _slicedToArray(childNodes, 1);

    customizeInput = _childNodes[0];
  }

  var getInputElement = function getInputElement() {
    return customizeInput;
  }; // ============================ Options ============================


  var optionChildren; // [Legacy] convert `children` or `dataSource` into option children

  if (childNodes.length && isSelectOptionOrSelectOptGroup(childNodes[0])) {
    optionChildren = children;
  } else {
```

I have fixed this issue by altering the code to this:
```
}); // ============================= Input =============================

  var customizeInput;

  if (childNodes.length && isValidElement(childNodes[0]) && !isSelectOptionOrSelectOptGroup(childNodes[0])) {
    console.log('childNodes', childNodes)
    var _childNodes = _slicedToArray(childNodes, 1);
    console.log('childNodes', _childNodes)

    customizeInput = _childNodes[0];
  } else if (childNodes.length && isValidElement(childNodes[childNodes.length - 1]) && !isSelectOptionOrSelectOptGroup(childNodes[childNodes.length - 1])) {
    var _childNodes = _slicedToArray(childNodes, 1);

    customizeInput = _childNodes[_childNodes.length - 1];
  }

  var getInputElement = function getInputElement() {
    return customizeInput;
  }; // ============================ Options ============================


  var optionChildren; // [Legacy] convert `children` or `dataSource` into option children

  if (childNodes.length && isSelectOptionOrSelectOptGroup(childNodes[0])) {
    optionChildren = children[0];
  } else if (childNodes.length > 1 && isSelectOptionOrSelectOptGroup(childNodes[1])) {
    optionChildren = children[1];
  } else {
```
This code allows you to place a custom `Input` and custom `Option`s as children to the `AutoComplete` and the `Input` can be first or last. Not sure if this is the most elegant approach but it seems to be working.  Anyway to add this so we can finally get away from `dataSource`?

**Comment by afc163** [comment] 2020-08-14 03:32
Duplicate of #23941

**Closed by afc163** 2020-08-14 03:32 UTC
