### ISSUE TITLE
antd4.3的Select组件聚焦不了

### ISSUE THREAD

**Issue by Shujunhuai** [ant-design/ant-design#24919] opened 2020-06-11 09:31 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/#API](https://ant.design/components/select-cn/#API)

### Steps to reproduce
给Select加autoFocus属性为true

### What is expected?
聚焦可以看到光标

### What is actually happening?
没有光标，也没有下拉，但是有聚焦的样式

| Environment | Info |
|---|---|
| antd | 4.3.2 |
| React | react |
| System | window |
| Browser | 谷歌 |

![image](https://user-images.githubusercontent.com/49665926/84369387-53de9280-ac09-11ea-865e-f381ec1785e4.png)

**Comment by afc163** [comment] 2020-06-11 10:01
Duplicate of #14503

**Closed by afc163** 2020-06-11 10:01 UTC
Labels: 🤔 Need Reproduce
