### ISSUE TITLE
Adding className to Carousel component adds that class to a child element

### ISSUE THREAD

**Issue by simon-fraser** [ant-design/ant-design#12138] opened 2018-09-07 13:03 UTC
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.0

### Environment
OSX 10.13.6, Chrome Version 68.0.3440.106

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kok6o674w3)

### Steps to reproduce
Create a new `Carousel` component and attempt to give it a new css class using the `className` attribute.

### What is expected?
The Carousel's wrapping element (`class="ant-carousel"`) in the DOM should have an additional class.

### What is actually happening?
The Carousel's wrapping element does not have a new css class instead the new css class is appearing on the slider element inside (`class="slick-slider new-class slick-initialized"`)

**Comment by supra28** [comment] 2018-09-07 18:03
@simon-fraser This seems to be the expected behaviour, its transferring all the classNames to the react-slick component that expects it.
I can use `prefixCls` prop to do what you are trying to do.
Like this :
`<Carousel prefixCls="ant-carousel new-class">`

**Comment by zombieJ** [comment] 2018-09-09 08:44
Since internal using `react-slick`, antd pass the `className` to child component.
It's little strange, but we may not modify this since this exists long time.

**Closed by zombieJ** 2018-09-09 08:44 UTC

**Comment by simon-fraser** [comment] 2018-09-10 15:16
Thank you @supra28 I had not looked too closely to the component code, and thusly did not see the prefixCls property.  
I recommend adding to the docs in that case. [https://ant.design/components/carousel/](https://ant.design/components/carousel/)
