### ISSUE TITLE
表格table

### ISSUE THREAD

**Issue by AceSelena** [ant-design/ant-design#27833] opened 2020-11-17 09:44 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
table中dataSource值为true或者false时，表格内容不显示

### What is expected?
table中dataSource值为true或者false时，表格内容显示true,false

### What is actually happening?
table中dataSource值为true或者false时，表格内容不显示

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 16 |
| System | windows |
| Browser | chrome 86.0.4240.193 |

**Comment by yoyo837** [comment] 2020-11-17 10:32
你指的是value是boolean类型？这不是table本身的问题吧，React就是这样，你可以加render toString()处理

**Comment by afc163** [comment] 2020-11-17 10:44
Duplicate of #24427

**Closed by afc163** 2020-11-17 10:44 UTC
Labels: 🤔 Need Reproduce
