### ISSUE TITLE
文档demo，当上传照片数到达限制后，上传按钮不消失，上传失败

### ISSUE THREAD

**Issue by panmenglin** [ant-design/ant-design#14802] opened 2019-02-12 15:37 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
右侧第2个例子，上传三张图片，上传按钮应该消失，实际第三张图片上传失败

### What is expected?
图片上传成功，上传按钮消失

### What is actually happening?
最后一张图片无法上传

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | 16.7.0 |
| System | maxos |
| Browser | chrome 71.0.3578.98 |

**Comment by wangmengyi1009** [comment] 2019-02-13 02:19
同样遇到了这个问题

**Comment by afc163** [comment] 2019-02-13 02:34
Fixed in https://github.com/ant-design/ant-design/pull/14780

**Comment by afc163** [comment] 2019-02-13 02:34
Duplicate of #14779

**Closed by afc163** 2019-02-13 02:34 UTC
