### ISSUE TITLE
[Input] 是否应该去除对正在输入的字符长度计算？

### ISSUE THREAD

**Issue by stygian-desolator** [ant-design/ant-design#27637] opened 2020-11-08 09:43 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://64v2o.csb.app/](https://64v2o.csb.app/)

### Steps to reproduce
任意输入一段中文字符

### What is expected?
输入中文字符时，会有字符组合的阶段，这个阶段输入的字符应该不被计算为实际输入，等到实际输入完成后，再将结果计算为实际输入的字符
![image](https://user-images.githubusercontent.com/73412177/98461760-dc2d8780-21e9-11eb-88dd-02a5e0d48610.png)

### What is actually happening?
将组合阶段的字符也计算为输入字符

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | react |
| System | Mac OS |
| Browser | Chrome |

**Comment by afc163** [comment] 2020-11-09 03:04
Duplicate of #27116

**Closed by afc163** 2020-11-09 03:04 UTC
