### ISSUE TITLE
有计划在input组件支持inputmask么?

### ISSUE THREAD

**Issue by okool** [ant-design/ant-design#25255] opened 2020-06-28 09:31 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
支持掩码,格式化文本内容. 如:身份证号,区号,坐标,ip地址,mac地址等等.

### What does the proposed API look like?
参考: https://github.com/insin/react-maskedinput

**Comment by afc163** [comment] 2020-06-28 12:51
Duplicate of #23201

**Closed by afc163** 2020-06-28 12:51 UTC
