### ISSUE TITLE
Select下拉菜单数据设置为8条，滚动条无法滚动

### ISSUE THREAD

**Issue by bihongbin3027** [ant-design/ant-design#27393] opened 2020-10-27 06:50 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biaodanchicun-ant-design-demo-forked-9t7si?file=/index.js)

### Steps to reproduce
打开上面链接重现

### What is expected?
希望滚动条正常

### What is actually happening?
滚动条无法滚动

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.13.1 |
| System | window 10 |
| Browser | chrome 83.0.4103.61 |

**Comment by yoyo837** [comment] 2020-10-27 06:52
ref: #27282

**Comment by afc163** [comment] 2020-10-27 06:57
Duplicate of #27374

**Closed by afc163** 2020-10-27 06:57 UTC
