### ISSUE TITLE
getFieldError does not work well when validateTrigger is set to onBlur

### ISSUE THREAD

**Issue by nameishari** [ant-design/ant-design#31338] opened 2021-07-09 19:32 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-lbn0d?file=/index.js)

### Steps to reproduce
1) Create a normal form with an input field wrapped in a form item.
2) Make sure that a validation rule is set and validationTrigger is set to onBlur
3) Enter a value in input field and come out of the input box (which triggers onBlur event)
4) Now try to access getFieldError value. It will return empty array. 

I noticed that getFieldError will return a valid result only when user in the field (onFocus) --- T**his is true only when validateTrigger is set to onBlur**

### What is expected?
getFieldError() should return proper value on onBlur

### What is actually happening?
getFieldError() returns empty array on onBlur.

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17.0.2 |
| System | macOS Big Sur 11.3.1 |
| Browser | Chrome Version 91.0.4472.114 |

---
**Note:** Basically,  when user left the field, i need to know if an input field is valid or not. So i can do additional styling and show some additional content. I have found a workaround for my problem. I set validateTrigger to false and trigger validation on onBlur manually by calling form.validateFields.
 
```
  const onBlur
      = (validateFields: ValidateFields<any>) =>  {
    if (rules) {
      validateFields([name])
        .then(() => setInvalid(false))
        .catch(() => setInvalid(true))
    }
  }
```

**Comment by afc163** [comment] 2021-07-12 03:07
Duplicate of #28378

**Closed by afc163** 2021-07-12 03:07 UTC

**Comment by linqian02** [comment] 2021-07-12 08:56
The same problem, but still did not find a solution
