### ISSUE TITLE
Please let me know how to make the basic example of tree select(https://3x.ant.design/components/tree-select/#header) to incorporate search box in input box same like multiple select

### ISSUE THREAD

**Issue by habeebahmed** [ant-design/ant-design#23489] opened 2020-04-22 09:03 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
@afc163 I was talking about v3 tree select where I can get searchbox inline just as like tree select in v4
I can't upgrade to v4 due to dependency 
So I think v3 won't have that feature?

V4 tree select 
![image](https://user-images.githubusercontent.com/36078669/79962094-43c9f280-84a5-11ea-8056-5b191216bf95.png)

V3 tree select
![image](https://user-images.githubusercontent.com/36078669/79962171-5d6b3a00-84a5-11ea-9fe9-24ab2ee4034f.png)

my requirement is to make searchbox inline similar to V4 which should work in V3

### What does the proposed API look like?
I think adding an option to toggle search box inline or in dropdown can work

**Comment by afc163** [comment] 2020-04-22 09:04
Duplicate of #23486

**Closed by afc163** 2020-04-22 09:04 UTC
