### ISSUE TITLE
Ant Menu and sub menus are not keyboard accessible

### ISSUE THREAD

**Issue by yuvrajsawant-github** [ant-design/ant-design#24880] opened 2020-06-09 17:29 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/23oxp)

### Steps to reproduce
1. Open above sandbox url
2. Use tab key of keyboard to navigate menus and sub menus 
3. It seems that unable to navigate to menu and sub menus using key board
4. Menu and sub menus should be accessible through keyboard 

### What is expected?
 Menu and sub menu should be accessible through keyboard 

### What is actually happening?
 It seems that unable to navigate to menu and sub menus using key board, please check.

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Edge Version 81.0.416.72 (Official build) (64-bit) or Chorme Version 81.0.4044.138 (Official Build) (64-bit) |

**Comment by afc163** [comment] 2020-06-10 02:42
Duplicate of #14356

**Closed by afc163** 2020-06-10 02:42 UTC
