### ISSUE TITLE
Support hover action on TreeNode of TreeView component

### ISSUE THREAD

**Issue by vucuongkg** [ant-design/ant-design#37571] opened 2022-09-16 02:08 UTC
### What problem does this feature solve?

When user hover treenode, component show buttons. It's nice UI/UX. Thanks

### What does the proposed API look like?

Feature request

**Comment by vucuongkg** [comment] 2022-09-16 02:10
I have found similar: https://github.com/ant-design/ant-design/issues/11668

**Comment by afc163** [comment] 2022-09-16 03:41
Duplicate of https://github.com/ant-design/ant-design/issues/11668

**Closed by afc163** 2022-09-16 03:41 UTC
