### ISSUE TITLE
antd的table大数据量渲染很卡顿，希望增加虚拟表格的渲染，或者提供下解决方案谢谢

### ISSUE THREAD

**Issue by jsonshao** [ant-design/ant-design#17562] opened 2019-07-10 03:06 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ctq123/ant-virtual-table 希望像这样的虚拟渲染，目前遇到的问题是antd的table很卡](https://github.com/ctq123/ant-virtual-table 希望像这样的虚拟渲染，目前遇到的问题是antd的table很卡)

### Steps to reproduce
大量数据渲染卡顿

### What is expected?
希望增加虚拟表格的渲染，或者提供下解决方案谢谢

### What is actually happening?
大数据表格渲染很卡

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.8.6 |
| System | window |
| Browser | chrome |

**Comment by afc163** [comment] 2019-07-10 04:04
Duplicate of #10431

**Closed by afc163** 2019-07-10 04:04 UTC

**Comment by Xutaotaotao** [comment] 2019-12-24 13:03
https://autodesk.github.io/react-base-table/
