### ISSUE TITLE
[Select] multiple Select will auto close drop down menu when Select is inside Radio

### ISSUE THREAD

**Issue by yingpengsha** [ant-design/ant-design#28232] opened 2020-12-07 06:12 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/white-microservice-68kkk?file=/index.js)

### Steps to reproduce
click Select when Select is inside Radio

### What is expected?
drop down menu won't auto close

### What is actually happening?
drop down menu will auto close

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17.0.1 |
| System | window 10 |
| Browser | chrome 87.0.4280.88 |

**Comment by zombieJ** [comment] 2020-12-07 08:33
Duplicate of #25959

**Closed by zombieJ** 2020-12-07 08:33 UTC
