### ISSUE TITLE
can't open https://ant.design/index-cn

### ISSUE THREAD

**Issue by Alex121** [ant-design/ant-design#7899] opened 2017-10-16 12:03 UTC
### Version
2.13.6

### Environment
chrome

### Reproduction link
[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce
浏览器访问 https://ant.design/index-cn

### What is expected?
正常打开页面

### What is actually happening?
无响应

**Comment by afc163** [comment] 2017-10-16 12:09
Duplicate of #7895

**Closed by afc163** 2017-10-16 12:09 UTC
