### ISSUE TITLE
ConfigProvider配置国际化错误

### ISSUE THREAD

**Issue by snoopy1412** [ant-design/ant-design#27662] opened 2020-11-09 14:00 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-9ewwq?file=/index.js)

### Steps to reproduce
```
import React from "react";
import { ConfigProvider, Modal } from "antd";
import zhCN from "antd/lib/locale/zh_CN";
import moment from "moment";
import "moment/locale/zh-cn";
import "antd/dist/antd.css";
import "./index.css";

moment.locale("zh-cn");

const App = () => {
  const handleClick = () => {
    Modal.confirm({
      title: "第一次是中文的，点击取消后就变成了英文按钮",
    });
  };
  return (
    <ConfigProvider locale={zhCN}>
      <div style={{ width: 400, margin: "100px auto" }}>
        <div style={{ marginTop: 16 }}>
          <button onClick={handleClick}>按钮</button>
        </div>
      </div>
    </ConfigProvider>
  );
};
export default App;

```

### What is expected?
期望 Modal.confirm 的 两个按钮均为中文

### What is actually happening?
第一次为取消，确认，点击取消后，再次唤起Modal,  变成了cancel 和 ok

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 17.0.1 |
| System | macOS 10.14.6 |
| Browser | chrome 86.0.4240.183 |

**Comment by xrkffgg** [comment] 2020-11-10 01:06
Duplicate of https://github.com/ant-design/ant-design/issues/27597

**Closed by xrkffgg** 2020-11-10 01:06 UTC

**Comment by Reviewlike** [comment] 2022-05-23 01:42
国际化使用中文，其余组件都正常，Modal.confirm()触发时弹窗为中文，当触发了非Modal.confirm()事件的弹窗后，再触发Modal.confirm()的弹窗onText变英文。
