### ISSUE TITLE
TimePicker时间选择框设置属性会导致样式不正确。

### ISSUE THREAD

**Issue by liuxuehuax** [ant-design/ant-design#35521] opened 2022-05-12 11:34 UTC
### Reproduction link

[https://codepen.io/liuxuehuax/pen/dydpOEK](https://codepen.io/liuxuehuax/pen/dydpOEK)

### Steps to reproduce

任意添加TimePicker.RangePicker的属性（例如：placeholder）。在首次进入页面，点击时间框 =》下拉时间选择框就会错位。

### What is expected?

下拉时间选择框能够正常展示。

### What is actually happening?

下拉时间选择框错位。

| Environment | Info |
| --- | --- |
| antd | 4.20.4 |
| React | 16.14.0 |
| System | mac && windows |
| Browser | chrome 100.0.4896.127 |

**Comment by liuxuehuax** [comment] 2022-05-12 11:35
![image](https://user-images.githubusercontent.com/54133566/168065786-62899656-99f2-4521-b09d-08b4f2902c77.png)

**Comment by liuxuehuax** [comment] 2022-05-12 11:36
![image](https://user-images.githubusercontent.com/54133566/168065994-441ca611-c1e5-42c0-b830-3fdd23ccbb9f.png)

**Comment by MadCcc** [comment] 2022-05-12 11:37
Duplicate of https://github.com/ant-design/ant-design/issues/35247

**Closed by MadCcc** 2022-05-12 11:37 UTC
