### ISSUE TITLE
validateFirst 影响 form 方法 validateFields 回调

### ISSUE THREAD

**Issue by For-me** [ant-design/ant-design#26118] opened 2020-08-10 10:40 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/autumn-night-j8i6s?file=/index.js)

### Steps to reproduce
切换demo中的select，看console里的打印值，在有validateFirst的情况下，总是走到then的逻辑，没有的情况会走到catch逻辑

### What is expected?
无论是否有validateFirst，校验出错都应该走到catch逻辑

### What is actually happening?
有validateFirst，校验出错走到then逻辑

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 16 |
| System | mac |
| Browser | Chrome84 |

**Comment by afc163** [comment] 2020-08-10 10:47
Duplicate of #25971

**Closed** 2020-08-11 08:51 UTC
