### ISSUE TITLE
[TreeSelect] Improper interaction when fold the parent tree nodes.

### ISSUE THREAD

**Issue by Coodool** [ant-design/ant-design#6451] opened 2017-06-13 04:10 UTC
### Version
2.11.0

### Environment
null

### Reproduction link
[https://ant.design/components/tree-select-cn/#components-tree-select-demo-checkable](https://ant.design/components/tree-select-cn/#components-tree-select-demo-checkable)

### Steps to reproduce
As you know, the TreeSelect dropdown list will popup upward when there is no enough space laying a long dropdown list under the input area which usually caused by a minor viewport. 
- You can **resize your browser window** and **scroll down until the TreeSelect near the bottom of the window**. 
- Click the input area to popup the dropdown list. Then click on the parent tree node and you can find the improper interaction as below.

![reproduce the issue](https://user-images.githubusercontent.com/20887105/27064875-38ca98e0-502c-11e7-832e-daa58ff2500b.gif)

### What is expected?
Dropdown list clinging to the input area.

### What is actually happening?
Vertical clearance between the input area and the folded dropdown list.

**Comment by yesmeck** [comment] 2017-06-13 06:54
Duplicate of #6451

**Closed** 2017-06-13 06:56 UTC
