### ISSUE TITLE
Can fields be just validated(), without showing errMsgs and changing style?

### ISSUE THREAD

**Issue by cyndra0** [ant-design/ant-design#28198] opened 2020-12-04 08:20 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前调用 formInstance.validateFields() 会触发 UI 的变化，但应该会有只想验证而不想让验证结果被用户感知的场景，是不是可以考虑把验证过程和验证结果UI分离呢？

### What does the proposed API look like?
1.  add new property on Form, something like noValidateStyle?: boolean，hide error styles when validating
or 2. formInstance.validateFields(nameList, noStyle?:boolean)

**Comment by afc163** [comment] 2020-12-04 08:58
Duplicate of #25993

**Closed by afc163** 2020-12-04 08:58 UTC
