### ISSUE TITLE
antd compoent 的 body row  不能获取index属性

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#41019] opened 2023-03-02 11:26 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ke-bian-ji-dan-yuan-ge-antd-4-24-8-forked-1dwsgn)

### Steps to reproduce

console log没有打印出index 的值

### What is expected?

应该能获取index的值

### What is actually happening?

获取不到index 的值

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 18.0.0 |
| System | windows10 -64  |
| Browser | chrome |

**Comment by Yuiai01** [comment] 2023-03-02 11:51
Duplicate of https://github.com/ant-design/ant-design/issues/40788

**Closed** 2023-03-02 12:33 UTC
Labels: unconfirmed
