### ISSUE TITLE
Add isValid property or isValid() method to form instance

### ISSUE THREAD

**Issue by roman-gula** [ant-design/ant-design#29377] opened 2021-02-19 18:45 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The main problem that there is no way to disable / enable submit button that is inside or outside form.

**`getFieldsError`** or **`validateFields`** does not help.

**`form.getFieldsError`** shows errors only if error messages are shown and form was validated.
When **`form.validateFields`** is called error messages are shown.

When form is loaded I should be able to disable button if form is not valid, then when fields values are changed I should be able to check if form is still valid or invalid. 

When I change field without rules, errors should not appear on fields with rules (if they invalid).
If there are initial values, but not valid - **`form.isValid`** (or **`form.isValid()`**) should be false.

If there was a method like **`isValid()`**, I could create react hook that check isValid on values change.

### What does the proposed API look like?
**`form.isValid: boolean`**
or
**`form.isValid: () => bolean`**

**Comment by zombieJ** [comment] 2021-02-20 05:58
Duplicate of #27667

**Closed by zombieJ** 2021-02-20 05:58 UTC

**Comment by roman-gula** [comment] 2021-02-20 09:25
@zombieJ https://github.com/ant-design/ant-design/issues/27667 it is not duplicate, disabling on submit and disabling if form is not valid are different things! 
Please reopen my issue
