### ISSUE TITLE
Textarea 中文输入超过被截断问题

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#27686] opened 2020-11-11 02:51 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/mraiguo/pen/oNLQEGo?editable=true&editors=001%3Dhttps%3A%2F%2Fant.design%2F](https://codepen.io/mraiguo/pen/oNLQEGo?editable=true&editors=001%3Dhttps%3A%2F%2Fant.design%2F)
可以在链接比对和原生的元素间的区别
### Steps to reproduce
输入到邻近maxLength 的字数后，切换拼音输入法，因为输入法组字是在输入框内进行的，会被 Textarea 内部的 slice 切断，只留下字母，但是原生的textarea 是按空格选词后切换汉字。
**除此之外还有个问题，就是这时候光标移到中间，再点击输入，会把最后一个字符删掉，且光标移到最后**  

[![BX06hD.gif](https://s1.ax1x.com/2020/11/11/BX06hD.gif)](https://imgchr.com/i/BX06hD)
### What is expected?
和正常的textarea 行为一致

### What is actually happening?
行为不一致

| Environment | Info |
|---|---|
| antd | latest |
| React | react16 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment] 2020-11-11 03:18
Duplicate of #27116

**Closed** 2020-12-21 08:22 UTC
Labels: 👷🏻‍♂️ Someone working on it
