### ISSUE TITLE
Autocomplete defaultActiveFirstOption is not working after option list changed

### ISSUE THREAD

**Issue by achilles-tee** [ant-design/ant-design#17485] opened 2019-07-05 04:01 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/billowing-architecture-wfc1r)

### Steps to reproduce
Type any character in input field 

### What is expected?
It should always highlight the first option

### What is actually happening?
It only highlight the first option at the very first time.
Any order changes to the options, the highlight won't go to the first option anymore.

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | react |
| System | mac |
| Browser | chrome |

---
defaultActiveFirstOption	Whether active first option by default
The defaultActiveFirstOption define as above, as my understanding and expected, it should always show the first option, no matter the options order changing.

**Comment by zombieJ** [comment] 2019-07-05 07:23
Duplicate of #17294

**Closed by zombieJ** 2019-07-05 07:23 UTC
