### ISSUE TITLE
List 的 grid 属性来实现栅格列表时，唯独不能实现一行5个的布局

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design#23613] opened 2020-04-26 07:52 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xiangyingshidezhageliebiao-ant-design-demo-te92y)

### Steps to reproduce
调整浏览器宽度，会发现怎么调都不会出现一行5个

### What is expected?
希望能实现一行5的的出现

### What is actually happening?
实际上失效

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.12 |
| System | mac |
| Browser | 谷歌 |

**Comment by zombieJ** [comment] 2020-04-27 06:55
Duplicate of #21474

https://github.com/ant-design/ant-design/issues/21474#issuecomment-588183319

**Closed by zombieJ** 2020-04-27 06:55 UTC
