### ISSUE TITLE
Button Type & PopConfirm OkType not accepting type of danger

### ISSUE THREAD

**Issue by Rocinante89** [ant-design/ant-design#24061] opened 2020-05-11 13:21 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com](https://github.com)

### Steps to reproduce
Using Typescript, creating a button component or popconfirm component and setting the type or okType to 'danger' will cause a compile error.

### What is expected?
The type should be able to be set to danger

### What is actually happening?
When you run npm start it is failing to compile 

| Environment | Info |
|---|---|
| antd | 4.2.1 |
| React | latest |
| System | win 10 |
| Browser | chrome latest |

**Comment by Rocinante89** [comment] 2020-05-11 13:22
![image](https://user-images.githubusercontent.com/8224386/81566467-d407a300-9392-11ea-8d49-1a2344a897b9.png)

**Comment by afc163** [comment] 2020-05-11 13:35
Duplicate of #23860

**Closed by afc163** 2020-05-11 13:35 UTC
