### ISSUE TITLE
Use `prop-types` standalone package

### ISSUE THREAD

**Issue by Haroenv** [ant-design/ant-design#5988] opened 2017-05-02 09:17 UTC
### What problem does this feature solve?
Instead of using `React.PropTypes`, we should use `import PropTypes from 'prop-types'`, which has been changed in React 15.5, and will be a breaking change later

### What does the proposed API look like?
```js
import PropTypes from 'prop-types'

Component.propTypes = {
  someProp: PropTypes.any,
};
```

**Comment by yesmeck** [comment] 2017-05-02 09:19
Duplicate of #5678

**Closed by yesmeck** 2017-05-02 09:19 UTC

**Comment by Haroenv** [comment] 2017-05-02 09:21
Ah, sorry, I didn't find that issue while searching
