### ISSUE TITLE
children prop in table not working with virtualized lists

### ISSUE THREAD

**Issue by vronifuchsberger** [ant-design/ant-design#21370] opened 2020-02-13 11:30 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/epic-newton-bejhe)

### Steps to reproduce
Add children prop to table data. Child rows won't be rendered at all and no indication that they exist.

### What is expected?
have expandable rows as in the https://next.ant.design/components/table/#components-table-demo-expand-children example. 

### What is actually happening?
children are not rendered and there is no indication that rows have children

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.4 |
| React | 16.12 |
| System | Windows 10 |
| Browser | Chrome 80 |

---
If this is a restriction from react-window and therefore not possible to achieve I think it should be added to the documentation.
Also the render prop is ignored. (this is easy to circumvent, but might still be good to mention in the documentation)

**Comment by zombieJ** [comment] 2020-02-17 06:48
Duplicate of #21022

**Closed by zombieJ** 2020-02-17 06:48 UTC
