### ISSUE TITLE
Table header and body columns misaligned when zooming in/out

### ISSUE THREAD

**Issue by luongminhanh** [ant-design/ant-design#50248] opened 2024-08-05 10:50 UTC
### Reproduction link

[https://ant.design/components/table](https://ant.design/components/table)

### Steps to reproduce

Use the browser's zoom function or press Ctrl   or Ctrl - to zoom in or out.

### What is expected?

The columns in the table header should remain aligned with the columns in the table body, regardless of the browser zoom level.

### What is actually happening?

When the zoom level in the browser is changed, either by using the browser's zoom controls or by pressing Ctrl   / Ctrl -, the columns in the table header and the table body become misaligned

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 18 |
| System | Windows 10 |
| Browser | Chrome |

---
I found this issue not only in my project but also on the official Ant Design documentation site, so I think it is an inherent issue with the antd Table component.

![image](https://github.com/user-attachments/assets/43144637-d64b-4fed-a769-6811534e191d)

**Comment by zombieJ** [comment] 2024-08-08 09:44
Duplicate of #48247

**Closed by zombieJ** 2024-08-08 09:44 UTC
Labels: unconfirmed
