### ISSUE TITLE
TreeSelect bug

### ISSUE THREAD

**Issue by truejay** [ant-design/ant-design#36901] opened 2022-08-04 16:58 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/checkable-antd-4-22-3-forked-xu8gne)

### Steps to reproduce

Set tagRender and maxTagCount.

### What is expected?

maxTagPlaceholder should apply similar to tagRender

### What is actually happening?

maxTagPlaceholder does not render as expected

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.2 |
| System | windows 10 |
| Browser | chrome latest |

**Comment by zombieJ** [comment] 2022-08-05 02:27
Duplicate of #32072

**Closed by zombieJ** 2022-08-05 02:27 UTC
