### ISSUE TITLE
<Table> scroll option can't affect to expandedRender.

### ISSUE THREAD

**Issue by haracejacob** [ant-design/ant-design#22557] opened 2020-03-24 07:05 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nested-tables-ant-design-demo-esi5n)

### Steps to reproduce
https://codesandbox.io/s/nested-tables-ant-design-demo-esi5n (4.x.x)
https://codesandbox.io/s/nested-tables-ant-design-demo-6jxcb (3.x.x)

### What is expected?
Scroll option in parent Table is affect to expandedRender

### What is actually happening?
In antd 4.x.x, ExpandedRender is not affected by scroll option in parent table

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.12.0 |
| System | macOS Catalina 10.15.3 |
| Browser | Chrome 80.0.3987.132 |

**Comment by zombieJ** [comment] 2020-03-24 07:33
It's by design. Expanded content not follow parent table scroll anymore.

But the shadow of nest table is a bug should be fixed.

**Comment by haracejacob** [comment] 2020-03-24 07:48
@zombieJ 

Then, how to make it follow?

**Comment by afc163** [comment] 2020-03-24 08:11
When Table contains fixed columns, we should make expanded content fixed to avoid cover by fixed columns. However, in this case, Expanded content in scrollable table without fixed columns could be scrollable too, I think 3.x demo has a better experience.

**Comment by haracejacob** [comment] 2020-04-01 08:43
@zombieJ @afc163 
The problem is `width` attribute in `<div class="ant-table-expanded-row-fixed">`
Why did you use `width` as 'style attributes' instead of `class`?
I cannot controll it

**Comment by zombieJ** [comment] 2020-04-01 09:56
Adjust in `4.2` to avoid breaking change.

**Closed** 2020-04-01 12:57 UTC
