### ISSUE TITLE
"Cannot update a component from inside the function body of a different component." on nested Form.Item

### ISSUE THREAD

**Issue by Thanaen** [ant-design/ant-design#21773] opened 2020-03-02 08:28 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-react-1613-warning-4p6is)

### Steps to reproduce
Just open the minimal reproduction, and look at the browser's console.

### What is expected?
There should be no error message.

### What is actually happening?
There is this error message:"Warning: Cannot update a component from inside the function body of a different component" coming from React

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.13.0 |
| System | Windows 10 1903 |
| Browser | Firefox 73.0.1 |

---
This new warning has been added to React with the 16.13.0 update (https://reactjs.org/blog/2020/02/26/react-v16.13.0.html#new-warnings)
It seems that a Form.Item that has the noStyle prop to true and that is nested with another Form.Item, like this:
```JSX
<Form.Item>
<Form.Item name="name" noStyle> <Input type="text" /> </Form.Item>
</Form.Item>
```

**Comment by afc163** [comment] 2020-03-02 08:51
Duplicate of #21698

**Closed by afc163** 2020-03-02 08:52 UTC

**Comment by Thanaen** [comment] 2020-03-02 08:55
My apologies for the duplicate !
