### ISSUE TITLE
DatePicker is not respecting ConfigProvider locale ptBR

### ISSUE THREAD

**Issue by herbertpimentel** [ant-design/ant-design#24264] opened 2020-05-18 13:39 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-h9d6p?file=/index.js)

### Steps to reproduce
open datepicker popup read moths and days of week still in english

### What is expected?
all the texts in the component to be translated to portuguese

### What is actually happening?
some text are in portuguese and moths and days of week still in english

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.13.1 |
| System | Windows10 |
| Browser | Chrome |

**Comment by afc163** [comment] 2020-05-18 14:16
Duplicate of #24260

**Closed by afc163** 2020-05-18 14:16 UTC
