### ISSUE TITLE
SCSS format stylesheet wanted

### ISSUE THREAD

**Issue by martin-luo** [ant-design/ant-design#20835] opened 2020-01-11 06:36 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hi there, 

Thanks for making the Antd open-source, it is an awesome package!

When I developed my project using Antd, I just found it is not that convenient, as my stylesheets are written in SCSS, while Antd only provides less and css format stylesheets.  I know there are some workarounds such as convert the LESS file to SCSS file, or use the bundled CSS files directly, but it would be great if we can have a SCSS format stylesheet.

### What does the proposed API look like?
SCSS-format stylesheets files

**Comment by afc163** [comment] 2020-01-11 15:24
Duplicate of #18611

**Closed by afc163** 2020-01-11 15:24 UTC
