### ISSUE TITLE
Drag for Switches?

### ISSUE THREAD

**Issue by mxye** [ant-design/ant-design#34947] opened 2022-04-08 16:31 UTC
### What problem does this feature solve?

Switches by default are clickable but not draggable. Users in general find that counter-intuitive. They've all been conditioned to expect the switches to drag. When they repeatedly attempt to drag the switch and fail, many of them just think the app is broken. 

Any chance to allow both drag and click to toggle the Switches? 

### What does the proposed API look like?

Switch -- by default responds to both drag and click events.

**Comment by afc163** [comment] 2022-04-11 03:48
Duplicate of #29289

**Closed by afc163** 2022-04-11 03:48 UTC
