### ISSUE TITLE
TypeScript按需载入部分的教程不适用于create-react-app 2.1

### ISSUE THREAD

**Issue by chenvd** [ant-design/ant-design#12933] opened 2018-11-02 09:39 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
create-react-app 2.1已经自带了对Type Script的支持了，不过Ant Design文档 《TypeScript 中使用》一章中提供的按需加载方法似乎不适用了

### What does the proposed API look like?
希望可以给出新的方法，支持在create-react-app 2.1中按需加载antd，react-scripts-ts对应的react-scripts版本太老了

**Comment by afc163** [comment] 2018-11-02 09:41
Duplicate of #12878

**Closed by afc163** 2018-11-02 09:41 UTC
