### ISSUE TITLE
table scrollbar visible on modal overflow

### ISSUE THREAD

**Issue by Rajesh-kumar-r** [ant-design/ant-design#17940] opened 2019-07-29 05:20 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sweet-mcnulty-ocdv7)

### Steps to reproduce
click scroll bar and move content .then if i open a modal the scroll bar will not hidden

### What is expected?
scrollbar to be hidden or modal should hide the scrollbar

### What is actually happening?
scrollbar disturb the modal

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.9.0 |
| System | mac os 10.14.5 |
| Browser | chrome 75 |

**Comment by jljsj33** [comment] 2019-07-29 08:11
I don't understand your description. can you upload a image with a problem?

**Comment by jljsj33** [comment] 2019-07-29 08:11
![image](https://user-images.githubusercontent.com/6802825/62031839-d7260e00-b21a-11e9-88a0-cd1dc6d92109.png)

**Comment by Rajesh-kumar-r** [comment] 2019-07-29 09:46
![Screenshot 2019-07-29 at 14 53 08](https://user-images.githubusercontent.com/47350245/62038704-d6d64480-b213-11e9-8552-2e11cf560c89.png)

**Comment by afc163** [comment] 2019-07-29 09:58
Duplicate of #15194

**Closed by afc163** 2019-07-29 09:58 UTC
