### ISSUE TITLE
Steps组件onChange事件位置错误

### ISSUE THREAD

**Issue by jrr997** [ant-design/ant-design#37137] opened 2022-08-18 08:13 UTC
### Reproduction link

[https://stackblitz.com/edit/react-ywfjoy?file=demo.js,package.json](https://stackblitz.com/edit/react-ywfjoy?file=demo.js,package.json)

### Steps to reproduce

1. 鼠标放到标题1上面,观察hover元素.
2. 鼠标点击标题1,onChange拿到了标题2的current值

### What is expected?

 鼠标放到标题1上面,期待触发标题1的hover,onChange拿到的标题1的current值.

### What is actually happening?

 鼠标放到标题1上面,期待触发标题2的hover,onChange实际拿到了标题2的current值.

| Environment | Info |
| --- | --- |
| antd | 4.22.6 |
| React | 17.0.2 |
| System | win10 |
| Browser | chrome |

---
给Step组件加宽度就会造成这个问题.

**Comment by afc163** [comment] 2022-08-18 09:04
总宽度太小了，因此会挤压错误，Step 每一项有一个最小宽度 @steps-description-max-width 变量可以自定义。

**Comment by afc163** [comment] 2022-08-18 13:30
Duplicate of #32805

**Closed by afc163** 2022-08-18 13:30 UTC
