### ISSUE TITLE
TreeSelect组件能否像Tree组件一样支持展开动画

### ISSUE THREAD

**Issue by sdhr27** [ant-design/ant-design#29274] opened 2021-02-07 08:02 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Tree组件在展开关闭节点的时候自带switch动画和节点动画，希望TreeSelect组件也能支持动画。

### What does the proposed API look like?
无感知支持，或者新增API motion

**Comment by afc163** [comment] 2021-02-07 12:15
Duplicate of https://github.com/ant-design/ant-design/issues/24292

**Closed by afc163** 2021-02-07 12:15 UTC
