### ISSUE TITLE
Time picker not displaying correctly on mobile devices

### ISSUE THREAD

**Issue by James2516** [ant-design/ant-design#7534] opened 2017-09-09 18:07 UTC
### Version
2.12.8

### Environment
Chrome v60, windows 10

### Reproduction link
https://codesandbox.io/s/14k8o6jzx3

### Steps to reproduce
Run the above link on mobile

### What is expected?
It should be positioned correctly, like on desktop

### What is actually happening?
https://i.imgur.com/NQObP8o.png
the dropdown is to the left of the input box

**Comment by afc163** [comment] 2017-09-09 18:24
Duplicate of https://github.com/react-component/time-picker/issues/67

**Closed by afc163** 2017-09-09 18:24 UTC
