### ISSUE TITLE
Add more CSS specificity to the Tag component colors

### ISSUE THREAD

**Issue by imballinst** [ant-design/ant-design#46478] opened 2023-12-15 11:11 UTC
### Reproduction link

[https://antd-remix-tag-repro.vercel.app/default-tag](https://antd-remix-tag-repro.vercel.app/default-tag)

### Steps to reproduce

1. Go to https://antd-remix-tag-repro.vercel.app/default-tag
2. You will be presented with a default-colored Tag and Badge
3. Then, click "Go to other page with all kind of tag colors"
4. You will land on the home page and will be presented with "supposed-to-be-colored" Tags and colored Badges

Side note: the issue only happens if you visit the `/default-tag` path first (e.g. using browser navigation, or reload the page there). This seems like because `/default-tag` only has the default colors (from SSR style), and then when we go to the home page using the link, then the success/warning Tag colors can't be overridden because they have the same CSS specificity (from `.ant-tag`).

The `.ant-tag` style that was applied first contains the background, color, etc. -- whereas the `.ant-tag-success` (or similar) that is applied later can't override the thing since it has the same CSS specificity.

### What is expected?

For "Tag" components, they are styled using something like `.ant-tag.ant-tag-warning`, so that the specificity is always stronger.

### What is actually happening?

At the moment, if we see the "Badge" component (https://ant.design/components/badge) and the "Tag" component (https://ant.design/components/tag), there is a bit of difference in terms of styling.

For the Badge component, it's styling using this thing: `:where(.css-unboq8).ant-badge.ant-badge-status .ant-badge-status-success`. As we can see, this increases the specificity of the badge status and hence is always on a strong position to override any cases (e.g. change to warning/error will always change the color 100%).

However, for the Tag component, it's styling using this thing: `:where(.css-unboq8).ant-tag` and `:where(.css-unboq8).ant-tag-warning`. As we could see, the former has the same CSS specificity as the latter. This causes some issues in certain SSR conditions, such as when the server style is initially injected for `.ant-tag`, then we change page to a page where there are other tag colors, e.g. `.ant-tag-warning`. Since they are client-side rendered and have the same CSS specificity as the styles from the server, then we can't override the color and hence, all tags in the new page will be using the "default color" instead of the colors that they should be.

| Environment | Info |
| --- | --- |
| antd | 5.12.2 |
| React | 18.0.2 |
| System | Ubuntu 20 |
| Browser | Firefox 120.0.1 |

---
Repository link for repro: https://github.com/imballinst/antd-remix-tag-repro

**Comment by MadCcc** [comment] 2023-12-18 02:25
Duplicate of https://github.com/ant-design/ant-design/issues/45894

**Closed** 2023-12-18 03:07 UTC
Labels: unconfirmed
