### ISSUE TITLE
Badge loses style and animation if "count" prop is not a number

### ISSUE THREAD

**Issue by oceandrama** [ant-design/ant-design#28992] opened 2021-01-22 21:19 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/standalone-antd4103-forked-hw068)

### Steps to reproduce
Click on switch to hide and show badges

### What is expected?
All badges look the same, have animation on show and on hide

### What is actually happening?
If we use not a number in a "count" prop, the badge loses their styles and animation on show. Styles and animations on hide works well

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Chrome  87.0.4280.88 |

**Comment by oceandrama** [comment] 2021-01-24 16:58
@afc163 Sorry, wrong link in description
https://codesandbox.io/s/antd-reproduction-template-forked-wpers

**Comment by afc163** [comment] 2021-01-25 01:48
`count` should be number unless we see it as ReactNode without numberic feature.

**Comment by oceandrama** [comment] 2021-01-25 10:35
@afc163 But there are animations on hide. When I switch trigger to false, background in the badge appears and the badge hide exactly the same as others. Why we can't do the same thing for animations on show

**Comment by oceandrama** [comment] 2021-01-26 22:52
@xrkffgg Sorry, maybe you could explain?

**Comment by xrkffgg** [comment] 2021-01-27 01:21
OK, I will check

**Comment by xrkffgg** [comment] 2021-01-27 01:23
关闭的时候，会有个动画背景 闪了一下

**Comment by xrkffgg** [comment] 2021-01-28 01:34
This is not a bug. This is the default closing animation `.ant-badge-zoom-leave`

Suggest use
```jsx
<Badge count={show ? <span>25</span> :  <span></span> } />
```

**Closed** 2021-01-28 01:34 UTC
