### ISSUE TITLE
Tree Com draggable 为 false 的节点，无法成为新的父节点

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/ant-design#36661] opened 2022-07-22 17:42 UTC
### What problem does this feature solve?

一些节点虽然无法拖拽它自身，但是可以移动其他节点作为它的子节点，目前这个需求无法满足

### What does the proposed API look like?

draggable: (...) => { draggable: boolean; nest: boolean }

![image](https://user-images.githubusercontent.com/37258382/180494804-9840e70b-4c1e-4896-a94d-16f0bd82dcc4.png)

**Comment by afc163** [comment] 2022-07-23 07:43
Duplicate of #30551

**Closed by afc163** 2022-07-23 07:43 UTC
