### ISSUE TITLE
Calendar  IE10报错

### ISSUE THREAD

**Issue by zmhweb** [ant-design/ant-design#15368] opened 2019-03-13 07:15 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rw6mw3n6wo)

### Steps to reproduce
引入后就使用的时候就报错

### What is expected?
正常显示

### What is actually happening?
直接报错

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.2 |
| System | window 10 |
| Browser | ie 10 |

**Comment by afc163** [comment] 2019-03-13 09:04
Duplicate of #15268

**Closed by afc163** 2019-03-13 09:04 UTC

**Comment by zmhweb** [comment] 2019-03-13 09:29
SCRIPT438: 对象不支持“getDerivedStateFromProps”属性或方法
bundle.js (139663,48)
The above error occurred in the <CalendarMixinWrapper> component:
    in CalendarMixinWrapper (created by Context.Consumer)
    in div (created by Context.Consumer)
    in LocaleReceiver (created by Calendar)
...



SCRIPT438: 对象不支持“getDerivedStateFromProps”属性或方法

@ant-design-bot 
![image](https://user-images.githubusercontent.com/16442336/54268104-783a6200-45b5-11e9-8eaf-e14f4860b274.png)
![image](https://user-images.githubusercontent.com/16442336/54268128-80929d00-45b5-11e9-98a2-39b1ae99ea0e.png)
