### ISSUE TITLE
select组件添加allowClear的回调函数

### ISSUE THREAD

**Issue by zxwGH** [ant-design/ant-design#25380] opened 2020-07-02 03:53 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
防止误点导致选项删除，给用户提示是否清空

### What does the proposed API look like?
添加allowClear的回调函数

**Comment by zombieJ** [comment] 2020-07-03 02:05
Duplicate of #21498

**Closed by zombieJ** 2020-07-03 02:05 UTC
