### ISSUE TITLE
how to set focus on Select's Search Input programmatically

### ISSUE THREAD

**Issue by desmondcheo86** [ant-design/ant-design#19564] opened 2019-11-05 03:48 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have an AddressInput component which consists of a label and an ANTD Select component where showSearch property value is true. There's a requirement from the user to set focus on the search input of the Select component when the label is clicked but set focus on the Select component does't focus the Search Input. 

       <div className="contact-details-input" onClick={this.onClick}>
                    <div className="address-input-label" onClick={this.onClick}>
                        {label}
                    </div>

                    {getFieldDecorator(id, {
                        initialValue: buildAddressString(this.state.value),
                        valuePropName: 'option',
                    })(
                        <div className="address-input-container">
                            <Select      
                             
                                showSearch
                                
                                showArrow={false}
                                notFoundContent="Enter street number and name to find address"
                                filterOption={false}
                                onSearch={this.handleSearchStart}
                                onSelect={this.selectAddress}                               
                                onDropdownVisibleChange={this.handleDropdownVisibleChange}
                      
                                onFocus={this.onFocus}
                                onBlur={this.onBlur}
                                open={open}
                            >
                                {options}
                            </Select>
                        </div>,
                    )}                    
                </div>
            </div>

Please advise.

### What does the proposed API look like?

perhaps a new method to focus on the search input field if it hasn't had one already on Select component

**Comment by dhassouni** [comment] 2019-11-12 21:09
I am not sure if the description here is really describing the same issue found in https://github.com/ant-design/ant-design/issues/14503, but if so, may make sense to merge.

The issue I am running into is that I cannot tab into a Select component with showSearch and mode="default" and start typing. However, I can do so with mode="multiple".

**Comment by afc163** [comment] 2019-11-13 02:46
Duplicate of #14503

**Closed by afc163** 2019-11-13 02:46 UTC
