### ISSUE TITLE
Collapse折叠面板 禁止折叠的问题

### ISSUE THREAD

**Issue by yinxiaodongabc** [ant-design/ant-design#23089] opened 2020-04-09 09:14 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
需求需要在面板头部增加一个按钮，触发点击事件，给面板里面动态新增元素。但是每次点击都会折叠面板，showArrow设为false只能隐藏箭头，感觉毫无作用，还是能折叠面板。disabled的话就直接禁止编辑面板头了

### What does the proposed API look like?
面板头添加按钮触发点击事件，但是不toggle面板。。。showArrow设置为false的时候不仅隐藏箭头，且无法折叠面板

**Comment by afc163** [comment] 2020-04-09 15:05
Duplicate of #15240

**Closed by afc163** 2020-04-09 15:05 UTC
