### ISSUE TITLE
Unexpected behavior of a "selection-column" in Table component

### ISSUE THREAD

**Issue by Frontmaster** [ant-design/ant-design#23935] opened 2020-05-07 08:10 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ef29j?file=/index.js)

### Steps to reproduce
This issue only happens when you make a Table header fixed and "selection-column" is present.
Pay attention to the change of the width of a "selection-column".

### What is expected?
Width of a "selection-column" should not change when switching between 'fixed/regular' header mode

### What is actually happening?
When making table header fixed "selection-column" changes it's dimensions

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | React ^16.13.1 |
| System | any |
| Browser | any |

---
Supposedly proper class name is not assigned to a `<col>` that corresponds to a 'selection-column'

**Comment by afc163** [comment] 2020-05-07 08:34
Duplicate of #23799

**Closed by afc163** 2020-05-07 08:34 UTC
