### ISSUE TITLE
4.x虚拟滚动树形组件Y轴滚动条能否始终显示或鼠标移上去显示

### ISSUE THREAD

**Issue by wongfugui** [ant-design/ant-design#31016] opened 2021-06-16 14:14 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前虚拟滚动树的Y轴滚动条只在滑动滚轮的时候才会出现，鼠标移上去也不会出现，感觉很不友好。

### What does the proposed API look like?
Y轴滚动条能和正常的一样始终显示或者鼠标移上去显示。

**Comment by afc163** [comment] 2021-06-16 15:52
Duplicate of #28074

**Closed by afc163** 2021-06-16 15:52 UTC
