### ISSUE TITLE
Descriptions 组件下 Description.Item 的 span 属性不生效呢？

### ISSUE THREAD

**Issue by wood3n** [ant-design/ant-design#29850] opened 2021-03-22 06:20 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-antd4123-forked-vf1zb?file=/index.js)

### Steps to reproduce
打开demo

### What is expected?
Descriptions 组件 设置 `column = 3`的时候，同时设置 Description.Item 的 span = 3，此时的 Description.Item 应该换行显示的

### What is actually happening?
没有换行显示，`colspan`没变化

| Environment | Info |
|---|---|
| antd | 4.14.0 |
| React | 16.14 |
| System | window10 1909 |
| Browser | Chrome 89 |

**Comment by afc163** [comment] 2021-03-22 14:12
Duplicate of #18155

**Closed by afc163** 2021-03-22 14:12 UTC
