### ISSUE TITLE
Past month selected day behavior

### ISSUE THREAD

**Issue by notnotgabriel** [ant-design/ant-design#9295] opened 2018-02-07 14:12 UTC
### Version
3.2.0

### Environment
Chrome

### Reproduction link
[https://codesandbox.io/s/lx4892x2l7](https://codesandbox.io/s/lx4892x2l7)

### Steps to reproduce
1. Open the DatePicker and see the actual day, eg.: Today is 7 of February
2. Turn back one or two months and you'll see the same actual day with the selected style eg.: 7 of January have selected style

### What is expected?
When I navigate between past months, the expected for me is Datepicker don't have selected style for actual day.

### What is actually happening?
When I navigate between past months, the Datepicker shows me the number of actual day with an selected style.

---
This is not a bug, maybe it's an improvement.

**Comment by notnotgabriel** [comment] 2018-02-07 14:13
@ant-design-bot added the wrong component >.<

**Comment by yesmeck** [comment] 2018-02-10 06:20
Duplicate of #6146

**Closed by yesmeck** 2018-02-10 06:20 UTC
Labels: Component: DatePicker
