### ISSUE TITLE
Modal open prop is not passed on to child component on 4.24.10

### ISSUE THREAD

**Issue by yechukim** [ant-design/ant-design#42658] opened 2023-05-26 10:18 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-s4h6ih?file=/InsideModal.jsx)

### Steps to reproduce

make a modal component from antd, and add another component inside modal. 
and from child component , try to log visible prop from parent component. it doesn't change at all.
visible prop (could be open prop but I guess it's same thing) only changes in the component that Modal is declared.

### What is expected?

visible prop should change according to parent component visible prop

### What is actually happening?

visible prop doesn't change even if parent component modal's visible prop has changed.

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | 17.0.1 |
| System | mac 12.6 |
| Browser | chrome 113.0.5672.126 |

---
not sure which version doesn't have this issue. 
when I tried 4.8.x version, there was no problem

**Comment by afc163** [comment] 2023-05-26 11:39
You can add `forceRender` to keep inner state after close modal.

https://codesandbox.io/s/antd-reproduction-template-forked-92i8kh?file=/InsideModal.jsx

**Comment by zombieJ** [comment] 2023-05-26 12:48
Modal will not trigger update to make closing content motion stable since some code will be like:
```tsx
<Modal open={open}>
  {/* In real world, this may be much complex */}
  {open && <></>}
</Modal>
```

Another reason is use memo for render perf saving.

You can ref @afc163 's reply use `forceRender` to always keep Modal context alive.

**Closed by zombieJ** 2023-05-26 12:48 UTC
Labels: unconfirmed

**Comment by yechukim** [comment] 2023-05-27 05:34
> You can add `forceRender` to keep inner state after close modal.
> 
> https://codesandbox.io/s/antd-reproduction-template-forked-92i8kh?file=/InsideModal.jsx

yes it works with forceRender, I do wonder though, cos I didn't have to add forceRender prop in previous version but it changed I guess ? 
cos in terms of react thoughts, when parent component render, does child component as well. 
if I don't want that I will use other ways like useMemo or any other options.

**Comment by zombieJ** [comment] 2023-05-28 02:31
In older version it already use `shouldComponentUpdate` in class component. But when refactor will function component it has some bug of this. After patch it fixed as origin behavior.

**Comment by yechukim** [comment] 2023-05-30 06:37
@zombieJ so do you mean original behavior is not rendering child component then? 
 When even parent component renders, child component wouldn't render unless I use forceRender ?
