### ISSUE TITLE
Dynamically assign Title value to PageHeader through state

### ISSUE THREAD

**Issue by PeterHassaballah** [ant-design/ant-design#22325] opened 2020-03-17 19:55 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-329u0)

### Steps to reproduce
Change the title to the const t and observe

### What is expected?
A dynamic assignment to the PageHeader prop => Title that takes as an input a string but it can not parse a constant

### What is actually happening?
Can not change Title prop dynamically 

| Environment | Info |
|---|---|
| antd | 3.26.12 |
| React | 16.9.0 |
| System | Win 10 |
| Browser | Chrome Version 80.0.3987.132 (Official Build) (64-bit) |

**Comment by afc163** [comment] 2020-03-18 03:24
Duplicate of #22324

**Closed by afc163** 2020-03-18 03:24 UTC
