### ISSUE TITLE
Expand all rows

### ISSUE THREAD

**Issue by dmarkin** [ant-design/ant-design#10199] opened 2018-04-23 10:06 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It's nice to have for table element "Expand all rows" at the top of the expand column

### What does the proposed API look like?
Its nice to have at the table parameter expandAll={true} (by default - false) to expand all expandable rows by clicking on it.
This functionality must to use expandedRowKeys and switch it from [] to [...allRows], but it have to be the same common element as for rows and it must position at the header of this column

**Comment by yesmeck** [comment] 2018-04-23 10:31
Duplicate of #8791

**Closed by yesmeck** 2018-04-23 10:31 UTC
