### ISSUE TITLE
Typography Text/Title being cut off when changed with editable/ellipsis

### ISSUE THREAD

**Issue by josh-schlick** [ant-design/ant-design#34724] opened 2022-03-25 17:55 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/typography-ellipse-editable-not-resizing-ulidp2)

### Steps to reproduce

- Use Typography.Text or Typography.Title with `ellipsis` and `editable`
- Dynamically make the inner text longer
- Notice the ellipsis is used, and the entire text is not shown, even though there is room to display the entire text
- (note: for Typography.Title, wrap in Row & Col to get problem)

### What is expected?

Entire text should be shown when there is room

### What is actually happening?

The ellipsis is used, and the entire text is not shown, even though there is room to display the entire text

| Environment | Info |
| --- | --- |
| antd | 4.19.3 |
| React | 6.14.0 |
| System | macos |
| Browser | chrome 99.0.4844.83 |

---
This bug is present in 4.18.4, but is not present in 4.18.3

**Comment by ZLester** [comment] 2022-03-25 19:33
Looks related to #32899

**Comment by afc163** [comment] 2022-03-26 02:57
Duplicate of #32899

**Closed by afc163** 2022-03-26 02:57 UTC
