### ISSUE TITLE
Width display issues on the Tour component

### ISSUE THREAD

**Issue by JulesLecuir** [ant-design/ant-design#40618] opened 2023-02-07 18:51 UTC
Please forgive my lazyness, but I haven't found the time to create repro link, I think it's really simple to reproduce anyways :)

### Code:
```js
const steps = [
  {
    title: "Something",
    description: (
      <div style={{width: 200}}>
        Some long text that I wanted to split on several lines as this is way too large, so I
        put it into a fixed width div.
      </div>
    ),
    target: () => myRef.current,
  },
]
```
### Result:

1. The component doesn't adapt to the children's width
![Screenshot from 2023-02-07 19-35-42](https://user-images.githubusercontent.com/33055419/217335273-d7cfcaea-54ae-4e1c-aafa-81d05bffe47d.png)

2. As you can see, when the tour component is close to the side of the screen, the arrow doesn't really point to the element taht is targeted.

3. In mobile view, the component goes out of the screen instead of shrinking accordingly to the viewport
![Screenshot from 2023-02-07 19-36-03](https://user-images.githubusercontent.com/33055419/217335482-39fbe52c-f605-4da9-a8d3-72b423ff74a0.png)

## And btw... Mistake in the docs ?

In [the Tour docs](https://ant.design/components/tour#tour), the onClose() method for the Tour component actually doesn't exists: in my code, I use the onFinish() method instead.

<br/>
And thanks for maintaining this wonderful project, I just updated to Antd5 and the new features are sick ! <3

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | 17.0.2 |
| System | Ubuntu 22 |
| Browser | Brave Browser last version |

**Comment by MadCcc** [comment] 2023-02-08 02:22
Duplicate of https://github.com/ant-design/ant-design/issues/40419

**Closed by MadCcc** 2023-02-08 02:22 UTC
Labels: unconfirmed
