### ISSUE TITLE
select的option全部显示不要滚动条 

### ISSUE THREAD

**Issue by vuvivian** [ant-design/ant-design#16579] opened 2019-05-14 06:09 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost:8080/businessmodel](http://localhost:8080/businessmodel)

### Steps to reproduce
由于下拉菜单的选项过多（有16个），Select在下拉菜单中使用了滚动条。但是我当前的需求是需要显示全部选项，去掉滚动条。
代码如下：
  <Select>
            <Option value="01">01</Option>
            <Option value="02">02</Option>
            <Option value="03">03</Option>
            <Option value="04">04</Option>
            <Option value="05">05</Option>
            <Option value="06">06</Option>
            <Option value="07">07</Option>
            <Option value="08">08</Option>
            <Option value="09">09</Option>
            <Option value="10">10</Option>
            <Option value="11">11</Option>
            <Option value="12">12</Option>
            <Option value="13">13</Option>
            <Option value="14">14</Option>
            <Option value="15">15</Option>
            <Option value="16">16</Option>
    </Select>

### What is expected?
显示全部option，去掉滚动条

### What is actually happening?
存在滚动条

| Environment | Info |
|---|---|
| antd | 3.10.3 |
| React | 15.4.2 |
| System | windows |
| Browser | google |

**Comment by vuvivian** [comment] 2019-05-14 06:30
抱歉

> Hello @vuvivian. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @vuvivian, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

抱歉，放错了地址，地址如下：https://n72px53n20.codesandbox.io/

**Comment by afc163** [comment] 2019-05-14 06:37
Duplicate of #16580

**Closed by afc163** 2019-05-14 06:37 UTC
Labels: 🤔 Need Reproduce
