### ISSUE TITLE
Vertical Menu - on opening SubMenu (on hover) this popup submenu is flickering

### ISSUE THREAD

**Issue by ckarsan** [ant-design/ant-design#27509] opened 2020-11-02 17:21 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu/](https://ant.design/components/menu/)

### Steps to reproduce
Go to vertical Menu and hover the Navigation 1, Navigation 2 and Navigation 3 menu items, 
The popout sub menu is flickering on opening / closing

### What is expected?
No Flickering, smooth opening of menu expected

### What is actually happening?
Smooth submenu popup

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 16.13.1 |
| System | Ubuntu 20.04  |
| Browser | Chrome and Firefox |

---
it happens on the antd own website aswell https://ant.design/components/menu/ just go to the "Vertical Menu"

**Comment by afc163** [comment] 2020-11-03 02:55
Duplicate of #26979

**Closed by afc163** 2020-11-03 02:55 UTC
