### ISSUE TITLE
Global CSS conflicts with other elements

### ISSUE THREAD

**Issue by Bram-Zijp** [ant-design/ant-design#9235] opened 2018-02-02 08:46 UTC
### What problem does this feature solve?
Text markup get's styled. Elements like a,h1-h6 are getting their colors overwritten.

### What does the proposed API look like?
All styles scoped to the antd library.

**Comment by yesmeck** [comment] 2018-02-02 08:49
Duplicate of #4331

**Closed by yesmeck** 2018-02-02 08:49 UTC
