### ISSUE TITLE
Add data-attribute to td in Tree data table component

### ISSUE THREAD

**Issue by likhita-palavali** [ant-design/ant-design#6996] opened 2017-07-28 20:43 UTC
### What problem does this feature solve?
I am using Tree data table component as per our display requirements.
I am trying to display a tooltip on hover for all the first td values in the table because the values are too big to display in a cell. 
To do this I need to add a data-attribute to first td of all rows.
Please provide a way to add data-attributes to td of tree data table.
Thanks.

### What does the proposed API look like?
Using the api (Tree data table for this.)
The api will show tooltip for long values.
I will use react-tooltip where i just need to provide a custom data-attribute to the td.

**Comment by afc163** [comment] 2017-07-29 05:58
Duplicate of #6994

**Closed by afc163** 2017-07-29 05:58 UTC
