### ISSUE TITLE
【bug】treeselect组件经打包后出现“Cannot read property 'filter' of undefined”

### ISSUE THREAD

**Issue by steady-join** [ant-design/ant-design#12166] opened 2018-09-10 10:27 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
centos7，node 8.1.1，react16.0，antd 3.8.0

### Reproduction link
[https://github.com/](https://github.com/)

### Steps to reproduce
开发正常使用，打包之后treeselect组件报错。“Cannot read property 'filter' of undefined”

### What is expected?
打包正常使用

### What is actually happening?
报错。“Cannot read property 'filter' of undefined”

---
```
<TreeSelect
            dropdownClassName='select-no-icon'
            placeholder='请选择套餐'
            style={{ width: 300 }}
            dropdownStyle={{ maxHeight: 250, overflow: 'auto' }}
            treeData={treeData}
            onChange={this.onTreeChange}
          />
 // 将数据列表转换成树形结构
  transformTreeData = (array) => {
    let treeData = []
    array.forEach(item => {
      treeData.push({
        title: item.packageName,
        value: item.packageId,
      })
    })
    this.setState({ treeData })
  }


<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by afc163** [comment] 2018-09-11 03:32
Duplicate of #12182

**Closed by afc163** 2018-09-11 03:32 UTC
Labels: Need Reproduce🤔
