### ISSUE TITLE
<Menu/> renders all tooltips on collapse by default

### ISSUE THREAD

**Issue by bamtheboozle** [ant-design/ant-design#41171] opened 2023-03-10 13:20 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3duopk?file=/demo.tsx:767-841)

### Steps to reproduce

collapse menu
all tooltips are rendered automatically when they shouldn't.

### What is expected?

tooltips should not be rendered unless you hover

### What is actually happening?

all tooltips are rendered automatically on collapse. this is actually present on the codesandbox above that is straight out of the docs

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 17 |
| System | macos |
| Browser | arc |

**Comment by Yuiai01** [comment] 2023-03-11 07:40
Duplicate of https://github.com/ant-design/ant-design/issues/41081

**Comment by afc163** [comment] 2023-03-11 10:31
Duplicate of https://github.com/ant-design/ant-design/issues/41081

**Closed by afc163** 2023-03-11 10:31 UTC
Labels: unconfirmed
