### ISSUE TITLE
Cascader 多选何时开放

### ISSUE THREAD

**Issue by Octopus912** [ant-design/ant-design#29743] opened 2021-03-12 08:08 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
起码能解决大部分需要使用多选  组织架构/省份城市区县/新闻类别/行业信息 等一类功能的企业或用户。对于此类用处颇多的功能，自首次提出，跨度4年不该简单的评判为“诡异的交互，诡异的需求”并被不停地关闭，隔壁elem都有了级联多选，期望发布吧。

### What does the proposed API look like?
添加属性或新组件

**Comment by afc163** [comment] 2021-03-12 09:44
Duplicate of #23410

**Closed by afc163** 2021-03-12 09:44 UTC
