### ISSUE TITLE
table列在固定宽度时，内容超出显示省略号，并当鼠标移动上去时，用气泡显示全部内容

### ISSUE THREAD

**Issue by dbfu** [ant-design/ant-design#11617] opened 2018-08-06 02:05 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决了table里内容过长，自动换行的问题。

### What does the proposed API look like?
希望table上加一个属性控制一下，就像element-ui一样。

**Comment by yesmeck** [comment] 2018-08-06 02:43
Duplicate of #5753

**Closed by yesmeck** 2018-08-06 02:43 UTC
