### ISSUE TITLE
Is Notification component has a way to update a notification instance?

### ISSUE THREAD

**Issue by LaiHuanMin** [ant-design/ant-design#8114] opened 2017-11-05 16:06 UTC
### What problem does this feature solve?
Notification can show message or status for user, but it's own content will always change. it just like when ajax ten request, you need to update message like current finish and total finish(1/10) in a same panel. 
if create every new Notification panel for each update, it's will be fixed full of screen and may not suit for user to use.I use Antd API and cannot find a way to update the created panel's content. And I Only can close it by close func and open it again. I think it's may not suit to develop, if there's provide update func. The Notification Component will be better for developer. 

### What does the proposed API look like?
```jsx
import {Notification} from 'antd'
var instance = Notification.open({ // create a instance object, and that object can provide update func.
  message: "Will Change my text"
});
setTimeout((function(){
  instance.update({ //use update func
    message: "yes, I change your text in a timeout function"
  });
},3000);
```

**Comment by afc163** [comment] 2017-11-07 03:39
Duplicate of #8021

**Closed by afc163** 2017-11-07 03:39 UTC
