### ISSUE TITLE
how can i customize the component upload thumbnail

### ISSUE THREAD

**Issue by dawnChen666** [ant-design/ant-design#17086] opened 2019-06-13 10:59 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
when i use upload component, i will upload such as doc, txt, xls and so on, not just img. i find that when i upload img, the thumbnail is img, and i can set thumbnail as a img when i upload others. but it seems that the whole page is not harmonious, so i want to set all thumbnail by the same style

### What does the proposed API look like?
add a new property with filelist as a parameter and return a list of reactnode such like this：
```javascript
<Upload renderFileList={this.handleRenderFileList} />

handleRenderFileList = (fileList) => {
    fileList.map(file => {
        if(file.type === 'msexcel')
            return <Icon type="file-excel" />
        else
            <Icon type="file-unknown" />
    });
}


<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by afc163** [comment] 2019-06-13 15:09
Set `file.thumbUrl` to a proper value.
Duplicate of #16047

**Comment by afc163** [comment] 2019-06-13 15:11
https://ant.design/components/upload-cn/#components-upload-demo-picture-style

**Comment by afc163** [comment] 2019-06-13 15:11
Duplicate of #16047

**Closed by afc163** 2019-06-13 15:11 UTC

**Comment by dawnChen666** [comment] 2019-06-13 15:51
> Set `file.thumbUrl` to a proper value.

I know this one and file.thumbUrl just accept a string value and i want to customize thumbnail in picture-card mode, i set showUploadList=false and render the filelist by myself just like picture-card mode. but i hope that i can use offcial api to do this. now you mark this issue as a duplicate issue, so i think there are many developers that may need this property, do you have a plan that extend the functionality to help developers to use upload more freely?

**Comment by afc163** [comment] 2019-06-14 02:40
@dawnChen666 PR is welcome

**Comment by zombieJ** [comment] 2019-06-14 08:17
Currently Upload support `previewFile` function to customize preview data-url content programly. I'm not sure if accepts ReactNode is a good idea with it.
Since thumbnail with Card List is a lightway access. For your requirement, why not return a data-url with image instead of ReactNode?

**Comment by dawnChen666** [comment] 2019-06-14 08:40
@zombieJ i'm sorry that i think thumbnailurl or previewfile accepting nothing but data-url is a good idea.it isn't customized and free i think, maybe i upload files but without data-url, i know nothing but the response with 200, and also i tried previewFile and upload a doc, in picture-card mode, i saw that thumbnail was broken and styles is chaotic in card div why not have a icon and filename in it just like this?
![image](https://user-images.githubusercontent.com/16607042/59495910-f236fb80-8ec2-11e9-84f4-a068fd583c70.png)

**Comment by zombieJ** [comment] 2019-06-17 04:15
`previewFile` don't deps on response. Just set it: https://codesandbox.io/s/delicate-smoke-bx4y7
And if current one do not satisfy requirements, you can design own preview list instead.

**Comment by dawnChen666** [comment] 2019-06-17 06:59
@zombieJ 看来我英语描述真的很不好
![image](https://user-images.githubusercontent.com/16607042/59581434-78438400-9107-11e9-8a2c-245fd9eef66a.png)
我试了你给的例子，图片上传的时候，没问题，红方格子里就是上传图片的缩略图，但是我又额外上传了一个非图片的文件，这种情况我想在管理系统中应该会很多，比如做财务系统的时候，需要申请人上传发票的照片，申请材料（doc）等等这种时候，非图片类型的缩略图会变成一个图片的标识加文件名，这样一方面会让人觉得这个明明是个图片标记但是没有缩略图，是不是图片上传失败了，其次，就算能正确理解没有缩略图的都是其他文件这个概念，整体的列表样式看上去也不够和谐，我只是请求说能不能自定义红框的内容，让开发者自己定义这个列表中每一个item的样式来保证界面传达出的意思是让人能够理解的比如doc文件都用<Icon type="file-word" />这个图标，ppt都用这个图标<Icon type="file-ppt" />来保证整个列表风格一致而不是一个缩略图一个像图片但是不是图片的样式，而且我还需要能够点击下载（注意是下载不是预览），这个组件的API也没有明确的属性可以使用，可能你们一开始设计的时候这个组件只是用来查看图片的吧。总之我只是给个建议，反正我用我自己的方式实现了我想要的，你们愿不愿意去扩展是你们的事情。

**Comment by zombieJ** [comment] 2019-06-17 07:33
上面那个例子就是传入后给出的缩略图是自定义的内容呀。`previewFile` 就是用来处理非图片类文件的预览。你可以判断文件类型给个 pdf 的图标，或者使用 服务端 / wasm 解析变成内容预览。

**Comment by dawnChen666** [comment] 2019-06-17 07:41
你给的例子里previewFile是antd的标志，你看我第一个框里的那个是个什么，另外图片类的预览是做不了自定义的是吗？

**Comment by Geylnu** [comment] 2019-12-23 03:00
我也遇到了这个问题，奇怪的是自己本地上传的paf显示的缩略图是一张图片，但是如果把url设置为上传后的链接就显示为一个文件了，有点奇怪
