### ISSUE TITLE
4.0 example of form - "complex form control" console warning/ 4.0的form的复杂布局会导致 warning

### ISSUE THREAD

**Issue by sunyum** [ant-design/ant-design#21733] opened 2020-03-01 11:06 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/run](https://stackblitz.com/run)

### Steps to reproduce
官网的例子，打开即可看到

### What is expected?
控制台无报错

### What is actually happening?
Form.Item 复杂布局使用 noStyle，控制台会报错  Warning: Cannot update a component from inside the function body of a different component
![image](https://user-images.githubusercontent.com/20025971/75624485-90a0f380-5bef-11ea-91b6-111c6d60c061.png)

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.13 |
| System | win10 |
| Browser | qq浏览器 |

**Comment by afc163** [comment] 2020-03-01 11:11
Your stackblitz link is empty.

**Comment by zombieJ** [comment] 2020-03-01 11:40
Duplicate of #21698

**Closed by zombieJ** 2020-03-01 11:40 UTC
Labels: 🤔 Need Reproduce
