### ISSUE TITLE
Table expandedRowRender triggers on mouse movement in the table

### ISSUE THREAD

**Issue by roelvdboom** [ant-design/ant-design#33342] opened 2021-12-17 10:39 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-table-expandedrowrender-keeps-rendering-on-hover-oonh8)

### Steps to reproduce
1. Create a Table with expandable rows and log each time the expandedRowRender function is called.
2. Hover over the table rows and view the log output.

### What is expected?
Only trigger the expandedRowRender function when the row is being expanded.

### What is actually happening?
The expandedRowRender function is being triggered on every mouse movement inside the table.

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 18.0.0 |
| System | Ubuntu 20.04 |
| Browser | Chrome |

---
Working correctly in version 4.16.13. Seems to be a problem since 4.17.0.

**Comment by roelvdboom** [comment] 2021-12-17 10:56
While doing some more investigation about this issue. The problem seems to be introduced in the following commit: https://github.com/ant-design/ant-design/commit/2bb9407f5f8555028a28a2b436cf351abd652ae6

The problem is introduced in `rc-table` version `7.19.0`. When upgrading `rc-table` to `7.21.0` the problem seems to be fixed.

**Comment by kid1412z** [comment] 2021-12-21 07:15
I have the same issue：
antd: 5.0.0
react :17.0.2
system: MacOS 11.4
Browser: Chrome

**Comment by tungphien** [comment] 2021-12-23 09:38
Still get the error re-render when update rc-table to 7.21.0 version. Any suggest for me pls

**Comment by roelvdboom** [comment] 2021-12-23 10:18
@tungphien use resolutions in your `package.json` file to temporarily upgrade the rc-table package to version 7.21.0 till they release a new ANTD version with the new rc-table version.

In your package.json add the following on root level.
```
"resolutions": {
    "antd/rc-table": "7.21.0"
}
```
Make sure to delete the resolution after upgrading to a new ANTD version.

**Comment by tungphien** [comment] 2021-12-24 02:19
![image](https://user-images.githubusercontent.com/28994477/147307540-0ef19b0e-2ef0-46ee-aef5-8b5d20fa77a4.png)
![image](https://user-images.githubusercontent.com/28994477/147307599-cf1c0456-86f7-42c9-b1a4-b0bdb59a3e76.png)
![image](https://user-images.githubusercontent.com/28994477/147307644-0a137431-4d00-4bc2-8351-86ae4094acf9.png)
![image](https://user-images.githubusercontent.com/28994477/147307703-ba2606ee-5f33-49d7-b069-af43099ddf90.png)
@roelvdboom 
Any ideal

**Comment by kid1412z** [comment] 2021-12-24 02:44
> ![image](https://user-images.githubusercontent.com/28994477/147307540-0ef19b0e-2ef0-46ee-aef5-8b5d20fa77a4.png) ![image](https://user-images.githubusercontent.com/28994477/147307599-cf1c0456-86f7-42c9-b1a4-b0bdb59a3e76.png) ![image](https://user-images.githubusercontent.com/28994477/147307644-0a137431-4d00-4bc2-8351-86ae4094acf9.png) ![image](https://user-images.githubusercontent.com/28994477/147307703-ba2606ee-5f33-49d7-b069-af43099ddf90.png) @roelvdboom Any ideal

I down grade Antd version to solve this problem temporarily.  In package.json: change to this: "antd": "~4.16.0",

**Comment by afc163** [comment] 2021-12-28 06:08
Fixed in 4.18.0: https://codesandbox.io/s/antd-table-expandedrowrender-keeps-rendering-on-hover-forked-38zvn

**Closed by afc163** 2021-12-28 06:08 UTC

**Comment by tungphien** [comment] 2021-12-29 02:44
![image](https://user-images.githubusercontent.com/28994477/147622523-b4242961-a123-4b2e-a6d6-d9fb10fe1df1.png)
https://codesandbox.io/s/antd-table-expandedrowrender-keeps-rendering-on-hover-forked-7wsr6?file=/index.js

**Comment by PauloMesquitaSP** [comment] 2022-02-09 19:53
The problem is still happening here
