### ISSUE TITLE
FormItem没有设置hasFeedback，但是当它包裹了一个 InputGroup，InputGroup里有Select时，Select 的箭头图标位置错误

### ISSUE THREAD

**Issue by maxmeng93** [ant-design/ant-design#20033] opened 2019-12-02 05:49 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/admiring-silence-8ktks)

### Steps to reproduce
FormItem没有设置hasFeedback，但是当它包裹了一个 InputGroup，InputGroup里有Select时，Select 的箭头图标位置错误

请看以下GIF演示
![image](https://raw.githubusercontent.com/maxmeng93/picee/master/bug/antd-bug1.ls3ktii2jqk.gif)

### What is expected?
Select 的箭头图标位置正确，没有偏移

### What is actually happening?
Select 的箭头图标位置错误，向左偏移，空了一个validateStatus图标的位置

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.12.0 |
| System | windows 10 |
| Browser | chrome |

---
关联问题 https://github.com/ant-design/ant-design/issues/19741

**Comment by afc163** [comment] 2019-12-02 05:52
Duplicate of #19741

**Closed by afc163** 2019-12-02 05:52 UTC
