### ISSUE TITLE
The Datepicker supports continuous multi-select

### ISSUE THREAD

**Issue by pdsuwwz** [ant-design/ant-design#13604] opened 2018-12-13 04:43 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Multi-range month query data

### What does the proposed API look like?
<DatePicker.MonthPicker
  multi={true}
/>

**Comment by afc163** [comment] 2018-12-13 05:40
Duplicate of #4447

**Closed by afc163** 2018-12-13 05:40 UTC
