### ISSUE TITLE
Select多选模式下当Option多于300个时操作会有明显卡顿

### ISSUE THREAD

**Issue by mytEcust** [ant-design/ant-design#16088] opened 2019-04-15 07:21 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l4qwlnj959)

### Steps to reproduce
```javascript
import React from "react";
import ReactDOM from "react-dom";
import { version, Select } from "antd";

const { Option } = Select;

const optionList = Array(300).fill("test");

ReactDOM.render(
  <div className="App">
    <div>
      <Select
        style={{ marginTop: "16px", width: "120px" }}
        optionFilterProp="children"
        mode="multiple"
      >
        {optionList.map((item, idx) => {
          return <Option key={idx}>{item}</Option>;
        })}
      </Select>
    </div>
  </div>,
  document.getElementById("root")
);

```

### What is expected?
在500个以内的多选可以流程进行？

### What is actually happening?
卡顿严重？

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.6 |
| System | Ubuntu 14 |
| Browser | chrome 64.0.3282.119 |

**Comment by afc163** [comment] 2019-04-15 07:39
Duplicate of #15620

**Closed by afc163** 2019-04-15 07:39 UTC
