### ISSUE TITLE
antd v4 table 固定表头，当点击menu去展开和收缩侧边路游栏，表头跟表内容对不齐 

### ISSUE THREAD

**Issue by wangxingxing123654** [ant-design/ant-design#22656] opened 2020-03-27 05:54 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/introduce-cn](https://ant.design/docs/react/introduce-cn)

### Steps to reproduce
antd v4 table 固定表头，当点击menu去展开和收缩侧边路游栏，表头跟表内容对不齐 

### What is expected?
antd v4 table 固定表头，当点击menu去展开和收缩侧边路游栏，表头跟表内容对齐 

### What is actually happening?
antd v4 table 固定表头，当点击menu去展开和收缩侧边路游栏，表头跟表内容对不齐 

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16 |
| System | mac  |
| Browser | chrome |

**Comment by afc163** [comment] 2020-03-27 05:55
Duplicate of https://github.com/ant-design/pro-table/issues/257

**Closed by afc163** 2020-03-27 05:55 UTC
