### ISSUE TITLE
🐛 [BUG] Form验证信息出现上下跳动

### ISSUE THREAD

**Issue by jianhuagao** [ant-design/ant-design#35267] opened 2022-04-27 06:51 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6t9kb9)

### Steps to reproduce

1.在必填项输入内容
2.删除内容 出现必填验证
3.反复步骤1和2 出现上下跳动

### What is expected?

不抖动

### What is actually happening?

上下抖动

| Environment | Info |
| --- | --- |
| antd | 4.20.0 |
| React | 18.0 |
| System | Windows10 |
| Browser | Microsoft Edge 100.0.1185.50 (正式版本) (64 位) |

![dba26aaa-727f-4189-9714-b45f7da241aa](https://user-images.githubusercontent.com/39371828/165458649-725c3c77-ea83-4018-a293-5607768fdc04.gif)

**Comment by afc163** [comment] 2022-04-27 06:52
Duplicate of https://github.com/ant-design/ant-design/issues/34267

**Closed by afc163** 2022-04-27 06:52 UTC
