### ISSUE TITLE
能否适配vite

### ISSUE THREAD

**Issue by lht931942788** [ant-design/ant-design#27585] opened 2020-11-05 13:04 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
vite环境使用antd

**Comment by xrkffgg** [comment] 2020-11-06 01:13
vite 不是 vue 系列的么。。。

你可以用 antdv

**Comment by afc163** [comment] 2020-11-06 02:03
Duplicate of #26090

**Closed by afc163** 2020-11-06 02:03 UTC
