### ISSUE TITLE
Select光标聚焦在dropdownRender区域每触发一次删除，选中的选项就会被删除一个

### ISSUE THREAD

**Issue by 3764446961** [ant-design/ant-design#50717] opened 2024-09-05 02:02 UTC
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-x5wh9c-dzg8pz?file=demo.tsx)

### Steps to reproduce

在input中触发删除，下拉框选中的选项被删除

### What is expected?

选中的选项不被删除

### What is actually happening?

在input中触发删除，下拉框选中的选项被删除

| Environment | Info |
| --- | --- |
| antd | 5.20.5 |
| React | 18 |
| System | macos |
| Browser | chrome |

**Comment by 3764446961** [comment] 2024-09-05 02:02
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/81083ad2-efed-4d6f-a3d9-05934c18f66b">

**Comment by afc163** [comment] 2024-09-05 02:05
https://github.com/ant-design/ant-design/issues/36670#issuecomment-1193141547

**Comment by afc163** [comment] 2024-09-05 02:06
Duplicate of https://github.com/ant-design/ant-design/issues/28694

**Closed by afc163** 2024-09-05 02:05 UTC
Labels: unconfirmed
