### ISSUE TITLE
Table组件 rowSelection存在的时候，没有竖向滚动条时，选中的时候，√未居中对齐，偏左了

### ISSUE THREAD

**Issue by frank7755** [ant-design/ant-design#18171] opened 2019-08-08 10:04 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
body overflow 设置成hidden

### What is expected?
√居中对齐

### What is actually happening?
√居左

| Environment | Info |
|---|---|
| antd | 3.21.2 |
| React | 3.21.1 |
| System | window 10 |
| Browser |  75.0.3770.142（正式版本） （64 位） |

![image](https://user-images.githubusercontent.com/16550396/62694404-d6555f00-ba06-11e9-84a2-99cc89ef7403.png)
![image](https://user-images.githubusercontent.com/16550396/62694451-f08f3d00-ba06-11e9-8903-8c534d4061ee.png)

**Comment by afc163** [comment] 2019-08-08 10:11
Duplicate of #16695

**Closed by afc163** 2019-08-08 10:11 UTC
