### ISSUE TITLE
Modal incorrectly closes on mouseup

### ISSUE THREAD

**Issue by ascendedguard** [ant-design/ant-design#28098] opened 2020-11-30 18:40 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/#components-form-demo-form-in-modal](https://ant.design/components/form/#components-form-demo-form-in-modal)

### Steps to reproduce
1. Click on New Collection to open modal
2. Type any text into the "Title" textbox.
3. Highlight the entered text from right to left, ending the highlight with a mouseup outside of the modal.

### What is expected?
Text should be highlighted and dialog remains open.

### What is actually happening?
The dialog closes as if the user had clicked outside.

| Environment | Info |
|---|---|
| antd | 4.8.6 |
| React | React 16.14.0 |
| System | Windows 10 v2004 |
| Browser | Chrome 86.0 |

---
We only saw this issue after upgrading from 4.5.1, which does not have this issue. There are other people also reporting this issue in the comments on the following issue: https://github.com/ant-design/ant-design/issues/15891

**Comment by marianayap** [comment] 2020-11-30 19:40
@ascendedguard Hey! can I take this issue?

**Comment by ascendedguard** [comment] 2020-11-30 20:08
> @ascendedguard Hey! can I take this issue?

Not up to me - I'm not with the AntD team.

**Comment by afc163** [comment] 2020-12-01 03:39
Duplicate of #27391

**Comment by marianayap** [comment] 2020-12-01 03:54
> Duplicate of #27391

Is there any other issue similar to this one that I could work on? @afc163

**Comment by afc163** [comment] 2020-12-01 03:56
@marianayap PR welcome~

**Comment by marianayap** [comment] 2020-12-01 04:10
@afc163 Okay, I'll work on it and open a PR

**Comment by afc163** [comment] 2020-12-03 04:08
Fixed in https://github.com/react-component/dialog/pull/210

**Closed by afc163** 2020-12-03 04:08 UTC
