### ISSUE TITLE
Sider Menu opens Popup when changing window size

### ISSUE THREAD

**Issue by mleister97** [ant-design/ant-design#36374] opened 2022-07-04 14:51 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jxdr9r?file=/index.js)

### Steps to reproduce

Resize the browser window.

### What is expected?

There should not be an open popup

### What is actually happening?

When resizing the browser a popup menu containing all items in children is opened. The bug only occurs if children are used in the menu.

| Environment | Info |
| --- | --- |
| antd | 4.21.5 |
| React | 17.0.2 |
| System | Windows 11 |
| Browser | Latest Chrome |

**Comment by mleister97** [comment] 2022-07-04 14:52
![image](https://user-images.githubusercontent.com/16700053/177178471-c46de1f2-172d-42da-a9bd-a810eb20f15a.png)

After resizing the window

**Comment by afc163** [comment] 2022-07-04 15:05
Duplicate of #36152

**Closed by afc163** 2022-07-04 15:05 UTC
