### ISSUE TITLE
Performance issues of Table filterDropdown with large datasources

### ISSUE THREAD

**Issue by emirozmen07** [ant-design/ant-design#50422] opened 2024-08-14 13:13 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ant-table-custom-filter-dropdown-forked-kw2fyd?workspaceId=d6a6dad2-227b-4f4b-92f7-4f43a3ea46a1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clztunbon00073b6j1recyc53%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clztunbon00033b6jx36x8ixu%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clztunbon00043b6j74we77cr%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clztunbon00063b6jwi57xizr%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clztunbon00033b6jx36x8ixu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clztunbon00023b6jq2v8uufk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A79%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponent%252FFilterTable.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clztunbon00033b6jx36x8ixu%2522%252C%2522activeTabId%2522%253A%2522clztunbon00023b6jq2v8uufk%2522%257D%252C%2522clztunbon00063b6jwi57xizr%2522%253A%257B%2522id%2522%253A%2522clztunbon00063b6jwi57xizr%2522%252C%2522activeTabId%2522%253A%2522clztv53sx000v3b6i4574o6mt%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clztunbon00053b6jpv08z64s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clztupurn001i3b6ic4wj9v92%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522CHANGELOG%2522%252C%2522id%2522%253A%2522clztv3mx2007l3b6ifsjm6cm1%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clztv53sx000v3b6i4574o6mt%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clztunbon00043b6j74we77cr%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clztunbon00043b6j74we77cr%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

Create a table with large datasource (over 2000), then try to filter one of the columns where number of filters is higher than 2000. Selecting elements is very hard because it's freezing. If you select around 30 elements and select ok, it will freeze and won't make the search.  (see "age" column in code sandbox)

If there are small amount of elements in the filter (let's say 30) and you select all, there is no issue at all. (See "name column")

### What is expected?

It should be more efficient and shouldn't freeze.

### What is actually happening?

It freezes when there are many elements in the filter.

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 17.0.2 |
| System | macosx |
| Browser | chrome |

---
I tried to create a custom filterdropdown with antd select component and it works very fast without freezing. But when I select the filters and run the filter by calling the default "confirm()" function it freezes again. So visualization issues can be fixed very easily but about actual filtering I don't know.

**Comment by stefann01** [comment] 2024-08-16 12:20
I am curious why would you have 2000 data entities on the frontend at the same time. I believe a server should be responsible for searching / filtering

**Comment by emirozmen07** [comment] 2024-08-16 12:29
You are absolutely correct. But still, I'm wondering if it's possible to optimize.

**Comment by MadCcc** [comment] 2024-08-21 08:37
Dropdown do not support virtual list currently.

**Comment by emirozmen07** [comment] 2024-08-23 12:39
Can we somehow override the confirm function with a custom function?

**Comment by afc163** [comment] 2024-08-23 13:37
Duplicate of https://github.com/ant-design/ant-design/issues/41863

**Closed by afc163** 2024-08-23 13:37 UTC
Labels: 💡 Feature Request, unconfirmed
