### ISSUE TITLE
Age sorting for group table is not working

### ISSUE THREAD

**Issue by ckalarickal** [ant-design/ant-design#50200] opened 2024-08-02 06:47 UTC
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/run?file=demo.tsx)

### Steps to reproduce

Just clicked the age sorting column and  its not working

### What is expected?

To sort the column (ascending or descending)

### What is actually happening?

No event of sorting is getting triggered when clicked.

| Environment | Info |
| --- | --- |
| antd | 5.19.4 |
| React | React |
| System | Windows |
| Browser | Chrome |

---
Please fix it as soon as possible

**Comment by yoyo837** [comment] 2024-08-02 07:14
Duplicate of https://github.com/ant-design/ant-design/issues/50154 and https://github.com/ant-design/ant-design/issues/50084

**Closed by yoyo837** 2024-08-02 07:14 UTC
Labels: unconfirmed

**Comment by ckalarickal** [comment] 2024-08-02 07:33
@yoyo837 is the fix pushed because the issue is still there

**Comment by yoyo837** [comment] 2024-08-02 07:35
> @yoyo837 is the fix pushed because the issue is still there

Please wait for the next patch release.

**Comment by ckalarickal** [comment] 2024-08-02 07:40
@yoyo837 And that would be on which date ?

**Comment by yoyo837** [comment] 2024-08-02 07:44
> @yoyo837 And that would be on which date ?

See https://ant.design/changelog#release-schedule, Barring any unforeseen circumstances, it will arrive over the weekend, or at the latest next Monday.

**Comment by spiderT** [comment] 2024-08-05 15:35
> > @yoyo837 And that would be on which date ?
> 
> See https://ant.design/changelog#release-schedule, Barring any unforeseen circumstances, it will arrive over the weekend, or at the latest next Monday.

It is not fix in version 5.20, cannot sort in group  table
