### ISSUE TITLE
InputNumber的formatter属性无法根据当前focus或者blur的状态改变

### ISSUE THREAD

**Issue by sanheart** [ant-design/ant-design#39814] opened 2022-12-26 07:17 UTC
### Reproduction link

[https://stackblitz.com/edit/react-88e1lk?file=demo.tsx](https://stackblitz.com/edit/react-88e1lk?file=demo.tsx)

### Steps to reproduce

1. inputnumber focused时候，改变 state focus的值
2. 当focus是 true时，展示value，当focus是false时，展示`${value}%`

### What is expected?

1. inputnumber focused时候，改变 state focus的值
2. 当focus是 true时，展示value，当focus是false时，展示`${value}%`

### What is actually happening?

1. inputnumber focused时候，改变 state focus的值
2. onFocus后，展示的是`${value}%`, 再失去焦点后，focus是 false，但展示的是value

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17 |
| System | mac os 11.5.2  |
| Browser | chrome  100.0.4896.127 |

**Comment by afc163** [comment] 2022-12-26 07:22
Duplicate of #31431

**Closed by afc163** 2022-12-26 07:22 UTC

**Comment by sanheart** [comment] 2022-12-26 08:41
> Duplicate of #31431

但是调用inputNumber的onFocus和onBlur方法去改变formatter，并不生效。
