### ISSUE TITLE
DatePicker has Radio.Button in renderExtraFooter auto close after choose

### ISSUE THREAD

**Issue by VibrateEntire** [ant-design/ant-design#45165] opened 2023-10-03 09:19 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xenodochial-bouman-9n8c4w)

### Steps to reproduce

As in sandbox, 
Using DatePicker, RangePicker 
Add a Radio to extra footer

### What is expected?

The Radio group won't close the interface when click like button version

### What is actually happening?

It close the interface after click

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 18 |
| System | Window 10 |
| Browser | Microsoft Edge |

---
This bug is very specific, but I hope it will get fix soon.
The temporary solution I use is re focus to the field as soon as it close. However, it is impossible to debug and feel irritation to debug.

**Comment by Yuiai01** [comment] 2023-10-06 12:58
This may be related to focus shifting.

**Comment by afc163** [comment] 2023-10-07 02:00
Duplicate of #33125

**Closed by afc163** 2023-10-07 02:00 UTC
Labels: unconfirmed
