### ISSUE TITLE
treeSelect下拉菜单树节点显示的内容过长时文字换行显示

### ISSUE THREAD

**Issue by scyuanhui** [ant-design/ant-design#28771] opened 2021-01-08 05:45 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yibujiazai-antd4100-forked-owbo7?file=/index.js)

### Steps to reproduce
点击子节点异步加载数据

### What is expected?
下拉菜单树节点显示的内容过长时文字不换行显示

### What is actually happening?
下拉菜单树节点显示的内容过长时文字换行显示

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17.0.1 |
| System | win10 |
| Browser |  谷歌：87.0.4280.88 |

**Comment by afc163** [comment] 2021-01-08 08:36
Duplicate of #28772

**Closed by afc163** 2021-01-08 08:36 UTC
