### ISSUE TITLE
Table前后固定列，其它的行高发生变化，fixed列高未变化。

### ISSUE THREAD

**Issue by TimbokY** [ant-design/ant-design#18231] opened 2019-08-12 13:47 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-edit-cell](https://ant.design/components/table-cn/#components-table-demo-edit-cell)

### Steps to reproduce
前后固定列，行高发生变化，fixed列高未变化。

### What is expected?
fixed列能岁行高变化而变化

### What is actually happening?
暂未解决

| Environment | Info |
|---|---|
| antd | 3.7.3 |
| React | >=16.0.0 |
| System | MacOs |
| Browser | "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36" |

**Comment by TimbokY** [comment] 2019-08-12 13:48
<img width="1404" alt="WeChatbe4378a9ba4d5e16429b85afd5fbc30c" src="https://user-images.githubusercontent.com/33300474/62869675-df1d9c00-bd4a-11e9-9ce1-1d7aa1b8d0a8.png">
看截图

**Comment by afc163** [comment] 2019-08-13 03:47
Duplicate of #14859

**Closed by afc163** 2019-08-13 03:47 UTC
