### ISSUE TITLE
3.24.x版本Table设置sortOrder导致死循环

### ISSUE THREAD

**Issue by soradaisuke** [ant-design/ant-design#19520] opened 2019-11-01 04:07 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/currying-water-c09n0?fontsize=14)

### Steps to reproduce
点击Name列排序

### What is expected?
正常排序

### What is actually happening?
死循环，白屏

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | 16 |
| System | Mac |
| Browser | Chrome |

---
1. 远程加载数据
2. sortOrder希望由外界控制

初步观察是因为getDerivedStateFromProps每次生成新的columns，导致componentDidUpdate死循环

```javascript
static getDerivedStateFromProps(nextProps: InternalTableProps<any>, prevState: TableState<any>) {
    const { prevProps } = prevState;
    const columns =
      nextProps.columns || normalizeColumns(nextProps.children as React.ReactChildren);
}
```

```javascript
componentDidUpdate() {
    const { columns, sortColumn, sortOrder } = this.state;
    if (this.getSortOrderColumns(columns).length > 0) {
      const sortState = this.getSortStateFromColumns(columns);
      if (sortState.sortColumn !== sortColumn || sortState.sortOrder !== sortOrder) {
        this.setState(sortState);
      }
    }
  }
```

**Comment by afc163** [comment] 2019-11-01 04:12
Duplicate of #19443

**Closed by afc163** 2019-11-01 04:12 UTC
