### ISSUE TITLE
Select all (rows) checkbox in table resets sorting

### ISSUE THREAD

**Issue by hon2a** [ant-design/ant-design#12581] opened 2018-10-10 12:30 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
MacOS 10.13.6, Chrome 69.0.3497.100 (64-bit)

### Reproduction link
[https://codepen.io/hon2a/pen/NOpQwx?&editors=001](https://codepen.io/hon2a/pen/NOpQwx?&editors=001)

### Steps to reproduce
- Create a `Table` with both column sorting and row selection.
- Sort the table by some sortable column.
- Click on the "Select all" checkbox in the top left corner of the table to select all rows at once.

### What is expected?
All rows are selected and the current sorting is retained.

### What is actually happening?
Rows are selected, but the sorting is lost (reset). Additionally, when the "Select all" checkbox is hovered over, a _"Sort"_ tooltip is shown, which shouldn't be there.

**Comment by notdrone** [comment] 2018-10-10 23:03
checking if columnKey isn't a `selection-column` before changing state might be a temporary fix
```js
handleChange = (pagination, filters, sorter) => {
    console.log('Various parameters', pagination, filters, sorter);
    if(sorter.columnKey!=='selection-column'){
      this.setState({
        sortedInfo: sorter,
        filteredInfo: filters,
      });
    }
  }
```

**Comment by zombieJ** [comment] 2018-10-15 01:36
fixed in [419287de](https://github.com/ant-design/ant-design/commit/419287de2b467486c06fcf4e5eb576861b8bc84b)

**Closed by zombieJ** 2018-10-15 01:36 UTC

**Comment by hon2a** [comment] 2018-10-15 08:28
@zombieJ : I don't see any fix for the _"Sort"_ tooltip (a `title` attribute somewhere) being shown on the selection column header hover in 419287de. (See the second part of _"What's actually happening?"_ in ticket description.)

**Comment by zombieJ** [comment] 2018-10-15 12:08
Hi @hon2a ,
The root cause of this issue is that code not check column is sortable when click the header. So I ref it to the commit.

Tooltip update is here: https://github.com/ant-design/ant-design/commit/f1d1d87de08eadaa00f3d4c3c302f16e77ea8020

**Comment by RichieChoo** [comment] 2018-10-17 02:19
I met this bug,too

**Comment by nitingupta220** [comment] 2020-10-14 07:43
<img width="1212" alt="Screenshot 2020-10-14 at 1 11 35 PM" src="https://user-images.githubusercontent.com/25584421/95958461-cc0ace00-0e1e-11eb-831e-e6d610daec93.png">
I'm using ant.design table and I have couple of items pre-selected. I want these items to be on top of the table so anyone can see the items which are selected. 
I want to sort the table based on the selection of items.
Can anyone help in this?

**Comment by nitingupta220** [comment] 2020-10-14 12:20
@zombieJ Can you help me in this issue?
