### ISSUE TITLE
Switch to end date section when using range picker with showTime: true

### ISSUE THREAD

**Issue by hosseind88** [ant-design/ant-design#35851] opened 2022-06-01 05:33 UTC
### What problem does this feature solve?

now if you want to show time in range picker, then you need to manually click on end date section to switch between. I want to see that is there any way to let developer make it automatic. I mean when I set start date, without clicking on Ok button or end date text, rangepicker switch to end date section.

and also like version 3.x , I want that when user selects the date and clicks outside of range picker, it don't lose it's value 

### What does the proposed API look like?

like the feature description

**Comment by MadCcc** [comment] 2022-06-06 06:48
Duplicate of https://github.com/ant-design/ant-design/issues/27779

**Closed** 2022-06-06 06:48 UTC
