### ISSUE TITLE
RangePicker start date input cleared after typing when using in React-table

### ISSUE THREAD

**Issue by ichirukia1566** [ant-design/ant-design#17635] opened 2019-07-15 03:04 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/agitated-jang-oxd6s)

### Steps to reproduce
Use RangePicker as a custom filter in React-table, type a valid start date.

### What is expected?
The start date is highlighted in the calendar, and the input is displayed properly. User should be able to select end date by typing as well.

### What is actually happening?
Although the date is correctly selected, I try to type an end date. The start date is then cleared and the end date cannot be handled properly.

![rangePicker](https://user-images.githubusercontent.com/5390408/61193799-40bcfd00-a6f0-11e9-8902-cb7468a9d154.gif)

| Environment | Info |
|---|---|
| antd | 3.20.2 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Chrome 74.0.3729.131 |

---
I do notice that this is a possible duplicate (except that I am using it in React-table instead of in a Form) of [#15673](https://github.com/ant-design/ant-design/issues/15673), but it hasn't been fixed yet and I can't use the proposed downgrade solution since I'm using hooks which requires React 16.8. May I know whether this will be fixed or is there any other solution to it? Thank you.

**Comment by zombieJ** [comment] 2019-07-15 08:53
Duplicate of #15673

**Closed by zombieJ** 2019-07-15 08:53 UTC
