### ISSUE TITLE
表格拖拽列进行伸缩后会自动触发排序

### ISSUE THREAD

**Issue by PeiTianHuang** [ant-design/ant-design#21888] opened 2020-03-05 02:24 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gallant-flower-ijzyq)

### Steps to reproduce
列配置中添加sorter: true后拖拽表格列，释放鼠标后可看到排序触发了

### What is expected?
只伸缩列，不触发排序，因为排序变更会触发数据请求

### What is actually happening?
触发了排序，导致数据更新

| Environment | Info |
|---|---|
| antd | 3.26.12 |
| React | 16.12.0 |
| System | windows10 |
| Browser | chrome69 |

**Comment by afc163** [comment] 2020-03-05 05:17
Duplicate of #14647

**Closed by afc163** 2020-03-05 05:17 UTC
