### ISSUE TITLE
option组件遍历8个时会报警告

### ISSUE THREAD

**Issue by wuchuheng** [ant-design/ant-design#27413] opened 2020-10-27 14:57 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-gx6j5f](https://stackblitz.com/edit/react-gx6j5f)

### Steps to reproduce
当我用for 遍历出Option 刚好8个时，并点击下拉框时，就会报出警告，内容为：Warning: `NaN` is an invalid value for the `top` css style property.
，如果不是8个则不会，这是我的复现代码地址：https://stackblitz.com/edit/react-gx6j5f 。

### What is expected?
不想出现这个错误警告

### What is actually happening?
错误警告

| Environment | Info |
|---|---|
| antd | undefined |
| React | react/ant |
| System | windows 10 |
| Browser | chrome |

**Comment by yoyo837** [comment] 2020-10-27 15:01
Duplicate of #27282

**Closed by yoyo837** 2020-10-27 15:01 UTC
