### ISSUE TITLE
Can`t connect notification to redux

### ISSUE THREAD

**Issue by WojtekMasiukiewicz** [ant-design/ant-design#20902] opened 2020-01-14 13:24 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-f5iv4)

### Steps to reproduce
# create antd notification with open method
# connect description component to redux store

### What is expected?
get access to redux store from components inside notification

### What is actually happening?
actualy i got error:
*Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Notification (created by TestComponent)*

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 16.12.0 |
| System | Ubuntu 18.04 |
| Browser | Chrome Version 79.0.3945.88 (Official Build) (64-bit) |

**Comment by yoyo837** [comment] 2020-01-15 07:45
Maybe duplicate of #14101.

**Comment by afc163** [comment] 2020-01-15 09:25
Duplicate of #14101

**Closed by afc163** 2020-01-15 09:25 UTC
