### ISSUE TITLE
edge浏览器  table固定列、选择框列 无法显示边框（分割线）。。。

### ISSUE THREAD

**Issue by kangkang12** [ant-design/ant-design#26615] opened 2020-09-07 06:21 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns](https://ant.design/components/table-cn/#components-table-demo-fixed-columns)

### Steps to reproduce
edge浏览器打开antd官方文档组件库。table。固定列。

### What is expected?
和chrome、ff显示一致

### What is actually happening?
固定列和选择框列无边框（分割线）。。。

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | W10 |
| Browser | edge |

**Comment by kangkang12** [comment] 2020-09-07 06:22
![image](https://user-images.githubusercontent.com/34826299/92354806-984cd200-f115-11ea-8dab-d4a26e3c2c9a.png)

**Comment by afc163** [comment] 2020-09-07 06:23
Duplicate of #22439

**Closed by afc163** 2020-09-07 06:23 UTC
