### ISSUE TITLE
Is there any way to make TD highly adaptive, only two or three data will auto occupy table, and larges data will be scrolled

### ISSUE THREAD

**Issue by Homebrew1** [ant-design/ant-design#31260] opened 2021-07-05 02:17 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Is there any way to make TD highly adaptive, only two or three data will occupy table, and larges data will be scrolled

### What does the proposed API look like?
<a-table autoContentHeight />

**Comment by Homebrew1** [comment] 2021-07-05 02:19
I proposed API : <a-table autoContentHeight />

**Comment by afc163** [comment] 2021-07-05 11:35
Duplicate of #29082

**Closed by afc163** 2021-07-05 11:35 UTC
