### ISSUE TITLE
table 能否增加支持斑马纹。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#24811] opened 2020-06-07 16:49 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以在视觉上面减少疲劳，如果一个表格有100条数据，看上去就很费眼睛，我以前3.0是自己写的斑马纹，但是我认为这个应该有必要增加到table 默认的属性里面

### What does the proposed API look like?
stripe = false或者 stripe = true

**Comment by zombieJ** [comment] 2020-06-08 01:52
Duplicate of #6506

**Closed by zombieJ** 2020-06-08 01:52 UTC
