### ISSUE TITLE
Need to remove reset rows option while table sorting 

### ISSUE THREAD

**Issue by miyamirz** [ant-design/ant-design#20004] opened 2019-11-29 06:52 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
(if default sort order is 'descend')-
first click of column , the rows reset
second click of column - the rows ascend
third click of column - the rows descend
I donot want the reset behaviour. I need just the ascend and descend. Is there any way?

### What does the proposed API look like?
I do not have any POC

**Comment by yoyo837** [comment] 2019-11-29 07:11
It's by design.

**Comment by miyamirz** [comment] 2019-11-29 07:12
@yoyo837 are there any workarounds?

**Comment by afc163** [comment] 2019-11-29 09:23
Duplicate of #19334

**Closed by afc163** 2019-11-29 09:23 UTC
