### ISSUE TITLE
Tabs 点击内容出现了选中状态

### ISSUE THREAD

**Issue by BugHiding** [ant-design/ant-design#22820] opened 2020-04-01 09:15 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-ant-design-demo-l1j64)

### Steps to reproduce
1.  点击`Tabs`中的内容
2.  出现了选中状态

### What is expected?
不出现选中状态`antd 4.0.4`
![4](https://user-images.githubusercontent.com/6602889/78120323-499b5d80-743c-11ea-950d-1396fe45bb27.gif)

### What is actually happening?
出现了选中状态 `antd 4.1.0`
![3](https://user-images.githubusercontent.com/6602889/78120244-2b356200-743c-11ea-8fe1-843a5ad8f596.gif)

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.1 |
| System | macOS 10.15.4 |
| Browser | Chrome 80.0.3987.149 |

**Comment by afc163** [comment] 2020-04-01 09:18
Duplicate of #22760

**Closed by afc163** 2020-04-01 09:18 UTC
