### ISSUE TITLE
Two input numbers with max props inside a Form

### ISSUE THREAD

**Issue by Ancinek** [ant-design/ant-design#8652] opened 2017-12-18 14:51 UTC
### Version
3.0.2

### Environment
MacOS HighSierra (10.13.1), Chrome Version 63.0.3239.84 (Official Build) (64-bit)

### Reproduction link
[https://codesandbox.io/s/6zznm37y13](https://codesandbox.io/s/6zznm37y13)

### Steps to reproduce
Click on the first InputNumber and change the value to the possible max (150), then try to switch the InputNumber by clicking on the next one. You can't do this as it keeps coming back to the first one.

### What is expected?
Switching between InputNumber components within a form.

### What is actually happening?
Can't switch if the value is equal to `max`.

**Comment by afc163** [comment] 2017-12-19 01:37
Duplicate of #8557

**Comment by afc163** [comment] 2017-12-21 13:01
Fixed in https://github.com/ant-design/ant-design/issues/8592 , try reinstall node_modules.

**Closed by afc163** 2017-12-21 13:01 UTC
Labels: Component: InputNumber
