### ISSUE TITLE
`renderExtraFooter` not working when `mode` is `year` 

### ISSUE THREAD

**Issue by hulubo** [ant-design/ant-design#13711] opened 2018-12-19 07:00 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ywmm7n5919)

### Steps to reproduce
`renderExtraFooter` not working when `mode` is `year` 

### What is expected?
What is returned in the renderExtraFooter method should be rendered in the panel.

### What is actually happening?
`renderExtraFooter` not working when `mode` is `year`

**Comment by afc163** [comment] 2018-12-21 12:31
Duplicate of #11618

**Closed by afc163** 2018-12-21 12:31 UTC
