### ISSUE TITLE
sortOrder   resizable issue

### ISSUE THREAD

**Issue by AlwaysBeOk** [ant-design/ant-design#15348] opened 2019-03-12 11:38 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l7lm059pvm)

### Steps to reproduce
拖拽第一列

### What is expected?
拖拽第一列，排序不会被触发，但实际情况是拖拽的时候，也触发了排序。

### What is actually happening?
实际情况是拖拽的时候，也触发了排序。

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.2.0 |
| System | mac os |
| Browser | chrome |

**Comment by afc163** [comment] 2019-03-12 11:43
Duplicate of #14647

**Closed by afc163** 2019-03-12 11:43 UTC

**Comment by AlwaysBeOk** [comment] 2019-03-12 12:40
it`s not work
