### ISSUE TITLE
[ResizeBox/伸缩框] 功能需求，希望增加这个组件！

### ISSUE THREAD

**Issue by kwooshung** [ant-design/ant-design#45435] opened 2023-10-19 16:39 UTC
### What problem does this feature solve?

这个功能我认为也是非常常用的，不仅可以分割面板！
例如：可以轻松做到输入框往下拉，即可修改输入框高度。十分灵活的一个功能。
据我所知目前仅 Arco Design 有这个功能。

### What does the proposed API look like?

具体参考API地址：https://arco.design/react/components/resize-box

> 同类产品issues
https://github.com/Tencent/tdesign-react/issues/2313

**Comment by JSchmidt63** [comment] 2023-10-27 14:11
discussions Question? Create some ResizeBox like arco.design? #33757
discussions Add component Splitter splitter #43554

**Comment by afc163** [comment] 2023-10-29 07:03
Duplicate of #44525

**Closed by afc163** 2023-10-29 07:03 UTC
Labels: 💡 Feature Request

**Comment by afc163** [comment] 2024-09-24 02:14
Supported in https://github.com/ant-design/ant-design/pull/50038
