### ISSUE TITLE
在系统放大或浏览器放大时 Table 有横向滚动条，滚动条拖动到最后，右侧阴影不会消失

### ISSUE THREAD

**Issue by ty-bt** [ant-design/ant-design#28770] opened 2021-01-08 03:42 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gudinglie-antd4100-forked-wxujo)

### Steps to reproduce
放大125%后，吧浏览器窗口调小，滚动条拉到最后面，然后慢慢拉宽浏览器，某些大小就会出现阴影

### What is expected?
滚动条拉到最后，后方阴影消失

### What is actually happening?
后方阴影依然存在

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.1 |
| System | window 10 |
| Browser | chrome  87.0.4280.141 |

**Comment by zombieJ** [comment] 2021-01-11 09:16
Duplicate of #25300

**Closed by zombieJ** 2021-01-11 09:16 UTC
