### ISSUE TITLE
New custom scroll in select is not working correctly

### ISSUE THREAD

**Issue by sntptrck** [ant-design/ant-design#26374] opened 2020-08-24 12:29 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-lpib7?file=/index.js)

### Steps to reproduce
1) Render select component with few options to show scrollbar
2) Open and select item and close several times to get bug with options render

### What is expected?
Options renders correctly, with native scrollbar

### What is actually happening?
options render incorrect

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.12 |
| System | Windows 10 |
| Browser | Chrome |

---
Custom scrollbar appers with 4.6 update and in older version too

![image](https://user-images.githubusercontent.com/25454834/91044822-94ea1e80-e61e-11ea-9424-11e10a42261a.png)

**Comment by xrkffgg** [comment] 2020-08-25 01:05
Duplicate of https://github.com/ant-design/ant-design/issues/26116

**Closed** 2020-08-25 02:50 UTC
Labels: 🐛 Bug, 👷🏻‍♂️ Someone working on it
