### ISSUE TITLE
React & ReactDom 18 beta support

### ISSUE THREAD

**Issue by Thanaen** [ant-design/ant-design#32898] opened 2021-11-16 14:48 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ant-design-react-18-lbk8j?file=/src/index.js)

### Steps to reproduce
Try to click on the dropdown or on the menu.
These actions are working on the React 17 fork of this codesandbox.

### What is expected?
https://codesandbox.io/s/ant-design-react-17-c2tx4?file=/src/index.js

### What is actually happening?
Dropdown and menu aren't working.
I haven't tested every antd component, only these two for now.

| Environment | Info |
|---|---|
| antd | 4.17.0 |
| React | 18 |
| System | Irrelevant |
| Browser | Irrelevant |

---
React 18 brings up several performance / DX improvements, I hope Ant Design will be able to keep up with this update 😄

**Comment by afc163** [comment] 2021-11-17 01:47
Duplicate of #26136

**Closed by afc163** 2021-11-17 01:47 UTC
