### ISSUE TITLE
Radio.Group内的子组件Radio如果包裹Select，则下拉菜单闪现后自动关闭

### ISSUE THREAD

**Issue by Jexecellent** [ant-design/ant-design#26495] opened 2020-08-31 06:51 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/practical-hodgkin-3r8w1?file=/index.js)

### Steps to reproduce
1. Radio.Group选择第四个more显示Select组件； 2. 点击select展开options后会闪现，然后马上关闭，导致select组件无法change;

### What is expected?
Radio.Group下的radio组件内可以正常使用select组件！

### What is actually happening?
Radio.Group下的radio组件内无法正常使用select组件

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.13.1 |
| System | windows 10 |
| Browser | 版本 84.0.4147.135（正式版本） （64 位） |

**Comment by afc163** [comment] 2020-08-31 06:55
Duplicate of #25959

**Closed by afc163** 2020-08-31 06:55 UTC
