### ISSUE TITLE
使用tab键到Select组件上不能直接输入

### ISSUE THREAD

**Issue by k983551019** [ant-design/ant-design#17834] opened 2019-07-24 02:49 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
使用tab键到Select组件上不能直接输入
![image](https://user-images.githubusercontent.com/48147837/61761197-879da780-ae00-11e9-829a-0abbc025b8d4.png)
获得焦点，但是此时不能输入，或者是输入没用
### What does the proposed API look like?
使用tab键到Select组件上可以直接输入
![image](https://user-images.githubusercontent.com/48147837/61761227-a308b280-ae00-11e9-9fcd-f39c118d5db0.png)
需要去点击一下，或者回车才可以输入搜索

**Comment by afc163** [comment] 2019-07-24 02:59
Duplicate of #14503

**Closed by afc163** 2019-07-24 02:59 UTC
