### ISSUE TITLE
Select - with showSearch enabled, autoFocus and focus() method doesn't focus the input

### ISSUE THREAD

**Issue by Moeface** [ant-design/ant-design#8486] opened 2017-12-07 00:47 UTC
### Version
3.0.0

### Environment
OSX Sierra 10.12.6, Chrome 62.0.3202.94, React 15.6.2

### Reproduction link
[https://codepen.io/anon/pen/XzwYrB](https://codepen.io/anon/pen/XzwYrB)

### Steps to reproduce
* Visit [this example codepen](https://codepen.io/anon/pen/XzwYrB) - This is the showSearch example from the docs with the autoFocus prop enabled

### What is expected?
The input should be focused so the user can start typing immediately

### What is actually happening?
The Select shows that it is active, with the blue outline visible, but the input is not actually focused and the user cannot type into the Select component without first clicking it.

---
This also happens when using the `focus()` method on the select. This only happens when `showSearch` is enabled.

**Comment by yesmeck** [comment] 2017-12-08 01:34
Duplicate of #8269

**Closed by yesmeck** 2017-12-08 01:34 UTC

**Comment by Moeface** [comment] 2017-12-08 02:38
Sorry, didn't see that when I searched. Thanks.
