### ISSUE TITLE
Form.Item with Upload, but  form.scrollToField Not effective

### ISSUE THREAD

**Issue by song-jz** [ant-design/ant-design#31579] opened 2021-07-29 07:19 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
<Form.Item
                            className="bbb"
                            label="label"
                            name="bbb"
                            rules={[{ required: true, message: 'rule' }]}
                            valuePropName="fileList"
                            getValueFromEvent={normFile}
                        >
                            <Upload name="bbb" {...upLoadProps}>
                                <Button icon={<UploadOutlined />}>upload</Button>
                            </Upload>
</Form.Item>

            form.validateFields()
            .then(info => {
               console.log('info', info)
            })
            .catch(error => {
                console.log('error', error)
                form.scrollToField(error['errorFields'][0]['name'][0], { behavior: 'smooth' })
            })

but submit this form with no content, form.scrollToField Not effective

### What is expected?
submit this form with no content, form.scrollToField scroll to field position

### What is actually happening?
submit this form with no content, form.scrollToField do not scroll to field position

| Environment | Info |
|---|---|
| antd | undefined |
| React | ^17.0.2 |
| System | IOS 10.15.5 |
| Browser | chrome |

**Comment by afc163** [comment] 2021-07-29 08:48
Duplicate of #28869

**Closed by afc163** 2021-07-29 08:48 UTC
