### ISSUE TITLE
CSS issues with Tooltip and Popover, Dropdown, Popconfirm arrows 

### ISSUE THREAD

**Issue by Stars0518** [ant-design/ant-design#36163] opened 2022-06-22 03:02 UTC
### Reproduction link

[https://ant.design/components/tooltip-cn/](https://ant.design/components/tooltip-cn/)

### Steps to reproduce

Move in or click on the box that appears, the arrow style above appears to be wrong

### What is expected?

Move or click the box that appears and the arrow style above appears

### What is actually happening?

Move in or click on the box that appears, the arrow style above appears to be wrong

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | 17.0.1 |
| System | windows |
| Browser | Chromium 86.0.4240.198 |

**Comment by afc163** [comment] 2022-06-22 03:15
Duplicate of #35010

**Closed by afc163** 2022-06-22 03:15 UTC
