### ISSUE TITLE
ant table什么时候能支持列拖动排序

### ISSUE THREAD

**Issue by doubleji** [ant-design/ant-design#20326] opened 2019-12-18 09:34 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用户有的时候想在页面上手动改变列的排序位置，例如想把第三列拖拽到第一列

### What does the proposed API look like?
<Table
          columns={columns}
          dataSource={this.state.data}
          suppressDragColumns=true
        />

**Comment by zcSkr** [comment] 2019-12-18 09:48
去年的时候支持

**Comment by afc163** [comment] 2019-12-18 09:49
Duplicate of #14138

**Closed by afc163** 2019-12-18 09:49 UTC
