### ISSUE TITLE
Option in Select repot 'missing import', but I declared Option

### ISSUE THREAD

**Issue by fikyair** [ant-design/ant-design#13246] opened 2018-11-22 09:22 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
2.13.9

### Environment
linux、版本 63.0.3239.132（正式版本）（64 位）

### Reproduction link
[https://github.com/fikyair/Ant-Design-Beta/blob/master/pic/cuowu.png](https://github.com/fikyair/Ant-Design-Beta/blob/master/pic/cuowu.png)

### Steps to reproduce
https://github.com/fikyair/Ant-Design-Beta/blob/master/pic/cuowu.png

### What is expected?
can't report bug

### What is actually happening?
Missing import statement

**Comment by yesmeck** [comment] 2018-11-22 10:04
Duplicate of #13247

**Closed by yesmeck** 2018-11-22 10:04 UTC
