### ISSUE TITLE
Form 布局layout='inline' 时， Input 加上 allowClear 属性，Input的宽度会改变

### ISSUE THREAD

**Issue by poyiding** [ant-design/ant-design#23256] opened 2020-04-14 13:03 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-ant-design-demo-y743s

### Steps to reproduce
Form 布局layout='inline' 时，Input 加上 allowClear 属性，Input的宽度会改变，3.x不会。

### What is expected?
 加上 allowClear ，Input 宽度不变

### What is actually happening?
 加上 allowClear ，Input 宽度改变

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | ^16.12.0" |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment] 2020-04-14 13:23
Duplicate of #22562

**Closed by zombieJ** 2020-04-14 13:23 UTC
