### ISSUE TITLE
Input prefix suffix style 

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#20831] opened 2020-01-11 02:45 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/input-cn/#components-input-demo-presuffix](https://next.ant.design/components/input-cn/#components-input-demo-presuffix)

### Steps to reproduce
Enter large amount of text.Prefix two texts have the same problem.
![image](https://user-images.githubusercontent.com/8358236/72197726-663c8080-345f-11ea-9de3-393272a7ea65.png)

### What is expected?
 normal style

### What is actually happening?
error style 

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment] 2020-01-11 15:17
Duplicate of #17811

**Closed** 2020-01-14 03:59 UTC
Labels: 4.x, 🐛 Bug, 👷🏻‍♂️ Someone working on it
