### ISSUE TITLE
4.18.x的Form组件触发校验后删除Input内容输入框会抖动

### ISSUE THREAD

**Issue by furan495** [ant-design/ant-design#33481] opened 2021-12-30 02:48 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
input输入内容后删除在输入，反复尝试都会抖动

### What is expected?
不抖动

### What is actually happening?
抖动

| Environment | Info |
|---|---|
| antd | 4.18.0 |
| React | 17.x |
| System | mac |
| Browser | 谷歌最新版 |

**Comment by afc163** [comment] 2021-12-30 02:54
Duplicate of #27746

**Closed by afc163** 2021-12-30 02:54 UTC
