### ISSUE TITLE
Table表头带有filter时，filter位置在最后，容易让人误以为是filter后面一列

### ISSUE THREAD

**Issue by WeiCongcong** [ant-design/ant-design#26447] opened 2020-08-28 03:36 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
查看上面链接中带有筛选功能的示例

### What is expected?
筛选图标与筛选列名相近

### What is actually happening?
筛选图标与表头下一列的列名相近

| Environment | Info |
|---|---|
| antd | undefined |
| React | - |
| System | - |
| Browser | - |

**Comment by afc163** [comment] 2020-08-28 14:24
Duplicate of #15403

**Closed by afc163** 2020-08-28 14:24 UTC
