### ISSUE TITLE
select下拉选项超过1000，会很卡顿

### ISSUE THREAD

**Issue by ffalconjs** [ant-design/ant-design#19614] opened 2019-11-07 10:05 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://暂无](http://暂无)

### Steps to reproduce
select下拉选项超过1000项，然后进行选择操作

### What is expected?
不会严重卡顿，性能是否可以优化

### What is actually happening?
必现

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.8.6 |
| System | macOS 10.14.6 |
| Browser | 78.0.3904.87 |

**Comment by afc163** [comment] 2019-11-07 10:12
Duplicate of #3789

**Closed by afc163** 2019-11-07 10:12 UTC
