### ISSUE TITLE
鼠标移出modal外关闭modal

### ISSUE THREAD

**Issue by zengwei2** [ant-design/ant-design#27706] opened 2020-11-12 02:03 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce
1. 打开modal
2. 鼠标从modal里滑出modal外后松手
3. modal关闭

### What is expected?
modal不关闭

### What is actually happening?
modal关闭

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 16 |
| System | windows10 |
| Browser | chrome |

**Comment by afc163** [comment] 2020-11-12 02:59
Duplicate of #27391

**Comment by afc163** [comment] 2020-12-03 04:08
Fixed in https://github.com/react-component/dialog/pull/210

**Closed by afc163** 2020-12-03 04:08 UTC
