### ISSUE TITLE
Use const [form] = Form.useForm (); warning appears

### ISSUE THREAD

**Issue by 279zlj** [ant-design/ant-design#22012] opened 2020-03-09 06:35 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
```
const BatchForm = (props) =>{
    const [form] = Form.useForm();
    useEffect(()=>{
        if(!props.visible){
            form.resetFields()
        }
    },[props.visible])
    function onsub (val){
        console.log(val,props.parmas)
        props.onCancel()
        form.resetFields()
    }
    function addCancel (){
        form.resetFields()
        props.onCancel()
    }
    return(
        <Modal title='输入批次' visible={props.visible} onCancel={addCancel} footer={false} okText='确定' cancelText='取消' >
            <Form {...formItemLayout} name='configform' form={form}  onFinish={onsub}>
                <Form.Item label='已选数量'>
                    {props.parmas.length}台
                </Form.Item>
                <Form.Item label='批次' name='batch' rules={[{required:true,message:'请输入批次'}]}>
                    <Input />
                </Form.Item>
                <Form.Item {...tailFormItemLayout}>
                    <Button type='primary' htmlType='submit' style={{float:'right'}}>确定</Button>
                </Form.Item>
            </Form>
        </Modal>
    )
}
```

### What is expected?
No warning

### What is actually happening?
Warning: Instance created by useForm is not connect to any Form element. Forget to pass form prop? 

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | react |
| System | win10 |
| Browser | chrome 80.0.3987.132 |

**Comment by afc163** [comment] 2020-03-09 07:06
Duplicate of #21543

**Closed by afc163** 2020-03-09 07:06 UTC
