### ISSUE TITLE
Add support for custom Upload List Item Components

### ISSUE THREAD

**Issue by StarryFire** [ant-design/ant-design#16505] opened 2019-05-09 11:46 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This will help developers who want to customize how to display previews of uploaded files.

### What does the proposed API look like?
Make a new component called Upload.Item which accepts props like 'thumbnail', 'text', 'description', etc.

**Comment by afc163** [comment] 2019-05-09 13:24
Duplicate of #16047

**Closed by afc163** 2019-05-09 13:24 UTC

**Comment by hiteshlimbani45** [comment] 2020-06-17 11:17
I have to customize my dragger component and add option of retry if file fail to uplode pls.. help me
