### ISSUE TITLE
Multi Select Responsive maxTagCount doesn't trigger the onBlur event when one option is selected

### ISSUE THREAD

**Issue by danielbellmas** [ant-design/ant-design#31839] opened 2021-08-18 11:50 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-lvrlw)

### Steps to reproduce
-

### What is expected?
Trigger the onBlur event 

### What is actually happening?
Pressing outside of the select closes the dropdown but doesn't trigger the onBlur event when only one option is selected after the select is empty. 

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0.0 |
| System | 10.11 |
| Browser | 92.0.4515.159 |

**Comment by afc163** [comment] 2021-08-19 01:21
Duplicate of #30325

**Closed by afc163** 2021-08-19 01:21 UTC
