### ISSUE TITLE
Select 组件同时设置 mode 为 multiple 和 open 为 false 是，输入框内容不显示

### ISSUE THREAD

**Issue by Arco1ris** [ant-design/ant-design#47714] opened 2024-03-05 07:46 UTC
### Reproduction link

[栗子](https://codesandbox.io/p/sandbox/antd-select-bug-45lnty?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clte2bfrg00063b6lzfcq7jpb%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clte2bfrg00023b6luqg5wtkp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clte2bfrg00033b6loqu4kvb8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clte2bfrg00053b6l5wzjhx0x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clte2bfrg00023b6luqg5wtkp%2522%253A%257B%2522id%2522%253A%2522clte2bfrg00023b6luqg5wtkp%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clte2bfrg00053b6l5wzjhx0x%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clte2bfrg00043b6lzrp3kme5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clte2bfrg00053b6l5wzjhx0x%2522%252C%2522activeTabId%2522%253A%2522clte2bfrg00043b6lzrp3kme5%2522%257D%252C%2522clte2bfrg00033b6loqu4kvb8%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clte2bfrg00033b6loqu4kvb8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

antd 的 select 组件，设置 mode="multiple" 和 open={false}
然后在输入框里输入内容“test”，注意光标不离开输入框

### What is expected?

输入框里出现输入的”test“

### What is actually happening?

输入框里什么都没有

| Environment | Info |
| --- | --- |
| antd | 5.15.0 |
| React | ^18.2.0 |
| System | macOS |
| Browser | chrome |

**Comment by afc163** [comment] 2024-03-05 08:08
<img width="651" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/daeb2c1c-3eea-4011-b4c5-92a4f9893727">

**Comment by Arco1ris** [comment] 2024-03-05 09:03
https://codesandbox.io/p/sandbox/antd-select-bug-45lnty?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clte2bfrg00063b6lzfcq7jpb%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clte2bfrg00023b6luqg5wtkp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clte2bfrg00033b6loqu4kvb8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clte2bfrg00053b6l5wzjhx0x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clte2bfrg00023b6luqg5wtkp%2522%253A%257B%2522id%2522%253A%2522clte2bfrg00023b6luqg5wtkp%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clte2bfrg00053b6l5wzjhx0x%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clte2bfrg00043b6lzrp3kme5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clte2bfrg00053b6l5wzjhx0x%2522%252C%2522activeTabId%2522%253A%2522clte2bfrg00043b6lzrp3kme5%2522%257D%252C%2522clte2bfrg00033b6loqu4kvb8%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clte2bfrg00033b6loqu4kvb8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by Arco1ris** [comment] 2024-03-05 09:08
> <img alt="图片" width="651" src="https://private-user-images.githubusercontent.com/507615/310032772-daeb2c1c-3eea-4011-b4c5-92a4f9893727.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mjk5NjcsIm5iZiI6MTcwOTYyOTY2NywicGF0aCI6Ii81MDc2MTUvMzEwMDMyNzcyLWRhZWIyYzFjLTNlZWEtNDAxMS1iNGM1LTkyYTRmOTg5MzcyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwOTA3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWU3MzJkNGY2ZjU5NmQwZjNmYzhmMGZhMTYwM2Y4MzRmMGEyYmVmZWFjZTNkYzczYzUxYzI5NDRkNWViMTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GYh1c49jb1twVIg09TTBlnv12EdmyBb1JkvdxngnJVs">

不好意思，我更新了一下，麻烦再看一下

**Comment by Arco1ris** [comment] 2024-03-05 09:09
我又更新了一下链接，麻烦再看下 [栗子](https://codesandbox.io/p/sandbox/antd-select-bug-45lnty?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clte2bfrg00063b6lzfcq7jpb%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clte2bfrg00023b6luqg5wtkp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clte2bfrg00033b6loqu4kvb8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clte2bfrg00053b6l5wzjhx0x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clte2bfrg00023b6luqg5wtkp%2522%253A%257B%2522id%2522%253A%2522clte2bfrg00023b6luqg5wtkp%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clte2bfrg00053b6l5wzjhx0x%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clte2bfrg00043b6lzrp3kme5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clte2bfrg00053b6l5wzjhx0x%2522%252C%2522activeTabId%2522%253A%2522clte2bfrg00043b6lzrp3kme5%2522%257D%252C%2522clte2bfrg00033b6loqu4kvb8%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clte2bfrg00033b6loqu4kvb8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by afc163** [comment] 2024-03-05 10:43
什么需求需要同时用到 `mode="multiple"` + `open={false}`？

**Comment by afc163** [comment] 2024-03-05 12:10
Duplicate of https://github.com/ant-design/ant-design/issues/27255

**Comment by zombieJ** [comment] 2024-03-06 08:28
你这个场景应该使用 `tags`，其他类型下 `open=false` 时输入框内容是不会展示的。

**Closed** 2024-03-10 00:04 UTC
Labels: needs-more-info
