### ISSUE TITLE
Required Footer for each coloumn OR a fixed last row

### ISSUE THREAD

**Issue by jagratiTomar** [ant-design/ant-design#10455] opened 2018-05-10 06:12 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
To display aggrigation in a table of all the rows in the bottom footer. Currently the footer that is provided is for the table not the column, due to which the footer is not really a part of the table and causes scroll-x issues. This should work with table having scroll-x and scroll-y. This feature would allow the user to see the last row always and scroll only on the other table rows.

### What does the proposed API look like?
Either row should have a prop : `fixed:bottom`. Or each coloum sould have a prop columnFooter = function(columnData)

I had found this https://codesandbox.io/s/m45r6o4nj8 code but it is not a good user experience.

**Comment by afc163** [comment] 2018-05-10 06:48
Duplicate of #5710

**Closed by afc163** 2018-05-10 06:48 UTC
