### ISSUE TITLE
Selecting multiple dates with Calendar and/or DatePicker. 

### ISSUE THREAD

**Issue by iamricky** [ant-design/ant-design#29635] opened 2021-03-05 18:04 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The ability pick pick multiple times/dates.

### What does the proposed API look like?
Extend DatePicker to include MultiplePicker; The Calendar component would just have a `multiple` boolean attribute

**Comment by afc163** [comment] 2021-03-06 05:02
Duplicate of #4447

**Closed by afc163** 2021-03-06 05:02 UTC
