### ISSUE TITLE
version >=3.9.0 extremely large bundle size

### ISSUE THREAD

**Issue by riwu** [ant-design/ant-design#13107] opened 2018-11-13 03:43 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.7

### Environment
macOS High Sierra 10.13.5, Chrome Version 70.0.3538.77, yarn v1.12.3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/20xvj96plj)

### Steps to reproduce
1. `yarn upgrade antd@3.8.4; yarn build`
2. `yarn upgrade antd@3.9.0; yarn build`

### What is expected?
Both commands should create bundle size of about 43KB gzipped.

### What is actually happening?
First command creates bundle size of about 43KB gzipped,
second command creates bundle size of about 214KB gzipped.

---
This issue is still present in the current version 3.10.7.

**Comment by zombieJ** [comment] 2018-11-13 13:00
duplicate of #12011

**Closed by zombieJ** 2018-11-13 13:00 UTC
