### ISSUE TITLE
Carousel组件轮播三四个小时后，出现内存泄露，直到崩溃页面

### ISSUE THREAD

**Issue by poetries** [ant-design/ant-design#20806] opened 2020-01-09 14:02 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/15062](https://github.com/ant-design/ant-design/issues/15062)

### Steps to reproduce
轮播三四个小时，发现浏览器内存一直增长，然后出现崩溃现象。

### What is expected?
能正常使用。哪个版本是正常的，有人遇到过吗

### What is actually happening?
浏览器内存一直增长，直到内存泄露崩溃页面

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16.7.0 |
| System | mac os |
| Browser | chrome |

---
更多类似问题 https://github.com/akiran/react-slick/issues/1257

**Comment by afc163** [comment] 2020-01-09 14:13
Duplicate of #15062

**Closed by afc163** 2020-01-09 14:13 UTC
Labels: help wanted
