### ISSUE TITLE
How to control AutoComplete popup direction?

### ISSUE THREAD

**Issue by JesperWe** [ant-design/ant-design#5130] opened 2017-03-01 15:40 UTC
I want to avoid this effect:

![antd-autocomplete-jumping](https://cloud.githubusercontent.com/assets/1643015/23467198/b1108a3e-fe9d-11e6-8661-3645262a91e5.gif)

(The menu appears above the input, then flips below when the search is narrowed).

**Comment by RaoHai** [comment] 2017-03-02 09:28
Flipping procedure is in [dom-align](https://github.com/yiminghe/dom-align).

May dom-align can adjust the flip rule to: When dropdown area broadened, try to flip, otherwise keep previous flipping status.

@afc163

**Comment by afc163** [comment] 2017-03-02 10:00
Just turn off auto adjust behavious when inputing search text.

**Comment by RaoHai** [comment] 2017-03-02 10:51
it's also necessary to flip when got more suggestions after search, because that may make a larger dropdown which can not fit in bottom area..

**Comment by JesperWe** [comment] 2017-03-02 11:03
If I can offer my opinion: Flipping the sides after the menu has been initially opened, and thus making the user "chase" the menu with the eyes depending on what is typed is not good UX.

I would personally prefer if there was a way for the designer to have control over the opening direction.

(Not within the scope of this issue, but in my particular use case, I have several components in the form, and they are popping up in different directions depending on the size of the widget, which is quit ugly...)

**Comment by RaoHai** [comment] 2017-03-02 11:29
Return to this issue, u can use `dropdownAlign` props to control it.

```jsx
dropdownAlign={{
   points: ['bl', 'tl'], // align dropdown bottom-left to top-left of input element
   offset: [0, -4], // align offset
    overflow: {
      adjustX: 0, 
      adjustY: 0, // do not auto flip in y-axis
  },
}}
```

doc of `dropdownAlign` can found in https://github.com/yiminghe/dom-align.

**Comment by JesperWe** [comment] 2017-03-02 11:55
@RaoHai that was exactly what I was looking for! Works perfectly. It is not mentioned anywhere at all as far as I (or Google...) can see in the https://ant.design documentation. I thought about creating a PR with docs, but it strikes me that these controls work for many components, not only AutoComplete, so maybe there should be a central page describing options common to all of them? 

(I leave this Issue open for now, since you guys started the discussion what should happen when NOT using the manual `dropdownAlign` controls)

**Comment by benjycui** [comment] 2017-03-03 02:09
The better solution may be: just align once when open, and should not re-align while updating.

Actually, [rc-align](https://github.com/react-component/align/blob/fd6aff71503d38f4315ca87f4de66c1b702abb21/src/Align.jsx#L61-L88) had tried to do so. But most of our users just pass object literal to `align` property, so it will [always re-align](https://github.com/react-component/align/blob/fd6aff71503d38f4315ca87f4de66c1b702abb21/src/Align.jsx#L66).

So, just update:

```diff
- if (prevProps.disabled || prevProps.align !== props.align) {
+ if (prevProps.disabled || !deepEqual(prevProps.align, props.align)) {
    reAlign = true;
  }
```

`deepEqual` is OK, for `algin` is just a simple object.

**Comment by benjycui** [comment] 2017-03-03 02:09
And I think this is a bug.

**Comment by RaoHai** [comment] 2017-03-03 02:36
My question is, if dropdown broadened (get bigger), if do not re-align, dropdown may out of viewport.

**Comment by RaoHai** [comment] 2017-03-03 02:43
算了用中文。

 update 的时候内容可能变少，也可能变多。更少的情况下不重新对齐是 OK 的，更多的话，很可能原先能摆下，现在摆不下了。不重新对齐，就可能导致 dropdown 的内容超出窗口，这个比一直重新对齐恐怕更不能接受。

**Comment by afc163** [comment] 2017-03-03 03:13
> My question is, if dropdown broadened (get bigger), if do not re-align, dropdown may out of viewport.

People can scroll down. I think it is unacceptable to see a visible ropdown jump between up and down.

**Comment by RaoHai** [comment] 2017-03-03 06:08
> People can scroll down for extra part. 

so we must set `resizeHeight` to allow dom-align to adjust height of dropdown.

**Comment by benjycui** [comment] 2017-03-21 01:28
ping @RaoHai 

It's this issue done? You PR had been merged.

**Comment by benjycui** [comment] 2017-04-26 07:07
> ping @RaoHai
> 
> It's this issue done? You PR had been merged.

**Comment by JesperWe** [comment] 2017-04-27 16:01
@benjycui as I said in an earlier comment, *my issue* is solved, but you (antd developers) started a bigger discussion in the issue so I left it open for you to close when done or moved to another issue.

**Closed** 2017-08-04 09:50 UTC
Labels: Discussion

**Comment by monolithed** [comment] 2023-07-15 13:11
I have the same issue when there's an indentation before AutoComplete. I tried to reproduce it on codesandbox, but it only affects my project. I don't even know what to do with it.
