### ISSUE TITLE
Form的scrollToFirstError 对于antd的Upload 组件无法生效

### ISSUE THREAD

**Issue by zht55555** [ant-design/ant-design#44968] opened 2023-09-20 07:17 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xiao-yan-qi-ta-zu-jian-antd-4-24-12-forked-gpn7m6?file=/demo.tsx)

### Steps to reproduce

当出现滚动条时 直接点击提交

### What is expected?

点击提交滚动到Upload组件位置

### What is actually happening?

无法滚动

| Environment | Info |
| --- | --- |
| antd | 4.24.14 |
| React | 18.0.0 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment] 2023-09-20 08:55
Duplicate of https://github.com/ant-design/ant-design/issues/28869

**Closed by afc163** 2023-09-20 08:55 UTC
Labels: unconfirmed
