### ISSUE TITLE
Suggesting use SCSS instead of LESS

### ISSUE THREAD

**Issue by KyleBing** [ant-design/ant-design#31409] opened 2021-07-15 04:01 UTC
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Serve larger project scale

### What does the proposed API look like?
Less is very similar to SCSS, so it is doable.

**Comment by PeachScript** [comment] 2021-07-15 04:13
Duplicate of #18611

**Closed by PeachScript** 2021-07-15 04:13 UTC

**Comment by LinboLen** [comment] 2022-11-06 07:23
related #38406
