### ISSUE TITLE
Table Selection is very slow if data source is too large

### ISSUE THREAD

**Issue by lttien1** [ant-design/ant-design#15635] opened 2019-03-25 11:00 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/p4045voj7)

### Steps to reproduce
Select page size > 100 rows

### What is expected?
When i click on checkbox, the table should not re-render all cell of table.

### What is actually happening?
When i checked a checkbox, the table delay about 2 seconds to checked this row.

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | React 16.2.0 |
| System | Window 7, Ram 8BG and SSD 120GB |
| Browser | Chrome 73 |

---
- You can use PC that have lower configuration computer to see this issue clearly

**Comment by afc163** [comment] 2019-03-25 11:02
Duplicate of #10431

**Closed by afc163** 2019-03-25 11:02 UTC
