### ISSUE TITLE
Tree组件 filterTreeNode回调函数中返回ture仍然不能使对应节点高亮

### ISSUE THREAD

**Issue by 123456wjw** [ant-design/ant-design#28875] opened 2021-01-15 02:47 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-antd4102-forked-fi3vv?file=/index.js)

### Steps to reproduce
在tree组件上加上filterTreeNode属性，然后在回调中返回true

### What is expected?
tree组件 filterTreeNode回调函数中返回ture使对应节点高亮

### What is actually happening?
Tree组件 filterTreeNode回调函数中返回ture不能使对应节点高亮

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | react 16.8.6 |
| System | windows 64 |
| Browser | 谷歌 87.0.4280.88 |

---
业务需要一颗不能节点不能选中的树，要求特定的节点高亮显示

**Comment by yoyo837** [comment] 2021-01-15 02:49
Duplicate of #28864

**Closed by yoyo837** 2021-01-15 02:49 UTC

**Comment by 123456wjw** [comment] 2021-01-15 02:51
> Duplicate of #28864

it dosn’t work

**Comment by yoyo837** [comment] 2021-01-15 02:52
Please wait release in this weekend.

**Comment by 123456wjw** [comment] 2021-01-15 02:53
> Please wait release in this weekend.

ok

**Comment by 123456wjw** [comment] 2021-01-15 02:53
> Please wait release in this weekend.

thanks
