### ISSUE TITLE
日期选择组件（DatePicker）设置了value属性之后无法使用上个月，上一年，下个月下一年等功能

### ISSUE THREAD

**Issue by 12522611705** [ant-design/ant-design#12120] opened 2018-09-07 01:39 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
系统环境windows,mac；浏览器：chrome67.0.3396.62，antd：3.9.1，react：16.4.0

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
官方DatePicker日期选择框组件的第二个例子选择月的可以重现

### What is expected?
1

### What is actually happening?
1

**Comment by hengkx** [comment] 2018-09-07 01:58
![image](https://user-images.githubusercontent.com/8358236/45194136-4fdb4f00-b284-11e8-9f59-7fd001cbf1d1.png)
![image](https://user-images.githubusercontent.com/8358236/45194149-5e296b00-b284-11e8-9c18-bd9ebf7c77dc.png)
`MonthPicker ` don't use prev yaer and next year

**Comment by 12522611705** [comment] 2018-09-07 02:06
Here is an example of choosing a month, and if you find an example where the date is selected and the value property is set, the next month will be as unusable as the previous month.

**Comment by afc163** [comment] 2018-09-07 03:13
Duplicate of #12082

**Closed by afc163** 2018-09-07 03:13 UTC
