### ISSUE TITLE
Button makes link broken in Firefox

### ISSUE THREAD

**Issue by tylerlong** [ant-design/ant-design#8686] opened 2017-12-20 15:56 UTC
### Version
3.0.2

### Environment
macOS 10.12.6, **Firefox** 57.0.2 (64-bit)

### Reproduction link
[https://codesandbox.io/s/z3w7lmw8j3](https://codesandbox.io/s/z3w7lmw8j3)

### Steps to reproduce
1. Open https://codesandbox.io/s/z3w7lmw8j3
1. Click link1
1. Click link2

### What is expected?
The url's fragment should change to #link1 when click link1

The url's fragment should change to #link2 when click link2

### What is actually happening?
The url's fragment doesn't change when click link1

---

**Comment by afc163** [comment] 2017-12-21 01:36
Duplicate of #7911

**Closed by afc163** 2017-12-21 01:36 UTC
