### ISSUE TITLE
List组件栅格布局 换行

### ISSUE THREAD

**Issue by xiaoblack163** [ant-design/ant-design#29213] opened 2021-02-03 10:34 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/y8p2h](https://codesandbox.io/s/y8p2h)

### Steps to reproduce
官网List组件 栅格布局

### What is expected?
正确的显示

### What is actually happening?
官网List组件 栅格布局，最后一个换行了

| Environment | Info |
|---|---|
| antd | 4.12.1 |
| React | 17.0.1 |
| System | mac |
| Browser | chrome 88 |

**Comment by afc163** [comment] 2021-02-03 11:13
Duplicate of #29208

**Closed by afc163** 2021-02-03 11:13 UTC

**Comment by chuifengji** [comment] 2021-02-03 12:02
I think I have solved this bug. I will push a PR later
