### ISSUE TITLE
全局样式针对 Modal.confirm 不生效

### ISSUE THREAD

**Issue by powerdong** [ant-design/ant-design#39239] opened 2022-12-04 08:15 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/gu-ding-tou-he-lie-antd-5-0-3-forked-4zdb9m?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

全局设置的border-radius 是4，modal里边的是2

### What is expected?

期望全局生效

### What is actually happening?

实际是antd默认的6

| Environment | Info |
| --- | --- |
| antd | 5.0.3 |
| React | 17 |
| System | Mac |
| Browser | edge |

**Comment by zombieJ** [comment] 2022-12-04 08:50
Duplicate of #39023

**Closed by zombieJ** 2022-12-04 08:50 UTC
