### ISSUE TITLE
when Select set value empty str , the placeholder not show

### ISSUE THREAD

**Issue by zhonggithub** [ant-design/ant-design#20324] opened 2019-12-18 07:01 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/white-fast-u7plm)

### Steps to reproduce
1, open https://ant.design/components/select-cn/
2, set value=""

### What is expected?
I think if value or defaultValue is empty str , show placeholder  is  a better choice。
I don't know if it's a bug. maby the design is so.

### What is actually happening?
when Select set value empty str , the placeholder not show

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | 16.12 |
| System | mac os |
| Browser | chrome 最新版本 |

**Comment by afc163** [comment] 2019-12-18 07:01
Duplicate of #2367

**Closed by afc163** 2019-12-18 07:02 UTC
