### ISSUE TITLE
表单必填无法提示到具体字段

### ISSUE THREAD

**Issue by ZYC1217** [ant-design/ant-design#41401] opened 2023-03-22 12:17 UTC
### Reproduction link

[https://4x.ant.design/components/form/#validateMessages](https://4x.ant.design/components/form/#validateMessages)

### Steps to reproduce

表单提交进行必填校验

### What is expected?

控制台打印具体某个字段未填写

### What is actually happening?

['请输入${label}']

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | react16 |
| System | window11 |
| Browser | 谷歌 |

**Comment by Wxh16144** [comment] 2023-03-22 13:04
Duplicate of #40497 ?

**Comment by MadCcc** [comment] 2023-03-22 13:06
> Duplicate of #40497 ?

Yes, trace in https://github.com/ant-design/ant-design/issues/40497

**Closed by MadCcc** 2023-03-22 13:06 UTC
Labels: unconfirmed
