### ISSUE TITLE
Split=false doesn't work on nested list

### ISSUE THREAD

**Issue by irvanherz** [ant-design/ant-design#36798] opened 2022-07-30 06:35 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-nested-list-bug-ipmm2o?file=/index.js)

### Steps to reproduce

Create a nested List with split=false on the child List.

### What is expected?

The split line separator should not show on the nested list.

### What is actually happening?

Split line separator show if I don't specify split=false on the parent List respectively.

| Environment | Info |
| --- | --- |
| antd | 4.22.2 |
| React | 18.2.0 |
| System | Arch Linux (64-bit) |
| Browser | Chromium 103.0.5060.53 (Official Build) Arch Linux (64-bit) |

**Comment by afc163** [comment] 2022-07-30 09:14
Duplicate of #31571

**Closed by afc163** 2022-07-30 09:14 UTC
