### ISSUE TITLE
部分语言未提供Form相关locale，导致使用@umijs/plugin-locale，切换到该语言时，Provider层级减少，引起子组件全部重新mount

### ISSUE THREAD

**Issue by Leemin0311** [ant-design/ant-design#27602] opened 2020-11-06 06:39 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/Leemin0311/config-privider-bug](https://github.com/Leemin0311/config-privider-bug)

### Steps to reproduce
yarn start

点击change to id_ID 或者 change to en_US

### What is expected?
组件树层级不变

### What is actually happening?
组件树层级改变导致DvaContainer unmount

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 16.12.0 |
| System | Mac OS X 10.15.7 |
| Browser | Chrome 86.0.4240.111 |

**Comment by afc163** [comment] 2020-11-06 06:54
Duplicate of #27418

**Comment by afc163** [comment] 2020-11-06 08:51
You could report it to umi issues.

**Closed by afc163** 2020-11-06 08:51 UTC

**Comment by afc163** [comment] 2020-11-06 09:08
Trace #27418
