### ISSUE TITLE
Mentions上下按键不联动滚动条

### ISSUE THREAD

**Issue by ywc644653066** [ant-design/ant-design#33310] opened 2021-12-15 09:34 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/s/ji-ben-shi-yong-antd-4-17-3-forked-xqx96?file=/package.json
[https://github.com/ywc644653066/Antd-Mentions-Project.git](https://github.com/ywc644653066/Antd-Mentions-Project.git)

### Steps to reproduce
Mentions提及组件，存在多个options时，输入@之后弹出提及框，键盘"下"键选到框外的option，滚动条并没有跟着滚动

### What is expected?
希望Mentions组件滚动条跟键盘上下键联动

### What is actually happening?
滚动条没有跟键盘上下键联动

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 16.14.0 |
| System | macOS10.15.4  |
| Browser | chrome96.0.4664.93 |

**Comment by afc163** [comment] 2021-12-15 09:52
Duplicate of #31756

**Closed by afc163** 2021-12-15 09:52 UTC
