### ISSUE TITLE
bug(ts): OptionProps in Select component is missing a prop in ts

### ISSUE THREAD

**Issue by dabuside** [ant-design/ant-design#18409] opened 2019-08-22 07:27 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/focused-driscoll-l7gxt)

### Steps to reproduce
```
    <Option value="china" label="China">
      <span role="img" aria-label="China">
        🇨🇳{' '}
      </span>
      China (中国)
    </Option>
```
Option accepts the label prop which is not in ts file. It would raise a ts type error
```
export interface OptionProps {
  disabled?: boolean;
  value?: string | number;
  title?: string;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
}
```

### What is expected?
add types to it

### What is actually happening?
Type '{ children: (string | Element)[]; value: string; label: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<OptionProps, any, any>> & Readonly<OptionProps> & Readonly<{ children?: ReactNode; }>'.
  Property 'label' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<OptionProps, any, any>> & Readonly<OptionProps> & Readonly<{ children?: ReactNode; }>'.ts(2322)

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.8.4 |
| System | mac os |
| Browser | chrome 76 |

---
https://github.com/ant-design/ant-design/blob/109bd4ecde8879b9a4cd4a3048041d350f265dcd/components/select/index.tsx#L83-L90

**Comment by afc163** [comment] 2019-08-22 07:29
Duplicate of #17493

**Closed by afc163** 2019-08-22 07:29 UTC

**Comment by GoJam11** [comment] 2020-11-23 10:09
you didn't resolve the problem
