### ISSUE TITLE
点击 stackblitz 无法正常预览demo

### ISSUE THREAD

**Issue by DaiWang-Lei** [ant-design/ant-design#37193] opened 2022-08-23 06:29 UTC
### Reproduction link

[https://stackblitz.com/run?file=index.js](https://stackblitz.com/run?file=index.js)

### Steps to reproduce

随便挑个demo，选择用stackblitz打开，都会报错，我主要用的是table表格。

### What is expected?

可以正常使用stackblitz，测试demo

### What is actually happening?

[每次点开stackblitz都会报错，](![1661236125096](https://user-images.githubusercontent.com/45023446/186086492-14b1497b-4256-4b8f-a317-dc16f22eca17.jpg))

| Environment | Info |
| --- | --- |
| antd | 4.22.7 |
| React | 17.0.2 |
| System | 1 |
| Browser | 104.0.5112.101 |

**Comment by DaiWang-Lei** [comment] 2022-08-23 06:30
![1661236125096](https://user-images.githubusercontent.com/45023446/186086558-757a319a-86bb-4e25-876a-d935ed02ef1c.jpg)

**Comment by zombieJ** [comment] 2022-08-23 06:31
清理一下游览器缓存哈~

Duplicate of #37113

**Closed by zombieJ** 2022-08-23 06:31 UTC
