### ISSUE TITLE
Fitler popover stuck in header part when using the fixed prop on <Table>

### ISSUE THREAD

**Issue by xPhentom** [ant-design/ant-design#39196] opened 2022-12-02 10:41 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/weathered-grass-hf8qbe?file=/src/App.js)

### Steps to reproduce

- Load the codesandbox reproduction
- Open the filter popover using the filter icon all the way to the right

### What is expected?

I expect the Popover to be above the Table element instead of being stuck in the table header.
Note: I had to use getPopupContainer={(e) => e.parentElement} or else the popover won't follow when scrolling. This can be replicated by getting an overflow: enlarge the console if needed.

### What is actually happening?

The popover seems to be stuck in the header

| Environment | Info |
| --- | --- |
| antd | 5.0.3 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Firefox |

**Comment by stijnvanhulle** [comment] 2022-12-02 10:53
I'm having the same issue on ant-design v4.24.4.

**Comment by afc163** [comment] 2022-12-02 11:04
Duplicate of #29366

**Closed by afc163** 2022-12-02 11:04 UTC

**Comment by xPhentom** [comment] 2022-12-02 11:48
Hi @afc163 
If I'm not mistaken, the ticket you've send needs to have the scroll={x: number,y: number} property.
My implementation doesn't have this which is why the issue is still there. Am I mistaken?

**Comment by xPhentom** [comment] 2022-12-02 11:53
I've implemented the proposed solution here: https://codesandbox.io/s/goofy-joji-twdoje?file=/src/App.js
It still doesn't follow the scroll.
