### ISSUE TITLE
change page rowSelection still exists when preserveSelectedRowKeys=false

### ISSUE THREAD

**Issue by 1247748612** [ant-design/ant-design#34442] opened 2022-03-11 08:48 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biao-ge-pi-liang-cao-zuo-forked-g6zxg6?file=/App.tsx)

### Steps to reproduce
https://codesandbox.io/s/biao-ge-pi-liang-cao-zuo-forked-g6zxg6?file=/App.tsx

### What is expected?
change page rowSelection still exists

### What is actually happening?
change page clear rowSelection

| Environment | Info |
|---|---|
| antd | 4.19.1 |
| React | 17 |
| System | Windows |
| Browser | Chrome |

---
related issue: https://github.com/ant-design/pro-components/issues/4805#issue-1163732754

related PR: https://github.com/ant-design/ant-design/pull/32877

**Comment by 1247748612** [comment] 2022-03-11 08:53
当preserveSelectedRowKeys为false时，切换页面应当清空rowSelection 并触发rowSelection.onChange事件传递空数组

**Comment by afc163** [comment] 2022-03-14 03:35
Duplicate of #32861

**Closed by afc163** 2022-03-14 03:35 UTC
