### ISSUE TITLE
Add extra prop to Collapse.Panel to render in the right of the panel header

### ISSUE THREAD

**Issue by skyskysky11** [ant-design/ant-design#14730] opened 2019-02-05 08:52 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This feature solve problem with adding actions to the panel header

### What does the proposed API look like?
Collapse.Panel prop "extra" (String | ReactNode) (Content to render in the right of the panel header)

**Comment by afc163** [comment] 2019-02-05 10:36
Duplicate of #11626

**Closed by afc163** 2019-02-05 10:36 UTC
