### ISSUE TITLE
DatePicker does not respect millisecond change in value

### ISSUE THREAD

**Issue by denisk20** [ant-design/ant-design#31048] opened 2021-06-18 11:05 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/interesting-dew-yt0yz?file=/index.js)

### Steps to reproduce
Open the sandbox, change the seconds and milliseconds inputs

### What is expected?
Both seconds and milliseconds of the To value of the DateRange are changed

### What is actually happening?
Only seconds change. Changing milliseconds does nothing

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | 16.14.0 |
| System | MacOS |
| Browser | Chrome |

---
This does not happen if I use `<DatePicker value={to}` rather than `<RangePicker value={[from, to]}`

**Comment by afc163** [comment] 2021-06-22 15:09
Duplicate of #28591

**Closed by afc163** 2021-06-22 15:09 UTC
