### ISSUE TITLE
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

### ISSUE THREAD

**Issue by front-end-developer-candy** [ant-design/ant-design#27047] opened 2020-10-09 03:43 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce

<Upload
            action="https://www.mocky.io/v2/5cc8019d300000980a055e76"
            listType="picture-card"
            fileList={fileList}
            onPreview={handlePreview}
            onChange={handleChange}
        >
            {child}
        </Upload>

### What is expected?
预期正常调用

### What is actually happening?
因为 rcAnimate 组件导致reactWarn,  Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | macOS |
| Browser | chrome |

**Comment by afc163** [comment] 2020-10-09 03:59
Duplicate of https://github.com/ant-design/ant-design/issues/22493#issuecomment-696259292

**Closed by afc163** 2020-10-09 03:59 UTC
