### ISSUE TITLE
Typing in dates while using date-fns for Datepicker gives undesired result

### ISSUE THREAD

**Issue by minhson3012** [ant-design/ant-design#36245] opened 2022-06-27 04:42 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/competent-water-u14mg3)

### Steps to reproduce

1. Replaced moment.js Datepicker with date-fns (https://ant.design/docs/react/replace-moment#DatePicker)
2. Set Datepicker format as "dd/MM/yyyy"
3. Typed in 23/06/2022 in the Datepicker

### What is expected?

I should be able to type 23/06/2022 normally

### What is actually happening?

Datepicker is displaying 23/06/0002, and if I continue typing it will show 23/06/000202. However the Datepicker modal will display 'June 0002'

![image](https://user-images.githubusercontent.com/22538900/175862439-41c53f98-87fd-4b70-bbd0-6463bef01d73.png)

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17.0.2 |
| System | Windows |
| Browser | all browsers |

**Comment by afc163** [comment] 2022-06-27 05:57
Duplicate of #30097

**Closed by afc163** 2022-06-27 05:57 UTC
