### ISSUE TITLE
When set  'mode' attributes of RangePicker to ['month', 'month'] or ['year', 'year'], and use it with getFieldDecorator , its value can't be changed

### ISSUE THREAD

**Issue by yisayu** [ant-design/ant-design#15732] opened 2019-03-29 03:24 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/k5q5xqvykr)

### Steps to reproduce
use the second RangePicker ,it's not work 

### What is expected?
 set  'mode' attributes of RangePicker to ['month', 'month'] or ['year', 'year'],  its value can be changed

### What is actually happening?
use the second RangePicker ,it's not work 

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.7.0 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment] 2019-03-30 05:07
Duplicate of #15659

**Closed by afc163** 2019-03-30 05:07 UTC
