### ISSUE TITLE
Tabs flicker if browser zoom level is set to 90%

### ISSUE THREAD

**Issue by wang-yikai** [ant-design/ant-design#49955] opened 2024-07-18 15:00 UTC
### Reproduction link

[https://codepen.io/NotYeetKai/pen/QWXyZRN?editors=001](https://codepen.io/NotYeetKai/pen/QWXyZRN?editors=001)

### Steps to reproduce

Set the "Tab position" to "left" and set the browser zoom to 90%.

### What is expected?

No flickering

### What is actually happening?

The tabs are flickering (the "..." is repeatedly showing and not showing).

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment] 2024-07-19 03:07
Duplicate of https://github.com/ant-design/ant-design/issues/46910

**Closed by afc163** 2024-07-19 03:07 UTC
Labels: unconfirmed
