### ISSUE TITLE
Cant set property "top" to dropdown menu using Autocomplete component via dropdownStyle prop of component

### ISSUE THREAD

**Issue by maksimhodasevich** [ant-design/ant-design#21578] opened 2020-02-25 08:06 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://pastebin.com/uP9CU1CH](https://pastebin.com/uP9CU1CH)

### Steps to reproduce
paste this code to working react component

(width added antd inside the component)

### What is expected?
you expect to see 100 px space between search bar and dropdown menu (i tried different combinations of dropdownStyle values like:

{top: 100}
{top: '100px'}
{top: '100px !important'}
etc

)

### What is actually happening?
you will see i little tiny empty space between search bar and dropdown results (top property of ant dropdown menu will be like 50-60px)

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | react 16.9.0 |
| System | ubuntu |
| Browser | last chrome |

---
no :D

**Comment by afc163** [comment] 2020-02-25 10:10
Duplicate of https://github.com/ant-design/ant-design/issues/11942#issuecomment-417195388

**Closed by afc163** 2020-02-25 10:10 UTC
