### ISSUE TITLE
Table有拖拽列和scroll横向滚动条属性时，表头与表体错位

### ISSUE THREAD

**Issue by QJerryxjh** [ant-design/ant-design#30824] opened 2021-06-02 06:07 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/keshensuolie-antd4161-forked-886qs?file=/index.js)

### Steps to reproduce
向左滑动表头，表头与表体错位，竖向边框线不再对齐

### What is expected?
表头表体对齐不会错位

### What is actually happening?
表头表体不对齐错位

| Environment | Info |
|---|---|
| antd | 4.16.1 |
| React | 17.0.2 |
| System | macos big sur 11.3 |
| Browser | chrome 90.0.4430.93 |

**Comment by afc163** [comment] 2021-06-02 10:21
https://github.com/ant-design/ant-design/issues/26413#issuecomment-802563939

**Comment by afc163** [comment] 2021-06-02 10:21
Duplicate of #30740

**Closed by afc163** 2021-06-02 10:21 UTC

**Comment by hemengke1997** [comment] 2021-07-08 07:41
https://github.com/hemengke1997/useATRH
表头拖拽hook
