### ISSUE TITLE
文件上传的组件，支持一下上传列表自定义渲染吧

### ISSUE THREAD

**Issue by 4-1-1** [ant-design/ant-design#25976] opened 2020-08-03 07:03 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我想在在文件上传后修改上传到后端和显示的文件名

### What does the proposed API look like?
支持自定义渲染列表就好， icon什么的我也能换了

**Comment by afc163** [comment] 2020-08-03 07:19
Duplicate of #16047

**Closed by afc163** 2020-08-03 07:19 UTC
