### ISSUE TITLE
Table with fixed column will not working along with react-window

### ISSUE THREAD

**Issue by shuozhang2016** [ant-design/ant-design#24530] opened 2020-05-28 04:14 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
add fixed props to any columns for Table with react-window

### What is expected?
scroll and works well

### What is actually happening?
not working at all

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.8 |
| System | macOS |
| Browser | any borwser |

![image](https://user-images.githubusercontent.com/17228552/83098405-1f34ec00-a0dd-11ea-8c7a-0d78dbde13ff.png)

**Comment by afc163** [comment] 2020-05-28 04:31
Duplicate of https://github.com/ant-design/ant-design/issues/20339

**Closed by afc163** 2020-05-28 04:31 UTC
