### ISSUE TITLE
Radio组件中包裹了Select组件后，Select选择后，再次选择点开下拉选择就会立马关闭

### ISSUE THREAD

**Issue by xiaofuliang** [ant-design/ant-design#49798] opened 2024-07-10 02:28 UTC
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-cn9xtu-ihpaqp?file=demo.tsx)

### Steps to reproduce

```
   <Radio.Group onChange={onChange} value={value}>
      <Space direction="vertical">
        <Radio value={2}>
          自发证日起
          <Select
            style={{ width: 100 }}
            options={[
              {
                label: '一年',
                value: 1,
              },
              {
                label: '两年',
                value: 2,
              },
            ]}
          ></Select>
          内有效
        </Radio>
        <Radio value={3}>Option C</Radio>
        <Radio value={4}>
          More...
          {value === 4 ? (
            <Input style={{ width: 100, marginLeft: 10 }} />
          ) : null}
        </Radio>
      </Space>
    </Radio.Group>
```
Select第一次点选值时正常，第二次点选会立马关闭选择

### What is expected?

选择正常

### What is actually happening?

选择立马关闭

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | 18.3.1 |
| System | windows 10 |
| Browser | chrome 124.0.6367.202 |

**Comment by afc163** [comment] 2024-07-10 02:31
Duplicate of https://github.com/ant-design/ant-design/issues/25959

**Closed by afc163** 2024-07-10 02:31 UTC
Labels: unconfirmed
