### ISSUE TITLE
Image组件PreviewGroup多张图预览，动态切换多张图后，预览会包含上一次图片的内容

### ISSUE THREAD

**Issue by artlxl** [ant-design/ant-design#28513] opened 2020-12-23 13:09 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duozhangtupianyulan-antd494-forked-fkxid)

### Steps to reproduce
点击更换按钮，更换新的图片，点击图片查看预览，左右切换图片，发现更换图片前的图片内容仍然还在。

### What is expected?
更换图片后，预览只保留当前更换后的内容

### What is actually happening?
更换的图片list与更换前的图片list发生了合并

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17.0.1 |
| System | windows |
| Browser | chrom87 |

**Comment by shaodahong** [comment] 2020-12-23 14:31
Duplicate of https://github.com/ant-design/ant-design/issues/28429

**Closed by shaodahong** 2020-12-23 14:31 UTC
