### ISSUE TITLE
FormItem inside Form Component will always show the message after "backspace" once

### ISSUE THREAD

**Issue by XuejiSun** [ant-design/ant-design#9470] opened 2018-03-01 09:51 UTC
### Version
3.2.2

### Environment
win OS, Chrome Version 64.0.3282.167, React 16.3.0-alpha.0

### Reproduction link
[https://codesandbox.io/s/32824r1jpp](https://codesandbox.io/s/32824r1jpp)

### Steps to reproduce
1.From UI, tap"App Name" menu and then tap "CREAT NEW" to bring out one Modal
2. Add some content to the input of app name, then delete the content by backspace
3. Start to add some content again

### What is expected?
After delete the content the first time, the message show out, but after edit the content again, the message should not show again.

### What is actually happening?
Start to add some content again, the message will always show out

**Comment by yesmeck** [comment] 2018-03-01 09:59
It's expected behavior.

**Comment by yesmeck** [comment] 2018-03-01 10:02
![kapture 2018-03-01 at 18 01 27](https://user-images.githubusercontent.com/465125/36838636-ad202130-1d7a-11e8-8d23-aab007b579e7.gif)

**Comment by XuejiSun** [comment] 2018-03-01 10:19
How about your chrome version? My workmates all can repro this issue.

**Comment by yesmeck** [comment] 2018-03-01 10:50
> Version 64.0.3282.186 (Official Build) (64-bit)


Could you record a screenshot?

**Comment by XuejiSun** [comment] 2018-03-02 15:40
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19721328/36907231-1406a6f0-1e73-11e8-8957-e9ae0339b8ce.gif)

**Comment by XuejiSun** [comment] 2018-03-02 15:41
Please refer to the screenshot attached.

**Comment by yesmeck** [comment] 2018-03-02 17:39
Good catch, it's a bug.

**Comment by XuejiSun** [comment] 2018-03-04 02:35
Thanks and when will be the fix available? :)

**Comment by benjycui** [comment] 2018-03-07 09:41
I cannot re-produce it, with Chrome@Version 64.0.3282.186 (Official Build) (64-bit)

<img src="http://g.recordit.co/T8vjwEwv8X.gif" />

**Comment by yesmeck** [comment] 2018-03-07 09:49
I can not reproduce it either now...

**Comment by yesmeck** [comment] 2018-03-07 09:49
@XuejiSun Could you check it again?

**Comment by XuejiSun** [comment] 2018-03-07 09:54
Sure, I remembered I did some change today.

**Comment by XuejiSun** [comment] 2018-03-07 09:56
OK now, please try again, I can reproduce it now.

**Comment by yesmeck** [comment] 2018-03-07 09:57
@XuejiSun What do you change?

**Comment by XuejiSun** [comment] 2018-03-07 10:00
I put the subcomponent inside GlobalStoreProvider and add below formItem
<FormItem
          label='Locale'
        >
          {getFieldDecorator('locale', {
            rules: [{ required: false }],
            initialValue: 'en-us'
          })(
            <Select setFieldsValue={this.state.locale} disabled>
              <Option value="en-us">en-us</Option>
            </Select>
            )}
        </FormItem>

**Comment by yesmeck** [comment] 2018-03-08 06:13
Closing since it's not a bug of antd.

**Closed by yesmeck** 2018-03-08 06:13 UTC
Labels: Bug, Component: Form
