### ISSUE TITLE
Modal 

### ISSUE THREAD

**Issue by Sessionking** [ant-design/ant-design#13231] opened 2018-11-21 08:39 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
拖拽功能，能不能来一个

**Comment by afc163** [comment] 2018-11-21 11:48
Duplicate of #3012

**Closed by afc163** 2018-11-21 11:48 UTC
