### ISSUE TITLE
Message will not disappear after timeout when change to another tab and switch back

### ISSUE THREAD

**Issue by DavosLi** [ant-design/ant-design#32161] opened 2021-09-14 08:45 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pu-tong-ti-shi-antd-4-17-0-alpha-0-forked-ypsdo?file=/index.js)

### Steps to reproduce
1.Click the button, the message shows up
2.Switch to another tab, wait for about 5s (longer than message duration)  
3.Switch back to demo tab, you can see the message still exists  

### What is expected?
message should be destoried after message duration time, even when the tab is not active.

### What is actually happening?
message still exists after duration time when switch back to the tab

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | >react 16 |
| System | windows 10 |
| Browser | chrome  92.0.4515.159 (Official Build) (64-bit) |

**Comment by afc163** [comment] 2021-09-14 11:49
Duplicate of #32101

**Closed by afc163** 2021-09-14 11:49 UTC
