### ISSUE TITLE
Form 表单为垂直布局时，Upload展示异常

### ISSUE THREAD

**Issue by xch1029** [ant-design/ant-design#26317] opened 2020-08-21 03:42 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sad-snow-w2vxw?file=/index.js)

### Steps to reproduce
form设置为垂直布局vertical，Upload设置为listType="picture-card"模式

### What is expected?
Upload下方没有100px左右的空白区

### What is actually happening?
Upload下方有个很大的空白区，大约100px

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.12.0 |
| System | windows |
| Browser | chrome  84.0.4147.125 |

**Comment by afc163** [comment] 2020-08-21 03:45
Duplicate of #23339

**Closed by afc163** 2020-08-21 03:45 UTC
