### ISSUE TITLE
Virtual List don't support merged cell.

### ISSUE THREAD

**Issue by yangguansen** [ant-design/ant-design#29580] opened 2021-03-02 06:18 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xuniliebiao-antd4130-forked-ftr8u?file=/index.js)

### Steps to reproduce
write colSpan in columns

### What is expected?
could merged cell

### What is actually happening?
don't merge cell

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | v16 |
| System | mac |
| Browser | Chrome |

---
I have 10000 datas needed to be render at the sametime, and i use merged cell & virtual list, but virtual list don't support merged cell.

**Comment by zombieJ** [comment] 2021-03-02 06:31
Duplicate of #20339

**Closed by zombieJ** 2021-03-02 06:31 UTC
