### ISSUE TITLE
表格分页选中，会把下一页相同位置的行选中

### ISSUE THREAD

**Issue by pkc000pkc** [ant-design/ant-design#10865] opened 2018-06-11 03:27 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.4

### Environment
chrome 67.0.3396.79

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vmp3orv9o3)

### Steps to reproduce
1.点击第一列
2.点击第二列，发现第十一行也会打勾

### What is expected?
第十一行没有变化

### What is actually happening?
第十一行被选中

**Comment by yesmeck** [comment] 2018-06-11 03:38
Duplicate of #10867

**Closed by yesmeck** 2018-06-11 03:38 UTC
