### ISSUE TITLE
Metion组件如果options内容很多，通过方向键操作滚动条不会自行滚动

### ISSUE THREAD

**Issue by Lomnus** [ant-design/ant-design#47329] opened 2024-02-04 05:09 UTC
### Reproduction link

[https://stackblitz.com/edit/react-7nhfay?file=demo.tsx](https://stackblitz.com/edit/react-7nhfay?file=demo.tsx)

### Steps to reproduce

输入@出现metion options，按方向键向下

### What is expected?

通过方向键选中哪里，滚动条相应滚动至该位置

### What is actually happening?

滚动条不会滚动，不知道当前选中了哪一条

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | 18.2 |
| System | windows |
| Browser | Chrome |

**Comment by afc163** [comment] 2024-02-04 05:31
Duplicate of #41651

**Closed by afc163** 2024-02-04 05:31 UTC
Labels: unconfirmed
