### ISSUE TITLE
Calendar日历 如果多日期显示

### ISSUE THREAD

**Issue by Nathanielna** [ant-design/ant-design#25229] opened 2020-06-26 03:47 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
日历组件可以同时显示多个选中，而不是1天

### What does the proposed API look like?
日历组件能够多显示
![image](https://user-images.githubusercontent.com/47273938/85818233-bc4d7800-b7a2-11ea-8973-6c975c6a208b.png)
比如27，28号也显示成26号的选中样子

**Comment by afc163** [comment] 2020-06-28 12:57
Duplicate of #4447

**Closed by afc163** 2020-06-28 12:57 UTC
