### ISSUE TITLE
Menu 组件 mode 为 horizontal，submenu 弹出层间距有问题

### ISSUE THREAD

**Issue by JarvisArt** [ant-design/ant-design#40444] opened 2023-01-29 11:14 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dfc5tv?file=/demo.tsx)

### Steps to reproduce

打开上面的链接窗口缩小点就可以复现

### What is expected?

v4 有间距的
<img width="625" alt="image" src="https://user-images.githubusercontent.com/38420763/215322271-3652eab5-8849-4550-b767-3c562449bd14.png">

### What is actually happening?

v5 没有间距
<img width="630" alt="image" src="https://user-images.githubusercontent.com/38420763/215322238-22160a46-e8fc-48fd-b769-7713a18f27d5.png">

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.0.0 |
| System | mac |
| Browser | chrome |

**Comment by MadCcc** [comment] 2023-01-30 08:24
Duplicate of https://github.com/ant-design/ant-design/issues/39007
这个问题是 overflow 产生的 submenu 接收到的 direction 仍是 `horizontal`，所以偏移按照竖直方向的来了。
在 rc-menu 重构中 解决这个问题。

**Closed by MadCcc** 2023-01-30 08:24 UTC
Labels: unconfirmed
