### ISSUE TITLE
Table 渲染大报表汇总数据时（实际使用场景不允许分页），勾选操作非常卡顿，引入 react-window 会导致 Table 功能缺失(限制)

### ISSUE THREAD

**Issue by fengyun2** [ant-design/ant-design#34135] opened 2022-02-20 05:59 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决渲染大报表汇总数据时，页面能正常使用（勾选、勾选后批量提交入库等各种操作），不卡顿。
demo：https://codesandbox.io/s/ji-ben-yong-fa-antd-4-18-7-forked-he3x8h?file=/index.js:1030-1254

**antd table 引入 `react-window` 后无法使用 rowSelection type = 'checkbox' 勾选功能。**  [[虚拟列表](https://ant-design.gitee.io/components/table-cn/#components-table-demo-virtual-list)](https://ant-design.gitee.io/components/table-cn/#components-table-demo-virtual-list)

### What does the proposed API look like?
API: virtualized | boolean | 呈现大表格数据
```js
const [selectedRowKeys, setSelectedRowKeys] = React.useState([]);
  const rowSelection = {
    selectedRowKeys,
    onChange: (keys) => setSelectedRowKeys(keys),
    type: 'checkbox'
  };
<Table virtualized columns={columns} dataSource={data} rowSelection={rowSelection} />
```

具体效果可参考：https://codesandbox.io/s/optimistic-dew-uu8y07?file=/src/App.js

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/8147202/154830547-89791379-9d0e-4179-8726-cb3ee32f2dfe.png">

**Comment by afc163** [comment] 2022-02-20 07:06
Duplicate of #20339

**Closed by afc163** 2022-02-20 07:06 UTC
