### ISSUE TITLE
4.2.0的Switch关闭状态下的文字样式错乱

### ISSUE THREAD

**Issue by hsl947** [ant-design/ant-design#24046] opened 2020-05-11 09:17 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sleepy-wind-qc8ej)

### Steps to reproduce
使用4.2.0的Switch组件，并加上开启关闭文字，即可重现

### What is expected?
关闭状态下的文字显示正常

### What is actually happening?
关闭状态下的文字显示错误，被覆盖了

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | Win10家庭中文版 B1903 |
| Browser | Google Chrome 81.0.4044.122 |

**Comment by zombieJ** [comment] 2020-05-11 09:30
Duplicate of #23784

**Closed by zombieJ** 2020-05-11 09:30 UTC

**Comment by mtiger95** [comment] 2020-05-11 10:43
add global style can resolve this issue
 `.ant-switch-inner{
  margin-right: 6px;
  margin-left: 24px;
}`
