### ISSUE TITLE
button点击时水波纹视效的一些显示问题

### ISSUE THREAD

**Issue by helloJincheng** [ant-design/ant-design#39965] opened 2023-01-03 02:25 UTC
### Reproduction link

[https://ant.design/components/button-cn](https://ant.design/components/button-cn)

### Steps to reproduce

1.button点击有loading的按钮
2.button点击后切换了界面

### What is expected?

1.button点击时如果有loading，水波纹宽度跟按钮宽度一致
2.button点击后切换了界面，水波纹不显示

### What is actually happening?

1.button点击时如果有loading，水波纹宽度跟按钮宽度不一致
2.button点击后切换了界面，水波纹还会显示一段时间

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.2.0 |
| System | mac |
| Browser | 谷歌 |

**Comment by helloJincheng** [comment] 2023-01-03 02:29
![Kapture 2023-01-03 at 10 18 59](https://user-images.githubusercontent.com/27672145/210292852-aecc5c8c-2980-4441-b290-5e8f715a95e4.gif)
![Kapture 2023-01-03 at 10 27 30](https://user-images.githubusercontent.com/27672145/210293026-68a93433-4658-4b3b-84d5-106450bc1b8c.gif)

**Comment by li-jia-nan** [comment] 2023-01-03 02:30
fixed in #39954

**Comment by afc163** [comment] 2023-01-03 02:30
Duplicate of https://github.com/ant-design/ant-design/issues/39949 and fixed in https://github.com/ant-design/ant-design/pull/39954

**Closed** 2023-01-03 02:30 UTC
