### ISSUE TITLE
tooltip 在两侧不够显示时，箭头位置不对

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#33358] opened 2021-12-20 03:27 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-17-3-forked-oj0me)

### Steps to reproduce
鼠标移上去

### What is expected?
箭头不设置的话位置不对

### What is actually happening?
箭头可以自动调整

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | lastest |
| System | mac |
| Browser | chrome |

---
因为内容是不固定的，可能很长或者很短，根据内容长度去判断设置 placement 感觉不太好。好像跟这个有关系  #30822

**Comment by afc163** [comment] 2021-12-20 03:42
Duplicate of #7038

**Closed by afc163** 2021-12-20 03:42 UTC
