### ISSUE TITLE
already select items gets removed both the new entry and selected one when entered selected value 

### ISSUE THREAD

**Issue by mac066** [ant-design/ant-design#34927] opened 2022-04-08 06:29 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6w033o)

### Steps to reproduce

In the provided link copied from example, a10 and c12 are the two values selected. Now to replace type a10 or c12 and enter.
already selected value get deleted. 

### What is expected?

Can we stop deleting the select value if entered multiple times persisting only the uniques values only?

### What is actually happening?

 select value get deleted when entered

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment] 2022-04-08 12:23
Duplicate of #20198

**Closed by afc163** 2022-04-08 12:23 UTC
