### ISSUE TITLE
Dropdown搭配Popconfirm导致弹出框失控

### ISSUE THREAD

**Issue by ZhangXY-Magic** [ant-design/ant-design#22814] opened 2020-04-01 07:47 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-ant-design-demo-e0lww)

### Steps to reproduce
在Dropdown中操作按钮引入Popconfirm进行二次确认操作，导致Popconfirm弹出框失控

### What is expected?
弹出框正常显示，正常操作

### What is actually happening?
弹出框消失，移动鼠标后闪现

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.12.0 |
| System | windows10 |
| Browser | chrome版本  80.0.3987.132 |

**Comment by afc163** [comment] 2020-04-01 08:00
Duplicate of #22578

**Closed by afc163** 2020-04-01 08:00 UTC
