### ISSUE TITLE
Google's lighthouse: Links are not crawlable (pagination)

### ISSUE THREAD

**Issue by decimoseptimo** [ant-design/ant-design#25628] opened 2020-07-14 23:02 UTC
- [x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This issue negatively impacts the lighthouse test at around 10 points in the SEO measurement

### What does the proposed API look like?
Probably replacing `<a>` for `<button>` tags will do for the pagination component. Although I can forsee similar issues present in other components.

**Comment by xrkffgg** [comment] 2020-07-15 01:22
Duplicate of https://github.com/ant-design/ant-design/issues/25627

**Closed by xrkffgg** 2020-07-15 01:22 UTC

**Comment by sumit-kumar100** [comment] 2023-11-11 07:04
You can use this funtion, I have manually implemented itemRender funtion of Pagination props to solve SEO - Links are not crawlable.
  
const itemRender = (
    current: number,
    type: "page" | "prev" | "next" | "jump-prev" | "jump-next",
    originalElement: React.ReactNode,
  ) => {
    if (type === "jump-prev" || type === "jump-next") {
      return React.cloneElement(
        (originalElement as React.ReactElement).props.children,
      );
    }
    return type === "page" ? <span>{current}</span> : originalElement;
  };
