### ISSUE TITLE
Select 添加 labelInValue属性后，当Option设置为disabled时报错

### ISSUE THREAD

**Issue by kunkkaliu** [ant-design/ant-design#10833] opened 2018-06-07 12:10 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
Mac，chrome  66.0.3359.139（正式版本） （64 位）

### Reproduction link
[https://codepen.io/kunkkaliu/pen/vrXzyY?editors=1111](https://codepen.io/kunkkaliu/pen/vrXzyY?editors=1111)

### Steps to reproduce
打开console，选择一项，console出现错误

### What is expected?
没有错误出现

### What is actually happening?
出现报错信息

**Comment by luisgurmendez** [comment] 2018-06-14 14:08
I think that the problem is in putting a value of an option that is disabled. I dont know why would you like to do this. The error message should be more specific though.

**Comment by picodoth** [comment] 2018-06-14 16:44
@kunkkaliu is it the wrong usage of `lableInValue`, should be an boolean. See https://codepen.io/picodoth/pen/QxMxbW?editors=1111 works just fine.

**Comment by luisgurmendez** [comment] 2018-06-14 17:05
@picodoth Could you elaborate? In @kunkkaliu reproduction link the `labelInValue` is set as a boolean properly. Why are you saying that is wrong? In your example you are setting `labelInValue` in the same way

**Comment by picodoth** [comment] 2018-06-15 02:32
@luisgurmendez my mistake, reopening. I'll take another look later today.

**Comment by kunkkaliu** [comment] 2018-06-19 10:18
@luisgurmendez  Because the project has such a requirement: Initial value is given to the Select, then these initial value options are not optional

**Comment by picodoth** [comment] 2018-06-20 09:55
> 出现报错信息

@kunkkaliu do you mean the following?
> "Warning: flattenChildren(...): Encountered two children with the same key, `.$jack`. Child keys must be unique; when two children share a key, only the first child will be used.
    in ul (created by DOMWrap)
    in DOMWrap (created by SubPopupMenu)
    in SubPopupMenu (created by Connect(SubPopupMenu))
    in Connect(SubPopupMenu) (created by Menu)
    in Provider (created by Menu)
    in Menu (created by DropdownMenu)
    in div (created by DropdownMenu)
    in DropdownMenu (created by SelectTrigger)
    in LazyRenderBox (created by PopupInner)
    in div (created by PopupInner)
    in PopupInner (created by Popup)
    in Align (created by Popup)
    in AnimateChild (created by Animate)
    in Animate (created by Popup)
    in div (created by Popup)
    in Popup"

If this case, this can be fixed by https://github.com/react-component/select/issues/308

**Comment by picodoth** [comment] 2018-06-20 12:44
closing via https://github.com/react-component/select/pull/309

**Closed by picodoth** 2018-06-20 12:44 UTC

**Comment by kunkkaliu** [comment] 2018-06-21 09:06
@picodoth  yes
