### ISSUE TITLE
3.9  how do I replace default icon svg. example datapicker's calendar icon.

### ISSUE THREAD

**Issue by kumaw** [ant-design/ant-design#12123] opened 2018-09-07 02:51 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
use private icon.

### What does the proposed API look like?
Icon should can replace default svg. in 3.8 i can replace iconfont file.

**Comment by afc163** [comment] 2018-09-07 03:04
Duplicate of #12116

**Closed by afc163** 2018-09-07 03:04 UTC

**Comment by HeskeyBaozi** [comment] 2018-09-14 16:59
https://github.com/ant-design/ant-design/pull/12247
