### ISSUE TITLE
两个Tree 组件之间实现拖拽，报错

### ISSUE THREAD

**Issue by Pan-Rong** [ant-design/ant-design#24102] opened 2020-05-13 02:40 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-omh2h?file=/index.js)

### Steps to reproduce
两个Tree 组件之间拖拽即可

### What is expected?
可以实现两个Tree 组件之间拖拽

### What is actually happening?
拖拽时报错，Tree.js 中，报错_this.dragNode为undefined

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13.1 |
| System | windows10 |
| Browser | 81.0.4044.138 |

**Comment by afc163** [comment] 2020-05-13 03:11
Duplicate of #24062

**Closed by afc163** 2020-05-13 03:11 UTC

**Comment by Pan-Rong** [comment] 2020-05-22 03:36
@afc163 您好，请问这个问题，我要怎么操作才能正常工作呢？目前antd 组件已经升级到最新版本了，但问题还在。还请帮忙指点一下，谢谢！

**Comment by thomasstjerne** [comment] 2020-05-26 11:34
@Pan-Rong maybe delete the rc-tree directory from node_modules and run `npm install` to make sure you get the latest.

**Comment by sizhanhe** [comment] 2021-12-16 09:55
难受  感觉还是没解决  一直报错
![image](https://user-images.githubusercontent.com/42952924/146349431-0050f883-64ca-4ac3-8f14-28e3a1299e45.png)
