### ISSUE TITLE
~180kb GZIPPED added to bundle after upgrading to 1.9.1

### ISSUE THREAD

**Issue by m4n3z40** [ant-design/ant-design#12063] opened 2018-09-04 23:21 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
browser

### Reproduction link
[https://github.com/](https://github.com/)

### Steps to reproduce
* Setup a webpack project with route-splitting / lazy-loading
* Add the following to two different split bundle chunks
```js
import Switch from 'antd/lib/switch';
import 'antd/lib/switch/style/index.css';
```
and

```js
import Checkbox from 'antd/lib/checkbox';
import 'antd/lib/checkbox/style/index.css';
```

### What is expected?
Not to impact the resulting bundle size so heavily.

### What is actually happening?
The following is the report of size (gzipped) changes to every file after upgrading to `3.9.1`. No other line was changed.

The `vendors~checkout~search.1540e7f4.chunk.js` chunk is the most aggressive size  change.

This is the chunk that includes both `Switch` and `Checkbox` components.

```
302.84 KB ( 102 B)      build/static/js/main.3eb8996d.js
  183.71 KB (-9 B)        build/static/js/vendors~map.77e00b5f.chunk.js
  179.57 KB ( 172.82 KB)  build/static/js/vendors~checkout~search.1540e7f4.chunk.js
  59.09 KB                build/static/css/2.37587298.css
  40.71 KB ( 2.83 KB)     build/static/js/vendors~search.c4972519.chunk.js
  21.8 KB ( 15 B)         build/static/js/landing~landing-business.729371b2.chunk.js
  17.77 KB ( 3 B)         build/static/js/product.1782b7fe.chunk.js
  17.17 KB (-5 B)         build/static/js/dashboard.d2a055ef.chunk.js
  13.37 KB                build/static/css/main.91efd589.css
  12.36 KB ( 3 B)         build/static/js/faq.1558625e.chunk.js
  11.71 KB ( 2 B)         build/static/js/landing.e0e3f6eb.chunk.js
  10.62 KB ( 4 B)         build/static/js/checkout.97859dcc.chunk.js
  7.88 KB (-705 B)        build/static/js/vendors~checkout.9282ca9f.chunk.js
  7.7 KB (-7 B)           build/static/js/search.a94ec09b.chunk.js
  7.22 KB (-2 B)          build/static/js/checkout~confirmation~product.9a03f1e6.chunk.js
  7.17 KB ( 11 B)         build/static/js/vendors~product.c6717556.chunk.js
  7.07 KB ( 3 B)          build/static/js/product~search.d2e16305.chunk.js
  5.94 KB (-4 B)          build/static/js/confirmation.de8f50c2.chunk.js
  5.14 KB                 build/static/css/24.b757218e.css
  4.5 KB                  build/static/css/10.600cf46b.css
  4.49 KB                 build/static/css/14.e89c7659.css
  4.15 KB ( 1 B)          build/static/js/landing-business.3d596d27.chunk.js
  3.28 KB                 build/service-worker.js
  3.2 KB                  build/static/css/11.f26d489b.css
  2.89 KB ( 6 B)          build/static/js/map.285ad291.chunk.js
  2.88 KB ( 4 B)          build/static/js/privacy-policies.febc84cd.chunk.js
  2.87 KB ( 4 B)          build/static/js/terms-of-use.b770f781.chunk.js
  2.54 KB                 build/static/css/12.02d84b53.css
  2.25 KB                 build/static/css/17.d3899d8b.css
  2.17 KB                 build/static/css/9.3d10ae67.css
  1.88 KB                 build/static/css/22.de55ce27.css
  1.65 KB ( 6 B)          build/static/css/23.e9ef4af4.css
  1.65 KB ( 41 B)         build/static/css/21.a59885b0.css
  1.56 KB (-3 B)          build/static/js/offline.281f2248.chunk.js
  1.21 KB (-1 B)          build/static/js/signout.62121607.chunk.js
  1.11 KB                 build/static/css/0.0f640efe.css
  976 B                   build/static/css/20.d20765d7.css
  891 B                   build/static/css/16.bf3628e8.css
  891 B                   build/static/css/15.bf3628e8.css
  653 B                   build/static/css/5.252e0d6d.css
  483 B (-4 B)            build/static/js/signin.46ca85b3.chunk.js
  450 B                   build/static/css/3.eb82f9e7.css
  405 B (-2 B)            build/static/js/404.b01e9a36.chunk.js
  342 B                   build/static/css/6.311f988c.css
  328 B                   build/static/css/19.e5ebfb26.css
  185 B ( 1 B)            build/static/js/signup.251f99fd.chunk.js
  145 B                   build/static/css/18.36e5c33b.css
```

---
The size change seems to have to do with a bunch of SVG React components (icons maybe). Which I think it was an awful decision.

Using SVG assets as React Components makes your resulting bundle bigger than it needs to. It greatly Increases javascript download, parsing and eval time, which impacts the user's experience directly, worsing the TTI - Time to Interactive - among other key factors.

**Comment by afc163** [comment] 2018-09-05 02:42
Duplicate of #12011

**Closed by afc163** 2018-09-05 02:42 UTC
