### ISSUE TITLE
When you switch month, a particular day of the current month in view is always highlighted, although it's not the selected date

### ISSUE THREAD

**Issue by vivianlixu** [ant-design/ant-design#9121] opened 2018-01-25 03:44 UTC
### Version
3.1.4

### Environment
chrome

### Reproduction link
[https://codepen.io/benjycui/pen/KgPZrE?editors=001](https://codepen.io/benjycui/pen/KgPZrE?editors=001)

### Steps to reproduce
Step 1. open the date picker; 
Step 2. select a date: Feb 15, 2018 (this date is highlighted in blue after selection); 
Step 3. click > button to switch to the next Month, which is March, 2018.

### What is expected?
the cube of March 15 displays as normal without any highlight (because the current selected date is Feb 15)

### What is actually happening?
March 15 is highlighted in blue, which make it look like this date is selected

---
Only the selected date(or the default selected date) should be highlighted with the blue background. When the user browses other months without changing his/her choice, the day of the current month in view shouldn't be highlighted

**Comment by yutingzhao1991** [comment] 2018-01-25 03:52
@yesmeck Is it Expected?

**Comment by yesmeck** [comment] 2018-01-25 03:55
Duplicate of #6146

**Closed by yesmeck** 2018-01-25 03:55 UTC
Labels: Component: DatePicker
