### ISSUE TITLE
Display week number in RangePicker component while picker property is set to date

### ISSUE THREAD

**Issue by GoogleAppEngine** [ant-design/ant-design#22844] opened 2020-04-02 03:53 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In our use case, we want to see week number and pick date,
but RangePicker only display week number when picker = week.
Is there any workaround? Could antd team provide a property like showWeekNumber in RangePicker component?

### What does the proposed API look like?
`<RangePicker` showWeekNumber/>

**Comment by GoogleAppEngine** [comment] 2020-04-02 03:54
could antd team provide  a API like this <RangePicker showWeekNumber/> ?

**Comment by afc163** [comment] 2020-04-02 03:58
Duplicate of #21726

**Closed by afc163** 2020-04-02 03:58 UTC
