### ISSUE TITLE
allowClear and prefix/suffix options for InputNumber

### ISSUE THREAD

**Issue by TheMisir** [ant-design/ant-design#26694] opened 2020-09-11 05:53 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I think InputNumber also might have same features as Input component (eg: allowClear, prefix and suffix, etc.)

### What does the proposed API look like?
Like Input props. ```<InputNumber allowClear suffix="USD" />```

**Comment by xrkffgg** [comment] 2020-09-11 07:06
Duplicate of: https://github.com/ant-design/ant-design/issues/25901

**Closed by xrkffgg** 2020-09-11 07:06 UTC

**Comment by afc163** [comment] 2024-07-10 06:52
`suffix` prop has been added in https://github.com/ant-design/ant-design/pull/49674
