### ISSUE TITLE
![image](https://user-images.githubusercontent.com/56147396/105679345-8b355180-5f03-11eb-91ab-4d8f8809bcc7.png)

### ISSUE THREAD

**Issue by mohammadtaghian** [ant-design/ant-design#29025] opened 2021-01-25 08:44 UTC
![image](https://user-images.githubusercontent.com/56147396/105679345-8b355180-5f03-11eb-91ab-4d8f8809bcc7.png)

_Originally posted by @mohammadtaghian in https://github.com/ant-design/ant-design/issues/29017#issuecomment-766638137_

**Comment by afc163** [comment] 2021-01-25 08:46
Duplicate of #29017

**Closed** 2021-01-25 08:45 UTC
Labels: Invalid
