### ISSUE TITLE
Calendar onSelect and onChange BUG

### ISSUE THREAD

**Issue by thevobos** [ant-design/ant-design#39779] opened 2022-12-23 23:06 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-tf6yus?file=/index.js)

### Steps to reproduce

i am use yarn and npm

### What is expected?

calender props "onChange" wheren i change "year or month" triggering. 
calender props "onSelect" when i select a day or month triggering

### What is actually happening?

"onSelect" triggering but i can't selecting a day when i change the "month" or "year". 

"onChange" will be work when i change "month" or "year". (won't be "onChange". )

| Environment | Info |
| --- | --- |
| antd | 5.0.5 |
| React | 18.2.0 |
| System | MAC VENTURE |
| Browser | CHROME |

---
The "onChange" and "onSelect" functions do the same. "onSelect" should be used for day selection. "onChange" should be used for calendar change.

**Comment by afc163** [comment] 2022-12-29 09:02
Duplicate of #39801

**Closed by afc163** 2022-12-29 09:02 UTC

**Comment by nikhil2802Vishwakarma** [comment] 2024-03-04 11:16
Hi @afc163 ,

Is this fix and is it up with the latest version? I am still facing an issue with headerRender. When onChange is triggered from the header render than the selected date is also changing  Or is there any selection to fix the issue?

```
<Calendar
                value={new dayjs(selectedDate)}
                disabledDate={disabledDate}
                onChange={dateSelectHandler}
                mode={'month'}
                fullscreen={false}
                headerRender={({ value, onChange }) => {
                    const handlePrev = () => {
                        onChange(value.clone().subtract(1, 'month'), 'sub');
                    };

                    const handleNext = () => {
                        onChange(value.clone().add(1, 'month'), 'sub');
                    };

                    return (
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                            <button onClick={handlePrev}>Previous</button>
                            <div>{value?.format('MMMM YYYY')}</div>
                            <button onClick={handleNext}>Next</button>
                        </div>
                    );
                }}
            />
```
