### ISSUE TITLE
Popconfirm children using custom button component got findDOMNode is deprecated in StrictMode 

### ISSUE THREAD

**Issue by eveforest** [ant-design/ant-design#43311] opened 2023-07-01 08:25 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/an-niu-lei-xing-antd-5-6-3-forked-tnqtg7?file=/demo.tsx)

### Steps to reproduce

button直接作为Popconfirm的children没问题，封装成组件再作为Popconfirm的children就报这个错误

### What is expected?

没有警告

### What is actually happening?

出现警告：Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper2 which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at button

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | 18.2.0 |
| System | win10 |
| Browser | chrome 版本 113.0.5672.63（正式版本） （64 位） |

**Comment by Yuiai01** [comment] 2023-07-01 12:09
Duplicate of https://github.com/ant-design/ant-design/issues/43064

**Closed** 2023-07-01 12:15 UTC
Labels: unconfirmed
