### ISSUE TITLE
In the table, I hope all my content can in a line, no wrap.

### ISSUE THREAD

**Issue by Churchson** [ant-design/ant-design#13322] opened 2018-11-28 06:38 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
After the table is dragged, the column width is reset. The width of the column is insufficient, resulting in a newline of the content.The table looks ugly.When the content exceeds the width of the column, i hope i can choose to hide it, or can be ellipsis, no wrap.

### What does the proposed API look like?
I hope it has a api in columns. Maybe this name is isWrap, typeof boolean. default value is true. it can be using for the table, if it is false, all the content in one line, the content overflow the column's width, it can be ellipsis.

**Comment by afc163** [comment] 2018-11-28 07:01
Duplicate of #5753

**Closed by afc163** 2018-11-28 07:01 UTC
