### ISSUE TITLE
Table多列排序，sorter不返回数组

### ISSUE THREAD

**Issue by ALL-STACK** [ant-design/ant-design#37099] opened 2022-08-17 02:09 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duo-lie-pai-xu-antd-4-22-5-forked-eppw1b?file=/demo.js)

### Steps to reproduce

点击排序触发表格onChange事件，sorter字段不返回数组

### What is expected?

多列排序返回数组

### What is actually happening?

只返回了单个排序数据

| Environment | Info |
| --- | --- |
| antd | 4.22.5 |
| React | react |
| System | win10 |
| Browser | chrome |

**Comment by MadCcc** [comment] 2022-08-17 02:14
Duplicate of https://github.com/ant-design/ant-design/issues/37024

**Closed by MadCcc** 2022-08-17 02:14 UTC
