### ISSUE TITLE
Cursor caret in Select (tag mode) goes disappeared

### ISSUE THREAD

**Issue by FINAs** [ant-design/ant-design#23175] opened 2020-04-13 01:58 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://dzwuff.run.stackblitz.io](https://dzwuff.run.stackblitz.io)

### Steps to reproduce
1. click the input box
2. check the caret

### What is expected?
1.click the input box
2.show the cursor caret

### What is actually happening?
It seems works fine on the official website,but there goes no caret when the code run in the stackblitz or my project.
It only breaks in chrome.

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | lastest |
| System | windows 10 |
| Browser | chrome |

**Comment by afc163** [comment] 2020-04-13 10:59
> https://dzwuff.run.stackblitz.io/

This link cannot be open.

**Comment by afc163** [comment] 2020-04-14 02:41
Duplicate of #23059

**Closed by afc163** 2020-04-14 02:41 UTC
Labels: 🤔 Need Reproduce
