### ISSUE TITLE
scroll with expandedRowRender rendering issue

### ISSUE THREAD

**Issue by benbruscella** [ant-design/ant-design#20712] opened 2020-01-06 23:56 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/interesting-dew-rodfq)

### Steps to reproduce
Expand row

### What is expected?
expanded row maintains alignment

### What is actually happening?
expanded row not aligned with scroll action

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | 16.12.0 |
| System | OSX 10.14.6 |
| Browser | Firefox 71.0 Chrome  |

**Comment by afc163** [comment] 2020-01-07 03:18
<img width="717" alt="image" src="https://user-images.githubusercontent.com/507615/71865854-2fa0f600-313f-11ea-91f2-3c63bd154355.png">

Duplicate of #9900

**Closed by afc163** 2020-01-07 03:18 UTC
