### ISSUE TITLE
对body设置scale的时候会影响到tooltip等组件的定位

### ISSUE THREAD

**Issue by SophinQ** [ant-design/ant-design#27742] opened 2020-11-13 04:18 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/sophinq/pen/oNLJVJJ](https://codepen.io/sophinq/pen/oNLJVJJ)

### Steps to reproduce
设置body scale为0.5，tooltip的定位不准确。设置scale为1，定位准确

### What is expected?
在对body设置scale时，tooltip的定位能够准确。

### What is actually happening?
在对body设置scale(0.5)时，tooltip的定位不准确。

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | windows10  |
| Browser | chrome  86.0.4240.111 |

**Comment by afc163** [comment] 2020-11-13 05:45
Duplicate of #26681

**Closed by afc163** 2020-11-13 05:45 UTC

**Comment by Flourad** [comment] 2021-01-25 08:00
> Duplicate of #26681
请问这个问题有办法解决么？
