### ISSUE TITLE
antd.table的sticky 在tabs失效

### ISSUE THREAD

**Issue by vanness30214** [ant-design/ant-design#34398] opened 2022-03-10 02:23 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sui-ye-mian-gun-dong-de-gu-ding-biao-tou-he-gun-dong-tiao-antd-4-19-1-forked-m8p7wq?file=/index.js)

### Steps to reproduce
在tabs中虚拟滚动条失效

### What is expected?
tabs中table虚拟滚动条也能实现

### What is actually happening?
tabs中table虚拟滚动条失效，也试了getContainer 加上其他父元素Dom也是不行

| Environment | Info |
|---|---|
| antd | 4.19.1 |
| React | 17.0.2 |
| System | window 10 |
| Browser | 99.0.1150.30 |

**Comment by afc163** [comment] 2022-03-10 02:40
Duplicate of #34021

**Closed by afc163** 2022-03-10 02:40 UTC
