### ISSUE TITLE
Input 的suffix过长时，Input的值会和suffix重叠

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#19427] opened 2019-10-25 09:37 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-cn/#components-input-demo-presuffix](https://ant.design/components/input-cn/#components-input-demo-presuffix)

### Steps to reproduce
下面 suffix为RMB或者文字过长时， 输入很多很多字符，会出现重叠
![image](https://user-images.githubusercontent.com/46179450/67560714-0aab0280-f74e-11e9-8588-18bda0fdaa34.png)

### What is expected?
不出现重叠

### What is actually happening?
重叠了

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | latest |
| System | windows10 |
| Browser | chrome78 |

**Comment by afc163** [comment] 2019-10-25 09:40
Duplicate of #17811

**Closed by afc163** 2019-10-25 09:40 UTC
