### ISSUE TITLE
Table.Column defaultFilteredValue not working with responsive attribute

### ISSUE THREAD

**Issue by bloriot97** [ant-design/ant-design#35057] opened 2022-04-15 15:43 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-daufaultfilterissue-090hyq)

### Steps to reproduce

Add `filters`, `defaultFilteredValue` and `responsive` attributes to a Column.

### What is expected?

Default filter values should be selected.

### What is actually happening?

No filter values selected.

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18 |
| System | macos 12.3  |
| Browser | Chrome 100.0.4896.75 |

---
Also the case with `columns` attribute.

**Comment by afc163** [comment] 2022-04-18 11:46
Duplicate of #32847

**Closed by afc163** 2022-04-18 11:46 UTC
