### ISSUE TITLE
disable whole form with fieldset

### ISSUE THREAD

**Issue by pawarvijay** [ant-design/ant-design#10475] opened 2018-05-11 07:14 UTC
- [X] I have searched the [issues] for reference issue #5562 it closed by bot , but deeply require this  

### Version
3.5.1

### Environment
mac os

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qvrozkkypw)

### Steps to reproduce
use antd select inside fieldset

### What is expected?
in native HTML` <fieldset/>` element disables all controls inside it

so andt components also should behave like it.

[it should disable html controls like this](http://jsfiddle.net/7qGHN/)

### What is actually happening?
antd dropdown is not getting disabled inside fieldset element [example](https://codesandbox.io/s/qvrozkkypw) 
 

---
i have over 30 forms each with 40...50 antd controls
and i don't want to create separate view page for each form

one good news will be 'it disabled textbox' 
but
dropdown is enabled

**Comment by yesmeck** [comment] 2018-05-11 08:01
Duplicate of #743 

We won't support fieldset.

**Closed by yesmeck** 2018-05-11 08:01 UTC
