### ISSUE TITLE
希望Form出一个控制里面组件大小的 api

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#19462] opened 2019-10-28 10:13 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
不用每个组件去写size

### What does the proposed API look like?
```
<Form size='small' />
size : 'small'|'large'|'mini'
```

**Comment by afc163** [comment] 2019-10-28 10:31
Duplicate of #17570

**Closed by afc163** 2019-10-28 10:31 UTC
