### ISSUE TITLE
drag and drop rows between antd tables 

### ISSUE THREAD

**Issue by mx2323** [ant-design/ant-design#30488] opened 2021-05-11 18:50 UTC
- [X ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
the only feature that we need in order to adopt ant design table throughout our app is being able to drag and then drop rows between antd tables.

### What does the proposed API look like?
some simple API that allows a row to be dragged that specifies the drop data, and some simple APIs on the drop side that understands the row, can visually indicate where the row will be dropped in the other table and then actually completing the row drop. 

if this is already possible - adding some documentation in the docs with an example would be great!

**Comment by mx2323** [comment] 2021-05-17 19:39
bump

**Comment by afc163** [comment] 2021-05-18 02:52
Duplicate of #26560

**Closed by afc163** 2021-05-18 02:52 UTC
