### ISSUE TITLE
An error occurred using the list component, ./node_modules/antd/es/spin/style/index.css Module build failed: Syntax Error 

### ISSUE THREAD

**Issue by sfyr111** [ant-design/ant-design#9518] opened 2018-03-05 06:47 UTC
### Version
3.2.3

### Environment
OS

### Reproduction link
[https://ant.design/components/list-cn/#components-list-demo-basic](https://ant.design/components/list-cn/#components-list-demo-basic)

#### code
```
import { List, Avatar } from 'antd';
const data = [
  {
    title: 'Ant Design Title 1',
  },
  {
    title: 'Ant Design Title 2',
  },
  {
    title: 'Ant Design Title 3',
  },
  {
    title: 'Ant Design Title 4',
  },
];


        <List
          itemLayout="horizontal"
          dataSource={data}
          renderItem={item => (
            <List.Item>
              <List.Item.Meta
                avatar={<Avatar src="https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png" />}
                title={<a href="https://ant.design">{item.title}</a>}
                description="Ant Design, a design language for background applications, is refined by Ant UED Team"
              />
            </List.Item>
          )}
        />
```

#### error
```
./node_modules/antd/es/spin/style/index.css
Module build failed: Syntax Error 

(96:10) Missed semicolon

  94 |   filter: blur(0.5px);
  95 |   /* autoprefixer: off */
> 96 |   filter: progid\:DXImageTransform\.Microsoft\.Blur(PixelRadius\=1, MakeShadow\=false);
     |          ^
  97 |   -webkit-transform: translateZ(0);
  98 | }

```

### What is expected?
no error

#### error
```
./node_modules/antd/es/spin/style/index.css
Module build failed: Syntax Error 

(96:10) Missed semicolon

  94 |   filter: blur(0.5px);
  95 |   /* autoprefixer: off */
> 96 |   filter: progid\:DXImageTransform\.Microsoft\.Blur(PixelRadius\=1, MakeShadow\=false);
     |          ^
  97 |   -webkit-transform: translateZ(0);
  98 | }

```

**Comment by yutingzhao1991** [comment] 2018-03-05 07:34
Duplicate of #4915

**Comment by yesmeck** [comment] 2018-03-05 08:29
Don't apply less-loader to css.

**Closed by yesmeck** 2018-03-05 08:29 UTC
Labels: Component: List
