### ISSUE TITLE
InputNumber 无法正确格式化以色列等国家的负数值

### ISSUE THREAD

**Issue by xuqiang1227** [ant-design/ant-design#28058] opened 2020-11-28 04:32 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/geshihuazhanshi-antd486-forked-3sc5e)

### Steps to reproduce
以色列等国家的负数格式显示为：`-x.xxx.xxx,xxx`

也就是千分位分隔符为 `.`， 小数点为： `,`

当输入值为 `-88888888888.88` 应该格式化为： `-88.888.888.888,88` ，但实体上显示为： `-88,888.888.888,88`

格式化正则表达式为：`/\B(?=(\d{3}) (?!\d))/g`

### What is expected?
当输入值为 `-88888888888.88` 应该格式化为： `-88.888.888.888,88`

### What is actually happening?
实际上显示的为: `-88,888.888.888,88`

| Environment | Info |
|---|---|
| antd | 4.8.6 |
| React | 16.14.0 |
| System | window 10 |
| Browser | chrome 87 |

**Comment by yoyo837** [comment] 2020-11-28 04:46
Duplicate of #28058

**Closed by yoyo837** 2020-11-28 04:46 UTC
