### ISSUE TITLE
Maybe  it is time to update most of the components that use 'ComponentWillReceiveProps' .

### ISSUE THREAD

**Issue by melodyWxy** [ant-design/ant-design#18257] opened 2019-08-14 03:52 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
   use  ant-design using version 3.14.2.   
   use  Menu or Form or other components using this hook… you know what happened

### What does the proposed API look like?
 it Should not contain 'ComponentWillReceiveProps'， updating it In the next version please.

**Comment by maruhgar** [comment] 2019-08-14 05:47
Using the latest ant design with react 16.9.0 shows the following deprecation warning

<img width="884" alt="Screenshot 2019-08-14 at 11 16 45 AM" src="https://user-images.githubusercontent.com/1837792/62997193-13957300-be85-11e9-94a4-96aacfdccedd.png">

**Comment by afc163** [comment] 2019-08-14 06:21
Duplicate of #9792

**Closed by afc163** 2019-08-14 06:21 UTC
