### ISSUE TITLE
tree 树能不能实现点击节点实现展开收缩

### ISSUE THREAD

**Issue by 1195002442** [ant-design/ant-design#29111] opened 2021-01-29 06:12 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
使用树节点前的小三角点击目标太小，不便于操作

### What does the proposed API look like?
和内置的目录树实现的效果一样，点击树节点实现展开收缩。但是内置的目录树不能自定义图标

**Comment by zombieJ** [comment] 2021-01-29 09:43
Duplicate of #27507

**Closed by zombieJ** 2021-01-29 09:43 UTC

**Comment by coldice945** [comment] 2022-04-25 11:22
可以通过修改样式的方式变相实现

https://github.com/ant-design/ant-design/issues/27507#issuecomment-1108443102
