### ISSUE TITLE
TreeSelect的showCheckedStrategy属性设置TreeSelect.SHOW_ALL还是不显示父节点？

### ISSUE THREAD

**Issue by liangchaofei** [ant-design/ant-design#24086] opened 2020-05-12 10:08 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-ant-design-demo-l6xxt)

### Steps to reproduce
选择子节点，父节点不显示

### What is expected?
选择子节点，父节点也显示

### What is actually happening?
选择子节点，父节点不显示

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | REACT |
| System | MAC |
| Browser | CHROME |

**Comment by afc163** [comment] 2020-05-12 10:12
Duplicate of #23493

**Closed by afc163** 2020-05-12 10:12 UTC

**Comment by liangchaofei** [comment] 2020-05-12 12:08
> Duplicate of #23493

这个没解决。辛苦再看下。设置showCheckedStrategy='SHOW_ALL' 不生效
