### ISSUE TITLE
[Message] - allow selecting animation for display

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design#9388] opened 2018-02-21 15:02 UTC
### What problem does this feature solve?
Be able to select how Message appears: fade in; flash; bounce; etc

### What does the proposed API look like?
Argument: 'animation'

**Comment by muzea** [comment] 2018-03-08 16:13
Duplicate of #9387

**Comment by avalanche1** [comment] 2018-03-09 10:56
I don't see how this is a duplicate.

**Comment by afc163** [comment] 2018-03-09 11:15
Merged in #9580

**Closed by afc163** 2018-03-09 11:15 UTC
Labels: Component: Message, Feature Request, PR welcome
