### ISSUE TITLE
Can't select menu overlay on Safari

### ISSUE THREAD

**Issue by violabg** [ant-design/ant-design#8501] opened 2017-12-07 11:18 UTC
### Version
3.0.0

### Environment
macOS browser Safari 11

### Reproduction link
[https://ant.design/components/menu/](https://ant.design/components/menu/)

### Steps to reproduce
hover a menu item to open its overlay 

### What is expected?
to be able to select a sub menu item on the overlay

### What is actually happening?
the overlay closes before you can interact with it

### Additional info
it works on Chrome

**Comment by afc163** [comment] 2017-12-07 13:37
Duplicate of #8453

**Closed by afc163** 2017-12-07 13:37 UTC
