### ISSUE TITLE
分页更新不触发onChange

### ISSUE THREAD

**Issue by unforesndprson** [ant-design/ant-design#41602] opened 2023-04-03 02:31 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fen-ye-she-zhi-antd-4-24-8-forked-bx84zd?file=/demo.tsx)

### Steps to reproduce

第二页删掉一个数据

### What is expected?

触发onChange

### What is actually happening?

分页展示更新了,但没有触发onChange

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 18 |
| System | macos 12.5.1 |
| Browser | chrome 111.0.5563.110 |

**Comment by afc163** [comment] 2023-04-03 10:18
Duplicate of https://github.com/ant-design/ant-design/issues/37823#issuecomment-1272237451

**Closed by afc163** 2023-04-03 10:18 UTC
Labels: unconfirmed
