### ISSUE TITLE
Input.Password: Chrome auto complete render background color region not very well

### ISSUE THREAD

**Issue by moonrailgun** [ant-design/ant-design#28548] opened 2020-12-25 12:11 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In normal case, chrome will record and auto complete form data.

and its not a good look. I think its should be improve

Just like this:  
![image.png](https://i.loli.net/2020/12/25/ejx2tgciJrw7NYU.png)

### What does the proposed API look like?
I think `Input.Password` should be a input tag fill in container and the switch button should be float over this dom

**Comment by afc163** [comment] 2020-12-28 04:05
Duplicate of https://github.com/ant-design/ant-design/issues/22593#issuecomment-603815276

**Closed by afc163** 2020-12-28 04:05 UTC
