### ISSUE TITLE
Dropdown does not change width when select width being changed

### ISSUE THREAD

**Issue by ops1ops** [ant-design/ant-design#29163] opened 2021-02-01 14:43 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-w3p4r?file=/index.js)

### Steps to reproduce
1. Set select width to 100%
2. Create some media queries that change select container width with different values
3. Open it in any mobile device
4. Open select
5. Change orientation

### What is expected?
Expected that dropdown width will be the same as select width

### What is actually happening?
Dropdown width stays with the same value

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 17.0.1 |
| System | Ubuntu 18.4 |
| Browser | Chrome last version |

**Comment by afc163** [comment] 2021-02-02 03:03
Duplicate of #28159

**Closed by afc163** 2021-02-02 03:03 UTC
