### ISSUE TITLE
升级v4.7后，menu导航三级菜单Uncaught Error: Unable to find node on an unmounted component.

### ISSUE THREAD

**Issue by bgy10** [ant-design/ant-design#27237] opened 2020-10-19 10:52 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stoic-galileo-eh5ip?file=/index.js)

### Steps to reproduce
menu导航菜单一至二级，collapsed伸展和收缩无问题，当展开第三级菜单时，再collapsed收缩即会出现
```
Uncaught Error: Unable to find node on an unmounted component.
```

### What is expected?
menu菜单展开和收缩

### What is actually happening?
第展开第三级菜单时，再collapsed收缩即会出现Uncaught Error: Unable to find node on an unmounted component.

| Environment | Info |
|---|---|
| antd | 4.7.1 |
| React | 16.9.0 |
| System | mac10.15.5 |
| Browser | chrome 86.0.4240.80 |

---
这应该升级版本4.7后，menu新产生的bug，而在版本4.6.3是不存在此bug，
官方文档实例也存在此error https://ant.design/components/menu-cn/#components-menu-demo-inline-collapsed

**Comment by afc163** [comment] 2020-10-19 11:15
Duplicate of #27176

**Closed by afc163** 2020-10-19 11:15 UTC
