### ISSUE TITLE
Select  use autoComplete="off" 

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#7659] opened 2017-09-19 07:49 UTC
### Version
2.13.2

### Environment
antd latest

### Reproduction link
[https://user-images.githubusercontent.com/25046350/29009116-f27ef532-7b52-11e7-9e3e-7949cee761f8.png](https://user-images.githubusercontent.com/25046350/29009116-f27ef532-7b52-11e7-9e3e-7949cee761f8.png)

### Steps to reproduce
insert content

### What is expected?
Does not display browser prompt

### What is actually happening?
Displays a browser prompt

**Comment by qq645381995** [comment] 2017-09-19 07:49
Don't need a example, a see will know that

**Comment by qq645381995** [comment] 2017-09-19 07:50
#7108

**Comment by afc163** [comment] 2017-09-19 07:52
Fixed in https://github.com/react-component/select/commit/bf0d54c262b2ca7e99fe403809acb8742650eb91

**Closed by afc163** 2017-09-19 07:52 UTC

**Comment by qq645381995** [comment] 2017-09-19 07:53
By the way, will antd be maintained

**Comment by afc163** [comment] 2017-09-19 07:56
#7656

**Comment by qq645381995** [comment] 2017-09-19 07:59
![image](https://user-images.githubusercontent.com/7971419/30581674-88c1da92-9d53-11e7-8aae-6236d1e9a5ac.png)

**Comment by afc163** [comment] 2017-09-19 08:05
https://github.com/react-component/select/commit/2361a46ec6a2bc16e9dc39e1cfa728e51eed73e3

**Comment by qq645381995** [comment] 2017-09-19 08:09
![image](https://user-images.githubusercontent.com/7971419/30582055-ed372a3a-9d54-11e7-8059-1b9b598b0a0a.png)

**Comment by 476474988** [comment] 2018-06-15 07:30
which version of ant-design has resolved for this bug?

**Comment by AdamGerthel** [comment] 2019-01-10 12:10
This is still an issue, since Chrome has started to ignore autoComplete="off" (see https://stackoverflow.com/questions/15738259/disabling-chrome-autofill). I suggest that a prop is added that makes it possible to set input attributes via a property on the Select/Cascader component.

![screenshot 2019-01-10 at 12 51 12](https://user-images.githubusercontent.com/1490370/50967676-1720e000-14d9-11e9-8b12-950a0cbabf55.jpg)

**Comment by ztplz** [comment] 2019-01-10 22:17
@AdamGerthel   Which version are you chrome? Now it's works. See this comment(https://stackoverflow.com/questions/12374442/chrome-ignores-autocomplete-off/52082658#52082658). Here is the demo in comment. http://jsfiddle.net/AlexandrAbakumov/L0e2u7v4/124/

**Comment by AdamGerthel** [comment] 2019-01-10 23:33
@ztplz that's strange.. I'm using Chrome 71. 

The fiddle works, but as you can see in my screenshot, I'm clearly getting an address autofill on a Cascader component. It happens immediately on input focus. I don't have time to make a working fiddle right now. I'm not sure if there's a difference between autofill and autocomplete in Chrome, or why it thinks that I'm trying to fill an address. The `name` attribute of the field was not address-related.

A strange observation I did was that it stopped happening when I used `popupPlacement="topLeft"`

**Comment by ztplz** [comment] 2019-01-11 00:40
What confuses me is that some people say it works, but others say it doesn't work. I just tested it locally, it works. My Chrome version is also 71.  Maybe this issue needs more feedback.

**Comment by ztplz** [comment] 2019-01-11 00:45
It’s hard to figure out where the problem is without reproduce demo.

**Comment by AdamGerthel** [comment] 2019-01-11 08:58
Yep - I tried to make to reproduce it with simple form fields, to trigger the "address" autocomplete that Chrome has, but I couldn't. The suggestion box does not appear if `autoComplete="off"`, and they do appear if there is no autoComplete attribute at all.

![jan-11-2019 09-58-00](https://user-images.githubusercontent.com/1490370/51023535-70dfe380-1587-11e9-9ccd-61a26ed0897c.gif)

Their adddress autocomplete is really weird because it is based on pretty [intricate guesses](https://stackoverflow.com/questions/7223168/how-to-trigger-autofill-in-google-chrome/41965106#41965106).

See https://jsfiddle.net/insats/60oLvumq for my test.

**Comment by ztplz** [comment] 2019-01-11 09:47
Thanks for make sense. It seems that it is working now. So what situation did you have this problem?

**Comment by AdamGerthel** [comment] 2019-01-11 09:54
On a Cascader component. I have rewritten it to use the TreeSelect component because of this issue, and I don't have time right now to reproduce it. I guess we'll have to close the issue for the moment and see if it turns up again in the future.

**Comment by zomars** [comment] 2019-08-15 18:11
Related to #15875

**Comment by HyperMaxime** [comment] 2020-01-14 14:06
Did anyone find a workaround for this issue?

**Comment by Wremeker** [comment] 2020-01-14 16:51
Has anyone found a solution for ant design?

**Comment by gino8080** [comment] 2020-01-31 10:27
any news on this?

**Comment by gino8080** [comment] 2020-01-31 11:02
ok this a DIRTY and absolutely NO ELEGANT hack but works..
waiting until antd select autoComplete attribute became editable:

just run this function when form is rendered first time
I put this on a 1 time  useEffect:
 
```javascript
 const fixAutocomplete = () => {
      document.querySelectorAll(".ant-select-selector input").forEach((e) => {
         e.setAttribute("autocomplete", "stopDamnAutocomplete");
        //you can put any value but NOT "off" or "false" because they DO NOT works
      })
    }
```

**Comment by zomars** [comment] 2020-01-31 17:05
You can try adding `autoComplete="new-password"`

**Comment by gino8080** [comment] 2020-01-31 17:37
the problem is that the antd select does not permit to change the autocomplete value
so setting autoComplete="new-password" has NO effect

the dirty hack force the new value on autocomplete prop, and the browser (Chrome for example) does not popup the autofill

**Comment by rbabayoff** [comment] 2020-08-18 18:23
Hey, got it working in chrome by adding "dontshow" instead of "off":

```
<Select autoComplete="dontshow">
```

**Comment by juliocabify100** [comment] 2020-10-28 19:28
> Hey, got it working in chrome by adding "dontshow" instead of "off":
> 
> ```
> <Select autoComplete="dontshow">
> ```

Also <Select autoComplete="chrome-off">
Ref: [https://stackoverflow.com/questions/15738259/disabling-chrome-autofill](https://stackoverflow.com/questions/15738259/disabling-chrome-autofill)

**Comment by juliocabify100** [comment] 2020-10-28 19:29
> Hey, got it working in chrome by adding "dontshow" instead of "off":
> 
> ```
> <Select autoComplete="dontshow">
> ```

**Also**: `<Select autoComplete="chrome-off">`
Ref: https://stackoverflow.com/questions/15738259/disabling-chrome-autofill

**Comment by N00nDay** [comment] 2020-10-30 12:52
As of Chrome 86 none of my workarounds work any more including the new "chrome-off". I have tried the following:

```
<Form autoComplete="off" ...>
<Form autoComplete="chrome-off" ...>
<Form autoComplete="false" ...>
<Form autoComplete="new-password" ...>
<Form autoComplte="for-the-love-of-all-that-is-holy-dont-use-autocomplete" ...>

<Select autoComplete="off" ...>
<Select autoComplete="chrome-off" ...>
<Select autoComplete="false" ...>
<Select autoComplete="new-password" ...>
<Select autoComplte="for-the-love-of-all-that-is-holy-dont-use-autocomplete" ...>
```

I have tried the options above together and in isolation to no avail. I have even tried using the hidden email and password field at the top of my form and still the autoComplete persists.

![Screen Shot 2020-10-30 at 8 47 00 AM](https://user-images.githubusercontent.com/28783829/97706850-b9360180-1a8c-11eb-99ce-e63cf24d5c0d.png)
![Screen Shot 2020-10-30 at 8 47 35 AM](https://user-images.githubusercontent.com/28783829/97706856-bc30f200-1a8c-11eb-9ecb-86d627459137.png)

**Comment by N00nDay** [comment] 2020-10-30 13:37
Found another workaround that will tide me over until Chrome decides they don't like this. I hate it because it makes the text cursor jitter but it makes my forms usable again so I will take if for now. The trick involves using the `onFocus` attribute of the `<Select />` component. `onSelect` fires a function that grabs the input then changes its value to `value=" "` then quickly changes it back to `value=""`.  Full example below.

```
const handleFocus = (el) => {
  const input = el.currentTarget.getElementsByTagName("INPUT")[0];
  input.value = " ";
  setTimeout(() => {
    input.value = "";
  });
};

<Select onFocus={handleFocus} ... />
```

The code we need, but not the code we deserve.

**Comment by N00nDay** [comment] 2020-10-30 15:52
The work around above doesn't work for inputs so below is my custom input for disabling `autoComplete`:

```
import React, { forwardRef } from "react";
import Input from "antd/es/input";

const InputNoAutoComplete = (
  {
    value,
    onChange,
    disabled,
    handleFocus,
    handleBlur,
    autoFocus = false,
    placeholder = undefined,
    type = "text",
    allowClear = false,
  },
  ref
) => {
  const triggerChange = (changedValue) => {
    if (onChange) {
      onChange(changedValue);
    }
  };

  const handleChange = (e) => {
    triggerChange(e.target.value);
  };

  return (
    <>
      <label htmlFor="" style={{ display: "none" }}>
        hidden label to mislead chrome autocomplete
      </label>
      <Input
        ref={ref}
        placeholder={placeholder}
        autoComplete="dont-use-autocomplete"
        disabled={disabled}
        onFocus={handleFocus}
        onBlur={handleBlur}
        onChange={handleChange}
        value={value}
        autoFocus={autoFocus}
        type={type}
        allowClear={allowClear}
      />
    </>
  );
};

export default forwardRef(InputNoAutoComplete);
```

Just use <InputNoAutoComplete ... /> instead of <Input ... /> and this does the trick. Simply adds a hidden label with the for value set to blank. Tricks Google and NO AUTOCOMPLETE!!! Again works for now but we shall see if Chrome catches on and "fixes" (those are air quotes) this problem in a future update.

The code we need, not not the code we deserve.

**Comment by camilo0119** [comment] 2020-11-14 23:02
> ok this a DIRTY and absolutely NO ELEGANT hack but works..
> waiting until antd select autoComplete attribute became editable:
> 
> just run this function when form is rendered first time
> I put this on a 1 time useEffect:
> 
> ```js
>  const fixAutocomplete = () => {
>       document.querySelectorAll(".ant-select-selector input").forEach((e) => {
>          e.setAttribute("autocomplete", "stopDamnAutocomplete");
>         //you can put any value but NOT "off" or "false" because they DO NOT works
>       })
>     }
> ```

Thank´s!!!

**Comment by N00nDay** [comment] 2020-11-21 19:06
This was working a few Chrome versions ago but is no longer working on my
current version of Chrome.

**Comment by ws-zykina** [comment] 2021-08-05 10:02
https://github.com/ant-design/ant-design/issues/15875#issuecomment-848943506


it helped me

**Comment by SlothDevLlama** [comment] 2021-10-10 08:50
> Hey, got it working in chrome by adding "dontshow" instead of "off":
> 
> ```
> <Select autoComplete="dontshow">
> ```

my silent hero!
