### ISSUE TITLE
怎么看待 Ant Design 圣诞彩蛋？

### ISSUE THREAD

**Issue by x-strong** [ant-design/ant-design#13883] opened 2018-12-25 09:42 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
中国

### Reproduction link
[http://new-issue.ant.design](http://new-issue.ant.design)

### Steps to reproduce
ant-d

### What is expected?
ant-d 智商正常。

### What is actually happening?
ant-d 智障！

---
ant-d 圣诞彩蛋始作俑者是TMD大傻逼！

**Comment by afc163** [comment] 2018-12-25 09:47
Duplicate of #13848

**Closed by afc163** 2018-12-25 09:47 UTC
