### ISSUE TITLE
采用了文档中推荐的虚拟表格实现方案后，设置rowSelection不起效果，

### ISSUE THREAD

**Issue by rollYouth** [ant-design/ant-design#25567] opened 2020-07-10 07:30 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/thirsty-shape-ldg9v?file=/index.js)

### Steps to reproduce
正常使用

### What is expected?
虚拟dom和多选能够并存

### What is actually happening?
虚拟dom和多选只能有一个生效

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | 16.8.6 |
| System | win10 |
| Browser | 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 |

---
业务要求需要渲染大量数据不采用分页，同时需要多选做批量处理

**Comment by afc163** [comment] 2020-07-10 09:01
Duplicate of #20339

**Closed by afc163** 2020-07-10 09:01 UTC

**Comment by bihongbin3027** [comment] 2023-05-16 08:47
@rollYouth 这个问题解决了吗 我现在也是rowSelection不起作用
