### ISSUE TITLE
[tabs] : docs error `onTabClick` Callback Arguments

### ISSUE THREAD

**Issue by RSS1102** [ant-design/ant-design#39971] opened 2023-01-03 09:04 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-lz9exn?file=/index.tsx)

### Steps to reproduce

```ts
被点击的回调
文档：
onTabClick function(key: string, event: MouseEvent)	
ts定义：
onTabClick?: (activeKey: string, e: React.KeyboardEvent | React.MouseEvent) => void;
```

### What is expected?

类型正确

### What is actually happening?

类型报错

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.2.0 |
| System | win11 |
| Browser | Chrome  108.0.5359.125 |

![image](https://user-images.githubusercontent.com/81673017/210326963-0acc2c1c-f8ea-472f-ae28-179c06212006.png)

**Comment by RSS1102** [comment] 2023-01-03 09:06
5.1问题tbas：
https://github.com/ant-design/ant-design/issues/39970
https://github.com/ant-design/ant-design/issues/39925

**Comment by MadCcc** [comment] 2023-01-04 02:34
Duplicate of https://github.com/ant-design/ant-design/issues/39925

**Comment by MadCcc** [comment] 2023-01-04 02:35
Merged into https://github.com/ant-design/ant-design/issues/39925

**Closed by MadCcc** 2023-01-04 02:34 UTC

**Comment by afc163** [comment] 2023-01-09 02:57
```diff
- const onTabClick = (key: string, event: MouseEvent) => {};
+ const onTabClick = (key: string, event: React.MouseEvent) => {};
```
