### ISSUE TITLE
Typescript Error implicit any types 3.0.0-alpha.19

### ISSUE THREAD

**Issue by DavidNorena** [ant-design/ant-design#8016] opened 2017-10-25 14:03 UTC
### Version
3.0.0-alpha.19

### Environment
browser version

### Reproduction link
[https://github.com/ant-design/ant-design/blob/antd-3.0/components/calendar/Header.tsx#L15](https://github.com/ant-design/ant-design/blob/antd-3.0/components/calendar/Header.tsx#L15)
[https://github.com/ant-design/ant-design/blob/antd-3.0/components/table/SelectionBox.tsx#L12](https://github.com/ant-design/ant-design/blob/antd-3.0/components/table/SelectionBox.tsx#L12)

### Steps to reproduce
In a project using Typescript set "strict" flag to true in tsconfig.json and try to build/compile the project.

### What is expected?
Compile the project without any issues, please set the respective return value types on the referenced scripts.

### What is actually happening?
When you try to build/compile the project gives the following errors:

```
1>    ERROR in [at-loader] ./node_modules/antd/lib/calendar/Header.d.ts:11:22
1>        TS7006: Parameter 'value' implicitly has an 'any' type.
1>
1>    ERROR in [at-loader] ./node_modules/antd/lib/table/SelectionBox.d.ts:10:16
1>        TS7006: Parameter 'e' implicitly has an 'any' type.

```

**Comment by afc163** [comment] 2017-10-25 14:41
Duplicate of #8011

**Closed by afc163** 2017-10-25 14:41 UTC
