### ISSUE TITLE
按钮的OnClick打开Modal的静态方法（如Modal.confirm...）,在Modal弹出的动画期间，可反复点击按钮，弹出多个Modal

### ISSUE THREAD

**Issue by huangyuan7** [ant-design/ant-design#46405] opened 2023-12-12 09:27 UTC
### Reproduction link

[https://ant-design.antgroup.com/components/modal-cn](https://ant-design.antgroup.com/components/modal-cn)

### Steps to reproduce

antd官网就能重现。Modal组件中的静态方法，快速点击按钮可弹出多个蒙层和对话框。

### What is expected?

快速点击按钮，也只能弹出一个Modal。

### What is actually happening?

快速点击按钮弹出了多个Modal。

| Environment | Info |
| --- | --- |
| antd | 5.12.2 |
| React | 18 |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment] 2023-12-12 10:10
Duplicate of #46129

**Closed by afc163** 2023-12-12 10:10 UTC
Labels: unconfirmed
