### ISSUE TITLE
form组件通过 onFieldsChange 和 fields把表单的数据存储到上层组件时，输入出现严重卡

### ISSUE THREAD

**Issue by jclegendary** [ant-design/ant-design#22632] opened 2020-03-26 08:08 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-lge66h?file=index.js](https://stackblitz.com/edit/react-lge66h?file=index.js)

### Steps to reproduce
快速输入表单

### What is expected?
平稳流畅

### What is actually happening?
卡顿

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | react16 |
| System | window |
| Browser | chrome |

**Comment by zombieJ** [comment] 2020-03-26 12:55
Duplicate of #21923

**Closed by zombieJ** 2020-03-26 12:55 UTC
