### ISSUE TITLE
When I use ant-design's RangePicker component, I set the showTime property to true and set it to disable the selection of today's date, but when I open the calendar panel, I don't select the day first, but select the hour, minute and second directly, the date is still automatically selected to today. The official documentation provides an example of "no date and time selection" can reproduce the problem.

### ISSUE THREAD

**Issue by zhoude0716** [ant-design/ant-design#29024] opened 2021-01-25 08:20 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/#components-date-picker-demo-disabled-date](https://ant.design/components/date-picker-cn/#components-date-picker-demo-disabled-date)

### Steps to reproduce
When I use ant-design's RangePicker component, I set the showTime property to true and set it to disable the selection of today's date, but when I open the calendar panel, I don't select the day first, but select the hour, minute and second directly, the date is still automatically selected to today. The official documentation provides an example of "no date and time selection" can reproduce the problem

### What is expected?
Calendar control won't let you select today when selecting hours, minutes and seconds after disabling today

### What is actually happening?
When using ant-design's RangePicker component, set the showTime property to true, and set it to disable the selection of today's date, the date will still be automatically selected to today after opening the calendar panel without selecting the day first, and directly selecting the hour, minute and second.

| Environment | Info |
|---|---|
| antd | 4.11.1 |
| React | React |
| System | win10 |
| Browser | chrome87 |

**Comment by xrkffgg** [comment] 2021-01-25 08:30
Duplicate of https://github.com/ant-design/ant-design/issues/29023

**Closed by xrkffgg** 2021-01-25 08:30 UTC
