### ISSUE TITLE
Table rowSelection `selections`  location is strange; Table的自定义选择框的下拉三角形位置奇怪 

### ISSUE THREAD

**Issue by NnnLillian** [ant-design/ant-design#29149] opened 2021-02-01 06:06 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zidingyixuanzexiang-antd4112-forked-eirdd?file=/index.js)

### Steps to reproduce
1. Table set `bordered`
2. Table set `rowSelection={selections: [Table.SELECTION_ALL,Table.SELECTION_NONE]}`

### What is expected?
i hope the “v" don't appear on the border. 我希望下拉小三角的图形不要叠在线上
[![yZJ954.png](https://s3.ax1x.com/2021/02/01/yZJ954.png)](https://imgchr.com/i/yZJ954)

### What is actually happening?
[![yZpdde.png](https://s3.ax1x.com/2021/02/01/yZpdde.png)](https://imgchr.com/i/yZpdde)

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 17.0.1 |
| System | windows |
| Browser | chrome 87.0.4280.88 |

**Comment by xrkffgg** [comment] 2021-02-01 06:10
Duplicate of https://github.com/ant-design/ant-design/issues/29083

**Closed** 2021-02-01 06:10 UTC
