### ISSUE TITLE
带有排序的固定列，水平滚动时会出现样式问题

### ISSUE THREAD

**Issue by lizhancheng** [ant-design/ant-design#39860] opened 2022-12-28 04:02 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gu-ding-lie-antd-5-1-1-forked-7o69rj)

### Steps to reproduce

右滚动后，鼠标悬浮在Age列

### What is expected?

样式正常显示

### What is actually happening?

能看见底部列头，导致重影
<img width="344" alt="image" src="https://user-images.githubusercontent.com/8544620/209755356-97a6c083-f493-4b6b-9a18-d0c4c95d400b.png">

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.2.0 |
| System | MacOS |
| Browser | chrome109 |

**Comment by afc163** [comment] 2022-12-28 04:59
Duplicate of https://github.com/ant-design/ant-design/issues/39006

**Closed** 2022-12-28 10:15 UTC
