### ISSUE TITLE
react 日期选择器 可否自定义渲染 通过按钮触发

### ISSUE THREAD

**Issue by lmr520** [ant-design/ant-design#25338] opened 2020-07-01 06:53 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
无法通过现有的api更好的去修改当前的组件的样式，需要自定义渲染，vue版本有这个功能，react版本是否支持

### What does the proposed API look like?
提供自定义渲染

**Comment by afc163** [comment] 2020-07-01 06:55
Duplicate of #18376

**Comment by afc163** [comment] 2020-07-01 06:55
Duplicate of #23276

**Closed by afc163** 2020-07-01 06:56 UTC
