### ISSUE TITLE
componentWillReceiveProps will be deprecated,Please update in time

### ISSUE THREAD

**Issue by wanliyunyan** [ant-design/ant-design#13581] opened 2018-12-12 06:51 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In order to avoid unnecessary errors

### What does the proposed API look like?
Use the new life cycle, e. g. getDerivedStateFromProps and getSnapshotBeforeUpdate

**Comment by afc163** [comment] 2018-12-12 09:19
Duplicate of #9792

**Closed by afc163** 2018-12-12 09:19 UTC
Labels: IssueHuntFest, Plan
