### ISSUE TITLE
TABLE组件中能否在列头上相关列增加展开收缩功能按钮？

### ISSUE THREAD

**Issue by zhangqhzz** [ant-design/ant-design#33435] opened 2021-12-28 02:22 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当有收缩展开行功能时，有时需要全部展开/收缩的需求

### What does the proposed API look like?
可自定义事件

**Comment by afc163** [comment] 2021-12-28 02:53
Duplicate of #33090

**Closed by afc163** 2021-12-28 02:53 UTC

**Comment by afc163** [comment] 2022-07-13 02:06
trace #36490
