### ISSUE TITLE
Cascader need multi-select

### ISSUE THREAD

**Issue by AriwFeng** [ant-design/ant-design#26745] opened 2020-09-15 02:53 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
some scene need multi select in Cascader

### What does the proposed API look like?
multiSelect = {true}

**Comment by afc163** [comment] 2020-09-15 02:56
Duplicate of #23410

**Closed by afc163** 2020-09-15 02:56 UTC
