### ISSUE TITLE
This issue is about Tabs,  Can you provide an attribute to fix a tab when there are so many tabPane in Tabs?

### ISSUE THREAD

**Issue by JadeLiuYC** [ant-design/ant-design#29173] opened 2021-02-02 03:25 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When the number is large, the front part will be hidden. Now we need a fixed display.

### What does the proposed API look like?
provide a fixed property in Tabs.TabPane, we can see it all the time.

**Comment by yoyo837** [comment] 2021-02-02 03:36
可以先从tabs的容器上下手解决眼前。

**Comment by afc163** [comment] 2021-02-02 03:37
Duplicate of #18782

**Closed by afc163** 2021-02-02 03:37 UTC
