### ISSUE TITLE
Virtual List rowselection

### ISSUE THREAD

**Issue by Rajgupta7080** [ant-design/ant-design#41968] opened 2023-04-24 07:51 UTC
### What problem does this feature solve?

When I use virtual list. I am not able to use row selection. Please add it 

### What does the proposed API look like?

rowselection should we work in virtual table

**Comment by afc163** [comment] 2023-04-24 08:07
Duplicate of https://github.com/ant-design/ant-design/issues/20339

**Closed by afc163** 2023-04-24 08:07 UTC
Labels: unconfirmed
