### ISSUE TITLE
Tree component is not expanding/collapsing with node 18 in strict mode

### ISSUE THREAD

**Issue by vytska** [ant-design/ant-design#35768] opened 2022-05-27 06:37 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zen-frost-fvyofn)

### Steps to reproduce

Use tree component with react 18 in strict mode

### What is expected?

Tree expands and collapses on click

### What is actually happening?

Tree remains static

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 18.1.0 |
| System | macOS 12.3.1 |
| Browser | Chrome 101.0.4951.64 |

**Comment by zombieJ** [comment] 2022-05-27 06:48
Duplicate of #35400

**Closed by zombieJ** 2022-05-27 06:48 UTC
