### ISSUE TITLE
babel-plugin-import not working when running `npm test`

### ISSUE THREAD

**Issue by Stupidism** [ant-design/ant-design#10391] opened 2018-05-07 04:25 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.0

### Environment
mac os, chrome

### Reproduction link
[https://github.com/Stupidism/cra-rewired-starter/commit/4c6a13730a89e58b2680274628422e3c9fee9f78](https://github.com/Stupidism/cra-rewired-starter/commit/4c6a13730a89e58b2680274628422e3c9fee9f78)

### Steps to reproduce
npm i && npm test

### What is expected?
test passes without warning

### What is actually happening?
warning occurred:
```
  console.warn node_modules/antd/lib/index.js:499
    You are using a whole package of antd, please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.
```
---
奇怪的是: 
npm
 start 和 npm run build && npm run analyze 都显示没有 import 整个 antd

**Comment by yesmeck** [comment] 2018-05-07 04:33
Duplicate of #10363

**Closed by yesmeck** 2018-05-07 04:33 UTC
