### ISSUE TITLE
Menu mode="inline" or mode="horizontal"  throws useLayoutEffect warning in Next.js

### ISSUE THREAD

**Issue by sb-lee** [ant-design/ant-design#31345] opened 2021-07-11 08:47 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/30396](https://github.com/ant-design/ant-design/issues/30396)

### Steps to reproduce
1. First,  set like https://github.com/ant-design/ant-design/issues/30396
2. Add an antd menu component.
```
<Menu mode="inline">
        <Menu.Item key="a">a</Menu.Item>
        <Menu.Item key="b">b</Menu.Item>
</Menu>
``` 

### What is expected?
No exceptions or warnings are expected.

### What is actually happening?
Same warning as  https://github.com/ant-design/ant-design/issues/30396
```javascript
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at Overflow (/Users/user/naver/workspace/pos-front/node_modules/rc-overflow/lib/Overflow.js:42:32)
    at InheritableContextProvider (/Users/user/naver/workspace/pos-front/node_modules/rc-menu/lib/context/MenuContext.js:39:23)
    at Menu (/Users/user/naver/workspace/pos-front/node_modules/rc-menu/lib/Menu.js:76:32)
    at InternalMenu (/Users/user/naver/workspace/pos-front/node_modules/antd/lib/menu/index.js:73:37)
    at Menu (/Users/user/naver/workspace/pos-front/node_modules/antd/lib/menu/index.js:166:37)
    at header
    at Basic (/Users/user/naver/workspace/pos-front/node_modules/antd/lib/layout/layout.js:78:25)
    at Header (/Users/user/naver/workspace/pos-front/node_modules/antd/lib/layout/layout.js:61:37)
    at section
    at BasicLayout (/Users/user/naver/workspace/pos-front/node_modules/antd/lib/layout/layout.js:93:34)
    at Layout (/Users/user/naver/workspace/pos-front/node_modules/antd/lib/layout/layout.js:61:37)
    at MordernaLayout (webpack-internal:///./component/layout/MordernaLayout.tsx:33:3)
    at MyApp (webpack-internal:///./pages/_app.tsx:27:3)
    at AppContainer (/Users/user/naver/workspace/pos-front/node_modules/next/dist/next-server/server/render.js:27:952)
```

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React |  lastest |
| System | mac os lastest |
| Browser | chrome,  |

**Comment by afc163** [comment] 2021-07-12 03:01
Duplicate of #30396

**Closed by afc163** 2021-07-12 03:01 UTC
