### ISSUE TITLE
The ant-tabs-dropdown of Tabs rendered on the body by default, i am eager to support rendering on custom nodes like other floating layers, such as Menu, Tooltip, etc.

### ISSUE THREAD

**Issue by JingJiang0628** [ant-design/ant-design#31826] opened 2021-08-18 02:03 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
So that different modules on the same page can define different styles

### What does the proposed API look like?
May provide API like getPopupContainer, or custom className of ant-tabs-dropdown

**Comment by afc163** [comment] 2021-08-18 03:18
Duplicate of #25844

**Closed by afc163** 2021-08-18 03:18 UTC
