### ISSUE TITLE
when i switch language from en to ch? Modal.confirm has some problem.

### ISSUE THREAD

**Issue by yanguoyu** [ant-design/ant-design#12769] opened 2018-10-22 11:59 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
mac osx 10.13 chrome 版本 69.0.3497.100（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l5om13w35q)

### Steps to reproduce
when i click the exchange button to exchange language from en to ch. then i click other button to show a modal

### What is expected?
i hope the modal's onOk text and onCancel text is ch.

### What is actually happening?
the modal's onOk text and onCancel text is en.

**Comment by afc163** [comment] 2018-10-22 13:10
Duplicate of #12768

**Closed by afc163** 2018-10-22 13:10 UTC

**Comment by ztplz** [comment] 2018-10-22 13:13
Duplicate to #12768
