### ISSUE TITLE
Table reponsive array prop should allow several widths

### ISSUE THREAD

**Issue by sparrowek** [ant-design/ant-design#48271] opened 2024-04-04 12:12 UTC
### What problem does this feature solve?

I want to switch between showing two column based on width

### What does the proposed API look like?

cols = [
{
title: '1'
responsive: ['xs', 'md']
},
{
title: '2'
responsive: ['lg', 'xl']
},

column 1 will be visible at lower widths and column 2 at higher widths - currently specifying responsive: ['xs', 'md'] gives the same result as ['xs'] - when the width is bigger column is still visible. I wonder why the prop accepts array?

**Comment by MadCcc** [comment] 2024-04-10 08:44
Duplicate of https://github.com/ant-design/ant-design/issues/47974

**Closed by MadCcc** 2024-04-10 08:44 UTC
Labels: unconfirmed
