### ISSUE TITLE
select组件如果下拉项元素是8个会有滚动条，并且拖动滚动条系统会崩溃

### ISSUE THREAD

**Issue by wencyL** [ant-design/ant-design#27460] opened 2020-10-30 06:14 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
1、进入antd官网；2、进入select选择器；3、找到dropdownRender使用示例；4、原本有两个下拉项，现在新增6个下拉项，光标离开，重新落入光标，出现滚动条，拖动滚动条

### What is expected?
8个下拉项的时候不要滚动条

### What is actually happening?
select组件8个下拉选项有滚动条，且拖动滚动条系统崩溃

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.13.0 |
| System | Windows |
| Browser | chrome |

**Comment by yoyo837** [comment] 2020-10-30 06:16
Duplicate of #27282

**Closed by yoyo837** 2020-10-30 06:16 UTC
