### ISSUE TITLE
Dropdown 和Modal Button组合，打开弹框，有其他时间较长处理，dropdown气泡会重新唤起

### ISSUE THREAD

**Issue by lemonlhy** [ant-design/ant-design#44197] opened 2023-08-14 02:38 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-8-3-forked-cjm8lc)

### Steps to reproduce

1.hover 10 出现气泡，打开弹框，气泡消失
2.hover 10000 出现气泡，打开弹框

### What is expected?

气泡也消失，也不会重新唤起

### What is actually happening?

气泡消失后又重新唤起

| Environment | Info |
| --- | --- |
| antd | 5.8.3 |
| React | 18.0.0 |
| System | win10 |
| Browser | 谷歌 |

**Comment by lemonlhy** [comment] 2023-08-14 02:38
![image](https://github.com/ant-design/ant-design/assets/24663035/a0bb7232-a052-46dc-a394-3e2bc693d11f)

**Comment by Wxh16144** [comment] 2023-08-14 02:44
和 #43860 重复了， 这个问题还得等大佬排一下，看起来比较难解决。

**Comment by MadCcc** [comment] 2023-08-14 02:51
Duplicate of https://github.com/ant-design/ant-design/issues/43860

**Closed** 2023-08-14 08:32 UTC
Labels: unconfirmed
