### ISSUE TITLE
当组件外层容器加上transform: scale(0.8)比例显示时，表格自带分页页码下拉框会错位，其他单独的下拉框组件下拉正常

### ISSUE THREAD

**Issue by AutumnFrost** [ant-design/ant-design#32458] opened 2021-10-13 07:32 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/pagination-cn/](https://ant.design/components/pagination-cn/)

### Steps to reproduce
就是标题写的那样
![2f5df8a497af1a843b7119c42d220f2](https://user-images.githubusercontent.com/54533209/137087502-eaa5c8f2-a3dd-42ab-8577-8b85ef66bc64.png)

### What is expected?
期望有无最简单的解决办法，或者后续组件会更新修复，不想自己在代码里面去改样式覆盖

### What is actually happening?
暂无

| Environment | Info |
|---|---|
| antd | 4.12.0 |
| React | 16.14.0 |
| System | win |
| Browser | chorem版本 94.0.4606.81（正式版本） （64 位） |

**Comment by afc163** [comment] 2021-10-13 07:39
Duplicate of #26681

**Closed by afc163** 2021-10-13 07:39 UTC
