### ISSUE TITLE
Select with mode="multiple" is very slow even with a few hundereds of items

### ISSUE THREAD

**Issue by heroandtn3** [ant-design/ant-design#19328] opened 2019-10-21 08:42 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xenodochial-jepsen-oo9ww)

### Steps to reproduce
- Click on the selection input
- Choose some options

### What is expected?
- Click on the selection input => the dropdown shows up quickly
- Choose some options => the selected options displayed in the list quickly

### What is actually happening?
- Click on the selection input => there is a delay before the dropdown shows up
- Choose some options => there is a delay before the selected options displayed in the list 

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | Latest |
| System | Linux |
| Browser | Chrome Version 77.0.3865.90 (Official Build) (64-bit) |

**Comment by yoyo837** [comment] 2019-10-21 10:49
Duplicate of #10431

**Closed by yoyo837** 2019-10-21 10:49 UTC

**Comment by rashmimh** [comment] 2019-10-25 06:50
Facing the same issue, values are reflecting very slowly but in my case, hundreds of data are not there, it's hardly 20-30 but the thing is I am trying to implement select/deselect all toggle.

**Comment by heroandtn3** [comment] 2019-10-26 14:24
Problem solved by switching to use react-select-virtualized.

**Comment by mzulfanw** [comment] 2024-06-12 15:18
@rashmimh i have problem same with your , but currently it was fixed you can fixed it by used Set
