### ISSUE TITLE
使用tsx使用Button组件老是提示错误

### ISSUE THREAD

**Issue by liu2080019** [ant-design/ant-design#15973] opened 2019-04-09 07:57 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://new-issue.ant.design/没有链接](https://new-issue.ant.design/没有链接)

### Steps to reproduce
就是很普通的render，返回一个<Button>提交</Button>     

### What is expected?
不报错

### What is actually happening?
 ts检测报错：Type '{ children: string; }' is missing the following properties from type 'Pick<Pick<(Readonly<AnchorButtonProps> & Readonly<{ children?: ReactNode; }>) | (Readonly<NativeButtonProps> & Readonly<{ children?: ReactNode; }>), "children" | "defaultChecked" | ... 257 more ... | "block"> & Pick<...> & Pick<...>, "children" | ... 256 more ... | "prefixCls">': defaultChecked, defaultValue, suppressContentEditableWarning, suppressHydrationWarning, and 253 more.ts(2740)

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.3.2 |
| System | macOS |
| Browser | chrome |

**Comment by zombieJ** [comment] 2019-04-09 08:11
Duplicate of #15930

**Closed by zombieJ** 2019-04-09 08:11 UTC
