### ISSUE TITLE
Select component doesn't have event object but just value and option for onChange handler

### ISSUE THREAD

**Issue by kushalmahajan** [ant-design/ant-design#14050] opened 2019-01-02 11:13 UTC
- [ x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
Use select inside Collapse's Panel  header prop. How ??  I used header as React Node and rendered select inside of it. 

### What is expected?
event object is required. Why? onChange of select also closes collapse, so wanted to stop the propagation 🥇 

### What is actually happening?
Select component onChange implementation is not passing event back

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.7.2 alpha |
| System | MacOs High Sierra |
| Browser | Chrome 71.0.3578.98 |

---

**Comment by afc163** [comment] 2019-01-03 02:31
https://codesandbox.io/s/626vkrv4rk

Duplicate of #2738

**Closed by afc163** 2019-01-03 02:31 UTC
