### ISSUE TITLE
Select Component should provide options prop,

### ISSUE THREAD

**Issue by littleone2018** [ant-design/ant-design#16324] opened 2019-04-26 02:08 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
otherwise，we need to use map each time; 
this does not lose flexibility, if we need some custom render, wo can use Option Component then.

### What does the proposed API look like?
<Select :options={[title: 'one', value: 1 ]} />

**Comment by ztplz** [comment] 2019-04-26 02:35
IMO this is an unnecessary feature, just because you don't want to use `map`? BTW you can generate `options` in a variety of ways.

**Comment by afc163** [comment] 2019-04-26 02:50
Duplicate of #15653

**Closed by afc163** 2019-04-26 02:50 UTC
