### ISSUE TITLE
Cascader  使用loadData 实现动态加载选项。二级菜单如果没有数据是否能隐藏二级菜单容器？

### ISSUE THREAD

**Issue by VanLee1212** [ant-design/ant-design#33112] opened 2021-12-01 08:56 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Cascader  使用loadData 实现动态加载选项。二级菜单如果没有数据时，隐藏二级菜单容器

### What does the proposed API look like?
可配置，或者默认
![image](https://user-images.githubusercontent.com/28707076/144202943-54a84f84-5b7e-4b7e-a887-8dc40f9558b8.png)

**Comment by afc163** [comment] 2021-12-01 09:08
Duplicate of #28774

**Closed by afc163** 2021-12-01 09:08 UTC

**Comment by VanLee1212** [comment] 2021-12-02 10:18
没看到具体怎么解决呀？
