### ISSUE TITLE
Year Picker

### ISSUE THREAD

**Issue by thamjieying** [ant-design/ant-design#9702] opened 2018-03-16 05:37 UTC
### What problem does this feature solve?
Select one year

### What does the proposed API look like?
A selector to select one whole year

**Comment by afc163** [comment] 2018-03-16 05:40
Duplicate of #4524

**Closed by afc163** 2018-03-16 05:40 UTC

**Comment by cwtuan** [comment] 2018-08-19 08:07
Do need a Year Picker !

**Comment by cwtuan** [comment] 2018-08-19 08:11
@afc163 

 #4524 提到用select代替，但是如果在年份不确定的情况下，不可能把所有年份的列出来在Select里。还是需要有YearPicker
