### ISSUE TITLE
v4文档中DatePicker CodeSandbox示例异常

### ISSUE THREAD

**Issue by LeoooY** [ant-design/ant-design#27744] opened 2020-11-13 04:59 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8ufwc)

### Steps to reproduce
点击文档中DatePicker CodeSandbox示例

### What is expected?
示例正常加载

### What is actually happening?
ModuleNotFoundError，示例无法加载

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 16.14 |
| System | ubuntu20.04 |
| Browser | Chrome |

![Screenshot from 2020-11-13 12-52-52](https://user-images.githubusercontent.com/38848201/99030429-f1bafc80-25af-11eb-8ce8-8e68cd6f382e.png)

**Comment by afc163** [comment] 2020-11-13 05:42
Duplicate of #27665

**Closed by afc163** 2020-11-13 05:42 UTC
