### ISSUE TITLE
upload 组件（照片墙）上传多张图片，图片自适应浏览器共有两行，图片超出一行之后，选择图片的选择框会在第三行出现

### ISSUE THREAD

**Issue by jxlstrive** [ant-design/ant-design#16165] opened 2019-04-18 09:56 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?&editable=true&editors=001](https://codepen.io/pen/?&editable=true&editors=001)

### Steps to reproduce
Ant Design Demo（upload 照片墙，尝试上传20张，问题就出现了）

const { Upload, Icon, Modal } = antd;

class PicturesWall extends React.Component {
  state = {
    previewVisible: false,
    previewImage: '',
    fileList: [{
      uid: '-1',
      name: 'xxx.png',
      status: 'done',
      url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
    }],
  };

  handleCancel = () => this.setState({ previewVisible: false })

  handlePreview = (file) => {
    this.setState({
      previewImage: file.url || file.thumbUrl,
      previewVisible: true,
    });
  }

  handleChange = ({ fileList }) => this.setState({ fileList })

  render() {
    const { previewVisible, previewImage, fileList } = this.state;
    const uploadButton = (
      <div>
        <Icon type="plus" />
        <div className="ant-upload-text">Upload</div>
      </div>
    );
    return (
      <div className="clearfix">
        <Upload
          action="//jsonplaceholder.typicode.com/posts/"
          listType="picture-card"
          fileList={fileList}
          onPreview={this.handlePreview}
          onChange={this.handleChange}
        >
          {fileList.length >= 20 ? null : uploadButton}
        </Upload>
        <Modal visible={previewVisible} footer={null} onCancel={this.handleCancel}>
          <img alt="example" style={{ width: '100%' }} src={previewImage} />
        </Modal>
      </div>
    );
  }
}

ReactDOM.render(<PicturesWall />, mountNode);

### What is expected?
期望upload的选择框跟随上一张图片，而不是超出一行之后就换行显示选择框了

### What is actually happening?
照片墙，上传多张图片。如该浏览器第一行图片只能放10张图片，但是实际上传了11张图片。目前的效果就是第一行10张图片，第二行1张图片，而选择框出现在了第三行

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | react |
| System | mac 10.14.4 (18E226) |
| Browser | chrome 版本 73.0.3683.86（正式版本） |

**Comment by afc163** [comment] 2019-04-18 14:43
Duplicate of #16045

**Closed by afc163** 2019-04-18 14:43 UTC
