### ISSUE TITLE
Select dropdown disappears when used inside shadow dom

### ISSUE THREAD

**Issue by sjsakib** [ant-design/ant-design#28766] opened 2021-01-07 17:36 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/immutable-water-oiox2?file=/index.js)

### Steps to reproduce
Click the select element 

### What is expected?
a drop down should appear with options, and should stay there until any click 

### What is actually happening?
dropdown disappears right after appearing

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.1 |
| System | ubuntu 20.10 |
| Browser | chrome 87 |

**Comment by afc163** [comment] 2021-01-08 02:50
Duplicate of #27250

**Closed by afc163** 2021-01-08 02:50 UTC
