### ISSUE TITLE
select控件mode为tags时，当输入内容重复时，按下回车可否保留一个输入放在最后一个位置

### ISSUE THREAD

**Issue by T-Inphic** [ant-design/ant-design#26213] opened 2020-08-14 09:18 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决输入重复内容，按下回车时取消选中状态

### What does the proposed API look like?
<Select mode='tags' repeatSaveOne={true}></Select> repeatSaveOne为true，输入重复内容，保存一个

**Comment by afc163** [comment] 2020-08-14 09:35
Duplicate of https://github.com/ant-design/ant-design/issues/20198#issuecomment-581402405

**Closed by afc163** 2020-08-14 09:35 UTC
