### ISSUE TITLE
antd@5.17.0中table的滚动条样式无法用全局样式覆盖

### ISSUE THREAD

**Issue by xss112633** [ant-design/ant-design#48801] opened 2024-05-07 07:13 UTC
### Reproduction link

[https://segmentfault.com/q/1010000044860439](https://segmentfault.com/q/1010000044860439)

### Steps to reproduce

无

### What is expected?

table滚动条样式可以被全局样式给覆盖

### What is actually happening?

table滚动条样式无法自定义

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | 18.2.0 |
| System | Windows 11 家庭中文版 |
| Browser | chrome 122.0.6261.96 |

---
umijs版本@4.1.1

**Comment by Wxh16144** [comment] 2024-05-07 07:19
貌似有人提过类似的问题，看看这个 https://github.com/ant-design/ant-design/issues/47592#issuecomment-1972831827  解决方案能不能满足需求

**Comment by MadCcc** [comment] 2024-05-08 08:49
duplicate of https://github.com/ant-design/ant-design/issues/47592#issuecomment-1972831827

**Closed by MadCcc** 2024-05-08 08:49 UTC
Labels: unconfirmed
