### ISSUE TITLE
Cascader级联选择 开放多选功能

### ISSUE THREAD

**Issue by xsphalo** [ant-design/ant-design#23611] opened 2020-04-26 07:08 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当对企业或工厂生产地址，或多项目标条件时可以选择多个地区，或者多个目标选项

### What does the proposed API look like?
增加类似Select一样的mode功能，比如： mode='multiple' | 'tags'

**Comment by afc163** [comment] 2020-04-26 07:12
Duplicate of #23410

**Closed by afc163** 2020-04-26 07:12 UTC
