### ISSUE TITLE
Ability to add title or aria-label attribute to timepicker and other compoents

### ISSUE THREAD

**Issue by AdamFreemer** [ant-design/ant-design#13336] opened 2018-11-28 14:49 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Accessibility (508) compliance. We are looking to expand our use of antd components, but have an accessibility compliance that requires page elements to have unique titles and/or aria-labels on the html element itself. 

### What does the proposed API look like?
title    -       item title    -     string   -   "item-title"

**Comment by afc163** [comment] 2018-11-28 16:38
Duplicate of #4102

**Closed by afc163** 2018-11-28 16:38 UTC
