### ISSUE TITLE
Typography.Paragraph expand issues

### ISSUE THREAD

**Issue by tienviplaanh** [ant-design/ant-design#50727] opened 2024-09-05 14:34 UTC
### Reproduction link

[[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/run?file=demo.tsx)](https://ant.design/components/typography#typography-demo-suffix)

### Steps to reproduce

It has an issue where, on the first render, it displays the entire text before collapsing it, which looks very irritating." Look at this demo on the homepage of Antd, if you reload the page, you'll see the text flicker momentarily. 

### What is expected?

I expected the page not to render a full paragraph upon initial load.

### What is actually happening?

On the initial render, the text would collapse, displaying the entire text before collapsing, which was very irritating.

| Environment | Info |
| --- | --- |
| antd | 5.20.5 |
| React | nextJS |
| System | Window |
| Browser | chorme |

**Comment by afc163** [comment] 2024-09-06 02:05
Duplicate of https://github.com/ant-design/ant-design/issues/50728

**Closed by afc163** 2024-09-06 02:05 UTC
Labels: unconfirmed
