### ISSUE TITLE
Can't control the input search value of Transfer Component

### ISSUE THREAD

**Issue by Leoguedesm1** [ant-design/ant-design#34455] opened 2022-03-11 15:10 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Use the transfer component in a Modal Component and make a search, when you close and reopen the modal the input search value persists

### What does the proposed API look like?
Create a prop in Transfer Component that you can control the search value

**Comment by afc163** [comment] 2022-03-12 05:37
Duplicate of #17240

**Closed by afc163** 2022-03-12 05:37 UTC
