### ISSUE TITLE
No need to check url is an image url or not.

### ISSUE THREAD

**Issue by elantion** [ant-design/ant-design#9880] opened 2018-03-30 08:52 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
chrome latest

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/upload/UploadList.tsx](https://github.com/ant-design/ant-design/blob/master/components/upload/UploadList.tsx)

### Steps to reproduce
create a normal 'picture-card' type uploader

### What is expected?
show all thumbnail images without checking image url

### What is actually happening?
only show base64 or url with image extension images.

---
My server API return uploaded image url without image extension and antd uploader won't show the thumbnail images.
For example: http://image.res.meizu.com/image/content/d223d25e32fb343ea2b050a2243a55e4/original
So I check the source code and I found code at 'ant-design/components/upload/UploadList.tsx line 84-91' has a image url checking function. Personally, I don't think it is necessary because depend a file whether an image is http content-type header not the extension. So I suggest remove the feature or add a props argument to control it.

Thanks, good day.

**Comment by elantion** [comment] 2018-03-30 09:03
I found a relative issue: https://github.com/ant-design/ant-design/issues/9835
I think props.listType has already told this is an images type uploader  (picture-card), so I suggest do not check image url in this type and no need to add more props argument.

**Comment by dengfuping** [comment] 2018-03-30 10:15
Related of PR #9621

**Comment by afc163** [comment] 2018-03-31 17:18
Duplicate of #9835

**Closed by afc163** 2018-03-31 17:18 UTC
Labels: Component: Upload
