### ISSUE TITLE
Table组件expandable下的table展开Icon在火狐浏览器上显示的不正确

### ISSUE THREAD

**Issue by SingedLL** [ant-design/ant-design#30408] opened 2021-05-06 06:32 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#expandable](https://ant.design/components/table-cn/#expandable)

### Steps to reproduce
在window下的Firefox浏览器上， Table的展开按钮不是“ “

### What is expected?
请保持各个浏览器显示一致

### What is actually happening?
在window下的Firefox浏览器上， Table的展开按钮不是“ “

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | react |
| System | window |
| Browser | Firefox |

**Comment by afc163** [comment] 2021-05-06 07:35
Duplicate of #29848

**Closed by afc163** 2021-05-06 07:35 UTC
