### ISSUE TITLE
Table 可编辑行 操作列固定后，保存的编辑内容，form中获取不到。操作列不固定一切正常

### ISSUE THREAD

**Issue by PinkRebbits** [ant-design/ant-design#12436] opened 2018-09-27 11:46 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
win10 最新版谷歌浏览器

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-edit-row](https://ant.design/components/table-cn/#components-table-demo-edit-row)

### Steps to reproduce
官网demo中设置可编辑行table的操作列为 fixed:'right', 点击 Edit 后 Save，form中的 row 将会为 {}

### What is expected?
操作列固定后能获取到表单数据

### What is actually happening?
操作列固定后未获取到表单数据

---
  save(form, key) {
    form.validateFields((error, row) => {
      if (error) {
        return;
      }
      const newData = [...this.state.data];
      const index = newData.findIndex(item => key === item.key);
      if (index > -1) {
        const item = newData[index];
        newData.splice(index, 1, {
          ...item,
          ...row,
        });
        this.setState({ data: newData, editingKey: '' });
      } else {
        newData.push(row);
        this.setState({ data: newData, editingKey: '' });
      }
    });
  }

**Comment by yesmeck** [comment] 2018-09-27 12:02
Duplicate of #11991

**Closed by yesmeck** 2018-09-27 12:02 UTC
