### ISSUE TITLE
input前缀过长样式重叠

### ISSUE THREAD

**Issue by chengzequn** [ant-design/ant-design#20278] opened 2019-12-16 09:07 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mpzks8.run.stackblitz.io](https://mpzks8.run.stackblitz.io)

### Steps to reproduce
1.写下面这样一个输入框 
<Input prefix="这是测试的前缀" />
2.在输入框中输入值

### What is expected?
希望前缀与输入值不重叠

### What is actually happening?
因为前缀过长，输入的值与前缀重叠

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 16.12.0 |
| System | window |
| Browser | 火狐 |

**Comment by afc163** [comment] 2019-12-16 09:24
目前的实现无法修复这个问题，需要你根据前缀宽度自定义 `padding-left`。

**Comment by afc163** [comment] 2019-12-16 09:26
Duplicate of #17811

**Closed by afc163** 2019-12-16 09:26 UTC
