### ISSUE TITLE
select为禁用状态，无法按住鼠标左键拖动选中

### ISSUE THREAD

**Issue by bihongbin3027** [ant-design/ant-design#30848] opened 2021-06-04 03:22 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://codesandbox.io/s/00qvf
select为禁用状态，无法按住鼠标左键拖动选中

### What does the proposed API look like?
select为禁用状态，希望拖动鼠标左键可以选中，选中后我就可以复制内容了

**Comment by xrkffgg** [comment] 2021-06-04 05:30
非禁用状态也没有拖动选中呀

**Comment by bihongbin3027** [comment] 2021-06-04 05:57
@xrkffgg 有时候想要复制内容去搜索，发现select选中不了，有点不方便

**Comment by afc163** [comment] 2021-06-04 06:35
Duplicate of #28989

**Closed by afc163** 2021-06-04 06:35 UTC
