### ISSUE TITLE
标签（tag）控件能否增加“去掉点击效果”的样式？

### ISSUE THREAD

**Issue by 7Charlotte** [ant-design/ant-design#15959] opened 2019-04-09 01:59 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我是交互设计师。我在某些场景使用tag标签时，仅需要静态样式，不需要鼠标经过和点击效果。

### What does the proposed API look like?
鼠标经过标签时，不需要变成“pointer”，维持“default”态即可。点击后无任何效果。

**Comment by afc163** [comment] 2019-04-09 02:37
Duplicate of #15114

**Closed by afc163** 2019-04-09 02:37 UTC
