### ISSUE TITLE
能否让 Text Ellipsis 上支持 Tooltip 功能

### ISSUE THREAD

**Issue by Overcase** [ant-design/ant-design#28329] opened 2020-12-11 10:43 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
文字溢出时隐藏，并使用 tooltip 展示内容

### What does the proposed API look like?
```jsx
<Text ellipsis={true} tooltip={true}> ant-design </Text>


<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by afc163** [comment] 2020-12-11 15:28
Duplicate of #25891

**Closed by afc163** 2020-12-11 15:28 UTC
