### ISSUE TITLE
add dragging to sort the images function to upload component

### ISSUE THREAD

**Issue by Liqiankun** [ant-design/ant-design#8406] opened 2017-12-01 10:20 UTC
### What problem does this feature solve?
Drag to sort images after uploading images

### What does the proposed API look like?
```
<Upload
    sort
    multiple
    action='/upload.do'
    listType='picture-card'
    onPreview={this.handlePreview}
 />
```

**Comment by yesmeck** [comment] 2017-12-01 10:21
Duplicate of #8387

**Closed by yesmeck** 2017-12-01 10:21 UTC
