### ISSUE TITLE
fix: antd V4 icon 不能够map 使用

### ISSUE THREAD

**Issue by crazyshakalaka** [ant-design/ant-design#29820] opened 2021-03-19 06:14 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/icon-cn/#%E5%9B%BE%E6%A0%87%E5%88%97%E8%A1%A8](https://ant.design/components/icon-cn/#%E5%9B%BE%E6%A0%87%E5%88%97%E8%A1%A8)

### Steps to reproduce
icon 不能直接循环使用

### What is expected?
antd 3 icon 可以循环使用

### What is actually happening?
不能循环使用报错

| Environment | Info |
|---|---|
| antd | 4.5.0 |
| React | react/next |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment] 2021-03-19 06:18
Duplicate of https://github.com/ant-design/ant-design/issues/20668

**Closed by afc163** 2021-03-19 06:18 UTC
