### ISSUE TITLE
Overriding custom component property

### ISSUE THREAD

**Issue by eduardodallmann** [ant-design/ant-design#28902] opened 2021-01-17 17:35 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd4102-forked-1do70?file=/index.js)

### Steps to reproduce
Try customize tab prop <ContainerTabPane {...props} tab="custom title">

### What is expected?
I expected to see custom title on the three tabs in this example

### What is actually happening?
It should be overriding the tab property

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | react ^16.14 |
| System | windows 10 |
| Browser | chrome |

---
https://stackoverflow.com/questions/65756292/overriding-custom-component-property

**Comment by afc163** [comment] 2021-01-18 01:25
Duplicate of #4853

**Closed by afc163** 2021-01-18 01:25 UTC
