### ISSUE TITLE
表格行列合并后，合并行的边框缺失

### ISSUE THREAD

**Issue by wanghui2021** [ant-design/ant-design#39728] opened 2022-12-22 05:26 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biao-ge-xing-lie-he-bing-antd-5-1-0-forked-nrcm2l)

### Steps to reproduce

无

### What is expected?

合并后存在边框

### What is actually happening?

合并后边框不存在

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | react@18.2.0 |
| System | macOS 13.1 |
| Browser | 108.0.5359.124 |

<img width="750" alt="image" src="https://user-images.githubusercontent.com/37385554/209063353-933add03-b83b-4fc3-985d-1287fe51cf94.png">

**Comment by afc163** [comment] 2022-12-22 06:06
Duplicate of https://github.com/ant-design/ant-design/issues/38724

**Closed by afc163** 2022-12-22 06:06 UTC
