### ISSUE TITLE
[Feature Request] Spin supports minDuration to avoid flickering caused by fast closing

### ISSUE THREAD

**Issue by condorheroblog** [ant-design/ant-design#51828] opened 2024-11-29 03:15 UTC
### What problem does this feature solve?

When requesting a backend interface, if the backend response time is very short, Spin will be opened and closed quickly, which is particularly obvious when motion is set to false.

Here is how spin behaves when motion is true or false:

https://stackblitz.com/edit/react-sczwsr?file=demo.tsx

set motion is true, maybe it looks good.

![motion is true 2024-11-29 at 10 41 05](https://github.com/user-attachments/assets/d51f92e2-6a75-472e-b22e-c053962bb58f)

set motion is false, I can't stand it.

![motion is false 2024-11-29 at 10 42 32](https://github.com/user-attachments/assets/10bb0d97-1e37-4284-bb99-ff2cf1bea6dc)

I found a related issue but it was marked inactive - https://github.com/ant-design/ant-design/issues/29568

### What does the proposed API look like?

<Spin minDuration={300} />

**Comment by afc163** [comment] 2024-11-29 03:19
Try `delay` prop.

**Comment by afc163** [comment] 2024-11-29 03:19
Duplicate of https://github.com/ant-design/ant-design/issues/29568

**Closed by afc163** 2024-11-29 03:19 UTC
Labels: unconfirmed

**Comment by condorheroblog** [comment] 2024-11-29 03:42
I have tried to use the delay parameter in my project.

---

Please consider the following scenario. I set the delay to 200, but the interface request takes 400 seconds. It seems that the above problem will still occur, although this situation may be rare.

Introducing minDuration seems to solve the above problem. What do you think?

**Comment by afc163** [comment] 2024-11-29 03:52
@condorheroblog Trace in https://github.com/ant-design/ant-design/issues/29568

**Comment by condorheroblog** [comment] 2024-11-29 03:53
Fine, Thank you and period. 👀
