### ISSUE TITLE
官网Breadcrumb组件的react router v6示例不显示

### ISSUE THREAD

**Issue by candy4290** [ant-design/ant-design#40213] opened 2023-01-13 06:29 UTC
### Reproduction link

[https://ant.design/components/breadcrumb-cn#components-breadcrumb-demo-react-router](https://ant.design/components/breadcrumb-cn#components-breadcrumb-demo-react-router)

### Steps to reproduce

打开上面的官网链接

### What is expected?

正常显示

### What is actually happening?

不显示

| Environment | Info |
| --- | --- |
| antd | 5.1.4 |
| React | 18.2.0 |
| System | Windows11 |
| Browser | chrome 108.0.5359.125 |

---
codesandbox中可以正常显示：https://codesandbox.io/s/68vend?file=/package.json

**Comment by MadCcc** [comment] 2023-01-13 06:31
Duplicate of https://github.com/ant-design/ant-design/issues/39674

**Closed by MadCcc** 2023-01-13 06:31 UTC
Labels: unconfirmed
