### ISSUE TITLE
3.9后打包字体太大

### ISSUE THREAD

**Issue by apollo7733** [ant-design/ant-design#13599] opened 2018-12-13 00:58 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
查了下以前的issue,这个问题提到过2会，不过还是再次提问下，为啥不可以用类似react-icons 3.xx的.mjs文件，虽然之前讨论里面提到了，有可能后台配置，动态加载icon,不过大多时候都是简单的图标需求，是在编辑阶段就能够感知的

### What does the proposed API look like?
采用类似react-icons 3.xx .mjs文件之类的来减少打包文件大小

**Comment by afc163** [comment] 2018-12-13 01:37
Duplicate of #12011

**Closed by afc163** 2018-12-13 01:37 UTC
Labels: Duplicate, IssueHuntFest
