### ISSUE TITLE
table自定义筛选filterDropdown问题

### ISSUE THREAD

**Issue by SSW-imp** [ant-design/ant-design#28503] opened 2020-12-23 07:20 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zidingyishaixuancaidan-antd494-forked-zd8b6?file=/index.js:1320-1327)

### Steps to reproduce
自定义筛选触发 confirm的时候 在table的onChange里拿不到filter的值

### What is expected?
期望在table的change里拿到对应filter的值 去调取接口

### What is actually happening?
实际结果filter里的值不管输入什么都是[ ]

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16 |
| System | windows |
| Browser | chrome |

**Comment by urrri** [comment] 2020-12-23 17:31
Starting version 4.9.3 onChange doesn't receive values for custom filters.

I think it should be related to https://github.com/ant-design/ant-design/pull/28220

**Comment by SSW-imp** [comment] 2020-12-24 01:22
> Starting version 4.9.3 onChange doesn't receive values for custom filters.
> 
> I think it should be related to #28220

Where will the value of the custom filter be stored? Can you only save the value in your own state and then manually control the filterdropdownvisible

**Comment by urrri** [comment] 2020-12-24 15:22
> > Starting version 4.9.3 onChange doesn't receive values for custom filters.
> > I think it should be related to #28220
> 
> Where will the value of the custom filter be stored? Can you only save the value in your own state and then manually control the filterdropdownvisible

Custom state was always saved internally in table and exposed ouside via onChange. It also can be overriden by definition of values on column definition. So there was whole cycle of controlled state. It was broken by the version 4.9.3, when onChange stopped receving correct data. Interesting, that if you dont use controlled state or server side processing it works fine on internal state

**Comment by SSW-imp** [comment] 2020-12-28 02:29
> > > Starting version 4.9.3 onChange doesn't receive values for custom filters.
> > > I think it should be related to #28220
> > 
> > 
> > Where will the value of the custom filter be stored? Can you only save the value in your own state and then manually control the filterdropdownvisible
> 
> Custom state was always saved internally in table and exposed ouside via onChange. It also can be overriden by definition of values on column definition. So there was whole cycle of controlled state. It was broken by the version 4.9.3, when onChange stopped receving correct data. Interesting, that if you dont use controlled state or server side processing it works fine on internal state

Will this be repaired in the future, or is it all like this

**Comment by urrri** [comment] 2020-12-28 02:38
> Will this be repaired in the future, or is it all like this

Good question to developers of Ant Design, but it looks only bot reads bug reports here.

**Comment by urrri** [comment] 2020-12-29 06:43
@afc163 
I think #28541 is not related to the issue. It fixes opposite problem brought with version 4.0.
Current issue talks about *missing **existing** custom filter **data*** in onChange 
but that fix talks about *empty array instead of null, when data **not exists***.

**Comment by Veveue** [comment] 2020-12-29 08:18
+1

**Comment by afc163** [comment] 2020-12-29 15:37
Duplicate of #28603

**Closed by afc163** 2020-12-29 15:37 UTC
Labels: help wanted
