### ISSUE TITLE
DatePicker hopes to provide quarterly options

### ISSUE THREAD

**Issue by ldd27** [ant-design/ant-design#20620] opened 2020-01-03 02:56 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
DatePicker hopes to provide quarterly options

### What does the proposed API look like?
DatePicker hopes to provide quarterly options

**Comment by afc163** [comment] 2020-01-03 02:58
Duplicate of #20150

**Closed by afc163** 2020-01-03 02:58 UTC
