### ISSUE TITLE
React 18下，使用 文件上传组件，删除图片时，页面闪烁

### ISSUE THREAD

**Issue by H246802** [ant-design/ant-design#36547] opened 2022-07-15 09:35 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-18xia-shi-yong-wen-jian-shang-chuan-zu-jian-shan-chu-tu-pian-shi-ye-mian-shan-shuo-g7unmc?file=/package.json)

### Steps to reproduce

点击删除图片。

### What is expected?

图片删除时上传区域不闪烁

### What is actually happening?

删除时上传区域闪烁

| Environment | Info |
| --- | --- |
| antd | 4.21.6 |
| React | 18.2.0 |
| System | macOS Monterey |
| Browser | 版本 103.0.5060.114（正式版本） (arm64) |

**Comment by afc163** [comment] 2022-07-15 14:05
Duplicate of #35390

**Closed by afc163** 2022-07-15 14:05 UTC
Labels: React 18
