### ISSUE TITLE
Upload CustomRequest OnSuccess Requires 2nd argument of xml when using typescript.

### ISSUE THREAD

**Issue by Rocinante89** [ant-design/ant-design#28680] opened 2021-01-04 11:56 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
1. Create upload component with custom request.
2. Type file as RcFile
3. notice onSuccess(file) causes error

### What is expected?
up until this version, useing the customRequest prop on the upload component allowed us to use onSuccess(file) or onSuccess({}, file). As onSuccess took a second argument of RcFile. This has now changed to an xmlHttpRequest and so is breaking our builds. The documentation around customRequest does not seem to have been updated to show this change. We would like to be able to pass the file as is shown in all the documentation surrounding the use of customRequest onSuccess method.

### What is actually happening?
TS is erroring when you use onSuccess?.(file) or onSuccess.({}, file) if it is typed as an RcFile.

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | latest |
| System | Win 10 |
| Browser | Chromium |

**Comment by Rocinante89** [comment] 2021-01-04 11:59
I think it's a typing error maybe. The [upload library](https://github.com/react-component/upload) says onSuccess should accept 3 args: 
![image](https://user-images.githubusercontent.com/8224386/103533042-4ed28080-4e84-11eb-8f28-bc30549ab4fc.png)

**Comment by zombieJ** [comment] 2021-01-11 10:00
> I think it's a typing error maybe. The [upload library](https://github.com/react-component/upload) says onSuccess should accept 3 args:
> ![image](https://user-images.githubusercontent.com/8224386/103533042-4ed28080-4e84-11eb-8f28-bc30549ab4fc.png)

It's `onSuccess` define. Not `customRequest` define: https://github.com/react-component/upload#customrequest


Duplicate of #28744

**Closed by zombieJ** 2021-01-11 10:00 UTC
