### ISSUE TITLE
antd 5.0 Virtual Table Demo support more props Eg:(render,..etc)

### ISSUE THREAD

**Issue by hamzamongam** [ant-design/ant-design#40078] opened 2023-01-07 09:35 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/virtual-list-antd-5-1-2-forked-9fx675?file=/demo.tsx)

### Steps to reproduce

..

### What is expected?

Need to render props

### What is actually happening?

..

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18 |
| System | Linux |
| Browser | Chrome |

**Comment by afc163** [comment] 2023-01-08 06:53
Duplicate of #20339

**Closed by afc163** 2023-01-08 06:53 UTC
