### ISSUE TITLE
RadioButtons in RadioGroup in FormItem do not select when clicked

### ISSUE THREAD

**Issue by dtzhao** [ant-design/ant-design#4638] opened 2017-01-18 07:22 UTC
#### Environment(required)

- antd version: latest
- OS and its version: macOS Sierra 10.12.2
- Browser and its version: Chrome Version 55.0.2883.95 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.

Running the following code locally renders the buttons correctly but not the functionality. This problem is specific to RadioButton, as the following code works perfectly with the Radio component. 
```
            render() {
                const { getFieldDecorator } = this.props.form;
                const formItemLayout = {
                    labelCol: { span: 7 },
                    wrapperCol: { span: 14 },
                };
                return (
                    <Form horizontal onSubmit = {this.handleSubmit}>
                        <FormItem
                            {...formItemLayout}
                            label = "Options"
                        >
                            {getFieldDecorator('radio-button', {
                                rules: [{
                                    required: true, message: 'Please select an option.',
                                }],
                            })(
                                <RadioGroup>
                                    <RadioButton value = "a">A</RadioButton>
                                    <RadioButton value = "b">B</RadioButton>
                                    <RadioButton value = "c">C</RadioButton>
                                </RadioGroup>,
                            )}
                        </FormItem>
                        ...
                </ Form>
```

#### What did you expect?

Radio Buttons should be selected when clicked, like in the example on the documentation site.

#### What happen?

RadioButton onHover animations work correctly but nothing happens onClick.

**Comment by benjycui** [comment] 2017-01-19 01:57
It works fine https://ant.design/components/form/#components-form-demo-validate-other

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment] 2017-01-22 10:12
Close it now. Reopen it if you can provide a re-producible demo.

**Closed by afc163** 2017-01-22 10:12 UTC

**Comment by tamagokun** [comment] 2017-02-22 14:35
I can reproduce this locally, but setting up the same example in codepen seems to work just fine.

However, I have deduced that the problem seems to be related to event handling. I can use `RadioButton` or `Radio` and use `onChange` for `RadioGroup` and I don't get anything calling that handler.

```js
class Form extends Component {
  onChange = (e) => {
    console.log('test', e)
  }

  render () {
    return <RadioGroup onChange={this.onChange}>
      <RadioButton value='a'>a</RadioButton>
      <RadioButton value='b'>b</RadioButton>
    </RadioGroup>
  }
}
```

If it makes any difference, i'm using next.js locally.

**Comment by tamagokun** [comment] 2017-02-22 14:51
Update:

I think this is the issue: https://github.com/ant-design/ant-design/blob/master/components/radio/group.tsx#L90

```js
if (radio && (radio.type === Radio || radio.type === RadioButton) && radio.props) {
```

it seems `radio.type` is not matching up. Perhaps this is an issue with babel?

**Comment by benjycui** [comment] 2017-02-23 02:09
@tamagokun Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001
