### ISSUE TITLE
Add possibility of providing arrow property to Tabs component for customizing inner Dropdown component

### ISSUE THREAD

**Issue by Romkaf** [ant-design/ant-design#30606] opened 2021-05-20 20:36 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
By default, the Dropdown in the Tabs component does not accept the arrow property. In order to add an arrow that is needed by design, you have to write extra code that creates problems!
I just ask you to add the arrow property to the inner Dropdown so that you can throw this property into the Tabs component. Adding a few lines of code will greatly simplify the interaction with the internal component of Tabs.

### What does the proposed API look like?
Add property arrow in TabNavList/OperationNode.tsx for Dropdown component

**Comment by afc163** [comment] 2021-05-21 02:48
Duplicate of #25844

**Closed by afc163** 2021-05-21 02:48 UTC
