### ISSUE TITLE
Table表格 ，分页配置项position属性，未提供隐藏配置

### ISSUE THREAD

**Issue by YWDMB** [ant-design/ant-design#14012] opened 2018-12-29 06:35 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
并不是所有Table表格都有分页能力

### What does the proposed API look like?
position     'top' | 'bottom' | 'both' | 'none'

**Comment by afc163** [comment] 2018-12-29 06:38
`position={false}` will hide and disable the pagination.

**Comment by afc163** [comment] 2018-12-29 06:38
Duplicate of #11213

**Closed by afc163** 2018-12-29 06:38 UTC

**Comment by YWDMB** [comment] 2018-12-29 06:48
https://ant.design/components/table-cn/#pagination
position={false}  Can not work

**Comment by YWDMB** [comment] 2018-12-29 07:09
pagination={false}

**Comment by tylerrrkd** [comment] 2020-04-21 11:29
@afc163 the position props of Pagination doesn't work in V4. Representation link: https://ant.design/components/table-cn/, search `pagination` and the first result is the problem.
