### ISSUE TITLE
tslint warning in Button component

### ISSUE THREAD

**Issue by yukai-w** [ant-design/ant-design#16025] opened 2019-04-11 07:45 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jlwopyz1x3)

### Steps to reproduce
https://codesandbox.io/s/jlwopyz1x3

### What is expected?
no tslint warning

### What is actually happening?
warning

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | react 16  |
| System | mac mojave |
| Browser | chrome 73.0.3683.103 |

**Comment by yesmeck** [comment] 2019-04-11 07:46
Duplicate of #15930

**Closed by yesmeck** 2019-04-11 07:46 UTC
