### ISSUE TITLE
InputNumber 格式化金额时 只输入4位 会自动补充为5位

### ISSUE THREAD

**Issue by dengshijian** [ant-design/ant-design#27905] opened 2020-11-20 07:35 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-number/#components-input-number-demo-formatter](https://ant.design/components/input-number/#components-input-number-demo-formatter)

### Steps to reproduce
在微软输入法 中文输入状态下 输入4位数字1

### What is expected?
正常显示

### What is actually happening?
经过formatter会变成5位

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | react |
| System | win 10 |
| Browser | google 86.0.4240.111 |

**Comment by yoyo837** [comment] 2020-11-20 07:47
Duplicate of #27748

**Closed by yoyo837** 2020-11-20 07:47 UTC
