### ISSUE TITLE
Input.Search onChange event fires with duplicated value when wrapped in AutoComplete and using copy/paste

### ISSUE THREAD

**Issue by rvinzent** [ant-design/ant-design#25228] opened 2020-06-25 18:53 UTC
- [ ] ~~I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.~~

This is a duplicate of an #25102  that has been closed without a fix and is no longer being acknowledged.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-bfdfz?file=/package.json)

### Steps to reproduce
copy/paste any value into the search box

### What is expected?
the same value is emitted by the on change event

### What is actually happening?
the value is duplicated and concatenated when emitted by the `onChange` event, e.g. `something` becomes `somethingsomething`

<img width="1348" alt="Screen Shot 2020-06-22 at 10 45 49 AM" src="https://user-images.githubusercontent.com/34038882/85781377-788f3b80-b6da-11ea-9c6b-bf1f2dc7f306.png">

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.13.1 |
| System | macOS 10.15.4 (19E287) |
| Browser | Chrome Version 83.0.4103.106 (Official Build) (64-bit) |

---
This is a duplicate of #25102  which was closed with a repro link that was still broken.

**Comment by afc163** [comment] 2020-06-28 12:59
I can't reproduce it

<img width="538" alt="image" src="https://user-images.githubusercontent.com/507615/85948224-3425c900-b982-11ea-817e-25b30430fece.png">

**Comment by rvinzent** [comment] 2020-06-28 14:26
You have to copy/paste (复制和粘贴) the value for it to work. Sorry for English 😬.

**Comment by afc163** [comment] 2020-06-28 14:31
![2020-06-28 22-29-41 2020-06-28 22_31_27](https://user-images.githubusercontent.com/507615/85950423-288ccf00-b98f-11ea-9f58-76fa28f42c06.gif)

**Comment by afc163** [comment] 2020-06-28 14:33
OK, I saw duplicated value in console now.

**Comment by AlbertAZ1992** [comment] 2020-07-03 02:34
@afc163  fixed in rc-select

**Comment by zombieJ** [comment] 2020-07-05 07:48
Why add `onChange` in the sub component? Just add it on the AutoComplete component instead.

**Closed** 2020-07-05 13:25 UTC
Labels: help wanted, 🐛 Bug
