### ISSUE TITLE
表格固定列情况下，右侧固定列跨列，样式出错， 左侧固定列跨列正常

### ISSUE THREAD

**Issue by SamWeichangyue** [ant-design/ant-design#31164] opened 2021-06-28 09:50 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gudinglie-antd4165-forked-e0y89?file=/index.js)

### Steps to reproduce
https://codesandbox.io/s/gudinglie-antd4165-forked-e0y89?file=/index.js

### What is expected?
右侧固定列跨列样式正常

### What is actually happening?
右侧固定列样式出错

| Environment | Info |
|---|---|
| antd | 4.16.5 |
| React | 16.14.0 |
| System | macOS |
| Browser | chrome  V91.0.4472.114 |

**Comment by SamWeichangyue** [comment] 2021-06-29 03:17
pro-component 下 table 也存在这个问题

**Comment by afc163** [comment] 2021-06-30 01:47
Duplicate of #31191

**Closed by afc163** 2021-06-30 01:47 UTC

**Comment by SamWeichangyue** [comment] 2021-06-30 02:47
issue 重复，但是bug怎么解决呢
