### ISSUE TITLE
The `prefixCls` feature of `Modal.info` method is incomplete

### ISSUE THREAD

**Issue by concefly** [ant-design/ant-design#12546] opened 2018-10-09 06:15 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wo45qp2437)

### Steps to reproduce
Just to invoke `Modal.info` with `prefixCls: 'custom-confirm'`.

### What is expected?
I expect that all the rended DOMs are prefixed correctly instead of the content area of Modal.

### What is actually happening?
![image](https://user-images.githubusercontent.com/6647656/46649974-90a0ed80-cbcd-11e8-9de7-fd6349d27435.png)

**Comment by afc163** [comment] 2018-10-09 06:16
Duplicate of #10855

**Comment by concefly** [comment] 2018-10-09 06:17
Well, I'm resoling it now and commiting a PR.

**Closed by afc163** 2018-10-09 06:16 UTC

**Comment by zombieJ** [comment] 2018-10-09 08:07
Seems little different with #10855 . The `prefixCls` works as the [content of Modal](https://github.com/ant-design/ant-design/blob/master/components/modal/confirm.tsx#L65) instead of Modal self.([history](https://github.com/ant-design/ant-design/blame/bbbdb9911d0d39e1721252c02046074ead7279a1/components/modal/confirm.tsx#L15))
