### ISSUE TITLE
Table's column filter confirm and reset buttons are not working

### ISSUE THREAD

**Issue by linw1995** [ant-design/ant-design#13668] opened 2018-12-17 11:16 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
mac 10.14.2 Chrome 70.0.3538.110

### Reproduction link
[https://codepen.io/linw1995/pen/NeryyE](https://codepen.io/linw1995/pen/NeryyE)

### Steps to reproduce
click the column filter dropdown's confirm and reset buttons in Components/Table Ajax example.

### What is expected?
the column filter dropdown's confirm and reset buttons are working.

### What is actually happening?
the column filter dropdown's confirm and reset buttons are not working.

**Comment by afc163** [comment] 2018-12-17 12:11
Duplicate of #13563

**Closed by afc163** 2018-12-17 12:11 UTC
