### ISSUE TITLE
select扩展菜单 dropdownRender组件无法响应点击onClick事件

### ISSUE THREAD

**Issue by liangxinchao** [ant-design/ant-design#16527] opened 2019-05-11 02:27 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/select-cn/#header](https://ant-design.gitee.io/components/select-cn/#header)

### Steps to reproduce
select 扩展菜单dropdownRender can not onClick={}

### What is expected?
can click or ...

### What is actually happening?
can not click

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | 16 |
| System | all system |
| Browser | all version |

**Comment by chenshuai2144** [comment] 2019-05-12 02:24
重现地址？

**Comment by afc163** [comment] 2019-05-12 09:30
Duplicate of #13448

**Closed by afc163** 2019-05-12 09:30 UTC
