### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by proficientdesigners** [ant-design/ant-design#31805] opened 2021-08-16 09:12 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/goofy-water-e31p3?file=/pages/index.js)

### Steps to reproduce
Need to check the simple antd login form with next js latest version with reactStrictMode: true,

### What is expected?
Need to solve the console log issue for Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode.

### What is actually happening?
When using the <Form.Item> with <Form.Item help="some string"/> the error occurs, but not when disabling strict mode

| Environment | Info |
|---|---|
| antd | 4.16.11 |
| React | 17.0.2 |
| System | Win 10 64 Bit - 21H1 |
| Browser | 92.0.4515.131 |

**Comment by yoyo837** [comment] 2021-08-16 09:15
See https://github.com/ant-design/ant-design/issues/26136

**Comment by afc163** [comment] 2021-08-16 09:18
Duplicate of #26136

**Closed by afc163** 2021-08-16 09:18 UTC

**Comment by julianklumpers** [comment] 2021-11-10 13:00
Because the duplicates are blocked and only accessible to moderators.

As a workaround, I am adding this at the root file.
I'm suppressing the warning like so:

```ts
// eslint-disable-next-line
const consoleError = console.error.bind(console);
// eslint-disable-next-line
console.error = (errObj, ...args) => {
  if (
    (process.env.NODE_ENV === 'development' && typeof errObj.message === 'string' && args.includes('findDOMNode')
  ) {
    return;
  }
  consoleError(errObj, ...args);
};
```

I know this is not a fix, but at least my console is not bloated with `findDOMNode` messages. Until And-Design fixes this, this will do.
