### ISSUE TITLE
Table scroller appears when there's no scroll needed

### ISSUE THREAD

**Issue by galisandlerfed** [ant-design/ant-design#21304] opened 2020-02-09 11:54 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://2t62s.csb.app/](https://2t62s.csb.app/)

### Steps to reproduce
Create a Table component with scrolling option and an option to add columns.

### What is expected?
I want the x axis scroller to appear only when the table is wide enough to scroll and not from the beginning when there are few columns.

### What is actually happening?
The x axis scroller appear always on the element (overflow: scroll)

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.9.0 |
| System | Windows 10 |
| Browser | Chrome 79.0.3945.130 |

---
A quick fix would be overflow: auto on ant-table-scroll class element.
The problem is that the style of this element is inline and not in css so it can't be overridden with class selectors... Only with !important which I don't like to use...

Thank you!

**Comment by afc163** [comment] 2020-02-10 02:21
Duplicate of #12088

**Closed by afc163** 2020-02-10 02:21 UTC
