### ISSUE TITLE
日期组件的年份选择器点击无反应

### ISSUE THREAD

**Issue by janryWang** [ant-design/ant-design#16436] opened 2019-05-06 04:10 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/p9lj99x37)

### Steps to reproduce
直接点击控件

### What is expected?
目前onChange也没触发，交互上也没任何反馈

### What is actually happening?
目前onChange也没触发，交互上也没任何反馈

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.7 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment] 2019-05-06 05:27
Duplicate of #4524

https://github.com/ant-design/ant-design/issues/15572

**Closed by afc163** 2019-05-06 05:27 UTC

**Comment by afc163** [comment] 2019-06-05 12:37
https://github.com/ant-design/ant-design/pull/16984
