### ISSUE TITLE
InputNumber doesn't work properly

### ISSUE THREAD

**Issue by zhz26826** [ant-design/ant-design#27768] opened 2020-11-13 21:29 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-enwmsj?file=index.js](https://stackblitz.com/edit/react-enwmsj?file=index.js)

### Steps to reproduce
1. Click InputNumber component to gain focus.
2. Input any number, e.g. 30.
3. Click step up/down button, or press up/down key. 
Then you can see the number doesn't increase/decrease correctly .

### What is expected?
The number should increase/decrease correctly after above steps.

### What is actually happening?
The number doesn't increase/decrease correctly  after above steps.

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 17.0 |
| System | macOS |
| Browser | chrome |

**Comment by kovalenkovpu** [comment] 2020-11-14 07:23
@zhz26826 I suppose such a behavior might be described here: https://github.com/facebook/react/issues/14010#issuecomment-433788147, though it's about functional components and a slightly different case.

**Comment by afc163** [comment] 2020-11-14 07:56
Duplicate of #26285

**Closed by afc163** 2020-11-14 07:56 UTC
Labels: 🐛 Bug
