### ISSUE TITLE
Table 组件设置滚动并包含自动宽高的图片时，固定列如何对齐

### ISSUE THREAD

**Issue by infinnie** [ant-design/ant-design#20993] opened 2020-01-18 07:24 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/practical-ives-p9nrd)

### Steps to reproduce
```jsx
<Table
  scroll={{ x: 1000 }}
  columns={[
    {
      title: "Image",
      render: () => ({
        children: (
          <img
            className="image"
            src="https://github.githubassets.com/images/modules/site/home-illo-business.png"
          />
        )
      })
    },
    {
      title: "Other",
      dataIndex: "text",
      fixed: "right"
    }
  ]}
  dataSource={[{ text: "text" }]}
/>
```

### What is expected?
固定的 Other 栏与包括图片的 Image 栏垂直方向对齐

### What is actually happening?
固定的 Other 栏与包括图片的 Image 栏垂直方向对齐不能，直到 (_e.g._) 窗口缩放之后

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.12.0 |
| System | Windows 7 |
| Browser | Google Chrome |

**Comment by zombieJ** [comment] 2020-01-19 06:55
Duplicate of #9900

**Closed by zombieJ** 2020-01-19 06:55 UTC
