### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by sunshixiong789** [ant-design/ant-design#13427] opened 2018-12-04 06:03 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
react 16.3

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
I used the create -react-app and antd  react-app-rewired,but find D:\bocoworkpace\comprehensive-regulation-web\node_modules\antd\lib\input\TextArea.d.ts
(20,21): error TS2304: Cannot find name 'ResizeObserver'.

### What is expected?
Compile

### What is actually happening?
Failed to compile

**Comment by yesmeck** [comment] 2018-12-04 06:04
Duplicate of #13405

**Closed by yesmeck** 2018-12-04 06:04 UTC

**Comment by sunshixiong789** [comment] 2018-12-04 06:07
I have searched this problem, the keyword is wrong. think you
