### ISSUE TITLE
Image.PreviewGrou组件在有相同图片时，左右切换的显示有问题

### ISSUE THREAD

**Issue by Huangxiaoyan71** [ant-design/ant-design#28496] opened 2020-12-23 03:17 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/image-cn/#header](https://ant.design/components/image-cn/#header)

### Steps to reproduce
    <Image.PreviewGroup>
      <Image
        width={200}
        src="https://gw.alipayobjects.com/zos/antfincdn/aPkFc8Sj7n/method-draw-image.svg"
      />
      <Image
        width={200}
        src="https://gw.alipayobjects.com/zos/antfincdn/aPkFc8Sj7n/method-draw-image.svg"
      />
    </Image.PreviewGroup>
PreviewGroup里面的图片链接一样的时候，左右切换图标显示有问题，遇到重复的图片无法显示。给图片链接加上不同的参数，像是https://gw.alipayobjects.com/zos/antfincdn/aPkFc8Sj7n/method-draw-image.svg?index=1，https://gw.alipayobjects.com/zos/antfincdn/aPkFc8Sj7n/method-draw-image.svg?index=0.就正常了

### What is expected?
有链接一样的图片也能显示左右切换图标

### What is actually happening?
有链接一样的图片不能显示左右切换图标

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.8.6 |
| System | windows |
| Browser | chrome |

**Comment by shaodahong** [comment] 2020-12-23 07:51
Duplicate of https://github.com/ant-design/ant-design/issues/28190

**Closed by shaodahong** 2020-12-23 07:51 UTC
