### ISSUE TITLE
Grid breakpoints with "flex props" not working

### ISSUE THREAD

**Issue by Tideus** [ant-design/ant-design#35958] opened 2022-06-08 19:00 UTC
### Reproduction link

[https://stackblitz.com/edit/react-acajke-gk1kjh?file=demo.js](https://stackblitz.com/edit/react-acajke-gk1kjh?file=demo.js)

### Steps to reproduce

Set breakpoints for a <Сol>:
```
<Сol>
   sm={{ flex: '100px' }}
   md={{ flex: '200px' }}
   lg={{ flex: '300px' }}
...
</Сol>
```

### What is expected?

The column size changes depending on the screen size.

### What is actually happening?

Column size does not change
```
labelCol={{ md: { flex: '50px' } }}
```
doesn't work either

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 17.0.2 |
| System | Windows 11 Pro |
| Browser | Google Chrome 102.0.5005.63 (64-bit) |

**Comment by afc163** [comment] 2022-06-09 02:18
Duplicate of #28961

**Closed by afc163** 2022-06-09 02:18 UTC

**Comment by Tideus** [comment] 2022-06-09 05:42
Thanks!
