### ISSUE TITLE
table组件数据过滤后，导致无法拖动滚动条，应该跟z-index有关；由于开始table记录较多，左侧固定column的高度较高，记录过滤后table高度降低，然而固定column的高度没变，导致覆盖横向滚动条，致无法滚动

### ISSUE THREAD

**Issue by coderyyx** [ant-design/ant-design#4893] opened 2017-02-15 13:14 UTC
![git](https://cloud.githubusercontent.com/assets/19465842/22975979/bc7c5c66-f3c3-11e6-8165-edd11d5ac894.png)

**Comment by benjycui** [comment] 2017-02-16 02:17
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment.

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by coderyyx** [comment] 2017-02-16 02:32
The first few columns is fixed,When I set the table properties scroll {x:Number,y:Number}, When the table data is getting less,Horizontal scroll bar is not work ,i think because the scroll.y is Fixed ,so Horizontal scroll bar was obscured by "ant-table-body-outer";please this picture

**Comment by yesmeck** [comment] 2017-02-17 03:32
Can't reproduce your issue, please provide a online demo http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by coderyyx** [comment] 2017-02-17 03:46
open 114.215.113.118:8080/DT

**Comment by coderyyx** [comment] 2017-02-17 03:52
when i review  your source code,the table height is auto.But my table height is fixed and the first few is fixed.when table data is getting less, Horizontal scroll bar was obscured by "ant-table-body-outer".tips:
my code too much so that is not convenient for you.

**Comment by yesmeck** [comment] 2017-02-17 03:56
Could you create a minimal demo on codepen?

**Comment by coderyyx** [comment] 2017-02-17 04:05
`class SearchTable extends React.Component {
  constructor(props){
    super(props);
    this.state={
          visible1:false,
          firstCheck:false,
          firstCheckData:{},
          maskClosable:false,
          rowData:{},
          column1:[
          {
            title: '患儿编码',
            dataIndex: 'disability_rescue_num',
            key: 'disability_rescue_num',
            fixed:'left',
            width:100

          },{
            title: '患儿姓名',
            dataIndex: 'disability_patient_name',
            key: 'disability_patient_name',
            fixed:'left',
            width:100

          },{
            title: '审核状态',
            dataIndex: 'disability_flow_state',
            key: 'disability_flow_state',
            fixed:'left',
            width:120,
            render:(text, row, index)=>{
                  if(text==1)
                    return "等待初审";
                  else if(text==-1)
                    return "补充资料";
                  else if(text==2)
                    return "初审通过";  
                  else if(text==3)
                    return "复审通过";
                  else if(text==-3)
                    return "复审不通过";
                  else
                    return "初审不通过";         
           }

          },{
            title: '初审时间',
            dataIndex: 'trail_time',
            key: 'trail_time',
            width:100

          },{
            title: '初审意见',
            dataIndex: 'trail_remark',
            key: 'trail_remark',
            width:150,
            render:(text, row, index)=>{
                if(!text)
                  return text;
                if(text.length>14)
                  return text.substring(0,14)+"...";
                else
                  return text;
            }
          },{
            title: '患儿生日',
            dataIndex: 'disability_birthday',
            key: 'disability_birthday',
            width:100

          },{
            title: '患儿性别',
            dataIndex: 'disability_patient_sex',
            key: 'disability_patient_sex',
            width:60

          },{
            title: '民族',
            dataIndex: 'disability_nationality_code',
            key: 'disability_nationality_code',
            width:60

          },{
            title: '证件号',
            dataIndex: 'card_code',
            key: 'card_code',
            width:150,
            render:(text, row, index)=>{
                if(!text)
                  return text;
                if(text.length>14)
                  return text.substring(0,14)+"...";
                else
                  return text;
            }

          },{
            title: '监护人',
            dataIndex: 'disability_guardian_name',
            key: 'disability_guardian_name',
            width:150,
            render:(text, row, index)=>{
                if(!text)
                  return text;
                if(text.length>14)
                  return text.substring(0,14)+"...";
                else
                  return text;
            }

          },{
            title: '监护人身份证号',
            dataIndex: 'disability_guardian_id_num',
            key: 'disability_guardian_id_num',
            width:150,
            render:(text, row, index)=>{
                // if(!text)
                //   return text;
                // if(text.length>14)
                //   return text.substring(0,14)+"...";
                // else
                  return text;
            }

          },{
            title: '联系手机',
            dataIndex: 'disability_mobile1',
            key: 'disability_mobile1',
            width:100,
            render:(text, row, index)=>{
                if(!text)
                  return text;
                if(text.length>14)
                  return text.substring(0,14)+"...";
                else
                  return text;
            }

          },{
            title: '定点医疗机构',
            dataIndex: 'disability_hospital_name',
            key: 'disability_hospital_name',
            width:200,
            render:(text, row, index)=>{
                if(!text)
                  return text;
                if(text.length>14)
                  return text.substring(0,14)+"...";
                else
                  return text;
            }

          },{
            title: '管理单位',
            dataIndex: 'manager_hospital_name',
            key: 'manager_hospital_name',
            width:200,
            render:(text, row, index)=>{
                if(!text)
                  return text;
                if(text.length>14)
                  return text.substring(0,14)+"...";
                else
                  return text;
            }
          },{
            title: '户籍所在地',
            dataIndex: 'disability_present_village_name',
            key: 'disability_present_village_name',
            width:200,
            render:(text, row, index)=>{
                if(!text)
                  return text;
                if(text.length>14)
                  return text.substring(0,14)+"...";
                else
                  return text;
            }

          },{
            title: '病种系统',
            dataIndex: 'disability_disease_type_name',
            key: 'disability_disease_type_name',
            width:200,
            render:(text, row, index)=>{
                if(!text)
                  return text;
                if(text.length>14)
                  return text.substring(0,14)+"...";
                else
                  return text;
            }

          },{
            title: '病名',
            dataIndex: 'disability_disease_name',
            key: 'disability_disease_name',
            width:200,
            render:(text, row, index)=>{
                if(!text)
                  return text;
                if(text.length>14)
                  return text.substring(0,14)+"...";
                else
                  return text;
            }

          },{
            title: '申请日期',
            dataIndex: 'disability_apply_time',
            key: 'disability_apply_time',
            width:100

          },{
            title: '录入人',
            dataIndex: 'create_user_name',
            key: 'create_user_name',
            width:100,
            render:(text, row, index)=>{
                if(!text)
                  return text;
                if(text.length>14)
                  return text.substring(0,14)+"...";
                else
                  return text;
            }

          },{
            title: '录入时间',
            dataIndex: 'create_time',
            key: 'create_time',
            width:100

          },{
            title: '家庭住址',
            dataIndex: 'disability_address',
            key: 'disability_address',
            width:200,
            render:(text, row, index)=>{
                if(!text)
                  return text;
                if(text.length>14)
                  return text.substring(0,14)+"...";
                else
                  return text;
            }

          },{
            title: '操作',
            key: 'outpatient_id16',
            fixed:'right',
            width:100,
            render:(text, row, index)=>{
            return <a onClick={()=>{this.showFirstCheck(row)}}>材料初审</a>;           
           }
          }],
          tableData:[],
          flag:false,
          top:600,
          totalPages:"",
          pageNo:""
    }
  }
  componentWillReceiveProps(nextProps){
  }
  componentWillMount(){
    // this.getRefresh();
  }
  componentWillUnmount() {
      DiagnoseManageCase.removeChangeListener(this._change.bind(this));
  }
  componentDidMount() {
      DiagnoseManageCase.addChangeListener(this._change.bind(this));
      t_height=$(window).height()-$(".form1").offset().top-$(".form1").height()-200;
       q_str={disability_num:"",patient_name:"",guardian_name:"",mobile:"",disease_type:"",disease_id:"",state:"",beginDate:"",endDate:"",doc_hospital_id:HospitalName.departmentid};
    let _data=searchFirstJudgeCase({data:q_str,page:1,pagesize:50},showError);
///////fixed the table height
      this.setState({top:t_hegiht,tableData:_data.data.row})
      
  }
  DoubleClick(record,index){
    // console.log(record)

    records=getApplyDetails(record.disability_id)
    this.setState({flag:false})
    if(!record.edit)
      this.setState({visible1:true,rowData:record})
  }
  showFirstCheck(row){
    this.setState({firstCheckData:row,flag:true})
  }
  hideModal(){
    this.setState({visible1:false})
  }
  hideFChcekModal(){
    this.setState({firstCheck:false})
  }
  getTop(arr,t_height){
    let rowNum=t_height>500?17:9;
    let h=arr.length>rowNum?rowNum*32:arr.length*32;
    let rowLength=arr.length;
    if(rowLength>rowNum||rowLength==rowNum){
      h=32*rowNum;
    }else if(rowLength<rowNum&&rowLength>4){
      h=rowLength*33;
    }else if(rowLength==1){
      h=50;
    }else if(rowLength==2){
      h=80;
    }else if(rowLength==3){
      h=108;
    }else if(rowLength==4){
      h=144;
    }
    return h;
  }
  _change() {
        //searchFrom data to refresh
        let _dataRow=DiagnoseManageCase.getCaseData();
        q_str=_dataRow.searchData;
        this.setState({top:h,tableData:_dataRow.data.row,total:_dataRow.data.total,totalPages:_dataRow.data.totalPages,pageNo:_dataRow.data.pageNo,flag:false});
  }
  render(){
    var top=this.state.top;
    var total=this.state.total;
    var totalPages=this.state.totalPages;
    var pageNo=this.state.pageNo;
// 3400
    const pagination={
      total:this.state.total,
      onChange: (current) => {
        //pageIndex current
        console.log(current)
        let dataRow=searchFirstJudgeCase({data:q_str,page:current,pagesize:50});
        this.setState({tableData:dataRow.row,total:dataRow.total,totalPages:dataRow.totalPages,pageNo:dataRow.pageNo,flag:false});
      },
      showTotal:(total)=>{ return "共"+total+"条记录"+" "+"第"+pageNo+"/"+totalPages+"页"},
      pageSize:50,
      showQuickJumper:true,
      defaultCurrent:1
      }
    
    return (
      <div style={_table}>
          <Table rowKey={record => record.uids} onRowDoubleClick={(record, index)=>this.DoubleClick(record, index)} dataSource={this.state.tableData} columns={this.state.column1} scroll={{x:3050,y:top}} pagination={pagination} size='small'/>
      </div>
    )
  } 
};

module.exports = SearchTable;`

**Comment by benjycui** [comment] 2017-02-17 06:07
An online demo is better, we are not JavaScript engine.

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by yesmeck** [comment] 2017-02-17 13:05
@coderyyx 在 codpen 上创建一个能运行并且能重现你问题的例子吧，不然没办法排查问题。

**Comment by whphhg** [comment] 2017-02-22 21:46
I'm experiencing the same issue (if I understand correctly). If the table has no scroll={{ y: 100 }} the header and cell align perfectly, but if I add y scroll limitation the headers get messed up.

![Err](https://preview.ibb.co/jbxpOv/Untitled.png)

**Comment by rfox00** [comment] 2017-02-23 08:41
我也遇到了这个问题，下面用官网demo改的例子：
http://codepen.io/rfox010/pen/jBONvE

设置了scroll.x和scroll.y，并且数据少于每页设置的最大数量时，左右锁定部分对应的底部滚动条无法拖动。
比如：每页显示10条，实际数据只有7条。

**Comment by coderyyx** [comment] 2017-02-23 08:46
小伙子终于有人遇到这个坑了啊@rfox00，我临时解决了，动态计算行高重新设置scroll.y，这样左侧固定部分就不会覆盖住横向滚动条了，

**Comment by rfox00** [comment] 2017-02-23 08:52
@coderyyx 恩恩，好办法啊，我也先用你这个思路改下吧，期待官方尽快fixed。

**Comment by coderyyx** [comment] 2017-02-23 08:56
@yesmeck 有中国人为什么要我用英语翻译啊，可怜我四级英语啊，我就在蚂蚁金服后面G栋，有空来看看  ->_<-,我们把你们的源码拿下来自己重新改了，你们修复的时候告诉下我具体怎么改的

**Comment by afc163** [comment] 2017-02-23 09:32
https://github.com/ant-design/ant-design/issues/4897

**Comment by afc163** [comment] 2017-02-23 09:32
@coderyyx 你不给我们重现的话，我们不是神仙，没有办法修复的。

**Comment by coderyyx** [comment] 2017-02-23 09:41
英文这个问题也解决了0-0，哈哈~看了你们rc-table代码，也没改好--主要是高度问题，你们用max-height和hieght又用来解决其他bug去了

**Comment by Serguzest** [comment] 2017-02-24 12:15
https://ant.design/components/table/#components-table-demo-fixed-columns-header

same bug is observable in the documentation. I am using full HD screen, if you have 4k screen, you might not able to observe the bug since there won't be any scroll at all, so just resize the browser's window down to the point where you can have horizontal scroll on the table.

**Comment by afc163** [comment] 2017-02-24 12:18
@Serguzest 

Because scroll area is fixed in `1500px` so it won't be scrollable in big screen.

```
<Table columns={columns} dataSource={data} scroll={{ x: 1500, y: 300 }} />
```

**Closed** 2017-02-27 07:54 UTC

**Comment by yesmeck** [comment] 2017-03-01 03:57
Reinstall node_modules.
