### ISSUE TITLE
global styles are overridden

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#28611] opened 2020-12-30 05:49 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/anniuleixing-antd494-forked-3z6rm)

### Steps to reproduce
Look directly at the a tag.
Here is an example of the a tag only, the global.less in the style folder also overrides some other styles

### What is expected?
Same style as the native browser

### What is actually happening?
Not the same style as the native browser

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | react16 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment] 2020-12-30 08:02
Duplicate of #9363

**Closed** 2020-12-30 08:02 UTC
