### ISSUE TITLE
希望能出一个Remixjs基于vite最新构建的antd5 ssr渲染的Demo?

### ISSUE THREAD

**Issue by Caesar-APAX** [ant-design/ant-design#49520] opened 2024-06-20 05:56 UTC
### What problem does this feature solve?

是否支持最新版本remixjs ssr渲染

### What does the proposed API look like?

是否支持最新版本remixjs ssr渲染

**Comment by afc163** [comment] 2024-06-20 06:01
Duplicate of https://github.com/ant-design/ant-design/discussions/49519

**Closed by afc163** 2024-06-20 06:01 UTC
Labels: unconfirmed
