### ISSUE TITLE
Select Header or Title should be stay when i select.

### ISSUE THREAD

**Issue by alicancelik** [ant-design/ant-design#13976] opened 2018-12-27 13:18 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
browser version

### Steps to reproduce
https://ant.design/components/select/

### What is expected?
I expected when i select option , it should be contain in select inner value , select inner value should be only as `1 item selected`  

<img width="205" alt="ekran resmi 2018-12-27 11 13 51" src="https://user-images.githubusercontent.com/26031105/50481519-0fe6d600-09f3-11e9-92c5-04d64c8f948e.png">

### What is actually happening?
When i select option , select option's name rendering in select inner value , for multi select every selected name became bigger to select width.

<img width="191" alt="ekran resmi 2018-12-27 11 10 00" src="https://user-images.githubusercontent.com/26031105/50481513-052c4100-09f3-11e9-8f33-daa3d4e9ed9e.png">

**Comment by alicancelik** [comment] 2018-12-27 13:20
@afc163  please do not put tag we can deal without link of reproduction :)

**Comment by afc163** [comment] 2018-12-27 14:20
Duplicate of #13968

**Closed by afc163** 2018-12-27 14:20 UTC
