### ISSUE TITLE
Select 选择器支持延迟触发 onSearch

### ISSUE THREAD

**Issue by lin-mt** [ant-design/ant-design#28796] opened 2021-01-10 02:45 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
输入框要输入的内容还没完全输入的时候会直接触发查询，而且间隔时间很短，虽然我们可以使用 setTimeout 自己实现，但是还是希望可以支持这个功能

### What does the proposed API look like?
function(value: string, delayTime?: number)

**Comment by afc163** [comment] 2021-01-10 13:50
Duplicate of #28369

**Closed by afc163** 2021-01-10 13:50 UTC
