### ISSUE TITLE
form中使用rangePicker输入开始值后再输结束值会自动删除开始值

### ISSUE THREAD

**Issue by hui5078** [ant-design/ant-design#18643] opened 2019-09-03 09:48 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
在form中使用rangePicker手动输入开始值后再输结束值会自动删除开始值

### What is expected?
手动输入后页面可展示而非删除

### What is actually happening?
在form中使用rangePicker手动输入开始值后再输结束值会自动删除开始值

| Environment | Info |
|---|---|
| antd | 3.23.1 |
| React | 无限制 |
| System | 76.0.3809.132 |
| Browser | 谷歌 |

---
可修改RangePicker.tsx中如下方法修改解决：
static getDerivedStateFromProps(nextProps: any, prevState: any) {
let state = null;
if ('value' in nextProps || prevState.open) {
const value = nextProps.value || prevState.value || [];
state = {
value,
};
if (!shallowequal(nextProps.value, prevState.value)) {
state = {
...state,
showDate: getShowDateFromValue(value, nextProps.mode) || prevState.showDate,
};
}
}
if ('open' in nextProps && prevState.open !== nextProps.open) {
state = {
...state,
open: nextProps.open,
};
}
return state;
}

**Comment by afc163** [comment] 2019-09-03 11:13
Duplicate of #17779

**Closed by afc163** 2019-09-03 11:13 UTC
