### ISSUE TITLE
Scroll-x is visible while it useless

### ISSUE THREAD

**Issue by GBcrimson** [ant-design/ant-design#22781] opened 2020-03-31 08:29 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-table-scroll-x-04rp7)

### Steps to reproduce
Width of table more than with of scroll props 'scroll={{x: 800}}'.

### What is expected?
 The scroll-x at the bottom of table invisible.

### What is actually happening?
 The scroll-x at the bottom of table is disabled, but visible. The table wrapper has styles: overflow-x: scroll; 

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | 16.11.0 |
| System | Win 10 |
| Browser | chrome  |

---
If the table wrapper styles: overflow-x: auto; All ok

**Comment by GBcrimson** [comment] 2020-03-31 08:30
![image](https://user-images.githubusercontent.com/4223563/78004594-fdb8bd80-7342-11ea-9309-7c373a79b97e.png)
![image](https://user-images.githubusercontent.com/4223563/78004635-0ad5ac80-7343-11ea-95f9-1a2d7083fdfe.png)

**Comment by GBcrimson** [comment] 2020-03-31 08:37
Actual for all  3.* (3.24+)

**Comment by afc163** [comment] 2020-03-31 09:11
Duplicate of #22346

**Closed by afc163** 2020-03-31 09:11 UTC
