### ISSUE TITLE
After upgrading from version 5.5 to version 5.16 I get Node memory limit error

### ISSUE THREAD

**Issue by ammirator-administrator** [ant-design/ant-design#49185] opened 2024-06-02 21:03 UTC
### Reproduction link

Not possible to provide such, and please do not autoclose this is a serious issue
3 of them were closed, peoples are having problems

### Steps to reproduce

Upgrade to version 5.16.0
And then try to run a simple script like to check the TS types `tsc --noEmit --pretty --p .`
It fails because of this error
```
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

A library like antd should not each this much memory and something new was added in these last versions which just eats the memory as crazy, this is not normal at all

### What is expected?

Is expected to not eat that much memory
I saw a similar issue opened in the repo but people are suggesting to increasing memory that's crazy a UI library should not eat 2gb of default memory that's insane, I saw that someone gets the error even on start
I mean it happens in existent projects that's why is hard to provide a reproducible link, no one is going to provide a existent project as a reproducible

### What is actually happening?

It just eats all the memory on types checks
something was added in these versions which eats all the memory

| Environment | Info |
| --- | --- |
| antd | 5.16.0 |
| React | any |
| System | any |
| Browser | any |

---
nop

**Comment by ammirator-administrator** [comment] 2024-06-02 21:14
!!! Please do not suggest to ingrease node memory limit, a library should not eat default 2gb of memory, that's not ok

**Comment by arvinxx** [comment] 2024-06-03 01:14
If you don't give a reproduction, we can't make sure it's the issue of antd. If you are using nextjs, it also could be nextjs's issue.

**Comment by zombieJ** [comment] 2024-06-03 01:50
Pls provide reproduce instead. We can not get valid info from nothing.

ref: [How to submit a riddle](https://ant.design/docs/blog/issue-helper)

**Comment by tobiasjeckel** [comment] 2024-06-03 16:50
Can confirm with antd v5.18.0 and typescript version 5.4.5.

After increasing my memory with `export NODE_OPTIONS=--max_old_space_size=14336` I was able to find out that many typescript errors of type 'Type instantiation is excessively deep and possibly infinite.' are thrown in Table components. The infinite type instantiation could maybe be what is causing the Node memory limit error. 
I am sorry I was unable to reproduce this in a separate online repo.

**Comment by tavvfiq** [comment] 2024-06-04 10:31
can confirm that this is reproducible by setting the max mem to 2048 when building. setting the max mem to at least 4096 solved the memory limit error but as @ammirator-administrator mention that this version seems using more than 2gigs memory..

**Comment by afc163** [comment] 2024-06-04 14:30
@ammirator-administrator @tavvfiq Could you guys provide a reproduce?

**Comment by matzeeable** [comment] 2024-06-05 09:05
Had the same issue with the latest version 5.18.0 (TypeScript `5.4.5`) and found out that this is caused by `rc-field-form` and `rc-table` and the following type `DeepNamePath`:

https://github.com/react-component/table/blob/dc8807f6f2f77b24b3b7577853e06c003c67d9b0/src/namePathType.ts#L8-L34
https://github.com/react-component/field-form/blob/6fac7ed93719dc4b9885de3010728a1c11818664/src/namePathType.ts#L6-L32

**Attention:** This issue does not happen for all projects, but larger ones with a lot of `Form.Item` and `Table` components!

When running in my large project with `tsc --noEmit --extendedDiagnostics`:

```
Memory used:              3498279K
```

When applying the optimized, below patch (e.g. with `patch-package` or `pnpm patch`):

```
Memory used:               598378K
```

This is a difference of 3.4 GB vs 500 MB (!).

Patched `DeepNamePath` (idk if this is optimal but it works for all my cases):

```ts
export type DeepNamePath<
  Store,
  ParentNamePath extends any[] = [],
  Depth extends any[] = []
> = Depth['length'] extends 4
  ? never
  : Store extends string | number | boolean
  ? ParentNamePath['length'] extends 0
    ? Store
    : never
  : Store extends (string | number | boolean)[]
  ? ParentNamePath['length'] extends 0
    ? Store
    : [...ParentNamePath, number]
  : Store extends any[]
  ? [...ParentNamePath, number] | DeepNamePath<Store[number], [...ParentNamePath, number], [unknown, ...Depth]>
  : Store extends object
  ? {
      [FieldKey in keyof Store]: Store[FieldKey] extends Function
        ? never
        :
            | (ParentNamePath['length'] extends 0 ? FieldKey : never)
            | [...ParentNamePath, FieldKey]
            | DeepNamePath<Required<Store>[FieldKey], [...ParentNamePath, FieldKey], [unknown, ...Depth]>;
    }[keyof Store]
  : never;
```

**Comment by tobiasjeckel** [comment] 2024-06-05 09:10
Thanks. Can confirm I am having the same exact issue in a large project with many `Table` and `Form.Item` components.

**Comment by crazyair** [comment] 2024-06-05 10:37
try antd 5.15.4 + rc-table 7.44.0

**Comment by crazyair** [comment] 2024-06-05 10:38
> try antd 5.15.4 + rc-table 7.44.0

I feel like it's caused by adding type constraints to Table dataIndex because Table triggers multiple times

**Comment by stoompa** [comment] 2024-07-02 12:58
Having the same issue, and dataIndex property in ColumnType causes the issue for me in latest antd

**Comment by edrmsgl** [comment] 2024-08-01 07:08
Similar problem applies to me. I am waiting for your solution suggestions.

And => 5.3.3
Typescript => 6.14.5
Nodejs => 12.18.2

**Comment by crazyair** [comment] 2024-08-01 07:10
The 'antd' version has already been released

**Comment by edrmsgl** [comment] 2024-08-01 07:13
Same problem I can't upgrade to version 5.19.4

**Comment by crazyair** [comment] 2024-08-01 07:24
> Same problem I can't upgrade to version 5.19.4

Why can't we upgrade

**Comment by edrmsgl** [comment] 2024-08-01 07:29
> Why can't we upgrade

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript gives heap out of memory error. I don't know if it is related to Nodejs, Typescript or OS versions. I need help.

**Comment by crazyair** [comment] 2024-08-01 07:30
Can you provide a reproduction

**Comment by edrmsgl** [comment] 2024-08-01 08:46
<--- Last few GCs --->                                                                                                                                                                         
                                                                                                                                                                                               
[36668:000001D974841260]   106270 ms: Mark-sweep 2045.2 (2053.6) -> 2043.3 (2052.4) MB, 2037.9 / 0.0 ms  (average mu = 0.067, current mu = 0.006) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF7196BA09D]
    1: StubFrame [pc: 00007FF7196BAFCD]
    2: StubFrame [pc: 00007FF7196FC1B2]
Security context: 0x02fd8fe808d1 <JSObject>
    3: getUnionTypeFromSortedList(aka getUnionTypeFromSortedList) [000001296B484F89] [C:\Users\emre.durmusoglu\Desktop\enocta.eep\enocta.eep.react\node_modules\typescript\lib\typescript.js:~62688] [pc=00000115D3FCB651](this=0x01b4e1
4804b1 <undefined>,0x01963e604661 <JSArray[464...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF718AA538F napi_wrap+114751
 2: 00007FF718A4FE26 v8::base::CPU::has_sse+66646
 3: 00007FF718A50C26 v8::base::CPU::has_sse+70230
 4: 00007FF719265B3E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF71924DC11 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF719119E7C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF7191250B0 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF719121BD4 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF7191173D3 v8::internal::Heap::CollectGarbage+1283
10: 00007FF719115A44 v8::internal::Heap::AddRetainedMap+2452
11: 00007FF719136D8D v8::internal::Factory::NewFillerObject+61
12: 00007FF718E9CED1 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1665
13: 00007FF7196BA09D v8::internal::SetupIsolateDelegate::SetupHeap+546637
14: 00007FF7196BAFCD v8::internal::SetupIsolateDelegate::SetupHeap+550525
15: 00007FF7196FC1B2 v8::internal::SetupIsolateDelegate::SetupHeap+817250
16: 00000115D3FCB651

**Comment by zombieJ** [comment] 2024-08-01 08:53
Reproduce means the build project not the log. It help less for us to debug the problem.

**Comment by edrmsgl** [comment] 2024-08-01 08:56
If you can send me a sample, I can try to prepare it.

**Comment by zombieJ** [comment] 2024-08-01 09:14
https://ant.design/docs/react/use-with-create-react-app  create a repo to reproduce and commit in github. Patch the github repo link.

**Comment by Mdemol** [comment] 2024-08-05 14:52
V5.15.4 seems to be working properly for me. From V5.16.0 and above seems to cause a memory issue in fork-ts-checker. As a workaroud you could create a .fork-ts-checkerrc file with the following content:

`{
    typescript: {
        memoryLimit: 8192
    }
}`

Also V5.16.0 and above seems to cause the error 'Type instantiation is excessively deep and possibly infinite.' in the Table components. For now I'm stuck at V5.15.4 sadly.

**Comment by 11bit** [comment] 2024-08-06 08:46
I made a repository that reproduces the bug https://github.com/11bit/antd-bug-reproduction. 

This is standard vite react project + fairly complex TS types generated from Github's graphql API. Bug happens because of [this file](https://github.com/11bit/antd-bug-reproduction/blob/main/src/App.tsx). Some more info in the project's readme.

By the way, as a workaround we narrow types that we use in table component. It is not very ergonomic but helps:
```
type RowInColumn = Pick<FullObject, 'col1' | 'col2' | 'col3'>
```

**Comment by crazyair** [comment] 2024-08-06 09:03
> I made a repository that reproduces the bug https://github.com/11bit/antd-bug-reproduction.
> 
> This is standard vite react project + fairly complex TS types generated from Github's graphql API. Bug happens because of [this file](https://github.com/11bit/antd-bug-reproduction/blob/main/src/App.tsx). Some more info in the project's readme.
> 
> By the way, as a workaround we narrow types that we use in table component. It is not very ergonomic but helps:
> 
> ```
> type PartialObject = Pick<FullObject, 'col1' | 'col2' | 'col3'>
> ```

 Your type is too large. It is recommended not to set the type for `ColumnsType`

```diff
-    const columns: ColumnsType<Repository> = [
+    const columns: ColumnsType = [
```

**Comment by 11bit** [comment] 2024-08-06 09:19
But I am loosing type safety for columns, right? It might be a workaround for people who want to upgrade tho.

**Comment by crazyair** [comment] 2024-08-06 09:26
DeepNamePath is designed to constrain dataIndex, but your type definition is too large for typescript to handle. So this function cannot be used

**Comment by vst** [comment] 2024-08-11 01:44
> `DeepNamePath` is designed to constrain `dataIndex`, but your type definition is too large for `typescript` to handle. So this function cannot be used

Is there a guidance for a "good size"?

**Comment by abenhamdine** [comment] 2024-08-11 21:35
> Can confirm with antd v5.18.0 and typescript version 5.4.5.
> 
> After increasing my memory with `export NODE_OPTIONS=--max_old_space_size=14336` I was able to find out that many typescript errors of type 'Type instantiation is excessively deep and possibly infinite.' are thrown in Table components. The infinite type instantiation could maybe be what is causing the Node memory limit error. I am sorry I was unable to reproduce this in a separate online repo.

Same issue for us.
Starting from 5.16, several definition columns triggers "Type instantiation is excessively deep and possibly infinite.ts(2589)" error

But I fail to see why theses particular lines causes an issue : 

```tsx
// Liv is a complex type generated by graphql-codegen
const columns: ColumnProps<Liv>[]

columns.push({
            title:
                <Tooltip title="Publication dans l'espace salarié">
                    <strong>Espace salarié</strong>
                </Tooltip>
            ,
            dataIndex: 'liv_is_displayed_salarie',
            key: 'liv_is_displayed_salarie',
            width: 165,
            align: 'center',
            fixed: 'right',
            render: (_value, liv) => isLivPublishableEspaceSal(liv) && <SwitchPublishLivInEspaceSalarie liv={liv} />,
            filters: publieFilters,
            onFilter: (value, liv) => {
                return !!liv.liv_is_displayed_salarie === value
            }
        })
```

**Comment by crazyair** [comment] 2024-08-12 07:16
> > Can confirm with antd v5.18.0 and typescript version 5.4.5.
> > After increasing my memory with `export NODE_OPTIONS=--max_old_space_size=14336` I was able to find out that many typescript errors of type 'Type instantiation is excessively deep and possibly infinite.' are thrown in Table components. The infinite type instantiation could maybe be what is causing the Node memory limit error. I am sorry I was unable to reproduce this in a separate online repo.
> 
> Same issue for us. Starting from 5.16, several definition columns triggers "Type instantiation is excessively deep and possibly infinite.ts(2589)" error
> 
> But I fail to see why theses particular lines causes this issue :
> 
> ```tsx
> // Liv is a complex type generated by graphql-codegen
> const columns: ColumnProps<Liv>[]
> 
> columns.push({
>             title:
>                 <Tooltip title="Publication dans l'espace salarié">
>                     <strong>Espace salarié</strong>
>                 </Tooltip>
>             ,
>             dataIndex: 'liv_is_displayed_salarie',
>             key: 'liv_is_displayed_salarie',
>             width: 165,
>             align: 'center',
>             fixed: 'right',
>             render: (_value, liv) => isLivPublishableEspaceSal(liv) && <SwitchPublishLivInEspaceSalarie liv={liv} />,
>             filters: publieFilters,
>             onFilter: (value, liv) => {
>                 return !!liv.liv_is_displayed_salarie === value
>             }
>         })
> ```

`const columns: ColumnProps<any>[]`

**Comment by Balaji1202** [comment] 2024-08-13 09:14
Any solution on this? I'm unable to upgrade 5.15.4 to any latest version.

**Comment by crazyair** [comment] 2024-08-13 09:18
> Any solution on this? I'm unable to upgrade from 5.15.4 to any latest version.

Please provide a reproduction

**Comment by Balaji1202** [comment] 2024-08-13 09:52
> > Any solution on this? I'm unable to upgrade from 5.15.4 to any latest version.
> 
> Please provide a reproduction

https://github.com/Balaji1202/antd-memory-issue

Clone this repository.
Run `yarn install` - antd version 5.20.0
Run `yarn tsc`

You should see this screen.
![image](https://github.com/user-attachments/assets/36c7811f-7547-4185-8b7f-d5a06cd27902)

Now, lower the antd version exact to "5.15.4" (The last version that doesn't have this issue)
Repeat the above steps, now it should complete normally.
![image](https://github.com/user-attachments/assets/95753675-daa1-4c06-9084-afe7344e0663)

**Comment by crazyair** [comment] 2024-08-13 09:55
> I made a repository that reproduces the bug https://github.com/11bit/antd-bug-reproduction.
> 
> This is standard vite react project + fairly complex TS types generated from Github's graphql API. Bug happens because of [this file](https://github.com/11bit/antd-bug-reproduction/blob/main/src/App.tsx). Some more info in the project's readme.
> 
> By the way, as a workaround we narrow types that we use in table component. It is not very ergonomic but helps:
> 
> ```
> type PartialObject = Pick<FullObject, 'col1' | 'col2' | 'col3'>
> ```

@Balaji1202 The same issue

```diff
-    const columns: ColumnsType<Repository> = [
+    const columns: ColumnsType = [
```

**Comment by Balaji1202** [comment] 2024-08-13 09:57
@crazyair This is one such instance. Consider a full blown project, do you want to remove the type from everywhere. I tried even that, but even then it is still happening for big projects.

**Comment by crazyair** [comment] 2024-08-13 09:58
> @crazyair This is one such instance. Consider a full blown project, do you want to remove the type from everywhere. I tried even that, but even then it is still happening for big projects.

Well, just remove the generics from ColumnsType

**Comment by Balaji1202** [comment] 2024-08-13 09:59
Sir, there is clearly some other underlying issue going. At least explain how on a lower antd version this works, and not with any version above 5.15.4.

**Comment by crazyair** [comment] 2024-08-13 10:06
> Sir, there is clearly some other underlying issue going. At least explain how on a lower antd version this works, and not with any version above 5.15.4.

In version 5.16.0, the table has been added https://ant.design/changelog#5160

Added dataindex type check
![image](https://github.com/user-attachments/assets/3f13d5a4-e53c-4f42-b778-afd0b158e9dd)

But your project's generic fields are too large, causing typescript parsing to fail. You can either shrink the types or remove the generics

**Comment by crazyair** [comment] 2024-08-13 12:08
I will test locally and change the length to 3. That's it. Wait for this https://github.com/react-component/table/pull/1170 Release the version, then antd will release the version

**Comment by Balaji1202** [comment] 2024-08-13 14:31
I cloned rc-table([with your changes](https://github.com/react-component/table/pull/1170/files)) and tested locally with this [issue repo](https://github.com/Balaji1202/antd-memory-issue) and with our actual project. It seems to run successfully now.🥳  Thanks a ton. 🎉

**Comment by afc163** [comment] 2024-08-13 15:29
Fixed in https://github.com/react-component/table/releases/tag/v7.47.2 , please remove lock files and reinstall node_modules.

**Comment by crazyair** [comment] 2024-08-13 15:31
> Fixed in https://github.com/react-component/table/releases/tag/v7.47.2 , please remove lock files and reinstall node_modules.

https://github.com/ant-design/ant-design/blob/master/package.json#L141

**Comment by Mdemol** [comment] 2024-08-14 08:36
The update seems to solve the 'Type instantiation is excessively deep and possibly infinite.' issue, but unfortunately the memory issue is still present.

**Comment by crazyair** [comment] 2024-08-14 08:37
Need to wait for antd to release the version

**Comment by yoyo837** [comment] 2024-08-16 02:16
Fixed in #50416. The fix will be included in the 5.21.0 release at the end of the month. At that time, please verify whether the problem has been fixed based on that version.

**Closed by yoyo837** 2024-08-16 02:16 UTC

**Comment by Balaji1202** [comment] 2024-09-05 04:22
When can we expect version `5.21.0` to be released. @yoyo837

**Comment by pengfan2013** [comment] 2024-11-29 09:40
表嵌入层级比较多时,  5.22.2构建时还是会轻松爆栈

**Comment by xuchaoying** [comment] 2024-12-23 06:01
不知道是不是table比较复杂？ 现在npm start后还是时不时会heap out of memory
