### ISSUE TITLE
antd 表单 getFieldDecorator 包裹自定义组件，校验规则可以生成，但是样式和提示不显示

### ISSUE THREAD

**Issue by zjscy666** [ant-design/ant-design#12763] opened 2018-10-22 08:09 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
全部

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
父组件MedicalListModal.jsx，这是一个modal
renderFormRow(modalData) {
        const { form: {getFieldDecorator}, handleAction } = this.props;
        let rowNum = modalData.length;
        let _arr = new Array(rowNum).fill(null);
        return (
            _arr.map((v, i) => {
                return (<FormItem
                    key={i}
                    {...this.formItemLayout}
                    label={modalData[i].label}
                >
                    {
                        modalData[i].type === 'autoComplete' && <EasyAutoComplete
                            data={modalData[i]}
                            getFieldDecorator={getFieldDecorator}
                            onSearchName={modalData[i].onSearch}
                            paramsField={modalData[i].id}
                            handleAction={handleAction}
                        />
                    }
                </FormItem>)
            })
        );
    };

export default Form.create()(MedicalListModal);

子组件 EasyAutoComplete.jsx
render() {
    const { dataSource } = this.state;
    const { data, getFieldDecorator, dataIndex } = this.props;
    let _id = data.id ? data.id : dataIndex;
    let initialValue = data[dataIndex] ? data[dataIndex]   '' : '';
    return (
      getFieldDecorator(_id, {
        rules: [{
          required: data.required, message: data.message,
        }],
        initialValue: initialValue,
      })(
        <AutoComplete
          dataSource={dataSource}
          onSelect={onSelect}
          onSearch={this.handleSearch}
          placeholder={data.placeholder}
        />
      )
    );
  }

export default EasyAutoComplete;

data.required是true,但是没有出现左边红色的*和相应的message提示

### What is expected?
期望出现提示和左边的红色*和相应的message提示

### What is actually happening?
data.required是true,但是没有出现左边红色的*和相应的message提示

---
重现链接随便写的，虽然校验可以，但是信息和样式不显示，用户无法及时获得相关信息

**Comment by afc163** [comment] 2018-10-22 13:20
Duplicate of #12762

**Closed by afc163** 2018-10-22 13:20 UTC
