### ISSUE TITLE
4.7.0 model 内选择 Select 组件选中下拉列表后自动关闭 

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design#27084] opened 2020-10-11 07:35 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
undefined

### Steps to reproduce
4.7.0 model 内选择 Select 组件选中下拉列表后自动关闭 

### What is expected?
不自动关闭

### What is actually happening?
自动关闭

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | react |
| System | windows |
| Browser | chrome |

**Comment by kaoding** [comment] 2020-10-11 07:37
@afc163 升级到 4.7.0 这个版本就会出现，需要一个紧急bug修复。

**Comment by yoyo837** [comment] 2020-10-11 07:39
Duplicate of #27080

**Comment by GuangMingZ** [comment] 2020-10-11 10:47
是的，本人也遇到了这个bug

**Closed** 2020-10-11 12:31 UTC
Labels: 🐛 Bug
