### ISSUE TITLE
Modal弹窗 将click事件注册在外层不清除将导致在微前端下重复订阅

### ISSUE THREAD

**Issue by ourfeel** [ant-design/ant-design#49506] opened 2024-06-19 11:06 UTC
### Reproduction link

[https://github.com/ant-design/ant-design/blob/4380c6b72dcc0efdbda1c0e600fc0fea6e9f7689/components/modal/Modal.tsx](https://github.com/ant-design/ant-design/blob/4380c6b72dcc0efdbda1c0e600fc0fea6e9f7689/components/modal/Modal.tsx)

### Steps to reproduce

![image](https://github.com/ant-design/ant-design/assets/4400909/e3f6b1f1-3617-448e-8963-1a9994548981)

### What is expected?

减少订阅数量

### What is actually happening?

大量订阅导致页面卡顿

| Environment | Info |
| --- | --- |
| antd | 5.18.3 |
| React | 任何 |
| System | 任何 |
| Browser | 任何 |

**Comment by afc163** [comment] 2024-06-19 11:09
Duplicate of #47498

**Closed by afc163** 2024-06-19 11:09 UTC
Labels: unconfirmed
