### ISSUE TITLE
antd4的所有弹出组件不支持IE？

### ISSUE THREAD

**Issue by ywy94ywy** [ant-design/ant-design#22667] opened 2020-03-27 07:56 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/dropdown-cn/](https://ant.design/components/dropdown-cn/)

### Steps to reproduce
点击下拉菜单组件

### What is expected?
希望在IE11下没有这样的问题①卡顿，②闪烁一次

### What is actually happening?
下拉菜单①卡顿，②闪烁一次

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.12.0 |
| System | window 10 |
| Browser | IE 11 |

**Comment by afc163** [comment] 2020-03-27 08:40
Duplicate of #21039

**Closed by afc163** 2020-03-27 08:40 UTC

**Comment by 532758463** [comment] 2020-07-21 06:47
这个有解决么？

**Comment by liqin1059** [comment] 2021-06-28 09:29
加一

**Comment by huahmj** [comment] 2021-07-23 00:54
这个问题什么时候解决？
