### ISSUE TITLE
RangePicker: Unable to use 24-hour clock

### ISSUE THREAD

**Issue by stoneox** [ant-design/ant-design#11200] opened 2018-07-09 03:45 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.5

### Environment
Linux; chrome 61; react 16.4.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lx3l3kjk3m)

### Steps to reproduce
1.click RangePicker component
2.select time 21:00:00

### What is expected?
RangePicker show 21:00:00

### What is actually happening?
show 9:00:00，Unable to use 24-hour clock

**Comment by dengfuping** [comment] 2018-07-09 04:07
@stoneox Duplicate of #11199.

**Closed by dengfuping** 2018-07-09 04:07 UTC
