### ISSUE TITLE
Add addonBefore and addonAfter to InputNumber

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design#26805] opened 2020-09-17 17:01 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We could have a unified formatting for Inputs and InputNumbers.
I have a form where I use Inputs with `addonBefore` prop extensively. And if InputNumber happens to be around - it looks really out of the ordinary. In such cases I have to drop usage of InputNumber and use simple Input instead - not to break uniformal style of my form.

### What does the proposed API look like?
Add `addonBefore` and `addonAfter` props.

**Comment by afc163** [comment] 2020-09-18 03:06
Duplicate of #14284

**Closed by afc163** 2020-09-18 03:06 UTC

**Comment by avalanche1** [comment] 2020-09-22 14:58
No. That's not a duplicate. 
They ask for adding `prefix` prop. I propose adding addonBefore and addonAfter props.

**Comment by jonybekov** [comment] 2020-11-12 06:48
Hi. I also wanted this feature as well

**Comment by mileshobby** [comment] 2021-01-21 07:56
Please could we get this 🙏

**Comment by peraltafederico** [comment] 2021-08-04 14:59
Why is this closed @afc163?
