### ISSUE TITLE
按照官网配置antd按需引入 打包后会多出来一个ICON/dist.js 400k左右的包

### ISSUE THREAD

**Issue by xiaofeizao1996** [ant-design/ant-design#16540] opened 2019-05-12 15:32 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/xiaofeizao1996/react-app](https://github.com/xiaofeizao1996/react-app)

### Steps to reproduce
运行yarn build

### What is expected?
文件没有引入这个包不会出现

### What is actually happening?
 出现了icon/dist.js这一个超级大的包

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | 16.8.6 |
| System | macos 10.14.4 |
| Browser | 版本 74.0.3729.131（正式版本） （64 位） |

---
自己尝试搭建脚手架出现该问题

**Comment by xiaofeizao1996** [comment] 2019-05-12 15:39
![image](https://user-images.githubusercontent.com/49969182/57584531-265b7d00-750f-11e9-826e-ff9028143a5d.png)

**Comment by afc163** [comment] 2019-05-13 02:48
Duplicate of #12011

**Closed by afc163** 2019-05-13 02:48 UTC
