### ISSUE TITLE
Datepicker tabbing behaviour

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design#19154] opened 2019-10-10 06:23 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently when navigating a form with keyboard, by tabbing through contols: when Datepicker gets focused - I cannot modify the value directly I have to click or press down to show the date chooser popup. This is inconvenient. 

### What does the proposed API look like?
When Datepicker gets focused - calendar popup should appear automatically.
If this goes against your design - then offer an API that would allow for such desired behaviour.

**Comment by afc163** [comment] 2019-10-10 06:45
Duplicate of #18936

**Closed by afc163** 2019-10-10 06:45 UTC

**Comment by afc163** [comment] 2019-10-10 06:49
Merge with https://github.com/ant-design/ant-design/issues/16270 

same as https://github.com/ant-design/ant-design/issues/4102#issuecomment-529167657

**Comment by avalanche1** [comment] 2019-10-10 09:38
Also note that the `Today` button inside calendar is not reachable via tabbing :(

**Comment by avalanche1** [comment] 2019-11-02 20:37
Also note that it is not possible to delete DatePicker value with backspace. In scenario when I've tabbed into the DatePicker.
