### ISSUE TITLE
Table组件增加columns resizeable功能

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#49732] opened 2024-07-05 02:04 UTC
### What problem does this feature solve?

可以对列的宽度进行自定义拖动

### What does the proposed API look like?

```
interface Column {
  // 之前的
  resizeable: boolean;
}
```

**Comment by afc163** [comment] 2024-07-05 04:28
Duplicate of https://github.com/ant-design/ant-design/issues/32811

**Closed by afc163** 2024-07-05 04:28 UTC
Labels: unconfirmed
