### ISSUE TITLE
希望Table提供对空数据替换文案的支持

### ISSUE THREAD

**Issue by perany** [ant-design/ant-design#28573] opened 2020-12-28 09:09 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当数据为undefined或者null时，希望table展示为'-'或者其他用户自定义的替换文案，而不是一个空的td。
功能必要性：当多个行列出现空数据时，页面显示空旷不雅观

### What does the proposed API look like?
在table增加替换文案配置，默认可以关闭

**Comment by afc163** [comment] 2020-12-28 09:15
Duplicate of #14459

**Comment by afc163** [comment] 2020-12-28 09:21
See https://github.com/ant-design/ant-design/issues/26423#issuecomment-682006310

**Closed by afc163** 2020-12-28 09:21 UTC
