### ISSUE TITLE
The above error occurred in the <MenuItem> component

### ISSUE THREAD

**Issue by six-666** [ant-design/ant-design#17068] opened 2019-06-12 12:56 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/six-666/bug](https://github.com/six-666/bug)

### Steps to reproduce
点击左侧菜单报错

### What is expected?
疑是menu组件所造成。

### What is actually happening?
疑是menu组件所造成。

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.8.6 |
| System | Mac |
| Browser | chrome |

**Comment by zombieJ** [comment] 2019-06-12 15:23
已知的 Suspense BUG：https://github.com/facebook/react/issues/15857

Duplicate of #17016

**Closed by zombieJ** 2019-06-12 15:23 UTC

**Comment by B1anker** [comment] 2019-07-19 11:43
@zombieJ 所以只能等react更新？

**Comment by zombieJ** [comment] 2019-07-22 02:22
@B1anker, 嗯。框架 bug 组件层面做不了什么。
