### ISSUE TITLE
antd Popover 包裹自定义组件 不起作用

### ISSUE THREAD

**Issue by gooddaddy** [ant-design/ant-design#19382] opened 2019-10-23 13:07 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hungry-jepsen-oly8n)

### Steps to reproduce
对比点击下两个button 

### What is expected?
自己包装了的组件起作用

### What is actually happening?
自己包装的组件不起作用

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16.11 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment] 2019-10-23 13:24
Duplicate of #15909

**Closed by afc163** 2019-10-23 13:24 UTC
