### ISSUE TITLE
RangePicker在IE11上，输入框无法聚焦的问题

### ISSUE THREAD

**Issue by wongfugui** [ant-design/ant-design#19851] opened 2019-11-21 03:01 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce

点击rangepicker组件，先将鼠标聚焦在输入框的结束日期上，然后开始日期输入框无法聚焦。
Click on the rangepicker component and focus the mouse on the enddate input box, then the startdate input box cannot be focused.

### What is expected?
先聚焦结束日期后，开始日期输入框可以聚焦。
The startdate input box can be focused after the mouse is focused on the enddate input box.

### What is actually happening?
先聚焦结束日期后，开始日期输入框无法聚焦。
The startdate input box cannot be focused after the mouse is focused on the enddate input box.

| Environment | Info |
|---|---|
| antd | 3.25.2 |
| React | 16.8.6 |
| System | windows |
| Browser | IE11 |

**Comment by afc163** [comment] 2019-11-22 07:47
Duplicate of #19128

**Closed by afc163** 2019-11-22 07:47 UTC
