### ISSUE TITLE
Tree loadData 在loading的过程中，treeData的icon会消失

### ISSUE THREAD

**Issue by wangdanting** [ant-design/ant-design#23496] opened 2020-04-22 10:00 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/16220538/79968740-23a92c00-84c3-11ea-95f3-2bf428c90265.png)
![image](https://user-images.githubusercontent.com/16220538/79968786-31f74800-84c3-11ea-9b07-e9cfc98ede85.png)

```
import React from 'react';
import ReactDOM from 'react-dom';
import { Tree } from 'antd';
import { FrownOutlined, SmileOutlined, MehOutlined, FrownFilled } from '@ant-design/icons';

const treeData = [
  {
    title: 'parent 1',
    key: '0-0',
    icon: <SmileOutlined />,
    children: [
      {
        title: 'leaf',
        key: '0-0-0',
        icon: <MehOutlined />,
      },
      {
        title: 'leaf',
        key: '0-0-1',
        icon: ({ selected }) => (selected ? <FrownFilled /> : <FrownOutlined />),
      },
    ],
  },
];

class Demo extends React.PureComponent {
  onLoadData = treeNode =>
    new Promise(resolve => {
      // resolve();
    });

  render() {
    return <Tree showIcon loadData={this.onLoadData} treeData={treeData} />;
  }
}

ReactDOM.render(<Demo />, document.getElementById('app'));
```

### What is expected?
Tree loadData 在loading的过程中，treeData的icon不会消失

### What is actually happening?
Tree loadData 在loading的过程中，treeData的icon会消失

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.0 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment] 2020-04-22 10:01
Duplicate of #23470

**Closed by afc163** 2020-04-22 10:01 UTC
