### ISSUE TITLE
ant-upload 如何进行大文件分块上传

### ISSUE THREAD

**Issue by sengmitnick126** [ant-design/ant-design#28112] opened 2020-12-01 08:12 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/upload-cn/#components-upload-demo-upload-with-aliyun-oss](https://ant-design.gitee.io/components/upload-cn/#components-upload-demo-upload-with-aliyun-oss)

### Steps to reproduce
无

### What is expected?
能够支持大文件分块上传

### What is actually happening?
大文件上传出错

| Environment | Info |
|---|---|
| antd | undefined |
| React | 4.0 |
| System | windows 10 |
| Browser | Chrome 46.0.2490.80 |

**Comment by xrkffgg** [comment] 2020-12-01 08:21
Duplicate of https://github.com/ant-design/ant-design/issues/25929

**Closed by xrkffgg** 2020-12-01 08:21 UTC

**Comment by hj12hj** [comment] 2022-02-09 01:46
有没有官方 例子
