### ISSUE TITLE
sortOrder defined for several Columns not working - caret shows up active only for the one of them

### ISSUE THREAD

**Issue by mcmxc** [ant-design/ant-design#15064] opened 2019-02-26 11:31 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/lpr1klo607?fontsize=14)

### Steps to reproduce
1. Create a Table using ants `Table` Component
2. Use ants `Column` components as a children
3. Provide `sorter={true}` and `sortOrder="ascend"` props to the several Column components

### What is expected?
Each Column with `sorter={true}` and `sortOrder=("ascend" || "descend")` props should have highlighted caret

### What is actually happening?
Only one Column has a highlighted caret identifying the sort order

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.8.1 |
| System | MacOS Mojave, 10.14.3 |
| Browser | Chrome (any browser basically) |

---
We are handling sorting with redux, in order to provide correct query params to sort table asynchronously. We have a secondary sort and would like to have visual indicators of which sorting field are currently applied. Thank You.

**Comment by zombieJ** [comment] 2019-02-26 15:00
Duplicate of #10946

**Closed by zombieJ** 2019-02-26 15:00 UTC
