### ISSUE TITLE
v4 RangePicker (with time) UX is confusing

### ISSUE THREAD

**Issue by mk-nickyang** [ant-design/ant-design#25926] opened 2020-07-31 04:06 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/u8d72)

### Steps to reproduce
v4 RangePicker user flow when `showTime={true}`:
- Select **start date**
- Select **start time** (optionally)
- Click **Ok**
- Select **end date**
- Select **end time** (optionally)
- Click **Ok**
- Done

### What is expected?
A better one

### What is actually happening?
The **Ok** button user has to click after selecting start date/time doesn't actually mean okay or finish.

Generally, the v4 RangePicker UX is much more complicated and confusing than the v3 one.

| Environment | Info |
|---|---|
| antd | 4.5.1 |
| React | 16.13.1 |
| System | macOS Catalina 10.15.5 |
| Browser | Chrome 84.0.4147.105 |

---
#WeWantV3RangePicker

**Comment by afc163** [comment] 2020-07-31 04:13
We should change `Ok` to a meaningful text, like `Next`.

**Comment by mk-nickyang** [comment] 2020-07-31 04:24
But what if user edits the **end date** first, click `Next`/`Ok` will then open the **start date** panel, which is also bit confusing

[![Image from Gyazo](https://i.gyazo.com/a9579856734b5be4d45ef99f3397410c.gif)](https://gyazo.com/a9579856734b5be4d45ef99f3397410c)

**Comment by mk-nickyang** [comment] 2020-07-31 04:52
In my humble opinion, even when user sets `showTime={true}`, RangePicker should still make date range select work the same, time select should be optionally and not breaking date range select workflow.

**Comment by afc163** [comment] 2020-07-31 09:49
We can discuess this in #21525, closing now.

**Comment by afc163** [comment] 2020-07-31 09:50
Duplicate of #21525

**Closed by afc163** 2020-07-31 09:49 UTC
