### ISSUE TITLE
Table总结栏在colspan=1时border-right被覆盖

### ISSUE THREAD

**Issue by meseme** [ant-design/ant-design#35763] opened 2022-05-27 01:42 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-4-18-7-forked-81my95?file=/index.js)

### Steps to reproduce

[Table标题在存在colspan和滚动条的时候border-right被覆盖 #35577](https://github.com/ant-design/ant-design/issues/35577) 
上面的Bug已经解决，稍带着把下面这个Bug也解决了吧，谢谢。
[Table 总结栏使用ColSpan前后风格不一致 #34129](https://github.com/ant-design/ant-design/issues/34129)

### What is expected?
右边栏正常
![0](https://user-images.githubusercontent.com/86905784/170610756-b51a907c-bb6a-4b2d-b65f-3828bbb99ee2.png)

### What is actually happening?
右边栏被覆盖
![1](https://user-images.githubusercontent.com/86905784/170610802-468cf7e4-5f08-4f49-8985-e03ea5422f0d.png)

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 16.14.0 |
| System | Windows 10 Pro N 19043.1348 |
| Browser | Microsoft Edge Version 96.0.1054.41 |

<!-- generated by ant-design-issue-helper. DO NOT REMOVE --
![0](https://user-images.githubusercontent.com/86905784/170610756-b51a907c-bb6a-4b2d-b65f-3828bbb99ee2.png)
![1](https://user-images.githubusercontent.com/86905784/170610802-468cf7e4-5f08-4f49-8985-e03ea5422f0d.png)
>

**Comment by afc163** [comment] 2022-05-27 02:23
Duplicate of #34129

**Closed by afc163** 2022-05-27 02:23 UTC
