### ISSUE TITLE
Tree组件的draggable配置不符合预期

### ISSUE THREAD

**Issue by ChenKun1997** [ant-design/ant-design#44875] opened 2023-09-15 01:06 UTC
### Reproduction link

[https://stackblitz.com/edit/react-tmkneq-wdupya?file=demo.tsx](https://stackblitz.com/edit/react-tmkneq-wdupya?file=demo.tsx)

### Steps to reproduce

如下图，上面四个节点是可以拖动的，nodeDraggable为true，下面四个不可拖动，但是同时上面四个节点应该不能拖动到下面四个节点上（也就是不可drop）
![image](https://github.com/ant-design/ant-design/assets/24249578/d22a2974-4edc-40da-9129-8ecd9e6f552f)

### What is expected?

期望可拖拽节点可以随意放置在任何地方

### What is actually happening?

不可拖拽的节点同时不可放置，不符合预期

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | 18.2.7 |
| System | mac |
| Browser | chrome |

**Comment by MadCcc** [comment] 2023-09-15 02:17
Duplicate of https://github.com/ant-design/ant-design/issues/44812

**Closed by MadCcc** 2023-09-15 02:17 UTC
Labels: unconfirmed
