### ISSUE TITLE
DatePicker[picker="halfyear"] RangePicker picker="halfyear"

### ISSUE THREAD

**Issue by toddywang** [ant-design/ant-design#42566] opened 2023-05-24 02:14 UTC
### What problem does this feature solve?

是否可以选择H1、H2模式。

### What does the proposed API look like?

<RangePicker picker="halfyear" />
<DatePicker picker="halfyear" />

**Comment by toddywang** [comment] 2023-05-24 02:14
<RangePicker picker="halfyear" /> <DatePicker picker="halfyear" />

**Comment by toddywang** [comment] 2023-05-24 02:14
RangePicker picker="halfyear" 
DatePicker picker="halfyear"

**Comment by afc163** [comment] 2023-05-24 02:27
Duplicate of #42565

**Closed by afc163** 2023-05-24 02:27 UTC
Labels: unconfirmed
