### ISSUE TITLE
Antd table virtual list supports expandable row

### ISSUE THREAD

**Issue by Sunnyjj-Sunnyjj** [ant-design/ant-design#28534] opened 2020-12-24 14:19 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Display a large list of data，table rows need to be displayed grouped by property;Poor scrolling.

### What does the proposed API look like?
virtual list supports expandable row

**Comment by afc163** [comment] 2020-12-25 02:38
Duplicate of #20339

**Closed by afc163** 2020-12-25 02:38 UTC
