### ISSUE TITLE
Select扩展菜单多选问题

### ISSUE THREAD

**Issue by heimiguoguo** [ant-design/ant-design#50787] opened 2024-09-10 09:23 UTC
### Reproduction link

[https://heimiguoguo.github.io/antd-demo](https://heimiguoguo.github.io/antd-demo)

### Steps to reproduce

选中一个选项jack，然后在input中输入hello，按退格键，选中的选项被清空了

### What is expected?

选中一个选项jack，然后在input中输入hello，按退格键，hello逐字母被清空

### What is actually happening?

选中一个选项jack，然后在input中输入hello，按退格键，选中的选项被清空了

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.1 |
| System | win10 |
| Browser | Chrome |

**Comment by afc163** [comment] 2024-09-10 14:02
Duplicate of https://github.com/ant-design/ant-design/issues/28694

**Closed by afc163** 2024-09-10 14:02 UTC
Labels: unconfirmed
