### ISSUE TITLE
升级v5后，没有css文件了，都是cssinjs，那想用postcss-pxtorem 咋办

### ISSUE THREAD

**Issue by changguilei** [ant-design/ant-design#43131] opened 2023-06-21 02:14 UTC
### Reproduction link

[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce

1

### What is expected?

可以继续使用postcss-pxtorem 适配大屏项目

### What is actually happening?

1

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | win |
| Browser | edge最新 |

**Comment by Wxh16144** [comment] 2023-06-21 02:16
Duplicate of #40789

**Closed by Wxh16144** 2023-06-21 02:16 UTC
Labels: unconfirmed

**Comment by zombieJ** [comment] 2023-06-21 02:17
Use Transformer: https://github.com/ant-design/cssinjs/blob/master/src/transformers/px2rem.ts

**Comment by changguilei** [comment] 2023-06-21 02:23
> Use Transformer: https://github.com/ant-design/cssinjs/blob/master/src/transformers/px2rem.ts

技术调整
弃用 less，采用 CSS-in-JS，更好地支持动态主题。底层使用 [@ant-design/cssinjs](https://github.com/ant-design/cssinjs) 作为解决方案。
所有 less 文件全部移除，less 变量不再支持透出。
产物中不再包含 css 文件。由于 CSS-in-JS 支持按需引入，原本的 antd/dist/antd.css 也已经移除，如果需要重置一些基本样式请引入 antd/dist/reset.css。
如果需要组件重置样式，又不想引入 antd/dist/reset.css 从而导致污染全局样式的话，可以尝试在应用最外层使用[App 组件](https://ant.design/components/app-cn)，解决原生元素没有 antd 规范样式的问题。

产物中都没用css了，怎么pxtorem ?

**Comment by yoyo837** [comment] 2023-06-21 02:24
> Use Transformer: https://github.com/ant-design/cssinjs/blob/master/src/transformers/px2rem.ts

用js调用

**Comment by afc163** [comment] 2023-06-21 02:33
拨冗读一下 https://github.com/ant-design/ant-design/discussions/40789#discussioncomment-5107123

**Comment by changguilei** [comment] 2023-06-21 02:35
> 拨冗读一下 [#40789 (reply in thread)](https://github.com/ant-design/ant-design/discussions/40789#discussioncomment-5107123) ，我们也确实要补一些文档。

看不懂，需要怎么用这个tansformer 转换啊
能上代码吗

**Comment by afc163** [comment] 2023-06-21 02:38
https://github.com/ant-design/ant-design/discussions/40789#discussioncomment-5107123 里 @Wxh16144 提到了一个 PR，链接是 https://github.com/ant-design/cssinjs/pull/89 ，PR 里实现了 px2remTransformer 并提供了相关 demo 代码。https://github.com/ant-design/cssinjs/pull/89/files#diff-0daf2b9114dc5ffa04af88924ad6eec68401bc222ed58fb5568418c1ec22d4dd

可以配合 https://ant.design/docs/react/compatible-style-cn#css-%E9%80%BB%E8%BE%91%E5%B1%9E%E6%80%A7 文档一起看最终的使用方式。

**Comment by changguilei** [comment] 2023-06-23 14:41
感谢大佬提供的px2remTransformer
现在提供的配置项太少了，能不能增加几个，参考postcss-pxtorem，因为有的属性我不想转换
postcsspxtorem({
                        rootValue({ file }) {
                            // 可以根据file做定制
                            // 参考vant的例子：file.indexOf('vant') !== -1 ? 37.5 : 75;
                            return 100;
                        },
                        unitPrecision: 6,
                        propList: ["*", "!font*", "!box-shadow", "!text-shadow"],
                        selectorBlackList: [], //不转换的类名
                        replace: true,
                        mediaQuery: true,
                        atRules: true,
                        minPixelValue: 1, //1px不会被转换，2px会被转换
                        exclude(file) {
                            // 默认值是/node_modules/i，若要使用第三方库，应该改为false
                            // 可以根据file做定制
                            return false;
                        },
                    }),

**Comment by yuenzp** [comment] 2023-07-20 02:51
@afc163  你好， 我安装了 5.7.1 ver 后有以下报错， 请问该如何解决？

····
ERROR in ./src/index.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/index.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '~antd/dist/antd.css' in 'C:\Users\afiqA\VSCode\Testing Trending Page\trending\src'
    at finishWithoutResolve (C:\Users\afiqA\VSCode\Testing Trending Page\trending\node_modules\enhanced-resolve\lib\Resolver.js:369:18)
    at C:\Users\afiqA\VSCode\Testing Trending Page\trending\node_modules\enhanced-resolve\lib\Resolver.js:461:15
    at C:\Users\afiqA\VSCode\Testing Trending Page\trending\node_modules\enhanced-resolve\lib\Resolver.js:519:5
    at eval (eval at create (C:\Users\afiqA\VSCode\Testing Trending Page\trending\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at C:\Users\afiqA\VSCode\Testing Trending Page\trending\node_modules\enhanced-resolve\lib\Resolver.js:519:5
    at eval (eval at create (C:\Users\afiqA\VSCode\Testing Trending Page\trending\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at C:\Users\afiqA\VSCode\Testing Trending Page\trending\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:89:43
    at C:\Users\afiqA\VSCode\Testing Trending Page\trending\node_modules\enhanced-resolve\lib\Resolver.js:519:5
    at eval (eval at create (C:\Users\afiqA\VSCode\Testing Trending Page\trending\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\Users\afiqA\VSCode\Testing Trending Page\trending\node_modules\enhanced-resolve\lib\Resolver.js:519:5

····

**Comment by yoyo837** [comment] 2023-07-20 02:54
> @afc163 你好， 我安装了 5.7.1 ver 后有以下报错， 请问该如何解决？
> 
> ···· ERROR in ./src/index.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/index.css) Module build failed (from ./node_modules/css-loader/dist/cjs.js): Error: Can't resolve '~antd/dist/antd.css' in 'C:\Users\afiqA\VSCode\Testing Trending Page\trending\src' at finishWithoutResolve (C:\Users\afiqA\VSCode\Testing Trending Page\trending\node_modules\enhanced-resolve\lib\Resolver.js:369:18) at C:\Users\afiqA\VSCode\Testing Trending Page\trending\node_modules\enhanced-resolve\lib\Resolver.js:461:15 at C:\Users\afiqA\VSCode\Testing Trending Page\trending\node_modules\enhanced-resolve\lib\Resolver.js:519:5 at eval (eval at create (C:\Users\afiqA\VSCode\Testing Trending Page\trending\node_modules\tapable\lib\HookCodeFactory.js:33:10), :16:1) at C:\Users\afiqA\VSCode\Testing Trending Page\trending\node_modules\enhanced-resolve\lib\Resolver.js:519:5 at eval (eval at create (C:\Users\afiqA\VSCode\Testing Trending Page\trending\node_modules\tapable\lib\HookCodeFactory.js:33:10), :27:1) at C:\Users\afiqA\VSCode\Testing Trending Page\trending\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:89:43 at C:\Users\afiqA\VSCode\Testing Trending Page\trending\node_modules\enhanced-resolve\lib\Resolver.js:519:5 at eval (eval at create (C:\Users\afiqA\VSCode\Testing Trending Page\trending\node_modules\tapable\lib\HookCodeFactory.js:33:10), :15:1) at C:\Users\afiqA\VSCode\Testing Trending Page\trending\node_modules\enhanced-resolve\lib\Resolver.js:519:5
> 
> ····

请看一下文档, 没有css文件了

**Comment by yuenzp** [comment] 2023-07-20 02:58
> 

检查过了， 我的antd 是从npm安装的。 我发现npm上的source file也缺少了css文件。

**Comment by yuenzp** [comment] 2023-07-20 02:59
@yoyo837 

检查过了， 我的antd 是从npm安装的。 我发现npm上的source file也缺少了css文件。

**Comment by yoyo837** [comment] 2023-07-20 03:05
前面讲过了, 资源里没有css文件了, 但是你还在引用css, 自然报错.

**Comment by yuenzp** [comment] 2023-07-20 03:11
那么从 4.24.12 升级 5.0 要做什么改动才能不再引用css?

**Comment by yoyo837** [comment] 2023-07-20 03:11
请看文档, 文档写了
