### ISSUE TITLE
form.resetFields不会触发dependencies的依赖

### ISSUE THREAD

**Issue by LiMuBai-ACE** [ant-design/ant-design#48898] opened 2024-05-13 10:40 UTC
### Reproduction link

[https://github.com/ant-design/ant-design/issues/31271](https://github.com/ant-design/ant-design/issues/31271)

### Steps to reproduce

https://github.com/ant-design/ant-design/issues/31271

### What is expected?

form.resetFields触发dependencies的依赖更新

### What is actually happening?

现在未能触发

| Environment | Info |
| --- | --- |
| antd | 4.24.6 |
| React | react |
| System | window |
| Browser | 谷歌 |

---
我在issues中看到有此问题，但好像并未修复，希望antd团队可以修复它

**Comment by afc163** [comment] 2024-05-14 01:36
Duplicate of #31271

**Closed by afc163** 2024-05-14 01:36 UTC
Labels: unconfirmed
