### ISSUE TITLE
DatePicker not using correct format

### ISSUE THREAD

**Issue by RickLucassen** [ant-design/ant-design#27198] opened 2020-10-16 13:46 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-9sk6u)

### Steps to reproduce
- Open reproduction
- Select date
- Date not presented in correct format

### What is expected?
Date formatted in expected format: D-M-YYYY as stated here: https://github.com/react-component/picker/blob/master/src/locale/nl_NL.ts

### What is actually happening?
Date not formatted as expected, default format is uses

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.14.0 |
| System | Ubuntu 20.04.1 |
| Browser | Chromium 85.0.4183.121 |

---
The default format is being used when the "format" property is not passed: https://github.com/react-component/picker/blob/master/src/utils/uiUtil.ts#L124 and https://github.com/react-component/picker/blob/master/src/Picker.tsx#L182

Previously in AntD 3 the format prop was sent to rc-picker: https://github.com/ant-design/ant-design/blob/3.x-stable/components/date-picker/createPicker.tsx#L193

But in AntD 4 this is not the case.

**Comment by afc163** [comment] 2020-10-17 04:22
Duplicate of #23902

**Closed by afc163** 2020-10-17 04:22 UTC
