### ISSUE TITLE
Prop on TreeSelect to display scrollbar permanently

### ISSUE THREAD

**Issue by aurelien-robineau** [ant-design/ant-design#29915] opened 2021-03-26 11:39 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I must display the scrollbar permanently on the tree select, and not only when I scroll, because I have users that don't understand that they must scroll. A simple prop to prevent the scrollbar from disappearing would be nice.

### What does the proposed API look like?
It would be a boolean props like so :
```
<TreeSelect alwaysDisplayScrollbar/>
```

**Comment by afc163** [comment] 2021-03-26 17:04
virtual={false}

**Comment by afc163** [comment] 2021-03-26 17:08
Duplicate of #28074

**Closed by afc163** 2021-03-26 17:08 UTC
