### ISSUE TITLE
Tour masking taking the scroll Event on the Safari Browser (Working fine on Chrome)

### ISSUE THREAD

**Issue by Upanshu07Sharma** [ant-design/ant-design#46774] opened 2024-01-03 10:14 UTC
### Reproduction link

[https://rqn2yj-3000.csb.app/](https://rqn2yj-3000.csb.app/)

### Steps to reproduce

step 1) : open the given link in Safari Browser. 
step 2): Start the tour on clicking Begin Tour button.
step 3): behind the tour's masking , scroll event is still active (only on Safari Browser.... working fine on Chrome)

Codesandbox link: https://codesandbox.io/p/devbox/rqn2yj
recording link google drive : [google drive video recording](https://drive.google.com/file/d/1ChcA-SIlRdl-YOCJIUHBWxQoUjg1PE6Q/view?usp=drive_link)

### What is expected?

Behind the tour's masking, scroll event should not be active. 
This issue is happening on Safari Browser. Working expected on Chrome.

### What is actually happening?

Behind the tour's masking, scroll event is  active so page is taking scroll event even behind the tour 's mask. 

| Environment | Info |
| --- | --- |
| antd | 5.12.7 |
| React | 18.2.0 |
| System | Macbook pro |
| Browser | Safari |

**Comment by MadCcc** [comment] 2024-01-03 11:25
Duplicate of https://github.com/ant-design/ant-design/issues/46679

**Closed by MadCcc** 2024-01-03 11:25 UTC
Labels: unconfirmed

**Comment by Upanshu07Sharma** [comment] 2024-01-03 11:42
- @MadCcc , this is not the duplicate of [#46679](https://github.com/ant-design/ant-design/issues/46679).
It is the separate one. please look into it.

Thanks
