### ISSUE TITLE
DatePicker如何在不设置值的情况下初始化界面定位到当前月和前一月,现在默认是当前月和后一月

### ISSUE THREAD

**Issue by xiangwanchun** [ant-design/ant-design#11977] opened 2018-08-31 03:10 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在大于当前日期被禁用的情况下,禁用的日期不能选择但又默认展现了出来.希望可以初始化定位到可选的日期范围内,免的多操作一步. 应用场景,统计日期筛选时,大于当前日期肯定是没有数据对的,所以需要禁用

### What does the proposed API look like?
希望提供一个 接收参数,可以控制初始化展现的日期

**Comment by afc163** [comment] 2018-09-02 06:40
You can try undocumented prop `defaultPickerValue`: https://codepen.io/afc163/pen/GXWygO?editors=0010

**Comment by afc163** [comment] 2018-09-02 06:40
Duplicate of #11148

**Closed by afc163** 2018-09-02 06:40 UTC

**Comment by springxiege** [comment] 2018-09-04 07:32
The prop defaultPickerValue doesn't work if setting the value or defaultValue
