### ISSUE TITLE
Message close callback not work with React 16

### ISSUE THREAD

**Issue by sowka1995** [ant-design/ant-design#40882] opened 2023-02-22 14:44 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-16-playground-forked-yffcnu?file=/src/index.js)

### Steps to reproduce

Click on blue button -> loading message will be closed after 1 second (works if hide callback is called before next message)

Click on red button -> loading message will not be closed after 1 second (hide callback is called after showing next message)

The problem occurs when using React v16 (16.4.0) but works in React 18.

### What is expected?

The message should disappear regardless of the order in which it was called.

### What is actually happening?

Message not disappear.

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 16.14.0 |
| System | Windows |
| Browser | Chrome/Edge chromium/Firefox |

---
The workaround is to change the hide callback order in whole application.
Hide callback from eg. message.loading should be called before any next message.info/success/error etc.

**Comment by afc163** [comment] 2023-02-24 10:22
Duplicate of #40332

**Closed by afc163** 2023-02-24 10:22 UTC
Labels: unconfirmed
