### ISSUE TITLE
Modal.config 支持配置 getContainer

### ISSUE THREAD

**Issue by wingsico** [ant-design/ant-design#29480] opened 2021-02-25 05:15 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决指令式使用 Modal 时正常挂载

### What does the proposed API look like?
```ts
Modal.config({
    getContainer: () => HTMLElement
})
```

**Comment by wingsico** [comment] 2021-02-25 05:16
补充说明：目前TS使用时没有相应的类型定义，仅有 rootPrefixCls
![image](https://user-images.githubusercontent.com/26498668/109106865-a21dcc80-776b-11eb-83b3-06138fdb2576.png)

**Comment by afc163** [comment] 2021-02-25 05:32
Duplicate of #23384

**Closed by afc163** 2021-02-25 05:32 UTC
