### ISSUE TITLE
Splitter 折叠展开后，宽度没有还原

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#51610] opened 2024-11-13 07:28 UTC
### Reproduction link

[https://ant-design.antgroup.com/components/splitter-cn#splitter-demo-multiple](https://ant-design.antgroup.com/components/splitter-cn#splitter-demo-multiple)

### Steps to reproduce

拖动之后折叠，然后展开

### What is expected?

展开之后的宽度恢复到拖动的地方

### What is actually happening?

宽度不正确

| Environment | Info |
| --- | --- |
| antd | 5.22.0 |
| React | latest |
| System | macOS |
| Browser | chrome |

https://github.com/user-attachments/assets/7f5bc37f-e8f4-434a-9350-14a4a3cae016

**Comment by afc163** [comment] 2024-11-14 01:54
Duplicate of #51152

**Closed by afc163** 2024-11-14 01:54 UTC
Labels: unconfirmed
