### ISSUE TITLE
官网文档页面v5版本的悬浮按钮回到顶部按钮显示异常

### ISSUE THREAD

**Issue by caichuanwang** [ant-design/ant-design#38835] opened 2022-11-22 02:41 UTC
### Reproduction link

[https://ant.design/components/float-button-cn](https://ant.design/components/float-button-cn)

### Steps to reproduce

1.正常打开悬浮按钮文档页面
2.页面下拉到底部

### What is expected?

正常表现

### What is actually happening?

1.正常打开时，返回顶部按钮不展示
2.页面下拉到底部，按钮消失

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 官网页面 |
| System | mac os |
| Browser | chrome 107.0.5304.110 |

---
官网文档页面

**Comment by MadCcc** [comment] 2022-11-22 02:43
Duplicate of https://github.com/ant-design/ant-design/issues/38769

**Closed by MadCcc** 2022-11-22 02:43 UTC
