### ISSUE TITLE
OnPressEnter, OnKeyPress for InputNumber and Autocomplete

### ISSUE THREAD

**Issue by genc6541** [ant-design/ant-design#16080] opened 2019-04-15 05:52 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/genc6541/pen/GLMxRb](https://codepen.io/genc6541/pen/GLMxRb)

### Steps to reproduce
Hello I could not implement onPressEnter or OnKeyPress events for InputNumber and AutoComplete. Why does not support this events? Is there any way achive use this events for InputNumber and AutoComplete components?

### What is expected?
onPressEnter or OnKeyPress should work for  InputNumber and AutoComplete

### What is actually happening?
Does not work

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | chrome  |

**Comment by ztplz** [comment] 2019-04-15 15:38
![image](https://user-images.githubusercontent.com/17755202/56145768-79f1ae00-5fd7-11e9-85d4-4942519a0111.png)
Seems your demo broken.

**Comment by afc163** [comment] 2019-04-22 03:11
Duplicate of #12476

**Closed by afc163** 2019-04-22 03:11 UTC
