### ISSUE TITLE
Individually imported components must not be dependent of `style/index.css` file

### ISSUE THREAD

**Issue by artuska** [ant-design/ant-design#18430] opened 2019-08-22 22:04 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This page

https://ng.ant.design/docs/getting-started/en#import-a-component-individually

tells that i have to include whole `index.css` file in order to use some component individually (i use Ant's DatePicker component)

```
@import "~ng-zorro-antd/style/index.min.css"; /* Import basic styles */
@import "~ng-zorro-antd/date-picker/style/index.min.css"; /* Import styles of the component */
```

Well, this is a complete overhead — `index.css` contains huge amount of useless styles which i don't want to use in my project, it contains a lot of normalize.css styles which i have to override back.

### What does the proposed API look like?
If i import a single component there must be a way not to import `index.css`.

What i did is just removed `index.css` from imports and wrote my own styles for some ant classes, so my DatePicker can work as expected:

```
.cdk-overlay-backdrop {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}

.cdk-overlay-container {
    position: absolute;
    top: 0;
    left: 0;
    z-index: 1000;
    width: 100%;
}

.cdk-overlay-pane {
    position: absolute;
}
```

In my case i managed `index.css` problem easy, but it may be not so easy in other cases.

**Comment by afc163** [comment] 2019-08-23 03:14
Duplicate of #9363

**Closed by afc163** 2019-08-23 03:14 UTC
