### ISSUE TITLE
TimePicker not scrolling on Modal

### ISSUE THREAD

**Issue by James2516** [ant-design/ant-design#7426] opened 2017-09-02 18:51 UTC
### Version
2.12.8

### Environment
Chrome v60, windows 10

### Reproduction link
https://codesandbox.io/s/6lol2kz3v3

### Steps to reproduce
When the modal is scrolled, the timepicker just stays on the same position instead of getting scrolled together with the other components.

### What is expected?
it should be repositioned

### What is actually happening?
it stays at the same spot when scrolled

**Comment by afc163** [comment] 2017-09-03 08:59
Duplicate of #7422

**Closed by afc163** 2017-09-03 08:59 UTC

**Comment by afc163** [comment] 2017-09-03 09:00
Try `getPopupContainer`

https://github.com/ant-design/ant-design/issues/3438
