### ISSUE TITLE
TimePicker Popup use12Hours AM and PM labels are not covered by internationalization

### ISSUE THREAD

**Issue by bertanyaman** [ant-design/ant-design#35655] opened 2022-05-20 08:00 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/locale-antd-4-20-5-forked-1kq08d)

### Steps to reproduce

Select any language by radio list that created top of example.
Open TimePicker Popup to change value.

### What is expected?

AM and PM labels must change by language

### What is actually happening?

AM and PM labels are not changing by language

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | 16.14.0 |
| System | 21H2 Windows 11 |
| Browser | 101.0.4951.67 Google Chrome |

**Comment by afc163** [comment] 2022-05-20 11:48
Duplicate of #31520

**Closed by afc163** 2022-05-20 11:48 UTC
