### ISSUE TITLE
使用next.js构建项目的时候inlineCollapsed为underfined

### ISSUE THREAD

**Issue by houko** [ant-design/ant-design#16474] opened 2019-05-08 07:16 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/xueshi-tld/hzxueshi](https://github.com/xueshi-tld/hzxueshi)

### Steps to reproduce
1. yarn build
2. yarn start

### What is expected?
正常运行

### What is actually happening?
TypeError: Cannot read property 'inlineCollapsed' of undefined

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | 16.8.6 |
| System | win10 |
| Browser | chrome73.0.3683.103 |

---
TypeError: Cannot read property 'inlineCollapsed' of undefined
    at Object.children (E:\react-workspace\hzxueshi\node_modules\antd\lib\menu\MenuItem.js:87:37)
    at a.render (E:\react-workspace\hzxueshi\node_modules\react-dom\cjs\react-dom-server.nod
e.production.min.js:44:64)
    at a.read (E:\react-workspace\hzxueshi\node_modules\react-dom\cjs\react-dom-server.node.
production.min.js:41:58)
    at renderToString (E:\react-workspace\hzxueshi\node_modules\react-dom\cjs\react-dom-serv
er.node.production.min.js:53:83)
    at render (E:\react-workspace\hzxueshi\node_modules\next-server\dist\server\render.js:86
:16)

**Comment by zombieJ** [comment] 2019-05-08 15:02
Duplicate of #16473

**Closed by zombieJ** 2019-05-08 15:02 UTC
