### ISSUE TITLE
ant design 组件文档 国内镜像 select 的文档页变成404了

### ISSUE THREAD

**Issue by Uaivg** [ant-design/ant-design#28922] opened 2021-01-19 08:59 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/select-cn/](https://ant-design.gitee.io/components/select-cn/)

### Steps to reproduce
问题时间：2021-01-19 16:57

### What is expected?
恢复网页

### What is actually happening?
.

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | . |
| System | win10 1909 |
| Browser | Google Chrome 87.0.4280.141 |

**Comment by Uaivg** [comment] 2021-01-19 09:01
现在恢复了...

**Comment by yoyo837** [comment] 2021-01-19 09:01
Duplicate of #28921

**Closed by yoyo837** 2021-01-19 09:01 UTC
