### ISSUE TITLE
ant Tabs component seems has a performance issues

### ISSUE THREAD

**Issue by PleaseTryAgain** [ant-design/ant-design#20025] opened 2019-12-01 07:49 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
严重性能问题

### What does the proposed API look like?
流畅运行

**Comment by afc163** [comment] 2019-12-01 07:50
Duplicate of #20003

**Closed by afc163** 2019-12-01 07:50 UTC
