### ISSUE TITLE
table scroll "x: max-content" is invalid when y is filled (填写y后x: max-content失效)

### ISSUE THREAD

**Issue by huangkaibo** [ant-design/ant-design#29562] opened 2021-03-01 11:33 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rx8jb?file=/index.js)

### Steps to reproduce
1. 注释掉y:300, 效果正常, 每一列都刚好显示完全
2. 恢复y:300, Name列显示过长, 后两列表头显示不完全

### What is expected?
每一列都刚好显示完全

### What is actually happening?
Name列显示过长, 后两列表头显示不完全

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | 17.0.1 |
| System | windows 10 |
| Browser | chrome 88.0.705.81 |

**Comment by afc163** [comment] 2021-03-02 00:30
Duplicate of #29283

**Closed by afc163** 2021-03-02 00:30 UTC
