### ISSUE TITLE
Calendar components now support year and month handover, can you add the operation of "day" and "week"?

### ISSUE THREAD

**Issue by czf0321** [ant-design/ant-design#10279] opened 2018-04-27 06:31 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Display schedule by week or day
for example: http://intljusticemission.github.io/react-big-calendar/examples/index.html

### What does the proposed API look like?
Which panels can I configure to display, such as days, weeks, months, and years

**Comment by afc163** [comment] 2018-04-28 07:29
Duplicate of #8024

**Closed by afc163** 2018-04-28 07:29 UTC
Labels: Component: Calendar, Feature Request
