### ISSUE TITLE
Cascader级联选择在全选时，能否不收起子项

### ISSUE THREAD

**Issue by chenxianfei** [ant-design/ant-design#34359] opened 2022-03-08 06:28 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Cascader级联选择在全选时，现在默认不显示子项，只显示全新的父项，能否显示子项

### What does the proposed API look like?
显示子项

**Comment by zombieJ** [comment] 2022-03-08 06:38
Duplicate of #34193

**Closed by zombieJ** 2022-03-08 06:38 UTC
