### ISSUE TITLE
Datepicker: Missing `showWeekNumbers` Attribute

### ISSUE THREAD

**Issue by sellalone** [ant-design/ant-design#44949] opened 2023-09-19 10:23 UTC
### What problem does this feature solve?

I expect the Ant Design **Datepicker** component to have an attribute called **showWeekNumbers** that allows users to display week numbers alongside the date selection without automatically selecting the whole week.

### What does the proposed API look like?

I propose adding a new attribute showWeekNumbers to the Datepicker component, which can be set to **true** or **false** depending on whether the user wants to display week numbers alongside date selection.

````
<DatePicker
   picker="date"
   format="YYYY-MM-DD HH:mm"
   showTime
   showNow={false}
   showWeekNumbers={true}
/>
````

### Issue Reference
This issue is related to [react-component/picker#326](https://github.com/react-component/picker/pull/326).

**Comment by afc163** [comment] 2023-09-20 08:57
Duplicate of #21726

**Closed by afc163** 2023-09-20 08:57 UTC
Labels: unconfirmed

**Comment by afc163** [comment] 2023-09-20 08:58
https://github.com/react-component/picker/pull/326 contains conflict and the author didn't respond.
