### ISSUE TITLE
Button 在 React.StrictMode 模式下，控制台报警告

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#23282] opened 2020-04-15 07:17 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/anniuleixing-ant-design-demo-r9xkz?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
React.StrictMode 模式下 Button 组件控制台报警告

### What is expected?
React.StrictMode 模式下 Button 组件控制台不报警告

### What is actually happening?
React.StrictMode 模式下 Button 组件控制台报警告

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | latest |
| System | win10 |
| Browser | chrome80 |

**Comment by afc163** [comment] 2020-04-15 07:19
Duplicate of #22493

**Closed by afc163** 2020-04-15 07:19 UTC
