### ISSUE TITLE
antd.variable.css 中重复定义 --ant-primary-color

### ISSUE THREAD

**Issue by buquan** [ant-design/ant-design#36893] opened 2022-08-04 08:27 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/awesome-easley-kcui6u?file=/src/App.js )

### Steps to reproduce

antd.variable.css 中重复定义 --ant-primary-color , antd.variable.css  查找--ant-primary-color:  出现 66次， 全量引入该css到页面中，审查元素html 发现大量被覆盖

### What is expected?

html元素不会有大量被覆盖无效的--ant-primary-color

### What is actually happening?

html元素有大量被覆盖无效的--ant-primary-color

| Environment | Info |
| --- | --- |
| antd | 4.22.3 |
| React | 18.0.0 |
| System | macos |
| Browser | chrome 103.0.5060.134 |

**Comment by zombieJ** [comment] 2022-08-04 08:34
Duplicate of #32529

**Closed by zombieJ** 2022-08-04 08:34 UTC
