### ISSUE TITLE
Form 组件 submit 提交出现闪屏

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design#36594] opened 2022-07-19 10:58 UTC
### Reproduction link

[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce

第一个示例 多刷新几次提交 就会出现闪屏

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | React 18.2.0 |
| System | Windows |
| Browser | Chrome 103 |

**Comment by afc163** [comment] 2022-07-19 11:00
Duplicate of https://github.com/ant-design/ant-design/issues/36470

**Closed by afc163** 2022-07-19 11:00 UTC
