### ISSUE TITLE
Upload support Chunked file

### ISSUE THREAD

**Issue by anlia260** [ant-design/ant-design#8676] opened 2017-12-20 07:41 UTC
### What problem does this feature solve?
上传组件支持切片上传

### What does the proposed API look like?
 maxChunkSize: 10000000 // 10 MB

**Comment by yesmeck** [comment] 2017-12-21 01:52
Duplicate of #6026

或者自己通过  `customRequest` 实现。

**Closed by yesmeck** 2017-12-21 01:52 UTC
