### ISSUE TITLE
Range Picker: Impossible to edit start date in Safari browser

### ISSUE THREAD

**Issue by ashypelskyi** [ant-design/ant-design#19228] opened 2019-10-15 09:55 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker/#components-date-picker-demo-format](https://ant.design/components/date-picker/#components-date-picker-demo-format)

### Steps to reproduce
1. Click on Range Picker;
2. Try to edit start time, in the top left corner, manually

### What is expected?
Ability to edit pre-set date

### What is actually happening?
Impossible to edit pre-set date

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 16.10.2 |
| System | OS X EL Capitan v10.11.6 |
| Browser | Safari 11.1.2(11605.3.8.1) |

---
This bug reproduces even if a date was not set on startup. Even when user choose the date, later they will not be able to edit the start date manually.

**Comment by afc163** [comment] 2019-10-15 11:26
Duplicate of #11957

**Closed by afc163** 2019-10-15 11:26 UTC
