### ISSUE TITLE
How to disable form submit button when there are form errors(v4)

### ISSUE THREAD

**Issue by debotos** [ant-design/ant-design#23887] opened 2020-05-05 14:48 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to disable form submit button but in v4 I am not able to do it in v3 I was able to do it.

### What does the proposed API look like?
There should be some kind of flag to identify.

**Comment by yoyo837** [comment] 2020-05-06 02:19
In this respect, there seems to be no difference between v3 and v4. How do you do it in the v3 version?

**Comment by afc163** [comment] 2020-05-06 02:39
Duplicate of #21439

#4374

**Closed by afc163** 2020-05-06 02:39 UTC
