### ISSUE TITLE
Need to make scroll bar visible. Right now its fading away if we take the cursor away from dropdown list.

### ISSUE THREAD

**Issue by harneet2690** [ant-design/ant-design#31364] opened 2021-07-12 14:26 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-tuemte](https://stackblitz.com/edit/react-tuemte)

### Steps to reproduce
Issue with Antd->Select-->Responsive maxTagCount

1. Click on inputbox, list will be open up make sure you have 20  records.
2. now take your cursor away from dropdown list (dnt click just take ur cursor away wait for 3 seconds)
3. You will see the scroll bar will fade away.

### What is expected?
Considering the above step.

Ideally scroll bar shouldnt fade away even if we take away the cursor from the dropdown list.
Say user search in the input box(eg box) and according the data get filters in the llist and gives you 15 records. So as a end user if wldnt be able make to if there is more content as scroll bar fade away.
So ideally scrollbar shldnt fade away.

### What is actually happening?
scrollbar is fading away and end user not able to find out if there is more content to scroll 

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome Version 91.0.4472.124 |

**Comment by afc163** [comment] 2021-07-13 01:25
Duplicate of #28074

**Closed by afc163** 2021-07-13 01:25 UTC
