### ISSUE TITLE
Allow an option for values to be set/obtained in ISO string format

### ISSUE THREAD

**Issue by bear-bibeault** [ant-design/ant-design#31707] opened 2021-08-07 05:07 UTC
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, values to and from the DatePicker are moment.js instances. As moment.js has been sun-setted, it would be great if code using the DatePicker did not have to import and use moment.js (even if DatePicker uses it internally).
Using ISO strings, code using the DatePicker would be free to use any date handling package (e.g. Luxon) or none at all.
For backward compatibility, this could be an option on the DatePicker as to not break any existing code.

### What does the proposed API look like?
Perhaps an option 'useISOString' on the DatePicker, and the affordance for values to be set/obtained using ISO strings.

**Comment by afc163** [comment] 2021-08-08 05:12
Duplicate of #26759

**Closed by afc163** 2021-08-08 05:12 UTC
