### ISSUE TITLE
DropDown Menu console error and layout dysfunction after update to 4.16.5

### ISSUE THREAD

**Issue by behuf** [ant-design/ant-design#31161] opened 2021-06-28 08:00 UTC
![image](https://user-images.githubusercontent.com/2044858/123601084-8c8ee100-d7f7-11eb-9fc3-8bb0146f0646.png)

![image](https://user-images.githubusercontent.com/2044858/123601178-a9c3af80-d7f7-11eb-87fb-aee91127e2fa.png)

- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-j4w67?file=/index.js)

### Steps to reproduce
nothing special. a simple dropdown menu with itemGroup and dropdownable

### What is expected?
the warning inside the console. and my layout is not correct 

### What is actually happening?
the warning inside the console. and my layout is not correct 

| Environment | Info |
|---|---|
| antd | 4.16.5 |
| React | react  |
| System | windows & nodejs  |
| Browser | chrome@latest |

**Comment by afc163** [comment] 2021-06-28 10:14
Duplicate of #31025

**Closed by afc163** 2021-06-28 10:14 UTC
