### ISSUE TITLE
dropdown中使用menu组件点击一次menuItem会触发两次click

### ISSUE THREAD

**Issue by sbyps** [ant-design/ant-design#10375] opened 2018-05-05 04:36 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.0

### Environment
win7, chrome 61.0.3163.100

### Reproduction link
[https://ant.design/components/dropdown-cn/#components-dropdown-demo-dropdown-button](https://ant.design/components/dropdown-cn/#components-dropdown-demo-dropdown-button)

### Steps to reproduce
参考官网链接示例 控制台log
click {key: "1", keyPath: Array(1), item: t, domEvent: n}
demo.js:1 click n {dispatchConfig: {…}, _targetInst: Yn, nativeEvent: MouseEvent, type: "click", target: li.ant-dropdown-menu-item.ant-dropdown-menu-item-active, …}

### What is expected?
修复bug

### What is actually happening?
setState报错，第二次没有key值了，使得各种组件都报错了

**Comment by yesmeck** [comment] 2018-05-05 04:49
https://github.com/react-component/menu/pull/140

**Comment by afc163** [comment] 2018-05-05 05:11
Duplicate of #10368

**Comment by yesmeck** [comment] 2018-05-07 08:01
Should be fixed in `rc-menu@7.0.3`

**Closed by yesmeck** 2018-05-07 08:01 UTC
