### ISSUE TITLE
Allow table column to be resizable

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#42153] opened 2023-05-05 04:24 UTC
### What problem does this feature solve?

This request will allow table columns to be resized to allow viewing of large column

### What does the proposed API look like?

add additional prop resizable: false/true to individual column to enable resizing

**Comment by afc163** [comment] 2023-05-05 05:51
Duplicate of https://github.com/ant-design/ant-design/issues/32811

**Closed by afc163** 2023-05-05 05:51 UTC
Labels: unconfirmed
