### ISSUE TITLE
Modal 限制最大内容高度

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design#11359] opened 2018-07-19 09:26 UTC
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
相关的：#5777、#10885

Madal内容较多的如果写死高度，则无法高效利用大分辨率的空间，只能自己手动加样式控制，能否默认提供类似100vh减去Modal的header和footer后高度空间来支持滚动？

### What does the proposed API look like?
添加最大内容滚动区域默认样式。

**Comment by yoyo837** [comment] 2018-07-19 09:34
并且如果高度上有必要，比如底部超出可见区域，top按Modal纵向剧中计算

**Comment by yesmeck** [comment] 2018-07-20 05:45
Duplicate of #5777

**Closed by yesmeck** 2018-07-20 05:45 UTC
