### ISSUE TITLE
hasFeedback and validateStatus not working when importing controls directly from antd/lib/...

### ISSUE THREAD

**Issue by sparrowek** [ant-design/ant-design#50072] opened 2024-07-25 10:10 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/customized-validation-antd-4-24-16-forked-dr5t4r?file=%2Fdemo.tsx%3A22%2C1)

### Steps to reproduce

import React from "react";
import "antd/dist/antd.css";
import { Form, Input } from "antd";
import { default as Input2 } from "antd/lib/input";

const App: React.FC = () => (
  <>
    <Form.Item hasFeedback validateStatus="error" help="error icon showing">
      <Input />
    </Form.Item>
    <Form.Item
      hasFeedback
      validateStatus="error"
      help="error icon and border not showing"
    >
      <Input2 />
    </Form.Item>
  </>
);

export default App;

### What is expected?

feedback icon and border should be shown not matter if we import ant controls from the barrel file "antd" or "antd/lib/input"

### What is actually happening?

When importing ant controls from "antd/lib/input" feedback icon is not shown but when importing from "antd" everything is working correctly.

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 18 |
| System | Windows |
| Browser | Firefox |

**Comment by afc163** [comment] 2024-07-25 10:59
Duplicate of https://github.com/ant-design/ant-design/issues/50073

**Closed by afc163** 2024-07-25 10:59 UTC
Labels: unconfirmed
