### ISSUE TITLE
tree select 开启虚拟渲染，能否滚动到指定位置呢，或者指定item？

### ISSUE THREAD

**Issue by hnsylitao** [ant-design/ant-design#24240] opened 2020-05-18 03:47 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
tree select 滚动到指定位置

### What does the proposed API look like?
scrollTo

**Comment by afc163** [comment] 2020-05-18 04:23
Duplicate of #24240

**Closed by afc163** 2020-05-18 04:23 UTC

**Comment by hnsylitao** [comment] 2020-05-18 06:15
可能是我搜索方式的问题，还是没找到有什么人解决过这个问题。

**Comment by afc163** [comment] 2020-05-18 06:16
我打错了，应该是 Duplicate of #23094

**Comment by atzcl** [comment] 2020-11-16 03:39
@afc163 TreeSelect 并没有暴露出 scrollTo 方法吧？
