### ISSUE TITLE
Virtual Table component layout broken on few scenarios

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#44745] opened 2023-09-10 21:37 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/virtual-list-antd-5-9-0-forked-ndmggl?file=/demo.tsx)

### Steps to reproduce

Create a virtual table and set the size. The table content is misaligned with the header

Layout is not working for the following scenarios:
1. on screen resize 

https://github.com/ant-design/ant-design/assets/52765572/9687d7e3-3278-4507-8978-6793f14878c4

2. When scroll.x is set to 'fit-content', when screen size is adjusted to smaller screen. Scroll x doesnt reveal all the columns
3. When size is specified e.g 'small' or 'middle'

### What is expected?

Layout should be aligned

### What is actually happening?

Layout is not aligned

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 18.2 |
| System | web |
| Browser | chrome |

**Comment by AsuraKev** [comment] 2023-09-10 22:03
Also without setting width on each column gives me this ..

![image](https://github.com/ant-design/ant-design/assets/52765572/078a5e9c-9845-42ce-9da6-15e308ffe9db)

**Comment by zombieJ** [comment] 2023-09-11 02:13
Your reproduce is default one which not preset your description.

**Comment by AsuraKev** [comment] 2023-09-11 03:53
Updated link for scenario: specifying table size

https://codesandbox.io/s/virtual-list-antd-5-9-0-forked-ndmggl?file=/demo.tsx

**Comment by zombieJ** [comment] 2023-09-12 07:21
What's the reproduce step of the codesandbox?

**Comment by 1123612483** [comment] 2023-09-12 07:54
Same issues. #44785

**Comment by zombieJ** [comment] 2023-09-13 06:21
> What's the reproduce step of the codesandbox?

pls provide more info about this issue

**Comment by AsuraKev** [comment] 2023-09-13 06:25
@zombieJ the issue of this reproduce https://codesandbox.io/s/virtual-list-antd-5-9-0-forked-ndmggl?file=/demo.tsx is that table content is not aligned with table header when you specified the size

**Comment by yoyo837** [comment] 2023-10-11 09:55
Duplicate of #44889

**Closed by yoyo837** 2023-10-11 09:55 UTC
