### ISSUE TITLE
Popover: wrong position while scrolling inner element instead of <body>

### ISSUE THREAD

**Issue by hojovi** [ant-design/ant-design#14830] opened 2019-02-14 03:59 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j1v892n289)

### Steps to reproduce
1. set body style "overflow: hidden";
2. add a <div> element with "overflow: scroll" and "height:100%";
3. add a <div> element in 1st <div> with sufficiently large height;
4. add a "Popover" component in 2nd div;
3. click the button in "Popover" and scroll page;

### What is expected?
the popover should be around it's child element while scrolling

### What is actually happening?
the popover isn't around it's child element

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | latest |
| System | Windows 10 |
| Browser | Chrome / Version 71.0.3578.98 |

**Comment by afc163** [comment] 2019-02-14 04:10
Duplicate of #3487

**Closed by afc163** 2019-02-14 04:10 UTC

**Comment by AbdulRayhman** [comment] 2019-02-14 14:17
modify .ant-popover{
  z-index: 0;
}
hope this resolve your issue.

**Comment by shivakantshukla55** [comment] 2021-02-19 12:04
Use <Select getPopupContainer={trigger => trigger.parentElement}>  to render a component inside the scroll area. If you need to config this globally in your application, try <ConfigProvider getPopupContainer={trigger => trigger.parentElement}> 

And make sure that parentElement is position: relative or position: absolute.

Reference:
[https://ant.design/docs/react/faq](url)
[https://codesandbox.io/s/4j168r7jw0?file=/index.js](url)

**Comment by katekostina** [comment] 2021-11-02 14:11
`<Popover getPopupContainer={trigger => trigger.parentElement}>`
Worked for me.

**Comment by AhmedRazaVerge** [comment] 2021-11-16 12:47
> `<Popover getPopupContainer={trigger => trigger.parentElement}>` Worked for me.

amazing
