### ISSUE TITLE
onChange in DatePicker keeps after Ok button.

### ISSUE THREAD

**Issue by Dradisen** [ant-design/ant-design#29253] opened 2021-02-05 11:06 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-99dmo?file=/index.js)

### Steps to reproduce
1) click on date input. Open panel
2) choose any day.
3) leave from date panel. click mouse any area except panel.

### What is expected?
I expecting what onChange work after any choose days in panel including button ok or do various  onChange for them actions.

### What is actually happening?
We look what onChange not work and not saving state in input until press button "ok" in footer

| Environment | Info |
|---|---|
| antd | 4.12.2 |
| React | 16.14.0 |
| System | Windows 10 |
| Browser | Google Chrome 88 |

**Comment by afc163** [comment] 2021-02-05 16:01
Try `onCalendarChange` instead.

**Comment by afc163** [comment] 2021-02-05 16:01
Duplicate of #21189

**Closed by afc163** 2021-02-05 16:01 UTC

**Comment by lian8306** [comment] 2021-02-19 07:21
> Duplicate of #27779

singlepicker没有这个事件
