### ISSUE TITLE
Select in multiple mode unmount clean up needed

### ISSUE THREAD

**Issue by thejasonxie** [ant-design/ant-design#46348] opened 2023-12-09 07:54 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/funny-hopper-zd2lv8?file=%2Fsrc%2FApp.js%3A19%2C14&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpxqlupr00062e67is45okos%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpxqlupr00022e6725ipvxmn%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpxqlupr00032e67tbkvtkgp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpxqlupr00052e67v2rqn7iv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpxqlupr00022e6725ipvxmn%2522%253A%257B%2522id%2522%253A%2522clpxqlupr00022e6725ipvxmn%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpxqzs9500022e67k1isx9eg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A19%252C%2522startColumn%2522%253A14%252C%2522endLineNumber%2522%253A19%252C%2522endColumn%2522%253A14%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpxqzs9500022e67k1isx9eg%2522%257D%252C%2522clpxqlupr00052e67v2rqn7iv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpxqlupr00042e672yxjy7eq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clpxqlupr00052e67v2rqn7iv%2522%252C%2522activeTabId%2522%253A%2522clpxqlupr00042e672yxjy7eq%2522%257D%252C%2522clpxqlupr00032e67tbkvtkgp%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpxqlupr00032e67tbkvtkgp%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. Use Select component with mode set to multiple
2. Mount and un-mount this component to see clean up error in console.

### What is expected?

Component's dependencies clean up properly when un-mounting

### What is actually happening?

Component's dependencies is not cleaning up properly when un-mounting

| Environment | Info |
| --- | --- |
| antd | 4.24.15 |
| React | 17.x |
| System | mac |
| Browser | firefox |

---
The Select component uses [@react-component/rc-select](https://github.com/react-component/select) which uses [@react-component/rc-overflow](https://github.com/react-component/overflow) which is the source of this bug. This occurs in react v17 not v18.

![antd](https://github.com/ant-design/ant-design/assets/34463193/e2cf2aca-8687-4942-8b03-4507bb2042d1)

**Comment by yoyo837** [comment] 2023-12-09 08:00
Duplicate of #45556, #44994

**Closed** 2023-12-09 08:02 UTC
Labels: unconfirmed

**Comment by Monisha-Muralidharan** [comment] 2024-05-02 10:30
I am using latest version of react. But still I am facing "the state update after component unmounted error" when using select component with mode as "multiple"/ "tags"

**Comment by thejasonxie** [comment] 2024-05-02 19:31
> I am using latest version of react. But still I am facing "the state update after component unmounted error" when using select component with mode as "multiple"/ "tags"

@Monisha-Muralidharan, You should open up a new issue in that case. Probably won't be addressed here because this issue is closed.
