### ISSUE TITLE
<Pagination> 渲染异常, 出现中文汉字 "五"

### ISSUE THREAD

**Issue by 16slowly** [ant-design/ant-design#12926] opened 2018-11-01 12:43 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.3

### Environment
Goole Chrome 70.0.3538.77 (Mac OS 64 位正式版本)

### Reproduction link
[http://vivedu-web.oss-cn-beijing.aliyuncs.com/wechat/WX20181101-203526%402x.png](http://vivedu-web.oss-cn-beijing.aliyuncs.com/wechat/WX20181101-203526%402x.png)

### Steps to reproduce
根据 API 调用 `<Pagination>` 组件，传入的参数均符合规定

### What is expected?
所有页码为阿拉伯数字

### What is actually happening?
![Pagination 出现汉字"五"](http://vivedu-web.oss-cn-beijing.aliyuncs.com/wechat/WX20181101-203526%402x.png)

**Comment by zombieJ** [comment] 2018-11-01 14:22
duplicate of #12925

**Closed by zombieJ** 2018-11-01 14:22 UTC
