### ISSUE TITLE
增加一个Spliter组件

### ISSUE THREAD

**Issue by noopn** [ant-design/ant-design#48349] opened 2024-04-09 03:22 UTC
### What problem does this feature solve?

解决常见上下或左右布局时，需要调整大小的需求

### What does the proposed API look like?

```
<Spliter>
   <Spliter.Left>
    <Spliter.Right>
      <Spliter>
          <Spliter.Top>
          <Spliter.Bottom>
        </Spliter>
    /Spliter.Right>
</Spliter>
```

**Comment by Wxh16144** [comment] 2024-04-09 03:27
Duplicate of #44525

**Closed** 2024-04-09 03:28 UTC
Labels: unconfirmed

**Comment by afc163** [comment] 2024-09-24 02:14
Supported in https://github.com/ant-design/ant-design/pull/50038
