### ISSUE TITLE
Cannot find `CascaderOptionType` and `CascaderValueType` type declare

### ISSUE THREAD

**Issue by hippo2cat** [ant-design/ant-design#33203] opened 2021-12-08 04:16 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/hippo2cat/antd-cascader-type-issue-reproduce](https://github.com/hippo2cat/antd-cascader-type-issue-reproduce)

### Steps to reproduce
upgrade antd version from 4.16.1 to 4.17.2, then you can't find `CascaderOptionType` and `CascaderValueType` type declares.

### What is expected?
need these type declares

### What is actually happening?
can't find them

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | windows 10 |
| Browser | chrome94 |

**Comment by hippo2cat** [comment] 2021-12-10 02:16
added reproduce

**Comment by baitun** [comment] 2021-12-12 12:32
I have the same problem.  
Looks like issue was introduced in https://github.com/ant-design/ant-design/pull/31936

**Comment by afc163** [comment] 2021-12-15 13:38
Duplicate of #33153

**Closed by afc163** 2021-12-15 13:38 UTC
Labels: 🤔 Need Reproduce
