### ISSUE TITLE
Deprecation warnings logged on error level

### ISSUE THREAD

**Issue by mkorpela** [ant-design/ant-design#38211] opened 2022-10-25 14:08 UTC
### Reproduction link

NOPE

### Steps to reproduce

Run <Modal visible={true} ..>
=> console.error: Warning: [antd: Modal] `visible` will be removed in next major version, please use `open` instead.

### What is expected?

console.warning

### What is actually happening?

console.error

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | React 18 |
| System | Internet |
| Browser | Chrome |

---
Our tests fail if any errors on the console. Please don't log on error level warnings.

**Comment by mkorpela** [comment] 2022-10-25 14:11
[afc163](https://github.com/afc163) Please don't do this.

**Comment by mkorpela** [comment] 2022-10-25 14:13
https://github.com/facebook/fbjs/pull/94#issuecomment-168332326 I see that there is this discussion but this is really unexpected.

**Comment by zombieJ** [comment] 2022-10-25 14:16
> [facebook/fbjs#94 (comment)](https://github.com/facebook/fbjs/pull/94#issuecomment-168332326) I see that there is this discussion but this is really unexpected.

As refed. antd follow the React warning style with console.error. Maybe it can do some hack on ConfigProvider to reduce warning level. Just a think but not a promise.

**Comment by afc163** [comment] 2022-10-25 15:00
Duplicate of #37764

**Closed by afc163** 2022-10-25 15:00 UTC

**Comment by mkorpela** [comment] 2022-11-07 14:12
@afc163 could you re-consider?
