### ISSUE TITLE
使用Typescript自定义Form组件，编译时类型错误

### ISSUE THREAD

**Issue by wz57c** [ant-design/ant-design#16302] opened 2019-04-25 07:48 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2zl3x0k5xr)

### Steps to reproduce
Form.create<StepFormProps>()(StepForm);

### What is expected?
不报错

### What is actually happening?
Form.create<StepFormProps>()(StepForm); 执行时不会报错，但是编译时会报错
编译报错：

Argument of type 'typeof StepForm' is not assignable to parameter of type 'ComponentType<{}>'.
  Type 'typeof StepForm' is not assignable to type 'ComponentClass<{}, any>'.
    Types of parameters 'props' and 'props' are incompatible.
      Type '{}' is missing the following properties from type 'Readonly<StepFormProps>': form, steps, onSubmit

Form.create<StepFormProps>()(StepForm as any); 执行时会报错，但是编译时不会报错
执行报错：

 TS2322: Type '{ steps: any; option: any; formData: any; onSubmit: (values?: any) => any; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<RcBaseFormProps & Pick<FormComponentProps, never>, any, any>> & Readonly<RcBaseFormProps & Pick<FormComponentProps, never>> & Readonly<...>'.  Property 'steps' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<RcBaseFormProps & Pick<FormComponentProps, never>, any, any>> & Readonly<RcBaseFormProps & Pick<FormComponentProps, never>> & Readonly<...>'.

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | 16.7.0 |
| System | mac os |
| Browser | Chrome 73.0.3683.103 |

**Comment by zombieJ** [comment] 2019-04-25 08:10
Duplicate of #16284

**Closed by zombieJ** 2019-04-25 08:10 UTC
