### ISSUE TITLE
Table中关于rowSelection配置问题，通过renderCell定义选择框，无法控制全选按钮样式的问题

### ISSUE THREAD

**Issue by xjingmo** [ant-design/ant-design#33192] opened 2021-12-07 11:49 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用户可以自己定义全选框的样式，以及是否渲染全选框

### What does the proposed API look like?
```javascript
/**
@param {boolean} checkedAll 当前是否全选
@param {React.ReactNode} orgininNode 原有节点 
*/
const renderSelectAllCell = (checkedAll:boolean,originNode:React.ReactNode)=>(originNode);
```

**Comment by afc163** [comment] 2021-12-07 12:00
Duplicate of #33176

**Closed by afc163** 2021-12-07 12:00 UTC
