### ISSUE TITLE
Yarn install generates warning about incorrect peer dependency for @ant-design/icons-react

### ISSUE THREAD

**Issue by pdeva** [ant-design/ant-design#15798] opened 2019-04-01 20:44 UTC
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://yarnpkg.com](https://yarnpkg.com)

### Steps to reproduce
include dependency to antd in `package.json` and run `yarn install`

### What is expected?
no warning

### What is actually happening?
Yarn shows this warning:  

warning "antd > @ant-design/icons-react@1.1.2" has incorrect peer dependency "@ant-design/icons@~1.1.0".

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | chrome  |

**Comment by Maktel** [comment] 2019-04-02 07:54
https://github.com/ant-design/ant-design/issues/15277
https://github.com/ant-design/ant-design-icons/issues/51

**Comment by zombieJ** [comment] 2019-04-02 08:59
Duplicate of #15277

**Closed by zombieJ** 2019-04-02 08:59 UTC
