### ISSUE TITLE
Upload Pictures Wall Drag To Order

### ISSUE THREAD

**Issue by canyanolGitHub** [ant-design/ant-design#17794] opened 2019-07-22 10:19 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Upload Pictures Wall Drag To Order

### What does the proposed API look like?
Upload Pictures Wall Drag To Order

**Comment by afc163** [comment] 2019-07-22 10:24
Duplicate of #8387

**Closed by afc163** 2019-07-22 10:24 UTC
