### ISSUE TITLE
small table 表头分组边框问题

### ISSUE THREAD

**Issue by theDoinb** [ant-design/ant-design#18846] opened 2019-09-17 02:51 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/compassionate-hoover-oog54)

### Steps to reproduce
合并表头，右侧加入某列

### What is expected?
边框是完整的

### What is actually happening?
合并表头右下侧边框消失

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.4.1 |
| System | win10 |
| Browser | 谷歌浏览器 |

**Comment by afc163** [comment] 2019-09-17 02:55
duplicate of ##18762, fixed in #18821

**Closed by afc163** 2019-09-17 02:55 UTC
