### ISSUE TITLE
When the parent element is scaled with scale, the select menu will be offset（父级元素使用scale缩放，会导致select菜单偏移）

### ISSUE THREAD

**Issue by sakurahe** [ant-design/ant-design#25879] opened 2020-07-29 05:41 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-fidsr8-1gqkuj?file=index.js](https://stackblitz.com/edit/react-fidsr8-1gqkuj?file=index.js)

### Steps to reproduce
Click on the selection box

### What is expected?
The drop-down menu is in the correct position（下拉菜单位置正确）

### What is actually happening?
Position offset

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 16.12.0 |
| System | macOS 10.15.5 |
| Browser | Chrome（版本 84.0.4147.89） |

---
[#20368](https://github.com/ant-design/ant-design/issues/20368) The issue mentioned this problem, but there was no solution or response in the end
（这个issue提到了这个问题，但最后没有解决方法）

**Comment by afc163** [comment] 2020-07-29 05:54
Duplicate of #20368

**Closed by afc163** 2020-07-29 05:54 UTC

**Comment by afc163** [comment] 2020-11-13 05:44
Duplicate of #26681
