### ISSUE TITLE
<Select> and <AutoComplete> could autoplacement <Dropdown>

### ISSUE THREAD

**Issue by Dorious** [ant-design/ant-design#14228] opened 2019-01-09 14:28 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Problem is I have a <Select> with options that are longer than select and select is close to the right border of the window. 
When the list is wide goes out of the viewport (because by default it is bottomLeft). The could be some option to autoplace <Dropdown>.

### What does the proposed API look like?
<Select dropdownPlacement="auto"> ?

**Comment by afc163** [comment] 2019-01-09 14:37
Duplicate of https://github.com/ant-design/ant-design/issues/12153#issuecomment-420874541

**Comment by afc163** [comment] 2019-01-09 14:38
https://github.com/ant-design/ant-design/issues/10338#issuecomment-386184073

**Closed by afc163** 2019-01-09 14:37 UTC
