### ISSUE TITLE
table: scroll 与嵌套表格expandedRowRender 渲染时会出现bug

### ISSUE THREAD

**Issue by ql434** [ant-design/ant-design#12704] opened 2018-10-18 06:26 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
mac10.11.6 , chrome 69.0.3497.100 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q7ko4116y4)

### Steps to reproduce
看代码，代码里面清晰 https://codesandbox.io/s/q7ko4116y4

### What is expected?
正常显示

### What is actually happening?
错位显示了

**Comment by afc163** [comment] 2018-10-18 06:50
Duplicate of #9900

**Closed by afc163** 2018-10-18 06:50 UTC
