### ISSUE TITLE
Form.Item TypeScript error when using RC of antd 4.0.0-rc.2

### ISSUE THREAD

**Issue by ptomaszi** [ant-design/ant-design#21075] opened 2020-01-22 09:31 UTC
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ptomaszi/react_antd](https://github.com/ptomaszi/react_antd)

### Steps to reproduce
Run npm start

### What is expected?
The npm start script should finish successfully without any TypeScript errors

### What is actually happening?
E:/Projects/_test/my-app/src/features/login/login.tsx
TypeScript error in E:/Projects/_test/my-app/src/features/login/login.tsx(18,11):
JSX element type 'ReactNode' is not a constructor function for JSX elements.
  Type 'undefined' is not assignable to type 'Element | null'.  TS2605

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.2 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by DennisBaekgaard** [comment] 2020-01-22 09:51
I Can confirm this is an issue as well.

**Comment by zombieJ** [comment] 2020-01-22 11:09
Duplicate of #21067

**Closed by zombieJ** 2020-01-22 11:09 UTC
