### ISSUE TITLE
Arrow-up/down keys do not work in Autocomplete with TextArea

### ISSUE THREAD

**Issue by KarelVerschraegen** [ant-design/ant-design#49260] opened 2024-06-05 13:30 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-g2n5pf?file=%2Findex.js)

### Steps to reproduce

When using the `Autocomplete` component, the arrow-up/down keys no longer work inside the `TextArea` component when the `Autocomplete` is not open.

### What is expected?

When using the `Autocomplete` component in controlled mode (i.e. open state is controlled manually), the up/down arrow keys should correctly navigate up and down when the `Autocomplete` dropdown is not open.

### What is actually happening?

The up/down arrow keys do not work

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 18.2.0 |
| System | macOS Sonoma 14.5 (23F79) Darwin Kernel Version 23.5.0 |
| Browser | Firefox 126.0.1 (64-bit) |

---
I initially tried to build something similar with the `Mentions` component, where the arrow up/down keys correctly work when the dropdown is not open, but I need more control over when the dropdown actually opens.

I tried re-creating the `Mentions` behaviour with the `Autocomplete` component and noticed that the arrow up/down keys no longer functioned as intended.

A possible solution for me could either be:
**Autocomplete component**
- Do not override the arrow up/down behaviour when the dropdown is closed

**Mentions component**
- Allow controlled mode where the open/closed state is controlled externally
- Allow rendering absolutely nothing when no values match. At the moment, the notFoundContent still renders an empty card even with `notFoundContent={null}`

Is there another workaround/solution for this problem?
Thanks!

**Comment by afc163** [comment] 2024-06-06 10:17
Duplicate of #36371

**Closed by afc163** 2024-06-06 10:17 UTC
Labels: unconfirmed
