### ISSUE TITLE
Drawer 官网示例导致滚动条消失

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#24688] opened 2020-06-02 07:11 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/drawer-cn/#components-drawer-demo-render-in-current](https://ant.design/components/drawer-cn/#components-drawer-demo-render-in-current)

### Steps to reproduce
先点击 在当前容器打开抽屉，然后直接点击在抽屉中使用表单。然后关闭抽屉，页面滚动条消失
![bug](https://user-images.githubusercontent.com/46179450/83490837-50e5f280-a4e3-11ea-8e64-26c17d024219.gif)

### What is expected?
然后关闭抽屉，页面滚动条正常显示

### What is actually happening?
然后关闭抽屉，页面滚动条消失

| Environment | Info |
|---|---|
| antd | 4.3.0 |
| React | latest |
| System | win10 |
| Browser | chrome80 |

**Comment by afc163** [comment] 2020-06-02 07:15
Duplicate of #20022

**Closed by afc163** 2020-06-02 07:15 UTC
