### ISSUE TITLE
DatePicker has inconsistent behaviour when using with and without "showTime"

### ISSUE THREAD

**Issue by jaworek** [ant-design/ant-design#27880] opened 2020-11-19 10:06 UTC
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-md42g)

### Steps to reproduce
1. Click on DatePicker input.
2. Select date.
3. Click on DatePicker with showTime.
4. Select value.
5. Click somewhere on the page, other than input.'
6. Value gets cleared instead of submitted.

### What is expected?
When selecting date and time in DatePicker. Blur should not clear value but apply it, just as pressing OK button.

### What is actually happening?
When using DatePicker changing date automatically closes input and applies value. When using it with ```showTime``` prop set to ```true``` it displays OK button. 
It is not possible to get consistent behaviour, because first option does not have OK button and second option, when user selects date, but does not press button it will clear selected value, which is confusing behaviour.

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 16.14.0 |
| System | MacOS 10.15.1 |
| Browser | Chrome 86 |

---
It would be useful to be able to hide OK button or display it consistently everywhere. Currently it is not possible.

**Comment by jaworek** [comment] 2020-11-19 11:01
Trying to set state manually using ```onChange``` or ```onCalendarChange``` does not work as these event are triggered only when user presses OK button.

**Comment by afc163** [comment] 2020-11-20 01:41
Duplicate of https://github.com/ant-design/ant-design/issues/27779#issuecomment-728840416

**Closed by afc163** 2020-11-20 01:41 UTC
