### ISSUE TITLE
Fixed Columns do not integrate well with Context apis

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [ant-design/ant-design#15096] opened 2019-02-27 11:47 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kxlzx2k0y7)

### Steps to reproduce
Please open the link.
In app.js line No. 47  is commented.
Click edit and enter random values and click on save.
In console you will see the form objects.

Now remove the comments of line No. 47
Click on edit, do changes and click on save
In console you will see an empty object.

Columns that are marked as fixed do not obey contextapis.

### What is expected?
The behaviour should be same in both fixed and unfixed columns

### What is actually happening?
It is not behaving as expected.

| Environment | Info |
|---|---|
| antd | 3.10.2 |
| React | 16.5.2 |
| System | OSX |
| Browser | Google Chrome |

---
This is a fork of one of the examples in antd.

**Comment by zombieJ** [comment] 2019-02-27 12:03
Duplicate of #14634

**Closed by zombieJ** 2019-02-27 12:03 UTC
