### ISSUE TITLE
Menu collapse isn't properly folding SubMenu when openKeys is set

### ISSUE THREAD

**Issue by ganlub** [ant-design/ant-design#7063] opened 2017-08-02 14:29 UTC
### Version
2.12.3

### Environment
Archlinux, Firefox 55.0b13 & Chromium 60.0.3112.78

### Reproduction link
[https://codepen.io/anon/pen/NvrVLd?editors=0110](https://codepen.io/anon/pen/NvrVLd?editors=0110)

### Steps to reproduce
Click the collapse button.

### What is expected?
To fold the SubMenu items when collapsing the Menu as it happens with `defaultOpenKeys`

### What is actually happening?
The SubMenu is not folding, and because of that the popup menu is not shown.

---
As a workaround I removed the openKeys prop when the Sider is collapsed.

**Comment by ddcat1115** [comment] 2017-08-03 01:38
You should use `defaultOpenKeys ` instead of `openKeys`

**Comment by afc163** [comment] 2017-08-04 08:15
Duplicate of #7062

**Closed** 2017-08-04 08:16 UTC
