### ISSUE TITLE
antd table 列上加入了footer不起作用，不知道要怎么操作

### ISSUE THREAD

**Issue by mar105** [ant-design/ant-design#14794] opened 2019-02-12 08:37 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
5710的例子看了，按下面这种方式加了不行。在你们官方的例子上直接加也不行，看就没有这个属性
const columns = [{
title: 'Name',
dataIndex: 'name',
}, {
title: 'Age1',
dataIndex: 'age',
footer: (data) => {
return

Summary: {data.reduce((sum, record) => sum   record.age, 0)}

},
}, {
title: 'Address',
dataIndex: 'address',
}];

### What does the proposed API look like?
希望能够表格下方有固定footer行

**Comment by yesmeck** [comment] 2019-02-12 08:42
文档里并没有这个 API， #5710 里只是提议加入这个 API。

Duplicate of #5710

**Closed by yesmeck** 2019-02-12 08:42 UTC
