### ISSUE TITLE
treeSelect及select控件 没有匹配到项就显示一串id

### ISSUE THREAD

**Issue by cdesky** [ant-design/ant-design#31695] opened 2021-08-06 08:35 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://192.168.3.85:3000/qm/#/qualityManagement/qualityReport/qualityReportBase?id=1c426c0e3d6f47cb83d3fcd3174c7c40](http://192.168.3.85:3000/qm/#/qualityManagement/qualityReport/qualityReportBase?id=1c426c0e3d6f47cb83d3fcd3174c7c40)

### Steps to reproduce
一个树再一个id扔在defaultValue里，那个id不在这个树里就会显示一串id

### What is expected?
不匹配就不要显示id

### What is actually happening?
一个树再一个id扔在defaultValue里，那个id不在这个树里就会显示一串id

| Environment | Info |
|---|---|
| antd | 3.26.16 |
| React | 16.13.1 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment] 2021-08-06 08:55
Duplicate of #27678

**Closed by afc163** 2021-08-06 08:55 UTC
