### ISSUE TITLE
Transfer组件个数不确定，不能每个都写一个change方法， 怎么才能判断是哪个组件的事件

### ISSUE THREAD

**Issue by zhangyanf** [ant-design/ant-design#16185] opened 2019-04-19 06:48 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当有多个Transfer组件时，onChange操作无法确定时哪个Transfer的change操作，增加一个参数的话 比如transfer的key，就可以知道调用的是哪个组件的chang方法
![image](https://user-images.githubusercontent.com/10766381/56356886-a5a9a980-620c-11e9-8f11-1b04741bafbc.png)

### What does the proposed API look like?
```

handleChange(targetKeys, direction, moveKeys, transferId){}

render(){
    <Row gutter={8}>
       transfers.map(transfer => (
        <Col span={16} offset={6}>
          <Transfer
           key={transferId}
            dataSource={ds}
            showSearch
            filterOption={this.filterOption}
            targetKeys={targetKeys}
            onChange={this.handleChange}
            onSearch={this.handleSearch}
            render={item => item.title}
          />
        </Col> 
      ))
      </Row>
} 
```

**Comment by afc163** [comment] 2019-04-19 08:36
Duplicate of #16176

**Closed by afc163** 2019-04-19 08:36 UTC
