### ISSUE TITLE
Layout suffixCls on a DOM element

### ISSUE THREAD

**Issue by janarvaez** [ant-design/ant-design#40996] opened 2023-03-01 11:41 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-de9kbi?file=/index.js)

### Steps to reproduce

- update to antd@5.2.3
- use the Layout component

### What is expected?

no warnings

### What is actually happening?

after this change https://github.com/ant-design/ant-design/pull/40933/files, this warning is being triggered
`Warning: React does not recognize the `suffixCls` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `suffixcls` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

| Environment | Info |
| --- | --- |
| antd | 5.2.3 |
| React | react 18 |
| System | macos |
| Browser | chrome |

**Comment by yoyo837** [comment] 2023-03-01 11:42
Duplicate of #40968

**Closed by yoyo837** 2023-03-01 11:42 UTC
Labels: unconfirmed
