### ISSUE TITLE
Disabled date logic for RangePicker

### ISSUE THREAD

**Issue by xedef** [ant-design/ant-design#39989] opened 2023-01-03 17:44 UTC
### Reproduction link

[https://fpiz14.csb.app/](https://fpiz14.csb.app/)

### Steps to reproduce

1. Create a RangePicker
2. Set `showTime` property
3. Set `disabledDate` by comparing to 2 limits by date and time

### What is expected?

1. All dates inside allowed range should be selectable
2. All times outside allowed range should be disabled

### What is actually happening?

1. Last date is unselectable
2. Even though the "Ok" button is disabled when selecting a time outside the allowed range, they should be shown as disabled in the same way dates are, to keep UI consistency

![image](https://user-images.githubusercontent.com/2538617/210411960-b2bb0443-64d5-4004-88eb-293a8a8bd999.png)

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18 |
| System | macOS |
| Browser | Chrome |

**Comment by afc163** [comment] 2023-01-04 02:28
Duplicate of #31261

**Closed by afc163** 2023-01-04 02:28 UTC
