### ISSUE TITLE
Select组件选项内容多的时候渲染速度慢

### ISSUE THREAD

**Issue by junhui75165** [ant-design/ant-design#14540] opened 2019-01-24 10:37 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/junhui/pen/wNaZyK?editors=0011](https://codepen.io/junhui/pen/wNaZyK?editors=0011)

### Steps to reproduce
Select组件下拉项内容多的时候，打开速度明显慢很多，数量级大概两千左右，打开速度大概三秒多

### What is expected?
将下拉项打开速度降低到1s以下

### What is actually happening?
打开速度大概三秒多

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | 15.6.1 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment] 2019-01-24 12:33
Duplicate of #3789

**Closed by afc163** 2019-01-24 12:33 UTC

**Comment by WangGuangCheng2018** [comment] 2019-05-06 10:19
下拉内容不应该也没必要展示太多，提供必要的搜索功能就足够了，前几天在antd 的Select上二次封装了个展示添加限制的选择器，一个demo[https://codesandbox.io/s/v10lw960y3](url)，希望可以帮到你
