### ISSUE TITLE
Tree shake the Icon component

### ISSUE THREAD

**Issue by wangyi7099** [ant-design/ant-design#18210] opened 2019-08-11 12:13 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Is there a way to tree shake the icon component ?
I just use few icons but all icons are introduced into the bundle and reaches a large size of `490 kb`.
<img width="1439" alt="屏幕快照 2019-08-11 下午8 09 03" src="https://user-images.githubusercontent.com/24426655/62833607-4a486f00-bc74-11e9-88b5-52ff5d98fc1b.png">

I just noticed `@ant-design/icons` are all imported by `Icon` component 
https://github.com/ant-design/ant-design/blob/aa2ed79770897194fa6c17b6d67dbc104c21227d/components/icon/index.tsx#L4

### What does the proposed API look like?
Can we use `module.exports`?
e.g.

```js
import * as allIcons from '@ant-design/icons/lib/dist';
Object.keys(allIcons).map(key => module.exports[key] = (allIcons as any)[key])
```

**Comment by afc163** [comment] 2019-08-11 13:22
Duplicate of #12011

**Closed by afc163** 2019-08-11 13:22 UTC
