### ISSUE TITLE
The dividing line of the table is not in a row（in Components--components table--Fixed Columns and Header）

### ISSUE THREAD

**Issue by broweRay** [ant-design/ant-design#18224] opened 2019-08-12 09:13 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-9twp7)

### Steps to reproduce
Run directly link

### What is expected?
Name field and Other field is not a line

### What is actually happening?
Name field and Other field is  a line

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.9.0 |
| System | win10 |
| Browser | Chrome75.0.3770.142 |

---
在columns数组的第一个column中，有一个children的情况下，使用fixed: left时，Name的下分割线和Other的下分割线不在一行上；fixed: left在children的子集上，又使第一列数据不显示；

**Comment by afc163** [comment] 2019-08-12 09:52
Duplicate of #17889

**Closed by afc163** 2019-08-12 09:52 UTC
