### ISSUE TITLE
expandedRowRender - Grid space for expand row

### ISSUE THREAD

**Issue by Mars4Max** [ant-design/ant-design#16888] opened 2019-05-30 10:17 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-gfqb3?fontsize=14)

### Steps to reproduce
Expand rows by   button. Lines do not fit when expanded.

### What is expected?
Set the same height of the expanded space in the docked column.

### What is actually happening?
Fixed columns has expanded space smaller than the expanded row.

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | 16.4.0 |
| System | Windows 10 |
| Browser | Chrome 74.0.3729.169 |

---
Nice to have: Make the space in fixed columns transparent when expanded

**Comment by afc163** [comment] 2019-05-30 15:59
<img width="613" alt="image" src="https://user-images.githubusercontent.com/507615/58645958-eda50b80-8336-11e9-99b9-79ca56fcfc39.png">

**Comment by afc163** [comment] 2019-05-30 15:59
Duplicate of #16878

**Closed by afc163** 2019-05-30 15:59 UTC

**Comment by Mars4Max** [comment] 2019-05-31 08:51
😢
