### ISSUE TITLE
Radio group is throwing forwardRef warning 

### ISSUE THREAD

**Issue by yakkantiraja** [ant-design/ant-design#25333] opened 2020-07-01 03:43 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v95ek)

### Steps to reproduce
When we use radio group its throwing forwardRef  warning . Same is observed in AntD api examples as well

Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### What is expected?
No warnings should be thrown

### What is actually happening?
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
    in RadioGroup
    in RadioGroup (at index.js:120)
    in Unknown
    in Unknown (created by Field)
    in div (created by FormItemInput)
    in div (created by FormItemInput)
    in div (created by Context.Consumer)
    in Col (created by FormItemInput)
    in FormItemInput (created by Field)
    in div (created by Context.Consumer)
    in Row (created by Field)
    in Field (created by WrapperField)
    in WrapperField (created by FormItem)
    in FormItem (at index.js:119)
    in form (created by ForwardRef(Form))
    in ForwardRef(Form) (created by ForwardRef(InternalForm))
    in SizeContextProvider (created by ForwardRef(InternalForm))
    in ForwardRef(InternalForm) (at index.js:47)
    in Demo (at index.js:247)

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | any |
| System | any |
| Browser | any |

**Comment by afc163** [comment] 2020-07-01 03:49
Duplicate of #25310

**Closed by afc163** 2020-07-01 03:49 UTC
