### ISSUE TITLE
TextArea breaks in Modal with Form when resetting in afterClose

### ISSUE THREAD

**Issue by bombillazo** [ant-design/ant-design#43631] opened 2023-07-18 17:52 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-pldz8f?file=/index.js)

### Steps to reproduce

- Setup modal with a Form inside. Have a Form.Item with an Input.TextArea component
- On the `afterClose` modal callback, reset the form with `form.resetFields()`
- Open modal with Input.TextArea
- Close modal
- Error will appear

### What is expected?

No issues when closing modal with a TextArea

### What is actually happening?

Something

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | React |
| System | Mac |
| Browser | Firefox |

**Comment by panlina** [comment] 2023-07-19 02:16
This should be duplicate of https://github.com/ant-design/ant-design/issues/43615 I created yesterday, which is already fixed.

**Comment by yoyo837** [comment] 2023-07-19 02:22
Duplicate of #43615

**Closed by yoyo837** 2023-07-19 02:22 UTC
Labels: unconfirmed
