### ISSUE TITLE
Transfer穿梭框能不能支持拖动配置功能

### ISSUE THREAD

**Issue by ModestQian** [ant-design/ant-design#26716] opened 2020-09-12 08:33 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以实现右边选中的数据，可以进行自定义排序功能

### What does the proposed API look like?
```
sortable --- 是否允许拖拽排序 --- Boolean --- false
建议参考飞冰组件里面的api
```

**Comment by afc163** [comment] 2020-09-13 05:01
Duplicate of #12817

**Closed by afc163** 2020-09-13 05:01 UTC

**Comment by shenzhongkang** [comment] 2021-11-09 06:59
Here is my solution, see: https://codesandbox.io/s/ant-design-transfer-draggable-sort-3hulk?file=/src/App.js @jsqq520
