### ISSUE TITLE
Drawer afterVisibleChange 动画结束后afterVisibleChange 方法内部会执行两次操作

### ISSUE THREAD

**Issue by gongzhiqiang123456** [ant-design/ant-design#17383] opened 2019-07-01 01:11 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/17182](https://github.com/ant-design/ant-design/issues/17182)

### Steps to reproduce
打开抽屉执行afterVisibleChange，afterVisibleChange里面的内容会被执行两次(如果有查询数据操作，同样的操作会执行两次)

### What is expected?
动画结束后仅且执行一次

### What is actually happening?
执行两次相同的内容

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 3.16.1 |
| System | windows |
| Browser | 火狐 |

**Comment by zombieJ** [comment] 2019-07-01 01:36
Re-install your node module. This has been fixed.

Duplicate of #17184

**Closed by zombieJ** 2019-07-01 01:36 UTC

**Comment by theFrontCalf** [comment] 2019-07-09 06:17
对的，我也是来这里寻找答案的
