### ISSUE TITLE
useLayoutEffect warning on the server side rendering with nextjs

### ISSUE THREAD

**Issue by hamidgarousi** [ant-design/ant-design#32311] opened 2021-09-26 12:17 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost:3000](http://localhost:3000)

### Steps to reproduce
useEffectLayout(()=>{}) hook cant work on server side rendering this hook should replace with useEffect(()=>{})

### What is expected?
useEffectLayout(()=>{}) hook cant work on server side rendering this hook should replace with useEffect(()=>{})

### What is actually happening?
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | react 17.0.2 and nextjs 11.1.2 |
| System | windows 10 |
| Browser | chrome 93 |

**Comment by afc163** [comment] 2021-09-26 12:35
Duplicate of #30396

**Closed by afc163** 2021-09-26 12:35 UTC
