### ISSUE TITLE
UI looks weird after set loading props to true in table component

### ISSUE THREAD

**Issue by ycczkl** [ant-design/ant-design#9884] opened 2018-03-30 19:47 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
macos10.10.5, chrome Version 65.0.3325 (Official Build) (64-bit)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/54n05z60kn)

### Steps to reproduce
Use chrome
Set loading props to true in table component.
https://codesandbox.io/s/54n05z60kn

![image](https://user-images.githubusercontent.com/6109663/38151509-77ab7766-3418-11e8-9985-cb9eb9637f2a.png)

### What is expected?
the table layout should be horizontal

### What is actually happening?
the table layout is diagonal

---
Seems like an chrome only issue. Safari and firefox looks good

**Comment by ddcat1115** [comment] 2018-04-02 07:54
The demo works fine(in the same version chrome)... 😦 

<img width="824" alt="2018-04-02 3 59 27" src="https://user-images.githubusercontent.com/7017767/38188305-f3f8bb68-368d-11e8-881a-25276ec5db84.png">

**Comment by yesmeck** [comment] 2018-04-02 07:56
Duplicate of https://github.com/ant-design/ant-design/issues/9731

**Closed by yesmeck** 2018-04-02 07:56 UTC
Labels: Component: Table

**Comment by yesmeck** [comment] 2018-04-02 08:00
@ycczkl It's a known issue which happens on the old version of OSX. Could you help us send a bug report to Chrome (none of us use an old version of OSX)?
