### ISSUE TITLE
RangePicker自动禁用错误

### ISSUE THREAD

**Issue by JackShell2020** [ant-design/ant-design#36917] opened 2022-08-05 10:46 UTC
### Reproduction link

[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce

带时分秒的RangePicker选择器，选择开始时间，然后选择结束时间

### What is expected?

结束时间面板中，开始时间之前的日期和时分秒都不可选

### What is actually happening?

结束时间面板中，开始时间之前的日期不可选，但时分秒仍然可以选择

| Environment | Info |
| --- | --- |
| antd | 4.22.3 |
| React | 18.0.0 |
| System | macOS |
| Browser | Chrome |

**Comment by afc163** [comment] 2022-08-08 09:46
Duplicate of #29179

**Closed by afc163** 2022-08-08 09:46 UTC
