### ISSUE TITLE
Input label as part of the border

### ISSUE THREAD

**Issue by kasunkula** [ant-design/ant-design#25264] opened 2020-06-28 14:31 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
we need a feature to embed the Input label inside the border as in below illustration
https://drive.google.com/file/d/15pTxylQRWNsPd_BhGYHf6jSoRTC_IeRu/view?usp=sharing

### What does the proposed API look like?
we need a feature to embed the Input label inside the border as in below illustration
https://drive.google.com/file/d/15pTxylQRWNsPd_BhGYHf6jSoRTC_IeRu/view?usp=sharing

**Comment by afc163** [comment] 2020-06-29 02:44
Duplicate of #12738

**Closed by afc163** 2020-06-29 02:44 UTC
