### ISSUE TITLE
Tabs should have a `getPopupContainer` prop to apply scoped styles to overlays.

### ISSUE THREAD

**Issue by rgosse** [ant-design/ant-design#27178] opened 2020-10-15 15:54 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sparkling-firefly-sdjpe)

### Steps to reproduce
Hover the "..." icon to show hidden tabs

### What is expected?
The dropdown should be styled according to our scoped ant-design stylesheet

### What is actually happening?
The overlay will always be mounted  under `<Body />` and will not be styled. Additionnally, we lose the ability to close the overlay.

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome 86 |

---
Like in all other components based on a dropdown, we should be able to pass a `getPopupContainer` prop so that we can apply the ant design stylesheet to a non-root DOM element.

**Comment by afc163** [comment] 2020-10-16 03:08
Duplicate of #25844

**Closed by afc163** 2020-10-16 03:08 UTC
