### ISSUE TITLE
InputNumber的异常行为

### ISSUE THREAD

**Issue by cjmafei** [ant-design/ant-design#27501] opened 2020-11-02 09:35 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/decimals-ant-design-demo-forked-yzhxq)

### Steps to reproduce
1.输入0.000000123
2.失去焦点
3.value变成了0.0000001

### What is expected?
输入框的值为0.000000123

### What is actually happening?
小数点后截取了

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | latest |
| System | latest |
| Browser | latest |

---
download了源码进行了debug，0.000000123会先变成1.23e-7，然后用正则拿到了7，对输入的value小数点后的值进行了slice操作，变成了0.0000001.不太懂为什么要这么截取？还有截图的位数有什么说法吗？

**Comment by cjmafei** [comment] 2020-11-02 09:36
![Uploading image.png…]()

**Comment by zombieJ** [comment] 2020-11-02 09:40
已经找到问题了那就直接来个 PR 吧 ~❤

**Comment by afc163** [comment] 2020-11-02 10:49
目前 InputNumber 对于小数和大数的支持不是很好，详情见 #25418

**Comment by afc163** [comment] 2020-11-02 10:49
Duplicate of #25418

**Closed by afc163** 2020-11-02 10:49 UTC
