### ISSUE TITLE
Opening of drawer causes error

### ISSUE THREAD

**Issue by pavolgolias** [ant-design/ant-design#17439] opened 2019-07-03 09:56 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pavolgolias/pen/oryXmJ](https://codepen.io/pavolgolias/pen/oryXmJ)

### Steps to reproduce
1. Just open the link, click the button and see the errors in the console.

### What is expected?
Drawer opens and closes without errors.

### What is actually happening?
Some errors occur. I suppose it happens in version 3.20.0

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8.6 |
| System | win 10 |
| Browser | chrome 75.0.3770.100 |

**Comment by afc163** [comment] 2019-07-03 10:26
Duplicate of #17387

**Closed by afc163** 2019-07-03 10:26 UTC
