### ISSUE TITLE
Ant-design Website

### ISSUE THREAD

**Issue by dima-klimenkov** [ant-design/ant-design#27384] opened 2020-10-26 13:15 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/](https://ant.design/)

### Steps to reproduce
On the main page of the site, when choosing the version of antd, when you click on the scrollbar, the website crashes.

### What is expected?
Select antd version

### What is actually happening?
Website crash with error, React #185 https://reactjs.org/docs/error-decoder.html?invariant=185 

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome 86.0.4240.111, (64 бит) |

---
I apologize for the flood, but I could not find where  report this problem

**Comment by yoyo837** [comment] 2020-10-26 13:24
ref: #27282

**Comment by xrkffgg** [comment] 2020-10-29 01:35
Duplicate of  https://github.com/ant-design/ant-design/issues/27374

后续统一在 #27282 解决

**Closed by xrkffgg** 2020-10-29 01:35 UTC
Labels: 🐛 Bug
