### ISSUE TITLE
本地启动 npm start 失败

### ISSUE THREAD

**Issue by chenyizhongx** [ant-design/ant-design#33694] opened 2022-01-12 08:12 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://gitpod.io/#https://github.com/ant-design/ant-design](https://gitpod.io/#https://github.com/ant-design/ant-design)

### Steps to reproduce
npm install 
npm start 

### What is expected?
能够正常启动

### What is actually happening?
> antd@4.18.3 prestart
> npm run version

> antd@4.18.3 version
> node ./scripts/generate-version

> antd@4.18.3 start
> antd-tools run clean && cross-env NODE_ENV=development concurrently "bisheng start -c ./site/bisheng.config.js"

antd-tools run clean
[0] ℹ Compiling 🚚  Bisheng
[0] /Users/chicv/personalProject/ant-design/node_modules/webpack/lib/Dependency.js:322
[0] 		throw new Error(
[0] 		^
[0]
[0] Error: module property was removed from Dependency (use compilation.moduleGraph.updateModule(dependency, module) instead)
[0]     at ProvidedDependency.set (/Users/chicv/personalProject/ant-design/node_modules/webpack/lib/Dependency.js:322:9)
[0]     at iterationDependencies (/Users/chicv/personalProject/ant-design/node_modules/bisheng/node_modules/webpack/lib/Compilation.js:940:21)
[0]     at /Users/chicv/personalProject/ant-design/node_modules/bisheng/node_modules/webpack/lib/Compilation.js:950:8
[0]     at /Users/chicv/personalProject/ant-design/node_modules/bisheng/node_modules/webpack/lib/NormalModuleFactory.js:409:6
[0]     at /Users/chicv/personalProject/ant-design/node_modules/bisheng/node_modules/webpack/lib/NormalModuleFactory.js:155:13
[0]     at eval (eval at create (/Users/chicv/personalProject/ant-design/node_modules/bisheng/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
[0]     at /Users/chicv/personalProject/ant-design/node_modules/case-sensitive-paths-webpack-plugin/index.js:178:9
[0]     at /Users/chicv/personalProject/ant-design/node_modules/case-sensitive-paths-webpack-plugin/index.js:125:7
[0]     at /Users/chicv/personalProject/ant-design/node_modules/case-sensitive-paths-webpack-plugin/index.js:125:7
[0]     at CaseSensitivePathsPlugin.fileExistsWithCase (/Users/chicv/personalProject/ant-design/node_modules/case-sensitive-paths-webpack-plugin/index.js:95:5)
[0]     at /Users/chicv/personalProject/ant-design/node_modules/case-sensitive-paths-webpack-plugin/index.js:118:10
[0]     at CaseSensitivePathsPlugin.getFilenamesInDir (/Users/chicv/personalProject/ant-design/node_modules/case-sensitive-paths-webpack-plugin/index.js:52:5)
[0]     at CaseSensitivePathsPlugin.fileExistsWithCase (/Users/chicv/personalProject/ant-design/node_modules/case-sensitive-paths-webpack-plugin/index.js:101:8)
[0]     at /Users/chicv/personalProject/ant-design/node_modules/case-sensitive-paths-webpack-plugin/index.js:118:10
[0]     at Array.<anonymous> (/Users/chicv/personalProject/ant-design/node_modules/case-sensitive-paths-webpack-plugin/index.js:72:5)
[0]     at Storage.finished (/Users/chicv/personalProject/ant-design/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
^C[0] bisheng start -c ./site/bisheng.config.js exited with code 1

| Environment | Info |
|---|---|
| antd | 4.18.3 |
| React | 无 |
| System | mac os M1 Big Sur 11.6.1 |
| Browser | 无 |

---
GitPod 中同样启动失败，应该跟本地环境没关系

**Comment by afc163** [comment] 2022-01-12 14:07
Duplicate of #33444

**Closed by afc163** 2022-01-12 14:07 UTC
