### ISSUE TITLE
table表格内编辑大量数据卡顿

### ISSUE THREAD

**Issue by 545582088** [ant-design/ant-design#19183] opened 2019-10-12 01:55 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://blog.csdn.net/weixin_43624724/article/details/85173774](https://blog.csdn.net/weixin_43624724/article/details/85173774)

### Steps to reproduce
大于50行数据，任意操作都卡顿
![image](https://user-images.githubusercontent.com/39516159/66692977-6bf6be80-ecd6-11e9-8241-5f940e693ae9.png)

### What is expected?
流畅

### What is actually happening?
卡顿

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 16.5.2 |
| System | windows10 |
| Browser | chrome 69.0.3497.92 |

**Comment by 545582088** [comment] 2019-10-12 02:05
同问题 #2884 ，但没找到解决方案，链接已经失效，是否可以提供新的链接

**Comment by afc163** [comment] 2019-10-12 02:54
Duplicate of #10431

**Closed by afc163** 2019-10-12 02:54 UTC
