### ISSUE TITLE
 DatePicker 的 RangePicker在protable下面 renderFormItem tooltip有问题，我在procomponent提交issue，没人管

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#31886] opened 2021-08-24 08:45 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cha-xun-biao-ge-forked-v9h8c?file=/App.tsx)

### Steps to reproduce
打开复现地址就可以看到问题，只显示了一个“请”和“输”。，正常应该是开始时间和结束时间 撒。具体看图

### What is expected?
具体看复现代码。

### What is actually happening?
datepicker显示有问题

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React |  16.13.1 |
| System | windows |
| Browser | chrome  92.0.4515.159 |

![image](https://user-images.githubusercontent.com/8272614/130586466-f30f3a0f-276a-4076-9190-a731b1494ad1.png)

**Comment by afc163** [comment] 2021-08-24 09:07
Duplicate of https://github.com/ant-design/pro-components/issues/3489

**Comment by xgj1988** [comment] 2021-08-24 09:07
@afc163  这个就是我提的啊，没人回答了嘛。所以才在这边来提一下

**Closed by afc163** 2021-08-24 09:07 UTC

**Comment by lovewaner** [comment] 2021-11-10 01:22
`renderFormItem: () => {
        return <RangePicker placeholder={['开始时间', '结束时间']} />;
      }`
