### ISSUE TITLE
select 全选/取消全选 

### ISSUE THREAD

**Issue by yangjunjie520** [ant-design/ant-design#30572] opened 2021-05-18 11:26 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
select 添加了一个全选选项 再次点击全选是 取消所有选择 

### What does the proposed API look like?
期望 在onDeselect 中 调用from.setFieldsValue  通过设置[]的形式 来取消所有选择

**Comment by afc163** [comment] 2021-05-18 13:21
Duplicate of #30041

**Closed by afc163** 2021-05-18 13:21 UTC
