### ISSUE TITLE
TimePicker disabledHours 先选择分钟或者秒默认会选择0时

### ISSUE THREAD

**Issue by wolyshaw** [ant-design/ant-design#26057] opened 2020-08-06 05:45 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/suspicious-taussig-4sq6k)

### Steps to reproduce
1. disabledHours={() => [0, 1]}，先disabled部分0和1时
2. 选择后面的分钟或者秒钟时，会默认选择0时

### What is expected?
选中第一个未被disabled的时

### What is actually happening?
会选中被disabled的时

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.12.0 |
| System | MacOS 10.15.5 |
| Browser | Chrome 84.0.4147.105 |

**Comment by xrkffgg** [comment] 2020-08-06 05:50
same like https://github.com/ant-design/ant-design/issues/26057

**Comment by afc163** [comment] 2020-08-06 05:52
Duplicate of #25143

**Closed by afc163** 2020-08-06 05:52 UTC
Labels: 🐛 Bug
