### ISSUE TITLE
login icon not shows

### ISSUE THREAD

**Issue by zwpCode** [ant-design/ant-design#5312] opened 2017-03-15 08:42 UTC
1.Icon图标-->方向性图标--><Icon type="login" />，login图标。此图标无法显示
2.官网地址。https://ant.design/components/icon-cn/

**Comment by yesmeck** [comment] 2017-03-15 08:45
It shows on Chrome 56. What browser and OS are you using?

**Comment by afc163** [comment] 2017-03-15 08:47
Try <kbd>Ctrl<kbd> + <kbd>Shift<kbd> + <kbd>R<kbd>

**Comment by afc163** [comment] 2017-03-16 03:02
closing for can't reproduce.

**Closed by afc163** 2017-03-16 03:02 UTC
