### ISSUE TITLE
级联选择器能支持多选吗？

### ISSUE THREAD

**Issue by duzuimoye** [ant-design/ant-design#30750] opened 2021-05-28 03:22 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有一个需求就是、希望可以开启多选模式,比如第一级选择了浙江省，第二级、第三级会默认选中全部市、区。然后每一级也可以多选。希望跟elementUI的级联选择器一样

### What does the proposed API look like?
希望可以通过props.multiple = true 来开启多选模式

**Comment by zombieJ** [comment] 2021-05-28 03:59
Duplicate of #23410

**Closed by zombieJ** 2021-05-28 03:59 UTC
