### ISSUE TITLE
Clickable item in Select.props.dropdownRender is not working

### ISSUE THREAD

**Issue by Songkeys** [ant-design/ant-design#16209] opened 2019-04-21 17:31 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/xpz38p5z3o)

### Steps to reproduce
See the examples I provided in codesandbox. The code is copied from the antd component doc, and I only add `onClick` prop to `<Select>`.

(I think I've found the reason. Skip to the **Reason** part plz.)

~~To trigger the bug (i.e. clicking "Add item" not working), I used trackpad on my MacBook by pressing it. However, when I tried to tap the trackpad, it was working sometimes....~~

~~Besides, I've tried to use a button instead, it behaves the same.~~

~~Didn't use a mouse to try this.~~

### What is expected?
When clicking "Add item", the `onClick` event on the item should be fired.

### What is actually happening?
Not working.

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | ^3.15.0 |
| System | macOS mojave |
| Browser | Chrome 69 |

## Reason

https://github.com/react-component/select/blob/master/src/DropdownMenu.tsx#L241

**The dropdown menu disappears when `onMouseDown` which is ahead of `div`'s `onClick`.**

So for now, I changed my trigger to `onMouseDown` either on my clickable item to solve this issue.

Why is it `onMouseDown` btw? I think changing it to the normal `onClick` might be more reasonable.

**Comment by afc163** [comment] 2019-04-22 02:19
Duplicate of #13448

**Closed by afc163** 2019-04-22 02:19 UTC
