### ISSUE TITLE
Table组件排序的上下箭头，是否可以添加下禁用功能

### ISSUE THREAD

**Issue by Aralhi** [ant-design/ant-design#11258] opened 2018-07-12 13:08 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有的业务场景是不必要升序排的，接口不支持升序排，但是还是可以点升序排

### What does the proposed API look like?
sorterDisabled: boolean|string   'ascend' 'descend' false

**Comment by Weirdo-Z** [comment] 2018-07-18 07:12
Emm...那为什么数据不默认显示降序排，还要点一下排序再降序排？ 你这个需求有点奇怪  
Why not show data default by ascend/descend

**Comment by Aralhi** [comment] 2018-07-19 04:04
@Weirdo-Z 是默认显示降序的，我想禁用或者隐藏向上的按钮，这样用户一目了然就知道这里不可以做升序排序了，thanks for you reply

**Comment by yesmeck** [comment] 2018-07-19 04:37
Duplicate of #11246

**Closed by yesmeck** 2018-07-19 04:37 UTC
