### ISSUE TITLE
Datepicker 组建 mode 参数为 'year' 时无法选择年份

### ISSUE THREAD

**Issue by fuzhongfeng** [ant-design/ant-design#11938] opened 2018-08-29 02:23 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.4

### Environment
codepen 平台 Datepicker 组建

### Reproduction link
[https://ant.design/components/date-picker-cn/#header](https://ant.design/components/date-picker-cn/#header)

### Steps to reproduce
codepen 平台 Datepicker 组建 mode 参数为 "year" 时，可以选择点击并弹出“年”选择面板，但是选择某一年（如2012）之后不能关闭，进而无法选择

### What is expected?
可以选择年份

### What is actually happening?
不能选择年份

---
官方给出的 codepen 例子

**Comment by mushan0x0** [comment] 2018-08-29 03:02
[https://codepen.io/mushan0x0/pen/zJKqQx?&editors=001](url) 复现地址

**Comment by afc163** [comment] 2018-08-29 03:14
Duplicate of #4524

**Closed by afc163** 2018-08-29 03:14 UTC

**Comment by zhangyanling77** [comment] 2018-12-29 09:08
> https://codepen.io/mushan0x0/pen/zJKqQx?&editors=001 复现地址

<DatePicker mode="year" onPanelChange={(v) => {console.log(v)}}/>

**Comment by afc163** [comment] 2019-06-05 12:37
https://github.com/ant-design/ant-design/pull/16984
