### ISSUE TITLE
TreeSelect 选中项聚焦边框缺失

### ISSUE THREAD

**Issue by Yuiai01** [ant-design/ant-design#45265] opened 2023-10-11 03:58 UTC
### Reproduction link

[https://ant.design/components/tree-select-cn#tree-select-demo-basic](https://ant.design/components/tree-select-cn#tree-select-demo-basic)

### Steps to reproduce

1. 点击输入框，展开下拉框，任意选中一项；
2. 再次点击输入框，查看选中项边框。

<img width="504" alt="image" src="https://github.com/ant-design/ant-design/assets/112228030/7e0a45ff-3d5d-4a49-9212-e2bb376bce05">

### What is expected?

选中项聚焦边框不缺失

### What is actually happening?

选中项聚焦边框缺失

| Environment | Info |
| --- | --- |
| antd | 5.10.0 |
| React | 18.0.0 |
| System | macOS 12.2.1 |
| Browser | Chrome 108.0.5359.124 |

**Comment by MadCcc** [comment] 2023-10-11 05:37
Duplicate of https://github.com/ant-design/ant-design/issues/44492

**Closed** 2023-10-16 13:38 UTC
Labels: unconfirmed
