### ISSUE TITLE
弹窗和抽屉同时关闭导致页面不可滚动

### ISSUE THREAD

**Issue by nuancheng** [ant-design/ant-design#28343] opened 2020-12-14 06:14 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inspiring-feather-bu9i2?file=/index.js)

### Steps to reproduce
打开抽屉，打开抽屉内的弹窗，点击确定关闭弹窗和抽屉，页面就不可滚动了

### What is expected?
打开抽屉，打开抽屉内的弹窗，点击确定关闭弹窗和抽屉，页面可滚动

### What is actually happening?
打开抽屉，打开抽屉内的弹窗，点击确定关闭弹窗和抽屉，页面不可滚动了

| Environment | Info |
|---|---|
| antd | 4.9.3 |
| React | 17.0.1 |
| System | macOS 10.15.7 (19H2) |
| Browser | chrome  版本 86.0.4240.111（正式版本） (x86_64) |

---
给关闭抽屉的方法添加setTimeout可暂时解决

另外发现之前的一个已关闭 issue 并没有解决，复现链接依然可复现bug  https://github.com/ant-design/ant-design/issues/19956

**Comment by afc163** [comment] 2020-12-14 06:42
Duplicate of #25972

**Closed by afc163** 2020-12-14 06:42 UTC
