### ISSUE TITLE
Ability to default SELECT to open

### ISSUE THREAD

**Issue by ChuckJonas** [ant-design/ant-design#10701] opened 2018-05-30 04:48 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It's common to want to show the select options when the select is first displayed on the page.  Currently there is no way to do this.  Instead the user must first click in the select input box before being able to access options.  This is a horrible UX in some cases.

### What does the proposed API look like?
      <Select
       defaultOpen={true}
      >
        {children}
      </Select>

**Comment by afc163** [comment] 2018-05-30 06:00
Duplicate of #10482

**Closed by afc163** 2018-05-30 06:00 UTC
