### ISSUE TITLE
表格中的Input.TextArea高度手动拉伸的时候，fixed的单元格没有被拉伸

### ISSUE THREAD

**Issue by ZH4L** [ant-design/ant-design#18271] opened 2019-08-14 10:56 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mutable-hill-xnwl5?fontsize=14)

### Steps to reproduce
1. 手动拉伸Age列中textarea的高度

### What is expected?
左侧fixed的Name列的高度自适应

### What is actually happening?
左侧fixed的Name列的高度未变化

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | latest |
| System | macos |
| Browser | chrome |

**Comment by afc163** [comment] 2019-08-14 11:04
Duplicate of #14859

**Closed by afc163** 2019-08-14 11:04 UTC
