### ISSUE TITLE
Grid Col not support flex with responsive properties, e.g. xl={{ flex: 1 }}

### ISSUE THREAD

**Issue by curly210102** [ant-design/ant-design#33629] opened 2022-01-08 13:32 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-mgwwp?file=/index.js)

### Steps to reproduce
Resize the view beyond 768px

### What is expected?
the "Right Part" to be `flex: none`, close to the "Left Part"

### What is actually happening?
the "Right Part" still be `flex: auto`

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | react 17.0.2 |
| System | MacOS v12.1 |
| Browser | Edge 95.0.1020.44 |

---
Based on Col API Doc and TypeScript declaration, flex can be passed to responsive props(xs/sm/md/lg...). TS Declaration was added in [this issue](https://github.com/ant-design/ant-design/issues/26553). But actually there is no code to implement this feature.

**Comment by afc163** [comment] 2022-01-10 03:06
Duplicate of #28961

**Closed by afc163** 2022-01-10 03:06 UTC
