### ISSUE TITLE
Table fixed columns doesn't work well with Virtual List(react-window)

### ISSUE THREAD

**Issue by lyx9439** [ant-design/ant-design#30194] opened 2021-04-18 05:16 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xuniliebiao-antd4151-forked-l7wz8?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
打开上面的codesandbox链接，横向滚动表格即可

### What is expected?
A、B列都可以固定

### What is actually happening?
A、B列的left属性都是0，导致重合

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | react@16.9.0 |
| System | macos |
| Browser | Chrome 89.0.4389.128 |

---
将官网的虚拟滚动demo加了两列固定列，即出现此问题。debug发现是因为rc-table/es/Table.js中的updateColsWidths未调用，这个方法是在rc-table/lib/Body/MeasureCell.js中调用的，因为虚拟滚动方案替换了TableBody，导致没有执行，故固定列出现问题。

**Comment by afc163** [comment] 2021-04-18 05:51
Duplicate of #20339

**Comment by afc163** [comment] 2021-04-18 05:51
PR is welcome~

**Closed by afc163** 2021-04-18 05:51 UTC
