### ISSUE TITLE
Reset fields for Form doesnt work on Upload Form Item

### ISSUE THREAD

**Issue by developdeez** [ant-design/ant-design#12719] opened 2018-10-18 22:29 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
reactjs

### Reproduction link
[https://ant.design/components/form/](https://ant.design/components/form/)

### Steps to reproduce
Implement form and use an image upload. Try to reset fields.

### What is expected?
Clear uploads array

### What is actually happening?
Uploads remain

---
Have also tried directly setting to empty.

Code sample (ignore apollo code):

           <FormItem
              label="Image"
              extra="Image for Event banner. Best size: 34x129 px"
              {...formItemLayout}
            >
              {getFieldDecorator("upload", {
                valuePropName: "file",
                getValueFromEvent: this.normFile
              })(
                <Upload
                  disabled={
                    this.props.form.getFieldValue("upload") ? true : false
                  }
                  name="file"
                  action="//jsonplaceholder.typicode.com/posts/"
                  onChange={this.handlePhotoChange}
                  file={this.props.form.upload}
                >
                  <Button>
                    <Icon type="upload" /> Click to Upload
                  </Button>
                </Upload>
              )}
            </FormItem>
            <FormItem labe

**Comment by developdeez** [comment] 2018-10-18 22:58
In fact I don't see form the docs how to even reset many of the form items.
```

   <FormItem label="Load test:">
              {getFieldDecorator("items", {
                initialValue: this.props.items? this.props.items: []
              })(
                <MultiSelectDropdown
                  name="items"
                  placeholder="test items..."
                  handleChange={this.handleChangeSelect}
                  options={options}
                  style={{ width: "100%" }}
                />
              )}
            </FormItem>
```

**Comment by afc163** [comment] 2018-10-23 02:59
Duplicate of #12722

**Closed by afc163** 2018-10-23 02:59 UTC

**Comment by chrismellor529** [comment] 2020-03-07 16:46
Hi, this issue has been resolved? I've really got the same issue.

**Comment by chrismellor529** [comment] 2020-03-08 03:44
Hi, I've solved this issue by just adding destroyOnClose = {true} into Modal.

```
<Modal
    destroyOnClose={true}
    visible={this.state.modalVisible}
    title="Example Modal"
    onOk={this.changeTimeModalHandleOk}
    onCancel={this.changeTimeModalHandleCancel}
>
    ...Dynamic Modal Content Here...
</Modal>

**Comment by sahil3Vedi** [comment] 2020-09-25 07:07
> Hi, I've solved this issue by just adding destroyOnClose = {true} into Modal.
> 
> ```
> <Modal
>     destroyOnClose={true}
>     visible={this.state.modalVisible}
>     title="Example Modal"
>     onOk={this.changeTimeModalHandleOk}
>     onCancel={this.changeTimeModalHandleCancel}
> >
>     ...Dynamic Modal Content Here...
> </Modal>
> ```

This works well, thanks :D
