### ISSUE TITLE
Modal框中提交按钮结束Loading后，Loading图标只是不可见，没有消失

### ISSUE THREAD

**Issue by vVvlife** [ant-design/ant-design#24392] opened 2020-05-22 06:37 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rk7cy?file=/index.js)

### Steps to reproduce
点击打开模态框，再次点击submit，等待结束后，submit按钮上的Loading图标所占的区域并没有消失

### What is expected?
按钮回到不加载的状态

### What is actually happening?
按钮回到不加载的状态，但是多了个图标占位符

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.13.1 |
| System | Linux Ubuntu |
| Browser | Firefox 76.0.1 (64-bit) |

**Comment by afc163** [comment] 2020-05-22 06:39
Duplicate of #24382

**Closed by afc163** 2020-05-22 06:39 UTC
