### ISSUE TITLE
Carousel vertical mode - not work.

### ISSUE THREAD

**Issue by gromov-io** [ant-design/ant-design#27277] opened 2020-10-21 06:46 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/focused-snowflake-7dg59?file=/src/App.js)

### Steps to reproduce
code sanbox..

### What is expected?
https://codesandbox.io/s/zealous-ishizaka-xywkp?file=/src/App.js

### What is actually happening?
https://codesandbox.io/s/zealous-ishizaka-xywkp?file=/src/App.js

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | 16.13.1 |
| System | Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa) |
| Browser | chrome:latest |

---
vertical mode - not work.

**Comment by afc163** [comment] 2020-10-21 14:15
Duplicate of #15449

**Closed by afc163** 2020-10-21 14:15 UTC
