### ISSUE TITLE
SubMenu 在ie11中无法弹出等一系列问题

### ISSUE THREAD

**Issue by huahmj** [ant-design/ant-design#31502] opened 2021-07-23 01:00 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu-cn/](https://ant.design/components/menu-cn/)

### Steps to reproduce
请用ie浏览器打开官方文档查看Menu组件，可以看到如下问题：
1. SubMenu的子菜单无法弹出
2. disabled无法正常显示
3. dark 主题下，Menu样式存在问题

### What is expected?
修复以上问题

### What is actually happening?
1. SubMenu的子菜单无法弹出
2. disabled无法正常显示
3. dark 主题下，Menu样式存在问题

| Environment | Info |
|---|---|
| antd | 4.16.8 |
| React | 17.x |
| System | windows 10 |
| Browser | ie 11 |

**Comment by afc163** [comment] 2021-07-23 01:41
Duplicate of #31283

**Closed by afc163** 2021-07-23 01:41 UTC
Labels: IE | Firefox | Safari, Internet Explorer
