### ISSUE TITLE
Allow keeping in select component its scrollbar visible when the user's mouse goes away

### ISSUE THREAD

**Issue by luccas-specht** [ant-design/ant-design#46989] opened 2024-01-15 19:37 UTC
### Reproduction link

[https://drive.google.com/file/d/1Xd2wgjfjlxdndJevu3tdWuY6vwepmOMV/view?usp=sharing](https://drive.google.com/file/d/1Xd2wgjfjlxdndJevu3tdWuY6vwepmOMV/view?usp=sharing)

### Steps to reproduce

- using select component.
- populate it with elements, perhaps: all countries in the world.
- scrolling the mouse over the elements, then throw it away from the list. The scrollbar will disappear a few seconds later.                 

### What is expected?

it is expected to keep visible, even thought user's mouse mouse goes away.

### What is actually happening?

scrollbar in select component is disappearing.

| Environment | Info |
| --- | --- |
| antd | 4.24.3 |
| React | 17.0.1 |
| System | Ubuntu 22.04.3 |
| Browser | Google Chrome - 117.0.0.0 |

**Comment by afc163** [comment] 2024-01-16 04:31
Duplicate of #28074

**Closed by afc163** 2024-01-16 04:31 UTC
Labels: unconfirmed
