### ISSUE TITLE
Notification 通知提醒框 闪烁抖动的厉害

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#50548] opened 2024-08-23 05:51 UTC
### Reproduction link

[https://ant.design/components/notification-cn](https://ant.design/components/notification-cn)

### Steps to reproduce

https://ant.design/components/notification-cn

看图吧，最新版本不知道为啥闪烁的厉害，早期的版本没这个问题

![noti](https://github.com/user-attachments/assets/01895f67-a630-4af4-803f-b124ccb6af59)

### What is expected?

不要闪烁

### What is actually happening?

这一版本闪烁的很厉害，早期版本没这个问题

| Environment | Info |
| --- | --- |
| antd | 5.20.2 |
| React | 18 |
| System | windows |
| Browser | chrome |

**Comment by kwooshung** [comment] 2024-08-27 20:45
确实有这个问题

**Comment by afc163** [comment] 2024-08-28 02:28
Duplicate of https://github.com/ant-design/ant-design/issues/48608

**Closed by afc163** 2024-08-28 02:28 UTC
Labels: unconfirmed
