### ISSUE TITLE
Menu 组件在 React.StrictMode 模式下，有警告信息

### ISSUE THREAD

**Issue by wanghui2021** [ant-design/ant-design#41077] opened 2023-03-06 01:49 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-76qr0l?file=/index.tsx:1567-1583)

### Steps to reproduce

无

### What is expected?

无警告信息

### What is actually happening?

存在警告信息

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | react@18.2.0 |
| System | macOS 13 |
| Browser | chrome 108.0.5359.124 |

<img width="769" alt="image" src="https://user-images.githubusercontent.com/37385554/223001698-835247d6-9128-4341-9bbe-d661f08f1cb5.png">

**Comment by Yuiai01** [comment] 2023-03-06 01:51
Duplicate of https://github.com/ant-design/ant-design/issues/35361

**Comment by Icemanzzt** [comment] 2023-03-06 03:03
StrictMode的支持情况：https://github.com/ant-design/ant-design/issues/26136

**Comment by afc163** [comment] 2023-03-06 03:05
Duplicate of https://github.com/ant-design/ant-design/issues/35361

**Closed by afc163** 2023-03-06 03:05 UTC
Labels: unconfirmed
