### ISSUE TITLE
Datepicker selected value format does not match current locale

### ISSUE THREAD

**Issue by LoicUV** [ant-design/ant-design#26977] opened 2020-09-30 16:39 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ky0cb)

### Steps to reproduce
- Wrap your datepicker with `ConfigProvider` with a locale (eg `fr_FR`)
- Select a date

### What is expected?
The format of the input value is `DD/MM/YYYY` for `fr_FR`

### What is actually happening?
The format of the input value is always `YYYY-MM-DD`

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | any |
| System | any |
| Browser | any |

---
Should use the locale config from `locale.DatePicker.lang.dateFormat` of ConfigConsumer

**Comment by afc163** [comment] 2020-10-01 04:29
Similar issue as #23902

**Comment by david-soyez** [comment] 2020-10-03 19:09
No it's not similar since you are relating to an old issue using LocalProvider which is deprecated.

**Comment by david-soyez** [comment] 2020-10-03 19:24
I found the issue. the related locale of moment is required.
Here is an example https://codesandbox.io/s/long-feather-s4fsd?file=/index.js
If you comment the moment import it won't work.

**Comment by david-soyez** [comment] 2020-10-04 15:21
Extend DatePicker and pass the format from the locale saved in an AppContext.

```
import React, { useContext } from 'react'
import { DatePicker as DatePickerAnt } from 'antd'
import AppContext from '../utils/appContext'

const DatePicker = ({props}) => {
  const app = useContext(AppContext)
  return (
    <DatePickerAnt format={app.locale.antd.DatePicker.lang.dateFormat} />
  )

}

export default DatePicker

```

**Comment by afc163** [comment] 2020-10-13 03:51
Duplicate of #23902

**Closed by afc163** 2020-10-13 03:51 UTC
