### ISSUE TITLE
在Form表单中使用Select，设置initialValue，当值为null的的时候，不会显示placeholder的内容

### ISSUE THREAD

**Issue by xiaosheng222** [ant-design/ant-design#9839] opened 2018-03-28 03:33 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
2.13.13

### Environment
window， chrome63， antd2.13.13

### Reproduction link
[https://github.com/xiaosheng222](https://github.com/xiaosheng222)

### Steps to reproduce
 <FormItem
                        label="是否存在逾期："
                    >
                        {getFieldDecorator('isOverdue', {
                            rules: [{ required: true, message: '不能为空' }],
                            initialValue: null
                        })(
                            <Select
                                style={{ width: '240px' }}
                                placeholder="请选择"
                            >
                                <Option value="true">是</Option>
                                <Option value="false">否</Option>
                            </Select>
                        )}
</FormItem>

### What is expected?
当initialValue不论为null或者undefined的时候都能够显示placeholder中的内容

### What is actually happening?
只有当值为undefined的时候才会显示

**Comment by afc163** [comment] 2018-03-28 03:40
Duplicate of #2367

**Closed** 2018-03-28 03:40 UTC
Labels: Component: Form
