### ISSUE TITLE
The CSS file to reset component styles drive me into trouble when setting my own styles.

### ISSUE THREAD

**Issue by xuxinhang** [ant-design/ant-design#13886] opened 2018-12-25 10:40 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
A problem about CSS.

### Reproduction link
-

### Steps to reproduce
// JSX
```js
<Card className={styles.myOwnStyle} />
```

// Less
```css
.myOwnStyle {
  margin-bottom: 1em;
}
```

Then, I can't set my own `margin-bottom`,  in case of Ant Design's `<style>` or `<link>` is located before mine. 

In addition, `!important`,  extra selectors or inline-styles might not meet my condition perfectly.

 

### What is expected?
Can some extra styles such as `margin: 0`, `color: xxx` be removed ?

### What is actually happening?
As you know.

**Comment by afc163** [comment] 2018-12-25 10:41
Duplicate of #9363

**Closed by afc163** 2018-12-25 10:41 UTC
