### ISSUE TITLE
Add Week & Day Options to Calendar

### ISSUE THREAD

**Issue by Rocinante89** [ant-design/ant-design#28049] opened 2020-11-27 10:52 UTC
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The calendar component allows users to select month or year. It is not easy to use when there are lots of events on a single day, however. Offering the option to view the calendar for a week or day would be fantastic and really make things simpler for our users. 

### What does the proposed API look like?
The Month/Year options buttons could be changed to a dropdown containing Day/Week/Month/Year, which would display the correct ui based on that selection.

Examples:
![image](https://user-images.githubusercontent.com/8224386/100441549-8e949400-309e-11eb-8b70-59353754e065.png)
![image](https://user-images.githubusercontent.com/8224386/100441572-9ce2b000-309e-11eb-9b64-c3fa956fe325.png)

**Comment by afc163** [comment] 2020-11-27 12:49
Duplicate of #16440

**Closed by afc163** 2020-11-27 12:49 UTC
