### ISSUE TITLE
Bug components/menu in React.18

### ISSUE THREAD

**Issue by duypham90** [ant-design/ant-design#41238] opened 2023-03-14 12:29 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/top-navigation-antd-5-3-1-forked-iwiwt7?file=/index.tsx:102-218)

![image](https://user-images.githubusercontent.com/24804332/225001655-8a1e928d-c988-4cea-aa00-8aeff4fd3668.png)

### Steps to reproduce

Step 1:
```ts
"react": "^18.0.0" => "react": "^18.2.0"
"react-dom": "^18.0.0" => "react-dom": "^18.2.0"
```

Step 2:

Replace by code in index.tsx file as below 
```ts
<React.StrictMode>
createRoot(document.getElementById("container")).render(
  <React.StrictMode>
    <Demo />
  </React.StrictMode>
);
```

### What is expected?

- Do not show Warning: findDOMNode is deprecated in StrictMode.

### What is actually happening?

- Maybe the core wrong

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | 18.2.0 |
| System | N/A |
| Browser | Chrome |

**Comment by MadCcc** [comment] 2023-03-14 12:54
Duplicate of https://github.com/ant-design/ant-design/issues/41223

**Closed by MadCcc** 2023-03-14 12:54 UTC
Labels: unconfirmed
