### ISSUE TITLE
Button 点击报错  render.js:38  Uncaught TypeError: reactRender is not a function

### ISSUE THREAD

**Issue by 2395000206** [ant-design/ant-design#52091] opened 2024-12-23 01:02 UTC
![企业微信截图_17349157188818](https://github.com/user-attachments/assets/a1544515-fb08-4366-917e-58fda76f01ed)
### Reproduction link

[http://localhost:3000/](http://localhost:3000/)

### Steps to reproduce

 "next": "15.1.1" 使用 Button 点击就报错   render.js:38  Uncaught TypeError: reactRender is not a function

### What is expected?

不报错

### What is actually happening?

render.js:38  Uncaught TypeError: reactRender is not a function

| Environment | Info |
| --- | --- |
| antd | 5.22.5 |
| React | 19 |
| next| 15.1.1|
| System | window 11 |
| Browser | 最新 |
![企业微信截图_17349157188818](https://github.com/user-attachments/assets/f3c157bf-113a-4e02-98ba-bc20451c32b1)

**Comment by li-jia-nan** [comment] 2024-12-23 01:39
- #51919

**Comment by 2395000206** [comment] 2024-12-23 02:44
需要使用Next.js 15.1.1版本

**Comment by afc163** [comment] 2024-12-23 03:00
Duplicate of #52080

**Comment by 2395000206** [comment] 2024-12-26 01:06
![企业微信截图_17351750951350](https://github.com/user-attachments/assets/07529568-e5d4-41b1-9539-3f4528402196)

删除了所有更新了，依旧报错
![企业微信截图_17351751569762](https://github.com/user-attachments/assets/cdeee1a5-8e30-4496-aba6-f7cb35b1d354)

**Comment by afc163** [comment] 2024-12-26 01:50
@2395000206 yarn.lock 或 pnpm-lock.yml 或 package-lock.json 都删了么？

**Comment by 2395000206** [comment] 2024-12-26 02:29
> @2395000206 yarn.lock 或 pnpm-lock.yml 或 package-lock.json 都删了么？

是的

**Comment by 2395000206** [comment] 2024-12-26 02:30
> @2395000206 yarn.lock 或 pnpm-lock.yml 或 package-lock.json 都删了么？

而且我看了，这次更新关联的rc-util 内置的也是最新版了

**Comment by afc163** [comment] 2024-12-26 02:44
@2395000206 给个重现?

**Closed** 2024-12-26 03:07 UTC
