### ISSUE TITLE
Modal pops up with the following error message: Blocked aria-hidden on a <div> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus.

### ISSUE THREAD

**Issue by gq123** [ant-design/ant-design#50170] opened 2024-07-31 06:58 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-y9vgcf?file=/index.js)

### Steps to reproduce

Mount the Modal on the body using React DOM, and when it pops up, an error will occur:
Blocked aria-hidden on a <div> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus.

### What is expected?

I hope the console does not report any errors

### What is actually happening?

Console error

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.2 |
| System | macos |
| Browser | chrome |

---
import React from "react";
import ReactDOM from 'react-dom'
import { createRoot } from "react-dom/client";
import { Button, Space, version,Modal } from "antd";
import "antd/dist/antd.css";
import "./index.css";

function renderToBody(element, callback) {
  const container = document.createElement('div')
  document.body.appendChild(container)
  function unmount() {
    const unmountResult = ReactDOM.unmountComponentAtNode(container)
    if (unmountResult && container.parentNode) {
      container.parentNode.removeChild(container)
    }
  }
  ReactDOM.render(element, container, callback)
  return unmount
}

const MyModal = ({onOK}) => {

  return <Modal open  onOk={() => {
    onOK()
  }}>
    123
  </Modal>
}

MyModal.show = () => {
  return new Promise(res => {
    const tempProps = {
      onOK: () => {
        unmount()
      }
    }
    const unmount = renderToBody(<MyModal {...tempProps} />)
  })
}

const App = () => {
  return (
    <div className="App">
      <h1>antd version: {version}</h1>
      <Space>
        <Button type="primary" onClick={async() => {
          await MyModal.show()
        }}>Primary Button</Button>
      </Space>
    </div>
  );
};

const root = createRoot(document.getElementById("root"));
root.render(<App />);

**Comment by afc163** [comment] 2024-07-31 07:58
<img width="1136" alt="图片" src="https://github.com/user-attachments/assets/b844956d-4915-4118-8bb7-6d5f69ce66dc">

Could not reproduce it in your codesandbox.

**Comment by Ymm0008** [comment] 2024-08-01 02:09
使用chrome最新版浏览器，直接打开官网的modal组件就会看到错误。

**Comment by Ymm0008** [comment] 2024-08-01 02:13
使用chrome最新版本浏览器（版本 127.0.6533.88），直接打开官网的antd(4.x版本)  modal组件就会看到错误。

![1](https://github.com/user-attachments/assets/8b96d1a1-a22c-4a6a-9e52-d96116be8194)
@afc163

**Comment by MrFriedRice** [comment] 2024-08-01 07:39
一样 解决了吗

**Comment by leedom-hub** [comment] 2024-08-01 07:40
I have the same question. Please tell me how to dismiss this warning.

**Comment by afc163** [comment] 2024-08-01 14:34
Fixed in https://github.com/react-component/dialog/releases/tag/v9.0.3

You can remove node_modules and all lock files then reinstall node_modules, make sure rc-dialog@9.0.3 is installed.

**Comment by afc163** [comment] 2024-08-01 15:41
Fixed in https://github.com/react-component/dialog/releases/tag/v9.0.4

Please remove lock files and reinstall node_modules.

**Closed by afc163** 2024-08-01 15:41 UTC
Labels: 4.x

**Comment by bohdan-mykhailenko** [comment] 2024-08-05 08:10
Have the same errors when work with Stripe Web elements(card number, etc)

**Comment by qq1871508593** [comment] 2024-08-06 06:45
> Fixed in https://github.com/react-component/dialog/releases/tag/v9.0.4
> 
> Please remove lock files and reinstall node_modules.

I have reinstalled the dependencies and upgraded the ant design vue version from 4.0.7 to 4.2.3 (remove the lock file), but it doesn't work for me

**Comment by afc163** [comment] 2024-08-06 08:35
Here is Ant Design React repoistory, not vue version. @qq1871508593

**Comment by qq1871508593** [comment] 2024-08-06 08:39
> Here is Ant Design React repoistory, not vue version. @qq1871508593

oh, sry sir, I'm stupid

**Comment by yqstart** [comment] 2024-08-19 06:01
![image](https://github.com/user-attachments/assets/d6d74dcc-c81f-476a-9ac4-5d6e21fed723)
![image](https://github.com/user-attachments/assets/f8e7dd35-23a4-4605-ae1b-ef287bd7a4ba)
![image](https://github.com/user-attachments/assets/113eb432-f81f-4415-9da2-061c88f7039c)

**Comment by Linne-Ohara** [comment] 2024-09-27 10:15
div[aria-hidden="true"] {
  display: none;
}

**Comment by revidovich** [comment] 2024-10-31 10:36
Hi there, have the same problem with Tabs component.
It looks good on my desktop:
![image](https://github.com/user-attachments/assets/31dec3a5-b2a8-47fb-8991-b3c7017dca67)  
But on my laptop all icons are blocked:
![image](https://github.com/user-attachments/assets/b5b4759a-8f19-49f7-990f-92c1cf479255)
 (ｅｄｇｅ,ｃｈｒｏｍｅ)     
 Blocked aria-hidden on an element because its descendant retained focus. The focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.

**Comment by grepsoft** [comment] 2025-03-02 12:53
you can also use the inert attribute on the div. Which helps in these situations.

**Comment by tudotubestudio** [comment] 2025-06-06 14:38
The warning “Blocked aria-hidden on an element because its descendant retained focus” happens when an element with aria-hidden="true" still has focus or contains a child that is focused. In other words, you should not hide via aria-hidden any subtree that still holds focus, since screen readers and assistive technology rely on that subtree being exposed. In our situation, the Select component’s trigger remained inside the modal, but its options list was rendered via a Portal outside of the modal’s DOM tree. Because the modal uses aria-hidden to ensure only its own content remains accessible when open, the dropdown list—though visually appearing on top of the modal—was technically outside the modal’s accessibility tree and thus blocked. Even though you could see the blue outline around the dropdown, none of its options could actually receive keyboard focus, leading to this architectural conflict.

To fix it, we applied the following solution:

Problem Insight

The Select component renders its detailed content (the options list) via a <Portal>, placing it outside the modal’s DOM.

The modal, in turn, uses aria-hidden and manages internal focus (TAB navigation), effectively blocking any element considered “outside” of it.

As a result, the Select trigger could be focused inside the modal, but the dropdown list was hidden from assistive technology because it was rendered outside the modal’s tree.

Technical Solution

We introduced a modal={true} prop on SelectContent.

When modal={true}, the Select stops using <Portal> and instead renders within the modal’s own DOM tree, ensuring that the options list remains part of the modal’s accessibility tree.

Any Selects that exist outside of modals continue to use the default behavior (Portal), so this change does not affect other parts of the system.

We also optimized the z-index (for example, z-[60]) when inside modals, making sure the dropdown layers above everything else and is never visually hidden.

Implementation

In components/ui/select.tsx, SelectContent now checks for the modal prop. If it’s true, it skips the <Portal> and injects the dropdown directly into the modal’s DOM tree.

Every modal instance containing a Select has been updated to pass modal={true} to SelectContent.

This maintained 100% compatibility with the rest of the system and introduced zero breaking changes.

With this approach, any Select dropdown inside a modal becomes part of that modal’s accessibility tree, eliminating the aria-hidden conflict and allowing proper keyboard focus and navigation.
