### ISSUE TITLE
DatePicker and RangePicker Year/Month Picker out of viewable range when page is zoomed in

### ISSUE THREAD

**Issue by yichang-bukku** [ant-design/ant-design#48810] opened 2024-05-07 11:52 UTC
### Reproduction link

[https://ant.design/components/date-picker](https://ant.design/components/date-picker)

### Steps to reproduce

1. Go to https://ant.design/components/date-picker
2. Zoom in Page to 125%
3. Select first data picker in https://ant.design/components/date-picker#components-date-picker-demo-basic, popup will be shown.
4. Slowly scroll up, there will be a region where year / month selector is not viewable

<img width="1046" alt="Screenshot 2024-05-07 at 9 51 32 PM" src="https://github.com/ant-design/ant-design/assets/157109083/b74c3b12-e355-43b8-a4b7-c5f996ee7e06">

(This doe not happen in antd v4 where DatePicker and RangePicker popup placement is always at bottom)

### What is expected?

The year / month selector should always be viewable, if not, the placement of popup should automatically be at bottom.

### What is actually happening?

There is a region where year / month selector is not viewable

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | 18.2.0 |
| System | MacOS Ventura 13.1 (22C65) |
| Browser | Brave Browser - Version 1.49.128 Chromium: 111.0.5563.110 (Official Build) (arm64) |

**Comment by MadCcc** [comment] 2024-05-08 09:15
Duplicate of https://github.com/ant-design/ant-design/issues/48694

**Closed by MadCcc** 2024-05-08 09:15 UTC
Labels: unconfirmed
