### ISSUE TITLE
icons is not being treeshaked in 4.0.0 [图标在 4.0.0 没有被按需加载]

### ISSUE THREAD

**Issue by mozkoe** [ant-design/ant-design#21789] opened 2020-03-02 15:43 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://none](https://none)

### Steps to reproduce
1. 新建最小 antd react 项目
2. 配置按需加载
3. 引入 message 组件 (或 breadcrumb, dropdown 等)
4. 打包并使用 webpack bundle analyzer 查看依赖

>
1. Create a bare minimum antd react project
2. Setup webpack treeshaking
3. Import 'message' component (or breadcrumb, dropdown)
4. Build the bundle and inspect it by using webpack bundle analyzer

### What is expected?
只打包使用的图标
Pack the using icons

### What is actually happening?
所有图标都被打包
All icons were packed

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.8.0 |
| System | macos |
| Browser | chrome 80 |

---
通过分析 webpack report.json，许多 antd 组件没有使用按需加载的方式加载 icons。通过 webpack 生成的组件代码中发现很多组件使用 cjs require 引入了整个 `@ant-design/icons` ，导致如果项目中用到了这样的组件，icons都会被整个打包进来。

By analyzing the webpack report.js, it seems that some antd components were not correctly importing the icons package in a treeshaking friendly way. Found that some component using icons package by cjs require, which webpack has to pack the whole icon package to the bundle. If any of these antd components were used in the project, the whole icons package would be packed into the bundle.

```js
var _icons = require("@ant-design/icons");
```

### Icon bundle size

![image](https://user-images.githubusercontent.com/5456835/75689609-6da03d80-5cdc-11ea-92c7-d31cb5b0a87f.png)

### Reasons of @ant-design/icons be imported

![image](https://user-images.githubusercontent.com/5456835/75689388-11d5b480-5cdc-11ea-82d9-8836d77f0173.png)

**Comment by afc163** [comment] 2020-03-02 15:54
Duplicate of #21744

Fixed in #21752

**Comment by afc163** [comment] 2020-03-02 15:54
BTW，最好使用 webpack 4 开启 tree shaking。

**Closed by afc163** 2020-03-02 15:54 UTC
