### ISSUE TITLE
Table sticky double scroll in drawer

### ISSUE THREAD

**Issue by edrmsgl** [ant-design/ant-design#35480] opened 2022-05-10 15:21 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/goofy-shirley-t3qj48?file=/demo.js)

### Steps to reproduce

-

### What is expected?

how can i remove double scroll in table

### What is actually happening?

Double scroll should not appear for table sticky in drawer

| Environment | Info |
| --- | --- |
| antd | 4.20.3 |
| React | 18.1.0 |
| System | Windows 11 |
| Browser | Chrome 101.0.4951.41 |

---
help me

**Comment by afc163** [comment] 2022-05-11 05:24
Duplicate of #33762

**Closed by afc163** 2022-05-11 05:24 UTC
