### ISSUE TITLE
Select  value为空时，placeholder不显示

### ISSUE THREAD

**Issue by zhang504988670** [ant-design/ant-design#14928] opened 2019-02-19 08:43 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vjolk4nz25)

### Steps to reproduce
value为空时，placeholder不显示

### What is expected?
当value为空时，placeholder显示

### What is actually happening?
value为空时，placeholder不显示

| Environment | Info |
|---|---|
| antd | 3.13.4 |
| React | React16.7.0 |
| System | win10 |
| Browser | chrome71.0.3578.80 |

**Comment by zhang504988670** [comment] 2019-02-19 08:47
需要手机判断将value置为undefined才行，望改进。
![image](https://user-images.githubusercontent.com/18161513/53001601-ffd4fb00-3465-11e9-8f85-2f651bcbda52.png)

**Comment by afc163** [comment] 2019-02-19 08:48
Duplicate of #2367

**Comment by afc163** [comment] 2019-02-19 08:49
https://github.com/ant-design/ant-design/issues/11330
#6543

**Closed by afc163** 2019-02-19 08:49 UTC

**Comment by snaildarter** [comment] 2019-10-30 03:56
> 需要手机判断将value置为undefined才行，望改进。
> ![image](https://user-images.githubusercontent.com/18161513/53001601-ffd4fb00-3465-11e9-8f85-2f651bcbda52.png)
直接赋值为 undefined 感觉好一点
