### ISSUE TITLE
Select component drop-down menu position display is abnormal on scroll div area

### ISSUE THREAD

**Issue by Southhill** [ant-design/ant-design#8661] opened 2017-12-19 05:35 UTC
### Version
2.13.3

### Environment
Mac Chrome react@15.6.1

### Reproduction link
[https://codesandbox.io/s/m9o5m7y498](https://codesandbox.io/s/m9o5m7y498)

### Steps to reproduce
on scroll div area(not document.body area)， click Select componet, show drop-down menu, scrolling div, drop-down menu and Select component  start separate(点击Select组件后，滚动div区域，下拉菜单和Select组件分离了)

### What is expected?
scrolling div, drop-down menu and Select component  is positon relative and not changed distance（滚动div区域，下拉菜单和Select组件的距离是不变的）

### What is actually happening?
scrolling div, drop-down menu and Select component  start separate(滚动div区域，下拉菜单和Select组件分离了)

**Comment by afc163** [comment] 2017-12-19 05:36
Duplicate of #8268

**Closed by afc163** 2017-12-19 05:36 UTC
