### ISSUE TITLE
所有页面的代码都打不开了

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#15924] opened 2019-04-08 04:14 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/button-cn/](https://ant.design/components/button-cn/)

### Steps to reproduce
打开官网，点击组件下面的展开代码按钮，不能展开代码

### What is expected?
能够展开代码

### What is actually happening?
不能展开代码

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.8.4 |
| System | windows10 |
| Browser | chrome73 |

**Comment by XianZhengquan** [comment] 2019-04-08 04:14
![image](https://user-images.githubusercontent.com/46179450/55698330-e11bcb00-59f7-11e9-8f95-a94af6fe0a1a.png)
两种方式均失效，

**Comment by XianZhengquan** [comment] 2019-04-08 04:16
火狐能够打开

**Comment by ztplz** [comment] 2019-04-08 04:22
![image](https://user-images.githubusercontent.com/17755202/55698532-e0376900-59f8-11e9-8e37-d00cf76fd1fe.png)
可以啊   Mac   chrome

**Comment by XianZhengquan** [comment] 2019-04-08 04:23
win10 ，刷新了很多遍，还是打不开

**Comment by XianZhengquan** [comment] 2019-04-08 04:28
好了，可以打开了，不知道什么原因

**Comment by lwg529** [comment] 2019-04-08 06:18
依然打不开呢

**Comment by ztplz** [comment] 2019-04-08 06:40
@zombieJ  win10 试下

**Comment by zhichao8756** [comment] 2019-04-08 06:48
遇到了同样的问题

**Comment by zombieJ** [comment] 2019-04-08 10:03
Duplicate of #15929

**Closed by zombieJ** 2019-04-08 10:03 UTC

**Comment by 1084350607** [comment] 2020-04-15 10:50
the same question,is there anybody solve it?

**Comment by yoyo837** [comment] 2020-04-15 10:54
> the same question,is there anybody solve it?

I tried it just now and it works.
