### ISSUE TITLE
[ConfigProvider] Ability to config components icons

### ISSUE THREAD

**Issue by amir2mi** [ant-design/ant-design#51269] opened 2024-10-16 14:08 UTC
### What problem does this feature solve?

I'm making customizations to Ant Design and one of the main aspects is icons. I searched for this, but it seems there is no way to customize each component icons.
For example, I need to change arrow icon of select component, currently the only way to change it is passing the `suffixIcon` prop, this way forces me to create a wrapper function for each component.
A more scalable way would be able to config icons in `<ConfigProvider />`.

### What does the proposed API look like?

```ts
<ConfigProvider 
   theme={{
       token: {
            Select: {
                 suffixIcon: <CustomIcon />
            }
       }
   }}
>
...
</ConfigProvider>
```

**Comment by afc163** [comment] 2024-10-17 01:58
Duplicate of https://github.com/ant-design/ant-design/issues/41413

**Closed by afc163** 2024-10-17 01:58 UTC
Labels: unconfirmed
