### ISSUE TITLE
Menu component not adaptive in flex container

### ISSUE THREAD

**Issue by skolkovsky** [ant-design/ant-design#30833] opened 2021-06-02 21:58 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/skolkovsky/antd-menu-component](https://github.com/skolkovsky/antd-menu-component)

### Steps to reproduce
Just resize screen

### What is expected?
Menu component collapse. And after restore in init screen all items are visible

### What is actually happening?
Menu component ignore adaptive rules

| Environment | Info |
|---|---|
| antd | 4.15.4 |
| React | 17.0.2 |
| System | macOS Big Sur |
| Browser | Chrome, Safari, Mozilla |

**Comment by afc163** [comment] 2021-06-03 03:46
Duplicate of #30813

**Closed by afc163** 2021-06-03 03:46 UTC
