### ISSUE TITLE
select组件选中状态或者hover状态时，滚动滚动条，滚动条经过选中状态时，会被选中状态图层遮盖，导致看不到滚动条

### ISSUE THREAD

**Issue by bruceliu68** [ant-design/ant-design#25759] opened 2020-07-22 11:54 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
select组件选中状态或者hover状态时，滚动滚动条，滚动条经过选中状态时，会被选中状态图层遮盖，导致到不到滚动条

### What is expected?
滚动条不被遮盖

### What is actually happening?
滚动条被遮盖

| Environment | Info |
|---|---|
| antd | 4.4.3 |
| React | 16.13.1 |
| System | Macos 10.13 |
| Browser | chrome:83.0.4103.116 |

**Comment by afc163** [comment] 2020-07-22 15:51
Duplicate of https://github.com/ant-design/ant-design/issues/23107

**Closed by afc163** 2020-07-22 15:51 UTC
