### ISSUE TITLE
Slider Tooltip is scrolling with the main scroll container on fixed elements

### ISSUE THREAD

**Issue by leifmarcus** [ant-design/ant-design#13030] opened 2018-11-08 10:46 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.4

### Environment
MacOS Mojave (10.14), Chrome Browser (70.0.3538.77), react version 16.5.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j1wrrk635)

### Steps to reproduce
click the link to the reproduction provided codesandbox.io

1. drag the slider on the slider module
2. wile the tooltiop is open, start scrolling the page

### What is expected?
the tooltip should stay at the same position

### What is actually happening?
the tooltip scrolls with the main page

**Comment by zy410419243** [comment] 2018-11-10 13:30
Why not change `position: fixed` to `position: absolute`?

**Comment by zombieJ** [comment] 2018-11-10 15:47
duplicate of #3438

**Closed by zombieJ** 2018-11-10 15:47 UTC

**Comment by leifmarcus** [comment] 2019-01-09 14:49
This is a different topic than addressed in #3438. I hope this can be opened again, because the tooltip does not have the option to declare a scroll container as the select field has

**Comment by zombieJ** [comment] 2019-01-09 14:57
These popup is use same Trigger component. `getPopupContainer` also works on the tooltip of slider: https://codesandbox.io/s/9yy6k3qkwo
