### ISSUE TITLE
antd table rowSelection onChange event selectedRows undefined

### ISSUE THREAD

**Issue by Even-Lau** [ant-design/ant-design#24243] opened 2020-05-18 04:19 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/selection-and-operation-ant-design-demo-hrpee?file=/index.js)

### Steps to reproduce
1. select a row on page 1
2. select a row on page 2
3. the first selected row will be undefined, the console log in the terminal will be like this {
selectedRowKeys: (2) [8, 14]
selectedRows: (2) [undefined, {…}]
}

### What is expected?
selected rows should not be undefined

### What is actually happening?
if the selectedRows are from different page, those selectedRows are not from current page will be undefined

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.13.1 |
| System | Windows10 |
| Browser | Google Chrome Version 81.0.4044.138 (Official Build) (64-bit) |

**Comment by afc163** [comment] 2020-05-18 04:22
Duplicate of #7942

**Closed by afc163** 2020-05-18 04:22 UTC

**Comment by zhangtsh5** [comment] 2020-08-27 06:54
why my selectedRowKeys have the same problem? selectedRowKeys only contain the currentPage
