### ISSUE TITLE
v4 Form values types

### ISSUE THREAD

**Issue by myzaree** [ant-design/ant-design#25760] opened 2020-07-22 12:15 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-95zxt?file=/src/App.tsx)

### Steps to reproduce
Actually everything work fine right now, except for values that are coming from "onFinish" and "form.validateFields().then(values)" are being "any" type.

### What is expected?
Being able to set Form values types like we did it previously like "const WrapperForm = Form.create\<FormProps\>()(LoginForm);"

### What is actually happening?
Values are being "Store" type  ---  { [name: string]: any }

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | ^16.12.0 |
| System | macOS High Sierra  |
| Browser | Google Chrome Version 84.0.4147.89 (Official Build) (64-bit) |

---
Sorry if I skipped any obvious thing that could be done, but I came back to antd after a long time of not using it.
I couldnt find a way to set form values types and eslint is screaming for breaking no-unsafe-assignment rule.

**Comment by zombieJ** [comment] 2020-07-23 03:35
Duplicate of #21195

**Closed by zombieJ** 2020-07-23 03:35 UTC
