### ISSUE TITLE
Form dynamic setFields Error 

### ISSUE THREAD

**Issue by satanYuTeng** [ant-design/ant-design#21962] opened 2020-03-07 03:35 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/form-cn/#components-form-demo-dynamic-form-item](https://3x.ant.design/components/form-cn/#components-form-demo-dynamic-form-item)

### Steps to reproduce
{getFieldDecorator(`names[${k}]`, {
          validateTrigger: ['onChange', 'onBlur'],
          rules: [
            {
              required: true,
              whitespace: true,
              message: "Please input passenger's name or delete this field.",
            },
          ],

this.props.form.setFields({
        names:{
          value:[1,1],
          errors:[new Error('test')]
        }
   });

对 names 使用 setFields 会报错
Warning: You cannot set a form field before rendering a field associated with the value.

### What is expected?
setFields 可以对 数组形式的装饰字段使用

### What is actually happening?
对 names 使用 setFields 会报错
Warning: You cannot set a form field before rendering a field associated with the value.

| Environment | Info |
|---|---|
| antd | 3.26.12 |
| React | 16.6 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment] 2020-03-07 07:09
Duplicate of #8880

Don't forget `getFieldDecorator('names', { initialValue: [] });` before using `setFields`.

**Closed by afc163** 2020-03-07 07:09 UTC

**Comment by satanYuTeng** [comment] 2020-03-07 08:26
![image](https://user-images.githubusercontent.com/17904882/76139932-4e186480-6090-11ea-99cf-64baef472399.png)
使用 getFieldDecorator('names', { initialValue: [] }) 会得到另外一个错误
Warning: One field name cannot be part of another, e.g. `a` and `a.b`. Check field: names[0]

**Comment by satanYuTeng** [comment] 2020-03-07 08:27
并没有解决问题

**Comment by satanYuTeng** [comment] 2020-03-07 09:14
> ![image](https://user-images.githubusercontent.com/17904882/76139932-4e186480-6090-11ea-99cf-64baef472399.png)
> 使用 getFieldDecorator('names', { initialValue: [] }) 会得到另外一个错误
> Warning: One field name cannot be part of another, e.g. `a` and `a.b`. Check field: names[0]

getFieldDecorator('names', { initialValue: [] }); 这句话加在 render() 里面也是一样的结果

**Comment by afc163** [comment] 2020-03-07 12:43
#8806

**Comment by yanlee26** [comment] 2020-09-30 08:58
not work yet [codepen.io](https://codepen.io/yanlee26/pen/ExKzErM?editors=0011)
