### ISSUE TITLE
form.validateFields throws error without any error in fields

### ISSUE THREAD

**Issue by piyushk96** [ant-design/ant-design#43976] opened 2023-08-02 14:47 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zealous-violet-9htvk7?file=/src/App.js)

### Steps to reproduce

Refresh the browser and check codesandbox browser's console

### What is expected?

No error should be present

### What is actually happening?

Form validation error is printed with empty `errorFields` array

| Environment | Info |
| --- | --- |
| antd | 5.8.1 |
| React | 18.2.0 |
| System | MacOS v12.5 |
| Browser | Firefox v115 |

**Comment by zombieJ** [comment] 2023-08-02 14:51
`outOfDate` mark means your current validation is Out Of Date. Which is not the latest validation.

**Comment by piyushk96** [comment] 2023-08-02 14:52
But it should not throw when errorFields is empty

**Comment by zombieJ** [comment] 2023-08-02 14:57
It's by design. All the walking validation will be marked as failed in case value change during the validation.

React will call `useEffect` twice in StrictMode, the StrictMode is design for developer to handle clean up for each OOD effect. You should follow React life cycle to handle this. And filter this is not hard:

https://codesandbox.io/s/vibrant-lamarr-nm3x5p?file=/src/App.js

**Closed by zombieJ** 2023-08-02 14:57 UTC
Labels: unconfirmed
