### ISSUE TITLE
Table组件的columns设置多个render后，任意hover某个单元格会触发所有的render

### ISSUE THREAD

**Issue by boylonghui** [ant-design/ant-design#33565] opened 2022-01-05 09:44 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fixed-header-and-scroll-bar-with-the-page-antd-4-17-2-forked-2ej6j?file=/index.js)

### Steps to reproduce
1. columns设置多个render
2. 鼠标hover任意单元格
3. 查看控制台信息，可以看到触发了所有定义的render

### What is expected?
只触发对应的render

### What is actually happening?
触发了所有的render

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 17.0.2 |
| System | Safari |
| Browser | chrome 96.0.4664.110 |

**Comment by afc163** [comment] 2022-01-05 11:55
Duplicate of #32979

**Closed by afc163** 2022-01-05 11:55 UTC
