### ISSUE TITLE
Modify extra variables with CSS Variables (Dynamic Theme)

### ISSUE THREAD

**Issue by silveriodti** [ant-design/ant-design#33178] opened 2021-12-06 15:43 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, if you are using dynamic theming with CSS Variables, which was recently released with AntD 4.17.0, you only have a few options of variables that you can customize using the Config Provider.

The ConfigProvider and it's config function only accept as input a bunch of color properties. But it would also be very useful to be able to modify other variables, such as "border-radius-base"or "font-size-base".

Even if you were not to modify those variables dinamically, it would be nice to be able to change them like you would if you were using a less loader, for example.

We are migrating from Less to CSS Variables, since it is the only solution that is working for dynamic theming on a GatsbyJS solution. But now we have more variables that we would like to customize and don't know how.

### What does the proposed API look like?
ConfigProvider.config({
        theme: {
          primaryColor: `#FFFFFF`,
          ...
          borderRadiusBase: '5px',
          fontSizeBase: '14px'
          ...
          (and so on for every style variable that you can change on a less loader, for example)
        }
      })

Or add documentation on how you can achieve this level of customisation by other means, like using babel or something. But it is important to be with CSS Variables (for Less there is a lot of docs already).

**Comment by afc163** [comment] 2021-12-07 01:58
Duplicate of #32807

**Closed by afc163** 2021-12-07 01:58 UTC
