### ISSUE TITLE
In ie11 browser, when click select component, it will flash once

### ISSUE THREAD

**Issue by realEago** [ant-design/ant-design#24395] opened 2020-05-22 07:16 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/EAGooo/pen/KKdJxOZ?editable=true](https://codepen.io/EAGooo/pen/KKdJxOZ?editable=true)

### Steps to reproduce
In ie11 browser, when click select component, it will flash once

### What is expected?
dont flash

### What is actually happening?
click once, flash once

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | react@16.x |
| System | windows10 |
| Browser | IE11 |

**Comment by afc163** [comment] 2020-05-22 07:19
Duplicate of #21039

**Closed by afc163** 2020-05-22 07:19 UTC
