### ISSUE TITLE
Add Speed Dial Component

### ISSUE THREAD

**Issue by an-tex** [ant-design/ant-design#25932] opened 2020-07-31 07:20 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

(Actually it is a duplicate of https://github.com/ant-design/ant-design/issues/12251, but it was closed as it was not conforming to the issue requirements)

### What problem does this feature solve?
When there are multiple "quick actions", a speed dial can hide the complexity while still allow the user to access all actions. Please refer to [Material-UI SpeedDial](https://material-ui.com/components/speed-dial/) for examples. 

### What does the proposed API look like?
```html
<SpeedDial>
  <SpeedDial.Item>Add to favourites</Menu.Item>
  <SpeedDial.Item>Share</Menu.Item>
  <SpeedDial.Item>Print</Menu.Item>
  <SpeedDial.Item>Add to favourites</Menu.Item>
  <SpeedDial.Item>Copy Link</Menu.Item>
</SpeedDial>
```

**Comment by afc163** [comment] 2020-07-31 07:22
Duplicate of #12738

**Closed by afc163** 2020-07-31 07:22 UTC

**Comment by an-tex** [comment] 2020-07-31 08:38
Hi, this is not just a floating Button. It's mainly about the opening menu once you click/hover it. Please have a look at the example (it's also a separate component in mui)

**Comment by afc163** [comment] 2020-07-31 08:39
I consider it as a special interaction of Floating Button.

**Comment by an-tex** [comment] 2020-07-31 08:41
It can be implemented on top of a normal Button, it's not about it being floating. It's rather like a dropdown Menu

**Comment by AbolfazlHeidarpour** [comment] 2022-11-04 08:47
Is it implemented yet?
