### ISSUE TITLE
Gutter create a bigger object than container, it makes a unwanted scroll

### ISSUE THREAD

**Issue by cesarve77** [ant-design/ant-design#25011] opened 2020-06-15 21:32 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cool-lederberg-nni33)

### Steps to reproduce
scroll left

### What is expected?
nos croll bar created

### What is actually happening?
gutter create a scroll in body

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | N/A |
| System | osx 10.14.5 (18F132) |
| Browser | All |

**Comment by afc163** [comment] 2020-06-16 00:08
Duplicate of #10144

**Closed by afc163** 2020-06-16 00:08 UTC

**Comment by cesarve77** [comment] 2020-06-16 06:15
Sorry I did not find it.
But why is it closed?

**Comment by rodrigograca31** [comment] 2020-07-01 19:57
@cesarve77 very good question I also think the other issue should not be closed.
