### ISSUE TITLE
请问现在的时间选择组件可以选择多个时间点吗？

### ISSUE THREAD

**Issue by 285858315** [ant-design/ant-design#26914] opened 2020-09-27 01:48 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以选择多个时间点

### What does the proposed API look like?
可以选择多个时间点

**Comment by yoyo837** [comment] 2020-09-27 01:55
意思是。类似Select的多选交互，但是选的内容是日历的时间？

**Comment by afc163** [comment] 2020-09-28 06:43
Duplicate of #4447

**Closed by afc163** 2020-09-28 06:43 UTC
