### ISSUE TITLE
Button with 'href' attribute cause an unexpected warning 

### ISSUE THREAD

**Issue by AndyLL** [ant-design/ant-design#18225] opened 2019-08-12 09:33 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-button-bug-stmyg?from-embed)

### Steps to reproduce
in the CodeSandbox page 
1. click project view switch 
2. if no warning shown click inner page refresh button 

### What is expected?
no warning shown

### What is actually happening?
Button with href attribute cause an unexpected warning, remove href can solve the issue. 

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | latest |
| System | latest macOS  |
| Browser | chrome |

**Comment by afc163** [comment] 2019-08-12 09:44
Duplicate of #18205

**Closed by afc163** 2019-08-12 09:44 UTC
