### ISSUE TITLE
modal 组件再严格模式下的警告 index.js:1451 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

### ISSUE THREAD

**Issue by chenjiajing23** [ant-design/ant-design#31181] opened 2021-06-29 07:04 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost:32000/zh_CN/ProjectConfig/412/ocr/OCR-99999999999](http://localhost:32000/zh_CN/ProjectConfig/412/ocr/OCR-99999999999)

### Steps to reproduce
本地开发环境运行，并开启React严格模式 "StrictMode"，并开启modal弹框

### What is expected?
不报警告

### What is actually happening?
index.js:1451 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
![截屏2021-06-29 14 54 36](https://user-images.githubusercontent.com/41351722/123752335-431fbe00-d8eb-11eb-9187-6ad89493bd20.png)

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17.0.1 |
| System | mac os 11.4 |
| Browser | chrome / 91.0.4472.114 |

---
index.js:1451 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

**Comment by yoyo837** [comment] 2021-06-29 07:24
Duplicate of #26136

**Closed by yoyo837** 2021-06-29 07:24 UTC
