### ISSUE TITLE
js error don't show obviously inside antd's form component validator 

### ISSUE THREAD

**Issue by lcl22hope** [ant-design/ant-design#26382] opened 2020-08-25 06:39 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/compassionate-visvesvaraya-2ie0i?file=/index.js)

### Steps to reproduce
open demo, click 'Register' Button, the JS error which inside form.Item's validator don't show in web browser console.

### What is expected?
I think such these errors or warning should not be caught inside form component, if this behavior exists, our developer may waste much time in debugging those problems. 

### What is actually happening?
js error inside validator function, don't show obviously

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | ^16.9.25 |
| System | Mac OS |
| Browser | Chrome version 84.0.4147.135 (Official Build) (64-bit)  |

**Comment by afc163** [comment] 2020-08-25 06:51
See https://ant.design/components/form/#Custom-validator-not-working and https://github.com/react-component/field-form/pull/35

**Comment by afc163** [comment] 2020-08-25 06:52
@zombieJ Any chance to throw error without try catch? It is confused for developers.

**Comment by afc163** [comment] 2020-08-25 06:52
Duplicate of #10718

**Comment by zombieJ** [comment] 2020-08-25 07:11
We do not maintain v3 any longer. Pls upgrade to v4 instead. New Form support to show error in console:

<img width="536" alt="截屏2020-08-25 下午3 10 35" src="https://user-images.githubusercontent.com/5378891/91143447-21f7ab00-e6e5-11ea-8b70-274517b95428.png">


ref: https://codesandbox.io/s/objective-cannon-f8qh3?file=/index.js

**Closed by zombieJ** 2020-08-25 07:11 UTC

**Comment by lcl22hope** [comment] 2020-08-26 11:26
> upgrade

Thx for your reply, by the way, to upgrade antd version is a great solution for this case. But our project exits for many years, It's hard to just upgrade antd.
