### ISSUE TITLE
table 没有渲染出bool 类型的值

### ISSUE THREAD

**Issue by poyiding** [ant-design/ant-design#24583] opened 2020-05-29 10:14 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenyongfa-ant-design-demo-ur2j0)

### Steps to reproduce
见 codesandbox 

### What is expected?
record 对象的值是bool 类型值时，能渲染出true 或者false , 现在是通过自己render: text => `${text}` 来渲染true 或者 false

### What is actually happening?
没有渲染出对应的bool类型的值

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | ^16.12.0 |
| System | mac  |
| Browser | chrom |

**Comment by afc163** [comment] 2020-05-29 10:15
Duplicate of #24427

**Closed by afc163** 2020-05-29 10:15 UTC
