### ISSUE TITLE
hope the Modal component to add drag functionality.

### ISSUE THREAD

**Issue by completeAutumn** [ant-design/ant-design#8897] opened 2018-01-10 02:51 UTC
### What problem does this feature solve?
Some requirements scenarios may pop up multiple Modal，or be required to have a drag functionality.

### What does the proposed API look like?
drag=true

**Comment by yesmeck** [comment] 2018-01-10 02:54
Duplicate of #3012 #374

**Closed** 2018-01-10 02:54 UTC

**Comment by xiabingwu** [comment] 2018-05-04 08:38
https://codesandbox.io/s/n3x23qxrm4 @completeAutumn

**Comment by dazhi007** [comment] 2019-02-15 08:49
en-us:
Here is an "ant-design-draggable-modal" provided by a foreigner, supporting drag and drop，[ant-design-draggable-modal](https://github.com/DylanVann/ant-design-draggable-modal)

zh-cn:
这里是一个老外提供的“ant-design-draggable-modal”,支持拖拽;[ant-design-draggable-modal](https://github.com/DylanVann/ant-design-draggable-modal)
