### ISSUE TITLE
RangePicker无法知道用户当前要选择的是起期还是止期

### ISSUE THREAD

**Issue by FloaJa** [ant-design/ant-design#33339] opened 2021-12-17 07:27 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
场景是起期禁止选择大于今日, 止期需要在起期之后, 也就是需要分别限制禁止选择日期, disabledDate是不能满足这个需求的, 我想要二次封装, 但是我无法获取当前用户在选择起期还是止期

### What does the proposed API look like?
disabledDate可以分为beginDisabledDate和endDisabledDate, 分别控制, 或者onOpenChange中告诉我用户要选择的是起期还是止期

**Comment by afc163** [comment] 2021-12-17 08:53
Duplicate of #33237

**Closed by afc163** 2021-12-17 08:53 UTC
