### ISSUE TITLE
Icon prop for Tree.TreeNode

### ISSUE THREAD

**Issue by Nouzbe** [ant-design/ant-design#8060] opened 2017-10-30 10:38 UTC
### What problem does this feature solve?
The icons displayed on the left of TreeNodes are either carets or [+] / [-] and file icons, based on the value of the Tree's showLine prop.

With this feature, these icons could be customized at the TreeNode level.
An example of use case could be a Tree that represents a file-system directory. It would be possible to display for each node an icon based on the extension of the file it represents (like Visual Studio's file explorer does)

### What does the proposed API look like?
The TreeNode could have an `icon` prop which value would be a React.Component rendering the icon. A second step is that this component could have an `open` prop itself so that we could control its render based on the fact that the node is open or closed.

```javascript
const MyIcon = props => props.open ? <Svg1/> : <Svg2/>

MyIcon.propTypes = {
    open: PropTypes.bool
}
...
    render() {
        return <TreeNode icon={MyIcon} />
    }
```

**Comment by benjycui** [comment] 2017-10-31 03:31
Duplicate of https://github.com/ant-design/ant-design/issues/779

**Closed by benjycui** 2017-10-31 03:31 UTC
