### ISSUE TITLE
Allow elements other than Option in Select's children

### ISSUE THREAD

**Issue by otakustay** [ant-design/ant-design#9150] opened 2018-01-28 12:23 UTC
### What problem does this feature solve?
Currently `Select` only accepts `Option` and `OptGroup` as its children, however in some cases we need more elements to visually customize the dropdown, for example we can add a `Divider` between two options:

```
|-----------------|
| Select all      |
|-----------------|
| Value A         |
| Value B         |
|-----------------|
```

### What does the proposed API look like?

We can be really excited to have this features supported like:

```
<Select>
  <Optionn value="all">Select All</Option>
  <Divider>
  <Option value="a">Value A</Option>
  <Option value="b">Value B</Option>
</Select>
```

`Select` can filter all `Option` and `OptGroup` elements to collect values and keys, and still keep other elements in its own place

**Comment by yesmeck** [comment] 2018-01-28 14:25
Duplicate of #4853

**Closed by yesmeck** 2018-01-28 14:25 UTC
Labels: Component: Select

**Comment by Namek** [comment] 2021-08-06 10:00
> Duplicate of #4853

@yesmeck how is this a duplicate?

**Comment by colonel-badmotherfucker** [comment] 2024-06-12 11:07
@yesmeck  how is it duplicate ?
