### ISSUE TITLE
Tree Component - Draggable demo / When there is a lot of node data, the node draggable styles are delayed.[树节点拖拽延迟与类名残留]

### ISSUE THREAD

**Issue by justtio** [ant-design/ant-design#25513] opened 2020-07-08 13:31 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/broken-resonance-teqlc?file=/src/App.js)

### Steps to reproduce
1. prepare data
2. set the hight = {420}
3. drag the node

### What is expected?
The node styles sticky with the draged tree item without any delay and wrong styles left.
树节点拖拽没有样式渲染延迟，并且没有残留的类名（样式）。

### What is actually happening?
The draged node styles show a big delay issue when we drag the tree node.
数据较多时，树节点拖拽出现明显延迟，且释放的节点位置的item会残留类名。

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | react |
| System | os |
| Browser | chrome  and firefox latest version |

---
数据较多时，节点拖拽时会显得非常不流畅。

---
效果图
![issue](https://user-images.githubusercontent.com/24400225/86924639-4feb5500-c162-11ea-917d-a304f3b55405.gif)

**Comment by afc163** [comment] 2020-07-08 14:00
Duplicate of #24380

**Closed by afc163** 2020-07-08 14:00 UTC
