### ISSUE TITLE
upload上传多个文件多次调用接口

### ISSUE THREAD

**Issue by wl95** [ant-design/ant-design#17914] opened 2019-07-26 05:24 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
同时选中多个文件上传

### What is expected?
上传多个文件 只调用一次接口

### What is actually happening?
upload上传多个文件多次调用接口

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 11 |
| System | 11 |
| Browser | 11 |

**Comment by zombieJ** [comment] 2019-07-28 16:18
duplicate of #8579

**Closed by zombieJ** 2019-07-28 16:18 UTC
