### ISSUE TITLE
InputNumber component not working as expected

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [ant-design/ant-design#30557] opened 2021-05-17 14:56 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-vm1rta?file=index.js](https://stackblitz.com/edit/react-vm1rta?file=index.js)

### Steps to reproduce
Visit the reproduction url and enter alphabets. 

### What is expected?
It should not accept alphabets

### What is actually happening?
It is actually accepting alphabets

| Environment | Info |
|---|---|
| antd | 4.15.5 |
| React | 17.0.0 |
| System | mac |
| Browser | Chrome |

---
This is reproducible in the examples shown in the antd component documentation

**Comment by afc163** [comment] 2021-05-18 02:52
Duplicate of #9421

**Closed by afc163** 2021-05-18 02:52 UTC
