### ISSUE TITLE
图片预览功能

### ISSUE THREAD

**Issue by q5222777** [ant-design/ant-design#22740] opened 2020-03-30 07:44 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
图片预览功能

### What does the proposed API look like?
<xxxx   src="xxxx.png"  />

**Comment by afc163** [comment] 2020-03-30 07:46
Duplicate of #13719

**Closed by afc163** 2020-03-30 07:46 UTC
