### ISSUE TITLE
Radio和Select组合使用，select已有值的情况下，点击select，下拉框会迅速消失

### ISSUE THREAD

**Issue by haoforliu** [ant-design/ant-design#28171] opened 2020-12-03 08:45 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/radioheselectzuheshiyong-fgu8t)

### Steps to reproduce
先选择Radio的more选项，点击select选择任意值，再次点击select时，select的下拉框会瞬间消失

### What is expected?
这种情形下，select的下拉框不会弹出后再消失

### What is actually happening?
这种情形下，select的下拉框会弹出后再消失

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 16.14.0 |
| System | windows10 |
| Browser | Chrome 86 |

**Comment by afc163** [comment] 2020-12-03 09:18
Duplicate of #25959

**Closed by afc163** 2020-12-03 09:18 UTC
