### ISSUE TITLE
【DatePicker】禁用某个日期段没有把年份一起禁用

### ISSUE THREAD

**Issue by ppjjzz** [ant-design/ant-design#17854] opened 2019-07-24 09:50 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/exciting-fog-ln1u1)

### Steps to reproduce
function disabledDate(current) {
  // Can not select days before today and today
  return current && current < moment("2017", "YYYY");
}
禁用2017年以前所有日期
![image](https://user-images.githubusercontent.com/26438223/61784057-8fc70880-ae3b-11e9-9910-74f7f036f0bc.png)

### What is expected?
不能选择的年份也一起禁用掉

### What is actually happening?
不能选的年份没有禁用

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | 16 |
| System | mac |
| Browser | Chrome |

**Comment by afc163** [comment] 2019-07-24 11:12
Duplicate of #9008

**Closed by afc163** 2019-07-24 11:12 UTC

**Comment by Pangnz** [comment] 2019-07-31 07:46
has the problem been solved?  I have the same problem.  -o-
