### ISSUE TITLE
type check issue in Form.d.ts file  

### ISSUE THREAD

**Issue by guissy** [ant-design/ant-design#7212] opened 2017-08-14 23:37 UTC
### Version
2.12.6

### Environment
osx

### Reproduction link
[https://codepen.io/guissy/pen/OjxOLx](https://codepen.io/guissy/pen/OjxOLx)

### Steps to reproduce
```
import {connect} from 'dva';
import { Form } from 'antd';
import * as React from 'react';
import { FormComponentProps, WrappedFormUtils } from 'antd/lib/form/Form';

@connect(({ indexPage }: any) => ({ indexPage }))
@Form.create()
export default class IndexPage extends React.PureComponent<IndexPageProps, any> {
  constructor(props: IndexPageProps) {
    super(props);
    this.state = {};
  }
  public render() {
    const { indexPage } = this.props;
    return (
      <div>IndexPage Works!</div>
    );
  }
}

interface IndexPageProps extends ReduxProps, FormComponentProps {
  form: WrappedFormUtils;
  indexPage?: any;
}
```
Error:(9, 1) TS1238:Unable to resolve signature of class decorator when called as an expression.
  Type 'ComponentClass<{}>' is not assignable to type 'typeof IndexPage'.
    Type 'Component<{}, ComponentState>' is not assignable to type 'IndexPage'.
      Types of property 'render' are incompatible.
        Type '() => false | Element' is not assignable to type '() => Element'.
          Type 'false | Element' is not assignable to type 'Element'.
            Type 'false' is not assignable to type 'Element'.

### What is expected?
Form.d.ts line 96 - 98:
export interface ComponentDecorator<TOwnProps> {
    (component: React.ComponentSpec<FormComponentProps & TOwnProps>): React.ComponentClass<TOwnProps>;
}

### What is actually happening?
Form.d.ts line 96 - 98:
export interface ComponentDecorator<TOwnProps> {
    (component: React.ComponentClass<FormComponentProps & TOwnProps>): React.ComponentClass<TOwnProps>;
}

---
React.ComponentClass change to  React.ComponentSpec, it works

**Comment by benjycui** [comment] 2017-08-15 01:30
I think your issue is duplicate of https://github.com/ant-design/ant-design/issues/6489

You can post you solution in https://github.com/ant-design/ant-design/issues/6489 , so that others can try, if it works, we can fix it in next version, thanks!

**Closed by benjycui** 2017-08-15 01:30 UTC
