### ISSUE TITLE
Datetime picker not responsive in mobile

### ISSUE THREAD

**Issue by spreadcharm** [ant-design/ant-design#34205] opened 2022-02-25 02:42 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-q7fye4?file=/index.js&resolutionWidth=320&resolutionHeight=675)

### Steps to reproduce
Change stylesheet like below

in the file "index.css"

.ant-picker-dropdown {
  max-width: 100%;
  overflow: auto;
}
.ant-picker-panel-container {
  width: fit-content;
}

### What is expected?
Datetime picker will be responsive

### What is actually happening?
Current, it's not responsive.

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.1 |
| System | Windows11 |
| Browser | Chrome98.0.4758.102  x64 |

**Comment by afc163** [comment] 2022-02-25 06:17
Duplicate of #26758

**Closed by afc163** 2022-02-25 06:17 UTC
