### ISSUE TITLE
antd的table rowSelection 复选100条数据，复选框卡顿，有延迟现象，请问如何解决，何时能解决？

### ISSUE THREAD

**Issue by jsonshao** [ant-design/ant-design#19858] opened 2019-11-21 05:58 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://segmentfault.com/q/1010000017065697](https://segmentfault.com/q/1010000017065697)

### Steps to reproduce
https://segmentfault.com/q/1010000017065697

### What is expected?
请问如何解决，何时能解决，或者能提供一个解决方案

### What is actually happening?
table中 复选100条卡顿

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.8.6 |
| System | window |
| Browser | chrome |

**Comment by zombieJ** [comment] 2019-11-21 06:06
Duplicate of #10431

**Closed by zombieJ** 2019-11-21 06:06 UTC
