### ISSUE TITLE
ant.design 官网挂掉了，怎么回事啊，哥们们

### ISSUE THREAD

**Issue by zhouxinjian52** [ant-design/ant-design#7986] opened 2017-10-23 07:24 UTC
### Version
2.13.7

### Environment
windows

### Reproduction link
[https://ant.design/docs/react/introduce-cn](https://ant.design/docs/react/introduce-cn)

### Steps to reproduce
打开https://ant.design/docs/react/introduce-cn

### What is expected?
可以打开

### What is actually happening?
不能打开

**Comment by afc163** [comment] 2017-10-23 07:27
Duplicate of #7895

**Closed by afc163** 2017-10-23 07:27 UTC
