### ISSUE TITLE
Modal  component appeared again after closing and disappeared very quickly 

### ISSUE THREAD

**Issue by Vu-Minh-Hoa** [ant-design/ant-design#39054] opened 2022-11-28 08:49 UTC
### Reproduction link

[https://ant.design/components/modal#components-modal-demo-confirm](https://ant.design/components/modal#components-modal-demo-confirm)

### Steps to reproduce

When I close the modal it appeared again after closing and disappeared very quickly.

### What is expected?

I think the class that revolve around changing the display is being remove a bit late.

### What is actually happening?

It appeared again after closing and disappeared very quickly

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | 18.2.0 |
| System | Window |
| Browser | Google Chrome, Microsoft Edge |

**Comment by phatify** [comment] 2022-11-29 13:50
@Vu-Minh-Hoa   nothing happened, it still works fine for me. Can you provide a video of that issue?

**Comment by Vu-Minh-Hoa** [comment] 2022-11-29 15:37
Sure, It still happen for me though on this chrome version and edge, I just update both of the browsers to the newest version but it still having the same issues here the version
![image](https://user-images.githubusercontent.com/67451987/204573247-e1511557-422e-45d4-8778-0a86c71c9674.png)
![image](https://user-images.githubusercontent.com/67451987/204573148-bbd588e0-af7e-482b-b9d0-39af2304bd13.png)

Here is the video.

https://user-images.githubusercontent.com/67451987/204573604-d07ed942-1858-42b3-80f7-cd0b709bb61f.mp4

**Comment by abenhamdine** [comment] 2022-11-29 20:03
Everything works fine for me, on Chrome Version 107.0.5304.121 (Build officiel) (x86_64)
MacOs Monterey 12.6.1

**Comment by MaciejWiatr** [comment] 2022-12-01 10:22
I'm having the same issue running On both Firefox and chrome, here's an example of this behavior
https://user-images.githubusercontent.com/44440856/205028300-95ddba22-3d9e-47d4-b2e0-333344cbca2a.mp4

**Comment by abenhamdine** [comment] 2022-12-17 11:44
I don't reproduce on Windows 11, Chrome Version 108.0.5359.125 (Build officiel) (64 bits)

**Comment by bougassaa** [comment] 2022-12-19 08:32
Hello, i have the same issue on **Windows (and Ubuntu)**, but on Mac os it works fine.

https://user-images.githubusercontent.com/66357198/208381826-ad6a3e69-7e9a-43a9-99a8-77645c91b683.mov

**Comment by raminmz66** [comment] 2022-12-19 08:46
I have the same problem with Ubuntu 18 :|

**Comment by siamakmontazer** [comment] 2022-12-19 09:56
Exactly the same problem for me too :(

**Comment by vuhuucuong** [comment] 2022-12-23 19:35
I was able to reproduce this by using `CPU Throttling` in **DevTool** -> **Performance**.
![image](https://user-images.githubusercontent.com/26746668/209396791-56deeb31-9fb2-434d-a24e-143bd1b9ca49.png)

The root cause is from [rc-dialog](https://github.com/react-component/dialog) (which `Modal` is based on). Apparently, the upgrade from React 17 -> 18 in antd v5 might break the expected behavior of `rc-dialog`. Probably relevant to [Automatic batching](https://github.com/reactwg/react-18/discussions/21) in React 18.

If you try to clone `rc-dialog` locally and upgrade it to React 18, it also has the same behavior. This doesn't happen with React <17


https://user-images.githubusercontent.com/26746668/209398445-c0c5f1bd-9a03-42e7-9907-884da3aa3e8d.mp4

**Comment by vuhuucuong** [comment] 2022-12-24 16:51
Manage to fix this in this PR https://github.com/react-component/dialog/pull/331
Would be great if someone can take a look

**Comment by vuhuucuong** [comment] 2022-12-25 18:51
> > Manage to fix this in this PR [react-component/dialog#331](https://github.com/react-component/dialog/pull/331) Would be great if someone can take a look
> 
> @vuhuucuong please use macbook as macOS to do everything :)))

What do you mean by "to do everything"? Not really sure why that's related to my PR?
Try to read my above comment, I could reproduce the issue on both Mac and Windows

https://user-images.githubusercontent.com/26746668/209479140-07b17daf-f81c-4e09-a2b8-0a2a6a0a911e.mp4

**Comment by heiyu4585** [comment] 2023-01-09 11:53
Duplicate of https://github.com/ant-design/ant-design/issues/39054

**Closed by heiyu4585** 2023-01-09 11:53 UTC
Labels: 🐛 Bug

**Comment by abenhamdine** [comment] 2023-01-09 13:14
> Duplicate of https://github.com/ant-design/ant-design/issues/39054

How issue #39054 could be duplicated of #39054 (itself) ??

**Comment by shamseer-ahammed** [comment] 2024-10-01 12:48
+1
