### ISSUE TITLE
Focus is lost in the Select component if the "mode" property is "multiple" and the "maxTagCount" property is "responsive"

### ISSUE THREAD

**Issue by Valtas** [ant-design/ant-design#33233] opened 2021-12-09 08:56 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/focus-is-lost-in-the-select-component-ant-design-viyf1)

### Steps to reproduce
Click on Select, then select 2 or more items without using the mouse.

### What is expected?
expected to see 2 or more selected items

### What is actually happening?
Only 1 item is selected. The focus is lost, there is no way to select the second item with the keyboard.

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome 96.0.4664.45 |

**Comment by afc163** [comment] 2021-12-09 11:20
Duplicate of #29444

**Closed by afc163** 2021-12-09 11:20 UTC
