### ISSUE TITLE
Notification 闪烁问题

### ISSUE THREAD

**Issue by CSpy163** [ant-design/ant-design#50326] opened 2024-08-09 04:40 UTC
### Reproduction link

[https://ant-design.antgroup.com/components/notification-cn#notification-demo-placement](https://ant-design.antgroup.com/components/notification-cn#notification-demo-placement)

### Steps to reproduce

连续点击第一个代码演示中的某个按钮，会弹出多个提示。

### What is expected?

提示丝滑插入到最顶部，旧的提示按顺序往下排。

### What is actually happening?

新提示插入到最顶上时，会先消失然后突然出现，就好像闪烁了一下。感觉很不流畅

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | V18.3.1 |
| System | WIndows11 |
| Browser | Chrome V127.0.6533.100 |

**Comment by afc163** [comment] 2024-08-09 05:00
Duplicate of https://github.com/ant-design/ant-design/issues/48608

**Closed by afc163** 2024-08-09 05:00 UTC
Labels: unconfirmed
