### ISSUE TITLE
TextArea showCount 和 extra 文字覆盖显示

### ISSUE THREAD

**Issue by hardmanhong** [ant-design/ant-design#49114] opened 2024-05-29 07:14 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/dai-zi-shu-ti-shi-antd-4-24-16-forked-7tcp6q?file=%2Fdemo.tsx%3A9%2C37)

### Steps to reproduce

同时设置 `extra` `maxLength` `showCount`，当 extra 过长时，覆盖了 showCount 

### What is expected?

正常显示

### What is actually happening?

覆盖显示

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 18.0.0 |
| System | window10 |
| Browser | chrome 125.0.6422.77 |

**Comment by afc163** [comment] 2024-05-29 07:23
Duplicate of #29709

**Closed by afc163** 2024-05-29 07:23 UTC
Labels: unconfirmed
