### ISSUE TITLE
Add the ability to pass `className` to the header of a Table

### ISSUE THREAD

**Issue by thisissami** [ant-design/ant-design#11715] opened 2018-08-11 00:19 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, with the Table component, it is very easy to style the Table as a whole (using `className`), and very easy to style any individual row (using the `rowClassName` function). However, styling the header seems impossible from within the component. 

If we pass a `className` to the table, targeting `thead` or `.ant-table-thead` within the referenced style doesn't affect the header. 

This makes the experience of altering the header of table very frustrating!! Considering that Ant Design is being advertised as an easy-to-use toolkit for building custom UIs, I think it is important that headers should be easily style-able. It is very common to want the header to look different than the rest of the rows, and currently - it is non-trivial. We can override the `less` variable for the header background (`table-header-bg`), but then what if we want to change the text-color too? What about other CSS variables? 

There is no straightforward way to do this that I can find, and I think adding the ability to pass a `headerClassName` to the `Table` would be very elegant & useful to many developers/designers.

I have also asked this question here: https://github.com/react-component/table/issues/228

### What does the proposed API look like?
```javascript
import React from 'react';
import { Table } from 'antd';
import { css } from 'react-emotion';

const header = css({ backgroundColor: 'rgb(100, 108, 140)', color: 'white', margin: '50px'});
const body = css({ backgroundColor: 'green' });

const styledTable = ({data, columns}) => ( 
  <Table 
    dataSource={data} 
    columns={columns} 
    className={body} // note - this works currently! (but doesn't affect the header)
    headerClassName={header}  // I would love this! 
  />
));

Cheers, thanks for taking the time to read this!


<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by apieceofbart** [comment] 2018-08-11 09:41
@thisissami This is open source - you can add that change :) I think all I have to do is to create a PR in `react-component/table` repo. Do you need help with that?

**Comment by yesmeck** [comment] 2018-08-11 15:31
Duplicate of https://github.com/react-component/table/issues/228

**Closed by yesmeck** 2018-08-11 15:31 UTC

**Comment by apieceofbart** [comment] 2018-08-11 18:42
@thisissami This should work:
```
const body = css({
  backgroundColor: 'green',
  '& thead > tr > th': {
    backgroundColor: 'blue'
  }
})
```
If you are looking for a library and this is the only thing you're missing in ant then let's fix that and help others at the same time :)

**Comment by thisissami** [comment] 2018-08-14 20:14
@apieceofbart thanks for your help! Here's a full react component anybody can grab if they're having an issue with this in the future. (also addresses the issue of applying borders to a row as a whole)


```javascript
import React from 'react';
import { Table } from 'antd';
import { css } from 'react-emotion';

const tableCSS = css({
  margin: '40px 120px',
  backgroundColor: 'white',
  '& table': {
    borderCollapse: 'collapse'
  },
  '& thead > tr > th': {
    backgroundColor: 'darkblue',
    color: 'white',
  },
  '& thead > tr': {
    borderWidth: '2px',
    borderColor: 'yellow',
    borderStyle: 'solid'
  }
});

const StyledTable = ({ data, columns }) => (
    <Table
      className={tableCSS}
      dataSource={data}
      columns={columns}
    />
);
```

**Comment by SharmaTushar1** [comment] 2024-04-04 07:01
+1 for this feature in 2024. Still have to target the antd table head class explicitly by defining a class for the parent.

**Comment by bombillazo** [comment] 2024-11-27 04:02
Would love to be able to edit the. footer and header className using the new `classNames` prop with `footer` and `header` keys...
