### ISSUE TITLE
Fixed Edit action column does not have value of fields in form

### ISSUE THREAD

**Issue by nguyenducthuanuet** [ant-design/ant-design#14039] opened 2019-01-02 04:32 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/nguyenducthuan/pen/KbZVWq?&editable=true&editors=001](https://codepen.io/nguyenducthuan/pen/KbZVWq?&editable=true&editors=001)

### Steps to reproduce
Add "fixed: 'right'" to operation column. Then click to Edit -> Save, form does not have any value of any field. (You can see on Console log when click Save)

### What is expected?
form has values of fields name, age, address when click Save.

### What is actually happening?
When add fixed to operation column, the form is changed. So it does not have value of row.

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | React 16.4.2 |
| System | Ubuntu 16.04 |
| Browser | Chrome |

**Comment by afc163** [comment] 2019-01-02 05:58
Fixed columns and editable row are not working along now.

**Comment by afc163** [comment] 2019-01-02 08:39
Duplicate of #13301

**Closed by afc163** 2019-01-02 08:39 UTC

**Comment by nguyenducthuanuet** [comment] 2019-01-02 16:05
> Fixed columns and editable row are not working along now.

Will you do this feature in the future ? I think it is very necessary!
