### ISSUE TITLE
Using the component of Drawer throws an Warning

### ISSUE THREAD

**Issue by DreamingLi** [ant-design/ant-design#28761] opened 2021-01-07 12:10 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l1kf4)

### Steps to reproduce
Just import Drawer from antd and use it, the warning will be printed out.

### What is expected?
no warning

### What is actually happening?
one warning is throwed out
Warning: React does not recognize the `scrollLocker` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `scrolllocker` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at DrawerChild (eval at z (https://codesandbox.io/static/js/sandbox.22ec4b3d5.js:1:98378), <anonymous>:52:34)
    at eval (eval at z (https://codesandbox.io/static/js/sandbox.22ec4b3d5.js:1:98378), <anonymous>:17:25)
    at PortalWrapper (eval at z (https://codesandbox.io/static/js/sandbox.22ec4b3d5.js:1:98378), <anonymous>:93:5)
    at DrawerWrapper (eval at z (https://codesandbox.io/static/js/sandbox.22ec4b3d5.js:1:98378), <anonymous>:42:34)
    at Drawer (https://l1kf4.csb.app/node_modules/antd/es/drawer/index.js:53:33)
    at DrawerWrapper (https://l1kf4.csb.app/node_modules/antd/es/drawer/index.js:261:34)
    at div
    at App

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.1 |
| System | windows10 |
| Browser | chrome 87.0.4280.88 |

**Comment by shaodahong** [comment] 2021-01-07 12:14
Duplicate of https://github.com/ant-design/ant-design/pull/28749

**Closed by shaodahong** 2021-01-07 12:14 UTC

**Comment by sal-tyfy** [comment] 2021-01-08 04:28
Duplicate
