### ISSUE TITLE
ColorPicker被Form.Item包裹，value不生效

### ISSUE THREAD

**Issue by 1123612483** [ant-design/ant-design#47980] opened 2024-03-20 08:23 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-n54htc?file=%2Findex.js%3A8%2C10)

### Steps to reproduce

1. 把antd版本升级到5.15.3

### What is expected?

效果跟5.12.5版本一样，Form初始化能设置value
![image](https://github.com/ant-design/ant-design/assets/20741541/035681ae-4768-4d7c-b5a3-879f637729a7)

### What is actually happening?

Form初始化没有设置value
![image](https://github.com/ant-design/ant-design/assets/20741541/8245d762-4a8a-4b19-9fd9-0053f7412f01)

| Environment | Info |
| --- | --- |
| antd | 5.15.3 |
| React | 18.2.0 |
| System | Win11 |
| Browser | Microsoft Edge 122.0.2365.92 |

**Comment by madocto** [comment] 2024-03-21 05:16
https://github.com/ant-design/ant-design/pull/45993/files#diff-be92dd92152a780003d48ddc95ec6716367d327f9f890f1221b84614aaa8168fR126 
从 antd@5.13.0 后出现的问题，改动后 `colorCleared` 状态默认为 true 了，并且没有随着 value 的变化去更新状态。

**Comment by yoyo837** [comment] 2024-03-21 06:09
I think it is Duplicate of https://github.com/ant-design/ant-design/issues/47539

**Comment by diandian18** [comment] 2024-03-22 08:29
> https://github.com/ant-design/ant-design/pull/45993/files#diff-be92dd92152a780003d48ddc95ec6716367d327f9f890f1221b84614aaa8168fR126 从 antd@5.13.0 后出现的问题，改动后 `colorCleared` 状态默认为 true 了，并且没有随着 value 的变化去更新状态。

请问哪天发布这个bug fix

**Comment by yoyo837** [comment] 2024-03-24 11:50
Duplicate of https://github.com/ant-design/ant-design/issues/47539

**Closed by yoyo837** 2024-03-24 11:50 UTC
Labels: 🐛 Bug
