### ISSUE TITLE
Drawer width set percent not working

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#11323] opened 2018-07-18 03:16 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
WIN10 - Chome67 - React 16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rmx13466pp)

### Steps to reproduce
Set Percent width and open Drawer

### What is expected?
Percent width working

### What is actually happening?
Percent width not working

**Comment by yesmeck** [comment] 2018-07-18 03:16
Duplicate of #11298

**Closed by yesmeck** 2018-07-18 03:16 UTC
