### ISSUE TITLE
create event by drag mouse within days in calendar

### ISSUE THREAD

**Issue by salekin02** [ant-design/ant-design#51475] opened 2024-11-04 04:12 UTC
### What problem does this feature solve?

Right now I am not able to create a single event for a date range. Also there are no way to show event title on date ranges.

### What does the proposed API look like?

It can be like: https://fullcalendar.io/demos

**Comment by MadCcc** [comment] 2024-11-06 08:31
Event in Calendar has been a feature request for a long time

**Comment by afc163** [comment] 2024-11-07 07:24
Duplicate of https://github.com/ant-design/ant-design/issues/12591

**Closed by afc163** 2024-11-07 07:24 UTC
Labels: 💡 Feature Request
