### ISSUE TITLE
在Dropdown组件中点击操作无法触发onVisibleChange的回调

### ISSUE THREAD

**Issue by moonrailgun** [ant-design/ant-design#33159] opened 2021-12-03 15:30 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rough-sky-kj037?file=/index.js)

### Steps to reproduce
点击下拉框任意项，查看console.log输出

### What is expected?
当dropdown关闭时，正确触发onVisibleChange的回调

### What is actually happening?
只会触发点开的回调，不能触发关闭的回调

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | windows |
| Browser | 92.0.4515.131 |

**Comment by afc163** [comment] 2021-12-03 15:35
Duplicate of #4994

**Closed by afc163** 2021-12-03 15:35 UTC

**Comment by moonrailgun** [comment] 2021-12-03 15:42
ok, this is a bug (i think ) but its always be here from 3.x.

i am not found its issue because of i search in open issue..
