### ISSUE TITLE
关于Table 带scroll属性是空数据的处理

### ISSUE THREAD

**Issue by ksh033** [ant-design/ant-design#15611] opened 2019-03-24 10:11 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现有空数据界面
![Image text](https://raw.githubusercontent.com/ksh033/test/master/2.png)
空数据是否应该放到ant-table-body下面

### What does the proposed API look like?
是否能该成
![Image text](https://raw.githubusercontent.com/ksh033/test/master/1.png)

**Comment by afc163** [comment] 2019-03-24 11:52
这个我试过，有点难，来个 PR 试试？

**Comment by afc163** [comment] 2019-03-24 11:53
Duplicate of #10490

**Closed by afc163** 2019-03-24 11:53 UTC

**Comment by pufei007** [comment] 2019-05-15 02:09
我尝试用css中fill-available属性来实现把滚动条撑到下面。但是在没有数据的时候，暂无数据页面元素会在滚动条下面。
:global(.ant-table-body) {
   height: -webkit-fill-available;
   height: fill-available;
}
