### ISSUE TITLE
Ant.Design Errors with Latest @types/react

### ISSUE THREAD

**Issue by spietrek** [ant-design/ant-design#15956] opened 2019-04-08 18:32 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mqqo1z105j)

### Steps to reproduce
Add @types/react@16.8.13 as a devDependency to your package.json.

### What is expected?
App should compile.

### What is actually happening?
Receiving the following error only with Button.

TypeScript error: Type '{ className: string; icon: string; onClick: (event: any) => void; }' is missing the following properties from type 'Pick<Pick<(Readonly<AnchorButtonProps> & Readonly<{ children?: ReactNode; }>) | (Readonly<NativeButtonProps> & Readonly<{ children?: ReactNode; }>), "defaultChecked" | "defaultValue" | ... 257 more ... | "ghost"> & Pick<...> & Pick<...>, "defaultChecked" | ... 256 more ... | "prefixCls">': defaultChecked, defaultValue, suppressContentEditableWarning, suppressHydrationWarning, and 251 more.  TS2740

    142 |         />
    143 |         {isSearchTermEntered && (
  > 144 |           <Button
        |            ^
    145 |             className="app-search-clear-button"
    146 |             icon="close"
    147 |             onClick={this.handleClearSearch}

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.8.6 |
| System | N/A |
| Browser | N/A |

**Comment by spietrek** [comment] 2019-04-08 18:37
Looks like dupe of [15390](https://github.com/ant-design/ant-design/issues/15930)

**Comment by zombieJ** [comment] 2019-04-09 02:45
Yes. It's bug from `@types/react@latest`. Have update ButtonProps for workaround.

Duplicate of #15390

**Closed by zombieJ** 2019-04-09 02:45 UTC

**Comment by afc163** [comment] 2019-04-09 02:47
Duplicate of #15930 not #15390
