### ISSUE TITLE
Is it possible to support getContainer props on Modal.confirm / Modal.alert / ... / Modal.other

### ISSUE THREAD

**Issue by linningmii** [ant-design/ant-design#11576] opened 2018-08-02 07:12 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
There's an event listener to handler outer click outside the target dom area on documentElement, there is no doubt the click in the confirm modal is in the outer range of the target area.

It's really hard to add an &lt;ConfirmModal /&gt; to all relative components especially the web app looks like an IDE.

The problem we faced will be solved if there is a props to set the confirm modal container dynamically.

### What does the proposed API look like?
```javascript
Modal.confirm({
  content: 'text',
  onOk: () => ajax()
  getContainer: () => ReactDOM.findDOMNode(this)
})
```

**Comment by yesmeck** [comment] 2018-08-02 07:16
Duplicate of #11377

**Closed by yesmeck** 2018-08-02 07:16 UTC
