### ISSUE TITLE
when dynamic column, table title and table column not alignment

### ISSUE THREAD

**Issue by sealzrt** [ant-design/ant-design#8594] opened 2017-12-13 14:01 UTC
### Version
3.0.1

### Environment
mac, chrome 63

### Reproduction link
[https://codesandbox.io/s/jj90ym2885](https://codesandbox.io/s/jj90ym2885)

### Steps to reproduce
the columns is dynamic. see the demo  https://codesandbox.io/s/jj90ym2885

### What is expected?
title and column is alignment

### What is actually happening?
title and column not alignment

**Comment by afc163** [comment] 2017-12-13 15:22
Duplicate of #8593

**Closed by afc163** 2017-12-13 15:22 UTC
