### ISSUE TITLE
Popover does not open on React 18 (createRoot) in StrictMode 

### ISSUE THREAD

**Issue by kel666** [ant-design/ant-design#34876] opened 2022-04-06 08:38 UTC
### Reproduction link

[https://stackblitz.com/edit/react-ts-d58jhr?file=index.tsx](https://stackblitz.com/edit/react-ts-d58jhr?file=index.tsx)

### Steps to reproduce

Hit "Click me" under "with createRoot".

### What is expected?

Popup should open

### What is actually happening?

Popup is not opened.

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18.0.0 |
| System | Windows 10 |
| Browser | Chrome 94 |

---
As you can see this works using old React render

**Comment by afc163** [comment] 2022-04-06 09:33
Duplicate of #34810

**Closed by afc163** 2022-04-06 09:33 UTC
