### ISSUE TITLE
Selecting suggestion from <Autocomplete/> in a form inside a <Modal/> will close the modal

### ISSUE THREAD

**Issue by besartmarku** [ant-design/ant-design#27115] opened 2020-10-12 13:58 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elegant-sinoussi-852p1?file=/index.js)

### Steps to reproduce
I have a form inside a Modal. The form has also a <Autocomplete/> field in it. Changing other fields work normally and they won't close the modal, but selecting a suggestion from <Autocomplete/> will close modal immediately.

### What is expected?
The Autocomplete field to "register" the value normally and not close the modal

### What is actually happening?
Selecting the suggestion closes the Modal

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | react |
| System | Windows 10 |
| Browser | Google Chrome  |

**Comment by afc163** [comment] 2020-10-12 14:02
Duplicate of #27080 and #27084

Fixed in https://github.com/react-component/dialog/pull/204

https://codesandbox.io/s/broken-mountain-7c4w7

**Closed by afc163** 2020-10-12 14:02 UTC
