### ISSUE TITLE
无法覆盖offset

### ISSUE THREAD

**Issue by cityvoice** [ant-design/ant-design#41331] opened 2023-03-19 03:24 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jymny9?file=/index.js)

### Steps to reproduce

无

### What is expected?

大分辨率下可以覆盖小分辨率下定义的offset

### What is actually happening?

offset没有被覆盖

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 16.12 |
| System | windows |
| Browser | EDGE |

**Comment by Yuiai01** [comment] 2023-03-19 03:27
Duplicate of https://github.com/ant-design/ant-design/issues/41142

**Comment by afc163** [comment] 2023-03-19 08:11
Duplicate of https://github.com/ant-design/ant-design/issues/41142

**Closed by afc163** 2023-03-19 08:11 UTC
Labels: unconfirmed
