### ISSUE TITLE
Image.PreviewGroup 添加一个下载按钮

### ISSUE THREAD

**Issue by liy010** [ant-design/ant-design#40551] opened 2023-02-05 06:02 UTC
### What problem does this feature solve?

在预览图片时下载当前图片，比如下载更高清的图片

### What does the proposed API look like?

下载icon在顶部的operation区，并且下载图片的url跟preview里设置的url可能不一样

**Comment by afc163** [comment] 2023-02-05 11:59
Duplicate of #38418

**Closed by afc163** 2023-02-05 11:59 UTC
Labels: unconfirmed
