### ISSUE TITLE
How to get APIs of Form in Stateless Component?

### ISSUE THREAD

**Issue by Smile-dan** [ant-design/ant-design#6972] opened 2017-07-26 16:42 UTC
### What problem does this feature solve?
the Stateless Component has been decorated by Form.create ，How to get APIs of Form?

### What does the proposed API look like?
To get APIs of Form

**Comment by benjycui** [comment] 2017-07-27 01:05
Duplicate of https://github.com/ant-design/ant-design/issues/6971

**Closed by benjycui** 2017-07-27 01:05 UTC
