### ISSUE TITLE
xxxl (3xl) breakpoint for Grids

### ISSUE THREAD

**Issue by Luxaaa** [ant-design/ant-design#36091] opened 2022-06-16 19:34 UTC
### What problem does this feature solve?

A 3xl breakpoint for the grid layout (Rows, Cols) can help to create better layouts for wide screens e.g. 21:9 screens

### What does the proposed API look like?

The only thing to do is to create a new breakpoint wich then can be used like the currently existing breakpoints like md or xxl.

Example:
```
<Row>
<Col md={24} xxl={12} xxxl={6}>I am a Column</Col>
</Row>
```

**Comment by afc163** [comment] 2022-06-17 02:11
Duplicate of #32954

**Closed by afc163** 2022-06-17 02:11 UTC
