### ISSUE TITLE
ant-tabs-ink-bar wrong position

### ISSUE THREAD

**Issue by cuongnm-bp** [ant-design/ant-design#18901] opened 2019-09-19 10:09 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-t1crg)

### Steps to reproduce
Create to many tab, select bottom tab, ink-bar is wrong position

### What is expected?
ink-bar match with tabpan

### What is actually happening?
ink-bar not match with tabpan

| Environment | Info |
|---|---|
| antd | 3.23.3 |
| React | 16.9.0 |
| System | window 10 64bit Pro |
| Browser | Chorme Version 76.0.3809.132 (Official Build) (64-bit) |

**Comment by afc163** [comment] 2019-09-19 13:11
<img width="504" alt="图片" src="https://user-images.githubusercontent.com/507615/65246881-f7d75980-db21-11e9-9a99-b2c19d25e26f.png">

It works fine.

**Comment by afc163** [comment] 2019-09-23 06:02
Duplicate of #18652

**Closed by afc163** 2019-09-23 06:02 UTC
Labels: 🤔 Need Reproduce
