### ISSUE TITLE
TimePicker 下拉滚动条过长

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#47681] opened 2024-03-02 06:52 UTC
### Reproduction link

 [https://ant.design/components/time-picker-cn](https://ant.design/components/time-picker-cn)

![image](https://github.com/ant-design/ant-design/assets/29728228/586d9a3f-0ba0-4f1a-a237-5ad8ad310c54)

![image](https://github.com/ant-design/ant-design/assets/29728228/dc597745-2c2c-4696-9b11-8ce7f2f2b2de)

### Steps to reproduce

就直接拿文档的例子，为什么hour min sec 下面这么多空白？正常应该滚动条滚到有底部数据就可以了，现在这种大段的空白比较奇怪

看了下css，这里最后 为什么有个伪类，会计算height？把他去掉貌似就正常了

![image](https://github.com/ant-design/ant-design/assets/29728228/9be5b40d-e2e4-4ef8-ad58-f90c9def514b)

![image](https://github.com/ant-design/ant-design/assets/29728228/875b85ef-0447-4fdd-8fa8-e8a12ae190aa)

![image](https://github.com/ant-design/ant-design/assets/29728228/99c633f1-8b00-4bbc-8179-1e8e0a314a60)

### What is expected?

不要有太多空白区域

### What is actually happening?

存在太多空白区域

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | 18 |
| System | windows 10 |
| Browser | chrome |

**Comment by yoyo837** [comment] 2024-03-02 07:00
Duplicate of https://github.com/ant-design/ant-design/issues/47526
这个问题应该已经修过了，官网没有重新部署。
https://stackblitz.com/edit/react-asmdwg-auu743?file=package.json

**Closed by yoyo837** 2024-03-02 07:00 UTC
Labels: unconfirmed

**Comment by zystudios** [comment] 2024-03-02 11:32
确认5.14.2修复了
