### ISSUE TITLE
inlineCollapsed Menu bug

### ISSUE THREAD

**Issue by L-x-C** [ant-design/ant-design#7059] opened 2017-08-02 08:14 UTC
### Version
2.12.3

### Environment
OSX, Chrome 59

### Reproduction link
[https://ant.design/components/menu-cn/#components-menu-demo-inline-collapsed](https://ant.design/components/menu-cn/#components-menu-demo-inline-collapsed)

### Steps to reproduce
![b](https://user-images.githubusercontent.com/4329120/28864047-cc61f2d6-779d-11e7-8fd9-66b9a796d7d8.gif)

First, close Navigation One.
Second, close Menu.
Third, click Navigation One.

### What is expected?
Navigation One should not be opened.

### What is actually happening?
Navigation One opens.

**Comment by PanJiaChen** [comment] 2017-08-02 08:15
same problem

**Comment by afc163** [comment] 2017-08-02 08:16
Duplicate of #7048

**Comment by afc163** [comment] 2017-08-02 08:16
Fixed in #7048

**Closed by afc163** 2017-08-02 08:16 UTC

**Comment by cjchnwscqwsbsy** [comment] 2018-01-26 06:32
Hello, could you tell me how you solve these problem ?
