### ISSUE TITLE
menu组件搭配React18出现菜单闪烁

### ISSUE THREAD

**Issue by Design-duke** [ant-design/ant-design#38304] opened 2022-10-31 09:38 UTC
### Reproduction link

[https://www.baidu.com](https://www.baidu.com)

### Steps to reproduce

暂无

### What is expected?

搭配React17就不会出现

### What is actually happening?

搭配React18会出现菜单闪烁

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18 |
| System | w10 |
| Browser | 谷歌 |

**Comment by HuanxinHu** [comment] 2022-11-02 21:25
同样有这个bug啊

**Comment by HuanxinHu** [comment] 2022-11-02 21:27
官网的layout sidebar codesandbox 就复现了。
https://codesandbox.io/s/uxnbbg?file=/package.json

**Comment by HuanxinHu** [comment] 2022-11-02 21:29
> 官网的layout sidebar codesandbox 就复现了。 https://codesandbox.io/s/uxnbbg?file=/package.json



> ### Reproduction link
> https://www.baidu.com
> 
> ### Steps to reproduce
> 暂无
> 
> ### What is expected?
> 搭配React17就不会出现
> 
> ### What is actually happening?
> 搭配React18会出现菜单闪烁
> 
> Environment	Info
> antd	4.23.6
> React	18
> System	w10
> Browser	谷歌

**Comment by HuanxinHu** [comment] 2022-11-03 23:59
> Hello @Design-duke. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @Design-duke, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

template created: https://codesandbox.io/s/antd-reproduction-template-forked-uncxj3?file=/index.js

**Comment by Design-duke** [comment] 2022-11-04 03:30
> > Hello @Design-duke. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> > 你好 @Design-duke, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> > ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)
> 
> template created: https://codesandbox.io/s/antd-reproduction-template-forked-uncxj3?file=/index.js

我已经再sendbox上写过了，我感觉和Layout组件也有关系

**Comment by afc163** [comment] 2022-11-05 07:53
Duplicate of #36152

**Closed by afc163** 2022-11-05 07:53 UTC
