### ISSUE TITLE
Virtual table render method not working

### ISSUE THREAD

**Issue by PiotrKalinski** [ant-design/ant-design#28899] opened 2021-01-17 00:28 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stupefied-rain-cm2zw)

### Steps to reproduce
I cannot pass any parameters to render function, not covered in docs

### What is expected?
Example of working code and documentation enrich.

### What is actually happening?
Table render is failing due to missing properties.

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 16.3.1 |
| System | Windows 10 |
| Browser | Chrome 87.0.4280.141 |

**Comment by afc163** [comment] 2021-01-17 08:21
Duplicate of #20339

**Closed by afc163** 2021-01-17 08:21 UTC
