### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by xiongqianhua** [ant-design/ant-design#46515] opened 2023-12-18 12:36 UTC
### Reproduction link

[https://ant.design/docs/react/use-with-next-cn?theme=dark](https://ant.design/docs/react/use-with-next-cn?theme=dark)

### Steps to reproduce

 就是按照官方的步骤：npx create-next-app antd-demo拉下来后，安装wannpm install antd --save，然后npm run dev 就报错了

### What is expected?

正常运行啊啊

### What is actually happening?

报错 ⨯ /Users/user/Desktop/zongmu-code/frontend/antd-demo/node_modules/rc-util/es/omit.js:1
import _objectSpread from "@babel/runtime/helpers/esm/objectSpread2";
^^^^^^

SyntaxError: Cannot use import statement outside a module

| Environment | Info |
| --- | --- |
| antd | 5.12.3 |
| React | "antd": "^5.12.3",     "next": "14.0.4",     "react": "^18",     "react-dom": "^18" |
| System | macbookpro m1 |
| Browser | Chrome 已是最新版本 版本 120.0.6099.109（正式版本） (arm64) |

---
说明这个版本的ant组件库根next框架并不兼容

**Comment by MadCcc** [comment] 2023-12-19 01:43
Duplicate of https://github.com/ant-design/ant-design/issues/46053

**Closed by MadCcc** 2023-12-19 01:43 UTC
Labels: unconfirmed
