### ISSUE TITLE
使用dayjs替换moment了但是体积没有减少

### ISSUE THREAD

**Issue by chenjunjia97** [ant-design/ant-design#31414] opened 2021-07-15 09:43 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-pro/issues/8741](https://github.com/ant-design/ant-design-pro/issues/8741)

### Steps to reproduce
按照官网步骤
![image](https://user-images.githubusercontent.com/49097606/125767160-3fecf2ca-fd84-4b85-827b-95ddac35ada5.png)

### What is expected?
momenjs被替换掉了

### What is actually happening?
没有替换掉

| Environment | Info |
|---|---|
| antd | 4.14.1 |
| React | 17 |
| System | windows10 |
| Browser | chrome |

**Comment by afc163** [comment] 2021-07-15 09:48
Duplicate of https://github.com/ant-design/ant-design-pro/issues/8741

**Closed by afc163** 2021-07-15 09:48 UTC
