### ISSUE TITLE
[Modal] should not close Modal when mouse sweep like Drawer

### ISSUE THREAD

**Issue by dengfuping** [ant-design/ant-design#27538] opened 2020-11-04 04:04 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal/#components-modal-demo-basic](https://ant.design/components/modal/#components-modal-demo-basic)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/14918822/98067391-701eec80-1e94-11eb-84c8-0cf27c7e2f95.png)
![image](https://user-images.githubusercontent.com/14918822/98068095-128b9f80-1e96-11eb-99d4-21cf5aa70bff.png)

### What is expected?
Don't close Modal like Drawer

### What is actually happening?
Close Modal.

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 16.14.0 |
| System | MacOS 10.15.5 |
| Browser | Chrome 81.0.4044.138 |

**Comment by xrkffgg** [comment] 2020-11-04 05:09
Duplicate of https://github.com/ant-design/ant-design/issues/27391

**Comment by afc163** [comment] 2020-12-03 04:08
Fixed in https://github.com/react-component/dialog/pull/210

**Closed by afc163** 2020-12-03 04:08 UTC
Labels: 🐛 Bug
