### ISSUE TITLE
about import style by css

### ISSUE THREAD

**Issue by moonlitusun** [ant-design/ant-design#15341] opened 2019-03-12 09:27 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am using the ant style introduced by css, but there are always a lot of global styles from antd, why is this?

### What does the proposed API look like?
no global css

**Comment by afc163** [comment] 2019-03-12 09:41
Duplicate of #9363

**Closed by afc163** 2019-03-12 09:41 UTC
