### ISSUE TITLE
RangePicker: bug occuring when End date manually set before Start date

### ISSUE THREAD

**Issue by JaufreLallement** [ant-design/ant-design#9313] opened 2018-02-08 20:29 UTC
### Version
3.2.0

### Environment
React

### Reproduction link
[https://codesandbox.io/s/rjm1rkxnyq](https://codesandbox.io/s/rjm1rkxnyq)

### Steps to reproduce
Pick for exemple the 6th of Feb 2018 as start date. Pick the 5th Mar 2018 as end date. Then manually replace the month number of the end date to set it to 02 (03 -> 02). The bug occurs everytimes you manually set the end date to be prior the start date.

### What is expected?
Maybe a reset of the end date when it is prior to the start date, in order to prevent the bug.

### What is actually happening?
Display an error message

**Comment by yesmeck** [comment] 2018-02-09 02:16
Duplicate of #9267, will fix this weekend.

**Closed by yesmeck** 2018-02-09 02:16 UTC
Labels: Bug, Component: DatePicker
