### ISSUE TITLE
Cascader跟Input搭配问题

### ISSUE THREAD

**Issue by wboykron** [ant-design/ant-design#7066] opened 2017-08-03 02:39 UTC
### Version
2.12.3

### Environment
macos、新版chrome

### Reproduction link
[http://new-issue.ant.design/](http://new-issue.ant.design/)

### Steps to reproduce
用户编辑，部门选择为Cascader，options来自model中，使用initialValue给部门要赋初值，更改input输入框的值，Cascader中的值会一下出现，一下为空

### What is expected?
Cascader不受Input影响

### What is actually happening?
更改input输入框的值，Cascader中的值会一下出现，一下为空

---
代码如下：
import React from 'react';
import { Form, Input, Tooltip, Icon, Cascader, Select, Row, Col, Checkbox, Button, AutoComplete,Radio,DatePicker,Upload,Spin } from 'antd';
const FormItem = Form.Item;
const Option = Select.Option;
const AutoCompleteOption = AutoComplete.Option;
const RadioGroup = Radio.Group;

import moment from 'moment';
import { routerRedux } from 'dva/router';

import { connect } from 'dva';

function UserEdit({
    dispatch,
    form,
    user,
    department,
    loading
  }){

  const { getFieldDecorator} = form;

  const { selectItem} = user;

  if(!selectItem.jobNumber){
    history.back();
    return null;
  }

  const formItemLayout = {
    labelCol: {
      xs: { span: 4 },
      sm: { span: 4 },
    },
    wrapperCol: {
      xs: { span: 20 },
      sm: { span: 20 },
    },
  };

  const tailFormItemLayout = {
    wrapperCol: {
      xs: {
        span: 14,
        offset: 2,
      },
      sm: {
        span: 14,
        offset: 2,
      },
    },
  };

  return(
    <Spin spinning={loading}>
    <div style={{padding:10}}>
      <div className="contentHead">
        <span className="contentLabel">编辑员工</span>
      </div>
      <Form layout="horizontal">
        <Row>
          <Col span={12}>
            <FormItem
              {...formItemLayout}
              label="工号"
              hasFeedback
              required
            >
              {getFieldDecorator('jobNumber', {
                rules: [{
                  required: true, message: '请输入工号',
                  }],
                initialValue:selectItem.jobNumber
                })(
              <Input />
                )}
            </FormItem>
            <FormItem
              {...formItemLayout}
              label="部门"
            >
              {getFieldDecorator('departmentId', {
                rules: [{
                  required: true, message: '请选择部门!',
                  }],
                  initialValue:selectItem.departmentIds
                })(
                  <Cascader options={department.dataSource} placeholder="选择部门" changeOnSelect/>
                )}
            </FormItem>
          </Col>
        </Row>

        <FormItem {...tailFormItemLayout}>
          <Button type="primary" htmlType="submit" size="large" onClick={(e)=>{handleSubmit(e)}}>保存</Button>
          <Button size="large" className="marginL10" onClick={(e)=>{
          dispatch(routerRedux.push({
              pathname: '/app/user'
          }));
        }}>取消</Button>
        </FormItem>
      </Form>
    </div>
    </Spin>
  )
}

function mapStateToProps({ user,department,loading }) {
  return {
    user,
    department,
    loading:loading.models.user
  };
}

export default connect(mapStateToProps)(Form.create()(UserEdit));

**Comment by ddcat1115** [comment] 2017-08-03 02:50
Please provide a `reproducible` and `most simplified` demo ->

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment] 2017-08-03 03:23
Duplicate of #7067

**Closed by afc163** 2017-08-03 03:23 UTC
