### ISSUE TITLE
Proposal to remove reliance on global styles

### ISSUE THREAD

**Issue by kylegach** [ant-design/ant-design#13459] opened 2018-12-05 21:34 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
As abundantly illustrated in #4331, the global nature of [base.less](https://github.com/ant-design/ant-design/blob/master/components/style/core/base.less) is preventing many from adopting Ant Design and causing serious issues for other adopters, particularly those using Ant as a dependency in their library.

I want to start a conversation to discuss ways forward. I've read through all of #4331 and each of the issues & PRs referenced within. As I understand it, Ant's perspective is:

- Ant's primary consumers have no issue with the global styles, so changing it is not a priority
- Some, if not most, of Ant's consumers rely on those global styles in their applications, so removing them would be a breaking change, which Ant is not willing to make

That perspective is understandable, but the problem (for many) of global styles should not be ignored.

### What does the proposed API look like?
> What if the community could do the work to transition component styles to no longer depend on global styles?

One approach:

1. Add automated visual regression testing for all components
2. Refactor component styles to use previously-global styles in a non-global manner
    - I like the [`[class="ant-"] { ... }` approach](https://github.com/ant-design/ant-design/issues/4331#issuecomment-423691027), but probably lots of options here
3. Confirm no breaking changes to components
4. Offer today's base.less, with global styles, as an opt-in import, for those dependent on it

Is Ant open to such a proposal? If so, do we have people willing to do the work in this community (🙋‍♂️)?

_Thanks to @DylanVann, whose [thoughts](https://github.com/ant-design/ant-design/issues/9363#issuecomment-444141010) prompted this proposal._

**Comment by afc163** [comment] 2018-12-06 02:57
Duplicate of #9363

**Closed by afc163** 2018-12-06 02:57 UTC
