### ISSUE TITLE
Closable Alert causes TypeError: node is null

### ISSUE THREAD

**Issue by rchavik** [ant-design/ant-design#26550] opened 2020-09-02 14:07 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://alert-repro.vercel.app/](https://alert-repro.vercel.app/)

### Steps to reproduce
- Browse to https://alert-repro.vercel.app/ (The repo is [here](https://github.com/rchavik/alert-repro))
- Open the webdev console
- Close the alert, causes wsod with errors in the console, eg: 

```
TypeError: e is null
    onLeaveStart index.js:143
    C useStatus.js:174
    React 3
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 20
    93 index.tsx:7
    l (index):1
    50 main.df098492.chunk.js:1
    l (index):1
    t (index):1
    r (index):1
    <anonymous> main.df098492.chunk.js:1
```

### What is expected?
App does not crash

### What is actually happening?
Application crashed

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.13.1 |
| System | linux |
| Browser | firefox |

---
I can't repro with codesandbox, maybe only happens on a typescript project.

**Comment by afc163** [comment] 2020-09-03 02:36
It may be caused by rc-motion@1.1.1, and resolved in https://github.com/react-component/motion/pull/5.

Please remove yarn.lock and reinstall node_modules.

**Closed by afc163** 2020-09-03 02:36 UTC
