### ISSUE TITLE
table组件 总结行summary 可配置为固定行，不跟随列表进行滚动，且可配置dataIndex，与列表的dataIndex位置相对应

### ISSUE THREAD

**Issue by nqsjd178559344** [ant-design/ant-design#27645] opened 2020-11-09 02:31 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当我页面请求大量数据，且存在竖向滚动条，那么我需要的总结行是我要在列表上能够直观的看到，而不是滚动到最后才可以看到总结行，且可配置dataIndex，让它与列表项可进行位置对应。

### columns

假设 columns = [
  {
    // 入库单号',
    title:'入库单号',
    dataIndex: 'entryOrderCode',
    width: 180,
    fixed: 'left',
  },
  {
    // 客户编码',
    title: '客户编码',
    dataIndex: 'ownerCode',
    width: 150,
    fixed: 'left',
  },
  {
    // 仓库编码',
    title: '仓库编码',
    dataIndex: 'warehouseCode',
    // width: 210,
    // fixed: 'left',
  },
];

summary={() => (
    <Table.Summary.Row>
      <Table.Summary.Cell dataIndex='entryOrderCode'>总数</Table.Summary.Cell>
      <Table.Summary.Cell dataIndex='datownerCodeaIndex'>121</Table.Summary.Cell>
      <Table.Summary.Cell dataIndex='warehouseCode'>111</Table.Summary.Cell>
    </Table.Summary.Row>
  )}

**Comment by nqsjd178559344** [comment] 2020-11-09 02:38
> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### What problem does this feature solve?
> 当我页面请求大量数据，且存在竖向滚动条，那么我需要的总结行是我要在列表上能够直观的看到，而不是滚动到最后才可以看到总结行，且可配置dataIndex，让它与列表项可进行位置对应。
> 
> ### What does the proposed API look like?
> ### columns
> 假设 columns = [
> {
> // 入库单号',
> title:'入库单号',
> dataIndex: 'entryOrderCode',
> width: 180,
> fixed: 'left',
> },
> {
> // 客户编码',
> title: '客户编码',
> dataIndex: 'ownerCode',
> width: 150,
> fixed: 'left',
> },
> {
> // 仓库编码',
> title: '仓库编码',
> dataIndex: 'warehouseCode',
> // width: 210,
> // fixed: 'left',
> },
> ];
> 
> summary={() => (
> <Table.Summary.Row fixed>
> <Table.Summary.Cell dataIndex='entryOrderCode'>总数</Table.Summary.Cell>
> <Table.Summary.Cell dataIndex='datownerCodeaIndex'>121</Table.Summary.Cell>
> <Table.Summary.Cell dataIndex='warehouseCode'>111</Table.Summary.Cell>
> </Table.Summary.Row>
> )}

**Comment by afc163** [comment] 2020-11-09 03:05
Duplicate of #25116

**Closed by afc163** 2020-11-09 03:05 UTC
