### ISSUE TITLE
在最新的React默认的严格模式下使用antd的组件会报错

### ISSUE THREAD

**Issue by omlou** [ant-design/ant-design#29185] opened 2021-02-02 08:30 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://reactjs.org/link/strict-mode-find-node //随便一个新版的react项目，使用了如Slider组件](https://reactjs.org/link/strict-mode-find-node //随便一个新版的react项目，使用了如Slider组件)

### Steps to reproduce
使用某些antd组件，如Slider等，控制台就会报错，或是报警告：
index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Handle which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
<React.StrictMode>
    <HashRouter>
      <App />
    </HashRouter>
  </React.StrictMode>
index.js删除<React.StrictMode></React.StrictMode>严格模式就不会报错了，你们是不是封装组件的时候用了什么官方不推荐的写法

### What is expected?
不报错

### What is actually happening?
报错

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | chrome 88.0.4324.104 |

**Comment by afc163** [comment] 2021-02-02 08:32
Duplicate of #26136

**Closed by afc163** 2021-02-02 08:32 UTC
