### ISSUE TITLE
Window object matchMedia

### ISSUE THREAD

**Issue by Chidi3b3r3** [ant-design/ant-design#15289] opened 2019-03-08 11:11 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
This only happens in the production build.

### What is expected?
The expectation is for the window to exist as an object with a matchMedia property otherwise polyfill the property. 

### What is actually happening?
Evaluating using the string representation of the window object ==> "[object Object]"

| Environment | Info |
|---|---|
| antd | 3.10.7 |
| React | 16.8 |
| System | iOS 12.1 |
| Browser | Mobile Safari |

---
`Cannot set property matchMedia of [object Object] which has only a getter.`

FIle ===> antd/lib/grid/row.js:75

I'm willing to raise a PR if I get a response around that.

**Comment by afc163** [comment] 2019-03-17 07:44
This issue is closed because it has been marked as Need Reproduce, but has not had recent activity.
If you can provide a reproduce, feel free to ping anyone of our maintainers to reopen this issue.
Thank you for your contributions.

**Closed** 2019-03-17 07:43 UTC
Labels: Need Reproduce🤔
