### ISSUE TITLE
_interopRequireWildcard wrap the react will trigger Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by hstarorg** [ant-design/ant-design#5989] opened 2017-05-02 09:30 UTC
### Version
2.9.3

### Environment
win10, chrome58

### Reproduction link
[http://codepen.io/benjycui/pen/KgPZrE?editors=001](http://codepen.io/benjycui/pen/KgPZrE?editors=001)

### Steps to reproduce
Import antd, run project will show the error message at F12 Panel

### What is expected?
No warning

### What is actually happening?
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by yesmeck** [comment] 2017-05-02 09:32
Duplicate of #5678

**Closed by yesmeck** 2017-05-02 09:32 UTC
