### ISSUE TITLE
style: Select down arrow doesn't rotate

### ISSUE THREAD

**Issue by guanyuan** [ant-design/ant-design#30103] opened 2021-04-12 06:50 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-rx8wc)

### Steps to reproduce
按照文档进行实验

### What is expected?
期望展开select组件，箭头会旋转方向

### What is actually happening?
箭头没有旋转

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16 |
| System | mac |
| Browser | chrome |

---
文档中也可以重现

**Comment by xrkffgg** [comment] 2021-04-12 07:44
https://github.com/ant-design/ant-design/pull/23468

**Comment by xrkffgg** [comment] 2021-04-12 07:45
It is design.

**Comment by xrkffgg** [comment] 2021-04-12 07:46
Duplicate of https://github.com/ant-design/ant-design/issues/25506

**Closed by xrkffgg** 2021-04-12 07:45 UTC
