### ISSUE TITLE
Table onChange filters is empty when using custom filters

### ISSUE THREAD

**Issue by khanakia** [ant-design/ant-design#28640] opened 2021-01-01 09:50 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/customized-filter-panel-antd494-forked-s63ji?file=/index.js)

### Steps to reproduce
1. Try to filter by Name
2. Check console name is empty https://prnt.sc/we2gb3

### What is expected?
Name should have filtered value https://prnt.sc/we2gb3

### What is actually happening?
filtered value is empty in name https://prnt.sc/we2gb3

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 16.14.0 |
| System | OSX |
| Browser | Chrome |

**Comment by oceandrama** [comment] 2021-01-03 12:04
Duplicate of https://github.com/ant-design/ant-design/issues/28603

**Comment by Meowu** [comment] 2021-01-03 17:38
will be fixed in https://github.com/ant-design/ant-design/pull/28627 .

**Closed** 2021-01-04 03:17 UTC
