### ISSUE TITLE
Popconfirm 在StrictMode下，控制台报错"findDOMNode is deprecated in StrictMode"

### ISSUE THREAD

**Issue by aehrfbszer** [ant-design/ant-design#47776] opened 2024-03-08 07:59 UTC
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-gxetif?file=package.json)

### Steps to reproduce

初次加载页面，控制台报错
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
at label
at Wave (https://react-gxetif.stackblitz.io/turbo_modules/antd@5.15.1/lib/_util/wave/index.js:19:5)
at InternalRadio (https://react-gxetif.stackblitz.io/turbo_modules/antd@5.15.1/lib/radio/radio.js:33:30)
at eval (https://react-gxetif.stackblitz.io/turbo_modules/@rc-component/trigger@1.18.3/lib/TriggerWrapper.js:11:24)
at DomWrapper (https://react-gxetif.stackblitz.io/turbo_modules/rc-resize-observer@1.4.0/lib/SingleObserver/DomWrapper.js:21:34)
at SingleObserver (https://react-gxetif.stackblitz.io/turbo_modules/rc-resize-observer@1.4.0/lib/SingleObserver/index.js:18:24)
at ResizeObserver (https://react-gxetif.stackblitz.io/turbo_modules/rc-resize-observer@1.4.0/lib/index.js:24:24)
at eval (https://react-gxetif.stackblitz.io/turbo_modules/@rc-component/trigger@1.18.3/lib/index.js:41:34)
at Tooltip (https://react-gxetif.stackblitz.io/turbo_modules/rc-tooltip@6.1.3/lib/Tooltip.js:21:32)
at eval (https://react-gxetif.stackblitz.io/turbo_modules/antd@5.15.1/lib/tooltip/index.js:37:16)
at eval (https://react-gxetif.stackblitz.io/turbo_modules/antd@5.15.1/lib/popover/index.js:43:18)
at eval (https://react-gxetif.stackblitz.io/turbo_modules/antd@5.15.1/lib/popconfirm/index.js:32:18)
at div
at App

### What is expected?

不报错

### What is actually happening?

控制台报错

| Environment | Info |
| --- | --- |
| antd | 5.15.1 |
| React | 18.2.0 |
| System | linux |
| Browser | chrome122.0.6261.111 |

**Comment by zombieJ** [comment] 2024-03-08 08:04
Radio 尚未支持 `nativeElement`

**Comment by afc163** [comment] 2024-03-14 03:52
Duplicate of https://github.com/ant-design/ant-design/issues/47863

**Comment by CooperHash** [comment] 2024-03-20 15:48
是否需要在popover底部添加跟popconfirm一样的提示：需要提供ref

**Comment by miaojinsing** [comment] 2024-03-24 09:35
菜单的折叠也是一样的  ，这个问题很久了 。

**Comment by CooperHash** [comment] 2024-03-24 09:53
> 是否需要在popover底部添加跟popconfirm一样的提示：需要提供ref

@afc163 是否需要在文档下面添加相应提示？

**Comment by afc163** [comment] 2024-03-24 10:23
@CooperHash 可以

**Comment by CooperHash** [comment] 2024-03-24 10:48
好，那我来update一下

**Closed** 2024-04-09 08:45 UTC
Labels: improvement
