### ISSUE TITLE
AntdV4 RangePicker when setting open = true the date cannot be selected correctly

### ISSUE THREAD

**Issue by conviva-zyang** [ant-design/ant-design#30930] opened 2021-06-09 09:51 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd4162-forked-cwz50?file=/index.js)

### Steps to reproduce
1. Click start date input box, start date get focus and highlight.
2. Click June 9, the input box focus automatically moves to end date, start date shows June 9.
3. Click June 25, the input box focus is still on end date, and the value of end date will change with the mouse.

### What is expected?
我遇到的主要问题是，设置open属性为true，然后通过onChange自己监听value变化自定义展示value值，所以这里不会出现range picker的输入框。当我在calendar选择了enddate 之后，输入框焦点依旧在end date。 再次点击又会选择一个end date。而我期望选择完end date之后再次点击calendar将重新选择一个start date。

### What is actually happening?
选择完end date之后点击calendar依旧会选择一个end date.

| Environment | Info |
|---|---|
| antd | undefined |
| React | ^16.14 |
| System | MacOs 10.15.7 (19H15) |
| Browser | Chrome  90.0.4430.93（正式版本） (x86_64) |

**Comment by afc163** [comment] 2021-06-10 05:39
Duplicate of #30525

**Closed by afc163** 2021-06-10 05:39 UTC
