### ISSUE TITLE
Modal 弹出页是否可以自定义固定高度，当页面超出设定高度时实现滚动

### ISSUE THREAD

**Issue by houdingding** [ant-design/ant-design#11376] opened 2018-07-20 05:41 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当弹出页内容过多时，可以是滚动，使得页面更美观些（比如form表单）

### What does the proposed API look like?
Modal 弹出页是否可以自定义固定高度，当页面超出设定高度时实现滚动

**Comment by yesmeck** [comment] 2018-07-20 05:45
Duplicate of #5777

**Closed by yesmeck** 2018-07-20 05:45 UTC
