### ISSUE TITLE
Table树形数据展示 固定列 指定列宽 ellipsis时, 单元格自动省略不生效, 会把列撑开

### ISSUE THREAD

**Issue by tty295** [ant-design/ant-design#20986] opened 2020-01-17 10:01 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/tty295/pen/WNbaNMy](https://codepen.io/tty295/pen/WNbaNMy)

### Steps to reproduce
table使用树形数据展示, 设置最左列为固定列, 并指定最左列列宽, 然后添加了ellipsis=true, 实际显示的列中超长字段未自动省略, 而是把该列撑开.
提供的重现链接中, 撑开的列把第二列挡住了

### What is expected?
即便自动省略不生效, 也不要把其他列挡住

### What is actually happening?
超长字段未自动省略, 并遮挡了其他列

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | react 16 |
| System | windows10 |
| Browser | chrome 79.0.3945.117 |

**Comment by afc163** [comment] 2020-01-17 10:24
Duplicate of #19946

**Closed by afc163** 2020-01-17 10:24 UTC
