### ISSUE TITLE
element.ref在React19被移除了

### ISSUE THREAD

**Issue by whatdfjslfjldks** [ant-design/ant-design#51986] opened 2024-12-11 16:57 UTC
### Reproduction link

[https://www.google.com/idkwhattolink](https://www.google.com/idkwhattolink)

### Steps to reproduce

报错：Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release.
我试了react18.3.1和react19版本都有这个error提示，antd版本是5.22.4

### What is expected?

不报error

### What is actually happening?

报error

| Environment | Info |
| --- | --- |
| antd | 5.22.4 |
| React | 18.3.1 和 19 |
| System | Window10 |
| Browser | Google |

**Comment by dnwu** [comment] 2024-12-12 07:06
一样遇到

**Comment by luongductrong** [comment] 2024-12-13 17:57
This is also the issue I intend to report.

**Comment by afc163** [comment] 2024-12-14 15:31
Duplicate of #51339

**Closed by afc163** 2024-12-14 15:31 UTC
Labels: unconfirmed

**Comment by lqxzd** [comment] 2025-02-13 12:03
antd版本为5.x可以安装兼容包
npm install @ant-design/v5-patch-for-react-19 --save
在应用的时候引入：import '@ant-design/v5-patch-for-react-19';
或者降低react的版本到18.2.0及以下，记得同步降低react-dom和react-router-dom的版本
