### ISSUE TITLE
AntDesign Calender Component onSelect problem

### ISSUE THREAD

**Issue by JonathanDalien** [ant-design/ant-design#42400] opened 2023-05-16 08:09 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-0ihci4?file=/index.tsx)

### Steps to reproduce

I want to achieve that when the user clicks on a day, the selected day is saved in the state. However, I have the problem that when the month changes, the previously selected day is also saved in the state along with the currently selected month. When I log the onSelect event to the console and change the month, I receive 2 Dayjs objects.

### What is expected?

I dont want that the day with the new selected month is also in the output from onSelect and onChange. It should only run the onSelect prop when the user is clicking on a cell

### What is actually happening?

When you change the month, the onSelect prop console logs the day with the new month

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | 18.2.0 |
| System | MacOs |
| Browser | Brave |

**Comment by zombieJ** [comment] 2023-05-16 08:18
Duplicate of #40407

**Closed by zombieJ** 2023-05-16 08:18 UTC
Labels: unconfirmed
