### ISSUE TITLE
Tab组件点击内容区域出现蓝色边框

### ISSUE THREAD

**Issue by Codyooo** [ant-design/ant-design#22879] opened 2020-04-03 05:46 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/intelligent-sea-csoyn)

### Steps to reproduce
点击TabPane区域

### What is expected?
没有蓝色边框

### What is actually happening?
有蓝色边框

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.8.3 |
| System | mac |
| Browser | Chrome 80.0.3987.149（正式版本） （64 位） |

**Comment by xrkffgg** [comment] 2020-04-03 05:56
Solved  by : https://github.com/ant-design/ant-design/pull/22752

Next version will online.

**Comment by afc163** [comment] 2020-04-03 05:57
Duplicate of #22760

**Closed** 2020-04-03 05:57 UTC

**Comment by susiachen** [comment] 2020-04-10 06:48
有解决方法了 吗

**Comment by yoyo837** [comment] 2020-04-10 06:50
@susiachen 已修复，等发布新版本。
