### ISSUE TITLE
 使用Menu组件的Submenu，绑定了key，控制台报错Duplicated key 'undefined' used in Menu by path []

### ISSUE THREAD

**Issue by ztever** [ant-design/ant-design#33699] opened 2022-01-12 14:16 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://xx.com](https://xx.com)

### Steps to reproduce
```
const RenderMenuItem: React.FC<{ list: DirectoryItem[] }> = ({ list }) => (
    <>
      {list.map((node: DirectoryItem) => (
        <SubMenu
          key={node.id}
          icon={
            <PlusSquareOutlined
              onClick={(evt: React.MouseEvent) => {
                evt.stopPropagation();
                clickPlus(node);
              }}
            />
          }
          title={node.name}
        >
        </SubMenu>
      ))}
    </>
  );

  return (
    <Menu
      defaultOpenKeys={defaultOpenKeys}
      defaultSelectedKeys={defaultSelectKeys}
      className={styles.menuList}
      mode="inline"
      style={{ borderRight: 0 }}
    >
      <RenderMenuItem list={menuData} />
    </Menu>
  );
};
```

### What is expected?
submenue的key能成功帮定

### What is actually happening?
node.id有值，但是submemu的key是undefined

| Environment | Info |
|---|---|
| antd | 4.17.0 |
| React | 17.0 |
| System | macOS |
| Browser | chrome 97.0.4692.71 |

**Comment by afc163** [comment] 2022-01-12 14:27
Duplicate of https://github.com/ant-design/ant-design/issues/4853

**Comment by afc163** [comment] 2022-01-12 15:04
Try `eventKey`.

**Comment by afc163** [comment] 2022-01-12 15:05
```diff
const RenderMenuItem: React.FC<{ list: DirectoryItem[] }> = ({ list }) => (
    <>
      {list.map((node: DirectoryItem) => (
        <SubMenu
          key={node.id}
+         eventKey={node.id}
          icon={
            <PlusSquareOutlined
              onClick={(evt: React.MouseEvent) => {
                evt.stopPropagation();
                clickPlus(node);
              }}
            />
          }
          title={node.name}
        >
        </SubMenu>
      ))}
    </>
  );

  return (
    <Menu
      defaultOpenKeys={defaultOpenKeys}
      defaultSelectedKeys={defaultSelectKeys}
      className={styles.menuList}
      mode="inline"
      style={{ borderRight: 0 }}
    >
      <RenderMenuItem list={menuData} />
    </Menu>
  );
};
```

**Closed** 2022-01-12 15:05 UTC

**Comment by ztever** [comment] 2022-01-13 02:48
> ```diff
> const RenderMenuItem: React.FC<{ list: DirectoryItem[] }> = ({ list }) => (
>     <>
>       {list.map((node: DirectoryItem) => (
>         <SubMenu
>           key={node.id}
> +         eventKey={node.id}
>           icon={
>             <PlusSquareOutlined
>               onClick={(evt: React.MouseEvent) => {
>                 evt.stopPropagation();
>                 clickPlus(node);
>               }}
>             />
>           }
>           title={node.name}
>         >
>         </SubMenu>
>       ))}
>     </>
>   );
> 
>   return (
>     <Menu
>       defaultOpenKeys={defaultOpenKeys}
>       defaultSelectedKeys={defaultSelectKeys}
>       className={styles.menuList}
>       mode="inline"
>       style={{ borderRight: 0 }}
>     >
>       <RenderMenuItem list={menuData} />
>     </Menu>
>   );
> };
> ```

加上eventkey后，控制台会报Each child in a list should have a unique "key" prop.的错误

**Comment by ztever** [comment] 2022-01-13 04:10
不用函数组件，就不会报错了
```
const renderMenuItem = menuData.map((node: DirectoryItem) => (
    <SubMenu
      key={node.id}
      icon={
        <PlusSquareOutlined
          onClick={(e: React.MouseEvent) => {
            e.stopPropagation();
            clickPlus(node);
          }}
        />
      }
      title={node.name}
    >
      {node.children &&
        node.children.map((node2: DirectoryItem) => {
          return (
            <Menu.Item onClick={() => onClickMenueItem(node2, node)} key={node2.id}>
              {node2.name}
            </Menu.Item>
          );
        })}
    </SubMenu>
  ));

  return (
    <Menu
      defaultOpenKeys={defaultOpenKeys}
      defaultSelectedKeys={defaultSelectKeys}
      className={styles.menuList}
      mode="inline"
      style={{ borderRight: 0 }}
    >
      {renderMenuItem}
    </Menu>
  );
};
```

**Comment by RyanWhipple** [comment] 2022-03-09 20:20
> Try `eventKey`.

Thanks, this worked for me!  `eventKey` isn't listed as an API in the docs, either in SubMenu or Menu.  Should this be updated?

https://ant.design/components/menu/

**Comment by zee-algo** [comment] 2022-12-09 07:54
> Try `eventKey`.

Thanks a lot. It worked!

**Comment by phuctran2901** [comment] 2023-01-23 12:20
eventKey current version is not provided anymore, is there any workaround anymore?

**Comment by khanisak** [comment] 2023-06-29 05:04
@phuctran2901 did you find a workaround? on v5.0.7 eventKey props exist on Menu.Item but does
not exist on Menu.SubItem
