### ISSUE TITLE
react 更新到16.9.0后，组件报生命周期警告

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#18405] opened 2019-08-22 06:35 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/determined-pine-7twl5)

### Steps to reproduce
用组件就会报

### What is expected?
使用react官方推荐的 `npx react-codemod rename-unsafe-lifecycles`  重命名一下

### What is actually happening?
报警告

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | latest |
| System | windows10 |
| Browser | chrome74 |

**Comment by XianZhengquan** [comment] 2019-08-22 06:37
还有你们配套的 设计动效里面的  `rc-tween-one`

**Comment by afc163** [comment] 2019-08-22 06:43
Duplicate of #9792

**Closed by afc163** 2019-08-22 06:43 UTC
