### ISSUE TITLE
InputNumber添加addonAfter无效

### ISSUE THREAD

**Issue by ybning** [ant-design/ant-design#10846] opened 2018-06-08 02:31 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
Win7 64位，Chrome 66.0.3359.117

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/py6q3pqj1j)

### Steps to reproduce
```
<InputNumber min={1} max={100} addonAfter={`折`} />
```

### What is expected?
![iput_addonafter](https://user-images.githubusercontent.com/3725612/41136056-108798fa-6b07-11e8-88f9-c829c341fec0.png)

### What is actually happening?
![iput_addonafter2](https://user-images.githubusercontent.com/3725612/41136061-16b68f24-6b07-11e8-8d4c-1b6b598130d7.png)

**Comment by afc163** [comment] 2018-06-08 02:32
InputNumber don't support `addon` yet.

**Comment by afc163** [comment] 2018-06-08 06:37
Duplicate of #1228

or you can try Input.Group: https://ant.design/components/input/#components-input-demo-group

**Closed by afc163** 2018-06-08 06:37 UTC

**Comment by crazyair** [comment] 2021-11-02 06:04
> InputNumber中添加这个属性无效

https://ant-design.gitee.io/components/form-cn/#%E6%9C%89%E6%9B%B4%E5%A4%9A%E5%8F%82%E8%80%83%E6%96%87%E6%A1%A3%E5%90%97%EF%BC%9F

**Comment by yanghuanrong** [comment] 2021-11-04 03:00
实际使用效果与文档不一致。
