### ISSUE TITLE
希望Input组件增加限制输入长度后，显示限制长度和当前输入长度

### ISSUE THREAD

**Issue by wangrenhai123** [ant-design/ant-design#26836] opened 2020-09-21 06:17 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
很多场景下需要限制用户输入的总长度，该功能虽然进行二次封装也比较容易，但是在使用form组件包裹Input后封装该功能变得困难。

### What does the proposed API look like?
在Input组件上添加一个API用于控制是否显示限制长度，类似element-ui的show-word-limit

**Comment by afc163** [comment] 2020-09-21 06:29
Duplicate of #24940

**Closed by afc163** 2020-09-21 06:29 UTC
