### ISSUE TITLE
TreeSelect treeCheckable 属性失效

### ISSUE THREAD

**Issue by morooi** [ant-design/ant-design#33438] opened 2021-12-28 03:08 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-select-cn/#components-tree-select-demo-checkable](https://ant.design/components/tree-select-cn/#components-tree-select-demo-checkable)

### Steps to reproduce
直接重现

### What is expected?
出现可勾选框

### What is actually happening?
没有出现可勾选框

| Environment | Info |
|---|---|
| antd | 4.18.0 |
| React | 16.14.0 |
| System | macOS 12.1 |
| Browser | Google Chrome 96.0.4664.110 |

---
实测 4.17.4 版本无此问题

**Comment by zombieJ** [comment] 2021-12-29 03:36
Duplicate of #33447

**Closed by zombieJ** 2021-12-29 03:36 UTC
