### ISSUE TITLE
antd Table合计

### ISSUE THREAD

**Issue by OnPure** [ant-design/ant-design#16932] opened 2019-06-03 08:31 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
实现如同execl表格的合计功能，并且支持分页，翻页后如同footer一样附在末尾，最好紧紧贴合，每一列要对齐，可以指定列的key，自动计算和

### What does the proposed API look like?
total

**Comment by afc163** [comment] 2019-06-03 08:41
Duplicate of #5710

**Closed by afc163** 2019-06-03 08:41 UTC
