### ISSUE TITLE
table开启虚拟滚动后，components属性会失效

### ISSUE THREAD

**Issue by linzhaoyang** [ant-design/ant-design#45525] opened 2023-10-25 08:58 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xu-ni-lie-biao-antd-5-10-2-forked-dfgf3p?file=/demo.tsx)

### Steps to reproduce

将table开启虚拟滚动，添加components属性并添加header和body

### What is expected?

能得到components属性的预期结果

### What is actually happening?

components属性属性无效

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | 17.0.2 |
| System | window10 |
| Browser | 103.0.5060.134 |

**Comment by yoyo837** [comment] 2023-10-25 08:59
Duplicate of #35776 44787

**Closed by yoyo837** 2023-10-25 08:59 UTC
Labels: unconfirmed
