### ISSUE TITLE
Input.TextArea 带移除图标的输入框 allowClear 样式错乱问题

### ISSUE THREAD

**Issue by XSmarter** [ant-design/ant-design#23874] opened 2020-05-05 07:04 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce
https://ant.design/components/input-cn/

### What is expected?
https://ant.design/components/input-cn/

### What is actually happening?
正常样式，可以正常占用区域，而不是覆盖其他区域

![image](https://user-images.githubusercontent.com/33716687/81041994-c0b38e00-8ee1-11ea-84fd-960dc490c829.png)

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 所有版本 |
| System | 所有系统 |
| Browser | 所有浏览器 |

**Comment by zombieJ** [comment] 2020-05-05 07:36
Duplicate of #23688

**Closed by zombieJ** 2020-05-05 07:36 UTC
