### ISSUE TITLE
Dropdown overlay shows at incorrect position when use zoom property in styles

### ISSUE THREAD

**Issue by ofsajd** [ant-design/ant-design#27371] opened 2020-10-26 08:24 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-wkpum8](https://stackblitz.com/edit/react-wkpum8)

### Steps to reproduce
- create a dropdown in the right side of viewport
- set zoom property in styles for the html element, eg. `html{ zoom: 80%}`
- click the dropdown trigger

### What is expected?
overlay shows in place defined in placement props

### What is actually happening?
overlay shows in a random place in horizontal axis, different for different zoom value

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 17.0.0 |
| System | MacOS Mojave |
| Browser | Chrome 86.0.4240.111 |

**Comment by afc163** [comment] 2020-10-26 08:30
Duplicate of #20368

**Closed by afc163** 2020-10-26 08:30 UTC

**Comment by afc163** [comment] 2020-11-13 05:44
Duplicate of #26681

**Comment by ZhouYing-JOEY** [comment] 2022-10-08 08:18
问题没解决为什么关闭了
