### ISSUE TITLE
TimePicker的范围选择器，设置format="HH:mm" ，点击结束时间，展开面板不符合预期

### ISSUE THREAD

**Issue by yoghurtxu** [ant-design/ant-design#38055] opened 2022-10-17 07:49 UTC
### Reproduction link

[https://www.google.com](https://www.google.com)

### Steps to reproduce

<TimePicker.RangePicker format="HH:mm" />，点击结束时间

### What is expected?

在结束时间的下方展开面板

### What is actually happening?

在开始时间的下方展开面板，且少了箭头

| Environment | Info |
| --- | --- |
| antd | 4.23.5 |
| React | 18.2.0 |
| System | macOS Catalina 10.15.7 |
| Browser | 谷歌 106.0.5249.119 |

**Comment by yoghurtxu** [comment] 2022-10-17 07:49
算是比较紧急且严重的bug了，辛苦修复！

**Comment by afc163** [comment] 2022-10-17 08:21
Duplicate of #35247

**Closed by afc163** 2022-10-17 08:21 UTC
