### ISSUE TITLE
TreeSelect does not support showArrow

### ISSUE THREAD

**Issue by ben-goldberg** [ant-design/ant-design#20711] opened 2020-01-06 22:12 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/intelligent-hawking-2bcce)

### Steps to reproduce
Create a TreeSelect w/ "multiple" prop set to true, and "showArrow" prop set to true.

### What is expected?
The arrow icon is shown at the right of the select box.

### What is actually happening?
There is no arrow icon at the right of the select box.

| Environment | Info |
|---|---|
| antd | 3.26.1 |
| React | 16.12.0 |
| System | 10.14.6 |
| Browser | Chrome 79.0.3945.88 |

---
This is supported for the "Select" element previously, from this issue: https://github.com/ant-design/ant-design/issues/12250.

**Comment by zombieJ** [comment] 2020-01-07 11:54
Duplicate of #18625

**Closed by zombieJ** 2020-01-07 11:54 UTC
