### ISSUE TITLE
[Customised Modal Footer Example] Loading icon still in DOM after loading complete causing malformed submit button.

### ISSUE THREAD

**Issue by mjfwebb** [ant-design/ant-design#24428] opened 2020-05-24 10:46 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ipm53)

### Steps to reproduce
Click the Open modal button. Click the submit button in the modal. Wait for the modal to close. Click the open modal button again.

### What is expected?
The submit button shouldn't be malformed.

### What is actually happening?
After the first round of submission and hiding of the modal, once opening it again, you see the submit button still has a size where the "loading" spinner would be, if it were visible.

![image](https://user-images.githubusercontent.com/28074382/82752184-8e000580-9dbc-11ea-9325-84c6d22f3ba7.png)

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | React |
| System | Windows 10 |
| Browser | Version 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit) |

**Comment by afc163** [comment] 2020-05-24 12:06
Duplicate of #24382

**Closed by afc163** 2020-05-24 12:06 UTC
