### ISSUE TITLE
Mention组件一直选择，内容会换行溢出

### ISSUE THREAD

**Issue by Joudee** [ant-design/ant-design#8914] opened 2018-01-10 10:46 UTC
### Version
3.1.1

### Environment
线上

### Reproduction link
[https://ant.design/components/mention-cn/](https://ant.design/components/mention-cn/)

### Steps to reproduce
示例先输入@唤起下拉，然后不停的@选中

### What is expected?
超出不显示

### What is actually happening?
超出会换行溢出

**Comment by yesmeck** [comment] 2018-01-10 12:54
Duplicate of #7717

**Closed by yesmeck** 2018-01-10 12:54 UTC
Labels: Component: Mention
