### ISSUE TITLE
Form input shakes after validation message disappear

### ISSUE THREAD

**Issue by hexwit** [ant-design/ant-design#35263] opened 2022-04-26 20:51 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-input-shaking-hndtpv?file=/src/App.js)

### Steps to reproduce

1. Make Username field show error message (enter something, and delete, to have field empty)
2. Do not leave input field and enter any value to make error message disappear
3. Watch password field and rest of the form. It is moved few pixels down, and returned back.

### What is expected?

Form elements should not move or shake.

### What is actually happening?

All form fields below username field are moved for a few pixels down, and then returned back. 

| Environment | Info |
| --- | --- |
| antd | 4.20.1 |
| React | 18.1.0 |
| System | MacOS Catalina |
| Browser | Chrome 100.0.4896.127 (Official Build) (x86_64) |

---
I don't see such behaviour on your documentation site, but I see it in local dev environment and in the sandbox. I copied and pasted code from the documentation.

**Comment by afc163** [comment] 2022-04-27 01:54
Duplicate of #34267

**Closed by afc163** 2022-04-27 01:54 UTC
