### ISSUE TITLE
Performance issue of tree component

### ISSUE THREAD

**Issue by mengfei0053** [ant-design/ant-design#15039] opened 2019-02-25 09:01 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
大数据量的tree组件渲染，卡顿问题，可否使用react-virtualized 或其他类似组件，进行优化。

### What does the proposed API look like?
加入一个是否开启虚拟化的开关的props，提高组件性能

**Comment by afc163** [comment] 2019-02-25 09:02
trace #3789

**Comment by afc163** [comment] 2019-02-25 09:02
Duplicate of #3789

**Closed by afc163** 2019-02-25 09:02 UTC
