### ISSUE TITLE
Menu render several times，it may cause performance problem

### ISSUE THREAD

**Issue by stonehank** [ant-design/ant-design#10720] opened 2018-05-31 09:11 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.4

### Environment
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

### Reproduction link
[https://ant.design/components/menu-cn/#components-menu-demo-inline-collapsed](https://ant.design/components/menu-cn/#components-menu-demo-inline-collapsed)

### Steps to reproduce
In /components/menu/index.tsx

about line 159

```js
getRealMenuMode() {
    const inlineCollapsed = this.getInlineCollapsed();
    // before(original)
    if (this.switchModeFromInline && inlineCollapsed) {
    // after
    //  if (this.switchModeFromInline && !inlineCollapsed) {
      return 'inline';
    }
    const { mode } = this.props;
    return inlineCollapsed ? 'vertical' : mode;
  }
```
The original code is ``` if (this.switchModeFromInline && inlineCollapsed)```;

If the SubMenu is expand and it's child SubMenu is also expand, then click a button to change it to collapsed inline menu, the Menu will render several times, because in here the this.switchModeFromInline && inlineCoolapsed are true, and the collapsed inline menu is consider as 'inline' mode.

If change to ```if (this.switchModeFromInline && !inlineCollapsed) ```, it will just render once.

So i was wonder it should be some adjust in the ```if``` statements or it's the expected effect.

before:

![](https://github.com/stonehank/temp/blob/master/muti-before-700.png?raw=true)

Click once, It's scripting 141ms.

![](https://github.com/stonehank/temp/blob/master/before-compress.gif?raw=true)

after:

![](https://github.com/stonehank/temp/blob/master/muti--after-700.png?raw=true)

Click once. It's scripting 51ms.

![](https://github.com/stonehank/temp/blob/master/after-compress.gif?raw=true)

### What is expected?
just render once

### What is actually happening?
render more than once

**Comment by picodoth** [comment] 2018-06-05 03:16
@stonehank thanks for this investigation. It was intended for better animation.

https://github.com/ant-design/ant-design/blob/master/components/menu/index.tsx#L198

Please pay close attention to the icon of navigation two (last item)

Smooth animation:
![ani1](https://user-images.githubusercontent.com/1731837/40953287-a3eb3bae-68b1-11e8-8136-27e5a8104d77.gif)

Non-smooth animation:
![ani2](https://user-images.githubusercontent.com/1731837/40953292-a9f38042-68b1-11e8-87e7-a2421ba71ff5.gif)

**Comment by picodoth** [comment] 2018-06-05 03:17
Closing this one

**Closed by picodoth** 2018-06-05 03:17 UTC
Labels: Component: Menu, Performance

**Comment by stonehank** [comment] 2018-06-05 05:18
@picodoth Yes, I got it!Thanks for your time!
