### ISSUE TITLE
Select组件在移动端Safari浏览器下，allowClear功能失效

### ISSUE THREAD

**Issue by littledian** [ant-design/ant-design#51393] opened 2024-10-28 01:19 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/sou-suo-kuang-antd-5-21-5-forked-jdwfx5?workspaceId=e572d46f-9fcd-4ec8-bb96-d39595174f3f)

### Steps to reproduce

用iPad或者iPhone打开该链接，点击选中一个选项，再次点击聚焦右侧出现 × 图表，点击无效，不会清空选项。

### What is expected?

点击 × 图标，清空选项

### What is actually happening?

点击 × 图标，不会清空选项

| Environment | Info |
| --- | --- |
| antd | 5.21.5 |
| React | ^18.0.0 |
| System | iOS 17.6.1 |
| Browser | Safari |

**Comment by wanpan11** [comment] 2024-10-28 01:30
未公开

![image](https://github.com/user-attachments/assets/4a87f0ab-8183-4303-944b-8ef757fed63a)

**Comment by littledian** [comment] 2024-10-28 05:55
> 未公开
> 
> ![image](https://private-user-images.githubusercontent.com/38714194/380549195-4a87f0ab-8183-4303-944b-8ef757fed63a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTUxOTUsIm5iZiI6MTczMDA5NDg5NSwicGF0aCI6Ii8zODcxNDE5NC8zODA1NDkxOTUtNGE4N2YwYWItODE4My00MzAzLTk0NGItOGVmNzU3ZmVkNjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA1NTQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNTM5ZmViNjMwMDU3NGQ3ZjIxZGJiMDY0YTVkMDE2YzVhNTczMzhjNWJjOTEzNmNiOTA4MWE4ZGJkODY4NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vdlcV3uttiwZW0UvB93fY4qV1mbn__yZBoQYy9-Pktw)

Sorry，现在已公开

**Comment by afc163** [comment] 2024-10-28 06:30
Duplicate of #28917

PR is welcome~

**Closed by afc163** 2024-10-28 06:30 UTC
Labels: 🤔 Need Reproduce
