### ISSUE TITLE
select a row key in a Table shouldn't trigger re-sort

### ISSUE THREAD

**Issue by calldanfeng** [ant-design/ant-design#13807] opened 2018-12-24 07:27 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.4

### Environment
Any os/browser

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l3443kpnq7)

### Steps to reproduce
https://codesandbox.io/s/l3443kpnq7

Create a table with 100,000 records. If the column hasn't ever been sorted. It's very fast to check/uncheck a record. But if a column has been sorted. It's very slow to check/uncheck a record. From a chrome performance analytics, most of the time cost is cost by Table#recursiveSort.
创建10万条记录的表。如果这个表未曾被排序过，勾选/取消勾选其中的行反应速度非常快。一旦这个表被排序后，勾选/取消勾选将会变得非常慢。从Chrome性能分析中可知大部分的时间消耗来自于Table组件的recursiveSort函数。

### What is expected?
check/uncheck a row in a table shouldn't trigger re-sort. 
勾选/取消勾选 不应该触发排序

### What is actually happening?
check/uncheck a row triggered re-sort as long as the Table has ever been sorted.
只要表格被排序过，勾选/取消勾选 会重新触发排序

**Comment by afc163** [comment] 2018-12-24 08:43
Duplicate of #13790

**Closed by afc163** 2018-12-24 08:43 UTC
