### ISSUE TITLE
官网导航菜单Menu示例第三个demo表现异常

### ISSUE THREAD

**Issue by jeanlikecoding** [ant-design/ant-design#34195] opened 2022-02-24 10:47 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu-cn/](https://ant.design/components/menu-cn/)

### Steps to reproduce
第三个demo展示【缩起/展开】功能：
1. 点击缩起，点击最后一个菜单项 > Submenu > Option 12
2. 点击展开
3. 点击最后一个菜单项中 Submenu 表现异常

### What is expected?
表现正确

### What is actually happening?
表现异常，缩起的子菜单会闪动

| Environment | Info |
|---|---|
| antd | 4.18.8 |
| React | 官网demo |
| System | window 10 |
| Browser | chrome 94.0.4606.61（正式版本）（64 位） |

**Comment by afc163** [comment] 2022-02-25 06:24
没发现有啥异常，能给个 gif 么？

**Comment by kkkisme** [comment] 2022-02-25 06:35
应该是这个问题 https://github.com/ant-design/ant-design/issues/32312

**Comment by afc163** [comment] 2022-02-25 06:44
Duplicate of #32312

**Closed by afc163** 2022-02-25 06:44 UTC
Labels: needs-more-info

**Comment by jeanlikecoding** [comment] 2022-02-25 07:18
图来了，点击submenu会有浮窗闪动。
![GIF 2022-2-25 15-16-11](https://user-images.githubusercontent.com/39725664/155671750-cb830150-1911-476c-9725-da1e91053b02.gif)
