### ISSUE TITLE
RangePicker设置 mode={["time", "time"]} showTime 时日期显示错误

### ISSUE THREAD

**Issue by TomLeel** [ant-design/ant-design#18142] opened 2019-08-07 08:04 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
getFieldDecorator包裹RangePicker设置 mode={["time", "time"]} showTime

### What is expected?
1、正确显示月份  
2、未传初始值或清除值后，确认按钮能够确认

### What is actually happening?
1、选择时间面板的月份比输入框的月份多1   
![image](https://user-images.githubusercontent.com/24224985/62605561-fa447200-b92c-11e9-8f53-79c2f2673dfa.png)

2、未传初始值或清除值后，时间选择不能确认，确认按钮呈现置灰状态
![image](https://user-images.githubusercontent.com/24224985/62605571-029cad00-b92d-11e9-8435-019beeb92aca.png)

| Environment | Info |
|---|---|
| antd | 3.21.2 |
| React | 16.8.6 |
| System | win 10 |
| Browser | Chrome |

**Comment by afc163** [comment] 2019-08-08 15:25
Duplicate of #17779

**Closed by afc163** 2019-08-08 15:25 UTC
