### ISSUE TITLE
radio component is incorrect in Firefox and IE browser style

### ISSUE THREAD

**Issue by jinleli** [ant-design/ant-design#12533] opened 2018-10-08 02:08 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
win7 64, IE11，firefox 62.0.2

### Reproduction link
[https://ant.design/components/radio-cn/](https://ant.design/components/radio-cn/)

### Steps to reproduce
Open the ant.design official website with firefox or IE and check the radio components.

### What is expected?
The styles of the radio components are consistent with chrome

### What is actually happening?
In the Firefox and IE the dots in the radio are not centered.

---
resolution 1920 * 1080

**Comment by zombieJ** [comment] 2018-10-08 02:11
Duplicate of #12533

**Closed by zombieJ** 2018-10-08 02:11 UTC
