### ISSUE TITLE
Input Component with addonAfter layout error  in Form Component!

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#10413] opened 2018-05-08 06:04 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.0

### Environment
浏览器版本

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/48o7w2w5v4)

### Steps to reproduce
Input Component set addonAfter in Form Component!

### What is expected?
Layout ok

### What is actually happening?
Layout error

**Comment by yesmeck** [comment] 2018-05-08 06:08
Duplicate of #10371

**Closed by yesmeck** 2018-05-08 06:08 UTC
