### ISSUE TITLE
Table设置scroll后，高度足够显示内容的时候也会显示滚动条

### ISSUE THREAD

**Issue by shijunwen** [ant-design/ant-design#29392] opened 2021-02-20 09:23 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biaogexingliehebing-antd4123-forked-02826?file=/index.js:0-2381)

### Steps to reproduce
设置scroll={{ y: 540 }}

### What is expected?
在高度不够的时候显示滚动条

### What is actually happening?
不论高度是否足够都会显示滚动条

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 17.0.1 |
| System | Windows |
| Browser | Google Chrome 88.0.4324.182（正式版本） （64 位） |

**Comment by afc163** [comment] 2021-02-20 09:31
Duplicate of #29082

**Closed by afc163** 2021-02-20 09:31 UTC
