### ISSUE TITLE
鼠标 hover已经收起的侧边栏菜单控制台会报警告。 Warning: findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by chenjiajing23** [ant-design/ant-design#40881] opened 2023-02-22 13:48 UTC
### Reproduction link

[https://stackblitz.com/edit/react-mbqgto-m7izxy?file=index.tsx,demo.tsx](https://stackblitz.com/edit/react-mbqgto-m7izxy?file=index.tsx,demo.tsx)

### Steps to reproduce

鼠标hover已经收起的侧边栏菜单控制台会报警告。前提：1. menus 的items 只有一层，没有 children且菜单栏收起状态。具体看 demo.tsx 注释的代码 2. 加上 React.StrictMode

### What is expected?

控制台没有 "Warning: findDOMNode is deprecated in StrictMode."

### What is actually happening?

<img width="1855" alt="image" src="https://user-images.githubusercontent.com/41351722/220639481-a676fa74-adc3-4142-b47b-2d67d391b967.png">

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Trigger which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
at li
at InternalItem (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/rc-overflow@1.2.8/lib/Item.js:34:25)
at InternalRawItem (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/rc-overflow@1.2.8/lib/RawItem.js:33:23)
at LegacyMenuItem (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/rc-menu@9.8.2/lib/MenuItem.js:44:34)
at InternalMenuItem (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/rc-menu@9.8.2/lib/MenuItem.js:71:21)
at MenuItem (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/rc-menu@9.8.2/lib/MenuItem.js:194:24)
at Trigger (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/rc-trigger@5.3.4/lib/index.js:82:36)
at Tooltip (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/rc-tooltip@5.3.1/lib/Tooltip.js:21:32)
at eval (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/antd@5.2.2/lib/tooltip/index.js:82:16)
at MenuItem (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/antd@5.2.2/lib/menu/MenuItem.js:21:5)
at ul
at Overflow (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/rc-overflow@1.2.8/lib/Overflow.js:50:32)
at InheritableContextProvider (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/rc-menu@9.8.2/lib/context/MenuContext.js:31:23)
at eval (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/rc-menu@9.8.2/lib/Menu.js:55:27)
at eval (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/antd@5.2.2/lib/menu/menu.js:33:26)
at eval (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/antd@5.2.2/lib/menu/index.js:17:36)
at div
at aside
at eval (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/antd@5.2.2/lib/layout/Sider.js:46:18)
at section
at eval (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/antd@5.2.2/lib/layout/layout.js:74:13)
at eval (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/antd@5.2.2/lib/layout/layout.js:39:17)
at main
at eval (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/antd@5.2.2/lib/layout/layout.js:58:7)
at eval (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/antd@5.2.2/lib/layout/layout.js:39:17)
at section
at eval (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/antd@5.2.2/lib/layout/layout.js:74:13)
at eval (https://react-mbqgto-m7izxy.stackblitz.io/turbo_modules/antd@5.2.2/lib/layout/layout.js:39:17)
at App (https://react-mbqgto-m7izxy.stackblitz.io/~/demo.tsx:36:59)

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2.0 |
| System | mac os 13.2.1 |
| Browser | chrome 版本 110.0.5481.100（正式版本） (x86_64) |

---
具体看 demo.tsx 组件代码

**Comment by afc163** [comment] 2023-02-23 02:00
Duplicate of #35361

**Closed by afc163** 2023-02-23 02:00 UTC
Labels: unconfirmed
