### ISSUE TITLE
Moment 2.26.0 breaks DatePicker

### ISSUE THREAD

**Issue by pdeva** [ant-design/ant-design#24377] opened 2020-05-21 22:20 UTC
- [x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://none](http://none)

### Steps to reproduce
Set dependency to `"moment": "2.26.0"` and use DatePicker.
compile code with typescript 3.9.3

### What is expected?
should compile without errors

### What is actually happening?
getting this error message:

```

src/widgets/timepicker.tsx:187:52 - error TS2322: Type '(current: Moment) => boolean' is not assignable to type '(date: Moment) => boolean'.
  Types of parameters 'current' and 'date' are incompatible.
    Property 'isoWeeksInISOWeekYear' is missing in type 'moment.Moment' but required in type 'import("D:/testdash/node_modules/moment/ts3.1-typings/moment").Moment'.

187                     <DatePicker.RangePicker onChange={onRangePick} disabledDate={disabledDate} open={isDatePickerOpen} onOpenChange={open => setDatePickerOpen(open)}/>
                                                                       ~~~~~~~~~~~~

  node_modules/moment/ts3.1-typings/moment.d.ts:546:5
    546     isoWeeksInISOWeekYear(): number;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'isoWeeksInISOWeekYear' is declared here.
  node_modules/rc-picker/lib/PickerPanel.d.ts:28:5
    28     disabledDate?: (date: DateType) => boolean;
           ~~~~~~~~~~~~
    The expected type comes from property 'disabledDate' which is declared here on type '(IntrinsicAttributes & IntrinsicClassAttributes<Component<RangePickerProps<Moment>, any, any>> & Readonly<..
.> & Readonly<...>) | (IntrinsicAttributes & ... 2 more ... & Readonly<...>) | (IntrinsicAttributes & ... 2 more ... & Readonly<...>)'

```

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.13.1 |
| System | windows 10 |
| Browser | chrome 83 |

**Comment by zombieJ** [comment] 2020-05-22 02:53
Duplicate of #24322

**Closed by zombieJ** 2020-05-22 02:53 UTC
