### ISSUE TITLE
Trigger a selection is lag with hundreds numbers of data in table

### ISSUE THREAD

**Issue by FINAs** [ant-design/ant-design#19256] opened 2019-10-17 02:15 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/funny-sun-fk5hg)

### Steps to reproduce
1.Open the link
2.Trigger a selection on a row.

### What is expected?
After click,row is selected and editable.

### What is actually happening?
After click,it feels a slow motion in selection animation and meanwhile the scroll is not work

| Environment | Info |
|---|---|
| antd | 3.24.0 |
| React | react |
| System | windows10 |
| Browser | chrome,edge,firefox |

---
Selection works fine when  page size is little than 10

**Comment by afc163** [comment] 2019-10-17 02:27
Duplicate of #10431

**Closed by afc163** 2019-10-17 02:27 UTC
