### ISSUE TITLE
[4.0] Arrow missing when hover Select

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#20493] opened 2019-12-27 07:51 UTC
https://next.ant.design/components/input-cn/#components-input-demo-group

<img width="442" alt="image" src="https://user-images.githubusercontent.com/507615/71507793-b2fd5480-28c0-11ea-9c57-94d00858c8f5.png">

**Comment by shaodahong** [comment] 2019-12-27 08:09
Duplicate of #20371

**Closed by shaodahong** 2019-12-27 08:09 UTC
Labels: 4.0, 🐛 Bug
