### ISSUE TITLE
Bug: Button display with loading spinner in react 18 without tooltip

### ISSUE THREAD

**Issue by deepakbhattmits** [ant-design/ant-design#34850] opened 2022-04-02 13:29 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/priceless-kalam-wmdi8g)

### Steps to reproduce

No need to do any steps / extra effort , anyone can see button by default comes with loading icon if we add `loading={false}` from button then also we can see loading spinner  

### What is expected?

1. Button should display without loading icon
2. This should display Tooltip.

### What is actually happening?

Button is display with loading icon

| Environment | Info |
| --- | --- |
| antd | 4.19.3 |
| React | 18.0.0 |
| System | Ubuntu |
| Browser | Chrome |

**Comment by beeinger** [comment] 2022-04-03 13:03
Same thing, all Buttons show up with a loader when upgraded to React v18

**Comment by malkev** [comment] 2022-04-03 14:47
The problem is uncompatibility with **ReactDOM.createRoot**.
This is my index.tsx that cause the problem:
```
let rootElement = document.getElementById("root")
if(rootElement) {
  const root = ReactDOM.createRoot(rootElement)
  root.render(<StrictMode><App /></StrictMode>)
}
```

I solved in this way:
```
ReactDOM.render(
    <App />,
  document.getElementById('root')
);
```

**Comment by deepakbhattmits** [comment] 2022-04-03 14:55
@malkev what if users wants to use react 18

**Comment by deepakbhattmits** [comment] 2022-04-03 17:27
I have asked this with react team please look into this [react-component/trigger#288](https://github.com/react-component/trigger/issues/288)

**Comment by afc163** [comment] 2022-04-05 04:32
Duplicate of https://github.com/ant-design/ant-design/issues/34788

**Closed** 2022-04-08 03:16 UTC
Labels: React 18

**Comment by deepakbhattmits** [comment] 2022-04-08 12:51
I didn't see this is fixed yet but why this issue closed. May i know the reason behind this 

If you still want to see the open this link there is no tooltip and button comes with loading icon .. 

https://codesandbox.io/embed/priceless-kalam-wmdi8g?codemirror=1

**Comment by MatheusPatrickZup** [comment] 2022-04-26 17:40
Any updates on this? Still having the same issue.

**Comment by aguiar-tiago** [comment] 2022-06-13 14:39
+1
