### ISSUE TITLE
Seems to be some issues with latest version 3.8.0

### ISSUE THREAD

**Issue by jaisonjjames** [ant-design/ant-design#11634] opened 2018-08-07 05:29 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
Chrome

### Reproduction link
[https://ant.design/components/tabs/](https://ant.design/components/tabs/)

### Steps to reproduce
Tried with ant version 3.8.0 and got an error like below with production build by using tabs, but its working fine with the version 3.7.3. 
"Uncaught TypeError: Cannot read property 'ownerDocument' of undefined"

Also, there is some issue happing with select component and using chartjs v2 with the same page. Unable to select options id chart to exist on the page.

### What is expected?
With out error on production build.

### What is actually happening?
Error happening on production build and some compoent not workign as expected.

**Comment by afc163** [comment] 2018-08-07 05:32
Duplicate of #11612

**Closed by afc163** 2018-08-07 05:32 UTC
