### ISSUE TITLE
Select component on modal crashes when clicking on the scrollbar

### ISSUE THREAD

**Issue by lc-leoniefarmer** [ant-design/ant-design#27430] opened 2020-10-28 20:40 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-n9elo?file=/index.js)

### Steps to reproduce
Place the select element on a modal. Click to open the select element. Click on the scrollbar. 

### What is expected?
Clicking on the scrollbar should not crash the app.

### What is actually happening?
App crashes when you click on the scrollbar:

Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (react-dom.development.js:23803)
    at scheduleUpdateOnFiber (react-dom.development.js:21835)
    at Object.enqueueSetState (react-dom.development.js:12467)
    at ScrollBar.push../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:365)
    at ScrollBar._this.delayHidden (ScrollBar.js:59)
    at ScrollBar.componentDidUpdate (ScrollBar.js:222)
    at commitLifeCycles (react-dom.development.js:20684)
    at commitLayoutEffects (react-dom.development.js:23426)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at commitRootImpl (react-dom.development.js:23151)
    at unstable_runWithPriority (scheduler.development.js:646)
    at runWithPriority$1 (react-dom.development.js:11276)
    at commitRoot (react-dom.development.js:22990)
    at performSyncWorkOnRoot (react-dom.development.js:22329)
    at react-dom.development.js:11327
    at unstable_runWithPriority (scheduler.development.js:646)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322)
    at flushSyncCallbackQueue (react-dom.development.js:11309)
    at scheduleUpdateOnFiber (react-dom.development.js:21893)
    at dispatchAction (react-dom.development.js:16139)
    at syncScrollTop (List.js:91)
    at onScrollBar (List.js:224)
    at ScrollBar.js:141

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | react |
| System | mac |
| Browser | chrome |

---
After opening select but before clicking on the scrollbar, the following error is displayed in the console.

index.js:1 Warning: `NaN` is an invalid value for the `top` css style property.

**Comment by afc163** [comment] 2020-10-29 02:51
Duplicate of #27282

**Comment by afc163** [comment] 2020-10-30 03:24
Fixed in https://github.com/react-component/virtual-list/commit/578c6994d5cba5173b55ee6ffe7d461946608c4f

**Closed by afc163** 2020-10-30 03:24 UTC
Labels: 🐛 Bug
