### ISSUE TITLE
Layout的Sider折叠时Menu闪烁，react 18

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design#39009] opened 2022-11-26 02:12 UTC
### Reproduction link

[https://ant.design/components/menu-cn#components-menu-demo-inline-collapsed](https://ant.design/components/menu-cn#components-menu-demo-inline-collapsed)

### Steps to reproduce

https://ant.design/components/menu-cn#components-menu-demo-inline-collapsed

### What is expected?

不闪动

### What is actually happening?

闪动

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | react |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment] 2022-11-27 14:16
Duplicate of #36152

**Closed by afc163** 2022-11-27 14:16 UTC
