### ISSUE TITLE
Radio.Group里的options属性，里面包裹的lable里有form.Item无法接收到其formItem的值

### ISSUE THREAD

**Issue by w602542704** [ant-design/ant-design#27550] opened 2020-11-04 10:30 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biaodanfangfadiaoyong-ant-design-demo-forked-l6i4y?file=/index.js)

### Steps to reproduce
1.Radio.Group里的options属性，
2.options数组里面包裹的label
3.label里有form.Item组件（reactNode类型）,
4.form.Item里面包裹着inputNumber组件
5.点击提交无法接收到其formItem的inputNumber值

### What is expected?
点击提交form下的name值可以接收到

### What is actually happening?
点击提交form下的name键值可以接收到，但是value无法接收到

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 16.9.17 |
| System | win |
| Browser | 谷歌 |

---
尽快修复吧

**Comment by yoyo837** [comment] 2020-11-04 10:35
Duplicate of #27551

**Closed by yoyo837** 2020-11-04 10:35 UTC
