### ISSUE TITLE
为什么antd4.0 5.0对比3.0性能下降很多 

### ISSUE THREAD

**Issue by okjun** [ant-design/ant-design#45379] opened 2023-10-17 03:30 UTC
### Reproduction link

[https://ant.design/components/tree-cn?locale=zh-CN](https://ant.design/components/tree-cn?locale=zh-CN)

### Steps to reproduce

打开https://ant.design/components/tree-cn?locale=zh-CN,使用react developer tools查看渲染次数

### What is expected?

和3.x一样

### What is actually happening?

4.x,5.x多次渲染

| Environment | Info |
| --- | --- |
| antd | 5.10.1 |
| React | react 16.9 |
| System | windows |
| Browser | chrome |

---
 antd4.0 5.0对比3.0性能下降很多 ，官网的例子对比都明显卡了挺多的，用react developer tools是显可以看到多次渲染 ，明明只应渲染子节点，但4.x,5.x渲染整个控件，树，下拉框等等都是这样的

**Comment by zombieJ** [comment] 2023-10-17 04:00
Duplicate of #45377

**Closed by zombieJ** 2023-10-17 04:00 UTC
Labels: unconfirmed
