### ISSUE TITLE
Depreciated warning in most of ant design components for react 16.9

### ISSUE THREAD

**Issue by Nilanth** [ant-design/ant-design#18238] opened 2019-08-13 04:53 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/0o4xq0n7r0)

### Steps to reproduce
Run antd in new version of reactjs and see the console 

### What is expected?
All depreciated life cycle method should be removed or added UNSAFE prefix to it

### What is actually happening?
Depreciated lifecycle method are present in ant design

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.9 |
| System | all |
| Browser | all |

**Comment by afc163** [comment] 2019-08-13 05:31
Duplicate of #9792

**Closed by afc163** 2019-08-13 05:31 UTC
