### ISSUE TITLE
Exposing interface

### ISSUE THREAD

**Issue by djyde** [ant-design/ant-design#6861] opened 2017-07-17 09:31 UTC
### What problem does this feature solve?
Interfaces should be exposed. For example, I have no way to import the `option` interface in `getFieldDecorator(id, option)`, which was declared in `Form.d.ts` (`WrappedFormUtils`). It should be exposed so that I could import it through `import { WrappedFormUtils } from 'antd'`.

### What does the proposed API look like?
FYI

**Comment by djyde** [comment] 2017-07-17 09:34
Real world example: https://github.com/mobxjs/mobx/blob/master/src/mobx.ts

**Comment by afc163** [comment] 2017-07-17 13:05
Duplicate of #6593

**Closed by afc163** 2017-07-17 13:05 UTC
