### ISSUE TITLE
webpack 打包antd文件时，样式解析出错。

### ISSUE THREAD

**Issue by jamieYou** [ant-design/ant-design#9481] opened 2018-03-02 06:10 UTC
### Version
3.2.2

### Environment
webpack@3.10.0

### Reproduction link
[https://ant.design/docs/react/introduce-cn](https://ant.design/docs/react/introduce-cn)

### Steps to reproduce
```
/* autoprefixer: off */
  filter: progid\:DXImageTransform\.Microsoft\.Blur(PixelRadius\=1, MakeShadow\=false);
              ^
Unrecognised input
```
文件地址：node_modules/antd/lib/spin/style/index.css(line 96, column 16)。
webpack相关配置
```
{
    test: /(\.js|\.jsx)$/,
    exclude: /node_modules/,
    use: ['babel-loader']
  },
  { test: /\.eot(\?v=\d .\d .\d )?$/, use: 'file-loader' },
  { test: /\.(woff|woff2)$/, use: 'file-loader' },
  { test: /\.ttf(\?v=\d .\d .\d )?$/, use: 'file-loader' },
  { test: /\.(jpe?g|png|gif|svg)$/i, use: 'url-loader?limit=10000' },
  { test: /\.ico$/, use: 'file-loader?name=[name].[ext]' },
  {
    test: /(\.css|\.less)$/,
    use: __DEV__
      ? ['style-loader', 'css-loader?sourceMap', postcssLoaderOptinos, lessLoaderOptinos]
      : ExtractTextPlugin.extract({
        use: ['css-loader?minimize', postcssLoaderOptinos, lessLoaderOptinos]
      })
  },
```

### What is expected?
打包成功

### What is actually happening?
打包失败

**Comment by yesmeck** [comment] 2018-03-02 06:22
Duplicate of #4915

**Closed** 2018-03-02 10:33 UTC
