### ISSUE TITLE
在umi框架中（使用SSR），使用antd的Menu组件，会出现 useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format.的错误 

### ISSUE THREAD

**Issue by VicoHu** [ant-design/ant-design#31324] opened 2021-07-08 14:59 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/VicoHu/umi-antd-menu-warning.git](https://github.com/VicoHu/umi-antd-menu-warning.git)

### Steps to reproduce
在编译并访问页面的时候会出现一个Warning警告
> Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.

### What is expected?
正常编译不出现错误

### What is actually happening?
编译完成，但是出现Warning警告

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17.0.2 |
| System | BigSur 11.4 |
| Browser | Chrome 91.0.4472.114 |

**Comment by afc163** [comment] 2021-07-09 02:46
Duplicate of #30396

**Closed by afc163** 2021-07-09 02:46 UTC
