### ISSUE TITLE
 In TS, the ‘label’ attribute passed into the ‘Select Option’ component is not recognized because it is not defined in interface ‘OptionProps’

### ISSUE THREAD

**Issue by liuxiayang** [ant-design/ant-design#25441] opened 2020-07-06 03:12 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/select-cn/](https://3x.ant.design/components/select-cn/)

### Steps to reproduce
1.Use label attribute in Option component
                   <Select
                        mode="multiple"
                        value={XX}       
                        optionFilterProp="label"
                        optionLabelProp="label"
                    >
                         <Select.Option label={'XX'}>
                                 <span>{'XX'}</span>
                          </Select.Option>
                    </Select>
2.TS error
      TS2769: No overload matches this call.
  Overload 1 of 2, '(props: OptionProps, context?: any): ClassicComponent<OptionProps, any>', gave the following error.
    Type '{ children: Element; key: number; label: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ClassicComponent<OptionProps, any>> & Readonly<...> & Readonly<...>'.
      Property 'label' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ClassicComponent<OptionProps, any>> & Readonly<...> & Readonly<...>'.
  Overload 2 of 2, '(props: OptionProps, context?: any): Component<OptionProps, any, any>', gave the following error.
    Type '{ children: Element; key: number; label: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<OptionProps, any, any>> & Readonly<OptionProps> & Readonly<...>'.
      Property 'label' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<OptionProps, any, any>> & Readonly<OptionProps> & Readonly<...>'.

### What is expected?
The label attribute in the Option component is compatible with TS

### What is actually happening?
TS error

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | react |
| System | macOs |
| Browser | Chrome |

---
Define label in interface OptionProps

**Comment by afc163** [comment] 2020-07-06 03:15
Duplicate of #17493

**Closed by afc163** 2020-07-06 03:15 UTC
