### ISSUE TITLE
Support React 17

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#27267] opened 2020-10-21 01:10 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
React 17 is release, support it?

![企业微信截图_20201021090945](https://user-images.githubusercontent.com/1730277/96660831-31117700-137d-11eb-8913-bbeb2ed6f5c5.png)

### What does the proposed API look like?
Support React 17.

**Comment by afc163** [comment] 2020-10-21 02:28
Duplicate of #26136

**Closed by afc163** 2020-10-21 02:28 UTC
