### ISSUE TITLE
Textarea feedback style

### ISSUE THREAD

**Issue by KInGATiLLa** [ant-design/ant-design#19556] opened 2019-11-04 10:37 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-9qxvo)

### Steps to reproduce
Textarea feedback style 

### What is expected?
Textarea feedback style not aligned properly in field

### What is actually happening?
Textarea feedback style not aligned properly in field

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.11.0 |
| System | Windows 10 64bit |
| Browser | 78.0 |

**Comment by afc163** [comment] 2019-11-04 11:16
Duplicate of https://github.com/ant-design/ant-design/issues/8956#issuecomment-357408374

**Closed by afc163** 2019-11-04 11:16 UTC
