### ISSUE TITLE
Table数据超过1000行，不分页的时候，checkbox选中的响应特别慢，导致整个页面特别卡

### ISSUE THREAD

**Issue by tipsxBase** [ant-design/ant-design#13593] opened 2018-12-12 12:34 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
windows10， chrome70.0.3538.102

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xolvk1z84p)

### Steps to reproduce
参见重现链接

### What is expected?
响应速度快，页面不会卡

### What is actually happening?
响应速度特别慢，页面会卡

**Comment by zy410419243** [comment] 2018-12-12 12:38
#3789

**Comment by afc163** [comment] 2018-12-12 12:39
Duplicate of #3789

**Closed by afc163** 2018-12-12 12:39 UTC
