### ISSUE TITLE
TreeSelect: has no horizontal scroll bar when using virtual scroll

### ISSUE THREAD

**Issue by JessArschoot** [ant-design/ant-design#34543] opened 2022-03-16 13:33 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-19-2-forked-1tmj3w?file=/index.js)

### Steps to reproduce
- add the prop virtualScroll = true
- add some more treeNodes to the treeNode  with value parent 1-0
- change the title of this tree node to some extremely long value. Which you are sure it will not be visible in the container

### What is expected?
The horizontal scroll bar should be visible

### What is actually happening?
Horizontal scrollbar is not visible, you don't see the long values

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | 16.18 |
| System | Windows, linux |
| Browser | Chrome 97.0.4692.71 |

**Comment by MadCcc** [comment] 2022-03-17 03:04
Duplicate of https://github.com/ant-design/ant-design/issues/33849

**Closed by MadCcc** 2022-03-17 03:04 UTC
