### ISSUE TITLE
menu组件inlineCollapsed=true，滑动出子菜单闪烁特别厉害

### ISSUE THREAD

**Issue by ziaochina** [ant-design/ant-design#8520] opened 2017-12-08 10:34 UTC
### Version
3.0.0

### Environment
chrome

### Reproduction link
[http://demo.whatsmk.com](http://demo.whatsmk.com)

### Steps to reproduce
demo.whatsmk.com  (user:13334445556 pwd:1),进入后收起菜单，鼠标滑过图标出第三级子菜单闪烁特别厉害

### What is expected?
期望不闪烁

### What is actually happening?
闪烁特别厉害

**Comment by afc163** [comment] 2017-12-13 12:04
Duplicate of #8557

**Closed by afc163** 2017-12-13 12:04 UTC

**Comment by ziaochina** [comment] 2017-12-14 00:20
更新了3.0.1,并没有解决问题

**Comment by ziaochina** [comment] 2017-12-14 00:27
![ezgif-2-5dc791a9be 1](https://user-images.githubusercontent.com/4494312/33969485-8ee90f06-e0a8-11e7-9f8b-cdded81e0f69.gif)

**Comment by ziaochina** [comment] 2017-12-14 00:27
@afc163 请再麻烦关注下，我这边测试了下，问题没有改善

**Comment by ziaochina** [comment] 2017-12-14 00:32
![ant](https://user-images.githubusercontent.com/4494312/33969633-56a97738-e0a9-11e7-9111-ea655c235cc3.gif)

**Comment by afc163** [comment] 2017-12-14 10:06
还未修复，见 #8557
