### ISSUE TITLE
升级React 18后 treeselect 第一个例子错误

### ISSUE THREAD

**Issue by meseme** [ant-design/ant-design#34804] opened 2022-03-31 02:23 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-19-4-forked-gq7q35?file=/index.js)

### Steps to reproduce

无法运行，直接卡死

### What is expected?

正常运行

### What is actually happening?

无法运行，直接卡死

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | 18.0.0 |
| System | Windows 10 Pro N 19043.1348 |
| Browser | Microsoft Edge Version 96.0.1054.41 |

**Comment by afc163** [comment] 2022-03-31 02:38
Duplicate of #34805

**Closed by afc163** 2022-03-31 02:38 UTC
