### ISSUE TITLE
Make individual Tree Nodes non draggable

### ISSUE THREAD

**Issue by DavidSichau** [ant-design/ant-design#18226] opened 2019-08-12 09:34 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We have a file structure, where some nodes are files that cannot be moved but viewed (e.g. read only files)

With antd Tree Component we can only either disable these nodes, but this will also make these nodes non selectable. Or have the nodes as default nodes, which can be moved around, and then handle invalid moves on the `onDragEnd` method.

For a user this behavior is not very convenient, as he can move the node around but on drop nothing happens.

However we want to be able to select a node to look at its content, but still be not able to move this node around.

### What does the proposed API look like?
Add an additional props to `<TreeNode>` component similar to `<Tree>`

`draggable`: Specifies whether this TreeNode is draggable of type boolean.

Which default value inherits from `draggable` of the `Tree` component.

**Comment by zombieJ** [comment] 2019-09-01 14:54
Duplicate of #15926

**Closed by zombieJ** 2019-09-01 14:54 UTC

**Comment by StubbornDeer** [comment] 2022-11-06 02:41
What is the solution? The documentation says:
```
draggable | Specifies whether this Tree or the node is draggable. Use icon: false to disable drag handler icon
```
but just setting icon to false to a node doesn't make it non-draggable (the handler is still enabled and the node can be dragged).
