### ISSUE TITLE
RangePicker当默认的开始日期和结束日期在同一个月份的时候界面显示异常

### ISSUE THREAD

**Issue by raymondjiang** [ant-design/ant-design#15940] opened 2019-04-08 10:43 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/#components-date-picker-demo-format](https://ant.design/components/date-picker-cn/#components-date-picker-demo-format)

### Steps to reproduce
第4个rangePicker的demo

### What is expected?
当前面板展示相邻的两个月份

### What is actually happening?
当前面板同一个月份展示了两遍

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.8.6 |
| System | macOS 10.14.3 |
| Browser | chrome 72.0.3626.121 |

**Comment by zombieJ** [comment] 2019-04-08 15:41
Duplicate of #15840

**Closed by zombieJ** 2019-04-08 15:41 UTC
