### ISSUE TITLE
on range-picker end month moves a month ahead of selected month on inputting the value and clicking enter

### ISSUE THREAD

**Issue by subbiah-logichub** [ant-design/ant-design#20656] opened 2020-01-03 21:11 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/s/woqpz

### Steps to reproduce
1) click second range picker to open it
2) click today in bottom right //end range will be 2020/01/03 11:41:48
3) click second range picker to open it
4) click end date and place your blinking cursor on the end date input box. // change the time manually or let it be the same doesn't matter. Don't change the date.
5) don't do anything just click enter.

### What is expected?
Expected behavior: end date should be same 2020/01/03 11:41:48

### What is actually happening?
Actual behavior: end date move a month ahead 2020/02/03 11:41:48

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 16.8.6 |
| System | mac 10.15.2 |
| Browser | chrome |

---
It only happens on enter event handler. Its works good on clicking ok button.

**Comment by subbiah-logichub** [comment] 2020-01-05 19:23
https://codesandbox.io/s/woqpz

**Comment by Maktel** [comment] 2020-01-09 15:40
Duplicate of #15353

**Closed** 2020-01-10 02:43 UTC
Labels: 🤔 Need Reproduce
