### ISSUE TITLE
ConfigProvider设置国际化，语言选为中文，Modal.confirm弹框第一次按钮是中文，点击按钮后变成英文了

### ISSUE THREAD

**Issue by rongzhx123** [ant-design/ant-design#27720] opened 2020-11-12 09:31 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/config-provider-cn/](https://ant.design/components/config-provider-cn/)

### Steps to reproduce
国际化demo那里切换到中文，点击Modal.confirm显示弹框，弹框第一次按钮是中文的；点击弹框按钮，按钮文字变成英文

### What is expected?
中文环境下，点击弹框按钮还是中文

### What is actually happening?
中文环境下，点击弹框按钮后变成英文

| Environment | Info |
|---|---|
| antd | 4.8.2|
| React | 16.13.1 |
| System | window |
| Browser | Chrome |

**Comment by xrkffgg** [comment] 2020-11-12 09:37
Duplicate of https://github.com/ant-design/ant-design/issues/27597

**Closed by xrkffgg** 2020-11-12 09:37 UTC
