### ISSUE TITLE
Make DatePicker internal input mirror `size` of external input for consistency

### ISSUE THREAD

**Issue by barneycarroll** [ant-design/ant-design#12658] opened 2018-10-15 17:43 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
Windows 10, Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k5z8rrol03)

### Steps to reproduce
Attempt to fill in the date as a string using the keyboard

### What is expected?
I should be able to navigate to the date input via keyboard and type in the date using numbers and punctuation.

### What is actually happening?
Instead I have to click on the external input, then click on the internal input, then start typing

**Comment by afc163** [comment] 2018-10-16 04:10
Duplicate of #12657

**Closed by afc163** 2018-10-16 04:10 UTC
