### ISSUE TITLE
Add swipe possibility to tabs component when screen size is mobile or tablets  and tabs count is big and appear tab prev and next arrows

### ISSUE THREAD

**Issue by Gherciu** [ant-design/ant-design#23265] opened 2020-04-14 20:22 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Will be very useful to add a swipe possibility to tabs component on mobile and tablets when tabs count is big and appear tabs arrow next and prev

### What does the proposed API look like?
Hmmm, something like this will be nice :
<Tabs allowSwipe > .... </Tabs>   or other more meaningful prop name

**Comment by afc163** [comment] 2020-04-20 04:18
same as #19015

**Comment by afc163** [comment] 2020-05-03 11:24
Duplicate of #19015

**Closed by afc163** 2020-05-03 11:24 UTC
