### ISSUE TITLE
Select sometimes doesn't scroll

### ISSUE THREAD

**Issue by JensD98** [ant-design/ant-design#26122] opened 2020-08-10 22:17 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-igs6s?file=/index.js)

### Steps to reproduce
Scroll to top or bottom without moving the mouse and try to scroll again.

### What is expected?
Scrolling should work.

### What is actually happening?
Scrolling doesn't work unless you move the mouse again.

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Google Chrome 84.0.4147.105 |

**Comment by afc163** [comment] 2020-08-11 01:58
I can't reproduce.

**Comment by 07akioni** [comment] 2020-08-11 05:46
It does exists, but randomly happens...

**Comment by JensD98** [comment] 2020-08-11 07:39
You have to scroll with determination :smiley: but I can get it reliable like this:
Without moving the mouse, scroll to the top and keep scrolling a little bit.

**Comment by 07akioni** [comment] 2020-08-11 09:45
> You have to scroll viciously 😃 but I can get it reliable like this:
> Without moving the mouse, scroll to the top or bottom and keep scrolling a little bit.

I did do that. It works sometimes.

**Comment by 07akioni** [comment] 2020-08-11 09:48
I find more stable reproduction steps.
1. do not use trackpad of mac
2. open select menu
3. scroll to bottom and point to 19
4. scroll down viciously
5. sometimes scroll up not working

**Comment by jingxiawl** [comment] 2020-08-17 06:18
@afc163  现在还是会出现这个问题，一样的只要多次在select下面滚动鼠标滑轮，会自动滚动到最下面或者最上面

**Comment by afc163** [comment] 2020-08-29 04:30
Is it resolved in antd 4.6.1 ?

**Comment by JensD98** [comment] 2020-08-29 08:46
Yes I think its fixed.

**Closed** 2020-08-29 09:01 UTC
Labels: 🐛 Bug
