### ISSUE TITLE
SelectedRowKeys and selectedRows behave inconsistently when the Table component loads data from a remote location

### ISSUE THREAD

**Issue by zhang0ZGC** [ant-design/ant-design#13430] opened 2018-12-04 09:18 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vxx8jq8k7)

### Steps to reproduce
1.  Select any column on the first page to view the console log.
2.  Click on the second page and then click on any column to view the console log.
3.   After the second step, `selectedRowKeys` is inconsistent with `selectedRows`, `selectedRows` only has the selected column data on the second page.

1. 在第一页选中任意列，查看控制台日志
2. 点击第二页，然后点击任意列，查看控制台日志
3. 第2步操作后，`selectedRowKeys`与`selectedRows`不一致，`selectedRows`只有第二页选中的列数据

### What is expected?
SelectedRowKeys behaves consistently with selectedRows

selectedRowKeys与selectedRows表现一致

### What is actually happening?
SelectedRows part of data loss after switching page

切换页码后selectedRows部分数据丢失

---
我使用了rowSelection这个玩意儿，发现跨页多选批量操作时总是漏了些数据。因为是借鉴antd-pro的，所以去看了一下antd-pro的查询表格，发现它加载数据的时候是把所有页的数据都一次性拿回来的，好像就没出现这个问题，我们每次只拿当前页的数据，选择后，selectedRows只剩下当前页一选择的数据了

**Comment by afc163** [comment] 2018-12-04 09:53
Duplicate of #11384

**Closed by afc163** 2018-12-04 09:53 UTC
