### ISSUE TITLE
表格组件拖拽手柄列样式错乱[Wrong style with component "Table" on function 'drag column']

### ISSUE THREAD

**Issue by battleanam** [ant-design/ant-design#25581] opened 2020-07-11 09:23 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-drag-sorting-handler](https://ant.design/components/table-cn/#components-table-demo-drag-sorting-handler)

### Steps to reproduce
1 进行拖拽排序操作（行的顺序发生变化，必要条件） drag and sort (row order change, necessary condition) 
2 对任意行进行拖拽  drag any row

### What is expected?
拖拽时不产生顺序变化时其他行的位置不发生变化
The position of other lines does not change when the order is not changed

### What is actually happening?
第二次进行拖拽时，移动一小部分，依旧使得其他行的位置发生变化
Other rows still change the position of themselves with less movement at the second time you drag

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | 16.x |
| System | win10 |
| Browser | ms edge insider |

**Comment by afc163** [comment] 2020-07-11 11:44
Duplicate of #25556

**Closed by afc163** 2020-07-11 11:44 UTC
