### ISSUE TITLE
antd Tree component props  "switcherIcon" just can be ReactNode,       I want can provide function like  (props: TreeNodeAttribute) => ReactNode 

### ISSUE THREAD

**Issue by beewolf233** [ant-design/ant-design#31585] opened 2021-07-29 09:12 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
when expand state change, switcherIcon can have diffrent icon show

### What does the proposed API look like?
<Tree 
switcherIcon={[<FolderFilled />, <FolderOpenFilled />]}
/>

or
<Tree 
switcherIcon={(props) => {
return props.expanded ? <FolderFilled /> : <FolderOpenFilled />
}}
/>

**Comment by afc163** [comment] 2021-07-29 09:18
Duplicate of #25632

**Closed by afc163** 2021-07-29 09:18 UTC
