### ISSUE TITLE
Select component: Option to turn off autoComplete of search input element on Chrome

### ISSUE THREAD

**Issue by thanhtunguet** [ant-design/ant-design#19609] opened 2019-11-07 04:03 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
My project leader ask me to turn of autocomplete feature of the search input of the select component. I thought of to create my own fork to modify code and use but the select component depends on `rc-select` so that I don't know how to implement this option in my own fork.

### What does the proposed API look like?
```javascript
<Select showSearch onSearch={handleSearch} searchAutoComplete={false} />
```

**Comment by afc163** [comment] 2019-11-07 05:54
Duplicate of #18808

**Closed by afc163** 2019-11-07 05:54 UTC
