### ISSUE TITLE
能否为tabs控件添加拖拽功能

### ISSUE THREAD

**Issue by maifine** [ant-design/ant-design#14341] opened 2019-01-15 07:09 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
tabs的拖拽还是比较常用的，希望考虑一下

### What does the proposed API look like?
希望提供内置的拖拽

**Comment by afc163** [comment] 2019-01-15 07:16
Duplicate of #9990

**Closed by afc163** 2019-01-15 07:16 UTC
