### ISSUE TITLE
TreeSelect 没有横向滚动条

### ISSUE THREAD

**Issue by ClaytonPetrosian** [ant-design/ant-design#27603] opened 2020-11-06 07:09 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当子分类层级较高时，一层一层开启后，最下层的子分类将看不到
![image](https://user-images.githubusercontent.com/17127196/98336646-3d1a5b80-2042-11eb-95c0-4c81e1f7826e.png)

### What does the proposed API look like?
希望当内容超出时能有横向的滚动条

**Comment by zombieJ** [comment] 2020-11-06 07:13
Duplicate of #24851

**Closed by zombieJ** 2020-11-06 07:13 UTC
