### ISSUE TITLE
Button always show loading spinner on React 18 with Strict Mode

### ISSUE THREAD

**Issue by ekodedypurnomo** [ant-design/ant-design#34893] opened 2022-04-07 02:56 UTC
### Reproduction link

[https://stackblitz.com/edit/react-ts-i8aq3d?file=index.tsx](https://stackblitz.com/edit/react-ts-i8aq3d?file=index.tsx)

### Steps to reproduce

Look at the button with React StrictMode enabled.

### What is expected?

Loading showing only when use 'loading' prop set to 'true'

### What is actually happening?

Loading spinner keep showing

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18.0.0 |
| System | MacOs 12.3 |
| Browser | Chrome 100.0 |

**Comment by afc163** [comment] 2022-04-07 03:02
Duplicate of #34788

**Closed by afc163** 2022-04-07 03:02 UTC

**Comment by deepakbhattmits** [comment] 2022-04-07 16:07
> ### Reproduction link
> https://stackblitz.com/edit/react-ts-i8aq3d?file=index.tsx
> 
> ### Steps to reproduce
> Look at the button with React StrictMode enabled.
> 
> ### What is expected?
> Loading showing only when use 'loading' prop set to 'true'
> 
> ### What is actually happening?
> Loading spinner keep showing
> 
> Environment	Info
> antd	4.19.5
> React	18.0.0
> System	MacOs 12.3
> Browser	Chrome 100.0

In
