### ISSUE TITLE
希望增加年份选择器

### ISSUE THREAD

**Issue by chenqq86** [ant-design/ant-design#13702] opened 2018-12-18 18:17 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望增加年份选择器

### What does the proposed API look like?
可以单独使用年份选择

**Comment by afc163** [comment] 2018-12-19 02:56
Duplicate of #4524

**Closed by afc163** 2018-12-19 02:56 UTC
