### ISSUE TITLE
TextArea在有allowClear属性时，不在父节点内，变为了浮动

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#23842] opened 2020-05-04 01:08 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wenbenyu-ant-design-demo-7s6nm)

### Steps to reproduce
TextArea在有allowClear属性时

### What is expected?
在父节点内

### What is actually happening?
变为了浮动

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.12 |
| System | Windows 10 |
| Browser | 谷歌浏览器 |

**Comment by zombieJ** [comment] 2020-05-04 03:17
Duplicate of #23688

**Closed by zombieJ** 2020-05-04 03:17 UTC
