### ISSUE TITLE
does antd has HtmlEditor?

### ISSUE THREAD

**Issue by top-soft** [ant-design/ant-design#13663] opened 2018-12-17 09:11 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Html Editor

### What does the proposed API look like?
<HtmlEditor>...</HtmlEditor>

**Comment by afc163** [comment] 2018-12-17 12:12
Duplicate of #1083

**Closed by afc163** 2018-12-17 12:12 UTC
