### ISSUE TITLE
ant4某个calc样式未使用~符号导致被less编译

### ISSUE THREAD

**Issue by HEJIN2016** [ant-design/ant-design#28939] opened 2021-01-20 02:34 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/menu/style/index.less](https://github.com/ant-design/ant-design/blob/master/components/menu/style/index.less)

### Steps to reproduce
143行代码 max-height: calc(100vh - 100px);被less编译，导致浏览器编译结果为    max-height: 0vh;

### What is expected?
期望该行代码改为max-height: ~'calc(100vh - 100px)';

### What is actually happening?
浏览器编译结果为    max-height: 0vh;

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | 16.13.0 |
| System | mac big sur |
| Browser | 版本 87.0.4280.141（正式版本） (x86_64) |

**Comment by afc163** [comment] 2021-01-20 02:43
建议升级 less 到 3.x 版本以上。

**Comment by afc163** [comment] 2021-01-20 02:45
<img width="546" alt="图片" src="https://user-images.githubusercontent.com/507615/105120085-8a1fb100-5b0c-11eb-8e2f-9e770d1bc044.png">

**Comment by afc163** [comment] 2021-01-20 02:49
Duplicate of #27782

**Closed by afc163** 2021-01-20 02:49 UTC

**Comment by logan2z** [comment] 2021-04-01 16:26
I'm not sure why this and the duplicate issue are both closed, the issue still exists in the latest code base.  It's clear that this use of `calc` has not been properly escaped like it has elsewhere in antd's less files.  This doesn't need much of an example to reproduce, it's obvious by inspection that the current code is incorrect.

**Comment by mtsee** [comment] 2021-08-17 16:34
> 建议升级 less 到 3.x 版本以上。

升级到4.x都没用

**Comment by mtsee** [comment] 2021-08-17 16:54
// 额，，，，，，，，，，官方不改就只有打补丁了

body {

  .ant-menu-vertical.ant-menu-sub,
  .ant-menu-vertical-left.ant-menu-sub,
  .ant-menu-vertical-right.ant-menu-sub {
    max-height: calc(~"100vh - 100px");
  }

  .ant-menu-inline .ant-menu-item,
  .ant-menu-inline .ant-menu-submenu-title {
    width: calc(~"100% + 1px");
  }

  .ant-menu.ant-menu-inline-collapsed>.ant-menu-item,
  .ant-menu.ant-menu-inline-collapsed>.ant-menu-item-group>.ant-menu-item-group-list>.ant-menu-item,
  .ant-menu.ant-menu-inline-collapsed>.ant-menu-item-group>.ant-menu-item-group-list>.ant-menu-submenu>.ant-menu-submenu-title,
  .ant-menu.ant-menu-inline-collapsed>.ant-menu-submenu>.ant-menu-submenu-title {
    left: 0;
    padding: 0 calc(~"50% - 16px / 2");
    text-overflow: clip;
  }

  .ant-menu-rtl.ant-menu-inline-collapsed.ant-menu-vertical .ant-menu-submenu-title {
    padding: 0 calc(~"50% - 16px / 2");
  }


  @media only screen and (max-width: 480px) {
    .ant-picker-calendar-header .ant-picker-calendar-month-select {
      width: calc(~"50% - 8px");
    }
  }

  .ant-drawer-header-no-title .ant-drawer-close {
    /* stylelint-disable-next-line function-calc-no-invalid */
    padding-right: calc(~"20px - var(--scroll-bar)");
  }

  .ant-modal {
    max-width: calc(~"100vw - 32px");
  }

  @media (max-width: 767px) {
    .ant-modal {
      max-width: calc(~"100vw - 16px");
    }
  }

  .ant-notification-notice {
    max-width: calc(~"100vw - 24px * 2");
  }

  .ant-notification-notice-message-single-line-auto-margin {
    width: calc(~"384px - 24px * 2 - 24px - 48px - 100%");
  }

  .ant-progress-show-info .ant-progress-outer {
    margin-right: calc(~"-2em - 8px");
    padding-right: calc(~"2em + 8px");
  }

  .ant-progress-rtl.ant-progress-show-info .ant-progress-outer {
    margin-left: calc(~"-2em - 8px");
    padding-left: calc(~"2em + 8px");
  }

  .ant-steps-dot .ant-steps-item-tail::after,
  .ant-steps-dot.ant-steps-small .ant-steps-item-tail::after {
    width: calc(~"100% - 20px");
  }

  .ant-steps-navigation.ant-steps-vertical>.ant-steps-item.ant-steps-item-active::before {
    height: calc(~"100% - 24px");
  }

  .ant-switch-checked .ant-switch-handle {
    left: calc(~"100% - 18px - 2px");
  }

  .ant-switch-small.ant-switch-checked .ant-switch-handle {
    left: calc(~"100% - 12px - 2px");
  }

  .ant-switch-rtl.ant-switch-checked .ant-switch-handle {
    right: calc(~"100% - 18px - 2px");
  }

  .ant-switch-rtl.ant-switch-small.ant-switch-checked .ant-switch-handle {
    right: calc(~"100% - 12px - 2px");
  }

  .ant-table-filter-dropdown-submenu>ul {
    max-height: calc(~"100vh - 130px");
  }

  .ant-timeline-item-tail {
    height: calc(~"100% - 10px");
  }

  .ant-timeline.ant-timeline-alternate .ant-timeline-item-left .ant-timeline-item-content,
  .ant-timeline.ant-timeline-right .ant-timeline-item-left .ant-timeline-item-content,
  .ant-timeline.ant-timeline-label .ant-timeline-item-left .ant-timeline-item-content {
    left: calc(~"50% - 4px");
    width: calc(~"50% - 14px");
  }

  .ant-timeline.ant-timeline-alternate .ant-timeline-item-right .ant-timeline-item-content,
  .ant-timeline.ant-timeline-right .ant-timeline-item-right .ant-timeline-item-content,
  .ant-timeline.ant-timeline-label .ant-timeline-item-right .ant-timeline-item-content {
    width: calc(~"50% - 12px");
  }

  .ant-timeline.ant-timeline-right .ant-timeline-item-right .ant-timeline-item-tail,
  .ant-timeline.ant-timeline-right .ant-timeline-item-right .ant-timeline-item-head,
  .ant-timeline.ant-timeline-right .ant-timeline-item-right .ant-timeline-item-head-custom {
    left: calc(~"100% - 4px - 2px");
  }

  .ant-timeline.ant-timeline-right .ant-timeline-item-right .ant-timeline-item-content {
    width: calc(~"100% - 18px");
  }

  .ant-timeline.ant-timeline-pending .ant-timeline-item-last .ant-timeline-item-tail {
    height: calc(~"100% - 14px");
  }

  .ant-timeline.ant-timeline-reverse .ant-timeline-item-pending .ant-timeline-item-tail {
    height: calc(~"100% - 15px");
  }

  .ant-timeline.ant-timeline-label .ant-timeline-item-label {
    width: calc(~"50% - 12px");
  }

  .ant-timeline.ant-timeline-label .ant-timeline-item-right .ant-timeline-item-label {
    left: calc(~"50% + 14px");
    width: calc(~"50% - 14px");
  }

  .ant-timeline-rtl.ant-timeline.ant-timeline-alternate .ant-timeline-item-left .ant-timeline-item-content,
  .ant-timeline-rtl.ant-timeline.ant-timeline-right .ant-timeline-item-left .ant-timeline-item-content,
  .ant-timeline-rtl.ant-timeline.ant-timeline-label .ant-timeline-item-left .ant-timeline-item-content {
    right: calc(~"50% - 4px");
  }

  .ant-timeline-rtl.ant-timeline.ant-timeline-label .ant-timeline-item-right .ant-timeline-item-label {
    right: calc(~"50% + 14px");
  }

  .ant-upload-list-picture .ant-upload-list-item-progress,
  .ant-upload-list-picture-card .ant-upload-list-item-progress {
    width: calc(~"100% - 24px");
  }

  .ant-upload-list-picture-card .ant-upload-list-item-progress {
    width: calc(~"100% - 14px");
  }
}
