### ISSUE TITLE
CSS has increased specificity in Antd v5

### ISSUE THREAD

**Issue by cant89** [ant-design/ant-design#41044] opened 2023-03-03 11:08 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-d2x6s1?file=/index.js:0-414)

### Steps to reproduce

1. Open devtools and inspect the `aside` with class `ant-layout-sider`
2. Look for the rule containing the property `background: #001529;`
3. See that it is declared as `.ant-layout .ant-layout-sider`

From the following link you cvan see the same Sider from Antd v4:
https://codesandbox.io/s/antd-reproduction-template-forked-jzx4fh?file=/index.js

Repeat the same steps and see that it was declared as  `.ant-layout-sider`.

### What is expected?

I expect the CSS specificity not to change from v4 to v5.
You can see the same behaviour also in other components.
Or at least if you can document it in the migration guide, specifying the components for which specificity is increased.

### What is actually happening?

CSS specificity is changed from v4 to v5.

| Environment | Info |
| --- | --- |
| antd | 5.2.1 |
| React | 17.0.2 |
| System | Mac OS |
| Browser | Chrome |

---
The reason why it is an issue for me is that, when customizing antd components with styled-components, it adds a random class name to the Sider, which with v5 does not have enough specificity. In the example the result is that an override of the background which was working in v4 does not work anymore in v5.

**Comment by Wxh16144** [comment] 2023-03-03 11:48
Duplicate of #40879

**Closed** 2023-03-03 11:53 UTC
Labels: unconfirmed
