### ISSUE TITLE
Ant Design - Upload - customize fileList display

### ISSUE THREAD

**Issue by a3596287** [ant-design/ant-design#24555] opened 2020-05-28 22:29 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6e93z)

### Steps to reproduce
see below

### What is expected?
Sorry, I know this is a usage request, not a but. 

But I can't find any useful resource. Please help.

 I want to customize the fileList display.

Currently, AntD is providing default fileList render, what do I need to do, if I want to render extra <div> element to the fileList?

Any link or training I can do?

Here is the default vs I want to customize picture on StackOverflow:
https://stackoverflow.com/questions/62075539/ant-design-upload-how-to-customize-filelist-display

Thanks

### What is actually happening?
above

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.13.1 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment] 2020-05-29 02:51
Duplicate of #16047

**Closed by afc163** 2020-05-29 02:51 UTC
