### ISSUE TITLE
Button when type="link" href="****",Receive an error warning：Received `false` for a non-boolean attribute `loading`.

### ISSUE THREAD

**Issue by DoubleRayWang** [ant-design/ant-design#18255] opened 2019-08-14 02:42 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-wqppn)

### Steps to reproduce
```jsx
<Button type="link" href='/login'>Login</Button>
```
can see the problem in DevTools

### What is expected?
No error warning

### What is actually happening?
Received `false` for a non-boolean attribute `loading`.

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.8.6 |
| System | win 10 专业版 1903 |
| Browser | Google Chrome 76.0.3809.100 |

**Comment by afc163** [comment] 2019-08-14 02:43
Duplicate of #18205

**Closed by afc163** 2019-08-14 02:43 UTC
