### ISSUE TITLE
RangePicker manual entry date incorrect after pressing enter

### ISSUE THREAD

**Issue by JuraJuki** [ant-design/ant-design#20152] opened 2019-12-09 14:44 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-bxotq)

### Steps to reproduce
Follow the steps in codeSandbox. Click the rangePicker, type dates, press enter. Follow the given note in sandbox.

### What is expected?
The ending date will be wrong

### What is actually happening?
The ending date should be the one typed

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.12.0. |
| System | MacOS Mojave - 10.14.6  |
| Browser |  Google Chrome 78.0.3904.108 (Official Build) (64-bit) |

---
I was doing some cypress learning and accidentally noticed this

**Comment by afc163** [comment] 2019-12-09 15:58
Duplicate of #15353

**Closed by afc163** 2019-12-09 15:58 UTC
