### ISSUE TITLE
@ant-design/icons causes huge app size 

### ISSUE THREAD

**Issue by sunel** [ant-design/ant-design#12349] opened 2018-09-21 07:11 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
All 

### Reproduction link
[https://github.com/ant-design/ant-design/blob/c4b17f23ef7c9ccebb5ea83ccd06f405fe3becce/components/icon/index.tsx#L3](https://github.com/ant-design/ant-design/blob/c4b17f23ef7c9ccebb5ea83ccd06f405fe3becce/components/icon/index.tsx#L3)

### Steps to reproduce
Can this not be tree shake-able 

https://github.com/ant-design/ant-design/blob/c4b17f23ef7c9ccebb5ea83ccd06f405fe3becce/components/icon/index.tsx#L3

Its takes unnecessary size of 500kb for just using Alert component

### What is expected?
tree shake-able  icon

### What is actually happening?
importing all icon if only one is used

**Comment by afc163** [comment] 2018-09-21 07:13
Duplicate of #12011

**Closed by afc163** 2018-09-21 07:13 UTC
