### ISSUE TITLE
React 16.1.1 loading component error

### ISSUE THREAD

**Issue by Coder-JJ** [ant-design/ant-design#8366] opened 2017-11-29 10:11 UTC
### Version
2.13.10

### Environment
Win10、Chrome61、React16.1.1

### Reproduction link
[https://github.com/Coder-JJ/antd-issue.git](https://github.com/Coder-JJ/antd-issue.git)

### Steps to reproduce
```html
<!doctype html>
<html>
<head>
  <link href="./antd.min.css" rel="stylesheet">
</head>
<body>
  <div id='root'></div>
  <script type='text/javascript' src='./react.production.min.js'></script>
  <script type='text/javascript' src='./react-dom.production.min.js'></script>
  <script type='text/javascript' src='./create-react-class.min.js'></script>
  <script type='text/javascript' src='./antd.min.js'></script>
  <script type='text/javascript'>
    const Test = createReactClass({
      componentDidMount () {
        setTimeout(function () {
          // success
          antd.message.loading('test loading 2.')
        }, 1000)
        // failed
        antd.message.loading('test loading 1.')
      },
      render () {
        return React.createElement('div', null, `test loading.`)
      }
    })
    ReactDOM.render(
      React.createElement(Test),
      document.querySelector('#root')
    )
  </script>
</body>
</html>

```

### What is expected?
call message.loading successful in `componentWillMount` or `componentDidMount` method

### What is actually happening?
`Uncaught TypeError: Cannot read property 'add' of null`

**Comment by yesmeck** [comment] 2017-11-29 10:32
Duplicate of #8289, we will support React 16 in antd 3.

**Closed by yesmeck** 2017-11-29 10:32 UTC
