### ISSUE TITLE
TimePicker.RangePicker show table in wrong place if open second field

### ISSUE THREAD

**Issue by gitRacoon** [ant-design/ant-design#38002] opened 2022-10-13 08:16 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/billowing-butterfly-sf4jl9?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

Set start and end time and than open the end field

### What is expected?

Tooltip with time should be under the end time field

### What is actually happening?

Tooltip with time should be under the start time field

| Environment | Info |
| --- | --- |
| antd | 4.23.5 |
| React | "react": "^18.2.0" |
| System | Ubuntu 22 |
| Browser | Google Chrome v106 |

**Comment by janyin** [comment] 2022-10-16 13:12
I think it is maybe related to react18 concurrent rendering.

There is no problem in react@17.0.2. https://codesandbox.io/s/practical-sun-rju6d7?file=/src/index.js

**Comment by gitRacoon** [comment] 2022-10-16 14:29
So are there any plans to adapt to the changes in react 18? or will you wait for react to revert to the previous show method? I believe this is not a react problem, but an innovation that requires changes from antd.

**Comment by janyin** [comment] 2022-10-16 15:59
> So are there any plans to adapt to the changes in react 18? or will you wait for react to revert to the previous show method? I believe this is not a react problem, but an innovation that requires changes from antd.
Certainly it's not react problem, but react18 is breaking change version, especially the rendering.
I don't think all components in ant-design are ready to react18, which need time to update.
By the way, I am not ant-design maintainer.

**Comment by janyin** [comment] 2022-10-16 16:00
> So are there any plans to adapt to the changes in react 18? or will you wait for react to revert to the previous show method? I believe this is not a react problem, but an innovation that requires changes from antd.

Certainly it's not react problem, but react18 is breaking change version, especially the rendering.
I don't think all components in ant-design are ready to react18, which need time to update.
By the way, I am not ant-design maintainer.

**Comment by afc163** [comment] 2022-10-26 08:49
Duplicate of #35247

**Closed by afc163** 2022-10-26 08:49 UTC
