### ISSUE TITLE
From.create<any>() TS Error

### ISSUE THREAD

**Issue by fengqinglingyu** [ant-design/ant-design#16303] opened 2019-04-25 07:50 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/fengqinglingyu/ant-design-tsc](https://github.com/fengqinglingyu/ant-design-tsc)

### Steps to reproduce
npm install
npm run start

### What is expected?
I can compile successfully. I can compile successfully at version 3.16.3, but fail at 3.16.4 or 3.16.5.

### What is actually happening?
```json
{
	"resource": "/Users/ali/tsc-sharing/ts-react-antd/ant-design-tsc/src/component/PersonForm.tsx",
	"owner": "typescript",
	"code": "2344",
	"severity": 8,
	"message": "Type 'PersonForm' does not satisfy the constraint 'FormComponentProps<any>'.\n  Property 'form' is missing in type 'PersonForm' but required in type 'FormComponentProps<any>'.",
	"source": "ts",
	"startLineNumber": 144,
	"startColumn": 28,
	"endLineNumber": 144,
	"endColumn": 38,
	"relatedInformation": [
		{
			"startLineNumber": 159,
			"startColumn": 5,
			"endLineNumber": 159,
			"endColumn": 9,
			"message": "'form' is declared here.",
			"resource": "/Users/ali/tsc-sharing/ts-react-antd/ant-design-tsc/node_modules/antd/lib/form/Form.d.ts"
		}
	]
}  
```
here is error message at VS code

| Environment | Info |
|---|---|
| antd | 3.16.4 |
| React | 16.8.6 |
| System | Macintosh; Intel Mac OS X 10_14_4 |
| Browser | Chrome/74.0.3729.108 |

---
if I lower my version to antd@3.16.3, I can compile successfully, so it's a bug began at antd@3.16.4, and it was be repaired at antd@3.16.5

**Comment by fengqinglingyu** [comment] 2019-04-25 07:53
<a>https://github.com/fengqinglingyu/ant-design-tsc/blob/master/src/component/PersonForm.tsx<a>
at this file

**Comment by zombieJ** [comment] 2019-04-25 08:10
Duplicate of #16303

**Closed by zombieJ** 2019-04-25 08:10 UTC

**Comment by sbusch** [comment] 2019-04-25 12:01
Not of #16303, duplicate of #16284
