### ISSUE TITLE
Descriptions.Item 外层嵌套 HOC 后无法正常显示

### ISSUE THREAD

**Issue by zhangminggeek** [ant-design/ant-design#32245] opened 2021-09-22 03:14 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/editabledescriptions-gn8w6?file=/src/App.tsx)

### Steps to reproduce
1. 引入 antd Descriptions 组件
2. 定义一个 HOC 作为 Descriptions.Item 组件的 wrapper
3. 在 Descriptions 中使用外部引入的 Descriptions.Item 组件

### What is expected?
能正常显示外部引入的 Descriptions.Item 组件

### What is actually happening?
Descriptions 中直接使用 Descriptions.Item 组件能正确显示，使用外部引入的组件无法正确显示

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | macOS |
| Browser | chrome 93.0.4577.63  |

**Comment by afc163** [comment] 2021-09-22 03:54
Duplicate of #4853

**Closed by afc163** 2021-09-22 03:54 UTC
