### ISSUE TITLE
Horizontal menu overflow flickers when specifying a custom width

### ISSUE THREAD

**Issue by m-weeks** [ant-design/ant-design#26908] opened 2020-09-25 16:10 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/thirsty-mahavira-utg3n?file=/src/App.js)

### Steps to reproduce
This totally depends on the width of the menu item, as it appears to only happen at some specific widths.

The simplest reproduction I can find is like so:

```
<Menu mode="horizontal" style={{ width: "200px" }}>
  <Menu.Item>Login</Menu.Item>
  <Menu.Item style={{ width: "100px" }}>Sign Up</Menu.Item>
</Menu>
```

### What is expected?
The menu item should either remain overflowed, or remain visible.

### What is actually happening?
The menu item will flicker between visible and hidden

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.13.1 |
| System | Windows |
| Browser | Chrome 85 |

**Comment by gpetrioli** [comment] 2020-09-26 11:59
This is related to https://github.com/react-component/menu/issues/331

**Comment by afc163** [comment] 2020-09-26 15:15
Duplicate of #26653

**Closed by afc163** 2020-09-26 15:15 UTC
