### ISSUE TITLE
Antd work with react-route error

### ISSUE THREAD

**Issue by qdxkrs** [ant-design/ant-design#11301] opened 2018-07-17 03:43 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
firefox 61

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jno1q93nk3)

### Steps to reproduce
code is simple

### What is expected?
code is simple

### What is actually happening?
You should not use <Link> outside a <Router>

**Comment by yesmeck** [comment] 2018-07-17 03:45
Duplicate of #11292

**Closed by yesmeck** 2018-07-17 03:45 UTC
