### ISSUE TITLE
Inline form on small displays

### ISSUE THREAD

**Issue by controlol** [ant-design/ant-design#45337] opened 2023-10-13 21:23 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antdesign-inline-form-bug-j6pc2g)

### Steps to reproduce

Create Form with layout="inline" and add some Form.Item
Use label in the Form.Item
Set screen width to  +- 500px, at most 576px

### What is expected?

Form items are rendered without overlapping content.

### What is actually happening?

div with class .ant-form-item-row is not expanding to occupy both the label and form input. Instead it only has space for the label. This causes the label of the next form item to overlap with the input of the previous form item.

| Environment | Info |
| --- | --- |
| antd | 5.10.0 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome and Firefox |

---
In the minimal production I am using Input and Checkbox, at least these two components are affected. This makes me believe that the cause is within the Form or Form.Item component. This is probably related to #22009

**Comment by Yuiai01** [comment] 2023-10-13 23:54
Duplicate of https://github.com/ant-design/ant-design/issues/45122

**Closed** 2023-10-17 07:20 UTC
Labels: unconfirmed
