### ISSUE TITLE
RangePicker 将mode设置为 ['month','month'], disabledDate不起作用 

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#20116] opened 2019-12-06 03:11 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/run](https://stackblitz.com/run)

### Steps to reproduce
选择日期，限定了 禁用范围，但是没有效果

### What is expected?
能够禁用

### What is actually happening?
不能禁用

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | latest |
| System | windows10 |
| Browser | chrome78 |

**Comment by XianZhengquan** [comment] 2019-12-06 03:15
额，不知道 stackblitz 怎么分享修改后的项目，代码如下
``` 
import React from 'react';
import ReactDOM from 'react-dom';
import 'antd/dist/antd.css';
import './index.css';
import { DatePicker } from 'antd';
import moment from 'moment'

const { RangePicker } = DatePicker;

class ControlledRangePicker extends React.Component {
  state = {
    mode: ['month', 'month'],
    value: [],
    currentDate:null
  };

  handlePanelChange = (value, mode) => {
    this.setState({
      value,
      mode: [mode[0] === 'date' ? 'month' : mode[0], mode[1] === 'date' ? 'month' : mode[1]],
      currentDate:value[0]
    });
  };

  handleChange = value => {
    this.setState({ value });
  };

  setDisabledDate = cur=>{
    return cur > moment(this.state.currentDate).add(10,'M')
  }

  render() {
    const { value, mode } = this.state;
    return (
      <RangePicker
        placeholder={['Start month', 'End month']}
        format="YYYY-MM"
        disabledDate={this.setDisabledDate}
        value={value}
        mode={mode}
        onChange={this.handleChange}
        onPanelChange={this.handlePanelChange}
      />
    );
  }
}

ReactDOM.render(
  <div>
    <ControlledRangePicker />
  </div>,
  document.getElementById('container'),
);
```

**Comment by afc163** [comment] 2019-12-06 03:26
Duplicate of #9008

**Closed by afc163** 2019-12-06 03:26 UTC

**Comment by XianZhengquan** [comment] 2019-12-06 03:28
@afc163 额，支持了吗？
