### ISSUE TITLE
Expand and Collapse TreeSelect item on click of label

### ISSUE THREAD

**Issue by Sangram9693** [ant-design/ant-design#28634] opened 2020-12-31 09:37 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-6szkf5?file=src/index.js](https://stackblitz.com/edit/react-6szkf5?file=src/index.js)

### Steps to reproduce
1. Click on label (Ex: A or B)

### What is expected?
It should expand and show the child value.

### What is actually happening?
Clicking on label is not showing the child items

| Environment | Info |
|---|---|
| antd | 3.26.20 |
| React | 16.7.0 |
| System | Windows |
| Browser | Chrome |

**Comment by jameslahm** [comment] 2020-12-31 09:45
![image](https://user-images.githubusercontent.com/43805318/103404808-e5a2f280-4b8f-11eb-8b5c-641d0cda9743.png)
Hi, I just try it, and it's normal?

**Comment by Sangram9693** [comment] 2021-01-04 12:04
@jameslahm 
Thank You for reply. 

I think you misunderstood my question, I am facing issue like: when i clicked on label it should expand all child items (Not clicking on icon)

**Comment by jameslahm** [comment] 2021-01-05 07:38
I guess it's expected and it's not a bug. Because the parent node should be selected when it's clicked.

**Comment by Sangram9693** [comment] 2021-01-06 03:20
Yeah, I agree that present node should be selected but i have used selectable={false} in this case it should expand on click of label right ?

**Comment by jameslahm** [comment] 2021-01-06 10:36
I think it's not semantically reasonable. Because the parent node should be selectable or not selectable. And Expanding can be done through clicking the icon.

**Comment by zombieJ** [comment] 2021-01-12 06:52
Duplicate of #27507

**Closed by zombieJ** 2021-01-12 06:52 UTC
