### ISSUE TITLE
Drawer visible 不可控

### ISSUE THREAD

**Issue by jaceyi** [ant-design/ant-design#24807] opened 2020-06-07 12:58 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/umr3b?file=/index.js)

### Steps to reproduce
visible 参数不生效

### What is expected?
期望能打开

### What is actually happening?
期望打不开

| Environment | Info |
|---|---|
| antd | 4.3.2 |
| React | 16.12 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment] 2020-06-07 13:13
Duplicate of #24797

**Closed by afc163** 2020-06-07 13:13 UTC
