### ISSUE TITLE
含选择框的table,当一次显示的数据量较多时,勾选响应速度变慢

### ISSUE THREAD

**Issue by QzAmoy** [ant-design/ant-design#12408] opened 2018-09-26 06:38 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
macOs Mojave;Chrome

### Reproduction link
[https://codepen.io/qzq/pen/NLQrgr](https://codepen.io/qzq/pen/NLQrgr)

### Steps to reproduce
https://codepen.io/qzq/pen/NLQrgr在这个链接中;勾选全部;

### What is expected?
快速响应

### What is actually happening?
响应缓慢,动画卡顿.

**Comment by zombieJ** [comment] 2018-09-26 06:41
考虑过分页吗？

**Comment by QzAmoy** [comment] 2018-09-26 06:44
> 考虑过分页吗？600条一屏幕也放不下呢

分页有考虑,但是在某些场景会需要显示较多数据.

**Comment by QzAmoy** [comment] 2018-09-26 06:45
> 考虑过分页吗？600条一屏幕也放不下呢

还有,就是卡顿并不是从600条开始的,大概300左右就会出现.

**Comment by zombieJ** [comment] 2018-09-26 06:47
ref: https://github.com/react-component/table/pull/231

**Comment by QzAmoy** [comment] 2018-09-29 03:03
> 不要用Badge status="processing"

好的,我试一下.

**Comment by afc163** [comment] 2018-10-07 15:57
trace #3789

**Comment by afc163** [comment] 2019-02-21 15:33
Duplicate of #10431

**Closed by afc163** 2019-02-21 15:33 UTC

**Comment by WangYang-Rex** [comment] 2020-05-20 07:18
> 不要用Badge status="processing"

这个是哪里设置的？
