### ISSUE TITLE
Table Edit Row 

### ISSUE THREAD

**Issue by MicroJes** [ant-design/ant-design#12199] opened 2018-09-11 16:06 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
chrome

### Reproduction link
[https://codepen.io/MicroJes/pen/WgzGeW?editors=1111](https://codepen.io/MicroJes/pen/WgzGeW?editors=1111)

### Steps to reproduce
click edit ，operate current row data，click save.  save data fail.

### What is expected?
save datat success.

### What is actually happening?
save data fail.

---
last colums  add key fixed: 'right'. cause the problem. In fact. I want fixed the last action col fixed right.

**Comment by yesmeck** [comment] 2018-09-11 16:15
Duplicate of #11991

**Closed by yesmeck** 2018-09-11 16:15 UTC
