### ISSUE TITLE
希望Image组件预览可以主动被调用

### ISSUE THREAD

**Issue by zcSkr** [ant-design/ant-design#26736] opened 2020-09-14 08:27 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
使用Image和Upload上传图片时候，可以在onPreview主动调用Image的预览模式来覆盖Upload默认的预览行为

### What does the proposed API look like?
期望像message组件一样可以主动调用，如message.success()等，
例如Image.preview({ src: 'xxxxxxxx' }).就可以实现图片的预览

**Comment by afc163** [comment] 2020-09-14 08:34
Duplicate of #26664

**Closed by afc163** 2020-09-14 08:34 UTC
