### ISSUE TITLE
TextArea with allowClear will trigger autosize action unnormal

### ISSUE THREAD

**Issue by fishenal** [ant-design/ant-design#20195] opened 2019-12-11 09:32 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
TextArea 配合allowclear属性会导致点击缩放的操作只能放大不能缩小

### What is expected?
TextArea 配合allowclear属性会导致点击缩放的操作只能放大不能缩小

### What is actually happening?
TextArea 配合allowclear属性会导致点击缩放的操作只能放大不能缩小

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8.6 |
| System | Win10 |
| Browser | Chrome |

---
TextArea 配合allowclear属性会导致点击缩放的操作只能放大不能缩小

**Comment by afc163** [comment] 2019-12-11 10:23
Duplicate of #19652

**Closed by afc163** 2019-12-11 10:23 UTC
