### ISSUE TITLE
Add a fixed summary at the end of the table to correctly work with a virtual list

### ISSUE THREAD

**Issue by iorabiadopo** [ant-design/ant-design#29591] opened 2021-03-02 13:48 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In the app that I have been working on the user needs the summary of all the data that he received, but sometimes there is just a lot of rows (>5000) and scrolling trough the end to see the total is really bad in ux perspective. From what I have seen there is no way to fix the summary in the same way that the header does. 

### What does the proposed API look like?
```
      <Table
        columns={fixedColumns}
        dataSource={fixedData}
        pagination={false}
        scroll={{ x: 2000 }}
        bordered
        summary={{
          fixed: true,
          data: () => (
            <Table.Summary.Row>
              <Table.Summary.Cell index={0}>Summary</Table.Summary.Cell>
              <Table.Summary.Cell index={1}>
                This is a summary content
              </Table.Summary.Cell>
            </Table.Summary.Row>
          ),
        }}
      />
```

**Comment by afc163** [comment] 2021-03-02 14:09
Duplicate of #25116

**Closed by afc163** 2021-03-02 14:09 UTC
