### ISSUE TITLE
Font Family is not applied consistently

### ISSUE THREAD

**Issue by barreeeiroo** [ant-design/ant-design#39802] opened 2022-12-25 18:59 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-0kx2f7?file=/index.js)

### Steps to reproduce

Try to set a custom font through `ConfigProvider`, and render any of the following components:
- `Typography.Title`
- `Dropdown`
- _Any text rendered without any component._

Note this list of components is just some of the components I found that were broken, there could be more.

### What is expected?

Font Family is applied consistently to all components.

### What is actually happening?

Font Family is getting ignored in some components, and falling back to the default one for each browser.
For reference, Chrome falls back to _Times New Roman_, while Code Sandbox `iframe` falls back to _Sans Serif_.

![image](https://user-images.githubusercontent.com/19251112/209484897-36729b69-e1c4-408e-b28f-8819de0aaa03.png)

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Chrome 108 |

---
_First of all, I couldn't find anything in the documentation regarding this change, so apologies if this is a duplicate or not an issue._

This was working in Ant Design 5.0.3. For reference, compare the sandbox above with this one: https://codesandbox.io/s/antd-reproduction-template-forked-szq3e1?file=/index.js.
As you can see, the code is exactly the same, but the rendering behaviour is different.

Also, attaching these images as well:
- Ant Design 5.0.3: https://imgur.com/a/lGZXaJP
- Ant Design 5.1.0: https://imgur.com/a/byoMseE

In this app, I am not applying any custom font through `ConfigProvider`. Before, in 5.0.3, the font was applied correctly (default is _`-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'`_). However, now in 5.1.0, there is no font at all, so it falls back to Chrome's default (_`Times New Roman`_).

Adding some more information, for example, component `Typography.Title` does not have any `font-family` attribute in the computed section, so it is falling back to the browser's default (which [is inconsistent across multiple devices, even for the same browser](https://granneman.com/webdev/coding/css/fonts-and-formatting/web-browser-font-defaults)):

![image](https://user-images.githubusercontent.com/19251112/209484920-0c7ac454-dac8-4de5-acd9-8a50d2102dee.png)

**Comment by MadCcc** [comment] 2022-12-26 02:36
Currently you can use App to make font-family right. 
Ref: https://ant.design/components/app

Duplicate of https://github.com/ant-design/ant-design/issues/39327#issuecomment-1362483680

**Closed by MadCcc** 2022-12-26 02:36 UTC

**Comment by dizefurkan** [comment] 2023-12-14 12:56
14.12.2023 

I have also facing same issue on iframe.
<img width="550" alt="Screenshot 2023-12-14 at 15 53 44" src="https://github.com/ant-design/ant-design/assets/28892291/7fa4738c-cef3-4375-bf9f-c729138a66f8">
<img width="545" alt="Screenshot 2023-12-14 at 15 53 47" src="https://github.com/ant-design/ant-design/assets/28892291/661522d7-f6ed-4906-a9f4-7c415cc7c3d8">

@barreeeiroo Are you solved your issue?
