### ISSUE TITLE
Accessibility issues

### ISSUE THREAD

**Issue by ojemuyiwa** [ant-design/ant-design#41314] opened 2023-03-17 16:58 UTC
### Reproduction link

[https://ant.design/components/dropdown](https://ant.design/components/dropdown)

### Steps to reproduce

unplug your mouse and tab to any drop-down. Can't get to submenu items on pressing enter or space. These cannot be triggered in jest tests either.

### What is expected?

users without keyboards have accessibility 

### What is actually happening?

Nothing happens

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18.2.0 |
| System | Mac OS Monterey |
| Browser | Chrome version 111.0.5563.64 |

---
Thanks

**Comment by afc163** [comment] 2023-03-19 08:22
Duplicate of #31284

**Closed by afc163** 2023-03-19 08:22 UTC
Labels: unconfirmed
