### ISSUE TITLE
table 全选时会触发 onChange 事件

### ISSUE THREAD

**Issue by Rockcookies** [ant-design/ant-design#12553] opened 2018-10-09 08:27 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
chrom 69.0.3497.100, react 16.5.2

### Reproduction link
[https://codepen.io/rockcookies/pen/gBgvjv](https://codepen.io/rockcookies/pen/gBgvjv)

### Steps to reproduce
同时设置 `rowSelection` 中的 `onChange` 事件和 `table` 组件中 `onChange` 事件，在点击全选时会同时触发两个事件。

### What is expected?
只触发 `rowSelection` 中的 `onChange` 事件

### What is actually happening?
同时触发两个事件

**Comment by zombieJ** [comment] 2018-10-09 09:11
Duplicate of #12532

**Closed by zombieJ** 2018-10-09 09:11 UTC
