### ISSUE TITLE
table with less data still display slidebar on the right

### ISSUE THREAD

**Issue by liuhaoliang** [ant-design/ant-design#20170] opened 2019-12-10 08:55 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/admiring-meadow-v5eki?fontsize=14&hidenavigation=1&theme=dark)

![image](https://user-images.githubusercontent.com/16020037/70514572-e32dbf00-1b6e-11ea-8391-3dd26fe76eb9.png)

### Steps to reproduce
open the link,you can see the slidebar

### What is expected?
less data no slidebar,just like css "overscroll-y: aoto"

### What is actually happening?
overscroll-y: scroll

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | 16.8.6 |
| System | window10 and macos |
| Browser | chrome latest |

---
demo link :  https://codesandbox.io/s/admiring-meadow-v5eki?fontsize=14&hidenavigation=1&theme=dark

**Comment by afc163** [comment] 2019-12-10 11:42
Duplicate of #12088

**Closed by afc163** 2019-12-10 11:42 UTC

**Comment by liuhaoliang** [comment] 2019-12-11 07:04
No Duplicate with #12088.My problem is the right bar

**Comment by afc163** [comment] 2019-12-11 07:17
可以到合并到 #12088 一起讨论，本质上是 scroll.x 和 scroll.y 的增强。

**Comment by liuhaoliang** [comment] 2019-12-11 08:19
好的，明白了，谢谢
