### ISSUE TITLE
addonAfter doesn't work with Input.Search

### ISSUE THREAD

**Issue by fwh1990** [ant-design/ant-design#14787] opened 2019-02-12 02:41 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.example.com](http://www.example.com)

### Steps to reproduce
<Input.Search addonAfter={\<Icon type="close" />} />

### What is expected?
Show the word.

### What is actually happening?
No Element created.

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 6.17.0 |
| System | macos 14 |
| Browser | chrome 70 |

---
I  use the close icon to exit search mode.

**Comment by fwh1990** [comment] 2019-02-12 02:46
Exactly, I have reported this bug 15 days ago. [#14586](https://github.com/ant-design/ant-design/issues/14586)

**Comment by ztplz** [comment] 2019-02-12 03:38
Duplicate of https://github.com/ant-design/ant-design/issues/14785.

**Closed by ztplz** 2019-02-12 03:38 UTC
