### ISSUE TITLE
Can'r set className for "Tabs" Component "more" dropdown

### ISSUE THREAD

**Issue by hallo-yurik** [ant-design/ant-design#34467] opened 2022-03-12 20:04 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I'm using nextjs and styling via module.css. If the width of the tabs decreases, the "more" icon appears. If you hover over it, a dropdown appears. Unfortunately, I can't style this dropdown effectively. I can't set this style this dropdown in the way I want, because it's a child of "body" and there is no direct access to this component. I 

### What does the proposed API look like?
I think the best way to fix this would be to do it as implemented in some other components: to add a prop like "moreDropdownClassName" would easily fix this problem.

**Comment by afc163** [comment] 2022-03-13 07:48
Duplicate of #25844

**Closed by afc163** 2022-03-13 07:48 UTC
