### ISSUE TITLE
Buttons of Modal component style issue

### ISSUE THREAD

**Issue by cslinmiso** [ant-design/ant-design#12268] opened 2018-09-17 08:59 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
Mac OS 10.13.6（17G65）, chrome version 68.0.3440.106 (正式版本) (64 位元)

### Reproduction link
[https://ant.design/components/modal/](https://ant.design/components/modal/)

### Steps to reproduce
- Link to https://ant.design/components/modal/
- Click on any Modal button to launch a modal
- Hover over the button groups or button of Modal

### What is expected?
Button should works without issue and the style has nothing wrong.

### What is actually happening?
While hovering over button, there's a line rendering along with button, the line grows on the times moving over through buttons.

---
Recording：https://www.useloom.com/share/73db555603ce4c5eb6077038195d8ad7

**Comment by zombieJ** [comment] 2018-09-17 09:30
Hmmm... such strange. I can't reproduce of this.
What do you get if inspect this line element?

**Comment by cslinmiso** [comment] 2018-09-17 10:03
> Hmmm... such strange. I can't reproduce of this.
> What do you get if inspect this line element?

@zombieJ Thanks for looking into it. I just tried it on Safari that it works fine, the best bet is that one of my chrome plugins is responsible. 
That being said, I am not able to reproduce it now either after I switch Evernote Clipper off and back on.

I tried to zoom in to 150% on my chrome, and the line goes up to top, and if I zoom out to 110% or so, it goes back to the left. 

FYI, I couldn't inspect the line no matter what at the time.

**Comment by zombieJ** [comment] 2018-09-17 12:31
What if in secure mode of chrome. Can u see it ?

**Comment by cslinmiso** [comment] 2018-09-17 13:29
Not anymore :( I will let you know if I am able to reproduce

**Comment by zombieJ** [comment] 2018-09-17 13:52
Great! Safe to close this issue?

**Comment by cslinmiso** [comment] 2018-09-17 14:01
Yep, that's alright. Thanks a lot for all the effort.

**Closed** 2018-09-17 14:10 UTC
