### ISSUE TITLE
68/5000   Select the component in the IE11 browser Edge document mode, click the box up and down arrow or drag the scroll bar, select the box to hide. Note: IE11 browser Edge document mode.

### ISSUE THREAD

**Issue by tianlang89757** [ant-design/ant-design#9058] opened 2018-01-22 03:08 UTC
### Version
3.1.4

### Environment
Windows7、IE11 Edge document mode、v3.1.4

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
Select the component in the IE11 browser Edge document mode, click the up and down arrow of the selection box, or drag the scroll bar, and select the box to disappear automatically (ps:  Note: IE11 browser Edge document mode.)

### What is expected?
In the IE11 browser Edge document mode, the select component can drag the scrollbar normally.

### What is actually happening?
In the IE11 browser Edge document mode, click the up and down arrow of the selection box, or drag the scroll bar, and select the box to disappear automatically, but in the other mode of IE11 browser, it is normal and can be dragged.

---
 Note: IE11 browser Edge document mode.

**Comment by afc163** [comment] 2018-01-22 03:29
Duplicate of #7934

**Closed by afc163** 2018-01-22 03:29 UTC

**Comment by tianlang89757** [comment] 2018-01-23 03:16
This problem I have solved, the solution is to delete antd.css stylesheet inside .ant-select-dropdown-menu under the overflow: auto style, you can solve the IE11 browser Edge document mode drag the scroll bar selection box Disappear problem
