### ISSUE TITLE
Property 'href' is missing in type {...} for Button

### ISSUE THREAD

**Issue by b-fett** [ant-design/ant-design#15726] opened 2019-03-28 13:32 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-ts-it9tfo?file=Hello.tsx](https://stackblitz.com/edit/react-ts-it9tfo?file=Hello.tsx)

### Steps to reproduce
place button component with any `type` property

### What is expected?
no typescript compilation error

### What is actually happening?
typescript compilation error

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.6 |
| System | Linux 4.19.30-1 |
| Browser | Chrome 73 |

**Comment by yesmeck** [comment] 2019-03-28 13:33
Duplicate of #15700

**Closed by yesmeck** 2019-03-28 13:33 UTC
