### ISSUE TITLE
Using <Modal> component results in "findDOMNode is deprecated in StrictMode" warning

### ISSUE THREAD

**Issue by jatu-studiobox** [ant-design/ant-design#28702] opened 2021-01-05 21:11 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/jatu-studiobox/samplestore](https://github.com/jatu-studiobox/samplestore)

### Steps to reproduce
1. install dependencies (npm i)
2. run app (npm start)
3. check console

### What is expected?
No warnings should be displayed.

### What is actually happening?
A warning message will appear in console.log stating "Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Wave which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here:  https://reactjs.org/link/strict-mode-find-node

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Microsoft Edge 87.0.664.66 |

**Comment by afc163** [comment] 2021-01-06 07:59
Duplicate of #27921

**Closed by afc163** 2021-01-06 07:59 UTC
