### ISSUE TITLE
React does not recognize the `scrollLocker` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `scrolllocker` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### ISSUE THREAD

**Issue by 123456wjw** [ant-design/ant-design#28693] opened 2021-01-05 07:47 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[localhost:8080](localhost:8080)

### Steps to reproduce
drawer划出之后drawer组件上添加了scrollLocker属性  并且不会盖住浏览器的滚动条

### What is expected?
drawer组件上去除scrollLocker属性  并且盖住浏览器的滚动条

### What is actually happening?
drawer组件上添加了scrollLocker属性  并且不会盖住浏览器的滚动条

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | react 16.8.6 |
| System | windows 64 |
| Browser | 谷歌 87.0.4280.88 |

**Comment by shaodahong** [comment] 2021-01-05 08:48
Duplicate of https://github.com/ant-design/ant-design/issues/28391

**Closed by shaodahong** 2021-01-05 08:48 UTC

**Comment by 123456wjw** [comment] 2021-01-06 01:15
> Duplicate of #28391

don't work

**Comment by shaodahong** [comment] 2021-01-06 02:01
Yep, waiting release

**Comment by iHanyuLee** [comment] 2021-03-17 03:41
I met the same problem
