### ISSUE TITLE
When the table has no data, if the number of columns is large, can you add horizontal scrolling to the header?

### ISSUE THREAD

**Issue by dongyang19931108** [ant-design/ant-design#17456] opened 2019-07-04 03:50 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When the column filter condition is not filtered, the header cannot be swam horizontally. If the filter column needs to be swiped outside the visible area, it can no longer be selected.

### What does the proposed API look like?
When there is no data in the table, if the number of columns is large, and the condition that the table has no data exists in the header, the header is added horizontally.

**Comment by afc163** [comment] 2019-07-04 06:01
Duplicate of #10490

**Closed by afc163** 2019-07-04 06:01 UTC
