### ISSUE TITLE
ant-design Tree组件-拖动示例代码片段问题

### ISSUE THREAD

**Issue by Ivan-hl** [ant-design/ant-design#46767] opened 2024-01-03 06:20 UTC
### Reproduction link

[https://ant-design.antgroup.com/components/tree-cn#components-tree-demo-draggable](https://ant-design.antgroup.com/components/tree-cn#components-tree-demo-draggable)

### Steps to reproduce

else if (
      ((info.node as any).props.children || []).length > 0 && // Has children
      (info.node as any).props.expanded && // Is expanded
      dropPosition === 1 // On the bottom gap
    ) 

经测试，在整个拖动示例的handleDrop函数中，上面的判断条件从未生效过。

info.node?.props中是否确定有children属性？

实际打印info.node.props结果没有children属性，这个children存在于info.props.data.children，请问demo代码片段是否存在错误？

如果不存在错误，请问此处的触发条件是什么操作

### What is expected?

else if (
      ((info.node as any).props.children || []).length > 0 && // Has children
      (info.node as any).props.expanded && // Is expanded
      dropPosition === 1 // On the bottom gap
    ) 
能够触发

### What is actually happening?

else if (
      ((info.node as any).props.children || []).length > 0 && // Has children
      (info.node as any).props.expanded && // Is expanded
      dropPosition === 1 // On the bottom gap
    ) 
从未触发

| Environment | Info |
| --- | --- |
| antd | 5.12.7 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome 111 |

**Comment by afc163** [comment] 2024-01-03 06:21
Duplicate of https://github.com/ant-design/ant-design/issues/45684

**Closed by afc163** 2024-01-03 06:21 UTC
Labels: unconfirmed
