### ISSUE TITLE
Nextjs static site generation extremely slow when using Typography

### ISSUE THREAD

**Issue by Sheap** [ant-design/ant-design#48788] opened 2024-05-06 08:36 UTC
### Reproduction link

[https://github.com/Sheap/antd-next-bug](https://github.com/Sheap/antd-next-bug)

### Steps to reproduce

```
pnpm install
pnpm build
```

### What is expected?

It should build as quickly as when Typography is not used (<1s)

### What is actually happening?

It takes ~10 minutes for the initial build attempt to time out. then the subsequent attempt succeeds quickly.
```
Generating static pages (0/4) ...
⚠ Sending SIGTERM signal to static worker due to timeout of 60 seconds. Subsequent errors may be a result of the worker exiting.
⚠ Restarted static page generation for /documentSearch because it took more than 60 seconds
⚠ See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
⚠ Restarted static page generation for / because it took more than 60 seconds
⚠ Restarted static page generation for /404 because it took more than 60 seconds
⚠ Restarted static page generation for /500 because it took more than 60 seconds
Generating static pages (1/4) 
Generating static pages (2/4) 
Generating static pages (3/4) 
✓ Generating static pages (4/4) 
```

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | 18 |
| System | fedora 39 |
| Browser | NA |

---
I have the same issue on my gitlab CI pipeline (which builds in an alpine container), suggesting it is not a system specific issue.

I have the same issue when using the page router, suggesting it is not related to the relatively new nextjs app router.

**Comment by afc163** [comment] 2024-05-06 08:40
Duplicate of #48758

**Closed by afc163** 2024-05-06 08:40 UTC
Labels: unconfirmed
