### ISSUE TITLE
Dropdown onVisibleChange event won't be trigger when open new window with target '_blank'.

### ISSUE THREAD

**Issue by narrowizard** [ant-design/ant-design#12511] opened 2018-10-04 01:21 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
Google Chrome 69.0.3497.100 x64

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n15l0w85q0)

### Steps to reproduce
1. hover the dropdown menu.
1. click any menu item.(it will open a new window)
1. return to origin page, and you will find that the dropdown menu is fold, but onVisibleChange was not triggerred with 'visible:false'.

### What is expected?
onVisibleChange should be triggerred when the dropdown menu going to fold.

### What is actually happening?
onVisibleChange was not triggerred when dropdown menu folding.

**Comment by zombieJ** [comment] 2018-10-08 06:10
Duplicate of #4994

**Closed by zombieJ** 2018-10-08 06:10 UTC
