### ISSUE TITLE
Add Close Icon Position for Drawer

### ISSUE THREAD

**Issue by Sarthak-ONS** [ant-design/ant-design#51230] opened 2024-10-14 06:23 UTC
### What problem does this feature solve?

By default, close icon in drawer is aligned on left of header, we need a feature to change the icon position to right or left.

### What does the proposed API look like?

We can pass props named closeIconPosition to Drawer Component, and change the insets from left ro right

**Comment by afc163** [comment] 2024-10-14 06:35
Duplicate of https://github.com/ant-design/ant-design/issues/35776

**Closed by afc163** 2024-10-14 06:35 UTC
Labels: unconfirmed
