### ISSUE TITLE
Ant Design table scroll not working inside the tabs content

### ISSUE THREAD

**Issue by agallio** [ant-design/ant-design#11726] opened 2018-08-13 07:07 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.1

### Environment
Windows 10 Pro v1803 / Chrome Latest

### Reproduction link
[https://ant.design/components/table/#header](https://ant.design/components/table/#header)

### Steps to reproduce
1. Create a tabs
2. Inside the tabs content, create a table
3. Inside the table add scroll={{}} attrib
4. Can't be scrolled!

### What is expected?
Scrollable Table inside the Tabs component

### What is actually happening?
Table can't be scrolled!

**Comment by yesmeck** [comment] 2018-08-13 07:39
Duplicate of #11621

**Closed by yesmeck** 2018-08-13 07:39 UTC
