### ISSUE TITLE
Input/TextArea: showCount and maxLength are inconsistent when type emoji

### ISSUE THREAD

**Issue by archisketch-thangly** [ant-design/ant-design#44636] opened 2023-09-05 09:18 UTC
### Reproduction link

[https://stackblitz.com/edit/react-kwdl7e](https://stackblitz.com/edit/react-kwdl7e)

### Steps to reproduce

 Enter emoji into the input and observe showCount and maxLength

### What is expected?

 showCount and maxLength must work consistently with each other

### What is actually happening?

 When I type with emoji showCount and maxLength are inconsistent

| Environment | Info |
| --- | --- |
| antd | 5.8.6 |
| React | 18.2.0 |
| System | Macbook Air M1 2020 - macOS 13.3.1 |
| Browser | Chrome 112.0.5615.137 |

**Comment by afc163** [comment] 2023-09-06 08:28
Duplicate of #37733

**Closed by afc163** 2023-09-06 08:28 UTC
Labels: unconfirmed
