### ISSUE TITLE
DatePicker and TimePicker isn't responsive on mobile browser

### ISSUE THREAD

**Issue by yuenzp** [ant-design/ant-design#36631] opened 2022-07-21 04:07 UTC
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/datepicker-timepicker-doesnt-responsive-on-mobile-browser-rmm7xd)

### Steps to reproduce

Step 1: Toggle codesandbox's browser responsive preview.
![image](https://user-images.githubusercontent.com/60993756/180127977-9a8a3820-f1a8-475c-a4e1-3336e1f32ce6.png)

Step 2: Click on the Date Picker.

### What is expected?

The DatePicker & TimePicker overflow due to none responsive.

### What is actually happening?

The DatePicker & TimePicker overflow due to none responsive.
![image](https://user-images.githubusercontent.com/60993756/180128093-58fc1c0e-108a-42da-8d6c-40b7f0680d4a.png)

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 18.2 |
| System | Android |
| Browser | Chrome |

---
Please fix this problem as soon as possible, I saw this issues mentioned on year 2018 and currently already year 2022 still not fixed.

**Comment by afc163** [comment] 2022-07-21 04:09
Duplicate of #26758

**Closed by afc163** 2022-07-21 04:09 UTC
