### ISSUE TITLE
InputNumber should return normalized number when onChange triggers

### ISSUE THREAD

**Issue by Artoria-0x04** [ant-design/ant-design#32193] opened 2021-09-16 03:23 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://codesandbox.io/s/input-number-onenter-t9obe?file=/App.tsx

When set as controlled input, you will get both unnormalized and normalized values from `onChange`, which is incorrect behavior.

Besides, the current implementation doesn't support onEnter submit in form and output float when `precicion={0}`. This change will support form usage naturally.

### What does the proposed API look like?
Return normalized number when onChange triggers, e.g. when `precision={0}`

**Comment by zombieJ** [comment] 2021-09-16 06:01
Duplicate of #32140

就如 https://github.com/ant-design/ant-design/issues/32140#issuecomment-917964769  所提，`onChange` 返回输入内容是受控需求。如果只返回正确值则用户无法再输入。改变该行为是 breaking chage。我先关掉这个 issue，重启 #32140 好了。

**Closed by zombieJ** 2021-09-16 06:01 UTC

**Comment by Artoria-0x04** [comment] 2021-09-16 09:04
明白了，之前忘了考虑受控的情况。
类似设置了 maxLength 的时候，达到限制条件就会改变输入反馈，尽管不能再输入更多数字，但该行为其实没问题。简单考虑了一下，尽管是个 breaking change，但受影响的 case 应该只是极小部分。
不管怎么说，感谢实现了该功能。
