### ISSUE TITLE
Table add an option to only sort by ascending and descending

### ISSUE THREAD

**Issue by violabg** [ant-design/ant-design#16747] opened 2019-05-23 07:32 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Right now, when you click the sorting button on a Table's column, you have three states, ascending, descending and false.
While I found this behaviour correct and useful, to some users this is confusing because they are used to only have two states, ascending and descending.

### What does the proposed API look like?
add an option to bypass the false state.

**Comment by zombieJ** [comment] 2019-05-23 15:16
It's by design. But you can still use control mode to handle this: https://github.com/ant-design/ant-design/issues/15415#issuecomment-491173425

Duplicate of #15415

**Closed by zombieJ** 2019-05-23 15:16 UTC

**Comment by mikhelev** [comment] 2020-04-10 14:15
I have good hack for this:
set sortDirections={["ascend", "descend", "ascend"]} for Table =)

**Comment by cesarnml** [comment] 2020-04-30 03:13
> I have good hack for this:
> set sortDirections={["ascend", "descend", "ascend"]} for Table =)

🙏 ⭐ 🎉
